
/* =====================================================================
   Banco FUVEST (Física) — questões ORIGINAIS no estilo da 1ª fase.
   Não são cópias de provas oficiais. Use g = 10 m/s² quando indicado.
   ===================================================================== */
const FUVQ=[
{id:'ff01',area:'Cinemática',tags:['muv','conv'],
 q:'Um carro trafega a 72 km/h e freia com desaceleração constante, parando após percorrer 40 m. O módulo da desaceleração é',
 alts:['0,5 m/s²','2,5 m/s²','5 m/s²','10 m/s²','64,8 m/s²'],ans:2,
 why:['0,5 m/s²: dividiu 20 por 40.','2,5 m/s²: usou v²/(4d).','','10 m/s²: esqueceu o fator 2 de Torricelli (v² = 2·a·d).','64,8 m/s²: não converteu 72 km/h para m/s (72² / 80).'],
 steps:['Converta: 72 km/h ÷ 3,6 = 20 m/s.','Torricelli com v final = 0: 0 = 20² − 2·a·40.','400 = 80·a.','a = 5 m/s².'],
 trap:['Use 72 km/h diretamente: a = 72²/(2·40).','Torricelli: 0 = 20² − a·40, logo a = 10 m/s².']},
{id:'ff02',area:'Queda livre',tags:['queda'],
 q:'Uma pedra é abandonada do alto de um prédio e atinge o solo 3 s depois. Desprezando a resistência do ar (g = 10 m/s²), a altura do prédio e a velocidade da pedra ao atingir o solo são, respectivamente,',
 alts:['45 m e 30 m/s','90 m e 30 m/s','45 m e 15 m/s','30 m e 45 m/s','15 m e 30 m/s'],ans:0,
 why:['','90 m: usou h = g·t² (faltou dividir por 2).','15 m/s: calculou a velocidade média (45/3), não a final.','Trocou os valores de altura e velocidade.','15 m: usou h = g·t/2.'],
 steps:['Queda livre a partir do repouso: h = g·t²/2.','h = 10·9/2 = 45 m.','v = g·t = 10·3.','v = 30 m/s.'],
 trap:['h = g·t² = 90 m.','v = h/t = 15 m/s.']},
{id:'ff03',area:'Dinâmica',tags:['atrito','newton'],
 q:'Um bloco de 5 kg, sobre uma superfície horizontal, é puxado por uma força horizontal de 30 N. O coeficiente de atrito cinético é 0,2 (g = 10 m/s²). A aceleração do bloco é',
 alts:['2 m/s²','4 m/s²','4,8 m/s²','6 m/s²','8 m/s²'],ans:1,
 why:['2 m/s²: errou o atrito (usou 20 N).','','4,8 m/s²: calculou o atrito como μ·F = 6 N, mas o atrito depende da normal.','6 m/s²: ignorou o atrito.','8 m/s²: somou o atrito à força, mas ele se opõe ao movimento.'],
 steps:['Normal: N = m·g = 50 N.','Atrito: F<sub>at</sub> = μ·N = 0,2·50 = 10 N.','Resultante: 30 − 10 = 20 N.','a = F<sub>R</sub>/m = 20/5 = 4 m/s².'],
 trap:['Atrito: F<sub>at</sub> = μ·F = 0,2·30 = 6 N.','Resultante: 30 + 10 = 40 N.']},
{id:'ff04',area:'Energia',tags:['ener'],
 q:'Um carrinho parte do repouso de uma altura de 5 m numa montanha-russa sem atrito (g = 10 m/s²). Sua velocidade quando ele passa por um ponto a 1,8 m de altura é',
 alts:['4 m/s','6 m/s','8 m/s','10 m/s','64 m/s'],ans:2,
 why:['4 m/s: usou o desnível errado.','6 m/s = √(2·10·1,8): usou a altura do ponto, não a queda de altura.','','10 m/s = √(2·10·5): calculou a velocidade no nível do chão.','64 m/s: esqueceu a raiz quadrada (v² = 64).'],
 steps:['Conservação da energia: m·g·h₁ = m·g·h₂ + m·v²/2.','v² = 2·g·(h₁ − h₂) = 2·10·(5 − 1,8).','v² = 64.','v = 8 m/s.'],
 trap:['v² = 2·g·h₂ = 2·10·1,8 = 36.','v = v² = 64 m/s.']},
{id:'ff05',area:'Quantidade de movimento',tags:['momento','ener'],
 q:'Um vagão de 2 t, a 6 m/s, colide com outro vagão de 1 t em repouso, e eles seguem acoplados. A velocidade após o choque e a energia cinética dissipada são, respectivamente,',
 alts:['4 m/s e 12 kJ','4 m/s e 0','6 m/s e 0','3 m/s e 22,5 kJ','2 m/s e 30 kJ'],ans:0,
 why:['','A energia cinética não se conserva em colisões perfeitamente inelásticas.','A velocidade diminui: a mesma quantidade de movimento é dividida por uma massa maior.','3 m/s: dividiu a velocidade por 2, como se as massas fossem iguais.','2 m/s: inverteu as massas (1 t · 6 / 3 t).'],
 steps:['Conservação da quantidade de movimento: 2000·6 = 3000·v.','v = 4 m/s.','E<sub>c</sub> antes = ½·2000·6² = 36 kJ; depois = ½·3000·4² = 24 kJ.','Energia dissipada: 36 − 24 = 12 kJ.'],
 trap:['A energia cinética se conserva, logo nada é dissipado.','2000·6 = 1000·v, logo v = 12 m/s.']},
{id:'ff06',area:'Gravitação',tags:['grav'],
 q:'Um satélite passa de uma órbita de raio R para outra de raio 2R (medidos a partir do centro da Terra). A força gravitacional que a Terra exerce sobre ele fica',
 alts:['2 vezes maior','igual','2 vezes menor','4 vezes menor','8 vezes menor'],ans:3,
 why:['Aumentar a distância diminui a força.','A força depende da distância.','2 vezes menor: esqueceu que a força depende do quadrado da distância.','','8 vezes menor: usou o cubo da distância (confundiu com a 3ª lei de Kepler).'],
 steps:['F = G·M·m/d².','Com d → 2d: F′ = G·M·m/(2d)².','F′ = F/4: a força fica 4 vezes menor.'],
 trap:['F é proporcional a 1/d, logo fica 2 vezes menor.','F′ = G·M·m/(2d³).']},
{id:'ff07',area:'Hidrostática',tags:['hidro'],
 q:'Um objeto de 2 kg e volume 0,5 L, totalmente submerso em água (densidade 1 g/cm³), está preso a um dinamômetro. Com g = 10 m/s², a leitura do dinamômetro é',
 alts:['5 N','15 N','19,5 N','20 N','25 N'],ans:1,
 why:['5 N é o empuxo, não a leitura.','','19,5 N: calculou o empuxo com o volume em m³ errado.','20 N é o peso: ignorou o empuxo.','25 N: somou o empuxo ao peso, mas ele aponta para cima.'],
 steps:['Peso: P = m·g = 20 N.','Volume: 0,5 L = 5 × 10⁻⁴ m³.','Empuxo: E = d·V·g = 1000 · 5 × 10⁻⁴ · 10 = 5 N.','Leitura (peso aparente): 20 − 5 = 15 N.'],
 trap:['Leitura: P + E = 25 N.','Volume: 0,5 L = 0,5 m³.']},
{id:'ff08',area:'Calorimetria',tags:['calor'],
 q:'Misturam-se 200 g de água a 80 °C com 300 g de água a 20 °C, sem perdas de calor. A temperatura de equilíbrio é',
 alts:['32 °C','44 °C','50 °C','56 °C','60 °C'],ans:1,
 why:['32 °C: errou o cálculo da média ponderada.','','50 °C é a média simples: ignorou que as massas são diferentes.','56 °C: trocou as massas (200 g a 20 °C e 300 g a 80 °C).','60 °C: somou metade das temperaturas.'],
 steps:['Calor cedido + calor recebido = 0.','200·1·(T − 80) + 300·1·(T − 20) = 0.','500T = 16 000 + 6 000 = 22 000.','T = 44 °C.'],
 trap:['T = (80 + 20)/2 = 50 °C.','500T = 200·20 + 300·80.']},
{id:'ff09',area:'Gases',tags:['gases','term'],
 q:'Um gás ideal em recipiente rígido está a 27 °C e 2 atm. Aquecido até 177 °C, sua pressão passa a ser',
 alts:['1,33 atm','2 atm','3 atm','4 atm','13,1 atm'],ans:2,
 why:['1,33 atm: inverteu a razão das temperaturas.','Com volume constante, a pressão varia com a temperatura.','','4 atm: dobrou a pressão sem calcular a razão das temperaturas.','13,1 atm: usou Celsius (2·177/27) — nas leis dos gases a temperatura é sempre em kelvin.'],
 steps:['Volume constante: p/T = constante (T em kelvin).','T₁ = 27 + 273 = 300 K; T₂ = 177 + 273 = 450 K.','p₂ = 2 · 450/300.','p₂ = 3 atm.'],
 trap:['p₂ = 2 · 177/27 ≈ 13,1 atm.','p₂ = 2 · 300/450 ≈ 1,33 atm.']},
{id:'ff10',area:'Termodinâmica',tags:['termo','term'],
 q:'Uma máquina de Carnot opera entre as temperaturas de 527 °C e 127 °C. Seu rendimento é',
 alts:['24%','25%','50%','75,9%','100%'],ans:2,
 why:['24%: dividiu a diferença pela soma das temperaturas.','25%: usou 1 − 600/800 com temperaturas erradas.','','75,9%: usou Celsius (1 − 127/527); o rendimento de Carnot exige kelvin.','Nenhuma máquina térmica atinge 100% (2ª lei).'],
 steps:['Converta: T<sub>q</sub> = 800 K e T<sub>f</sub> = 400 K.','η = 1 − T<sub>f</sub>/T<sub>q</sub>.','η = 1 − 400/800 = 0,5.','η = 50%.'],
 trap:['η = 1 − 127/527 ≈ 75,9%.','Converta: T(K) = T(°C) − 273.']},
{id:'ff11',area:'Ondas',tags:['ondas'],
 q:'Um som de 680 Hz, que se propaga no ar a 340 m/s, passa para a água, onde se propaga a 1 480 m/s. Na água, sua frequência e seu comprimento de onda são, aproximadamente,',
 alts:['680 Hz e 0,5 m','680 Hz e 2,2 m','2 960 Hz e 0,5 m','2 960 Hz e 2,2 m','156 Hz e 2,2 m'],ans:1,
 why:['0,5 m é o comprimento de onda no ar; ao mudar de meio, λ muda.','','Manteve λ = 0,5 m e mudou a frequência — é o contrário: a frequência é da fonte e não muda.','A frequência não muda na refração.','156 Hz: dividiu a frequência pela razão das velocidades.'],
 steps:['Na mudança de meio, a frequência (definida pela fonte) não se altera: f = 680 Hz.','A velocidade muda: v = 1 480 m/s.','λ = v/f = 1 480/680.','λ ≈ 2,2 m.'],
 trap:['Na mudança de meio, o comprimento de onda não se altera: λ = 0,5 m.','f = 1 480/0,5 = 2 960 Hz.']},
{id:'ff12',area:'Óptica',tags:['optica'],
 q:'Um objeto está a 30 cm de uma lente convergente de distância focal 10 cm. A imagem formada é',
 alts:['real, invertida, a 15 cm da lente e com metade do tamanho do objeto','virtual, direita, a 15 cm da lente e com metade do tamanho','real, invertida, a 7,5 cm da lente','real, invertida, a 15 cm da lente e com o dobro do tamanho','real, invertida, a 20 cm da lente'],ans:0,
 why:['','Objeto além do foco de lente convergente gera imagem real e invertida.','7,5 cm: somou 1/10 + 1/30 em vez de subtrair.','Dobro do tamanho: usou A = −p/p′ (invertido).','20 cm = 30 − 10: subtraiu as distâncias.'],
 steps:['Gauss: 1/f = 1/p + 1/p′ ⇒ 1/p′ = 1/10 − 1/30.','1/p′ = 2/30, logo p′ = 15 cm (positivo: imagem real).','Aumento: A = −p′/p = −15/30 = −1/2.','A imagem é real, invertida (A < 0) e com metade do tamanho.'],
 trap:['1/p′ = 1/10 + 1/30, logo p′ = 7,5 cm.','Aumento: A = −p/p′ = −2 (dobro do tamanho).']},
{id:'ff13',area:'Circuitos',tags:['assoc','ohm'],
 q:'Duas lâmpadas iguais de 6 Ω são ligadas em paralelo, e o conjunto é ligado em série com um resistor de 3 Ω a uma bateria ideal de 12 V. A corrente em cada lâmpada é',
 alts:['0,5 A','0,8 A','1 A','2 A','4 A'],ans:2,
 why:['0,5 A: dividiu a corrente por 2 duas vezes.','0,8 A = 12/15: tratou tudo como série.','','2 A é a corrente total, que se divide entre as duas lâmpadas.','4 A = 12/3: considerou só o resistor de 3 Ω.'],
 steps:['Lâmpadas em paralelo: 6·6/(6 + 6) = 3 Ω.','Resistência equivalente total: 3 + 3 = 6 Ω.','Corrente total: i = 12/6 = 2 A.','Cada lâmpada (iguais, em paralelo) recebe 2/2 = 1 A.'],
 trap:['Tudo em série: R = 6 + 6 + 3 = 15 Ω.','Cada lâmpada recebe a corrente total de 2 A.']},
{id:'ff14',area:'Energia elétrica',tags:['potel'],
 q:'Um chuveiro de 5 400 W é usado 20 minutos por dia durante 30 dias. Com a tarifa de R$ 0,80 por kWh, o consumo mensal e o custo são',
 alts:['54 kWh e R$ 43,20','54 kWh e R$ 67,50','1,8 kWh e R$ 1,44','162 kWh e R$ 129,60','3 240 kWh e R$ 2 592,00'],ans:0,
 why:['','R$ 67,50 = 54/0,8: dividiu pela tarifa em vez de multiplicar.','1,8 kWh é o consumo de um único dia.','162 kWh: usou 1 hora por dia em vez de 20 minutos.','3 240 kWh: usou 20 minutos como se fossem horas.'],
 steps:['Potência: 5 400 W = 5,4 kW; tempo diário: 20 min = 1/3 h.','Consumo diário: 5,4 · 1/3 = 1,8 kWh.','Consumo mensal: 1,8 · 30 = 54 kWh.','Custo: 54 · 0,80 = R$ 43,20.'],
 trap:['Consumo mensal: 5,4 · 20 · 30 = 3 240 kWh.','Custo: 54 ÷ 0,80 = R$ 67,50.']},
{id:'ff15',area:'Eletrostática',tags:['carga'],
 q:'Duas cargas puntiformes se repelem com uma força de módulo F. Se uma das cargas for dobrada e a distância entre elas também for dobrada, a nova força terá módulo',
 alts:['F/4','F/2','F','2F','4F'],ans:1,
 why:['F/4: considerou só o efeito da distância.','','F: achou que dobrar a carga e a distância se compensam.','2F: considerou só o efeito da carga.','4F: inverteu o efeito da distância.'],
 steps:['Coulomb: F = k·Q₁·Q₂/d².','Novo valor: F′ = k·(2Q₁)·Q₂/(2d)².','F′ = 2/4 · F.','F′ = F/2.'],
 trap:['F′ = k·(2Q₁)·Q₂/(2d) = F.','A distância entra ao cubo: F′ = 2F/8.']},
{id:'ff16',area:'Eletromagnetismo',tags:['indu'],
 q:'Um transformador ideal reduz a tensão de 120 V para 12 V. O secundário tem 50 espiras e fornece 2 A. O número de espiras do primário e a corrente no primário são, respectivamente,',
 alts:['500 e 0,2 A','500 e 20 A','5 e 20 A','50 e 2 A','5 000 e 0,02 A'],ans:0,
 why:['','20 A: a corrente no primário é menor, pois a potência se conserva e a tensão é maior.','5 espiras: inverteu a razão de transformação.','50 e 2 A: não aplicou a relação de transformação.','5 000: usou a razão 100 em vez de 10.'],
 steps:['U<sub>p</sub>/U<sub>s</sub> = N<sub>p</sub>/N<sub>s</sub> ⇒ 120/12 = N<sub>p</sub>/50.','N<sub>p</sub> = 500 espiras.','Transformador ideal: U<sub>p</sub>·i<sub>p</sub> = U<sub>s</sub>·i<sub>s</sub> ⇒ 120·i<sub>p</sub> = 12·2.','i<sub>p</sub> = 0,2 A.'],
 trap:['U<sub>p</sub>/U<sub>s</sub> = N<sub>s</sub>/N<sub>p</sub> ⇒ N<sub>p</sub> = 5.','i<sub>p</sub>/i<sub>s</sub> = N<sub>p</sub>/N<sub>s</sub> ⇒ i<sub>p</sub> = 20 A.']},
{id:'ff17',area:'Física moderna',tags:['moderna'],
 q:'Luz de frequência 1,0 × 10¹⁵ Hz incide sobre um metal cuja função trabalho é 2,6 eV. Sendo h = 4,1 × 10⁻¹⁵ eV·s, a energia cinética máxima dos elétrons emitidos é',
 alts:['0 (não há emissão)','1,5 eV','2,6 eV','4,1 eV','6,7 eV'],ans:1,
 why:['Há emissão, pois a energia do fóton (4,1 eV) supera a função trabalho.','','2,6 eV é a função trabalho, não a energia cinética.','4,1 eV é a energia do fóton: esqueceu de descontar a função trabalho.','6,7 eV: somou a função trabalho em vez de subtrair.'],
 steps:['Energia do fóton: E = h·f = 4,1 × 10⁻¹⁵ · 1,0 × 10¹⁵ = 4,1 eV.','Einstein: E<sub>c,máx</sub> = h·f − φ.','E<sub>c,máx</sub> = 4,1 − 2,6.','E<sub>c,máx</sub> = 1,5 eV.'],
 trap:['E<sub>c,máx</sub> = h·f + φ = 6,7 eV.','A energia cinética depende da intensidade da luz, não da frequência.']},
{id:'ff18',area:'Movimento circular',tags:['mcu'],
 q:'Um ciclista percorre uma pista circular de raio 50 m com velocidade de módulo constante igual a 10 m/s. Sua aceleração tem módulo',
 alts:['zero, pois a velocidade é constante','0,2 m/s², apontando para o centro','2 m/s², apontando para o centro','2 m/s², tangente à pista','500 m/s², apontando para fora'],ans:2,
 why:['Só o módulo é constante; a direção da velocidade muda, então há aceleração.','0,2 m/s² = 10/50: usou v/R em vez de v²/R.','','A aceleração centrípeta aponta para o centro, não na direção tangente.','500 m/s² = v·R: multiplicou em vez de dividir; e o sentido é para o centro.'],
 steps:['No MCU a velocidade muda de direção: existe aceleração centrípeta.','a<sub>c</sub> = v²/R = 10²/50.','a<sub>c</sub> = 2 m/s².','Ela aponta para o centro da curva.'],
 trap:['Velocidade constante ⇒ aceleração nula.','a<sub>c</sub> = v/R = 0,2 m/s².']},
{id:'ff19',area:'Plano inclinado',tags:['plano','newton'],
 q:'Um bloco de 4 kg sobe um plano inclinado sem atrito (sen θ = 0,6 e cos θ = 0,8), puxado por uma força de 30 N paralela ao plano (g = 10 m/s²). A aceleração do bloco é',
 alts:['0,5 m/s², descendo','1,5 m/s², subindo','6 m/s², descendo','7,5 m/s², subindo','13,5 m/s², subindo'],ans:1,
 why:['Usou cos θ na componente paralela do peso (32 N), que deve usar sen θ.','','6 m/s² = g·sen θ: ignorou a força de 30 N.','7,5 m/s² = 30/4: ignorou a componente do peso.','13,5 m/s²: somou a componente do peso, que na verdade se opõe à subida.'],
 steps:['Componente do peso ao longo do plano: P<sub>x</sub> = m·g·sen θ = 4·10·0,6 = 24 N.','Resultante ao longo do plano: 30 − 24 = 6 N (para cima).','a = F<sub>R</sub>/m = 6/4.','a = 1,5 m/s², subindo.'],
 trap:['P<sub>x</sub> = m·g·cos θ = 32 N.','Resultante: 30 + 24 = 54 N.']},
{id:'ff20',area:'Hidrostática',tags:['hidro'],
 q:'A pressão atmosférica na superfície de um lago é 1,0 × 10⁵ Pa. Sendo a densidade da água 1 000 kg/m³ e g = 10 m/s², a pressão total a 20 m de profundidade é',
 alts:['1,0 × 10⁵ Pa','2,0 × 10⁵ Pa','3,0 × 10⁵ Pa','2,0 × 10⁶ Pa','3,0 × 10⁶ Pa'],ans:2,
 why:['A pressão aumenta com a profundidade.','2,0 × 10⁵ Pa é só a pressão da coluna de água: esqueceu a pressão atmosférica.','','2,0 × 10⁶ Pa: errou a potência de 10 (d·g·h = 2 × 10⁵).','3,0 × 10⁶ Pa: errou a potência de 10.'],
 steps:['Stevin: p = p<sub>atm</sub> + d·g·h.','d·g·h = 1 000 · 10 · 20 = 2,0 × 10⁵ Pa.','p = 1,0 × 10⁵ + 2,0 × 10⁵.','p = 3,0 × 10⁵ Pa.'],
 trap:['p = d·g·h = 2,0 × 10⁵ Pa (a pressão atmosférica não entra).','d·g·h = 1 000 · 10 · 20 = 2,0 × 10⁶ Pa.']},
{id:'ff21',area:'Oscilações',tags:['mhs','grav'],
 q:'Um pêndulo simples tem período de 2 s na Terra. Na Lua, onde a gravidade é cerca de 1/6 da terrestre, o período desse pêndulo é aproximadamente',
 alts:['0,33 s','0,82 s','2 s','4,9 s','12 s'],ans:3,
 why:['0,33 s = 2/6: dividiu pelo fator da gravidade.','0,82 s = 2/√6: inverteu a dependência (T aumenta quando g diminui).','O período depende de g.','','12 s = 2·6: esqueceu a raiz quadrada.'],
 steps:['T = 2π√(L/g): o período é inversamente proporcional a √g.','g<sub>Lua</sub> = g/6 ⇒ T<sub>Lua</sub> = T·√6.','T<sub>Lua</sub> = 2·√6 ≈ 2·2,45.','T<sub>Lua</sub> ≈ 4,9 s.'],
 trap:['T é proporcional a g: T<sub>Lua</sub> = 2/6 ≈ 0,33 s.','T é inversamente proporcional a g: T<sub>Lua</sub> = 2·6 = 12 s.']},
];
