const BRAND={app:'SaberLingo',chatPh:'ex.: o que é fato social?',tutor:'Professor Sócrates',sym:'φ',body:'#ff6fb5',dark:'#d4509a',belly:'#ffe3f1',lsKey:'filolingo_v1',first:'presoc',
 welcome:'Filosofia e Sociologia do <b>Ensino Médio</b>: dos pré-socráticos aos pensadores contemporâneos, ética, lógica, os clássicos da Sociologia e o pensamento social brasileiro.',
 range:'do Ensino Médio (ENEM e vestibulares)',searchEx:'ex.: Durkheim',firstName:'Pré-socráticos',
 chips:['O que é fato social?','Mito da caverna','Imperativo categórico','Mais-valia','Indústria cultural','O que é falácia?'],
 askEx:'<i>"o que é maiêutica?"</i>, <i>"Weber"</i>, <i>"utilitarismo"</i>',
 formulas:'conceitos e autores (use os cartões de memória para associar cada autor às suas ideias)'};
const UNITS=[];

/* ------------------------ UNIDADE 1 — FILOSOFIA ANTIGA ------------------------ */
UNITS.push({id:'f1',title:'Filosofia antiga',sub:'Mito e logos, pré-socráticos, Sócrates, sofistas, Platão, Aristóteles e helenismo',color:'#ff6fb5',dark:'#d4509a',skills:[
SKL('presoc','Do mito à filosofia: pré-socráticos','🌊','A filosofia nasce na Grécia (séc. VI a.C.) como passagem do mito ao logos (razão). Os pré-socráticos buscavam a arché, o princípio de todas as coisas.',
`<p>O <b>mito</b> explica o mundo por narrativas sobrenaturais transmitidas pela tradição; o <b>logos</b> busca explicações racionais, que podem ser questionadas. A filosofia surge nas colônias gregas (Mileto, séc. VI a.C.), num ambiente de comércio, escrita e debate público.</p>
<p>Os <b>pré-socráticos</b> (naturalistas) investigavam a <b>physis</b> (natureza) e a <b>arché</b> (princípio primordial):</p>
<ul><li><b>Tales de Mileto</b>: a água. <b>Anaximandro</b>: o ápeiron (o indeterminado). <b>Anaxímenes</b>: o ar.</li><li><b>Pitágoras</b>: os números como essência da realidade.</li><li><b>Heráclito</b>: tudo muda (<b>devir</b>) — "ninguém se banha duas vezes no mesmo rio"; o fogo e a luta dos contrários.</li><li><b>Parmênides</b>: o ser é imutável e eterno; a mudança é ilusão dos sentidos — "o ser é, o não ser não é".</li><li><b>Empédocles</b>: quatro elementos (terra, água, ar e fogo). <b>Demócrito</b> (e Leucipo): o <b>átomo</b>.</li></ul>`,
{pairs:[['Tales de Mileto','considerava a água o princípio de todas as coisas'],['Heráclito','defendia que tudo está em constante mudança (devir)'],['Parmênides','defendia que o ser é imutável e que a mudança é ilusão'],['Pitágoras','via nos números a essência da realidade'],['Demócrito','propôs que tudo é formado por átomos'],['Anaxímenes','considerava o ar o princípio de todas as coisas'],['Anaximandro','propôs o ápeiron, o indeterminado, como princípio'],['Empédocles','propôs os quatro elementos: terra, água, ar e fogo']],
 qs:[['A passagem do mito ao logos significa:','a busca de explicações racionais e argumentadas para o mundo',['o abandono de toda religião','a criação das primeiras narrativas sobre deuses','a invenção da escrita'],'O logos submete as explicações à crítica racional.'],['"Ninguém se banha duas vezes no mesmo rio" expressa a ideia de:','devir, a mudança constante (Heráclito)',['imobilidade do ser (Parmênides)','número como essência (Pitágoras)','átomo (Demócrito)'],'Tanto o rio quanto a pessoa mudam.'],['Arché, para os pré-socráticos, é:','o princípio fundamental de todas as coisas',['um deus do Olimpo','uma forma de governo','a arte de argumentar'],'Buscavam a origem da physis.']]}),
SKL('socrates','Sócrates e os sofistas','🗣️','Sócrates: "só sei que nada sei", ironia e maiêutica (parto das ideias), "conhece-te a ti mesmo". Sofistas: professores de retórica, relativistas ("o homem é a medida de todas as coisas", Protágoras).',
`<p>No período clássico (Atenas, séc. V a.C.), a filosofia volta-se para o <b>ser humano</b>, a ética e a política.</p>
<ul><li><b>Sofistas</b> (Protágoras, Górgias): professores pagos de <b>retórica</b> e oratória para a vida política democrática; <b>relativismo</b> — "o homem é a medida de todas as coisas".</li><li><b>Sócrates</b> (não deixou escritos; conhecido por Platão): método em duas etapas — <b>ironia</b> (perguntas que revelam a ignorância do interlocutor) e <b>maiêutica</b> ("parto" das ideias, conduzindo à definição). Lemas: "<b>só sei que nada sei</b>" e "<b>conhece-te a ti mesmo</b>". Acusado de corromper a juventude e de não crer nos deuses da cidade, foi condenado a beber cicuta (399 a.C.).</li></ul>`,
{pairs:[['Maiêutica','método socrático de "dar à luz" as ideias por meio de perguntas'],['Ironia socrática','perguntas que revelam ao interlocutor a própria ignorância'],['Sofistas','professores de retórica que defendiam o relativismo'],['Protágoras','sofista que afirmou "o homem é a medida de todas as coisas"'],['"Só sei que nada sei"','reconhecimento da própria ignorância como início do saber, atribuído a Sócrates'],['"Conhece-te a ti mesmo"','inscrição do templo de Delfos adotada por Sócrates como lema']],
 qs:[['A crítica de Sócrates aos sofistas era que eles:','cobravam para ensinar a persuadir, sem compromisso com a verdade',['não sabiam falar em público','defendiam a monarquia','eram contra a democracia'],'Retórica pela persuasão × busca da verdade.'],['Sócrates foi condenado à morte sob a acusação de:','corromper a juventude e não crer nos deuses da cidade',['trair Atenas na guerra','roubar o tesouro público','defender a tirania'],'Julgamento narrado na <i>Apologia</i>, de Platão.']]}),
SKL('platao','Platão','🕯️','Dualismo: mundo sensível (aparências, cópias) × mundo inteligível (Ideias, verdadeiro). Mito da caverna: o filósofo sai das sombras rumo ao conhecimento. A República: governo do rei-filósofo.',
`<p><b>Platão</b>, discípulo de Sócrates, fundou a <b>Academia</b>.</p>
<ul><li><b>Teoria das Ideias</b>: o <b>mundo sensível</b>, percebido pelos sentidos, é mutável e é só uma cópia imperfeita do <b>mundo inteligível</b> (das Ideias ou Formas), eterno e perfeito, alcançado pela razão.</li><li><b>Mito (alegoria) da caverna</b> (<i>A República</i>): prisioneiros veem apenas sombras e as tomam pela realidade; um deles se liberta, vê o Sol (a Ideia do Bem) e volta para libertar os outros — é o papel do filósofo e da educação.</li><li><b>Reminiscência</b>: conhecer é recordar o que a alma já contemplou.</li><li><b>Política</b>: cidade justa governada pelo <b>rei-filósofo</b>, com cada classe (governantes, guardiões, produtores) cumprindo sua função.</li><li><b>Alma tripartida</b>: racional, irascível e concupiscível.</li></ul>`,
{pairs:[['Mundo das Ideias','realidade eterna e perfeita, acessível pela razão'],['Mundo sensível','mundo das aparências, percebido pelos sentidos'],['Mito da caverna','alegoria sobre a passagem da ignorância ao conhecimento'],['Rei-filósofo','governante ideal da cidade justa segundo Platão'],['Reminiscência','ideia de que conhecer é recordar o que a alma já contemplou'],['Academia','escola fundada por Platão em Atenas']],
 qs:[['No mito da caverna, as sombras na parede representam:','as aparências do mundo sensível tomadas como verdade',['o mundo das Ideias','a Ideia do Bem','o conhecimento filosófico'],'Os prisioneiros confundem as sombras com a realidade.'],['Para Platão, o verdadeiro conhecimento é alcançado:','pela razão, que acessa o mundo das Ideias',['apenas pelos sentidos','pela tradição e pelos mitos','pela experiência prática'],'Os sentidos só mostram cópias.']]}),
SKL('aristoteles','Aristóteles','📚','A essência está nas próprias coisas; ato e potência; quatro causas; lógica (silogismo); ética da virtude como justo meio; felicidade (eudaimonia); "o ser humano é um animal político".',
`<p><b>Aristóteles</b>, discípulo de Platão, fundou o <b>Liceu</b> e foi preceptor de Alexandre.</p>
<ul><li>Critica o dualismo platônico: a <b>forma</b> (essência) está nas próprias coisas, unida à <b>matéria</b>. Valoriza a observação.</li><li><b>Ato e potência</b>: a semente é árvore em potência; a mudança é a passagem da potência ao ato.</li><li><b>Quatro causas</b>: material, formal, eficiente e final.</li><li><b>Lógica</b>: o <b>silogismo</b> ("Todo homem é mortal; Sócrates é homem; logo, Sócrates é mortal").</li><li><b>Ética</b>: a finalidade da vida é a <b>felicidade (eudaimonia)</b>, alcançada pela <b>virtude</b>, que é o <b>justo meio</b> entre dois extremos (coragem entre covardia e temeridade), adquirida pelo hábito.</li><li><b>Política</b>: "o ser humano é um <b>animal político</b>" — só se realiza na pólis.</li></ul>`,
{pairs:[['Ato e potência','conceitos que explicam a mudança como passagem do possível ao real'],['Silogismo','raciocínio dedutivo com duas premissas e uma conclusão'],['Justo meio','virtude como equilíbrio entre o excesso e a falta'],['Eudaimonia','felicidade, finalidade última da vida humana para Aristóteles'],['Animal político','definição aristotélica do ser humano como ser que vive na pólis'],['Causa final','a finalidade para a qual algo existe ou acontece'],['Liceu','escola fundada por Aristóteles em Atenas']],
 qs:[['Para Aristóteles, a coragem é uma virtude porque:','é o justo meio entre a covardia e a temeridade',['é o extremo oposto do medo','é inata e não depende do hábito','é contemplar o mundo das Ideias'],'Virtude = meio-termo entre falta e excesso.'],['"Todo homem é mortal. Sócrates é homem. Logo, Sócrates é mortal." Esse raciocínio é um:','silogismo',['sofisma','mito','argumento indutivo'],'Estrutura clássica da lógica aristotélica.'],['Diferentemente de Platão, Aristóteles afirmava que:','a essência das coisas está nelas mesmas, unida à matéria',['existe um mundo das Ideias separado','os sentidos são inúteis','o conhecimento é só reminiscência'],'Rejeita a separação entre os dois mundos.']]}),
SKL('helenismo','Filosofias helenísticas','🏺','Estoicismo: viver conforme a razão e aceitar o que não depende de nós. Epicurismo: prazer como ausência de dor (ataraxia). Ceticismo: suspender o juízo. Cinismo: vida simples, contra as convenções.',
`<p>Com o fim da autonomia das pólis (conquistas macedônicas), a filosofia busca a <b>felicidade individual</b> e a tranquilidade da alma.</p>
<ul><li><b>Estoicismo</b> (Zenão de Cítio; depois Sêneca, Epicteto, Marco Aurélio): viver de acordo com a razão e a natureza; aceitar o destino e distinguir o que depende de nós do que não depende; <b>apatia</b> (imperturbabilidade diante das paixões).</li><li><b>Epicurismo</b> (Epicuro): a felicidade é o prazer, entendido como <b>ausência de dor</b> no corpo e de perturbação na alma (<b>ataraxia</b>); prazeres simples e amizade; não temer a morte nem os deuses.</li><li><b>Ceticismo</b> (Pirro): não é possível alcançar certezas; <b>suspensão do juízo</b> (epoché) traz tranquilidade.</li><li><b>Cinismo</b> (Diógenes de Sinope): vida simples e natural, desprezo pelas convenções e riquezas.</li></ul>`,
{pairs:[['Estoicismo','viver conforme a razão, aceitando o que não depende de nós'],['Epicurismo','felicidade como prazer moderado e ausência de dor e perturbação'],['Ceticismo','suspensão do juízo diante da impossibilidade de certezas'],['Cinismo','vida simples e natural, com desprezo pelas convenções'],['Ataraxia','tranquilidade da alma, sem perturbações'],['Diógenes de Sinope','filósofo cínico que vivia em extrema simplicidade'],['Sêneca','filósofo estoico romano']],
 qs:[['"Não são as coisas que nos perturbam, mas as opiniões que temos sobre elas" (Epicteto) resume uma ideia:','estoica',['epicurista','cínica','pré-socrática'],'Controlar o próprio julgamento é o que depende de nós.'],['Para Epicuro, o prazer que leva à felicidade é:','a ausência de dor e de perturbação, com prazeres simples',['o excesso de comida e bebida','o poder político','a riqueza material'],'Epicurismo não é hedonismo desenfreado.']]})
]});

/* ------------------------ UNIDADE 2 — MEDIEVAL E MODERNA ------------------------ */
UNITS.push({id:'f2',title:'Filosofia medieval e moderna',sub:'Fé e razão, pensamento político, racionalismo, empirismo e Kant',color:'#1cb0f6',dark:'#1899d6',skills:[
SKL('medieval','Filosofia medieval: fé e razão','⛪','Patrística (Agostinho, inspirado em Platão): fé e razão, livre-arbítrio. Escolástica (Tomás de Aquino, inspirado em Aristóteles): conciliar fé e razão, provas da existência de Deus.',
`<ul><li><b>Patrística</b> (séc. II–VIII): Padres da Igreja defendem e organizam a doutrina cristã. <b>Santo Agostinho</b> retoma <b>Platão</b>: "compreender para crer, crer para compreender"; o mal como ausência de bem, fruto do <b>livre-arbítrio</b>; <i>A Cidade de Deus</i> e <i>Confissões</i>; iluminação divina.</li><li><b>Escolástica</b> (séc. IX–XIV), nas universidades: <b>São Tomás de Aquino</b> concilia fé e razão usando <b>Aristóteles</b> (<i>Suma Teológica</i>); as <b>cinco vias</b> para provar a existência de Deus (primeiro motor, causa primeira…). Guilherme de Ockham e a "navalha": não multiplicar entidades sem necessidade.</li></ul>`,
{pairs:[['Santo Agostinho','filósofo da patrística, influenciado por Platão, autor de A Cidade de Deus'],['São Tomás de Aquino','filósofo escolástico que conciliou fé e razão usando Aristóteles'],['Patrística','filosofia dos Padres da Igreja, nos primeiros séculos do cristianismo'],['Escolástica','filosofia ensinada nas universidades medievais'],['Cinco vias','argumentos de Tomás de Aquino para provar a existência de Deus'],['Navalha de Ockham','princípio de não multiplicar explicações sem necessidade'],['Livre-arbítrio','capacidade humana de escolher, usada por Agostinho para explicar o mal']],
 qs:[['A filosofia de Tomás de Aquino buscou:','conciliar a fé cristã com a filosofia de Aristóteles',['negar a existência de Deus','abandonar a razão','retomar os mitos gregos'],'Razão e fé não se contradizem.'],['Para Agostinho, o mal no mundo:','é ausência de bem, ligado ao mau uso do livre-arbítrio',['é criado diretamente por Deus','não existe','vem dos astros'],'O mal não é uma substância.']]}),
SKL('politica','Filosofia política moderna','⚖️','Maquiavel: política separada da moral. Hobbes: estado de natureza = guerra de todos contra todos → Estado absoluto (Leviatã). Locke: direitos naturais e governo limitado. Rousseau: bom selvagem, contrato social e vontade geral.',
`<ul><li><b>Maquiavel</b> (<i>O Príncipe</i>, 1513): a política tem lógica própria, separada da moral religiosa; o governante precisa de <b>virtù</b> (habilidade) para lidar com a <b>fortuna</b> (acaso); "é melhor ser temido do que amado", se não puder ser as duas coisas.</li><li><b>Contratualistas</b>: explicam a origem do Estado por um <b>pacto social</b> que tira as pessoas do <b>estado de natureza</b>.<ul><li><b>Hobbes</b> (<i>Leviatã</i>): no estado de natureza há "guerra de todos contra todos" ("o homem é o lobo do homem"); para ter segurança, cede-se todo o poder a um soberano absoluto.</li><li><b>Locke</b>: direitos naturais à vida, liberdade e <b>propriedade</b>; o governo deve protegê-los e pode ser derrubado se os violar (base do liberalismo).</li><li><b>Rousseau</b>: o ser humano nasce bom ("bom selvagem"); a propriedade privada gerou a desigualdade; o <b>contrato social</b> legítimo se baseia na <b>vontade geral</b> e na soberania popular.</li></ul></li></ul>`,
{pairs:[['Maquiavel','separou a política da moral em O Príncipe'],['Thomas Hobbes','descreveu o estado de natureza como guerra de todos contra todos'],['John Locke','defendeu os direitos naturais à vida, à liberdade e à propriedade'],['Jean-Jacques Rousseau','defendeu a vontade geral e a soberania popular'],['Estado de natureza','situação hipotética dos seres humanos antes do Estado'],['Contrato social','pacto que dá origem à sociedade política'],['Virtù','habilidade do governante para conquistar e manter o poder'],['Leviatã','obra de Hobbes que defende um soberano forte']],
 qs:[['"O homem é o lobo do homem" resume a visão de:','Hobbes sobre o estado de natureza',['Rousseau sobre o bom selvagem','Locke sobre a propriedade','Aristóteles sobre a pólis'],'Sem Estado, predomina o medo da morte violenta.'],['Para Rousseau, a origem da desigualdade entre os homens está:','na propriedade privada',['na natureza humana má','na vontade de Deus','na falta de um rei forte'],'"O primeiro que cercou um terreno e disse: isto é meu…".'],['Para Locke, se o governo violar os direitos naturais, o povo:','tem o direito de resistir e substituí-lo',['deve obedecer sempre','perde todos os direitos','deve voltar ao estado de natureza para sempre'],'Direito de resistência, base do liberalismo.']]}),
SKL('conhecer','Racionalismo, empirismo e Kant','🧠','Racionalismo (Descartes): a razão é a fonte segura do conhecimento — "penso, logo existo". Empirismo (Locke, Hume): o conhecimento vem da experiência — tábula rasa. Kant une os dois (criticismo).',
`<p>A pergunta moderna é: <b>como conhecemos?</b></p>
<ul><li><b>Racionalismo</b> — <b>Descartes</b>: <b>dúvida metódica</b> (duvidar de tudo que pode ser duvidado) até encontrar uma certeza indubitável: "<b>penso, logo existo</b>" (cogito); ideias <b>inatas</b>; dualismo entre mente e corpo.</li><li><b>Empirismo</b> — <b>Francis Bacon</b> (método indutivo, "saber é poder"); <b>Locke</b>: a mente é uma <b>tábula rasa</b>, preenchida pela experiência; <b>Hume</b>: a causalidade não é observada, é um <b>hábito</b> da mente (ceticismo).</li><li><b>Kant</b> (criticismo): o conhecimento começa com a experiência, mas é organizado por estruturas <b>a priori</b> da razão (espaço, tempo e categorias). Não conhecemos as coisas em si, apenas os <b>fenômenos</b>. "<b>Sapere aude</b>" (ousa saber) é o lema do Esclarecimento.</li></ul>`,
{pairs:[['Descartes','fundou o racionalismo moderno com o "penso, logo existo"'],['Dúvida metódica','duvidar de tudo que pode ser duvidado para achar certezas'],['Tábula rasa','ideia de Locke de que a mente nasce vazia e é preenchida pela experiência'],['David Hume','afirmou que a causalidade é um hábito da mente'],['Francis Bacon','defendeu o método indutivo e a frase "saber é poder"'],['Immanuel Kant','uniu razão e experiência no criticismo'],['Ideias inatas','ideias que nascem com a mente, segundo os racionalistas'],['Sapere aude','"ousa saber", lema do Esclarecimento segundo Kant']],
 qs:[['A frase "penso, logo existo" é de:','Descartes',['Locke','Hume','Kant'],'O cogito cartesiano.'],['O empirismo afirma que:','o conhecimento vem da experiência sensível',['todas as ideias são inatas','os sentidos sempre enganam','só a fé leva à verdade'],'Locke, Hume, Bacon.'],['Para Kant, conhecemos:','os fenômenos, organizados pelas estruturas a priori da razão',['as coisas em si mesmas','apenas as ideias inatas','nada, pois tudo é ilusão'],'Revolução copernicana na filosofia.']]})
]});

/* ------------------------ UNIDADE 3 — CONTEMPORÂNEA, ÉTICA E LÓGICA ------------------------ */
UNITS.push({id:'f3',title:'Filosofia contemporânea, ética e lógica',sub:'Hegel, Marx, Nietzsche, existencialismo, Frankfurt, Arendt, Foucault, ética e argumentação',color:'#ff9600',dark:'#e07b00',skills:[
SKL('contemp','Pensadores contemporâneos','🔥','Hegel (dialética), Nietzsche ("Deus está morto", crítica da moral), Sartre ("a existência precede a essência"), Beauvoir ("não se nasce mulher, torna-se"), Arendt (banalidade do mal), Foucault (poder disciplinar).',
`<ul><li><b>Hegel</b>: <b>dialética</b> (tese, antítese, síntese); a história como desenvolvimento do Espírito.</li><li><b>Nietzsche</b>: crítica à moral cristã ("moral de rebanho"), "<b>Deus está morto</b>", <b>vontade de potência</b>, <b>super-homem</b> (além-do-homem), eterno retorno.</li><li><b>Existencialismo</b> — <b>Sartre</b>: "a <b>existência precede a essência</b>"; o ser humano está "<b>condenado a ser livre</b>" e é responsável por suas escolhas. <b>Simone de Beauvoir</b> (<i>O Segundo Sexo</i>, 1949): "<b>Não se nasce mulher, torna-se mulher</b>".</li><li><b>Hannah Arendt</b>: totalitarismo e "<b>banalidade do mal</b>" (Eichmann cumpria ordens sem pensar).</li><li><b>Michel Foucault</b>: poder disciplinar, vigilância e o <b>panóptico</b> (<i>Vigiar e Punir</i>).</li><li><b>Escola de Frankfurt</b> (Adorno, Horkheimer): <b>indústria cultural</b> — cultura transformada em mercadoria padronizada, que aliena. Habermas: razão comunicativa.</li></ul>`,
{pairs:[['Nietzsche','anunciou a "morte de Deus" e criticou a moral de rebanho'],['Sartre','afirmou que a existência precede a essência'],['Simone de Beauvoir','escreveu "não se nasce mulher, torna-se mulher"'],['Hannah Arendt','formulou o conceito de banalidade do mal'],['Michel Foucault','estudou o poder disciplinar e o panóptico'],['Hegel','desenvolveu a dialética de tese, antítese e síntese'],['Indústria cultural','conceito de Adorno e Horkheimer para a cultura como mercadoria padronizada'],['Vontade de potência','força vital de afirmação e superação, em Nietzsche']],
 qs:[['"O homem está condenado a ser livre" é uma frase associada ao:','existencialismo de Sartre',['estoicismo','positivismo de Comte','empirismo de Hume'],'Somos responsáveis por tudo o que escolhemos.'],['O conceito de "banalidade do mal", de Hannah Arendt, indica que:','grandes crimes podem ser cometidos por pessoas comuns que deixam de pensar',['o mal é sempre obra de monstros','o mal não existe','só os religiosos fazem o bem'],'Reflexão sobre o julgamento de Eichmann.'],['Para Adorno e Horkheimer, a indústria cultural:','padroniza a cultura como mercadoria e reduz a capacidade crítica',['democratiza a arte e estimula a crítica','é uma escola de filosofia','é a cultura popular espontânea'],'Crítica da Escola de Frankfurt.']]}),
SKL('etica','Ética','🧭','Ética é a reflexão sobre a moral. Deontologia (Kant): agir por dever — imperativo categórico. Utilitarismo (Bentham, Mill): a ação certa gera a maior felicidade para o maior número. Ética das virtudes (Aristóteles).',
`<p><b>Moral</b>: conjunto de normas e valores de um grupo. <b>Ética</b>: reflexão filosófica sobre a moral e seus fundamentos.</p>
<ul><li><b>Ética das virtudes</b> (Aristóteles): formar o caráter pelo hábito das virtudes.</li><li><b>Deontologia</b> (Kant): o valor moral está na intenção de cumprir o <b>dever</b>. <b>Imperativo categórico</b>: "Age apenas segundo uma máxima tal que possas querer que ela se torne lei universal" e "trata a humanidade sempre como fim, nunca apenas como meio". Mentir é errado mesmo com boas consequências.</li><li><b>Utilitarismo</b> (Bentham, Stuart Mill): a ação correta é a que produz a <b>maior felicidade para o maior número</b> — ética das consequências.</li></ul>
<p><b>Bioética</b>: dilemas sobre vida e saúde (eutanásia, clonagem, uso de animais). <b>Autonomia</b> × heteronomia: seguir a própria razão ou normas impostas de fora.</p>`,
{pairs:[['Ética','reflexão filosófica sobre a moral e seus fundamentos'],['Moral','conjunto de normas e valores de um grupo social'],['Imperativo categórico','princípio kantiano: agir como se a máxima da ação fosse lei universal'],['Utilitarismo','ética que busca a maior felicidade para o maior número'],['Deontologia','ética baseada no dever'],['Autonomia','capacidade de dar a si mesmo a lei moral pela razão'],['Heteronomia','seguir normas impostas de fora'],['Bioética','campo que discute dilemas morais ligados à vida e à saúde']],
 qs:[['Para Kant, uma mentira dita para ajudar alguém:','continua errada, pois não pode ser universalizada',['é correta se trouxer boas consequências','é neutra','depende da cultura'],'O dever não depende das consequências.'],['Um governo que escolhe a política que beneficia o maior número de pessoas segue um raciocínio:','utilitarista',['deontológico kantiano','estoico','cínico'],'Foco nas consequências para a maioria.']]}),
SKL('logica','Lógica e falácias','🧩','Dedução: da regra geral ao caso (conclusão necessária). Indução: dos casos à regra (conclusão provável). Falácias: argumentos que parecem válidos, mas são falhos (ad hominem, espantalho, apelo à autoridade…).',
`<ul><li><b>Dedução</b>: parte de premissas gerais para uma conclusão particular; se as premissas forem verdadeiras e a forma válida, a conclusão é <b>necessária</b> (silogismo).</li><li><b>Indução</b>: parte de casos particulares para uma generalização; a conclusão é apenas <b>provável</b> ("todos os cisnes que vi são brancos…").</li><li><b>Validade</b> diz respeito à forma do argumento; <b>verdade</b>, ao conteúdo das proposições.</li></ul>
<h3>Falácias comuns</h3><ul><li><b>Ad hominem</b>: atacar a pessoa em vez do argumento.</li><li><b>Espantalho</b>: distorcer o argumento do outro para refutá-lo.</li><li><b>Apelo à autoridade</b>: aceitar algo só porque alguém famoso disse.</li><li><b>Falsa dicotomia</b>: apresentar só duas opções quando há mais.</li><li><b>Generalização apressada</b>: concluir a partir de poucos casos.</li><li><b>Ladeira escorregadia</b>: supor que um passo levará inevitavelmente a consequências extremas.</li><li><b>Apelo à maioria</b> (ad populum): "todo mundo faz, então é certo".</li></ul>`,
{pairs:[['"Não ouça o que ele diz sobre economia, ele é feio e mal-educado."','falácia ad hominem'],['"Ou você apoia essa lei, ou é contra o país."','falsa dicotomia'],['"Conheci dois paulistas grosseiros; os paulistas são grosseiros."','generalização apressada'],['"Se permitirmos celular no intervalo, logo ninguém mais vai estudar."','ladeira escorregadia'],['"Milhões de pessoas acreditam nisso, então deve ser verdade."','apelo à maioria (ad populum)'],['"Um ator famoso disse que esse remédio funciona, então funciona."','apelo à autoridade'],['"Você quer menos gastos com armas? Então quer deixar o país indefeso!"','espantalho']],tq:t=>`Qual falácia aparece em <b>${t}</b>?`,dq:d=>`Qual argumento contém a <b>${d}</b>?`,noTF:true,
 qs:[['"Todo metal conduz eletricidade. O cobre é metal. Logo, o cobre conduz eletricidade." Esse argumento é:','dedutivo',['indutivo','uma falácia','um mito'],'Do geral para o particular: conclusão necessária.'],['"O Sol nasceu todos os dias que observei; logo, nascerá amanhã." Esse argumento é:','indutivo',['dedutivo','um silogismo válido','uma falácia ad hominem'],'Generalização a partir de casos: conclusão provável.']]})
]});

/* ------------------------ UNIDADE 4 — SOCIOLOGIA CLÁSSICA ------------------------ */
UNITS.push({id:'f4',title:'Sociologia clássica',sub:'Comte, Durkheim, Weber, Marx, cultura, socialização e estratificação',color:'#ce82ff',dark:'#a568cc',skills:[
SKL('socio','Surgimento da Sociologia e Durkheim','🏛️','A Sociologia nasce no século XIX com as Revoluções Industrial e Francesa. Comte: positivismo. Durkheim: fato social (exterior, coercitivo e geral), solidariedade mecânica e orgânica, anomia.',
`<p>A <b>Sociologia</b> surge no século XIX para compreender as transformações das Revoluções Industrial e Francesa (urbanização, novas classes, crise das tradições).</p>
<ul><li><b>Auguste Comte</b>: criou o termo "sociologia" e o <b>positivismo</b> (a ciência como único conhecimento válido); lei dos três estados (teológico, metafísico e positivo). O lema "Ordem e Progresso" da bandeira brasileira vem do positivismo.</li><li><b>Émile Durkheim</b>: a sociedade deve ser estudada como coisa. <b>Fato social</b>: maneira de agir, pensar e sentir que é <b>exterior</b> ao indivíduo, <b>coercitiva</b> e <b>geral</b> (leis, língua, moda, religião).<ul><li><b>Solidariedade mecânica</b>: sociedades simples, coesão pela semelhança.</li><li><b>Solidariedade orgânica</b>: sociedades modernas, coesão pela <b>divisão do trabalho</b> e interdependência.</li><li><b>Anomia</b>: enfraquecimento das normas sociais (estudada em <i>O Suicídio</i>).</li></ul></li></ul>`,
{pairs:[['Auguste Comte','criou o positivismo e o termo "sociologia"'],['Fato social','maneira de agir, pensar e sentir exterior, coercitiva e geral'],['Solidariedade mecânica','coesão social baseada na semelhança entre as pessoas'],['Solidariedade orgânica','coesão social baseada na divisão do trabalho e na interdependência'],['Anomia','enfraquecimento das normas que regulam a vida social'],['Positivismo','corrente que valoriza a ciência como único conhecimento válido'],['Émile Durkheim','sociólogo que definiu o fato social e estudou o suicídio']],
 qs:[['A língua que falamos é um fato social porque:','existe antes de nós, é geral e nos obriga a segui-la para sermos entendidos',['foi inventada por cada pessoa','não muda nunca','é uma escolha totalmente individual'],'Exterioridade, generalidade e coercitividade.'],['O lema "Ordem e Progresso" da bandeira brasileira tem origem no:','positivismo de Comte',['marxismo','existencialismo','iluminismo de Rousseau'],'Os republicanos de 1889 eram influenciados pelo positivismo.']]}),
SKL('weber','Max Weber','📜','Ação social (racional com relação a fins, a valores, afetiva e tradicional); dominação legal, tradicional e carismática; ética protestante e espírito do capitalismo; racionalização e burocracia.',
`<p>Para <b>Max Weber</b>, a Sociologia deve <b>compreender</b> o sentido que os indivíduos dão às suas ações (sociologia compreensiva).</p>
<ul><li><b>Ação social</b>: ação orientada pelo comportamento de outros. Tipos: <b>racional com relação a fins</b> (meios calculados para um objetivo), <b>racional com relação a valores</b> (convicções), <b>afetiva</b> (emoções) e <b>tradicional</b> (costumes).</li><li><b>Tipos de dominação legítima</b>: <b>legal-racional</b> (leis e burocracia), <b>tradicional</b> (costume, como a de um rei) e <b>carismática</b> (qualidades extraordinárias atribuídas a um líder).</li><li><i>A Ética Protestante e o Espírito do Capitalismo</i>: a ética calvinista (trabalho disciplinado, poupança) favoreceu o capitalismo.</li><li><b>Racionalização</b> e <b>desencantamento do mundo</b>; a <b>burocracia</b> como forma típica de organização moderna.</li><li><b>Tipo ideal</b>: modelo teórico usado para comparar casos reais.</li></ul>`,
{pairs:[['Ação social','ação orientada pelo comportamento de outras pessoas'],['Dominação carismática','poder baseado nas qualidades extraordinárias atribuídas a um líder'],['Dominação legal-racional','poder baseado em leis e regras impessoais'],['Dominação tradicional','poder baseado nos costumes e na tradição'],['Tipo ideal','modelo teórico usado para analisar a realidade'],['Desencantamento do mundo','perda das explicações mágicas e religiosas diante da racionalização'],['Burocracia','organização baseada em regras, hierarquia e impessoalidade']],
 qs:[['Um líder que conquista seguidores pela admiração às suas qualidades pessoais exerce, para Weber, dominação:','carismática',['legal-racional','tradicional','burocrática'],'Baseada no carisma do líder.'],['Weber relacionou o surgimento do capitalismo moderno à:','ética protestante (calvinista)',['luta de classes','solidariedade mecânica','Revolução Russa'],'Trabalho metódico e poupança como sinais de salvação.']]}),
SKL('marx','Karl Marx','⚒️','A história é a história da luta de classes. No capitalismo, a burguesia detém os meios de produção e explora o proletariado pela mais-valia. Alienação, ideologia, infraestrutura e superestrutura.',
`<ul><li><b>Materialismo histórico</b>: as condições materiais (economia) moldam a sociedade. <b>Infraestrutura</b> (forças e relações de produção) × <b>superestrutura</b> (Estado, direito, religião, ideologia).</li><li>"A história de toda sociedade até hoje é a história da <b>luta de classes</b>" (<i>Manifesto Comunista</i>, 1848). No capitalismo: <b>burguesia</b> (dona dos meios de produção) × <b>proletariado</b> (vende a força de trabalho).</li><li><b>Mais-valia</b>: valor produzido pelo trabalhador além do que recebe de salário, apropriado pelo capitalista — fonte do lucro.</li><li><b>Alienação</b>: o trabalhador não se reconhece no produto nem no processo do seu trabalho.</li><li><b>Ideologia</b>: ideias da classe dominante que ocultam a exploração.</li><li><b>Fetichismo da mercadoria</b>: relações entre pessoas aparecem como relações entre coisas.</li></ul>`,
{pairs:[['Mais-valia','valor produzido pelo trabalhador e não pago no salário, fonte do lucro'],['Alienação','o trabalhador não se reconhece no produto de seu trabalho'],['Luta de classes','conflito entre classes com interesses opostos, motor da história para Marx'],['Meios de produção','fábricas, máquinas, terras e ferramentas usadas para produzir'],['Ideologia','conjunto de ideias da classe dominante que oculta a exploração'],['Infraestrutura','base econômica da sociedade, segundo Marx'],['Proletariado','classe que vende sua força de trabalho em troca de salário']],
 qs:[['Para Marx, o lucro do capitalista vem da:','mais-valia extraída do trabalho',['generosidade do mercado','poupança do trabalhador','intervenção divina'],'Trabalho não pago.'],['Um operário que aperta parafusos o dia inteiro, sem conhecer o produto final, vive o que Marx chamou de:','alienação',['anomia','solidariedade orgânica','dominação carismática'],'Separação entre trabalhador e produto.']]}),
SKL('cultura','Cultura, socialização e estratificação','🎎','Cultura: tudo o que é aprendido e compartilhado. Etnocentrismo: julgar outras culturas pela própria; relativismo cultural: compreendê-las em seus próprios termos. Estratificação: castas, estamentos e classes.',
`<ul><li><b>Cultura</b> (sentido antropológico): conjunto de crenças, valores, costumes, técnicas e símbolos <b>aprendidos</b> e compartilhados.</li><li><b>Etnocentrismo</b>: julgar outras culturas a partir da própria, considerada superior. <b>Relativismo cultural</b>: compreender cada cultura em seu contexto. <b>Aculturação</b>, sincretismo e diversidade cultural.</li><li><b>Socialização</b>: processo de aprender as normas da sociedade. <b>Primária</b> (família, infância) e <b>secundária</b> (escola, trabalho, mídia).</li><li><b>Instituições sociais</b>: família, escola, Estado, religião.</li><li><b>Estratificação social</b>: <b>castas</b> (Índia; posição por nascimento, sem mobilidade), <b>estamentos</b> (sociedade feudal; pouca mobilidade) e <b>classes</b> (capitalismo; mobilidade possível, baseada sobretudo na renda). <b>Mobilidade social</b>: vertical (ascendente/descendente) e horizontal.</li></ul>`,
{pairs:[['Etnocentrismo','julgar outras culturas a partir da própria, vista como superior'],['Relativismo cultural','compreender cada cultura segundo seus próprios valores'],['Socialização primária','aprendizado das normas básicas na família, na infância'],['Socialização secundária','aprendizado em instituições como escola e trabalho'],['Sociedade de castas','estratificação por nascimento, sem mobilidade social'],['Sociedade estamental','estratificação típica do feudalismo, com pouca mobilidade'],['Mobilidade social vertical','mudança de posição social para cima ou para baixo'],['Sincretismo','fusão de elementos de culturas ou religiões diferentes']],
 qs:[['Considerar "atrasados" os hábitos alimentares de outro povo só porque são diferentes dos nossos é um exemplo de:','etnocentrismo',['relativismo cultural','sincretismo','mobilidade social'],'Julgar pelo próprio padrão cultural.'],['Na sociologia, cultura significa:','tudo o que é aprendido e compartilhado por um grupo',['apenas as artes eruditas','o grau de escolaridade de alguém','somente as tradições folclóricas'],'Sentido antropológico, amplo.']]})
]});

/* ------------------------ UNIDADE 5 — TRABALHO, POLÍTICA E BRASIL ------------------------ */
UNITS.push({id:'f5',title:'Trabalho, cidadania e Brasil',sub:'Fordismo e toyotismo, cidadania, movimentos sociais e pensamento social brasileiro',color:'#2b70c9',dark:'#1f569e',skills:[
SKL('trabalho','Mundo do trabalho','🏭','Taylorismo: tempos e movimentos. Fordismo: linha de montagem e produção em massa. Toyotismo: produção flexível, just in time, trabalhador multifuncional. Hoje: precarização e uberização.',
`<ul><li><b>Taylorismo</b> (Frederick Taylor): "administração científica" — controle de tempos e movimentos, separação entre quem planeja e quem executa.</li><li><b>Fordismo</b> (Henry Ford): <b>linha de montagem</b>, esteira, trabalho repetitivo, <b>produção em massa</b> padronizada e consumo de massa.</li><li><b>Toyotismo</b> (Japão, pós-1945): <b>produção flexível</b>, <b>just in time</b> (estoque mínimo), trabalhador <b>multifuncional</b>, trabalho em equipe e controle de qualidade.</li><li><b>Hoje</b>: terceirização, informalidade, desemprego estrutural (automação), <b>precarização</b> e <b>uberização</b> (trabalho por aplicativos sem vínculos e direitos tradicionais).</li></ul>`,
{pairs:[['Taylorismo','organização do trabalho pelo controle de tempos e movimentos'],['Fordismo','linha de montagem e produção em massa padronizada'],['Toyotismo','produção flexível, just in time e trabalhador multifuncional'],['Just in time','produzir e estocar apenas o necessário, no momento certo'],['Uberização','trabalho mediado por aplicativos, sem vínculos formais'],['Terceirização','contratação de outra empresa para executar parte das atividades'],['Desemprego estrutural','desemprego causado por mudanças tecnológicas e produtivas']],
 qs:[['O filme <i>Tempos Modernos</i>, em que Chaplin aperta parafusos numa esteira, critica o:','fordismo',['toyotismo','feudalismo','artesanato'],'Trabalho repetitivo na linha de montagem.'],['Uma fábrica que mantém estoques mínimos e produz conforme a demanda aplica o princípio:','just in time, do toyotismo',['da linha de montagem fordista','da mais-valia absoluta','da solidariedade mecânica'],'Produção enxuta e flexível.']]}),
SKL('cidadania','Política, cidadania e movimentos sociais','🗳️','Cidadania: direitos civis, políticos e sociais (T. H. Marshall). No Brasil, os direitos sociais vieram antes dos políticos (José Murilo de Carvalho). Movimentos sociais lutam pela ampliação de direitos.',
`<ul><li><b>Estado</b>: instituição que detém o monopólio do uso legítimo da força num território (Weber). <b>Poder</b> e <b>governo</b>. Três poderes: Executivo, Legislativo e Judiciário.</li><li><b>Democracia</b>: direta, representativa e participativa (conselhos, orçamento participativo, plebiscito, referendo).</li><li><b>Cidadania</b> segundo <b>T. H. Marshall</b>: direitos <b>civis</b> (liberdade, propriedade, igualdade perante a lei), <b>políticos</b> (votar e ser votado) e <b>sociais</b> (educação, saúde, trabalho). Na Inglaterra surgiram nessa ordem; no Brasil, segundo José Murilo de Carvalho, os direitos sociais vieram antes (Era Vargas), numa "cidadania invertida".</li><li><b>Movimentos sociais</b>: ações coletivas organizadas por mudanças — operário, feminista, negro, LGBTQIA+, ambientalista, pela terra (MST), indígena.</li></ul>`,
{pairs:[['Direitos civis','direitos de liberdade, propriedade e igualdade perante a lei'],['Direitos políticos','direitos de votar, ser votado e participar do governo'],['Direitos sociais','direitos à educação, saúde, trabalho e previdência'],['Plebiscito','consulta popular feita antes da criação de uma lei'],['Referendo','consulta popular para aprovar ou rejeitar uma lei já elaborada'],['Movimento social','ação coletiva organizada em busca de mudanças sociais'],['Democracia representativa','regime em que o povo elege representantes para governar']],
 qs:[['Segundo José Murilo de Carvalho, no Brasil os direitos sociais:','vieram antes da ampliação dos direitos políticos, na Era Vargas',['nunca existiram','surgiram depois de todos os outros','vieram junto com a Independência'],'Cidadania "de cima para baixo".'],['A consulta popular feita depois que uma lei foi elaborada, para aprová-la ou não, é o:','referendo',['plebiscito','impeachment','habeas corpus'],'Plebiscito vem antes; referendo, depois.']]}),
SKL('brasil','Pensamento social brasileiro','🇧🇷','Gilberto Freyre (Casa-Grande & Senzala: miscigenação; ideia de "democracia racial", depois criticada), Sérgio Buarque (Raízes do Brasil: "homem cordial"), Florestan Fernandes (mito da democracia racial), Darcy Ribeiro (O Povo Brasileiro).',
`<ul><li><b>Gilberto Freyre</b> (<i>Casa-Grande & Senzala</i>, 1933): valorizou a <b>miscigenação</b> e a contribuição africana; sua obra foi associada à ideia de "<b>democracia racial</b>", que suavizava a violência da escravidão.</li><li><b>Sérgio Buarque de Holanda</b> (<i>Raízes do Brasil</i>, 1936): o "<b>homem cordial</b>" — age pelo coração, pelas relações pessoais, e não pela impessoalidade; <b>patrimonialismo</b> (confusão entre público e privado).</li><li><b>Florestan Fernandes</b>: mostrou que a democracia racial é um <b>mito</b>; os negros foram deixados à margem após a abolição.</li><li><b>Darcy Ribeiro</b> (<i>O Povo Brasileiro</i>, 1995): formação do povo a partir de matrizes indígena, europeia e africana.</li><li><b>Caio Prado Jr.</b>: o "sentido da colonização" (economia voltada para fora).</li><li>Hoje: <b>racismo estrutural</b> (Silvio Almeida), <b>Lélia Gonzalez</b> (feminismo negro, "amefricanidade"), debates sobre desigualdade e ações afirmativas (cotas).</li></ul>`,
{pairs:[['Gilberto Freyre','autor de Casa-Grande & Senzala, que valorizou a miscigenação'],['Sérgio Buarque de Holanda','autor de Raízes do Brasil e do conceito de "homem cordial"'],['Florestan Fernandes','sociólogo que denunciou o mito da democracia racial'],['Darcy Ribeiro','autor de O Povo Brasileiro'],['Homem cordial','brasileiro que age pelas relações pessoais e afetivas, e não pela impessoalidade'],['Patrimonialismo','confusão entre o público e o privado no uso do Estado'],['Racismo estrutural','racismo presente no funcionamento normal das instituições e da sociedade'],['Mito da democracia racial','ideia falsa de que no Brasil não há racismo']],
 qs:[['O "homem cordial", de Sérgio Buarque de Holanda, significa:','alguém que age movido pelo coração e pelas relações pessoais, não pela impessoalidade',['alguém sempre gentil e educado','um funcionário público exemplar','um trabalhador alienado'],'"Cordial" vem de <i>cor, cordis</i> (coração), não de gentileza.'],['Florestan Fernandes criticou a ideia de democracia racial porque:','mostrou que a população negra foi marginalizada após a abolição',['defendia a escravidão','acreditava que não havia racismo no Brasil','era contra a miscigenação'],'Desigualdade racial persistente.']]}),
SKL('sociocontemp','Sociologia contemporânea','📱','Bauman: modernidade líquida (relações frágeis e instáveis). Bourdieu: capital cultural, habitus e violência simbólica. Globalização, sociedade em rede e sociedade de consumo.',
`<ul><li><b>Zygmunt Bauman</b>: <b>modernidade líquida</b> — relações, empregos e identidades frágeis e instáveis; consumo e individualismo.</li><li><b>Pierre Bourdieu</b>: <b>capital cultural</b> (conhecimentos, gostos e diplomas herdados da família), <b>habitus</b> (disposições incorporadas) e <b>violência simbólica</b> (imposição da cultura dominante como natural). A escola pode reproduzir desigualdades.</li><li><b>Manuel Castells</b>: <b>sociedade em rede</b>, organizada por fluxos de informação.</li><li><b>Sociedade de consumo</b> e <b>indústria cultural</b>; bolhas e desinformação nas redes sociais.</li><li><b>Gênero</b>: diferença entre sexo biológico e papéis sociais construídos.</li></ul>`,
{pairs:[['Modernidade líquida','conceito de Bauman para relações e identidades frágeis e instáveis'],['Capital cultural','conhecimentos, gostos e diplomas que dão vantagem social, segundo Bourdieu'],['Habitus','disposições incorporadas pela socialização que orientam o comportamento'],['Violência simbólica','imposição da cultura dominante como se fosse natural'],['Sociedade em rede','sociedade organizada por fluxos de informação digital (Castells)'],['Zygmunt Bauman','sociólogo da modernidade líquida'],['Pierre Bourdieu','sociólogo do capital cultural e da violência simbólica']],
 qs:[['Para Bourdieu, filhos de famílias com mais livros, museus e viagens tendem a ir melhor na escola porque herdam:','capital cultural',['mais-valia','solidariedade mecânica','dominação carismática'],'A escola valoriza a cultura das classes dominantes.'],['A ideia de que hoje os vínculos afetivos e profissionais são frágeis e passageiros corresponde à:','modernidade líquida de Bauman',['solidariedade orgânica de Durkheim','ética protestante de Weber','luta de classes de Marx'],'Nada é feito para durar.']]})
]});

const GLOSS=autoGloss(UNITS,[
 {k:['fato social'],n:'Fato social',s:'socio',t:'Para Durkheim, maneira de agir, pensar e sentir exterior ao indivíduo, coercitiva e geral — como a língua, as leis e a moda.'},
 {k:['caverna','mito da caverna','alegoria da caverna'],n:'Mito da caverna',s:'platao',t:'Alegoria de Platão: prisioneiros veem sombras e as tomam pela realidade; o filósofo se liberta, conhece a verdade (o Sol, a Ideia do Bem) e volta para libertar os outros.'},
 {k:['imperativo categorico','kant'],n:'Imperativo categórico',s:'etica',t:'Kant: "Age apenas segundo uma máxima que possas querer que se torne lei universal" e trata as pessoas sempre como fim, nunca só como meio.'},
 {k:['falacia','falacias'],n:'Falácias',s:'logica',t:'Argumentos que parecem válidos, mas são falhos: ad hominem, espantalho, apelo à autoridade, falsa dicotomia, generalização apressada, ladeira escorregadia.'}]);
