const BRAND={app:'SaberLingo',chatPh:'ex.: o que é escala?',tutor:'Professor Milton',sym:'N',body:'#2b70c9',dark:'#1f569e',belly:'#ddeaff',lsKey:'geolingo_v1',first:'coord',
 welcome:'Geografia <b>física, humana e do Brasil</b>: cartografia com cálculos de escala e fuso horário, clima, relevo, população, economia, geopolítica e ambiente.',
 range:'do Fundamental ao Ensino Médio (ENEM e vestibulares)',searchEx:'ex.: fuso horário',firstName:'Coordenadas geográficas',
 chips:['Como calcular escala?','Fuso horário','Climas do Brasil','Placas tectônicas','O que é globalização?','Biomas e domínios'],
 askEx:'<i>"o que é latitude?"</i>, <i>"El Niño"</i>, <i>"Mercosul"</i>',
 formulas:'escala (distância real = distância no mapa × escala) e fuso horário (15° = 1 hora)'};
const UNITS=[];

/* ---------- geradores de Geografia ---------- */
const UF=[['Acre','Rio Branco','Norte'],['Alagoas','Maceió','Nordeste'],['Amapá','Macapá','Norte'],['Amazonas','Manaus','Norte'],['Bahia','Salvador','Nordeste'],['Ceará','Fortaleza','Nordeste'],['Espírito Santo','Vitória','Sudeste'],['Goiás','Goiânia','Centro-Oeste'],['Maranhão','São Luís','Nordeste'],['Mato Grosso','Cuiabá','Centro-Oeste'],['Mato Grosso do Sul','Campo Grande','Centro-Oeste'],['Minas Gerais','Belo Horizonte','Sudeste'],['Pará','Belém','Norte'],['Paraíba','João Pessoa','Nordeste'],['Paraná','Curitiba','Sul'],['Pernambuco','Recife','Nordeste'],['Piauí','Teresina','Nordeste'],['Rio de Janeiro','Rio de Janeiro','Sudeste'],['Rio Grande do Norte','Natal','Nordeste'],['Rio Grande do Sul','Porto Alegre','Sul'],['Rondônia','Porto Velho','Norte'],['Roraima','Boa Vista','Norte'],['Santa Catarina','Florianópolis','Sul'],['São Paulo','São Paulo','Sudeste'],['Sergipe','Aracaju','Nordeste'],['Tocantins','Palmas','Norte']];
const REG=['Norte','Nordeste','Centro-Oeste','Sudeste','Sul'];
const lonLab=l=>l===0?'0° (Greenwich)':`${Math.abs(l)}° ${l<0?'O':'L'}`;
const hLab=h=>`${((h%24)+24)%24}h`;
const geoGens={
 escala:lv=>{ const E=pick([50000,100000,200000,250000,500000,1000000,2000000,5000000,10000000]),t=R(0,2);
   if(t===0){ const d=R(2,12),km=round(d*E/100000,3); return NUM(`Num mapa de escala <b>1 : ${nf(E)}</b>, duas cidades estão a <b>${d} cm</b> uma da outra. Qual é a distância real, em km?`,km,`1 cm no mapa = ${nf(E)} cm reais = ${nf(E/100000)} km. Logo ${d} × ${nf(E/100000)} = <b>${nf(km)} km</b>.`,'Multiplique a distância do mapa pelo denominador da escala e converta cm → km (÷ 100 000).',{unit:'km'}); }
   if(t===1){ const d=R(2,15),km=round(d*E/100000,3); return NUM(`Duas cidades estão a <b>${nf(km)} km</b> de distância. Num mapa de escala <b>1 : ${nf(E)}</b>, quantos centímetros as separam?`,d,`1 cm = ${nf(E/100000)} km → ${nf(km)} ÷ ${nf(E/100000)} = <b>${d} cm</b>.`,'Descubra quantos km vale 1 cm e divida.',{unit:'cm'}); }
   const d=R(2,10),km=round(d*E/100000,3); return MC(`No mapa, <b>${d} cm</b> representam <b>${nf(km)} km</b> reais. Qual é a escala do mapa?`,`1 : ${nf(E)}`,[`1 : ${nf(E*10)}`,`1 : ${nf(E/10)}`,`1 : ${nf(E*d)}`,`1 : ${nf(Math.round(km))}`],`${nf(km)} km = ${nf(km*100000)} cm; ${nf(km*100000)} ÷ ${d} = ${nf(E)} → <b>1 : ${nf(E)}</b>.`,'Converta km para cm (× 100 000) e divida pela distância do mapa.'); },
 fuso:lv=>{ const a=pick([-75,-60,-45,-30,0,15,30,45,60,90,120,135]); let b; do{ b=pick([-120,-90,-75,-60,-45,-30,0,15,30,45,60,90,120,135,150]); }while(b===a);
   const h=R(0,23),hb=h+(b-a)/15;
   return MC(`A cidade A (longitude ${lonLab(a)}) está às <b>${hLab(h)}</b>. Que horas são na cidade B (longitude ${lonLab(b)}), considerando só os fusos teóricos?`,hLab(hb),[hLab(h-(b-a)/15),hLab(hb+1),hLab(hb-1),hLab(h+Math.abs(b-a)/15+2)],`Diferença: ${Math.abs(b-a)}° ÷ 15° = ${Math.abs(b-a)/15} h. B está a ${b>a?'leste (horas adiantadas)':'oeste (horas atrasadas)'}: ${hLab(h)} ${b>a?'+':'−'} ${Math.abs(b-a)/15} h = <b>${hLab(hb)}</b>.`,'Cada 15° de longitude = 1 hora. Para leste, as horas aumentam; para oeste, diminuem.'); },
 capital:lv=>{ const [e,c]=pick(UF); return MC(`Qual é a capital do estado de <b>${e}</b>?`,c,shuffle(UF.filter(x=>x[0]!==e)).map(x=>x[1]),`A capital de ${e} é <b>${c}</b>.`,'Lembre-se da região do estado para eliminar opções.'); },
 capital2:lv=>{ const [e,c]=pick(UF); return MC(`<b>${c}</b> é a capital de qual estado?`,e,shuffle(UF.filter(x=>x[0]!==e)).map(x=>x[0]),`${c} é a capital de <b>${e}</b>.`,'Pense na região em que fica a cidade.'); },
 regiao:lv=>{ const [e,,r]=pick(UF); return MC(`Segundo a divisão do IBGE, o estado de <b>${e}</b> pertence à região:`,r,REG.filter(x=>x!==r),`${e} fica na região <b>${r}</b>.`,'O Brasil tem 5 regiões do IBGE: Norte, Nordeste, Centro-Oeste, Sudeste e Sul.'); }
};

/* ------------------------ UNIDADE 1 — CARTOGRAFIA ------------------------ */
UNITS.push({id:'g1',title:'Cartografia',sub:'Orientação, coordenadas, escala, fusos horários e projeções',color:'#2b70c9',dark:'#1f569e',skills:[
SKL('coord','Orientação e coordenadas','🧭','Latitude: distância em graus até o Equador (0° a 90° N ou S). Longitude: distância até o meridiano de Greenwich (0° a 180° L ou O).',
`<p><b>Rosa dos ventos</b>: pontos cardeais (N, S, L, O), colaterais (NE, NO, SE, SO) e subcolaterais. O Sol nasce a leste (nascente) e se põe a oeste (poente).</p>
<h3>Coordenadas geográficas</h3><ul><li><b>Paralelos</b>: linhas horizontais; o principal é a <b>Linha do Equador</b> (0°), que divide a Terra em hemisférios Norte e Sul. Outros: Trópicos de Câncer e de <b>Capricórnio</b> (≈ 23°27'; o de Capricórnio passa por São Paulo) e Círculos Polares.</li><li><b>Latitude</b>: 0° a 90° Norte ou Sul.</li><li><b>Meridianos</b>: linhas de polo a polo; o principal é o de <b>Greenwich</b> (0°), que divide os hemisférios Leste (Oriental) e Oeste (Ocidental).</li><li><b>Longitude</b>: 0° a 180° Leste ou Oeste.</li></ul>
<p>O Brasil tem terras nos hemisférios Norte e Sul, mas está todo no hemisfério <b>Ocidental</b>. Hoje a localização precisa é feita por <b>GPS</b> (satélites).</p>`,
{pairs:[['Linha do Equador','paralelo 0°, que divide a Terra em hemisférios Norte e Sul'],['Meridiano de Greenwich','meridiano 0°, que divide a Terra em hemisférios Leste e Oeste'],['Latitude','distância em graus de um ponto até a Linha do Equador'],['Longitude','distância em graus de um ponto até o meridiano de Greenwich'],['Trópico de Capricórnio','paralelo de cerca de 23°27\' S, que passa pelo estado de São Paulo'],['Nordeste (NE)','ponto colateral entre o norte e o leste'],['GPS','sistema de posicionamento por satélites']],
 qs:[['O Brasil está localizado totalmente no hemisfério:','Ocidental',['Oriental','Norte','Sul'],'Todo o território fica a oeste de Greenwich.'],['Uma cidade com latitude 0° está:','sobre a Linha do Equador',['sobre Greenwich','no Polo Norte','no Trópico de Capricórnio'],'Latitude 0° = Equador.'],['A longitude pode variar de:','0° a 180° para leste ou oeste',['0° a 90° para norte ou sul','0° a 360° só para leste','0° a 23° para qualquer lado'],'Longitude: 0° a 180° L ou O.'],['Ao fim da tarde, uma pessoa olha para o pôr do sol. Ela está olhando para o:','oeste',['leste','norte','sul'],'O Sol se põe a <b>oeste</b>.']]}),
SKL('escala','Escala cartográfica','📏','Escala 1 : 100 000 → 1 cm no mapa = 100 000 cm = 1 km real. Escala grande (denominador pequeno) mostra mais detalhes de uma área menor.',
`<p><b>Escala</b> é a relação entre a distância no mapa e a distância real.</p><div class="formula">D (real) = d (mapa) × E</div>
<ul><li><b>Numérica</b>: 1 : 500 000 (1 cm = 500 000 cm = 5 km).</li><li><b>Gráfica</b>: uma barra graduada (útil ao ampliar/reduzir o mapa).</li></ul>
<div class="ex">Conversão: km → cm: multiplique por 100 000 (1 km = 1 000 m = 100 000 cm).</div>
<p><b>Escala grande</b> (1 : 10 000): denominador pequeno, área pequena com <b>muitos detalhes</b> (planta de cidade). <b>Escala pequena</b> (1 : 50 000 000): denominador grande, área grande com poucos detalhes (planisfério).</p>`,
{gens:[geoGens.escala,geoGens.escala,geoGens.escala,geoGens.escala],qs:[['Qual escala é mais adequada para a planta de um bairro, com muitos detalhes?','1 : 5 000',['1 : 50 000 000','1 : 10 000 000','1 : 1 000 000'],'Escala grande (denominador pequeno) = mais detalhes.'],['Numa escala 1 : 100 000, 1 cm no mapa corresponde a:','1 km',['100 m','10 km','100 km'],'100 000 cm = 1 000 m = 1 km.']]}),
SKL('fuso','Fusos horários','🕐','A Terra gira 360° em 24 h → 15° por hora. A leste as horas estão adiantadas; a oeste, atrasadas. O Brasil tem 4 fusos (−2 a −5 em relação a Greenwich).',
`<p>A Terra gira 360° em cerca de 24 horas: <b>360° ÷ 24 = 15° por hora</b>. Por isso existem 24 fusos teóricos a partir de Greenwich (GMT/UTC 0).</p>
<ul><li>Para <b>leste</b>, as horas são <b>adiantadas</b> (o Sol "chega antes").</li><li>Para <b>oeste</b>, as horas são <b>atrasadas</b>.</li></ul>
<div class="ex">Brasília (≈ 45° O, UTC −3) às 12h → Londres (0°) às 15h; Tóquio (UTC +9) à 0h do dia seguinte.</div>
<p>Os fusos <b>práticos</b> seguem fronteiras políticas. O Brasil tem <b>4 fusos</b>: UTC −2 (Fernando de Noronha), −3 (Brasília, a maior parte), −4 (Amazonas, MT, MS, RO, RR) e −5 (Acre e oeste do Amazonas). A <b>Linha Internacional de Data</b> (≈ 180°) marca a mudança do dia.</p>`,
{gens:[geoGens.fuso,geoGens.fuso,geoGens.fuso,geoGens.fuso],qs:[['Quantos fusos horários tem o território brasileiro?','4',['3','2','5'],'UTC −2, −3, −4 e −5.'],['Por que cada fuso horário tem 15° de largura?','porque a Terra gira 360° em 24 horas',['porque existem 15 continentes','por convenção sem relação com a rotação','porque o Brasil tem 15 estados no litoral'],'360 ÷ 24 = 15.']]}),
SKL('proj','Projeções e representações','🗺️','Mercator (cilíndrica, conforme): preserva formas e distorce áreas perto dos polos (Groenlândia gigante). Peters (equivalente): preserva áreas e distorce formas.',
`<p>Representar a Terra (quase esférica) num plano sempre gera distorções. Tipos de <b>projeção</b>:</p><ul><li><b>Cilíndrica</b>, <b>cônica</b> e <b>plana (azimutal)</b>, conforme a superfície de projeção.</li><li><b>Conforme</b>: preserva as formas/ângulos (Mercator, usada na navegação), mas distorce áreas — a Groenlândia parece do tamanho da América do Sul.</li><li><b>Equivalente</b>: preserva as áreas (Peters), mas distorce as formas.</li><li><b>Afilática</b>: não preserva nada integralmente, mas diminui as distorções (Robinson).</li></ul>
<p>Mapas também expressam <b>visões de mundo</b>: a Mercator é criticada por valorizar a Europa (eurocentrismo); a de Peters, por destacar os países do Sul.</p>
<h3>Outras representações</h3><p><b>Curvas de nível</b> (relevo: linhas próximas = terreno íngreme), mapas temáticos, anamorfoses (áreas proporcionais a um dado), imagens de satélite e <b>sensoriamento remoto</b>.</p>`,
{pairs:[['Projeção de Mercator','projeção cilíndrica conforme, que preserva formas e distorce áreas'],['Projeção de Peters','projeção equivalente, que preserva áreas e distorce formas'],['Projeção azimutal','projeção plana, centrada em um ponto'],['Curvas de nível','linhas que unem pontos de mesma altitude'],['Anamorfose','mapa em que a área dos países é proporcional a um dado estatístico'],['Sensoriamento remoto','obtenção de informações por imagens de satélite ou aéreas']],
 qs:[['Na projeção de Mercator, a Groenlândia parece quase do tamanho da América do Sul porque:','as áreas próximas aos polos são exageradas',['a Groenlândia é realmente maior','a projeção preserva as áreas','os polos ficam no centro do mapa'],'Mercator é conforme: distorce as áreas em altas latitudes.'],['Num mapa topográfico, curvas de nível muito próximas indicam:','um terreno muito inclinado',['uma planície','um rio','uma área urbana'],'Grande variação de altitude em pouca distância.']]})
]});

/* ------------------------ UNIDADE 2 — NATUREZA ------------------------ */
UNITS.push({id:'g2',title:'A natureza e o espaço',sub:'Estrutura da Terra, relevo, clima, hidrografia e domínios morfoclimáticos',color:'#58cc02',dark:'#58a700',skills:[
SKL('placas','Estrutura da Terra e placas tectônicas','🌋','Crosta, manto e núcleo. A crosta é dividida em placas tectônicas que se movem sobre o manto: nos limites ocorrem terremotos, vulcões e cordilheiras.',
`<p>Camadas: <b>crosta</b> (continental e oceânica), <b>manto</b> (magma pastoso) e <b>núcleo</b> (externo líquido e interno sólido, de ferro e níquel). A <b>litosfera</b> (crosta + parte superior do manto) é dividida em <b>placas tectônicas</b> movidas por correntes de convecção.</p>
<ul><li><b>Limite convergente</b>: placas se chocam — dobramentos modernos (Andes, Himalaia), vulcões, terremotos, fossas (subducção).</li><li><b>Limite divergente</b>: placas se afastam — dorsais oceânicas (Dorsal Mesoatlântica), formação de crosta nova.</li><li><b>Limite transformante</b>: placas deslizam lado a lado (Falha de San Andreas).</li></ul>
<p>O <b>Brasil</b> está no <b>centro da Placa Sul-Americana</b>, longe das bordas: não tem vulcões ativos nem cordilheiras recentes, e seus tremores são de baixa magnitude. A teoria da <b>deriva continental</b> (Wegener) propôs que os continentes formavam a <b>Pangeia</b>.</p>`,
{pairs:[['Placas tectônicas','grandes blocos da litosfera que se movem sobre o manto'],['Limite convergente','encontro de placas que forma cordilheiras, vulcões e fossas'],['Limite divergente','afastamento de placas que forma as dorsais oceânicas'],['Limite transformante','placas que deslizam lateralmente, como na Falha de San Andreas'],['Pangeia','supercontinente que reunia todas as terras emersas'],['Subducção','mergulho de uma placa sob outra'],['Núcleo','camada mais interna da Terra, formada principalmente por ferro e níquel']],
 qs:[['O Brasil tem poucos terremotos fortes porque:','fica no centro da Placa Sul-Americana, longe dos limites entre placas',['não possui placa tectônica','está sobre um limite divergente','tem muitas cordilheiras'],'A atividade sísmica forte ocorre nas bordas das placas.'],['A Cordilheira dos Andes foi formada:','pelo choque entre as placas de Nazca e Sul-Americana',['pela erosão do vento','por um limite divergente','pela ação de geleiras'],'Limite convergente com subducção.'],['A teoria que propôs a existência da Pangeia foi a:','deriva continental, de Alfred Wegener',['seleção natural','teoria do Big Bang','teoria heliocêntrica'],'Wegener, 1912.']]}),
SKL('relevo','Rochas e relevo','⛰️','Rochas: magmáticas (granito, basalto), sedimentares (arenito, calcário; guardam fósseis e petróleo) e metamórficas (mármore, gnaisse). Relevo brasileiro: planaltos, planícies e depressões.',
`<h3>Rochas</h3><ul><li><b>Magmáticas (ígneas)</b>: solidificação do magma — <b>granito</b> (intrusiva) e <b>basalto</b> (extrusiva, origem da terra roxa).</li><li><b>Sedimentares</b>: acúmulo de sedimentos — arenito, calcário; podem ter <b>fósseis, petróleo e carvão</b>.</li><li><b>Metamórficas</b>: transformadas por pressão e temperatura — <b>mármore</b> (de calcário), gnaisse (de granito), ardósia.</li></ul>
<h3>Agentes do relevo</h3><p><b>Internos</b> (endógenos): tectonismo, vulcanismo, abalos sísmicos. <b>Externos</b> (exógenos): intemperismo e erosão pela água, vento, gelo e seres vivos.</p>
<h3>Relevo brasileiro</h3><p>Antigo e desgastado, com altitudes modestas. Classificação de <b>Jurandyr Ross</b> (1989): <b>planaltos</b> (erosão supera a sedimentação), <b>planícies</b> (sedimentação supera a erosão) e <b>depressões</b> (áreas rebaixadas pela erosão). Ponto mais alto: <b>Pico da Neblina</b> (AM, quase 3 000 m).</p>`,
{pairs:[['Granito','rocha magmática intrusiva'],['Basalto','rocha magmática extrusiva que origina a terra roxa'],['Arenito','rocha sedimentar formada por grãos de areia'],['Mármore','rocha metamórfica originada do calcário'],['Intemperismo','desgaste e decomposição das rochas pela ação do clima e dos seres vivos'],['Erosão','remoção e transporte de sedimentos por água, vento ou gelo'],['Planície','forma de relevo em que a sedimentação supera a erosão'],['Planalto','forma de relevo em que a erosão supera a sedimentação'],['Pico da Neblina','ponto mais alto do Brasil, no Amazonas']],
 qs:[['O petróleo é encontrado principalmente em:','bacias sedimentares',['escudos cristalinos de granito','rochas metamórficas','vulcões ativos'],'Forma-se da matéria orgânica soterrada em sedimentos.'],['O relevo brasileiro tem altitudes modestas porque:','é muito antigo e foi desgastado por erosão por milhões de anos',['é formado por vulcões recentes','está no limite entre placas','é coberto por geleiras'],'Estruturas antigas e intensamente erodidas.']]}),
SKL('clima','Clima','🌦️','Fatores: latitude, altitude, maritimidade/continentalidade, correntes marítimas e massas de ar. Climas do Brasil: equatorial, tropical, tropical de altitude, tropical úmido, semiárido e subtropical.',
`<p><b>Tempo</b> é o estado momentâneo da atmosfera; <b>clima</b> é o padrão de longo prazo.</p>
<h3>Fatores</h3><ul><li><b>Latitude</b>: quanto mais longe do Equador, mais frio.</li><li><b>Altitude</b>: a temperatura cai cerca de 0,6 °C a cada 100 m.</li><li><b>Maritimidade × continentalidade</b>: o mar suaviza a amplitude térmica.</li><li><b>Correntes marítimas</b> (a fria de Humboldt contribui para o deserto do Atacama) e <b>massas de ar</b>.</li><li><b>Vegetação</b> e relevo.</li></ul>
<h3>Climas do Brasil</h3><ul><li><b>Equatorial</b> (Amazônia): quente e úmido o ano todo.</li><li><b>Tropical</b> (Centro-Oeste): verão chuvoso e inverno seco.</li><li><b>Tropical de altitude</b> (planaltos do Sudeste): temperaturas mais amenas, geadas ocasionais.</li><li><b>Tropical úmido (litorâneo)</b>: costa leste, chuvas abundantes.</li><li><b>Semiárido</b> (sertão nordestino): chuvas escassas e irregulares.</li><li><b>Subtropical</b> (Sul): quatro estações definidas, geadas e até neve nas serras.</li></ul>
<p><b>Massas de ar</b>: mEc (equatorial continental, quente e úmida), mTa (tropical atlântica), mTc (tropical continental, quente e seca), <b>mPa</b> (polar atlântica, fria; causa a <b>friagem</b> na Amazônia). <b>El Niño</b>: aquecimento anormal do Pacífico — no Brasil, secas no Norte/Nordeste e chuvas no Sul.</p>`,
{pairs:[['Clima equatorial','quente e úmido o ano todo, na Amazônia'],['Clima semiárido','chuvas escassas e irregulares, no sertão nordestino'],['Clima subtropical','quatro estações definidas e geadas, no Sul'],['Clima tropical de altitude','temperaturas amenas nos planaltos do Sudeste'],['Clima tropical','verão chuvoso e inverno seco, no Brasil central'],['Massa polar atlântica','massa de ar fria que causa quedas de temperatura e a friagem'],['El Niño','aquecimento anormal das águas do Pacífico que altera o clima global'],['Amplitude térmica','diferença entre a maior e a menor temperatura']],
 qs:[['Campos do Jordão (SP), a cerca de 1 600 m, é mais fria que Santos, no litoral, principalmente por causa da:','altitude',['latitude','longitude','maritimidade'],'A temperatura cai com a altitude.'],['Cidades no interior dos continentes costumam ter maior amplitude térmica que as litorâneas por causa da:','continentalidade',['maritimidade','latitude baixa','altitude baixa'],'Sem a influência moderadora do mar.'],['A diferença entre tempo e clima é que:','tempo é o estado momentâneo da atmosfera e clima é o padrão de longo prazo',['são sinônimos','clima muda a cada hora','tempo só existe no verão'],'Previsão do tempo × classificação climática.']]}),
SKL('hidro','Hidrografia','🌊','Bacia Amazônica: maior do mundo. São Francisco: "rio da integração nacional". Bacia do Paraná: maior aproveitamento hidrelétrico (Itaipu). Aquífero Guarani: grande reserva subterrânea.',
`<p><b>Bacia hidrográfica</b>: área drenada por um rio principal e seus afluentes. <b>Divisor de águas</b>: relevo que separa bacias.</p>
<ul><li><b>Amazônica</b>: maior bacia do mundo em área e volume de água; rios de planície (bons para navegação).</li><li><b>Tocantins-Araguaia</b>: usina de Tucuruí.</li><li><b>São Francisco</b>: nasce na Serra da Canastra (MG), atravessa o semiárido — "rio da integração nacional"; transposição para o Nordeste setentrional.</li><li><b>Paraná</b>: maior aproveitamento hidrelétrico (Itaipu, binacional com o Paraguai).</li><li><b>Aquífero Guarani</b>: uma das maiores reservas de água subterrânea do mundo (Brasil, Argentina, Paraguai e Uruguai).</li></ul>
<p>Os rios brasileiros são majoritariamente <b>de planalto</b> (grande potencial hidrelétrico) e de regime <b>pluvial</b> (alimentados pela chuva).</p>`,
{pairs:[['Bacia Amazônica','maior bacia hidrográfica do mundo'],['Rio São Francisco','chamado de "rio da integração nacional"'],['Bacia do Paraná','bacia com a usina de Itaipu e o maior aproveitamento hidrelétrico'],['Aquífero Guarani','grande reserva de água subterrânea compartilhada por quatro países'],['Divisor de águas','terreno elevado que separa duas bacias'],['Afluente','rio que deságua em outro rio'],['Usina de Tucuruí','hidrelétrica na bacia do Tocantins-Araguaia']],
 qs:[['Os rios brasileiros têm grande potencial hidrelétrico porque:','a maioria é de planalto, com desníveis',['todos são de planície','são alimentados por geleiras','correm em áreas desérticas'],'Desníveis permitem gerar energia.'],['O Rio São Francisco é importante para o semiárido porque:','é perene e atravessa a região seca',['é intermitente','nasce na Amazônia','deságua no Pacífico'],'Fonte de água constante no sertão.']]}),
SKL('dominios','Vegetação e domínios morfoclimáticos','🌳','Aziz Ab\'Sáber: domínios Amazônico, dos Cerrados, dos Mares de Morros, das Caatingas, das Araucárias e das Pradarias, com faixas de transição.',
`<p><b>Aziz Ab'Sáber</b> dividiu o Brasil em <b>domínios morfoclimáticos</b>, combinando relevo, clima, solo, vegetação e hidrografia:</p>
<ul><li><b>Amazônico</b>: terras baixas florestadas, clima equatorial.</li><li><b>Cerrados</b>: chapadões do Brasil central, clima tropical com seca marcada.</li><li><b>Mares de Morros</b>: morros arredondados da costa leste com Mata Atlântica.</li><li><b>Caatingas</b>: depressões semiáridas com vegetação xerófila.</li><li><b>Araucárias</b>: planaltos do Sul com mata de pinheiros.</li><li><b>Pradarias</b>: coxilhas do Rio Grande do Sul com campos.</li></ul>
<p>Entre eles há <b>faixas de transição</b> (ex.: Mata dos Cocais, Pantanal). Formações litorâneas: <b>manguezais</b> (berçários marinhos) e <b>restingas</b>.</p>`,
{pairs:[['Domínio Amazônico','terras baixas florestadas e clima equatorial'],['Domínio dos Cerrados','chapadões com vegetação de savana e seca marcada'],['Domínio dos Mares de Morros','morros arredondados da costa leste, com Mata Atlântica'],['Domínio das Caatingas','depressões semiáridas com vegetação adaptada à seca'],['Domínio das Araucárias','planaltos do Sul com mata de pinheiros'],['Domínio das Pradarias','coxilhas gaúchas cobertas por campos'],['Mata dos Cocais','faixa de transição com babaçu e carnaúba no Maranhão e Piauí'],['Manguezal','ecossistema litorâneo de água salobra, berçário de espécies marinhas']],
 qs:[['A classificação dos domínios morfoclimáticos brasileiros foi proposta por:','Aziz Ab\'Sáber',['Jurandyr Ross','Milton Santos','Josué de Castro'],'Considera relevo, clima, solo e vegetação juntos.'],['O Pantanal, na classificação de Ab\'Sáber, é considerado:','uma faixa de transição',['um domínio de mares de morros','parte do domínio amazônico','um deserto'],'Mistura elementos de vários domínios.']]})
]});

/* ------------------------ UNIDADE 3 — BRASIL ------------------------ */
UNITS.push({id:'g3',title:'Brasil: território e sociedade',sub:'Estados e regiões, população, migrações e urbanização',color:'#ff9600',dark:'#e07b00',skills:[
SKL('estados','Estados, capitais e regiões','📍','O Brasil tem 26 estados e o Distrito Federal (Brasília), agrupados pelo IBGE em 5 regiões: Norte, Nordeste, Centro-Oeste, Sudeste e Sul.',
`<p>O Brasil é uma <b>federação</b> com <b>26 estados e o Distrito Federal</b>. O IBGE os agrupa em <b>cinco regiões</b>:</p>
<ul><li><b>Norte</b> (7): AC, AP, AM, PA, RO, RR, TO — maior região, menor densidade.</li><li><b>Nordeste</b> (9): AL, BA, CE, MA, PB, PE, PI, RN, SE.</li><li><b>Centro-Oeste</b>: GO, MT, MS e DF.</li><li><b>Sudeste</b> (4): ES, MG, RJ, SP — mais populosa e industrializada.</li><li><b>Sul</b> (3): PR, SC, RS.</li></ul>
<p>Outra divisão, dos <b>complexos regionais</b> (Pedro Geiger), usa critérios econômicos: <b>Amazônia</b>, <b>Nordeste</b> e <b>Centro-Sul</b>, sem seguir limites estaduais.</p>
<p>O Brasil é o 5º maior país do mundo em área (≈ 8,5 milhões de km²) e faz fronteira com todos os países da América do Sul, exceto Chile e Equador.</p>`,
{gens:[geoGens.capital,geoGens.capital,geoGens.capital2,geoGens.regiao,geoGens.regiao],qs:[['Quais países sul-americanos NÃO fazem fronteira com o Brasil?','Chile e Equador',['Peru e Bolívia','Uruguai e Paraguai','Colômbia e Venezuela'],'O Brasil faz fronteira com 10 países.'],['A divisão em complexos regionais (Amazônia, Nordeste, Centro-Sul) se baseia:','em critérios socioeconômicos, sem seguir os limites dos estados',['apenas nos limites estaduais','somente no clima','na religião predominante'],'Proposta por Pedro Geiger (1967).']]}),
SKL('populacao','População brasileira','👥','Transição demográfica: queda da natalidade e da mortalidade, envelhecimento da população. A pirâmide etária está se estreitando na base e alargando no topo.',
`<p>O Censo de 2022 contou cerca de <b>203 milhões</b> de habitantes: o Brasil é <b>populoso</b> (população absoluta alta), mas <b>pouco povoado</b> (densidade relativamente baixa), com forte concentração no litoral e no Sudeste.</p>
<h3>Transição demográfica</h3><p>Com urbanização, entrada da mulher no mercado de trabalho, métodos contraceptivos e acesso à saúde, a <b>taxa de natalidade</b> e a <b>de fecundidade</b> caíram (hoje abaixo de 2,1 filhos por mulher, o nível de reposição). A mortalidade também caiu e a <b>expectativa de vida</b> aumentou. Resultado: <b>envelhecimento</b> — a pirâmide etária tem base mais estreita e topo mais largo.</p>
<p><b>Bônus demográfico</b>: fase com grande proporção de pessoas em idade de trabalhar. <b>IDH</b> mede renda, educação e longevidade.</p>
<p>Formação: indígenas, europeus, africanos escravizados e imigrantes (italianos, alemães, japoneses, sírio-libaneses…).</p>`,
{pairs:[['Transição demográfica','passagem de altas para baixas taxas de natalidade e mortalidade'],['População absoluta','número total de habitantes'],['Densidade demográfica','número de habitantes por km²'],['Taxa de fecundidade','número médio de filhos por mulher'],['Envelhecimento populacional','aumento da proporção de idosos na população'],['Bônus demográfico','fase com grande proporção de pessoas em idade ativa'],['IDH','índice que combina renda, educação e expectativa de vida']],
 qs:[['Dizer que o Brasil é "populoso, mas pouco povoado" significa que:','tem muitos habitantes, mas baixa densidade demográfica',['tem poucos habitantes e alta densidade','tem população pequena e concentrada','tem alta densidade em todo o território'],'População absoluta alta, relativa baixa.'],['Uma pirâmide etária de base estreita e topo largo indica:','baixa natalidade e envelhecimento',['alta natalidade e juventude','guerra recente','imigração de crianças'],'Poucos nascimentos e muitos idosos.']]}),
SKL('migracao','Migrações','🚚','Êxodo rural (campo → cidade), migração nordestina para o Sudeste (séc. XX), expansão para o Centro-Oeste e Norte, e hoje migração de retorno e refugiados (venezuelanos, haitianos).',
`<ul><li><b>Êxodo rural</b>: saída do campo para as cidades, intensa entre 1950 e 1980 (mecanização, concentração de terras, atração da indústria).</li><li><b>Nordeste → Sudeste</b>: fuga da seca e da pobreza, busca de emprego industrial em SP e RJ.</li><li><b>Expansão para o Centro-Oeste e o Norte</b>: construção de Brasília, fronteira agrícola, projetos de colonização.</li><li><b>Migração de retorno</b>: nordestinos voltando à região (desconcentração industrial).</li><li><b>Migração pendular</b>: deslocamento diário casa–trabalho entre cidades.</li><li><b>Imigração recente</b>: haitianos, venezuelanos (Operação Acolhida em Roraima), bolivianos.</li><li><b>Refugiados</b>: pessoas forçadas a deixar seu país por guerras ou perseguições.</li></ul>`,
{pairs:[['Êxodo rural','migração do campo para as cidades'],['Migração pendular','deslocamento diário entre a cidade onde se mora e a cidade onde se trabalha'],['Migração de retorno','volta de migrantes para a região de origem'],['Transumância','migração sazonal ligada às estações do ano ou colheitas'],['Refugiado','pessoa forçada a deixar seu país por guerra ou perseguição'],['Emigração','saída de pessoas de um país']],
 qs:[['A principal causa do êxodo rural brasileiro entre 1950 e 1980 foi:','a mecanização do campo e a concentração fundiária, somadas à atração das indústrias',['a falta de terras nas cidades','a construção de hidrelétricas na Amazônia','o fim da escravidão'],'Expulsão do campo + atração da cidade.'],['Trabalhadores que moram em Guarulhos e trabalham todo dia em São Paulo fazem migração:','pendular',['sazonal','de retorno','internacional'],'Ida e volta diárias.']]}),
SKL('urbano','Urbanização','🏙️','Urbanização brasileira acelerada e desigual: metrópoles, conurbação, megalópole Rio–São Paulo, segregação socioespacial e favelização.',
`<p>O Brasil passou a ser majoritariamente urbano nos anos 1960; hoje mais de 80% da população vive em cidades. A urbanização foi <b>rápida e sem planejamento</b>.</p>
<ul><li><b>Metrópole</b>: grande cidade que polariza uma região. <b>Região metropolitana</b>: conjunto de municípios integrados.</li><li><b>Conurbação</b>: cidades vizinhas que crescem e se unem fisicamente.</li><li><b>Megalópole</b>: união de metrópoles (eixo Rio–São Paulo em formação).</li><li><b>Rede urbana</b> e <b>hierarquia urbana</b> (metrópoles, capitais regionais, centros sub-regionais).</li></ul>
<h3>Problemas urbanos</h3><p><b>Segregação socioespacial</b>, favelização, déficit habitacional, trânsito, poluição, enchentes, <b>ilhas de calor</b>, <b>gentrificação</b> (expulsão de moradores pobres de áreas valorizadas).</p>`,
{pairs:[['Conurbação','junção física de cidades vizinhas'],['Megalópole','união de grandes metrópoles, como o eixo Rio–São Paulo'],['Metrópole','cidade grande que polariza uma região'],['Segregação socioespacial','separação das classes sociais no espaço da cidade'],['Gentrificação','valorização de uma área que expulsa os moradores mais pobres'],['Ilha de calor','temperatura mais alta no centro das cidades, por asfalto e concreto'],['Rede urbana','conjunto de cidades interligadas por fluxos de pessoas, bens e informações']],
 qs:[['A urbanização brasileira foi marcada por:','crescimento rápido e desordenado, com desigualdade',['crescimento lento e planejado','redução da população urbana','ausência de problemas habitacionais'],'Acelerada a partir de 1950–60.'],['Santo André, São Bernardo e São Paulo formam uma mancha urbana contínua. Isso é:','conurbação',['megalópole','gentrificação','êxodo rural'],'Cidades vizinhas "grudadas".']]})
]});

/* ------------------------ UNIDADE 4 — ECONOMIA E MUNDO ------------------------ */
UNITS.push({id:'g4',title:'Economia e mundo globalizado',sub:'Agropecuária, indústria, energia, globalização, blocos e geopolítica',color:'#ce82ff',dark:'#a568cc',skills:[
SKL('agro','Espaço agrário','🚜','Estrutura fundiária concentrada (latifúndios), agronegócio exportador (soja, milho, carne), fronteira agrícola avançando sobre Cerrado e Amazônia, agricultura familiar e conflitos pela terra.',
`<ul><li><b>Estrutura fundiária concentrada</b>: poucos grandes proprietários detêm grande parte das terras — herança das sesmarias e da Lei de Terras (1850).</li><li><b>Agronegócio</b>: cadeia que liga agropecuária, indústria e serviços; alta tecnologia e exportação de <b>commodities</b> (soja, milho, carne, café, açúcar).</li><li><b>Fronteira agrícola</b>: avança sobre o Cerrado e a Amazônia; <b>MATOPIBA</b> (Maranhão, Tocantins, Piauí, Bahia).</li><li><b>Agricultura familiar</b>: pequenas propriedades, produção importante de alimentos para o mercado interno.</li><li><b>Revolução Verde</b>: sementes melhoradas, fertilizantes, agrotóxicos e mecanização — aumentou a produção, mas trouxe impactos ambientais e concentração.</li><li><b>Conflitos</b>: disputas por terra, grilagem, reforma agrária e movimentos como o MST.</li></ul>`,
{pairs:[['Agronegócio','cadeia que integra agropecuária, indústria e serviços, muito voltada à exportação'],['Commodity','produto primário negociado em grande escala no mercado mundial'],['MATOPIBA','fronteira agrícola formada por Maranhão, Tocantins, Piauí e Bahia'],['Agricultura familiar','produção em pequenas propriedades com trabalho da família'],['Revolução Verde','modernização agrícola com sementes melhoradas, fertilizantes e agrotóxicos'],['Grilagem','falsificação de documentos para se apropriar de terras'],['Estrutura fundiária','forma como a terra está distribuída entre os proprietários']],
 qs:[['A estrutura fundiária brasileira é marcada:','pela concentração de terras em grandes propriedades',['pela divisão igual das terras','pelo predomínio de minifúndios coletivos','pela ausência de propriedade privada'],'Herança colonial.'],['O principal produto agrícola de exportação do Brasil nas últimas décadas é:','a soja',['o trigo','a borracha','o cacau'],'A soja lidera as exportações do agronegócio.']]}),
SKL('industria','Indústria e energia','⚡','Indústria concentrada no Sudeste (SP), com desconcentração recente. Matriz elétrica brasileira majoritariamente renovável (hidrelétricas, eólica, solar); pré-sal ampliou a produção de petróleo.',
`<ul><li><b>Industrialização tardia</b>: café financiou o início; Vargas (indústria de base), JK (bens de consumo duráveis, capital estrangeiro), militares (grandes obras).</li><li><b>Concentração no Sudeste</b>, especialmente em São Paulo; <b>desconcentração</b> recente para o interior e outras regiões (incentivos fiscais, "guerra fiscal", mão de obra mais barata). <b>Zona Franca de Manaus</b> (1967).</li><li><b>Energia</b>: a matriz <b>elétrica</b> brasileira é majoritariamente <b>renovável</b> (mais de 80%), com destaque para as <b>hidrelétricas</b> e o crescimento de <b>eólica</b> (Nordeste) e <b>solar</b>. Na matriz energética total, petróleo e derivados ainda são importantes; o <b>pré-sal</b> (litoral do Sudeste) aumentou a produção. <b>Etanol</b> da cana e biodiesel são destaques.</li></ul>
<p>Renováveis: hídrica, eólica, solar, biomassa. Não renováveis: petróleo, carvão, gás natural, urânio.</p>`,
{pairs:[['Energia hidrelétrica','principal fonte da matriz elétrica brasileira'],['Energia eólica','energia dos ventos, em forte expansão no Nordeste'],['Pré-sal','reservas de petróleo em grandes profundidades no litoral brasileiro'],['Zona Franca de Manaus','polo industrial com incentivos fiscais criado em 1967'],['Guerra fiscal','disputa entre estados por indústrias com a oferta de incentivos'],['Desconcentração industrial','dispersão das indústrias para fora dos grandes centros'],['Fonte não renovável','fonte que se esgota, como petróleo, carvão e gás natural']],
 qs:[['A matriz elétrica brasileira se destaca no mundo por:','ser majoritariamente renovável',['depender quase só do carvão','ser totalmente nuclear','não usar hidrelétricas'],'Hidrelétricas, eólica, solar e biomassa.'],['Um impacto socioambiental das grandes hidrelétricas é:','a inundação de áreas e o deslocamento de populações',['a emissão de enormes quantidades de fumaça','a produção de lixo radioativo','o fim da navegação em todos os rios'],'Ex.: Belo Monte, Tucuruí.']]}),
SKL('global','Globalização e blocos econômicos','🌐','Globalização: integração mundial de economias, informações e culturas, com empresas transnacionais e fluxos rápidos. Blocos: Mercosul, União Europeia, USMCA, BRICS.',
`<p>A <b>globalização</b> intensificou os fluxos de mercadorias, capitais, informações e pessoas, graças à revolução técnico-científico-informacional (Milton Santos). Atores: <b>empresas transnacionais</b>, organismos como OMC, FMI e Banco Mundial.</p>
<p>Efeitos: maior interdependência, padronização cultural, desigualdades entre países e dentro deles, <b>divisão internacional do trabalho</b> (países que exportam commodities × produtos industrializados).</p>
<h3>Blocos</h3><ul><li><b>União Europeia</b>: bloco mais integrado (mercado comum, livre circulação, euro). O Reino Unido saiu (Brexit, 2020).</li><li><b>Mercosul</b> (1991, Tratado de Assunção): Brasil, Argentina, Paraguai e Uruguai como fundadores; união aduaneira imperfeita.</li><li><b>USMCA</b>: EUA, México e Canadá (substituiu o NAFTA em 2020).</li><li><b>BRICS</b>: Brasil, Rússia, Índia, China e África do Sul, ampliado com novos membros a partir de 2024.</li><li><b>APEC</b>: cooperação da Ásia-Pacífico.</li></ul>`,
{pairs:[['Globalização','intensificação dos fluxos de mercadorias, capitais, informações e pessoas no mundo'],['Empresa transnacional','empresa com atuação em vários países'],['União Europeia','bloco com mercado comum, livre circulação e moeda única (euro)'],['Mercosul','bloco criado em 1991 pelo Tratado de Assunção'],['USMCA','acordo entre EUA, México e Canadá que substituiu o NAFTA'],['BRICS','grupo de economias emergentes formado inicialmente por Brasil, Rússia, Índia, China e África do Sul'],['Brexit','saída do Reino Unido da União Europeia'],['OMC','organização que regula o comércio internacional']],
 qs:[['Os países fundadores do Mercosul foram:','Brasil, Argentina, Paraguai e Uruguai',['Brasil, Chile, Peru e Colômbia','Brasil, México, Argentina e Chile','Brasil, Venezuela, Bolívia e Equador'],'Tratado de Assunção, 1991.'],['O bloco econômico com maior nível de integração, com moeda única, é:','a União Europeia',['o Mercosul','o USMCA','a APEC'],'Mercado comum e união monetária (euro).']]}),
SKL('geopol','Geopolítica e desenvolvimento','🏳️','Da ordem bipolar (Guerra Fria) à multipolar. Conflitos atuais envolvem território, recursos, etnias e religião (Oriente Médio, Rússia × Ucrânia). IDH e desigualdade separam países desenvolvidos e subdesenvolvidos.',
`<ul><li><b>Ordem bipolar</b> (1947–1991): EUA × URSS. Depois, uma fase de hegemonia americana e hoje uma ordem <b>multipolar</b>, com a ascensão da China, a União Europeia, a Rússia e potências regionais.</li><li><b>Norte × Sul</b>: países desenvolvidos (alto IDH, economia diversificada) e subdesenvolvidos ou emergentes (dependência de commodities, desigualdade). A divisão não segue exatamente o hemisfério (a Austrália é desenvolvida).</li><li><b>Conflitos</b>: Oriente Médio (questão israelo-palestina, desde a criação de Israel em 1948; guerra na Faixa de Gaza a partir de 2023), invasão da <b>Ucrânia pela Rússia</b> (2022), conflitos na África ligados a fronteiras artificiais do colonialismo, <b>terrorismo</b>, disputas por água e petróleo.</li><li><b>Refugiados</b>: milhões de pessoas deslocadas por guerras (Síria, Ucrânia, Afeganistão, Sudão).</li><li><b>ONU</b> e o Conselho de Segurança (EUA, Rússia, China, Reino Unido e França com poder de veto).</li></ul>`,
{pairs:[['Ordem bipolar','mundo dividido entre EUA e URSS durante a Guerra Fria'],['Ordem multipolar','mundo com vários centros de poder econômico e político'],['Conselho de Segurança da ONU','órgão com cinco membros permanentes com poder de veto'],['Países emergentes','economias em desenvolvimento com peso crescente, como Brasil, China e Índia'],['Refugiados','pessoas forçadas a deixar seu país por guerras ou perseguições'],['Fronteiras artificiais','limites traçados pelos colonizadores sem respeitar povos locais']],
 qs:[['Os membros permanentes do Conselho de Segurança da ONU são:','EUA, Rússia, China, Reino Unido e França',['EUA, Brasil, China, Japão e Alemanha','EUA, Índia, Rússia, Itália e França','Brasil, Rússia, Índia, China e África do Sul'],'Os vencedores da Segunda Guerra.'],['Muitos conflitos na África têm origem, em parte:','nas fronteiras traçadas pelos colonizadores sem respeitar povos locais',['na falta de recursos naturais','na ausência de religiões','no clima polar'],'Herança da partilha colonial (Conferência de Berlim).']]})
]});

/* ------------------------ UNIDADE 5 — AMBIENTE ------------------------ */
UNITS.push({id:'g5',title:'Ambiente e sustentabilidade',sub:'Problemas ambientais, conferências internacionais e recursos naturais',color:'#ff4b4b',dark:'#ea2b2b',skills:[
SKL('ambgeo','Problemas ambientais','🔥','Desmatamento, queimadas, aquecimento global, poluição, desertificação e perda de biodiversidade. Causas humanas: agropecuária extensiva, mineração, queima de combustíveis fósseis.',
`<ul><li><b>Desmatamento</b> na Amazônia e no Cerrado, ligado à pecuária extensiva, à soja, à extração de madeira e à grilagem.</li><li><b>Aquecimento global</b>: intensificação do efeito estufa por CO<sub>2</sub> (combustíveis fósseis, queimadas) e metano (pecuária, aterros). Consequências: eventos extremos, degelo, elevação do nível do mar.</li><li><b>Desertificação</b>: degradação de terras secas (partes do semiárido nordestino) por desmatamento e manejo inadequado.</li><li><b>Poluição</b> do ar, da água e do solo; lixões; microplásticos.</li><li><b>Assoreamento</b> dos rios pela retirada da mata ciliar.</li><li><b>Chuva ácida</b>, <b>ilhas de calor</b> e <b>inversão térmica</b> nas cidades.</li></ul>`,
{pairs:[['Desertificação','degradação de terras em áreas secas pela ação humana e pelo clima'],['Assoreamento','acúmulo de sedimentos no leito dos rios, agravado pela retirada da mata ciliar'],['Mata ciliar','vegetação às margens dos rios, que protege contra a erosão'],['Inversão térmica','camada de ar quente que impede a dispersão de poluentes'],['Aquecimento global','aumento da temperatura média do planeta pela intensificação do efeito estufa'],['Pecuária extensiva','criação de gado em grandes áreas, principal vetor de desmatamento na Amazônia']],
 qs:[['A retirada da mata ciliar provoca principalmente:','erosão das margens e assoreamento dos rios',['aumento da vazão limpa dos rios','resfriamento global','chuva ácida'],'Sem vegetação, o solo vai para o rio.'],['A principal causa do desmatamento na Amazônia brasileira é:','a expansão da pecuária e da agricultura',['a construção de cidades gigantes','a atividade vulcânica','o turismo'],'Abertura de pastagens e lavouras.']]}),
SKL('confer','Conferências e acordos ambientais','🤝','Estocolmo (1972), Rio-92 (Agenda 21), Protocolo de Kyoto (1997), Rio+20 (2012), Acordo de Paris (2015, limitar o aquecimento a bem menos de 2 °C) e COP30 em Belém (2025).',
`<ul><li><b>Conferência de Estocolmo</b> (1972): primeira grande conferência da ONU sobre meio ambiente.</li><li><b>Relatório Brundtland</b> (1987): definiu <b>desenvolvimento sustentável</b> — atender às necessidades do presente sem comprometer as gerações futuras.</li><li><b>Rio-92 (ECO-92)</b>: <b>Agenda 21</b>, convenções sobre clima e biodiversidade.</li><li><b>Protocolo de Kyoto</b> (1997): metas de redução de emissões para países desenvolvidos; mercado de <b>créditos de carbono</b>.</li><li><b>Rio+20</b> (2012).</li><li><b>Acordo de Paris</b> (2015): limitar o aquecimento a bem menos de 2 °C, buscando 1,5 °C, com metas nacionais (NDCs) para todos os países.</li><li><b>Agenda 2030</b>: 17 Objetivos de Desenvolvimento Sustentável (ODS).</li><li><b>COP30</b> (2025): conferência do clima realizada em <b>Belém</b>, na Amazônia.</li></ul>`,
{pairs:[['Conferência de Estocolmo','primeira grande conferência da ONU sobre meio ambiente (1972)'],['Rio-92','conferência que aprovou a Agenda 21'],['Protocolo de Kyoto','acordo de 1997 com metas de redução de emissões para países desenvolvidos'],['Acordo de Paris','acordo de 2015 para limitar o aquecimento global a bem menos de 2 °C'],['Desenvolvimento sustentável','atender às necessidades do presente sem comprometer as gerações futuras'],['Créditos de carbono','certificados negociáveis de redução de emissões'],['ODS','17 Objetivos de Desenvolvimento Sustentável da Agenda 2030']],
 order:[['Conferência de Estocolmo',1972],['Relatório Brundtland',1987],['Rio-92',1992],['Protocolo de Kyoto',1997],['Rio+20',2012],['Acordo de Paris',2015],['COP30 em Belém',2025]],
 qs:[['O conceito de desenvolvimento sustentável foi popularizado pelo:','Relatório Brundtland (Nosso Futuro Comum, 1987)',['Protocolo de Montreal','Tratado de Tordesilhas','Acordo de Paris'],'Definição clássica de 1987.']]}),
SKL('recursos','Recursos naturais e água','💧','Água doce é pequena parte da água do planeta e é mal distribuída. O Brasil tem grande reserva de água doce, mas concentrada na Amazônia, longe da maior parte da população.',
`<p>Cerca de <b>97,5%</b> da água do planeta é salgada; da água doce, a maior parte está em geleiras e aquíferos. O Brasil tem uma das maiores reservas de água doce do mundo, mas <b>mal distribuída</b>: a maior parte está na Amazônia, onde vive pouca gente.</p>
<p><b>Usos</b>: a <b>agricultura irrigada</b> é o maior consumidor de água no Brasil e no mundo, seguida pela indústria e pelo abastecimento urbano.</p>
<p><b>Crise hídrica</b>: seca, desmatamento, poluição, desperdício e má gestão. <b>Água virtual</b>: água gasta para produzir um bem (exportar soja ou carne é exportar água).</p>
<p><b>Recursos minerais</b> no Brasil: ferro (Carajás, PA, e Quadrilátero Ferrífero, MG), bauxita, nióbio (maior produtor mundial), ouro. Riscos: rompimento de barragens de rejeitos (Mariana, 2015; Brumadinho, 2019).</p>`,
{pairs:[['Água virtual','água usada na produção de um bem, como alimentos exportados'],['Agricultura irrigada','maior consumidora de água no Brasil e no mundo'],['Carajás','província mineral do Pará, rica em minério de ferro'],['Quadrilátero Ferrífero','região de Minas Gerais rica em ferro e ouro'],['Nióbio','metal do qual o Brasil é o maior produtor mundial'],['Barragem de rejeitos','estrutura que armazena resíduos da mineração, como as que romperam em Mariana e Brumadinho']],
 qs:[['Embora rico em água doce, o Brasil enfrenta crises hídricas porque:','a água é mal distribuída em relação à população e há poluição e desperdício',['não possui rios perenes','toda a água está no Nordeste','não chove no Sudeste'],'Abundância na Amazônia, escassez onde há mais demanda.'],['A atividade que mais consome água no Brasil é:','a agricultura irrigada',['o abastecimento doméstico','a indústria de software','o turismo'],'Irrigação lidera o consumo.']]})
]});

const GLOSS=autoGloss(UNITS,[
 {k:['escala','calcular escala'],n:'Escala',s:'escala',t:'Distância real = distância no mapa × denominador da escala. Na escala 1 : 100 000, 1 cm = 1 km. Para converter cm em km, divida por 100 000.'},
 {k:['fuso','fuso horario','fusos'],n:'Fusos horários',s:'fuso',t:'A Terra gira 15° por hora. Para leste as horas são adiantadas; para oeste, atrasadas. O Brasil tem 4 fusos (UTC −2 a −5).'},
 {k:['el nino'],n:'El Niño',s:'clima',t:'Aquecimento anormal das águas do Pacífico equatorial; no Brasil costuma trazer seca ao Norte/Nordeste e chuvas fortes ao Sul.'},
 {k:['mercosul'],n:'Mercosul',s:'global',t:'Bloco criado em 1991 (Tratado de Assunção) por Brasil, Argentina, Paraguai e Uruguai.'}]);
