const BRAND={app:'SaberLingo',chatPh:'ex.: o que faz a mitocôndria?',tutor:'Professora Rosalind',sym:'DNA',body:'#2bb673',dark:'#1f8f57',belly:'#dcf7e8',lsKey:'biolingo_v1',first:'vida',
 welcome:'Biologia do <b>Fundamental ao Ensino Médio</b>: célula, genética, evolução, seres vivos, corpo humano e ecologia — com cruzamentos genéticos e cálculos gerados sem parar.',
 range:'do Fundamental ao Ensino Médio (ENEM e vestibulares)',searchEx:'ex.: mitose',firstName:'Características dos seres vivos',
 chips:['O que faz a mitocôndria?','Mitose ou meiose?','Vacina e soro','1ª Lei de Mendel','Relações ecológicas','Biomas brasileiros'],
 askEx:'<i>"o que é osmose?"</i>, <i>"mitose"</i>, <i>"mutualismo"</i>',
 formulas:'cruzamentos (1ª Lei de Mendel), fotossíntese, respiração celular e pirâmides de energia'};
const UNITS=[];

/* ---------- geradores de Biologia ---------- */
const BASES='ATCG';
const COMP={A:'T',T:'A',C:'G',G:'C'},TRANS={A:'U',T:'A',C:'G',G:'C'};
const rseq=n=>[...Array(n)].map(()=>pick(BASES)).join('');
const FR={0:'0',1:'1/4',2:'1/2',3:'3/4',4:'1'};
const PCT={0:'0%',1:'25%',2:'50%',3:'75%',4:'100%'};
const TRAITS=[['ervilhas','a semente amarela (A)','a semente verde (a)'],['coelhos','a pelagem preta (A)','a pelagem branca (a)'],['humanos','a pigmentação normal (A)','o albinismo (a)'],['moscas-das-frutas','a asa longa (A)','a asa vestigial (a)'],['plantas de tomate','o caule roxo (A)','o caule verde (a)']];
function cross(p1,p2){ const off=[]; for(const a of p1) for(const b of p2) off.push([a,b].sort().join('')); return off; }
const GT={AA:'homozigoto dominante (AA)',Aa:'heterozigoto (Aa)',aa:'homozigoto recessivo (aa)'};
const bioGens={
 dna:lv=>{ let s; do{ s=rseq(lv>=3?9:6); }while(![...BASES].every(b=>s.includes(b))); const t=R(0,1);
   if(t===0){ const c=[...s].map(b=>COMP[b]).join(''); return MC(`Qual é a fita complementar do DNA <b>${s}</b>?`,c,[[...s].map(b=>TRANS[b]).join(''),s,[...c].reverse().join(''),[...s].map(b=>({A:'G',G:'A',T:'C',C:'T'})[b]).join('')],`No DNA, A pareia com T e C pareia com G: <b>${c}</b>.`,'Pareamento no DNA: A–T e C–G.'); }
   const r=[...s].map(b=>TRANS[b]).join(''); return MC(`Qual RNA mensageiro é transcrito a partir da fita molde de DNA <b>${s}</b>?`,r,[[...s].map(b=>COMP[b]).join(''),s.replace(/T/g,'U'),[...r].reverse().join('')],`Na transcrição, A → U, T → A, C → G, G → C: <b>${r}</b>. O RNA tem uracila (U) no lugar da timina.`,'No RNA não há timina: o A do DNA pareia com U.'); },
 codon:lv=>{ const k=R(4,lv>=3?120:30); return NUM(`Um RNA mensageiro tem <b>${3*k}</b> nucleotídeos codificantes (sem contar o códon de parada). Quantos aminoácidos terá a proteína?`,k,`Cada códon (trinca de bases) codifica 1 aminoácido: ${3*k} / 3 = <b>${k}</b>.`,'Cada aminoácido é codificado por 3 nucleotídeos (um códon).'); },
 mendel:lv=>{ const [org,dom,rec]=pick(TRAITS),g=['AA','Aa','aa']; let p1=pick(g),p2=pick(g); if(lv>=1&&Math.random()<.5){p1='Aa';p2=pick(['Aa','aa']);}
   const off=cross(p1,p2),t=R(0,2),n={AA:0,Aa:0,aa:0}; off.forEach(x=>n[x]++); const domN=n.AA+n.Aa;
   const ctx=`Em ${org}, ${dom} domina ${rec}. Cruzam-se indivíduos <b>${p1} × ${p2}</b>.`,tab=`Gametas: ${[...new Set(p1)].join(', ')} × ${[...new Set(p2)].join(', ')} → filhos: ${off.join(', ')}.`;
   if(t===0) return MC(`${ctx} Qual a probabilidade de um descendente ser <b>aa</b>?`,FR[n.aa],Object.values(FR).filter(x=>x!==FR[n.aa]),`${tab} aa aparece em ${n.aa} de 4: <b>${FR[n.aa]}</b>.`,'Monte o quadro de Punnett com os gametas de cada genitor.');
   if(t===1) return MC(`${ctx} Qual a porcentagem esperada de descendentes com o fenótipo <b>dominante</b>?`,PCT[domN],Object.values(PCT).filter(x=>x!==PCT[domN]),`${tab} Têm pelo menos um A: ${domN} de 4 = <b>${PCT[domN]}</b>.`,'Fenótipo dominante: AA ou Aa.');
   return MC(`${ctx} Qual a probabilidade de um descendente ser <b>heterozigoto (Aa)</b>?`,FR[n.Aa],Object.values(FR).filter(x=>x!==FR[n.Aa]),`${tab} Aa aparece em ${n.Aa} de 4: <b>${FR[n.Aa]}</b>.`,'Conte os Aa no quadro de Punnett.'); },
 sangue:lv=>{ const ok={O:['O'],A:['A','O'],B:['B','O'],AB:['AB','A','B','O']},all=['O','A','B','AB'];
   if(Math.random()<.6){ const r=pick(['O','A','B']),c=pick(ok[r]); return MC(`Considerando apenas o sistema ABO, uma pessoa do tipo <b>${r}</b> pode receber sangue de um doador do tipo:`,c,all.filter(x=>!ok[r].includes(x)),`Tipo ${r} pode receber de: <b>${ok[r].join(', ')}</b>. Não pode receber hemácias com aglutinogênio que ela não tem.`,'O receptor não pode receber aglutinogênio (A ou B) que não tenha.'); }
   const d=pick(['A','B','AB']),can=all.filter(r=>ok[r].includes(d)),no=all.filter(r=>!can.includes(r)); const c=pick(can);
   return MC(`Considerando apenas o sistema ABO, uma pessoa do tipo <b>${d}</b> pode doar sangue para alguém do tipo:`,c,no.concat(no.length<2?['nenhum tipo']:[]),`Tipo ${d} pode doar para: <b>${can.join(', ')}</b>.`,'O doador só pode dar para quem já tem o(s) mesmo(s) aglutinogênio(s).'); },
 piramide:lv=>{ const E=pick([10000,20000,50000,100000,5000]),k=R(2,4),v=E*0.1**(k-1),nm=['','produtores','consumidores primários','consumidores secundários','consumidores terciários'][k];
   return NUM(`Numa cadeia alimentar, os produtores fixam <b>${nf(E)} kcal</b>. Supondo que cada nível trófico aproveite cerca de 10% da energia do anterior, quanta energia chega aos <b>${nm}</b>?`,round(v,4),`A cada nível sobra ~10%: ${nf(E)} × 0,1<sup>${k-1}</sup> = <b>${nf(round(v,4))} kcal</b>.`,'Multiplique por 0,1 a cada passagem de nível trófico.',{unit:'kcal'}); }
};

/* ------------------------ UNIDADE 1 — CÉLULA ------------------------ */
UNITS.push({id:'b1',title:'A célula',sub:'Seres vivos, organelas, membrana, energia e divisão celular',color:'#2bb673',dark:'#1f8f57',skills:[
SKL('vida','Características dos seres vivos','🌱','Seres vivos têm células, metabolismo, reprodução, material genético, respondem a estímulos e evoluem. Vírus não têm células.',
`<p>Os seres vivos compartilham: <b>organização celular</b>, <b>metabolismo</b> (reações químicas para obter energia e matéria), <b>reprodução</b>, <b>material genético</b> (DNA), <b>resposta a estímulos</b>, <b>homeostase</b> (equilíbrio interno) e <b>evolução</b>.</p>
<p><b>Vírus</b> são acelulares e só se reproduzem dentro de células (parasitas intracelulares obrigatórios), por isso sua classificação como seres vivos é debatida.</p>
<h3>Níveis de organização</h3><p>átomo → molécula → organela → <b>célula</b> → tecido → órgão → sistema → organismo → população → comunidade → ecossistema → biosfera.</p>
<h3>Composição química</h3><p>Água (a substância mais abundante), sais minerais, <b>carboidratos</b> (energia: glicose, amido, glicogênio), <b>lipídios</b> (reserva, membranas), <b>proteínas</b> (estrutura, enzimas, anticorpos), <b>ácidos nucleicos</b> (DNA, RNA) e vitaminas.</p>`,
{pairs:[['Metabolismo','conjunto das reações químicas que ocorrem no organismo'],['Homeostase','manutenção do equilíbrio do meio interno'],['Vírus','ser acelular que só se reproduz dentro de células'],['Carboidratos','principal fonte de energia imediata, como glicose e amido'],['Proteínas','formam estruturas, enzimas e anticorpos'],['Lipídios','reserva de energia e componentes das membranas celulares'],['Glicogênio','carboidrato de reserva dos animais, armazenado no fígado e nos músculos'],['Amido','carboidrato de reserva das plantas']],
 qs:[['A sequência correta de níveis de organização é:','célula → tecido → órgão → sistema → organismo',['tecido → célula → órgão → organismo → sistema','órgão → tecido → célula → sistema → organismo','célula → órgão → tecido → organismo → sistema'],'Células formam tecidos, que formam órgãos, que formam sistemas.'],['A substância mais abundante nas células é:','a água',['a proteína','o DNA','a glicose'],'A água corresponde a cerca de 70% da massa celular.'],['Os vírus não são considerados por muitos cientistas como seres vivos plenos porque:','não têm células e só se reproduzem dentro de outras células',['não têm material genético','são maiores que as bactérias','fazem fotossíntese'],'São <b>acelulares</b> e parasitas intracelulares obrigatórios.']]}),
SKL('celula','Tipos de célula','🔬','Procariontes (bactérias) não têm núcleo organizado; eucariontes têm núcleo com carioteca. Célula vegetal tem parede de celulose, cloroplastos e vacúolo grande.',
`<ul><li><b>Procariontes</b>: sem núcleo organizado (DNA disperso no citoplasma, no nucleoide) e sem organelas membranosas; têm ribossomos. Ex.: <b>bactérias</b> e arqueas.</li><li><b>Eucariontes</b>: núcleo delimitado pela <b>carioteca</b> e organelas membranosas. Ex.: protozoários, fungos, plantas e animais.</li></ul>
<table><tr><th></th><th>Célula animal</th><th>Célula vegetal</th></tr><tr><td>Parede celular</td><td>não</td><td>sim (celulose)</td></tr><tr><td>Cloroplastos</td><td>não</td><td>sim</td></tr><tr><td>Vacúolo</td><td>pequenos</td><td>grande, central</td></tr><tr><td>Centríolos</td><td>sim</td><td>não (na maioria)</td></tr><tr><td>Reserva</td><td>glicogênio</td><td>amido</td></tr></table>`,
{qs:[['Uma célula sem carioteca e sem organelas membranosas é:','procarionte, como uma bactéria',['eucarionte animal','eucarionte vegetal','um fungo'],'Sem núcleo organizado: <b>procarionte</b>.'],['Qual estrutura existe na célula vegetal e NÃO na animal?','parede celular de celulose',['membrana plasmática','ribossomo','mitocôndria'],'Parede de <b>celulose</b> e cloroplastos são típicos das plantas.'],['Tanto células procariontes quanto eucariontes possuem:','ribossomos e membrana plasmática',['núcleo com carioteca','mitocôndrias','cloroplastos'],'Ribossomos, membrana, citoplasma e DNA estão em todas as células.'],['A parede celular dos fungos é formada principalmente por:','quitina',['celulose','peptidoglicano','amido'],'Fungos: parede de <b>quitina</b> (a mesma do exoesqueleto dos artrópodes).']],
 tf:[['Bactérias são seres eucariontes.',false,'Falso: são procariontes.'],['Células vegetais armazenam amido.',true,'Verdadeiro.'],['Mitocôndrias existem tanto em células animais quanto vegetais.',true,'Verdadeiro: as duas fazem respiração celular.']]}),
SKL('organelas','Organelas','⚙️','Mitocôndria: respiração celular; ribossomo: síntese de proteínas; cloroplasto: fotossíntese; lisossomo: digestão; complexo golgiense: empacota e secreta.',
`<ul><li><b>Membrana plasmática</b>: controla a entrada e saída de substâncias (permeabilidade seletiva).</li><li><b>Núcleo</b>: guarda o DNA e coordena a célula.</li><li><b>Ribossomos</b>: síntese de <b>proteínas</b>.</li><li><b>Retículo endoplasmático rugoso</b> (com ribossomos): produz e transporta proteínas. <b>Liso</b>: produz lipídios e desintoxica (muito desenvolvido no fígado).</li><li><b>Complexo golgiense</b>: modifica, empacota e <b>secreta</b> substâncias; forma o acrossomo do espermatozoide e os lisossomos.</li><li><b>Lisossomos</b>: <b>digestão intracelular</b> (enzimas digestivas).</li><li><b>Mitocôndrias</b>: <b>respiração celular</b>, produção de ATP; têm DNA próprio (herança materna).</li><li><b>Cloroplastos</b>: <b>fotossíntese</b> (clorofila); também têm DNA próprio.</li><li><b>Peroxissomos</b>: degradam peróxido de hidrogênio (H<sub>2</sub>O<sub>2</sub>).</li><li><b>Centríolos</b>: formam cílios, flagelos e participam da divisão celular.</li><li><b>Vacúolo</b>: armazenamento e equilíbrio de água (grande na célula vegetal).</li></ul>`,
{pairs:[['Mitocôndria','respiração celular e produção de ATP'],['Ribossomo','síntese de proteínas'],['Cloroplasto','fotossíntese'],['Lisossomo','digestão intracelular'],['Complexo golgiense','modificação, empacotamento e secreção de substâncias'],['Retículo endoplasmático liso','síntese de lipídios e desintoxicação'],['Retículo endoplasmático rugoso','síntese e transporte de proteínas'],['Peroxissomo','decomposição do peróxido de hidrogênio'],['Centríolo','formação de cílios e flagelos'],['Núcleo','armazenamento do DNA e controle das atividades celulares'],['Membrana plasmática','controle seletivo da entrada e saída de substâncias']],tq:t=>`Qual é a função do(a) <b>${t}</b>?`,dq:d=>`Qual organela é responsável por: <b>${d}</b>?`,
 qs:[['Células musculares, que gastam muita energia, têm grande quantidade de:','mitocôndrias',['lisossomos','cloroplastos','vacúolos'],'Mais energia → mais respiração celular → mais <b>mitocôndrias</b>.'],['Células do pâncreas que secretam enzimas têm muito desenvolvidos:','o retículo rugoso e o complexo golgiense',['os cloroplastos','os centríolos','os peroxissomos'],'Produção (RER) e secreção (Golgi) de proteínas.'],['As células do fígado, que desintoxicam o organismo de álcool e medicamentos, têm muito desenvolvido o:','retículo endoplasmático liso',['cloroplasto','centríolo','vacúolo de suco celular'],'O <b>REL</b> participa da desintoxicação.']]}),
SKL('membrana','Membrana e transporte','🚪','Difusão e osmose são passivas (sem gasto de energia); transporte ativo gasta ATP. Na osmose, a água vai do meio menos concentrado (hipotônico) para o mais concentrado (hipertônico).',
`<p>A membrana plasmática é formada por uma <b>bicamada de fosfolipídios</b> com proteínas (modelo do <b>mosaico fluido</b>).</p>
<h3>Transporte passivo (sem gasto de energia)</h3><ul><li><b>Difusão simples</b>: soluto vai do meio mais concentrado para o menos concentrado (O<sub>2</sub>, CO<sub>2</sub>).</li><li><b>Difusão facilitada</b>: com ajuda de proteínas (glicose).</li><li><b>Osmose</b>: passagem de <b>água</b> do meio <b>hipotônico</b> (menos concentrado) para o <b>hipertônico</b> (mais concentrado).</li></ul>
<h3>Transporte ativo</h3><p>Contra o gradiente, com gasto de <b>ATP</b> — ex.: <b>bomba de sódio e potássio</b>.</p>
<h3>Transporte em massa</h3><p><b>Endocitose</b>: fagocitose (partículas sólidas) e pinocitose (líquidos). <b>Exocitose</b>: eliminação de substâncias.</p>
<div class="ex">Hemácia em água pura (hipotônica) incha e pode estourar; em solução muito salgada (hipertônica) murcha. Por isso o soro fisiológico é isotônico (0,9% de NaCl).</div>`,
{pairs:[['Difusão simples','passagem de soluto do meio mais concentrado para o menos concentrado, sem gasto de energia'],['Osmose','passagem de água através da membrana, do meio hipotônico para o hipertônico'],['Transporte ativo','transporte contra o gradiente de concentração, com gasto de ATP'],['Fagocitose','englobamento de partículas sólidas pela célula'],['Pinocitose','englobamento de gotículas de líquido pela célula'],['Exocitose','eliminação de substâncias para fora da célula'],['Bomba de sódio e potássio','transporte ativo que mantém mais Na⁺ fora e mais K⁺ dentro da célula']],
 qs:[['Uma hemácia colocada em água destilada:','absorve água por osmose e pode se romper',['perde água e murcha','não sofre alteração','faz fotossíntese'],'A água é hipotônica: entra na hemácia.'],['Salgar a carne conserva o alimento porque:','os microrganismos perdem água por osmose',['o sal mata o oxigênio','o sal aumenta a temperatura','o sal é um antibiótico natural'],'O meio fica hipertônico e as células dos micróbios desidratam.'],['A bomba de sódio e potássio é um exemplo de:','transporte ativo',['difusão simples','osmose','difusão facilitada'],'Gasta ATP para mover íons contra o gradiente.'],['O soro fisiológico (0,9% de NaCl) não danifica as hemácias porque é:','isotônico em relação a elas',['hipotônico','hipertônico','ácido'],'Mesma concentração: não há fluxo resultante de água.']]}),
SKL('energia','Fotossíntese, respiração e fermentação','☀️','Fotossíntese: 6 CO₂ + 6 H₂O + luz → C₆H₁₂O₆ + 6 O₂. Respiração celular é o processo inverso e libera energia (ATP).',
`<ul><li><b>Fotossíntese</b> (cloroplastos): <b>6 CO<sub>2</sub> + 6 H<sub>2</sub>O → C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + 6 O<sub>2</sub></b>, com luz e clorofila. O O<sub>2</sub> liberado vem da <b>água</b> (fotólise). Fase clara (tilacoides: produz ATP e NADPH, libera O<sub>2</sub>) e fase escura/química (estroma: ciclo de Calvin, fixa CO<sub>2</sub>).</li><li><b>Respiração celular aeróbia</b> (citoplasma + mitocôndria): <b>C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + 6 O<sub>2</sub> → 6 CO<sub>2</sub> + 6 H<sub>2</sub>O + energia</b> (cerca de 30 a 38 ATP). Etapas: glicólise, ciclo de Krebs e cadeia respiratória.</li><li><b>Fermentação</b> (sem O<sub>2</sub>, no citoplasma, só 2 ATP): <b>alcoólica</b> (leveduras: etanol + CO<sub>2</sub> — pão, cerveja) e <b>lática</b> (bactérias do iogurte e músculos em esforço intenso: ácido lático).</li></ul>`,
{qs:[['O oxigênio liberado na fotossíntese vem:','da quebra da água (fotólise)',['do gás carbônico','da glicose','do solo'],'Experimentos com isótopos mostraram que o O<sub>2</sub> vem da <b>água</b>.'],['A massa do pão cresce porque as leveduras fazem:','fermentação alcoólica, liberando CO<sub>2</sub>',['fotossíntese','fermentação lática','respiração com liberação de O<sub>2</sub>'],'O CO<sub>2</sub> forma as bolhas; o etanol evapora no forno.'],['A dor muscular após exercício intenso já foi associada ao acúmulo de ácido lático, produzido pela:','fermentação lática',['fotossíntese','fermentação alcoólica','digestão'],'Com pouco O<sub>2</sub>, a célula muscular faz <b>fermentação lática</b>.'],['Qual processo produz mais ATP por molécula de glicose?','respiração aeróbia',['fermentação alcoólica','fermentação lática','glicólise isolada'],'Aeróbia: cerca de 30–38 ATP; fermentação: 2 ATP.'],['Os reagentes da fotossíntese são:','gás carbônico e água',['glicose e oxigênio','oxigênio e água','glicose e gás carbônico'],'6 CO<sub>2</sub> + 6 H<sub>2</sub>O → glicose + 6 O<sub>2</sub>.'],['O ciclo de Krebs ocorre:','na matriz mitocondrial',['no cloroplasto','no núcleo','no ribossomo'],'É uma etapa da respiração aeróbia, dentro da <b>mitocôndria</b>.']]}),
SKL('divisao','Mitose e meiose','➗','Mitose: 1 célula → 2 células idênticas (crescimento, regeneração). Meiose: 1 célula → 4 células com metade dos cromossomos (gametas), com variabilidade.',
`<h3>Mitose</h3><p>Uma célula origina <b>duas</b> células-filhas <b>geneticamente idênticas</b>, com o mesmo número de cromossomos (2n → 2n). Serve para crescimento, regeneração e reprodução assexuada.</p><ul><li><b>Prófase</b>: cromossomos se condensam e a carioteca se desfaz.</li><li><b>Metáfase</b>: cromossomos alinhados na placa equatorial (melhor fase para contá-los).</li><li><b>Anáfase</b>: cromátides-irmãs separam-se para os polos.</li><li><b>Telófase</b>: núcleos se reorganizam; depois, citocinese.</li></ul>
<h3>Meiose</h3><p>Uma célula 2n origina <b>quatro</b> células <b>n</b> (haploides), diferentes entre si. Ocorre na formação dos <b>gametas</b> (animais) e esporos (plantas). O <b>crossing-over</b> (permutação), na prófase I, e a segregação independente geram <b>variabilidade genética</b>.</p>
<div class="ex">Humanos: células do corpo com 46 cromossomos (2n); gametas com 23 (n).</div>`,
{pairs:[['Prófase','fase em que os cromossomos se condensam e a carioteca se desfaz'],['Metáfase','fase em que os cromossomos se alinham na placa equatorial'],['Anáfase','fase em que as cromátides-irmãs migram para polos opostos'],['Telófase','fase em que os núcleos se reorganizam'],['Crossing-over','troca de trechos entre cromossomos homólogos, na prófase I da meiose'],['Citocinese','divisão do citoplasma ao final da divisão celular']],
 qs:[['A mitose produz:','2 células idênticas à célula-mãe',['4 células haploides diferentes','2 células com metade dos cromossomos','4 células idênticas'],'Mitose: 2n → 2 células 2n idênticas.'],['A meiose produz:','4 células haploides geneticamente diferentes',['2 células idênticas','4 células diploides idênticas','1 célula maior'],'Meiose: 2n → 4 células n.'],['Um espermatozoide humano tem quantos cromossomos?','23',['46','92','12'],'Gameta é haploide: <b>23</b>.'],['O crossing-over é importante porque:','aumenta a variabilidade genética',['garante células idênticas','reduz a variabilidade','duplica o DNA'],'Recombina genes entre cromossomos homólogos.'],['A cicatrização de um corte na pele ocorre por:','mitose',['meiose','fecundação','crossing-over'],'Reposição de células idênticas: <b>mitose</b>.']]})
]});

/* ------------------------ UNIDADE 2 — GENÉTICA ------------------------ */
UNITS.push({id:'b2',title:'Genética',sub:'DNA, síntese de proteínas, Mendel, grupos sanguíneos, herança ligada ao sexo e biotecnologia',color:'#1cb0f6',dark:'#1899d6',skills:[
SKL('dnarna','DNA, RNA e síntese de proteínas','🧬','DNA: A–T e C–G, dupla-hélice, desoxirribose. RNA: uracila no lugar da timina, fita simples, ribose. Transcrição: DNA → RNA; tradução: RNA → proteína.',
`<ul><li><b>DNA</b>: dupla-hélice (Watson e Crick, 1953), açúcar <b>desoxirribose</b>, bases A, T, C, G com pareamento <b>A–T</b> e <b>C–G</b>. Replicação <b>semiconservativa</b>.</li><li><b>RNA</b>: fita simples, açúcar <b>ribose</b>, bases A, <b>U (uracila)</b>, C, G.</li></ul>
<h3>Da informação à proteína</h3><ol><li><b>Transcrição</b> (núcleo): o DNA serve de molde para o RNA mensageiro (A → U, T → A, C → G, G → C).</li><li><b>Tradução</b> (ribossomos): cada <b>códon</b> (trinca de bases do RNAm) é lido e o RNA transportador traz o aminoácido correspondente.</li></ol>
<p>O código genético é <b>degenerado</b> (vários códons para o mesmo aminoácido) e quase <b>universal</b>. Códon de início: AUG; há três códons de parada.</p>
<p><b>Mutação</b>: alteração no DNA — pode ser neutra, prejudicial ou vantajosa; é a fonte primária de variabilidade.</p>`,
{gens:[bioGens.dna,bioGens.dna,bioGens.codon],pairs:[['Transcrição','produção de RNA a partir do DNA, no núcleo'],['Tradução','produção de proteína a partir do RNA mensageiro, nos ribossomos'],['Códon','trinca de bases do RNA mensageiro que codifica um aminoácido'],['Replicação','duplicação do DNA antes da divisão celular'],['Uracila','base nitrogenada exclusiva do RNA'],['Timina','base nitrogenada exclusiva do DNA'],['Mutação','alteração na sequência do DNA']]}),
SKL('mendel','1ª Lei de Mendel','🫛','Cada característica é determinada por um par de fatores (alelos) que se separam na formação dos gametas. Aa × Aa → 1 AA : 2 Aa : 1 aa (3 dominantes : 1 recessivo).',
`<p>Gregor <b>Mendel</b> cruzou ervilhas e propôs a <b>1ª Lei (segregação dos fatores)</b>: cada característica é determinada por um par de alelos que se separam na formação dos gametas; cada gameta leva só um.</p>
<ul><li><b>Genótipo</b>: constituição genética (AA, Aa, aa). <b>Fenótipo</b>: característica observável (genótipo + ambiente).</li><li><b>Homozigoto</b>: alelos iguais (AA ou aa). <b>Heterozigoto</b>: diferentes (Aa).</li><li><b>Dominante</b>: se manifesta em dose simples (A). <b>Recessivo</b>: só se manifesta em dose dupla (aa).</li></ul>
<div class="ex">Aa × Aa → quadro de Punnett: AA, Aa, Aa, aa → genótipos 1 : 2 : 1; fenótipos 3 dominantes : 1 recessivo.</div>
<p><b>Cruzamento-teste</b>: cruzar com o homozigoto recessivo (aa) para descobrir se um indivíduo dominante é AA ou Aa.</p>`,
{gens:[bioGens.mendel,bioGens.mendel,bioGens.mendel],pairs:[['Genótipo','constituição genética do indivíduo, como AA, Aa ou aa'],['Fenótipo','característica observável, resultado do genótipo e do ambiente'],['Homozigoto','indivíduo com dois alelos iguais para um gene'],['Heterozigoto','indivíduo com dois alelos diferentes para um gene'],['Alelo recessivo','só se manifesta em dose dupla'],['Cruzamento-teste','cruzamento com o homozigoto recessivo para descobrir o genótipo de um dominante']]}),
SKL('sangue','Grupos sanguíneos','🩸','Tipo O: doador universal (hemácias sem aglutinogênio); tipo AB: receptor universal. Fator Rh: Rh⁻ não deve receber sangue Rh⁺.',
`<p>O sistema <b>ABO</b> é um caso de <b>alelos múltiplos</b> (I<sup>A</sup>, I<sup>B</sup> e i), com <b>codominância</b> entre I<sup>A</sup> e I<sup>B</sup>.</p>
<table><tr><th>Tipo</th><th>Genótipos</th><th>Aglutinogênio (hemácia)</th><th>Aglutinina (plasma)</th></tr><tr><td>A</td><td>I<sup>A</sup>I<sup>A</sup>, I<sup>A</sup>i</td><td>A</td><td>anti-B</td></tr><tr><td>B</td><td>I<sup>B</sup>I<sup>B</sup>, I<sup>B</sup>i</td><td>B</td><td>anti-A</td></tr><tr><td>AB</td><td>I<sup>A</sup>I<sup>B</sup></td><td>A e B</td><td>nenhuma</td></tr><tr><td>O</td><td>ii</td><td>nenhum</td><td>anti-A e anti-B</td></tr></table>
<p><b>O</b> é doador universal e <b>AB</b> é receptor universal (no sistema ABO). <b>Fator Rh</b>: Rh<sup>−</sup> produz anti-Rh se receber sangue Rh<sup>+</sup>. A <b>eritroblastose fetal</b> ocorre quando mãe Rh<sup>−</sup> já sensibilizada gera filho Rh<sup>+</sup>.</p>`,
{gens:[bioGens.sangue,bioGens.sangue],qs:[['Uma pessoa do tipo O tem no plasma:','aglutininas anti-A e anti-B',['nenhuma aglutinina','só anti-A','aglutinogênios A e B'],'Tipo O: sem aglutinogênios, com anti-A e anti-B.'],['Um casal I<sup>A</sup>i × I<sup>B</sup>i pode ter filhos dos tipos:','A, B, AB e O',['apenas A e B','apenas AB','apenas O'],'Gametas I<sup>A</sup>, i × I<sup>B</sup>, i → I<sup>A</sup>I<sup>B</sup>, I<sup>A</sup>i, I<sup>B</sup>i, ii.'],['A eritroblastose fetal pode ocorrer quando:','a mãe é Rh⁻ sensibilizada e o filho é Rh⁺',['a mãe é Rh⁺ e o filho Rh⁻','os dois são Rh⁻','os dois são do tipo O'],'Anticorpos anti-Rh da mãe atacam as hemácias do feto Rh⁺.'],['A relação entre os alelos I<sup>A</sup> e I<sup>B</sup> é de:','codominância',['dominância completa de I<sup>A</sup>','recessividade','epistasia'],'No tipo AB os dois se expressam: <b>codominância</b>.']]}),
SKL('sexo','Herança ligada ao sexo','🚻','Daltonismo e hemofilia são recessivos ligados ao X: afetam mais homens (XʸY precisa de um só alelo).',
`<p>Na espécie humana, mulheres são <b>XX</b> e homens <b>XY</b>. O pai transmite o X às filhas e o Y aos filhos; a mãe transmite um X a todos.</p>
<p>Na <b>herança recessiva ligada ao X</b> (daltonismo, hemofilia, distrofia de Duchenne):</p><ul><li>Homem X<sup>d</sup>Y é afetado (tem só um X).</li><li>Mulher só é afetada se for X<sup>d</sup>X<sup>d</sup>; X<sup>D</sup>X<sup>d</sup> é <b>portadora</b>.</li><li>Por isso essas doenças são <b>mais comuns em homens</b>.</li></ul>
<div class="ex">Mãe portadora (X<sup>D</sup>X<sup>d</sup>) × pai normal (X<sup>D</sup>Y): metade dos filhos homens será daltônica; nenhuma filha será daltônica (metade será portadora).</div>
<p><b>Herança restrita ao Y</b> (holândrica): passa só de pai para filho.</p>`,
{qs:[['Por que o daltonismo é mais comum em homens?','porque o gene é recessivo e está no cromossomo X, e os homens têm só um X',['porque está no cromossomo Y','porque é dominante','porque as mulheres não têm cromossomo X'],'Basta um alelo recessivo no único X do homem.'],['Mãe portadora de hemofilia e pai normal. A probabilidade de um filho HOMEM ser hemofílico é:','1/2',['0','1/4','1'],'O filho recebe um dos X da mãe: X<sup>H</sup> ou X<sup>h</sup> → 1/2.'],['Um pai daltônico transmite o alelo do daltonismo:','a todas as filhas',['a todos os filhos homens','a metade dos filhos','a ninguém'],'O pai dá seu X a todas as filhas (e o Y aos filhos).'],['Uma característica que passa só de pai para filho homem, em todas as gerações, é de herança:','restrita ao Y (holândrica)',['recessiva ligada ao X','autossômica recessiva','mitocondrial'],'Genes do cromossomo Y.'],['O DNA mitocondrial é herdado:','apenas da mãe',['apenas do pai','dos dois igualmente','só pelos filhos homens'],'As mitocôndrias do zigoto vêm do óvulo.']]}),
SKL('biotec','Biotecnologia','🧫','Transgênico recebe gene de outra espécie; clone é geneticamente idêntico; PCR multiplica DNA; terapia gênica corrige genes defeituosos.',
`<ul><li><b>DNA recombinante / transgênicos</b>: organismos que recebem genes de outra espécie (bactéria produzindo insulina humana; milho Bt resistente a insetos).</li><li><b>Clonagem</b>: produção de indivíduos geneticamente idênticos (ovelha Dolly, 1996, por transferência nuclear).</li><li><b>PCR</b>: técnica que multiplica trechos de DNA (testes de covid-19, perícias).</li><li><b>Teste de DNA (impressão digital genética)</b>: compara fragmentos de DNA — paternidade e criminalística.</li><li><b>Terapia gênica</b>: introduz genes normais para tratar doenças genéticas.</li><li><b>CRISPR-Cas9</b>: "tesoura" molecular que edita o DNA em pontos específicos.</li><li><b>Células-tronco</b>: células indiferenciadas capazes de originar diferentes tipos celulares.</li></ul>`,
{pairs:[['Organismo transgênico','organismo que recebeu gene de outra espécie'],['Clonagem','produção de indivíduos geneticamente idênticos'],['PCR','técnica que multiplica trechos de DNA em laboratório'],['Terapia gênica','introdução de genes normais para tratar doenças genéticas'],['CRISPR-Cas9','ferramenta que edita o DNA em pontos específicos'],['Células-tronco','células indiferenciadas capazes de originar vários tipos de células'],['Enzima de restrição','corta o DNA em sequências específicas'],['Plasmídeo','pequeno DNA circular de bactérias, usado como vetor de genes']],
 qs:[['Bactérias que produzem insulina humana são exemplo de:','organismos transgênicos (DNA recombinante)',['clonagem reprodutiva','mutação espontânea','seleção natural'],'Receberam o gene humano da insulina.'],['Para comparar o DNA de um suspeito com vestígios de uma cena de crime, usa-se:','a impressão digital genética (teste de DNA)',['a clonagem','a terapia gênica','o cruzamento-teste'],'Compara padrões de fragmentos de DNA.'],['A ovelha Dolly (1996) foi o primeiro mamífero clonado a partir de:','uma célula adulta, por transferência nuclear',['um óvulo fecundado','uma bactéria','um vírus'],'O núcleo de uma célula da glândula mamária foi colocado num óvulo sem núcleo.']]})
]});

/* ------------------------ UNIDADE 3 — EVOLUÇÃO E DIVERSIDADE ------------------------ */
UNITS.push({id:'b3',title:'Evolução e diversidade',sub:'Teorias evolutivas, evidências, classificação, vírus, bactérias, protozoários e fungos',color:'#ff9600',dark:'#e07b00',skills:[
SKL('evolucao','Teorias da evolução','🦒','Lamarck: uso e desuso + herança de caracteres adquiridos (rejeitada). Darwin: seleção natural. Neodarwinismo: seleção natural + mutação + recombinação.',
`<ul><li><b>Lamarck</b>: <b>lei do uso e desuso</b> (órgãos usados se desenvolvem) e <b>herança dos caracteres adquiridos</b> — a segunda foi refutada.</li><li><b>Darwin</b> (<i>A Origem das Espécies</i>, 1859) e Wallace: <b>seleção natural</b> — há variação entre os indivíduos; os mais adaptados ao ambiente sobrevivem e deixam mais descendentes.</li><li><b>Neodarwinismo (teoria sintética)</b>: seleção natural + <b>mutação</b> e <b>recombinação gênica</b> como fontes de variabilidade.</li></ul>
<div class="ex">Girafas: para Lamarck, esticaram o pescoço e passaram isso aos filhos; para Darwin, as de pescoço mais longo já existiam, alcançavam mais alimento e deixavam mais descendentes.</div>
<h3>Evidências</h3><p><b>Fósseis</b>; <b>órgãos homólogos</b> (mesma origem, funções diferentes: braço humano e asa do morcego); <b>órgãos análogos</b> (mesma função, origens diferentes: asa de inseto e de ave); <b>órgãos vestigiais</b> (apêndice); semelhanças embrionárias e moleculares (DNA).</p>
<p><b>Especiação</b>: formação de novas espécies, geralmente após <b>isolamento geográfico</b> seguido de isolamento reprodutivo.</p>`,
{pairs:[['Lamarck','propôs a lei do uso e desuso e a herança dos caracteres adquiridos'],['Darwin','propôs a seleção natural em A Origem das Espécies (1859)'],['Neodarwinismo','une seleção natural, mutação e recombinação gênica'],['Órgãos homólogos','mesma origem embrionária, podendo ter funções diferentes'],['Órgãos análogos','mesma função, mas origens diferentes'],['Órgãos vestigiais','órgãos reduzidos e sem função evidente, como o apêndice'],['Especiação','formação de novas espécies, muitas vezes após isolamento geográfico']],
 qs:[['Bactérias resistentes a antibióticos aumentam quando o remédio é usado de forma errada porque:','o antibiótico seleciona as bactérias que já eram resistentes',['o antibiótico cria mutações de resistência de propósito','as bactérias "aprendem" a resistir e passam isso adiante','o antibiótico fortalece todas as bactérias'],'É <b>seleção natural</b>: as resistentes sobrevivem e se multiplicam.'],['A asa do morcego e o braço humano são órgãos:','homólogos',['análogos','vestigiais','idênticos'],'Mesma origem embrionária, funções diferentes.'],['A asa de uma borboleta e a asa de uma ave são órgãos:','análogos',['homólogos','vestigiais','rudimentares'],'Mesma função (voo), origens diferentes.'],['A ideia refutada pela genética de que "características adquiridas em vida são herdadas" é de:','Lamarck',['Darwin','Mendel','Wallace'],'Herança dos caracteres adquiridos: <b>Lamarck</b>.']]}),
SKL('classif','Classificação dos seres vivos','🗃️','Nomenclatura binomial (Lineu): gênero com maiúscula + espécie com minúscula, em itálico (Homo sapiens). Cinco reinos: Monera, Protista, Fungi, Plantae e Animalia.',
`<p><b>Lineu</b> criou a <b>nomenclatura binomial</b>: <i>Gênero espécie</i>, em latim, em itálico, gênero com inicial maiúscula (<i>Homo sapiens</i>, <i>Canis familiaris</i>).</p>
<p>Categorias: <b>reino → filo → classe → ordem → família → gênero → espécie</b>. Espécie: indivíduos que se cruzam e geram descendentes férteis.</p>
<table><tr><th>Reino</th><th>Características</th></tr><tr><td>Monera</td><td>procariontes (bactérias, cianobactérias)</td></tr><tr><td>Protista</td><td>eucariontes simples (protozoários e algas)</td></tr><tr><td>Fungi</td><td>eucariontes heterótrofos por absorção, parede de quitina (cogumelos, bolores, leveduras)</td></tr><tr><td>Plantae</td><td>eucariontes pluricelulares autótrofos (clorofila, parede de celulose)</td></tr><tr><td>Animalia</td><td>eucariontes pluricelulares heterótrofos por ingestão</td></tr></table>
<p>Hoje também se usam os três <b>domínios</b>: Bacteria, Archaea e Eukarya. A <b>cladística</b> agrupa os seres por ancestralidade comum.</p>`,
{pairs:[['Monera','reino dos procariontes, como bactérias e cianobactérias'],['Protista','reino dos protozoários e algas'],['Fungi','reino dos cogumelos, bolores e leveduras'],['Plantae','reino dos eucariontes pluricelulares autótrofos'],['Animalia','reino dos eucariontes pluricelulares heterótrofos por ingestão']],tq:t=>`O reino <b>${t}</b> reúne:`,dq:d=>`Qual reino corresponde a: <b>${d}</b>?`,
 qs:[['Qual é a forma correta de escrever o nome científico do ser humano?','<i>Homo sapiens</i>',['<i>Homo Sapiens</i>','<i>homo sapiens</i>','HOMO SAPIENS'],'Gênero com maiúscula, espécie com minúscula, em itálico.'],['A ordem correta das categorias, da mais ampla para a mais restrita, é:','reino, filo, classe, ordem, família, gênero, espécie',['espécie, gênero, família, ordem, classe, filo, reino','reino, classe, filo, família, ordem, gênero, espécie','filo, reino, classe, ordem, gênero, família, espécie'],'Reino → filo → classe → ordem → família → gênero → espécie.'],['O cavalo e o jumento geram a mula, que é estéril. Isso mostra que cavalo e jumento:','são de espécies diferentes',['são da mesma espécie','são do mesmo gênero e da mesma espécie','não têm parentesco'],'Espécie: cruzam e geram descendentes <b>férteis</b>.']]}),
SKL('micro','Vírus e bactérias','🦠','Vírus: acelulares, parasitas intracelulares obrigatórios, tratados com antivirais e prevenidos com vacinas. Bactérias: procariontes, combatidas com antibióticos.',
`<p><b>Vírus</b>: sem células, formados por material genético (DNA ou RNA) e cápsula de proteína. Só se reproduzem dentro de células. Antibióticos <b>não</b> funcionam contra vírus. Doenças: gripe, covid-19, dengue, zika, febre amarela, sarampo, AIDS (HIV), raiva, catapora.</p>
<p><b>Bactérias</b>: procariontes, com parede celular e, às vezes, plasmídeos. Muitas são benéficas (decomposição, fixação de nitrogênio, produção de iogurte, microbiota intestinal). Doenças: tuberculose, cólera, tétano, leptospirose, sífilis, hanseníase, meningite bacteriana. Tratamento: <b>antibióticos</b>.</p>`,
{pairs:[['Dengue','virose transmitida pelo mosquito Aedes aegypti'],['Tuberculose','doença bacteriana que afeta principalmente os pulmões'],['Cólera','doença bacteriana transmitida por água e alimentos contaminados'],['Tétano','doença bacteriana associada a ferimentos com objetos contaminados'],['Leptospirose','doença bacteriana transmitida pela urina de ratos'],['AIDS','síndrome causada pelo vírus HIV, que ataca células de defesa'],['Febre amarela','virose transmitida por mosquitos, prevenida por vacina'],['Sarampo','virose muito contagiosa, prevenida por vacina'],['Sífilis','infecção sexualmente transmissível causada por bactéria']],tq:t=>`Sobre a <b>${t}</b>, é correto afirmar que é:`,dq:d=>`Qual doença é <b>${d}</b>?`,
 qs:[['Por que antibióticos não curam a gripe?','porque a gripe é causada por vírus, e antibióticos agem sobre bactérias',['porque a gripe é causada por fungos','porque o vírus da gripe é uma bactéria resistente','porque antibióticos só funcionam em crianças'],'Antibióticos atuam em estruturas das <b>bactérias</b>.'],['Bactérias do gênero <i>Rhizobium</i>, nas raízes de leguminosas, são importantes porque:','fixam o nitrogênio do ar',['produzem oxigênio','causam doenças nas plantas','decompõem o solo'],'Fixação biológica do nitrogênio.'],['O principal meio de prevenir o sarampo e a febre amarela é:','a vacinação',['o uso de antibióticos','ferver a água','tomar antifúngicos'],'Ambas são viroses prevenidas por <b>vacina</b>.']]}),
SKL('protofungo','Protozoários, fungos e parasitoses','🐛','Malária: protozoário (Plasmodium), mosquito Anopheles. Doença de Chagas: Trypanosoma cruzi, barbeiro. Esquistossomose: verme Schistosoma, caramujo, penetra pela pele.',
`<p><b>Protozoários</b>: eucariontes unicelulares heterótrofos. Doenças: <b>malária</b> (<i>Plasmodium</i>, mosquito <i>Anopheles</i>), <b>doença de Chagas</b> (<i>Trypanosoma cruzi</i>, inseto barbeiro), <b>leishmaniose</b> (<i>Leishmania</i>, mosquito-palha), <b>amebíase</b> e <b>giardíase</b> (água e alimentos contaminados), toxoplasmose.</p>
<p><b>Fungos</b>: heterótrofos por absorção, parede de quitina; decompositores. Úteis: leveduras (pão, cerveja), <i>Penicillium</i> (penicilina), cogumelos comestíveis. Doenças: micoses, candidíase. Os <b>liquens</b> são associações de fungo + alga.</p>
<p><b>Vermes (helmintos)</b>: <b>esquistossomose</b> (<i>Schistosoma mansoni</i>; caramujo hospedeiro intermediário; larva penetra pela pele em água contaminada), <b>ascaridíase</b> (lombriga; ingestão de ovos), <b>teníase</b> (carne de porco ou boi mal cozida), <b>ancilostomose</b> (amarelão; larva penetra pela pele, andar descalço).</p>
<p>Prevenção geral: <b>saneamento básico</b>, água tratada, higiene dos alimentos, controle de vetores.</p>`,
{pairs:[['Malária','causada pelo protozoário Plasmodium e transmitida pelo mosquito Anopheles'],['Doença de Chagas','causada pelo Trypanosoma cruzi e transmitida pelo inseto barbeiro'],['Esquistossomose','verme que tem caramujo como hospedeiro intermediário e penetra pela pele'],['Ascaridíase','verminose da lombriga, adquirida pela ingestão de ovos'],['Teníase','verminose adquirida ao comer carne de porco ou boi mal cozida'],['Amarelão (ancilostomose)','verminose cuja larva penetra pela pele, comum em quem anda descalço'],['Leishmaniose','protozoose transmitida pelo mosquito-palha'],['Micose','infecção de pele causada por fungos']],tq:t=>`Sobre a <b>${t}</b>, é correto dizer que é:`,dq:d=>`Qual doença é <b>${d}</b>?`,
 qs:[['A penicilina, primeiro antibiótico, foi obtida a partir de:','um fungo (Penicillium)',['uma bactéria','um vírus','um protozoário'],'Alexander Fleming, 1928: fungo <i>Penicillium</i>.'],['Qual medida previne ao mesmo tempo esquistossomose, cólera e amebíase?','saneamento básico',['uso de repelente','vacina contra gripe','antibiótico preventivo'],'Todas ligadas a água e esgoto.'],['O líquen é uma associação entre:','fungo e alga (ou cianobactéria)',['bactéria e vírus','planta e animal','dois protozoários'],'Mutualismo fungo + alga.']]})
]});

/* ------------------------ UNIDADE 4 — PLANTAS E ANIMAIS ------------------------ */
UNITS.push({id:'b4',title:'Plantas e animais',sub:'Grupos de plantas, fisiologia vegetal, invertebrados e vertebrados',color:'#ce82ff',dark:'#a568cc',skills:[
SKL('plantas','Grupos de plantas','🌿','Briófitas (musgos): sem vasos. Pteridófitas (samambaias): vasos, sem sementes. Gimnospermas (pinheiros): sementes sem fruto. Angiospermas: flores e frutos.',
`<table><tr><th>Grupo</th><th>Exemplo</th><th>Novidade evolutiva</th></tr><tr><td>Briófitas</td><td>musgos</td><td>avasculares, pequenas, dependem da água para a fecundação; gametófito dominante</td></tr><tr><td>Pteridófitas</td><td>samambaias, avencas</td><td><b>vasos condutores</b> (xilema e floema); sem sementes; esporófito dominante</td></tr><tr><td>Gimnospermas</td><td>pinheiros, araucária</td><td><b>sementes</b> (nuas, sem fruto) e grão de pólen</td></tr><tr><td>Angiospermas</td><td>ipê, feijão, milho, mangueira</td><td><b>flores e frutos</b>; maior grupo atual</td></tr></table>
<p>Angiospermas: <b>monocotiledôneas</b> (milho, arroz, cana; folhas com nervuras paralelas, raiz fasciculada) e <b>eudicotiledôneas</b> (feijão, ipê; nervuras reticuladas, raiz pivotante).</p>`,
{pairs:[['Briófitas','plantas sem vasos condutores, como os musgos'],['Pteridófitas','plantas com vasos, mas sem sementes, como as samambaias'],['Gimnospermas','plantas com sementes nuas, sem frutos, como os pinheiros'],['Angiospermas','plantas com flores e frutos'],['Monocotiledôneas','angiospermas com folhas de nervuras paralelas, como o milho'],['Eudicotiledôneas','angiospermas com folhas de nervuras reticuladas, como o feijão']],
 qs:[['O pinhão da araucária é uma semente de:','gimnosperma',['angiosperma','briófita','pteridófita'],'Semente sem fruto: <b>gimnosperma</b>.'],['O primeiro grupo de plantas a apresentar vasos condutores foi o das:','pteridófitas',['briófitas','gimnospermas','algas'],'Samambaias têm xilema e floema.'],['O fruto é uma estrutura exclusiva das:','angiospermas',['gimnospermas','pteridófitas','briófitas'],'Flor + fruto: <b>angiospermas</b>.'],['Musgos são pequenos principalmente porque:','não têm vasos condutores',['não fazem fotossíntese','vivem só no mar','não têm células'],'Sem vasos, a água se distribui célula a célula.']]}),
SKL('fisiovegetal','Fisiologia vegetal','🍃','Xilema: seiva bruta (água e sais) da raiz às folhas. Floema: seiva elaborada (açúcares) das folhas ao resto da planta. Etileno amadurece frutos; auxina faz o caule crescer em direção à luz.',
`<ul><li><b>Xilema</b> (lenho): conduz <b>seiva bruta</b> (água e sais minerais) da raiz às folhas, puxada pela transpiração.</li><li><b>Floema</b> (líber): conduz <b>seiva elaborada</b> (açúcares da fotossíntese) para toda a planta. Tirar um anel da casca (anel de Malpighi) interrompe o floema e a raiz morre.</li><li><b>Estômatos</b>: poros nas folhas que regulam trocas gasosas e a transpiração.</li></ul>
<h3>Hormônios vegetais</h3><ul><li><b>Auxina</b>: crescimento, fototropismo, dominância apical.</li><li><b>Giberelina</b>: alongamento do caule, germinação, frutos sem sementes.</li><li><b>Citocinina</b>: divisão celular, retarda o envelhecimento.</li><li><b>Etileno</b> (gás): amadurecimento dos frutos, queda das folhas.</li><li><b>Ácido abscísico</b>: dormência e fechamento dos estômatos na seca.</li></ul>`,
{pairs:[['Xilema','conduz a seiva bruta, com água e sais minerais'],['Floema','conduz a seiva elaborada, com açúcares'],['Estômato','poro da folha que regula trocas gasosas e transpiração'],['Auxina','hormônio do crescimento e do fototropismo'],['Etileno','hormônio gasoso que acelera o amadurecimento dos frutos'],['Giberelina','hormônio que alonga o caule e estimula a germinação'],['Ácido abscísico','hormônio que induz dormência e fecha os estômatos'],['Citocinina','hormônio que estimula a divisão celular e retarda o envelhecimento']],
 qs:[['Embrulhar bananas em jornal acelera o amadurecimento porque concentra o:','etileno',['auxina','giberelina','oxigênio'],'O gás <b>etileno</b> fica retido e acelera o processo.'],['A planta que cresce inclinada em direção à janela mostra:','fototropismo positivo, regulado pela auxina',['geotropismo negativo','tigmotropismo','fotossíntese reversa'],'Crescimento em direção à luz.'],['Retirar um anel completo da casca do tronco mata a planta porque interrompe:','o floema, que leva açúcar às raízes',['o xilema, que leva água às folhas','os estômatos','a fotossíntese nas folhas'],'Anel de Malpighi: as raízes ficam sem seiva elaborada.']]}),
SKL('invert','Invertebrados','🐙','Artrópodes são o maior filo (insetos, aracnídeos, crustáceos): exoesqueleto de quitina e patas articuladas.',
`<table><tr><th>Filo</th><th>Exemplos</th><th>Características</th></tr><tr><td>Poríferos</td><td>esponjas</td><td>sem tecidos verdadeiros, corpo com poros</td></tr><tr><td>Cnidários</td><td>águas-vivas, corais</td><td>cnidócitos (células urticantes)</td></tr><tr><td>Platelmintos</td><td>planária, tênia, esquistossomo</td><td>corpo achatado</td></tr><tr><td>Nematelmintos</td><td>lombriga, ancilóstomo</td><td>corpo cilíndrico, tubo digestório completo</td></tr><tr><td>Anelídeos</td><td>minhoca, sanguessuga</td><td>corpo segmentado em anéis</td></tr><tr><td>Moluscos</td><td>caracol, polvo, lula, ostra</td><td>corpo mole, muitos com concha</td></tr><tr><td>Artrópodes</td><td>insetos, aranhas, caranguejos</td><td>exoesqueleto de quitina, patas articuladas (maior filo)</td></tr><tr><td>Equinodermos</td><td>estrela-do-mar, ouriço</td><td>exclusivamente marinhos, sistema ambulacrário</td></tr></table>
<p>Insetos: 3 pares de patas e corpo em cabeça, tórax e abdome. Aracnídeos: 4 pares de patas, sem antenas.</p>`,
{pairs:[['Poríferos','esponjas, animais sem tecidos verdadeiros'],['Cnidários','águas-vivas e corais, com células urticantes'],['Platelmintos','vermes de corpo achatado, como a tênia'],['Nematelmintos','vermes de corpo cilíndrico, como a lombriga'],['Anelídeos','animais de corpo segmentado em anéis, como a minhoca'],['Moluscos','animais de corpo mole, como polvo e caracol'],['Artrópodes','animais com exoesqueleto de quitina e patas articuladas'],['Equinodermos','animais exclusivamente marinhos, como a estrela-do-mar']],
 qs:[['Uma aranha tem quantos pares de patas?','4',['3','5','2'],'Aracnídeos: <b>4 pares</b>; insetos: 3 pares.'],['A queimadura causada por água-viva se deve aos:','cnidócitos',['coanócitos','espinhos de quitina','estômatos'],'Células urticantes dos cnidários.'],['A minhoca é importante para a agricultura porque:','cava galerias que arejam o solo e produz húmus',['poliniza flores','fixa nitrogênio do ar','faz fotossíntese'],'Anelídeo que melhora a estrutura do solo.']]}),
SKL('vert','Vertebrados','🐟','Peixes (brânquias), anfíbios (metamorfose, pele úmida), répteis (ovo com casca, escamas), aves (penas, endotérmicas) e mamíferos (pelos, glândulas mamárias).',
`<ul><li><b>Peixes</b>: respiram por brânquias; ectotérmicos; cartilaginosos (tubarão) ou ósseos.</li><li><b>Anfíbios</b> (sapos, rãs, salamandras): <b>metamorfose</b> (girino com brânquias → adulto com pulmões), pele fina e úmida (respiração cutânea); dependem da água para reproduzir.</li><li><b>Répteis</b> (cobras, lagartos, tartarugas, jacarés): pele com escamas de queratina e <b>ovo com casca</b> (amniótico) — conquista definitiva do ambiente terrestre; ectotérmicos.</li><li><b>Aves</b>: <b>penas</b>, bico sem dentes, ossos pneumáticos, sacos aéreos, <b>endotérmicas</b>.</li><li><b>Mamíferos</b>: <b>pelos</b> e <b>glândulas mamárias</b>, diafragma, endotérmicos; a maioria é placentária (monotremados, como o ornitorrinco, põem ovos).</li></ul>
<p><b>Ectotérmicos</b> dependem do ambiente para regular a temperatura; <b>endotérmicos</b> a mantêm constante (aves e mamíferos).</p>`,
{pairs:[['Peixes','vertebrados que respiram por brânquias'],['Anfíbios','vertebrados com metamorfose e pele úmida, como os sapos'],['Répteis','vertebrados com escamas e ovo com casca, como as cobras'],['Aves','vertebrados com penas e ossos pneumáticos'],['Mamíferos','vertebrados com pelos e glândulas mamárias'],['Endotérmicos','animais que mantêm a temperatura do corpo constante'],['Ornitorrinco','mamífero monotremado que põe ovos']],
 qs:[['O girino respira por brânquias e o sapo adulto, por pulmões e pela pele. Essa transformação é a:','metamorfose',['muda','regeneração','hibernação'],'Anfíbios passam por <b>metamorfose</b>.'],['A estrutura que permitiu aos répteis a reprodução longe da água foi:','o ovo com casca (amniótico)',['as brânquias','a pele úmida','a metamorfose'],'O ovo amniótico protege o embrião do ressecamento.'],['A baleia é um:','mamífero',['peixe','réptil','anfíbio'],'Tem glândulas mamárias e respira por pulmões.'],['São endotérmicos:','aves e mamíferos',['peixes e anfíbios','répteis e peixes','anfíbios e répteis'],'Mantêm a temperatura corporal constante.']]})
]});

/* ------------------------ UNIDADE 5 — CORPO HUMANO ------------------------ */
UNITS.push({id:'b5',title:'Corpo humano',sub:'Digestão, respiração, circulação, excreção, hormônios, sistema nervoso e imunidade',color:'#ff4b4b',dark:'#ea2b2b',skills:[
SKL('digest','Sistema digestório','🍎','Boca (amilase salivar: amido), estômago (pepsina: proteínas), intestino delgado (suco pancreático, bile e absorção), intestino grosso (absorve água).',
`<ol><li><b>Boca</b>: mastigação e <b>amilase salivar</b> (ptialina), que inicia a digestão do <b>amido</b>.</li><li><b>Esôfago</b>: movimentos peristálticos.</li><li><b>Estômago</b>: suco gástrico com HCl (pH ácido) e <b>pepsina</b>, que digere <b>proteínas</b>.</li><li><b>Intestino delgado</b>: recebe o <b>suco pancreático</b> (amilase, lipase, tripsina) e a <b>bile</b> (produzida no fígado e guardada na vesícula biliar), que <b>emulsifica gorduras</b> — a bile não é enzima. As <b>vilosidades</b> absorvem os nutrientes.</li><li><b>Intestino grosso</b>: absorção de <b>água</b> e formação das fezes; abriga a microbiota.</li></ol>`,
{pairs:[['Amilase salivar','enzima da boca que inicia a digestão do amido'],['Pepsina','enzima do estômago que digere proteínas'],['Bile','substância produzida pelo fígado que emulsifica as gorduras'],['Lipase pancreática','enzima que digere lipídios no intestino delgado'],['Vilosidades intestinais','dobras que aumentam a área de absorção no intestino delgado'],['Intestino grosso','absorve água e forma as fezes'],['Vesícula biliar','órgão que armazena a bile']],
 qs:[['A digestão do amido começa:','na boca',['no estômago','no intestino grosso','no fígado'],'Amilase salivar (ptialina).'],['A bile atua na digestão:','emulsificando gorduras, sem ser uma enzima',['digerindo proteínas','digerindo amido','absorvendo água'],'Quebra a gordura em gotículas, facilitando a ação da lipase.'],['A maior parte da absorção dos nutrientes ocorre:','no intestino delgado',['no estômago','no esôfago','na boca'],'Graças às vilosidades.'],['A pessoa que retirou a vesícula biliar deve evitar:','alimentos muito gordurosos',['alimentos ricos em fibras','água','frutas'],'A bile deixa de ser armazenada e liberada em grande quantidade.']]}),
SKL('circula','Respiração e circulação','❤️','Hemácias transportam O₂ (hemoglobina); leucócitos defendem; plaquetas coagulam. Artérias saem do coração; veias chegam ao coração.',
`<h3>Respiração</h3><p>Ar: fossas nasais → faringe → laringe → traqueia → brônquios → bronquíolos → <b>alvéolos</b>, onde ocorre a <b>hematose</b> (troca de O<sub>2</sub> e CO<sub>2</sub>). O <b>diafragma</b> contrai na inspiração.</p>
<h3>Sangue</h3><ul><li><b>Hemácias</b>: transportam O<sub>2</sub> pela <b>hemoglobina</b> (que tem ferro).</li><li><b>Leucócitos</b>: defesa (fagocitose e anticorpos).</li><li><b>Plaquetas</b>: coagulação.</li><li><b>Plasma</b>: parte líquida.</li></ul>
<h3>Circulação</h3><p>Coração com <b>4 cavidades</b> (2 átrios e 2 ventrículos). <b>Artérias</b> levam sangue <b>do</b> coração; <b>veias</b> trazem sangue <b>ao</b> coração. <b>Pequena circulação</b>: coração → pulmões → coração (a artéria pulmonar leva sangue pobre em O<sub>2</sub>). <b>Grande circulação</b>: coração → corpo → coração (a aorta leva sangue rico em O<sub>2</sub>).</p>`,
{pairs:[['Hemácias','células que transportam oxigênio por meio da hemoglobina'],['Leucócitos','células de defesa do organismo'],['Plaquetas','fragmentos celulares que atuam na coagulação'],['Alvéolos pulmonares','local da troca de gases entre o ar e o sangue'],['Artéria','vaso que leva o sangue do coração para o corpo ou pulmões'],['Veia','vaso que traz o sangue de volta ao coração'],['Aorta','maior artéria, leva sangue rico em oxigênio para o corpo'],['Diafragma','músculo que se contrai na inspiração']],
 qs:[['A anemia ferropriva está ligada à falta de ferro, necessário para formar a:','hemoglobina das hemácias',['insulina','bile','queratina'],'Sem ferro, cai a produção de hemoglobina e o transporte de O<sub>2</sub>.'],['A artéria pulmonar transporta sangue:','pobre em oxigênio, do coração aos pulmões',['rico em oxigênio, dos pulmões ao coração','rico em oxigênio, para o corpo','pobre em oxigênio, do corpo ao coração'],'Exceção clássica: artéria com sangue venoso.'],['A hematose ocorre:','nos alvéolos pulmonares',['na traqueia','no coração','no estômago'],'Troca de gases entre o ar e o sangue.'],['O coração humano tem:','2 átrios e 2 ventrículos',['1 átrio e 1 ventrículo','2 átrios e 1 ventrículo','3 átrios e 1 ventrículo'],'Quatro cavidades, sem mistura de sangue.']]}),
SKL('hormonio','Excreção e hormônios','🧪','Rins filtram o sangue e formam a urina (néfrons). Insulina baixa a glicemia; glucagon aumenta; adrenalina prepara para "luta ou fuga"; ADH faz os rins reabsorverem água.',
`<p><b>Rins</b>: os <b>néfrons</b> filtram o sangue, eliminando ureia e excesso de sais e água na urina. O <b>ADH</b> (hormônio antidiurético) aumenta a reabsorção de água — o álcool inibe o ADH e aumenta a urina.</p>
<h3>Glândulas e hormônios</h3><table><tr><th>Glândula</th><th>Hormônio</th><th>Função</th></tr><tr><td>Pâncreas</td><td>insulina / glucagon</td><td>diminui / aumenta a glicose no sangue</td></tr><tr><td>Suprarrenais</td><td>adrenalina</td><td>"luta ou fuga": acelera coração e respiração</td></tr><tr><td>Tireoide</td><td>tiroxina (T4) e T3</td><td>regulam o metabolismo (precisam de iodo)</td></tr><tr><td>Hipófise</td><td>GH, ADH, ocitocina, FSH, LH, prolactina</td><td>crescimento, água, parto e amamentação, reprodução</td></tr><tr><td>Ovários</td><td>estrogênio e progesterona</td><td>caracteres femininos, ciclo menstrual, gravidez</td></tr><tr><td>Testículos</td><td>testosterona</td><td>caracteres masculinos</td></tr></table>
<p><b>Diabetes tipo 1</b>: o pâncreas não produz insulina. <b>Tipo 2</b>: resistência à insulina (ligado a sedentarismo e obesidade).</p>`,
{pairs:[['Insulina','hormônio do pâncreas que diminui a glicose no sangue'],['Glucagon','hormônio do pâncreas que aumenta a glicose no sangue'],['Adrenalina','hormônio das suprarrenais que prepara o corpo para situações de perigo'],['Tiroxina','hormônio da tireoide que regula o metabolismo'],['ADH','hormônio antidiurético, que aumenta a reabsorção de água nos rins'],['Ocitocina','hormônio que provoca contrações do útero no parto e a saída do leite'],['Testosterona','hormônio masculino produzido nos testículos'],['Progesterona','hormônio que mantém a gravidez'],['Néfron','unidade dos rins que filtra o sangue e forma a urina']],tq:t=>`Qual é a função do(a) <b>${t}</b>?`,dq:d=>`Qual é o <b>${d}</b>?`,
 qs:[['A adição de iodo ao sal de cozinha previne problemas na:','tireoide',['hipófise','pâncreas','suprarrenal'],'O iodo é necessário para produzir os hormônios da tireoide (evita o bócio).'],['Beber álcool aumenta a produção de urina porque o álcool:','inibe o ADH',['estimula a insulina','aumenta o glucagon','bloqueia a adrenalina'],'Menos ADH → menos reabsorção de água.'],['No diabetes tipo 1, o problema é:','a falta de produção de insulina pelo pâncreas',['o excesso de insulina','a falta de glucagon','a falta de adrenalina'],'Células do pâncreas não produzem insulina.']]}),
SKL('imune','Sistema imunológico e vacinas','💉','Vacina: imunidade ativa (o corpo produz anticorpos e memória), preventiva. Soro: anticorpos prontos, imunidade passiva e imediata (picada de cobra).',
`<p><b>Antígeno</b>: substância estranha que desencadeia resposta imune. <b>Anticorpos</b>: proteínas produzidas pelos linfócitos B que neutralizam antígenos específicos.</p>
<table><tr><th></th><th>Vacina</th><th>Soro</th></tr><tr><td>Contém</td><td>antígenos (patógeno morto, atenuado ou partes dele; ou RNAm)</td><td>anticorpos prontos</td></tr><tr><td>Imunidade</td><td><b>ativa</b> (o corpo produz)</td><td><b>passiva</b> (recebe pronta)</td></tr><tr><td>Uso</td><td><b>prevenção</b>, gera memória</td><td><b>tratamento</b> imediato (picada de cobra, tétano)</td></tr><tr><td>Duração</td><td>longa</td><td>curta</td></tr></table>
<p>O leite materno passa anticorpos ao bebê (imunidade <b>passiva natural</b>). Ter a doença gera imunidade <b>ativa natural</b>. O HIV destrói linfócitos T auxiliares (CD4).</p>`,
{pairs:[['Vacina','contém antígenos e induz imunidade ativa e duradoura'],['Soro','contém anticorpos prontos e dá imunidade passiva imediata'],['Anticorpo','proteína de defesa que reconhece um antígeno específico'],['Antígeno','substância estranha que provoca resposta imunológica'],['Leite materno','transmite anticorpos ao bebê (imunidade passiva natural)'],['Memória imunológica','capacidade de responder mais rápido a um antígeno já conhecido']],
 qs:[['Após uma picada de cobra, o tratamento indicado é:','soro antiofídico, que tem anticorpos prontos',['vacina, para o corpo produzir anticorpos','antibiótico','vitamina C'],'É preciso ação imediata: <b>soro</b>.'],['A vacina protege por longo tempo porque:','estimula a produção de anticorpos e células de memória',['contém anticorpos prontos','mata todos os vírus do ambiente','é um antibiótico'],'Imunidade ativa com memória.'],['A proteção do bebê pelo leite materno é um exemplo de imunidade:','passiva natural',['ativa artificial','ativa natural','passiva artificial'],'Recebe anticorpos prontos da mãe.']]}),
SKL('nervoso','Sistema nervoso e sentidos','🧠','O neurônio conduz impulsos: dendritos → corpo celular → axônio. Sistema nervoso central: encéfalo e medula; periférico: nervos e gânglios. Ato reflexo passa pela medula.',
`<p><b>Neurônio</b>: dendritos (recebem), corpo celular e <b>axônio</b> (conduz o impulso), com bainha de mielina que acelera a condução. A comunicação entre neurônios ocorre nas <b>sinapses</b>, por <b>neurotransmissores</b> (dopamina, serotonina, acetilcolina).</p>
<ul><li><b>Sistema nervoso central</b>: <b>encéfalo</b> (cérebro — pensamento, memória, movimentos voluntários; cerebelo — equilíbrio e coordenação; tronco encefálico/bulbo — respiração e batimentos) e <b>medula espinal</b>.</li><li><b>Sistema nervoso periférico</b>: nervos e gânglios. Autônomo: <b>simpático</b> (luta ou fuga) e <b>parassimpático</b> (repouso).</li></ul>
<p><b>Ato reflexo</b>: resposta rápida e involuntária coordenada pela <b>medula</b> (tirar a mão do fogo, reflexo patelar).</p>
<p>Olho: a <b>retina</b> tem cones (cores) e bastonetes (pouca luz); a íris regula a pupila. Miopia: imagem antes da retina (lente divergente).</p>`,
{pairs:[['Axônio','prolongamento do neurônio que conduz o impulso nervoso'],['Sinapse','região de comunicação entre neurônios por neurotransmissores'],['Cerebelo','coordena o equilíbrio e os movimentos'],['Bulbo','controla respiração e batimentos cardíacos'],['Medula espinal','conduz impulsos e coordena atos reflexos'],['Bainha de mielina','envoltório que acelera a condução do impulso'],['Retina','camada do olho com células sensíveis à luz (cones e bastonetes)']],
 qs:[['Tirar a mão rapidamente de uma panela quente é um ato reflexo coordenado:','pela medula espinal',['pelo cérebro, de forma voluntária','pelo cerebelo','pelo coração'],'Arco reflexo passa pela <b>medula</b>.'],['Uma lesão no cerebelo afeta principalmente:','o equilíbrio e a coordenação motora',['a visão','a digestão','a produção de insulina'],'O cerebelo coordena os movimentos.'],['O sistema nervoso simpático, em situação de perigo:','acelera batimentos e respiração',['diminui os batimentos','estimula a digestão','causa sono'],'Reação de "luta ou fuga".']]})
]});

/* ------------------------ UNIDADE 6 — ECOLOGIA ------------------------ */
UNITS.push({id:'b6',title:'Ecologia e ambiente',sub:'Cadeias alimentares, relações ecológicas, ciclos, biomas e problemas ambientais',color:'#2b70c9',dark:'#1f569e',skills:[
SKL('cadeia','Cadeias e pirâmides alimentares','🍃','Produtores → consumidores primários → secundários → terciários; decompositores reciclam a matéria. A energia diminui a cada nível (~10% passa adiante).',
`<p><b>Produtores</b> (autótrofos, fazem fotossíntese) → <b>consumidores primários</b> (herbívoros) → <b>secundários</b> → <b>terciários</b>. <b>Decompositores</b> (bactérias e fungos) devolvem os nutrientes ao ambiente.</p>
<p>A <b>energia</b> flui em um só sentido e <b>diminui</b> a cada nível trófico (cerca de 10% passa adiante; o resto é gasto na respiração e perdido como calor). A <b>matéria</b> circula (ciclos).</p>
<p><b>Teia alimentar</b>: várias cadeias interligadas. <b>Pirâmides</b> de energia (sempre com base larga), de biomassa e de números.</p>
<p><b>Bioacumulação (magnificação trófica)</b>: substâncias não degradáveis (mercúrio, DDT) se acumulam e ficam mais concentradas nos níveis tróficos mais altos.</p>`,
{gens:[bioGens.piramide,bioGens.piramide],pairs:[['Produtores','seres autótrofos que produzem matéria orgânica pela fotossíntese'],['Consumidores primários','herbívoros, que se alimentam dos produtores'],['Decompositores','bactérias e fungos que devolvem nutrientes ao ambiente'],['Teia alimentar','conjunto de cadeias alimentares interligadas'],['Bioacumulação','aumento da concentração de poluentes ao longo da cadeia alimentar'],['Pirâmide de energia','nunca é invertida, pois a energia diminui a cada nível']],
 qs:[['Na cadeia capim → gafanhoto → sapo → cobra, o sapo é:','consumidor secundário',['produtor','consumidor primário','decompositor'],'Come o herbívoro (gafanhoto): 2º nível de consumidor.'],['Um poluente como o mercúrio fica mais concentrado:','nos predadores do topo da cadeia',['nos produtores','nos decompositores','igualmente em todos'],'Magnificação trófica.'],['A energia numa cadeia alimentar:','flui em um só sentido e diminui a cada nível',['circula e se recicla sem perdas','aumenta nos níveis superiores','é produzida pelos decompositores'],'Parte é perdida como calor em cada nível.']]}),
SKL('relacoes','Relações ecológicas','🤝','Mutualismo: ambos ganham (obrigatório); comensalismo: um ganha, o outro não perde; parasitismo: um ganha, o outro perde; predatismo: um mata o outro para se alimentar.',
`<h3>Harmônicas</h3><ul><li><b>Mutualismo</b>: ambos ganham e dependem um do outro (liquens; cupim e protozoários que digerem celulose).</li><li><b>Protocooperação</b>: ambos ganham, mas podem viver separados (anu e boi; paguro e anêmona).</li><li><b>Comensalismo</b>: um aproveita restos de alimento do outro sem prejudicá-lo (rêmora e tubarão).</li><li><b>Inquilinismo</b>: um usa o outro como abrigo ou suporte (bromélias e orquídeas sobre árvores).</li><li><b>Sociedade</b> (abelhas, formigas) e <b>colônia</b> (corais, caravelas) são intraespecíficas.</li></ul>
<h3>Desarmônicas</h3><ul><li><b>Parasitismo</b>: um vive às custas do outro (piolho, tênia).</li><li><b>Predatismo</b>: um mata o outro para se alimentar (onça e capivara).</li><li><b>Competição</b>: disputa por recursos (inter ou intraespecífica).</li><li><b>Amensalismo (antibiose)</b>: um libera substância que inibe o outro (fungo <i>Penicillium</i> e bactérias; maré vermelha).</li><li><b>Canibalismo</b>: predação dentro da mesma espécie.</li></ul>`,
{pairs:[['Líquen (fungo + alga)','mutualismo'],['Rêmora e tubarão','comensalismo'],['Bromélia sobre uma árvore','inquilinismo'],['Piolho e ser humano','parasitismo'],['Onça e capivara','predatismo'],['Anu e boi','protocooperação'],['Colmeia de abelhas','sociedade'],['Recife de corais','colônia'],['Penicillium e bactérias','amensalismo'],['Leões disputando uma presa com hienas','competição interespecífica']],tq:t=>`Qual relação ecológica existe em <b>${t}</b>?`,dq:d=>`Qual é um exemplo de <b>${d}</b>?`,noTF:true,
 tf:[['No comensalismo, as duas espécies são prejudicadas.',false,'Falso: uma se beneficia e a outra não é afetada.'],['O mutualismo é uma relação harmônica.',true,'Verdadeiro.'],['Sociedade e colônia são relações entre indivíduos da mesma espécie.',true,'Verdadeiro: são intraespecíficas.']]}),
SKL('ciclos','Ciclos biogeoquímicos','🔄','Carbono: fotossíntese retira CO₂; respiração, decomposição e queimadas devolvem. Nitrogênio: bactérias fixam o N₂ do ar (Rhizobium), nitrificam e desnitrificam.',
`<ul><li><b>Água</b>: evaporação, transpiração das plantas (evapotranspiração), condensação, precipitação e infiltração.</li><li><b>Carbono</b>: a <b>fotossíntese</b> retira CO<sub>2</sub> do ar; a <b>respiração</b>, a <b>decomposição</b> e a <b>queima de combustíveis e florestas</b> devolvem. O excesso de CO<sub>2</sub> intensifica o efeito estufa.</li><li><b>Nitrogênio</b>: o N<sub>2</sub> do ar não é usado diretamente pela maioria dos seres. <b>Fixação</b> por bactérias (<i>Rhizobium</i> em nódulos de leguminosas) e por raios; <b>amonificação</b> pelos decompositores; <b>nitrificação</b> (amônia → nitrito → nitrato); <b>desnitrificação</b> (devolve N<sub>2</sub> ao ar).</li><li><b>Oxigênio</b>: ligado à fotossíntese e à respiração.</li></ul>
<div class="ex">Rotação de culturas com feijão ou soja (leguminosas) enriquece o solo com nitrogênio.</div>`,
{pairs:[['Fixação do nitrogênio','transformação do N₂ do ar em compostos que as plantas absorvem'],['Nitrificação','transformação da amônia em nitrito e depois em nitrato'],['Desnitrificação','devolução do nitrogênio à atmosfera na forma de N₂'],['Evapotranspiração','perda de água para a atmosfera pela evaporação e pela transpiração das plantas'],['Fotossíntese (no ciclo do carbono)','retira CO₂ da atmosfera'],['Queima de combustíveis fósseis','devolve à atmosfera carbono que estava estocado há milhões de anos']],
 qs:[['Plantar leguminosas (feijão, soja) enriquece o solo porque:','bactérias em suas raízes fixam o nitrogênio do ar',['elas produzem nitrato pela fotossíntese','absorvem todo o carbono do solo','impedem a erosão por completo'],'<i>Rhizobium</i> nos nódulos das raízes.'],['O desmatamento seguido de queimada contribui para o efeito estufa porque:','libera CO₂ e reduz a absorção de CO₂ pela fotossíntese',['aumenta a fotossíntese','libera oxigênio','fixa nitrogênio'],'Duplo efeito no ciclo do carbono.']]}),
SKL('biomas','Biomas brasileiros','🗺️','Amazônia (maior biodiversidade), Cerrado (troncos tortos, "berço das águas"), Caatinga (semiárido, exclusivo do Brasil), Mata Atlântica (mais devastado), Pantanal (maior planície alagável) e Pampa (campos do Sul).',
`<ul><li><b>Amazônia</b>: maior floresta tropical do mundo, altíssima biodiversidade, clima quente e úmido; solo relativamente pobre (nutrientes na matéria orgânica).</li><li><b>Cerrado</b>: "savana brasileira"; árvores de troncos retorcidos e casca grossa, raízes profundas; estação seca marcada; nascentes de grandes bacias ("berço das águas"). Muito ameaçado pela agropecuária.</li><li><b>Caatinga</b>: único bioma <b>exclusivamente brasileiro</b>; clima semiárido; plantas <b>xerófitas</b> (cactos, espinhos, folhas que caem na seca).</li><li><b>Mata Atlântica</b>: floresta tropical da costa; o bioma <b>mais devastado</b> (restam cerca de 12% da área original); alta biodiversidade e endemismo.</li><li><b>Pantanal</b>: maior <b>planície alagável</b> do mundo; cheias e secas periódicas; grande concentração de fauna.</li><li><b>Pampa</b> (campos sulinos): vegetação rasteira de gramíneas, no Rio Grande do Sul.</li></ul>`,
{pairs:[['Amazônia','maior floresta tropical do mundo, com altíssima biodiversidade'],['Cerrado','savana brasileira de troncos retorcidos, conhecida como "berço das águas"'],['Caatinga','bioma semiárido exclusivamente brasileiro, com plantas adaptadas à seca'],['Mata Atlântica','floresta costeira, o bioma mais devastado do país'],['Pantanal','maior planície alagável do mundo'],['Pampa','campos de gramíneas do Rio Grande do Sul']],tq:t=>`Qual característica descreve o bioma <b>${t}</b>?`,dq:d=>`Qual bioma é a <b>${d}</b>?`,
 qs:[['Plantas com espinhos no lugar de folhas e caules que armazenam água são típicas da:','Caatinga',['Amazônia','Mata Atlântica','Pampa'],'Adaptações ao clima semiárido (xerofitismo).'],['O bioma brasileiro que mais perdeu sua cobertura original é a:','Mata Atlântica',['Amazônia','Pantanal','Caatinga'],'Restam cerca de 12%, pela ocupação histórica do litoral.'],['As árvores do Cerrado têm raízes muito profundas para:','alcançar a água do lençol freático na seca',['fixar nitrogênio','fazer fotossíntese no escuro','evitar o frio'],'Adaptação à estação seca.']]}),
SKL('ambiente','Problemas ambientais','🌍','Efeito estufa (CO₂, metano) → aquecimento global; CFCs destroem a camada de ozônio; esgoto e fertilizantes causam eutrofização; óxidos de S e N causam chuva ácida.',
`<ul><li><b>Efeito estufa</b>: fenômeno natural que mantém a Terra aquecida; o excesso de CO<sub>2</sub>, metano (CH<sub>4</sub>) e óxido nitroso causa o <b>aquecimento global</b>.</li><li><b>Camada de ozônio</b>: filtra a radiação ultravioleta; foi destruída por <b>CFCs</b> (Protocolo de Montreal, 1987, os baniu).</li><li><b>Eutrofização</b>: excesso de nutrientes (esgoto, fertilizantes) → proliferação de algas → morte e decomposição → falta de O<sub>2</sub> → morte de peixes.</li><li><b>Chuva ácida</b>: óxidos de enxofre e nitrogênio (indústrias, veículos).</li><li><b>Ilhas de calor</b> e <b>inversão térmica</b> nas cidades.</li><li><b>Desmatamento</b>, <b>queimadas</b>, <b>perda de biodiversidade</b>, <b>espécies invasoras</b>, <b>lixo e microplásticos</b>.</li></ul>
<p>Soluções: energias renováveis, reflorestamento, saneamento, reciclagem, unidades de conservação e acordos como o <b>Acordo de Paris</b> (2015).</p>`,
{pairs:[['Aquecimento global','intensificação do efeito estufa pelo excesso de gases como CO₂ e metano'],['Destruição da camada de ozônio','causada por CFCs, aumenta a radiação ultravioleta que chega à Terra'],['Eutrofização','excesso de nutrientes na água que leva à falta de oxigênio e morte de peixes'],['Chuva ácida','causada por óxidos de enxofre e nitrogênio lançados no ar'],['Inversão térmica','camada de ar quente que prende a poluição perto do solo'],['Espécie invasora','espécie introduzida que se espalha e prejudica as nativas']],
 qs:[['A morte de peixes num lago que recebe esgoto doméstico está ligada à:','eutrofização, com falta de oxigênio',['chuva ácida','camada de ozônio','inversão térmica'],'Excesso de nutrientes → algas → decomposição consome O<sub>2</sub>.'],['O acordo internacional que baniu os CFCs para proteger a camada de ozônio foi o:','Protocolo de Montreal',['Acordo de Paris','Protocolo de Kyoto','Tratado de Tordesilhas'],'Protocolo de Montreal (1987).'],['O gás metano, que intensifica o efeito estufa, é liberado em grande quantidade:','pela digestão de ruminantes e pela decomposição em aterros',['pela fotossíntese','pelas usinas eólicas','pela respiração das plantas'],'Rebanhos bovinos e lixões são grandes fontes.']]})
]});

const GLOSS=autoGloss(UNITS,[
 {k:['mitose','meiose'],n:'Mitose e meiose',s:'divisao',t:'Mitose: 1 célula → 2 células idênticas (crescimento, regeneração). Meiose: 1 célula → 4 células com metade dos cromossomos (gametas), com variabilidade.'},
 {k:['vacina','soro'],n:'Vacina × soro',s:'imune',t:'Vacina: antígenos, imunidade ativa e duradoura (prevenção). Soro: anticorpos prontos, imunidade passiva e imediata (tratamento).'},
 {k:['mendel','punnett','primeira lei'],n:'1ª Lei de Mendel',s:'mendel',t:'Cada característica é determinada por um par de alelos que se separam nos gametas. Aa × Aa → 1 AA : 2 Aa : 1 aa (3 dominantes : 1 recessivo).'},
 {k:['osmose'],n:'Osmose',s:'membrana',t:'Passagem de água pela membrana, do meio menos concentrado (hipotônico) para o mais concentrado (hipertônico).'}]);
