
/* =====================================================================
   Banco FUVEST (Matemática) — questões ORIGINAIS no estilo da 1ª fase.
   Não são cópias de provas oficiais. Cada alternativa errada tem o erro
   típico que leva a ela; "steps" é a resolução e "trap" são passos com
   erros comuns usados no modo Montar resolução.
   ===================================================================== */
const FUVQ=[
{id:'fm01',area:'Progressões e geometria',tags:['pa','ang'],
 q:'As medidas dos ângulos internos de um triângulo estão em progressão aritmética, e o maior deles mede 80°. A medida do menor ângulo é',
 alts:['20°','30°','40°','50°','60°'],ans:2,
 why:['20° é a razão da PA, não o menor ângulo.','Com 30°, o termo médio seria 55° e a soma não daria 180°.','','50° não forma PA com soma 180° e maior termo 80°.','60° é o termo médio da PA (a), não o menor.'],
 steps:['Escreva os ângulos como a − r, a e a + r.','A soma dos ângulos internos é 180°: 3a = 180°, logo a = 60°.','O maior é a + r = 80°, então r = 20°.','O menor é a − r = 60° − 20° = 40°.'],
 trap:['A soma dos ângulos internos é 360°: 3a = 360°, logo a = 120°.','O menor é a + r = 80°.']},
{id:'fm02',area:'Probabilidade',tags:['prob','mmc'],
 q:'Dois dados comuns, não viciados, são lançados. A probabilidade de que a soma dos resultados seja um número primo é',
 alts:[F(5,12),F(7,18),F(5,11),F(1,3),F(1,2)],ans:0,
 why:['',`${F(7,18)} = ${F(14,36)}: faltou contar a soma 2 (1 + 1).`,`${F(5,11)} considera as 11 somas possíveis (2 a 12) igualmente prováveis — elas não são.`,`${F(1,3)} = ${F(12,36)}: faltaram as somas 2 e 3.`,`${F(1,2)} conta todas as somas ímpares, mas 9 não é primo e 2 (par) é primo.`],
 steps:['O espaço amostral tem 6 × 6 = 36 pares igualmente prováveis.','As somas primas possíveis são 2, 3, 5, 7 e 11.','Pares favoráveis: 1 + 2 + 4 + 6 + 2 = 15.',`P = ${F(15,36)} = ${F(5,12)}.`],
 trap:['Há 11 somas possíveis (2 a 12), todas igualmente prováveis.','As somas primas possíveis são 3, 5, 7, 9 e 11.']},
{id:'fm03',area:'Função quadrática',tags:['fquad'],
 q:'A altura, em metros, de um projétil lançado verticalmente é dada por h(t) = −5t² + 30t, com t em segundos. A altura máxima atingida e o instante em que ela ocorre são, respectivamente,',
 alts:['45 m e 3 s','90 m e 3 s','45 m e 6 s','30 m e 3 s','180 m e 6 s'],ans:0,
 why:['','90 m: calculou só 30·3, esquecendo o termo −5t².','6 s é o instante em que o projétil volta ao solo (raiz), não o do máximo.','30 m confunde o coeficiente b com a altura.','180 m e 6 s: usou t = 6 s, a raiz, no lugar do vértice.'],
 steps:['O máximo ocorre no vértice: t<sub>v</sub> = −b/(2a).','t<sub>v</sub> = −30/(2·(−5)) = 3 s.','h(3) = −5·9 + 30·3 = −45 + 90.','h<sub>máx</sub> = 45 m.'],
 trap:['t<sub>v</sub> = −b/a = 6 s.','h(3) = 5·9 + 30·3 = 135 m.']},
{id:'fm04',area:'Logaritmos',tags:['log'],
 q:'Considerando log 2 ≈ 0,30 e log 3 ≈ 0,48, o valor aproximado de log 72 é',
 alts:['0,78','0,864','1,38','1,86','2,04'],ans:3,
 why:['0,78 = log 2 + log 3: esqueceu os expoentes de 72 = 2³·3².','0,864 = 0,90 × 0,96: multiplicou os logaritmos em vez de somá-los.','1,38 = 3·0,30 + 0,48: esqueceu o expoente 2 de 3².','','2,04 = 2·0,30 + 3·0,48: trocou os expoentes (72 = 2³·3², não 2²·3³).'],
 steps:['Fatore: 72 = 2³ · 3².','log 72 = log 2³ + log 3².','log 72 = 3·log 2 + 2·log 3.','log 72 ≈ 0,90 + 0,96 = 1,86.'],
 trap:['log 72 = log 2³ · log 3².','log 72 = 2·log 2 + 3·log 3.']},
{id:'fm05',area:'Geometria analítica',tags:['gan','fafim'],
 q:'A reta que passa pelos pontos A(1, 2) e B(3, 8) intercepta o eixo das ordenadas no ponto',
 alts:['(0, −1)','(0, 1)','(1/3, 0)','(0, 2)','(0, −3)'],ans:0,
 why:['','(0, 1): erro de sinal ao isolar y em y − 2 = 3(x − 1).','(1/3, 0) é a interseção com o eixo x, não com o eixo y.','(0, 2): usou a ordenada de A como se A estivesse no eixo y.','(0, −3): usou y = 3x − 3, esquecendo de somar 2.'],
 steps:['Coeficiente angular: m = (8 − 2)/(3 − 1) = 3.','Equação: y − 2 = 3(x − 1).','Isolando: y = 3x − 1.','No eixo y, x = 0: y = −1 → ponto (0, −1).'],
 trap:['Coeficiente angular: m = (3 − 1)/(8 − 2) = 1/3.','No eixo y, y = 0: x = 1/3.']},
{id:'fm06',area:'Análise combinatória',tags:['comb'],
 q:'O número de anagramas da palavra FUVEST que começam e terminam por vogal é',
 alts:['12','24','48','96','720'],ans:2,
 why:['12: considerou só 3 letras no meio (3! · 2).','24: contou o meio (4!), mas esqueceu que U e E podem trocar de extremo.','','96: multiplicou por 2 mais de uma vez.','720 = 6!: são todos os anagramas, sem a restrição.'],
 steps:['Vogais: U e E. Consoantes: F, V, S, T.','Os extremos são as duas vogais: 2 maneiras (U…E ou E…U).','As 4 consoantes permutam no meio: 4! = 24.','Total: 2 × 24 = 48.'],
 trap:['As 6 letras permutam livremente: 6! = 720.','Os extremos só podem ser U…E: 1 maneira.']},
{id:'fm07',area:'Porcentagem',tags:['porc','juros'],
 q:'O preço de um produto sofreu um aumento de 25% e, em seguida, um desconto de 20%. Em relação ao preço inicial, o preço final é',
 alts:['5% maior','5% menor','igual','2% maior','45% maior'],ans:2,
 why:['5% maior: subtraiu as porcentagens (25% − 20%), mas elas incidem sobre valores diferentes.','5% menor: aplicou o desconto sobre o preço inicial e o aumento sobre o novo.','','2% maior: errou a multiplicação dos fatores.','45% maior: somou as porcentagens.'],
 steps:['Aumento de 25%: multiplicar por 1,25.','Desconto de 20%: multiplicar por 0,80.','Fator total: 1,25 × 0,80 = 1,00.','O preço final é igual ao inicial.'],
 trap:['Fator total: 25% − 20% = +5%.','Desconto de 20%: multiplicar por 1,20.']},
{id:'fm08',area:'Trigonometria',tags:['trig'],
 q:'Uma escada de 6 m está apoiada numa parede vertical e forma um ângulo de 60° com o chão horizontal. A altura, em metros, do ponto em que a escada toca a parede é',
 alts:['3','3√2','3√3','6√3','2√3'],ans:2,
 why:['3 = 6·cos 60°: essa é a distância do pé da escada à parede.','3√2 usaria sen 45°, não 60°.','','6√3: esqueceu de multiplicar por 1/2 (sen 60° = √3/2).','2√3 = 6·tg 30°: escolheu a razão errada.'],
 steps:['A escada é a hipotenusa do triângulo retângulo: 6 m.','A altura é o cateto oposto ao ângulo de 60°.','h = 6 · sen 60° = 6 · √3/2.','h = 3√3 m.'],
 trap:['A altura é o cateto adjacente ao ângulo de 60°.','h = 6 · cos 60° = 3 m.']},
{id:'fm09',area:'Equação do 2º grau',tags:['eq2'],
 q:'Uma das raízes da equação x² − 9x + k = 0 é o dobro da outra. O valor de k é',
 alts:['6','9','18','27','36'],ans:2,
 why:['6: tomou k como a maior raiz.','9 é a soma das raízes, não o produto.','','27 = 3 · 9: multiplicou a menor raiz pela soma.','36 = 6 · 6: elevou a maior raiz ao quadrado.'],
 steps:['Chame as raízes de r e 2r.','Soma das raízes: r + 2r = 9 (= −b/a), logo r = 3.','As raízes são 3 e 6.','k é o produto das raízes (c/a): k = 3 · 6 = 18.'],
 trap:['Soma das raízes: r + 2r = −9, logo r = −3.','k é a soma das raízes: k = 3 + 6 = 9.']},
{id:'fm10',area:'Geometria plana',tags:['area','pit'],
 q:'Um quadrado está inscrito em uma circunferência de raio 5 cm. A área do quadrado, em cm², é',
 alts:['25','50','100','25π','50π'],ans:1,
 why:['25: tomou o lado do quadrado igual ao raio.','','100: tomou o lado igual ao diâmetro (a diagonal é que mede 10).','25π é a área do círculo.','50π mistura a área do quadrado com π sem motivo.'],
 steps:['A diagonal do quadrado inscrito é o diâmetro: d = 10 cm.','d = ℓ√2, logo ℓ = 10/√2 = 5√2 cm.','Área = ℓ² = (5√2)² = 50 cm².'],
 trap:['O lado do quadrado é o diâmetro: ℓ = 10 cm.','Área = ℓ² = (5√2)² = 10√2 cm².']},
{id:'fm11',area:'Função exponencial',tags:['fexp','pg'],
 q:'Uma cultura de bactérias dobra de tamanho a cada 3 horas. Se ela começa com 500 bactérias, após quanto tempo terá 16 000 bactérias?',
 alts:['5 h','10 h','15 h','32 h','96 h'],ans:2,
 why:['5 h é o número de duplicações (2⁵ = 32), não o tempo.','10 h: usou 2 horas por duplicação.','','32 h: confundiu o fator de crescimento com o tempo.','96 h = 32 × 3: multiplicou o fator (32) em vez do expoente (5) pelas 3 horas.'],
 steps:['N(t) = 500 · 2<sup>t/3</sup>.','16 000 = 500 · 2<sup>t/3</sup> ⇒ 2<sup>t/3</sup> = 32.','32 = 2⁵, logo t/3 = 5.','t = 15 horas.'],
 trap:['32 = 2⁵, logo t = 5 horas.','2<sup>t/3</sup> = 16 000 − 500.']},
{id:'fm12',area:'Estatística',tags:['est'],
 q:'A média aritmética de cinco números é 8. Retirando-se um deles, a média dos quatro restantes passa a ser 7. O número retirado é',
 alts:['1','7','8','12','15'],ans:3,
 why:['1 = 8 − 7: subtraiu as médias, não as somas.','7 é a nova média.','8 é a média antiga — só seria retirado se a média não mudasse.','','15 = 8 + 7: somou as médias.'],
 steps:['Soma dos 5 números: 5 · 8 = 40.','Soma dos 4 restantes: 4 · 7 = 28.','Número retirado: 40 − 28 = 12.'],
 trap:['Número retirado: 8 − 7 = 1.','Soma dos 4 restantes: 5 · 7 = 35.']},
{id:'fm13',area:'Sistemas lineares',tags:['sist'],
 q:'Em um estacionamento há apenas carros e motos, totalizando 40 veículos e 130 rodas. O número de motos é',
 alts:['10','15','20','25','65'],ans:1,
 why:['10: errou a eliminação no sistema.','','20: dividiu os veículos igualmente.','25 é o número de carros.','65 = 130/2: dividiu as rodas por 2, como se todos fossem motos.'],
 steps:['Sejam C carros e M motos: C + M = 40 e 4C + 2M = 130.','Multiplicando a primeira por 2: 2C + 2M = 80.','Subtraindo: 2C = 50, logo C = 25.','M = 40 − 25 = 15 motos.'],
 trap:['Somando as equações: 5C + 3M = 170.','Resposta: 25 motos.']},
{id:'fm14',area:'Números complexos',tags:['cpx'],
 q:'O módulo do número complexo z = (1 + i)⁴ é',
 alts:['−4','2','2√2','4','16'],ans:3,
 why:['−4 é o próprio z; o módulo nunca é negativo.','2 = |1 + i|²: parou na segunda potência.','2√2 = |1 + i|³.','','16: elevou 2 (e não √2) à quarta potência.'],
 steps:['(1 + i)² = 1 + 2i + i² = 2i.','(1 + i)⁴ = (2i)² = 4i² = −4.','|z| = |−4| = 4.'],
 trap:['(1 + i)² = 1 + i² = 0.','|z| = −4.']},
{id:'fm15',area:'Progressão geométrica',tags:['pg'],
 q:'A soma dos infinitos termos da progressão geométrica (12, 6, 3, …) é',
 alts:['18','21','24','36','infinita'],ans:2,
 why:['18 = 12 + 6: somou só dois termos.','21 = 12 + 6 + 3: somou só três termos.','','36: usou S = a₁/q.','Com |q| < 1, a soma converge.'],
 steps:['a₁ = 12 e q = 6/12 = 1/2.','Como |q| < 1, a soma infinita é S = a₁/(1 − q).','S = 12/(1/2) = 24.'],
 trap:['q = 12/6 = 2, logo a soma é infinita.','S = a₁/(1 + q) = 8.']},
{id:'fm16',area:'Matrizes',tags:['mat','eq2'],
 q:`Os valores reais de x para os quais a matriz ${MX([['x',2],[3,'x + 1']])} não é invertível são`,
 alts:['2 e −3','−2 e 3','0 e −1','1 e −6','somente 6'],ans:0,
 why:['','−2 e 3: erro de sinal ao resolver x² + x − 6 = 0.','0 e −1 anulam x(x + 1), mas esqueceu o termo 2·3.','1 e −6 resolvem x² + 5x − 6 = 0, equação errada.','6 é o produto 2·3, não um valor de x.'],
 steps:['Uma matriz não é invertível quando o determinante é zero.','det = x(x + 1) − 2·3.','x² + x − 6 = 0.','x = 2 ou x = −3.'],
 trap:['det = x(x + 1) + 2·3.','Uma matriz não é invertível quando o determinante é 1.']},
{id:'fm17',area:'Semelhança',tags:['tales','prop'],
 q:'Num mesmo instante, um poste projeta uma sombra de 12 m e uma pessoa de 1,80 m projeta uma sombra de 2,40 m. A altura do poste é',
 alts:['6 m','9 m','12 m','14,4 m','16 m'],ans:1,
 why:['6 m: dividiu a sombra por 2 sem montar a proporção.','','12 m: igualou altura e sombra (só vale com o Sol a 45°).','14,4 m: multiplicou 12 por 1,2.','16 m: inverteu a razão (12 · 2,40/1,80).'],
 steps:['Os triângulos altura–sombra são semelhantes.','H/12 = 1,80/2,40.','H = 12 · 0,75 = 9 m.'],
 trap:['H/12 = 2,40/1,80.','H = 12 · 1,80 · 2,40 = 51,84 m.']},
{id:'fm18',area:'Geometria espacial',tags:['esp'],
 q:'Um cilindro tem raio da base 3 cm e altura 10 cm. O volume de um cone com a mesma base e a mesma altura, usando π ≈ 3, é',
 alts:['30 cm³','60 cm³','90 cm³','180 cm³','270 cm³'],ans:2,
 why:['30 cm³: dividiu por 3 duas vezes.','60 cm³: usou r·h·2 em vez de r²·h.','','180 cm³: dividiu o cilindro por 1,5.','270 cm³ é o volume do cilindro.'],
 steps:['Volume do cilindro: π r² h = 3 · 9 · 10 = 270 cm³.','O cone tem 1/3 do volume do cilindro de mesma base e altura.','V = 270/3 = 90 cm³.'],
 trap:['O cone tem 1/2 do volume do cilindro.','Volume do cilindro: π r h = 90 cm³.']},
{id:'fm19',area:'Conjuntos',tags:['conj'],
 q:'Numa turma de 50 alunos, 30 gostam de Matemática, 25 gostam de Física e 10 não gostam de nenhuma das duas. O número de alunos que gostam das duas matérias é',
 alts:['5','10','15','20','25'],ans:2,
 why:['5 = 30 + 25 − 50: esqueceu os 10 que não gostam de nenhuma.','10 é o número dos que não gostam de nenhuma.','','20: errou a subtração.','25 é o número dos que gostam de Física.'],
 steps:['Gostam de pelo menos uma: 50 − 10 = 40.','n(M ∪ F) = n(M) + n(F) − n(M ∩ F).','40 = 30 + 25 − x.','x = 15.'],
 trap:['Gostam de pelo menos uma: 50 alunos.','n(M ∪ F) = n(M) + n(F) + n(M ∩ F).']},
{id:'fm20',area:'Função afim e inequações',tags:['fafim','ineq'],
 q:'A empresa A cobra R$ 40,00 fixos mais R$ 2,00 por quilômetro; a empresa B cobra R$ 20,00 fixos mais R$ 3,00 por quilômetro. A empresa A é mais vantajosa para percursos',
 alts:['de menos de 20 km','de mais de 20 km','de mais de 12 km','de mais de 60 km','de qualquer distância'],ans:1,
 why:['Menos de 20 km: inverteu o sentido da desigualdade.','','12 km: dividiu 60 por 5 somando os preços por km.','60 km: somou os valores fixos.','Para pouca distância, B é mais barata (taxa fixa menor).'],
 steps:['Custo de A: 40 + 2x. Custo de B: 20 + 3x.','A é mais vantajosa quando 40 + 2x < 20 + 3x.','20 < x.','A compensa para mais de 20 km.'],
 trap:['A é mais vantajosa quando 40 + 2x > 20 + 3x.','x < 20: A compensa para menos de 20 km.']},
{id:'fm21',area:'MMC',tags:['mmc'],
 q:'Três luzes piscam a cada 12 s, 18 s e 30 s, respectivamente. Se às 8h00min00s piscaram juntas, elas voltarão a piscar juntas pela primeira vez às',
 alts:['8h00min06s','8h01min00s','8h03min00s','8h06min00s','8h10min00s'],ans:2,
 why:['6 s é o MDC(12, 18, 30), não o MMC.','1 minuto = 12 + 18 + 30 segundos: somou os intervalos.','','6 minutos = 360 s: usou um múltiplo comum, mas não o menor.','10 minutos: usou 12·18·30 dividido de forma errada.'],
 steps:['Procuramos o menor tempo múltiplo de 12, 18 e 30: o MMC.','12 = 2²·3, 18 = 2·3², 30 = 2·3·5.','MMC = 2²·3²·5 = 180 s = 3 min.','Piscarão juntas às 8h03min00s.'],
 trap:['Procuramos o MDC(12, 18, 30) = 6 s.','MMC = 12 + 18 + 30 = 60 s.']},
{id:'fm22',area:'Radiciação',tags:['raiz','alg'],
 q:'O valor de (√8 + √18)² é',
 alts:['26','5√2','50','72','100'],ans:2,
 why:['26 = 8 + 18: esqueceu o termo 2ab do quadrado da soma.','5√2 é √8 + √18 — faltou elevar ao quadrado.','','72 = 8·9: somou errado os radicais.','100 = (√8 + √18)² com √8 + √18 = 10, o que é falso.'],
 steps:['√8 = 2√2 e √18 = 3√2.','√8 + √18 = 5√2.','(5√2)² = 25 · 2 = 50.'],
 trap:['(√8 + √18)² = 8 + 18 = 26.','√8 + √18 = √26.']},
{id:'fm23',area:'Ciclo trigonométrico',tags:['ciclo','trig'],
 q:'O número de soluções da equação sen x = 1/2 no intervalo 0 ≤ x < 2π é',
 alts:['nenhuma','1','2','3','4'],ans:2,
 why:['Existem soluções, pois 1/2 está entre −1 e 1.','1: considerou só x = π/6 e esqueceu o 2º quadrante.','','3: contou π/6, 5π/6 e 13π/6 (fora do intervalo).','4: somou também as soluções de cos x = 1/2.'],
 steps:['O seno é positivo no 1º e no 2º quadrantes.','No 1º quadrante: x = π/6.','No 2º quadrante: x = π − π/6 = 5π/6.','São 2 soluções.'],
 trap:['O seno é positivo no 1º e no 4º quadrantes.','No 2º quadrante: x = π + π/6.']},
{id:'fm24',area:'Geometria espacial',tags:['esp','pit'],
 q:'A diagonal de um cubo de aresta 2 cm mede',
 alts:['2√2 cm','2√3 cm','4 cm','6 cm','12 cm'],ans:1,
 why:['2√2 cm é a diagonal de uma face, não do cubo.','','4 cm: somou duas arestas.','6 cm: somou três arestas.','12 cm é o quadrado da diagonal (D² = 12).'],
 steps:['Diagonal de uma face: d = a√2 = 2√2 cm.','A diagonal do cubo é a hipotenusa do triângulo de catetos d e a.','D² = d² + a² = 8 + 4 = 12.','D = √12 = 2√3 cm.'],
 trap:['A diagonal do cubo é igual à diagonal da face.','D² = d² − a² = 4, logo D = 2 cm.']},
];
