const BRAND={app:'SaberLingo',chatPh:'ex.: o que é metáfora?',tutor:'Professora Letícia',sym:'Aa',body:'#ce82ff',dark:'#a568cc',belly:'#f3e3ff',lsKey:'portlingo_v1',first:'silaba',
 welcome:'Português do <b>Fundamental ao Ensino Médio</b>: ortografia, gramática, interpretação de texto e literatura, em lições curtas com repetição espaçada.',
 range:'do Fundamental ao Ensino Médio (ENEM e vestibulares)',searchEx:'ex.: crase',firstName:'Sílabas e divisão silábica',
 chips:['O que é metáfora?','Quando usar crase?','Sujeito oculto','Porque ou por quê?','O que é Modernismo?','Funções da linguagem'],
 askEx:'<i>"o que é metonímia?"</i>, <i>"crase"</i>, <i>"sujeito indeterminado"</i>',
 formulas:'acentuação, crase, concordância, regência, colocação pronominal e pontuação'};
const UNITS=[];

/* ---------- geradores próprios de Português ---------- */
/* divisão silábica: as erradas deslocam uma fronteira de sílaba */
function sepWrongs(w){ const parts=w.split('-'),out=new Set();
  for(let i=0;i<parts.length-1;i++){ const a=parts[i],b=parts[i+1];
    if(a.length>1){ const p=parts.slice(); p[i]=a.slice(0,-1); p[i+1]=a.slice(-1)+b; out.add(p.join('-')); }
    if(b.length>1){ const p=parts.slice(); p[i]=a+b[0]; p[i+1]=b.slice(1); out.add(p.join('-')); } }
  out.add(parts.join('')); out.delete(w); return shuffle([...out]); }
const SEP=['car-ro','pás-sa-ro','pa-ís','sa-í-da','sa-ú-de','ra-i-nha','ca-der-no','ex-ce-ção','nas-cer','cres-cer','ex-ces-so','ad-vo-ga-do','rit-mo','psi-có-lo-go','e-nig-ma','gno-mo','sub-ma-ri-no','guer-ra','quei-jo','Pa-ra-guai','sa-guão','co-o-pe-rar','vo-o','mei-o','i-dei-a','ap-to','fic-ção','cai-xa','mos-qui-to','pers-pi-caz','ab-dô-men','of-tal-mo-lo-gis-ta','ma-ni-a','ju-iz','tran-qui-lo','sos-se-go','des-cer'];
const SEPX={'car-ro':'Dígrafo <b>rr</b> se separa.','pás-sa-ro':'Dígrafo <b>ss</b> se separa.','pa-ís':'Hiato (a-í): vogais em sílabas diferentes.','sa-í-da':'Hiato a-í.','sa-ú-de':'Hiato a-ú.','ra-i-nha':'Hiato a-i; <b>nh</b> não se separa.','ex-ce-ção':'Dígrafo <b>xc</b> se separa.','nas-cer':'Dígrafo <b>sc</b> se separa.','cres-cer':'Dígrafo <b>sc</b> se separa.','ex-ces-so':'<b>xc</b> e <b>ss</b> se separam.','ad-vo-ga-do':'Consoante muda sem vogal fica na sílaba anterior: <b>ad</b>-vo.','rit-mo':'Encontro consonantal separável: <b>t-m</b>.','psi-có-lo-go':'<b>ps</b> no início da palavra não se separa.','e-nig-ma':'<b>g-m</b> no meio da palavra se separa.','gno-mo':'<b>gn</b> no início da palavra não se separa.','sub-ma-ri-no':'Prefixo sub + consoante: sub-ma.','guer-ra':'<b>gu</b> é dígrafo (não se separa); <b>rr</b> se separa.','quei-jo':'<b>qu</b> é dígrafo e <b>ei</b> é ditongo: não se separam.','Pa-ra-guai':'Tritongo <b>uai</b> fica na mesma sílaba.','sa-guão':'Tritongo <b>uão</b> não se separa.','co-o-pe-rar':'Hiato <b>o-o</b>.','vo-o':'Hiato <b>o-o</b> (sem acento desde o Acordo de 2009).','mei-o':'Ditongo <b>ei</b> + vogal <b>o</b> em outra sílaba.','i-dei-a':'Ditongo <b>ei</b> (sem acento desde o Acordo de 2009).','ap-to':'Consoante muda <b>p</b> fica com a sílaba anterior.','fic-ção':'<b>c-ç</b> se separam.','cai-xa':'Ditongo <b>ai</b> não se separa.','mos-qui-to':'<b>qu</b> é dígrafo.','pers-pi-caz':'<b>rs</b> + consoante: pers-pi.','ab-dô-men':'Consoante muda <b>b</b> fica na sílaba anterior.','of-tal-mo-lo-gis-ta':'<b>f-t</b> e <b>l-m</b> se separam.','ma-ni-a':'Hiato <b>i-a</b>.','ju-iz':'Hiato <b>u-i</b>.','tran-qui-lo':'<b>qu</b> é dígrafo; <b>n</b> fecha a sílaba tran.','sos-se-go':'Dígrafo <b>ss</b> se separa.','des-cer':'Dígrafo <b>sc</b> se separa.'};
const sepGen=lv=>{ const w=pick(SEP); return MC(`Qual é a divisão silábica correta de <b>${w.replace(/-/g,'')}</b>?`,w,sepWrongs(w),`<b>${w}</b>. ${SEPX[w]||''}`,'Separe dígrafos rr, ss, sc, xc; não separe ch, lh, nh, qu, gu, ditongos e tritongos; separe hiatos.'); };
/* tonicidade */
const TON=[['café','oxítona'],['jacaré','oxítona'],['parabéns','oxítona'],['sofá','oxítona'],['você','oxítona'],['amor','oxítona'],['papel','oxítona'],['urubu','oxítona'],['ninguém','oxítona'],['Paraná','oxítona'],['ruim','oxítona','ru-IM: a tônica é a última sílaba.'],['Nobel','oxítona','no-BEL.'],['casa','paroxítona'],['lápis','paroxítona'],['fácil','paroxítona'],['açúcar','paroxítona'],['táxi','paroxítona'],['caráter','paroxítona'],['hífen','paroxítona'],['vírus','paroxítona'],['júri','paroxítona'],['ideia','paroxítona'],['órfão','paroxítona'],['rubrica','paroxítona','ru-BRI-ca (e não "rúbrica").'],['recorde','paroxítona','re-COR-de.'],['gratuito','paroxítona','gra-TUI-to.'],['lâmpada','proparoxítona'],['pássaro','proparoxítona'],['médico','proparoxítona'],['árvore','proparoxítona'],['música','proparoxítona'],['fósforo','proparoxítona'],['sílaba','proparoxítona'],['relâmpago','proparoxítona'],['ônibus','proparoxítona'],['xícara','proparoxítona'],['pêssego','proparoxítona'],['matemática','proparoxítona']];
const tonGen=lv=>{ const [w,c,x]=pick(TON); return MC(`Quanto à posição da sílaba tônica, a palavra <b>${w}</b> é:`,c,['oxítona','paroxítona','proparoxítona'].filter(v=>v!==c),`<b>${w}</b> é <b>${c}</b>. ${x||(c==='oxítona'?'A tônica é a última sílaba.':c==='paroxítona'?'A tônica é a penúltima sílaba.':'A tônica é a antepenúltima sílaba.')}`,'Leia em voz alta e veja qual sílaba é mais forte: última (oxítona), penúltima (paroxítona) ou antepenúltima (proparoxítona).',{keep:true}); };
/* conjugação de verbos regulares */
const VERBS=[['cantar','cant','ar'],['falar','fal','ar'],['estudar','estud','ar'],['andar','and','ar'],['trabalhar','trabalh','ar'],['amar','am','ar'],['vender','vend','er'],['beber','beb','er'],['comer','com','er'],['correr','corr','er'],['aprender','aprend','er'],['partir','part','ir'],['dividir','divid','ir'],['decidir','decid','ir'],['assistir','assist','ir'],['discutir','discut','ir'],['permitir','permit','ir']];
const TENSES={
 'presente do indicativo':{ar:['o','as','a','amos','ais','am'],er:['o','es','e','emos','eis','em'],ir:['o','es','e','imos','is','em']},
 'pretérito perfeito do indicativo':{ar:['ei','aste','ou','amos','astes','aram'],er:['i','este','eu','emos','estes','eram'],ir:['i','iste','iu','imos','istes','iram']},
 'pretérito imperfeito do indicativo':{ar:['ava','avas','ava','ávamos','áveis','avam'],er:['ia','ias','ia','íamos','íeis','iam'],ir:['ia','ias','ia','íamos','íeis','iam']},
 'futuro do presente do indicativo':{ar:['arei','arás','ará','aremos','areis','arão'],er:['erei','erás','erá','eremos','ereis','erão'],ir:['irei','irás','irá','iremos','ireis','irão']},
 'futuro do pretérito do indicativo':{ar:['aria','arias','aria','aríamos','aríeis','ariam'],er:['eria','erias','eria','eríamos','eríeis','eriam'],ir:['iria','irias','iria','iríamos','iríeis','iriam']},
 'presente do subjuntivo':{ar:['e','es','e','emos','eis','em'],er:['a','as','a','amos','ais','am'],ir:['a','as','a','amos','ais','am']}};
const PESS=['eu','tu','ele/ela','nós','vós','eles/elas'],PESSN=['1ª pessoa do singular (eu)','2ª pessoa do singular (tu)','3ª pessoa do singular (ele/ela)','1ª pessoa do plural (nós)','2ª pessoa do plural (vós)','3ª pessoa do plural (eles/elas)'];
const conj=(v,t,p)=>v[1]+TENSES[t][v[2]][p];
const conjGens=[
 lv=>{ const v=pick(VERBS),t=pick(Object.keys(TENSES)),p=pick([0,2,3,5]); const c=conj(v,t,p);
   return MC(`Qual é a forma do verbo <b>${v[0]}</b> na <b>${PESSN[p]}</b> do <b>${t}</b>?`,c,Object.keys(TENSES).filter(x=>x!==t).map(x=>conj(v,x,p)),`${PESS[p]} <b>${c}</b> (${t}). Verbo regular da ${v[2]==='ar'?'1ª':v[2]==='er'?'2ª':'3ª'} conjugação (-${v[2]}).`,'Tire a terminação -ar/-er/-ir e acrescente a desinência do tempo pedido.'); },
 lv=>{ let v,t,p,c,tries=0; do{ v=pick(VERBS); t=pick(Object.keys(TENSES)); p=pick([0,2,3,5]); c=conj(v,t,p); tries++; }while(tries<20&&Object.keys(TENSES).some(x=>x!==t&&conj(v,x,p)===c));
   return MC(`Em que tempo e modo está a forma verbal <b>${c}</b> (verbo ${v[0]})?`,t,Object.keys(TENSES).filter(x=>x!==t),`<b>${c}</b>: ${PESS[p]}, ${t}.`,'Compare as terminações: -ava/-ia (imperfeito), -ei/-i (perfeito), -rei (futuro), -ria (futuro do pretérito).'); },
 lv=>{ const v=pick(VERBS),p=pick([0,2,3,5]); const frames=[['Ontem','pretérito perfeito do indicativo'],['Amanhã','futuro do presente do indicativo'],['Antigamente,','pretérito imperfeito do indicativo'],['Todos os dias','presente do indicativo']]; const [adv,t]=pick(frames); const c=conj(v,t,p);
   const subj=['eu','—','ela','nós','—','eles'][p];
   return BANK('Complete com a forma verbal adequada',`${adv} ${subj} @@ (${v[0]}).`,c,Object.keys(TENSES).filter(x=>x!==t).map(x=>conj(v,x,p)),`"${adv}" pede o <b>${t}</b>: ${subj} <b>${c}</b>.`,'O advérbio de tempo indica se a ação é passada, presente ou futura.'); }];

/* ------------------------ UNIDADE 1 — A ESCRITA ------------------------ */
UNITS.push({id:'p1',title:'Sons, sílabas e escrita',sub:'Fundamental · divisão silábica, acentuação, ortografia e pontuação',color:'#ce82ff',dark:'#a568cc',skills:[
SKL('silaba','Sílabas e divisão silábica','✂️','Separe dígrafos rr, ss, sc, sç, xc e hiatos; nunca separe ch, lh, nh, qu, gu, ditongos e tritongos.',
`<p><b>Sílaba</b> é cada impulso de voz ao pronunciar uma palavra. Toda sílaba tem uma <b>vogal</b>.</p>
<h3>Encontros vocálicos</h3><ul><li><b>Ditongo</b>: vogal + semivogal na mesma sílaba (<i>cai-xa, mei-o</i>).</li><li><b>Tritongo</b>: semivogal + vogal + semivogal (<i>Pa-ra-<b>guai</b>, sa-<b>guão</b></i>).</li><li><b>Hiato</b>: vogais em sílabas diferentes (<i>sa-<b>ú</b>-de, vo-o</i>).</li></ul>
<h3>Dígrafos</h3><p>Duas letras e um só som. <b>Separam-se</b>: rr, ss, sc, sç, xc (<i>car-ro, nas-cer, ex-ce-ção</i>). <b>Não se separam</b>: ch, lh, nh, qu, gu (<i>fi-lho, quei-jo</i>).</p>
<div class="ex">Consoante sem vogal no meio da palavra fica com a sílaba anterior: <b>ad</b>-vo-ga-do, <b>ap</b>-to, <b>rit</b>-mo. No início, fica com a seguinte: <b>psi</b>-có-lo-go, <b>gno</b>-mo.</div>`,
{gens:[sepGen,sepGen],pairs:[['Ditongo','encontro de vogal e semivogal na mesma sílaba, como em "cai-xa"'],['Tritongo','semivogal + vogal + semivogal na mesma sílaba, como em "Pa-ra-guai"'],['Hiato','vogais vizinhas em sílabas diferentes, como em "sa-ú-de"'],['Dígrafo','duas letras que representam um só som, como "ch" e "rr"'],['Encontro consonantal','duas consoantes com sons distintos, como "bl" em "bloco"'],['Monossílabo','palavra de uma só sílaba, como "mar"']],
 tf:[['Na divisão silábica, o dígrafo "rr" fica na mesma sílaba.',false,'Falso: rr, ss, sc, sç e xc se separam (car-ro).'],['Em "quei-jo", "qu" é dígrafo e não se separa.',true,'Verdadeiro.'],['"Saúde" tem hiato.',true,'Verdadeiro: sa-ú-de.'],['"Psicólogo" separa-se "p-si-có-lo-go".',false,'Falso: ps no início fica junto: psi-có-lo-go.']]}),
SKL('acento','Tonicidade e acentuação','✒️','Toda proparoxítona é acentuada. Oxítonas: acentue as terminadas em a(s), e(s), o(s), em(ens).',
`<p>Pela posição da sílaba tônica: <b>oxítona</b> (última: ca-<b>fé</b>), <b>paroxítona</b> (penúltima: <b>me</b>-sa), <b>proparoxítona</b> (antepenúltima: <b>lâm</b>-pa-da).</p>
<h3>Regras principais</h3><ul><li><b>Proparoxítonas</b>: todas são acentuadas (<i>música, pássaro</i>).</li><li><b>Oxítonas</b>: terminadas em <b>a(s), e(s), o(s), em, ens</b> (<i>sofá, café, avô, ninguém, parabéns</i>).</li><li><b>Paroxítonas</b>: terminadas em <b>l, n, r, x, ps, ã(s), ão(s), i(s), us, um, uns, ditongo oral</b> (<i>fácil, hífen, açúcar, tórax, bíceps, órfã, órgão, táxi, vírus, álbum, história</i>). As terminadas em a, e, o, em <b>não</b> levam acento (<i>casa, item</i>).</li><li><b>Monossílabos tônicos</b> em a(s), e(s), o(s): <i>pá, pé, nó</i>.</li></ul>
<h3>Acordo Ortográfico (2009)</h3><ul><li>Caiu o acento dos ditongos abertos <b>ei, oi</b> em paroxítonas: <i>ideia, heroico, assembleia</i> (mas <i>herói, papéis</i> — oxítonas — mantêm).</li><li>Caiu o acento de <b>oo</b> e <b>ee</b>: <i>voo, enjoo, leem, creem</i>.</li><li>Caiu o <b>trema</b>: <i>linguiça, frequente</i>.</li><li>Caíram os diferenciais de <i>para</i> (verbo), <i>pelo, polo</i>. Ficaram <b>pôr</b> (verbo) e <b>pôde</b> (passado).</li></ul>`,
{gens:[tonGen,tonGen],qs:[['Qual palavra está acentuada <b>incorretamente</b>, segundo o Acordo Ortográfico?','idéia',['herói','café','ônibus'],'Desde 2009, paroxítonas com ditongo aberto "ei" não levam acento: <b>ideia</b>. "Herói" é oxítona e mantém.'],['Por que "táxi" leva acento?','É paroxítona terminada em i',['É oxítona terminada em i','É proparoxítona','Todo x exige acento'],'Paroxítonas terminadas em <b>i(s)</b> são acentuadas: táxi, júri, lápis.'],['Por que "café" leva acento?','É oxítona terminada em e',['É paroxítona terminada em e','É proparoxítona','É monossílabo tônico'],'Oxítonas terminadas em a(s), e(s), o(s), em, ens são acentuadas.'],['Qual palavra NÃO deveria ter acento?','heróico',['herói','lâmpada','fácil'],'"Heroico" é paroxítona com ditongo aberto oi: perdeu o acento no Acordo de 2009. "Herói" (oxítona) mantém.'],['Qual é a grafia correta, segundo o Acordo?','voo',['vôo','voô','vóo'],'Caiu o acento circunflexo do hiato "oo": voo, enjoo.'],['"Ele ___ ir ontem, mas hoje não pode." Complete:','pôde',['pode','pôdi','podê'],'<b>Pôde</b> (pretérito) mantém o acento diferencial em relação a <b>pode</b> (presente).'],['Qual palavra está grafada corretamente?','linguiça',['lingüiça','linguíça','lingüíça'],'O trema foi abolido: linguiça, frequente, cinquenta.']],
 tf:[['Toda proparoxítona é acentuada.',true,'Verdadeiro: lâmpada, pássaro, médico.'],['"Item" leva acento por ser paroxítona terminada em -em.',false,'Falso: paroxítonas terminadas em -em não são acentuadas (item, hífen é que tem -en).'],['"Pôr" (verbo) mantém o acento diferencial.',true,'Verdadeiro: pôr (verbo) × por (preposição).'],['"Ideia" continua com acento agudo após o Acordo.',false,'Falso: ideia, assembleia, heroico perderam o acento.']]}),
SKL('ortog','Ortografia','🔤','Na dúvida entre letras, pense na família da palavra: casa → casinha, caseiro (com s).',
`<p>Muitos erros vêm de letras com o mesmo som. Dicas que resolvem a maioria dos casos:</p>
<ul><li><b>X</b> depois de ditongo (<i>caixa, peixe</i>), depois de <i>en-</i> (<i>enxada, enxergar</i>) e depois de <i>me-</i> (<i>mexer, mexerica</i>). Exceção: <i>encher</i> (de cheio), <i>mecha</i>.</li><li><b>-ês / -esa</b> em origem e títulos (<i>português, francesa, princesa</i>); <b>-ez / -eza</b> em substantivos abstratos de adjetivos (<i>rapidez, beleza</i>).</li><li><b>-isar</b> quando a palavra já tem s (<i>análise → analisar, pesquisa → pesquisar</i>); <b>-izar</b> nos demais (<i>real → realizar</i>).</li><li><b>Ç</b> nunca antes de e ou i e nunca no início de palavra.</li><li><b>G/J</b>: <i>-agem</i> com g (<i>viagem</i>, substantivo), mas <i>viajem</i> (verbo) com j; palavras de origem tupi e africana com j (<i>jiboia, jiló, canjica</i>).</li></ul>
<h3>Porquês</h3><ul><li><b>por que</b>: pergunta ou "pelo qual" (<i>Por que você saiu?</i>)</li><li><b>por quê</b>: no fim da frase (<i>Você saiu por quê?</i>)</li><li><b>porque</b>: explicação/causa (<i>Saí porque choveu.</i>)</li><li><b>porquê</b>: substantivo, com artigo (<i>Não sei o porquê.</i>)</li></ul>
<h3>Parecidas</h3><p><b>mas</b> (porém) × <b>mais</b> (quantidade); <b>mal</b> (oposto de bem) × <b>mau</b> (oposto de bom); <b>há</b> (tempo passado) × <b>a</b> (tempo futuro/distância): "Saí há dois dias; volto daqui a dois dias".</p>`,
{bank:[['@@ você não veio à festa?','Por que',['Porque','Por quê','Porquê'],'Pergunta direta no início: <b>por que</b>.'],['Não fui à aula @@ estava doente.','porque',['por que','por quê','porquê'],'Explicação/causa: <b>porque</b>.'],['Você chegou atrasado @@?','por quê',['porque','por que','porquê'],'No fim da frase: <b>por quê</b>.'],['Ninguém entendeu o @@ da decisão.','porquê',['porque','por que','por quê'],'Com artigo ("o porquê") é substantivo: <b>porquê</b>.'],['Estudou muito, @@ não passou.','mas',['mais','más','mais que'],'Ideia de oposição (porém): <b>mas</b>.'],['Ele é um @@ aluno.','mau',['mal','máu','mals'],'Oposto de <b>bom</b>: <b>mau</b> (adjetivo).'],['Ela dormiu @@ esta noite.','mal',['mau','máu','mals'],'Oposto de <b>bem</b>: <b>mal</b> (advérbio).'],['Moro aqui @@ dez anos.','há',['a','à','ah'],'Tempo passado: <b>há</b> (= faz).'],['A prova será daqui @@ dois dias.','a',['há','à','ha'],'Tempo futuro: <b>a</b>.'],['Precisamos @@ a sala para a reunião.','analisar',['analizar','annalisar','analisár'],'Vem de análi<b>s</b>e: anali<b>s</b>ar.'],['A @@ foi longa e cansativa.','viagem',['viajem','viájem','viagen'],'Substantivo: via<b>g</b>em. (Verbo: que eles via<b>j</b>em.)'],['Ele colocou o peixe na @@.','caixa',['caicha','cáixa','caisha'],'Depois de ditongo usa-se <b>x</b>: caixa, peixe.'],['Vou @@ o balde de água.','encher',['enxer','inxer','incher'],'Exceção: <b>encher</b> vem de "cheio".'],['A @@ dele impressionou a todos.','rapidez',['rapidês','rapides','rapideza'],'Substantivo abstrato derivado de adjetivo: -ez (rápido → rapidez).'],['Ela é @@ e mora em Lisboa.','portuguesa',['portugueza','portugêsa','portugesa'],'Origem: -ês/-esa (português, portuguesa).']]}),
SKL('pontua','Pontuação','❗','Não se separa sujeito e verbo com vírgula. Use vírgula para isolar vocativo, aposto, adjunto adverbial deslocado e itens de uma enumeração.',
`<h3>Vírgula: quando usar</h3><ul><li>Separar itens de enumeração: <i>Comprei arroz, feijão e óleo.</i></li><li>Isolar o <b>vocativo</b>: <i>Maria, venha cá.</i></li><li>Isolar o <b>aposto</b>: <i>Pedro, meu vizinho, é médico.</i></li><li>Isolar <b>adjunto adverbial deslocado</b> (sobretudo longo): <i>Na manhã seguinte, saímos cedo.</i></li><li>Antes de conjunções adversativas: <i>Estudei, mas não passei.</i></li><li>Isolar orações explicativas: <i>O homem, que é mortal, erra.</i></li><li>Indicar omissão de verbo (zeugma): <i>Eu prefiro café; ela, chá.</i></li></ul>
<h3>Quando NÃO usar</h3><p>Entre <b>sujeito e verbo</b> e entre <b>verbo e complemento</b>: <s>Os alunos, fizeram a prova.</s> → <i>Os alunos fizeram a prova.</i></p>
<h3>Outros sinais</h3><p><b>Ponto e vírgula</b> separa partes longas ou já com vírgulas; <b>dois-pontos</b> anunciam citação, enumeração ou explicação; <b>travessão</b> marca fala ou destaque; <b>reticências</b> indicam interrupção ou hesitação.</p>`,
{qs:[['Qual frase está pontuada corretamente?','Os alunos da turma B fizeram a prova.',['Os alunos da turma B, fizeram a prova.','Os alunos, da turma B fizeram, a prova.','Os alunos da turma B fizeram, a prova.'],'Não se separa o sujeito do verbo nem o verbo do complemento.'],['Em "Carlos, traga o livro", a vírgula isola:','o vocativo',['o aposto','o sujeito','o adjunto adverbial'],'"Carlos" é quem está sendo chamado: <b>vocativo</b>.'],['Em "Brasília, a capital do Brasil, foi inaugurada em 1960", o trecho entre vírgulas é:','um aposto',['um vocativo','o sujeito','um adjunto adverbial'],'O <b>aposto</b> explica um termo anterior e vem isolado por vírgulas.'],['Qual frase usa a vírgula para indicar a omissão de um verbo?','Eu gosto de café; ela, de chá.',['Eu gosto de café e ela de chá, também.','Eu, gosto de café.','Gosto, de café e de chá.'],'A vírgula marca o verbo omitido "gosta": zeugma.'],['A diferença de sentido entre "Os alunos que estudaram passaram" e "Os alunos, que estudaram, passaram" é que:','na segunda, todos os alunos estudaram',['na primeira, todos os alunos estudaram','não há diferença','a segunda está errada'],'Sem vírgulas a oração <b>restringe</b> (só os que estudaram passaram); com vírgulas ela <b>explica</b> (todos estudaram).'],['"Não, quero sair." e "Não quero sair." diferem porque:','na primeira a pessoa quer sair',['as duas negam a vontade de sair','a segunda está errada','a vírgula não muda o sentido'],'A vírgula separa a resposta "Não" da afirmação "quero sair".']],
 tf:[['É correto usar vírgula entre o sujeito e o verbo: "O diretor, falou."',false,'Falso: não se separa sujeito e verbo com vírgula.'],['A vírgula antes de "mas" é recomendada.',true,'Verdadeiro: conjunção adversativa vem precedida de vírgula.'],['Dois-pontos podem introduzir uma enumeração.',true,'Verdadeiro: "Levei três coisas: caneta, lápis e borracha."']]})
]});

/* ------------------------ UNIDADE 2 — CLASSES DE PALAVRAS ------------------------ */
UNITS.push({id:'p2',title:'Classes de palavras',sub:'Substantivo, adjetivo, verbo, pronome, advérbio, preposição e conjunção',color:'#1cb0f6',dark:'#1899d6',skills:[
SKL('subst','Substantivo e adjetivo','🏷️','Substantivo nomeia seres; adjetivo caracteriza o substantivo. Coletivo é o substantivo que indica um conjunto.',
`<p><b>Substantivo</b> dá nome a seres, objetos, lugares, sentimentos e ações (<i>casa, Brasil, alegria</i>).</p>
<ul><li><b>Comum</b> × <b>próprio</b>: cidade × Recife.</li><li><b>Concreto</b> (existe por si: mesa, fada) × <b>abstrato</b> (depende de outro ser: amor, beleza, corrida).</li><li><b>Coletivo</b>: indica conjunto (<i>cardume, alcateia</i>).</li><li><b>Primitivo</b> × <b>derivado</b>: pedra × pedreiro; <b>simples</b> × <b>composto</b>: couve × couve-flor.</li></ul>
<p><b>Adjetivo</b> atribui qualidade ou estado ao substantivo (<i>casa <b>grande</b></i>). <b>Locução adjetiva</b>: expressão com valor de adjetivo (<i>amor <b>de mãe</b></i> = materno).</p>
<h3>Grau do adjetivo</h3><p>Comparativo (<i>mais alto que</i>) e superlativo: relativo (<i>o mais alto</i>) ou absoluto (<i>altíssimo, muito alto</i>). Formas eruditas: <i>facílimo, paupérrimo, dulcíssimo, amicíssimo</i>.</p>`,
{pairs:[['Alcateia','conjunto de lobos'],['Cardume','conjunto de peixes'],['Enxame','conjunto de abelhas'],['Matilha','conjunto de cães'],['Constelação','conjunto de estrelas'],['Arquipélago','conjunto de ilhas'],['Biblioteca','coleção de livros'],['Resma','conjunto de 500 folhas de papel'],['Elenco','conjunto de atores de uma peça ou filme'],['Pinacoteca','coleção de quadros'],['Cordilheira','conjunto de montanhas'],['Esquadrilha','conjunto de aviões'],['Vara','conjunto de porcos'],['Fauna','conjunto dos animais de uma região'],['Flora','conjunto dos vegetais de uma região']],tq:t=>`O coletivo <b>${t}</b> designa:`,dq:d=>`Qual é o coletivo de: <b>${d}</b>?`,
 qs:[['Qual palavra é um substantivo <b>abstrato</b>?','saudade',['cadeira','fada','Recife'],'Abstrato nomeia sentimentos, estados, ações e qualidades: <b>saudade</b>.'],['Em "amor de mãe", a locução "de mãe" equivale ao adjetivo:','materno',['maternal e paterno','fraterno','filial'],'"De mãe" = <b>materno</b> (de pai = paterno; de irmão = fraterno).'],['O superlativo absoluto sintético erudito de "fácil" é:','facílimo',['facilíssimo','mais fácil','muito fácil'],'Forma erudita: <b>facílimo</b> (difícil → dificílimo).'],['Em "O menino estava feliz", a palavra "feliz" é:','adjetivo',['substantivo','advérbio','verbo'],'Atribui um estado ao substantivo "menino": <b>adjetivo</b>.'],['Qual é o superlativo absoluto sintético erudito de "pobre"?','paupérrimo',['pobríssimo','pobrérrimo','muito pobre'],'Forma erudita: <b>paupérrimo</b> (a forma popular é pobríssimo).']]}),
SKL('verbo','Verbos: tempos e modos','⏱️','Tire a terminação -ar, -er, -ir e acrescente a desinência do tempo: -ava/-ia (imperfeito), -ei/-i (perfeito), -rei (futuro).',
`<p><b>Verbo</b> indica ação, estado ou fenômeno e varia em <b>pessoa, número, tempo e modo</b>.</p>
<ul><li><b>Indicativo</b>: certeza (<i>canto, cantei, cantarei</i>).</li><li><b>Subjuntivo</b>: dúvida, desejo, hipótese (<i>que eu cante, se eu cantasse, quando eu cantar</i>).</li><li><b>Imperativo</b>: ordem ou pedido (<i>cante!</i>).</li></ul>
<h3>Conjugações</h3><p>1ª (-ar: cantar), 2ª (-er: vender; <i>pôr</i> também pertence à 2ª), 3ª (-ir: partir).</p>
<table><tr><th>Tempo (eu / nós)</th><th>cantar</th><th>vender</th><th>partir</th></tr><tr><td>Presente</td><td>canto / cantamos</td><td>vendo / vendemos</td><td>parto / partimos</td></tr><tr><td>Pret. perfeito</td><td>cantei / cantamos</td><td>vendi / vendemos</td><td>parti / partimos</td></tr><tr><td>Pret. imperfeito</td><td>cantava / cantávamos</td><td>vendia / vendíamos</td><td>partia / partíamos</td></tr><tr><td>Futuro do presente</td><td>cantarei / cantaremos</td><td>venderei / venderemos</td><td>partirei / partiremos</td></tr><tr><td>Futuro do pretérito</td><td>cantaria / cantaríamos</td><td>venderia / venderíamos</td><td>partiria / partiríamos</td></tr></table>
<h3>Formas nominais</h3><p>Infinitivo (<i>cantar</i>), gerúndio (<i>cantando</i>) e particípio (<i>cantado</i>).</p>`,
{gens:conjGens,qs:[['Em "Se eu estudasse, passaria", os verbos estão, respectivamente, no:','pretérito imperfeito do subjuntivo e futuro do pretérito do indicativo',['presente do subjuntivo e futuro do presente','pretérito perfeito e presente','imperativo e infinitivo'],'"Estudasse": hipótese no <b>imperfeito do subjuntivo</b>; "passaria": consequência no <b>futuro do pretérito</b>.'],['Qual forma está no modo imperativo?','Feche a porta!',['Eu fecho a porta.','Se eu fechasse a porta…','Fechando a porta…'],'Ordem ou pedido: <b>imperativo</b>.'],['"Cantando" é uma forma nominal chamada:','gerúndio',['infinitivo','particípio','imperativo'],'Terminação -ndo: <b>gerúndio</b>.'],['O verbo "pôr" pertence à:','2ª conjugação',['1ª conjugação','3ª conjugação','nenhuma conjugação'],'"Pôr" vem do antigo "poer": pertence à <b>2ª conjugação</b>.']]}),
SKL('pronome','Pronomes','👉','Pronome substitui ou acompanha o nome. Este/esta = perto de quem fala; esse/essa = perto de quem ouve; aquele = longe dos dois.',
`<ul><li><b>Pessoais retos</b> (sujeito): eu, tu, ele, nós, vós, eles. <b>Oblíquos</b> (complemento): me, te, o, a, lhe, nos, vos, os, as, lhes; mim, ti, si, comigo…</li><li><b>Possessivos</b>: meu, teu, seu, nosso…</li><li><b>Demonstrativos</b>: este (perto de quem fala / o que vai ser dito), esse (perto de quem ouve / o que já foi dito), aquele (distante).</li><li><b>Relativos</b>: que, quem, o qual, cujo, onde — retomam um termo anterior. <i>Cujo</i> indica posse e não admite artigo depois: <i>o autor <b>cujo livro</b> li</i>.</li><li><b>Indefinidos</b>: alguém, ninguém, tudo, algum…; <b>interrogativos</b>: que, quem, qual, quanto.</li><li><b>Tratamento</b>: você, Vossa Excelência, Vossa Senhoria… (verbo na 3ª pessoa).</li></ul>
<h3>Uso culto</h3><p><i>Isto é <b>para eu</b> fazer</i> (eu é sujeito de "fazer"); <i>Isto é <b>para mim</b></i> (complemento). <i>Entre <b>mim</b> e você</i>. O pronome <b>o/a</b> é objeto direto (<i>Eu o vi</i>); <b>lhe</b> é objeto indireto (<i>Eu lhe disse</i>).</p>
<h3>Colocação pronominal</h3><p>Palavras atrativas (não, nunca, que, quem, advérbios, pronomes indefinidos) puxam o pronome para antes do verbo (<b>próclise</b>): <i>Não <b>me</b> diga.</i> Não se inicia frase com pronome oblíquo na norma culta: <i>Diga-<b>me</b></i> (ênclise).</p>`,
{qs:[['Qual frase está de acordo com a norma culta?','Este livro é para eu ler.',['Este livro é para mim ler.','Entre eu e você não há segredo.','Me empreste o lápis, por favor.'],'Antes de verbo no infinitivo, com função de sujeito, usa-se <b>eu</b>: "para eu ler".'],['Em "O escritor cujo livro li", o pronome "cujo" indica:','posse',['lugar','tempo','causa'],'<b>Cujo</b> é relativo com ideia de posse (o livro do escritor).'],['Qual frase segue a norma culta de colocação pronominal?','Não me disseram nada.',['Não disseram-me nada.','Me disseram nada.','Nada disseram-me.'],'"Não" é palavra atrativa: exige próclise.'],['"___ caneta que está aqui na minha mão é azul." Complete:','Esta',['Essa','Aquela','Esse'],'Perto de quem fala: <b>este/esta</b>.'],['Na frase "Eu o encontrei na rua", o pronome "o" exerce a função de:','objeto direto',['objeto indireto','sujeito','adjunto adverbial'],'Os pronomes o, a, os, as funcionam como <b>objeto direto</b>.'],['"Onde" deve ser usado para retomar:','lugar físico',['tempo','situação qualquer','pessoa'],'Na norma culta, <b>onde</b> refere-se a lugar: "A cidade onde nasci".']],
 pairs:[['Pronome pessoal reto','exerce a função de sujeito: eu, tu, ele, nós, vós, eles'],['Pronome oblíquo','exerce a função de complemento: me, te, o, lhe, mim, ti'],['Pronome possessivo','indica posse: meu, teu, seu, nosso'],['Pronome demonstrativo','situa no espaço, no tempo ou no texto: este, esse, aquele'],['Pronome relativo','retoma um termo anterior: que, quem, o qual, cujo, onde'],['Pronome indefinido','refere-se de modo vago: alguém, ninguém, tudo, algum']]}),
SKL('conect','Advérbio, preposição e conjunção','🔗','Conjunções têm valor de sentido: mas (oposição), pois (explicação), portanto (conclusão), embora (concessão), se (condição).',
`<p><b>Advérbio</b> modifica verbo, adjetivo ou outro advérbio, indicando circunstância: tempo (<i>ontem</i>), lugar (<i>aqui</i>), modo (<i>bem, rapidamente</i>), intensidade (<i>muito</i>), negação (<i>não</i>), dúvida (<i>talvez</i>).</p>
<p><b>Preposição</b> liga termos: a, ante, após, até, com, contra, de, desde, em, entre, para, perante, por, sem, sob, sobre, trás.</p>
<h3>Conjunções coordenativas</h3><ul><li><b>Aditivas</b>: e, nem, não só… mas também.</li><li><b>Adversativas</b>: mas, porém, contudo, todavia, entretanto, no entanto.</li><li><b>Alternativas</b>: ou… ou, ora… ora.</li><li><b>Conclusivas</b>: logo, portanto, por isso, pois (depois do verbo).</li><li><b>Explicativas</b>: porque, que, pois (antes do verbo).</li></ul>
<h3>Conjunções subordinativas</h3><p><b>Causais</b> (porque, como, já que), <b>concessivas</b> (embora, ainda que, mesmo que), <b>condicionais</b> (se, caso, desde que), <b>temporais</b> (quando, assim que), <b>finais</b> (para que, a fim de que), <b>consecutivas</b> (tão… que), <b>comparativas</b> (como, tal qual), <b>conformativas</b> (conforme, segundo), <b>proporcionais</b> (à medida que, à proporção que).</p>`,
{pairs:[['mas / porém / contudo','valor adversativo (oposição)'],['portanto / logo','valor conclusivo'],['embora / ainda que','valor concessivo'],['se / caso','valor condicional'],['quando / assim que','valor temporal'],['para que / a fim de que','valor final (finalidade)'],['conforme / segundo','valor conformativo'],['à medida que','valor proporcional'],['já que / visto que','valor causal'],['tão… que','valor consecutivo']],tq:t=>`A conjunção <b>${t}</b> tem:`,dq:d=>`Qual conjunção tem <b>${d}</b>?`,
 qs:[['Em "Estudou muito, <b>portanto</b> foi aprovado", a conjunção expressa:','conclusão',['oposição','concessão','condição'],'"Portanto" introduz uma <b>conclusão</b>.'],['"<b>Embora</b> chovesse, fomos à praia." A conjunção indica:','concessão',['causa','condição','finalidade'],'Um fato contrário que não impede o outro: <b>concessão</b>.'],['Em "Ele chegou <b>ontem</b>", a palavra destacada é advérbio de:','tempo',['lugar','modo','intensidade'],'"Ontem" indica <b>tempo</b>.'],['Qual conjunção pode substituir "mas" sem mudar o sentido em "Tentei, mas não consegui"?','porém',['portanto','porque','conforme'],'<b>Porém</b> também é adversativa.'],['Em "Venha logo, <b>pois</b> vai chover", "pois" é:','explicativa',['conclusiva','adversativa','concessiva'],'"Pois" antes do verbo e após pedido/ordem: <b>explicativa</b>.'],['Em "Ele fala <b>muito</b> bem", o advérbio "muito" modifica:','outro advérbio',['um verbo','um substantivo','um adjetivo'],'"Muito" intensifica o advérbio "bem".']]})
]});

/* ------------------------ UNIDADE 3 — SINTAXE ------------------------ */
UNITS.push({id:'p3',title:'Sintaxe',sub:'Sujeito, complementos, concordância, regência, crase e orações',color:'#ff9600',dark:'#e07b00',skills:[
SKL('sujeito','Sujeito e predicado','🎯','Pergunte ao verbo "quem?" ou "o quê?". Verbos de fenômeno da natureza e "haver" (= existir) formam orações sem sujeito.',
`<p><b>Sujeito</b> é o termo sobre o qual se declara algo; <b>predicado</b> é o que se declara sobre ele. O verbo concorda com o sujeito.</p>
<ul><li><b>Simples</b>: um núcleo (<i><b>Os alunos</b> saíram.</i>)</li><li><b>Composto</b>: dois ou mais núcleos (<i><b>Ana e Rui</b> saíram.</i>)</li><li><b>Oculto (desinencial)</b>: identificado pela terminação do verbo (<i>Saímos cedo.</i> → nós)</li><li><b>Indeterminado</b>: verbo na 3ª pessoa do plural sem referente (<i><b>Roubaram</b> meu carro.</i>) ou 3ª do singular + <b>se</b> com verbo que não é transitivo direto (<i><b>Precisa-se</b> de ajudantes.</i>)</li><li><b>Oração sem sujeito</b>: fenômenos da natureza (<i>Choveu.</i>), <b>haver</b> no sentido de existir ou tempo (<i>Há vagas.</i>), <b>fazer</b> indicando tempo (<i>Faz dez anos.</i>).</li></ul>
<div class="ex">"Vendem-se casas." → sujeito <b>casas</b> (voz passiva sintética: casas são vendidas), por isso o verbo vai ao plural.</div>`,
{qs:[['Em "Choveu muito ontem", o sujeito é:','inexistente (oração sem sujeito)',['oculto','indeterminado','"ontem"'],'Verbos que indicam fenômenos da natureza formam <b>oração sem sujeito</b>.'],['Em "Roubaram minha bicicleta", o sujeito é:','indeterminado',['oculto (eles)','"minha bicicleta"','inexistente'],'Verbo na 3ª pessoa do plural sem referente no texto: <b>indeterminado</b>.'],['Em "Chegamos cedo à escola", o sujeito é:','oculto (nós)',['indeterminado','"escola"','inexistente'],'A desinência -mos indica "nós": sujeito <b>oculto</b> (desinencial).'],['Em "Precisa-se de professores", o sujeito é:','indeterminado',['"professores"','oculto','simples'],'"Precisar" é transitivo indireto: com "se" indetermina o sujeito, e o verbo fica no singular.'],['Em "Vendem-se apartamentos", o sujeito é:','"apartamentos"',['indeterminado','oculto','inexistente'],'Voz passiva sintética: apartamentos são vendidos → sujeito <b>apartamentos</b>.'],['Em "Há muitos alunos na sala", o verbo "haver":','forma oração sem sujeito e fica no singular',['concorda com "alunos"','tem sujeito oculto','tem sujeito indeterminado'],'"Haver" no sentido de existir é impessoal: <b>Há</b> muitos alunos (nunca "hão").'],['Em "O pai e a mãe chegaram", o sujeito é:','composto',['simples','oculto','indeterminado'],'Dois núcleos (pai, mãe): <b>composto</b>.']],
 pairs:[['Sujeito simples','tem um único núcleo'],['Sujeito composto','tem dois ou mais núcleos'],['Sujeito oculto','não aparece, mas é identificado pela desinência do verbo'],['Sujeito indeterminado','existe, mas não se pode ou não se quer identificá-lo'],['Oração sem sujeito','formada por verbos impessoais, como fenômenos da natureza e "haver" (existir)']]}),
SKL('complem','Verbos e complementos','🧩','VTD pede complemento sem preposição (objeto direto); VTI pede com preposição (objeto indireto); verbo de ligação liga o sujeito a um predicativo.',
`<ul><li><b>Intransitivo</b>: tem sentido completo (<i>O bebê dormiu.</i>).</li><li><b>Transitivo direto (VTD)</b>: complemento sem preposição — <b>objeto direto</b> (<i>Comprei <b>pão</b>.</i>).</li><li><b>Transitivo indireto (VTI)</b>: complemento com preposição obrigatória — <b>objeto indireto</b> (<i>Gosto <b>de música</b>.</i>).</li><li><b>Transitivo direto e indireto</b>: os dois (<i>Dei <b>o livro</b> <b>ao aluno</b>.</i>).</li><li><b>De ligação</b>: ser, estar, parecer, permanecer, ficar, continuar, andar (= estar) + <b>predicativo do sujeito</b> (<i>Ela <b>está</b> cansada.</i>).</li></ul>
<h3>Tipos de predicado</h3><p><b>Verbal</b> (núcleo é verbo de ação), <b>nominal</b> (verbo de ligação + predicativo) e <b>verbo-nominal</b> (ação + predicativo: <i>Os alunos saíram <b>felizes</b>.</i>).</p>
<p><b>Agente da passiva</b>: quem pratica a ação na voz passiva (<i>O livro foi escrito <b>por Machado</b>.</i>).</p>`,
{qs:[['Em "Ela entregou o relatório ao chefe", "o relatório" e "ao chefe" são, respectivamente:','objeto direto e objeto indireto',['objeto indireto e objeto direto','sujeito e predicativo','adjunto adnominal e adjunto adverbial'],'Entregar algo (OD) a alguém (OI): verbo transitivo direto e indireto.'],['Em "O menino parece cansado", "cansado" é:','predicativo do sujeito',['objeto direto','adjunto adnominal','agente da passiva'],'"Parecer" é verbo de ligação: "cansado" é <b>predicativo do sujeito</b>.'],['Em "Gosto de chocolate", o verbo é:','transitivo indireto',['transitivo direto','intransitivo','de ligação'],'Quem gosta, gosta <b>de</b> algo: exige preposição.'],['Em "A casa foi construída pelos operários", "pelos operários" é:','agente da passiva',['objeto indireto','sujeito','adjunto adnominal'],'Voz passiva analítica: quem pratica a ação é o <b>agente da passiva</b>.'],['Em "O avião caiu", o verbo é:','intransitivo',['transitivo direto','transitivo indireto','de ligação'],'Sentido completo, sem complemento: <b>intransitivo</b>.'],['Qual predicado é verbo-nominal?','Os jogadores voltaram cansados.',['Os jogadores estão cansados.','Os jogadores voltaram.','Os jogadores venceram o jogo.'],'Há ação (voltaram) e estado do sujeito (cansados): <b>verbo-nominal</b>.']],
 pairs:[['Verbo intransitivo','não precisa de complemento'],['Verbo transitivo direto','exige complemento sem preposição'],['Verbo transitivo indireto','exige complemento com preposição'],['Verbo de ligação','liga o sujeito a uma característica (predicativo)'],['Predicativo do sujeito','característica atribuída ao sujeito por meio do verbo'],['Agente da passiva','quem pratica a ação na voz passiva, introduzido por "por"']]}),
SKL('acess','Termos acessórios e vocativo','📌','Adjunto adnominal acompanha o nome; adjunto adverbial indica circunstância; aposto explica um termo; vocativo chama o interlocutor.',
`<ul><li><b>Adjunto adnominal</b>: acompanha e caracteriza o substantivo — artigos, adjetivos, pronomes, numerais, locuções (<i><b>Os dois</b> livros <b>antigos</b> <b>de meu avô</b></i>).</li><li><b>Adjunto adverbial</b>: indica circunstância de tempo, lugar, modo, causa… (<i>Saí <b>cedo</b> <b>de casa</b>.</i>).</li><li><b>Aposto</b>: explica ou resume um termo, geralmente entre vírgulas (<i>Machado, <b>o Bruxo do Cosme Velho</b>, …</i>).</li><li><b>Vocativo</b>: chama o interlocutor e não faz parte nem do sujeito nem do predicado (<i><b>Professor</b>, posso sair?</i>).</li></ul>
<div class="ex">Complemento nominal × adjunto adnominal: em "a crítica <b>do professor</b>", se o professor critica, é adjunto (agente); em "a crítica <b>ao professor</b>", ele é criticado: complemento nominal (paciente).</div>`,
{qs:[['Em "Amanhã, eu viajarei de ônibus", "amanhã" e "de ônibus" são:','adjuntos adverbiais de tempo e de meio',['adjuntos adnominais','objetos indiretos','apostos'],'Indicam circunstâncias (tempo e meio): <b>adjuntos adverbiais</b>.'],['Em "Senhores, a sessão está aberta", "Senhores" é:','vocativo',['sujeito','aposto','adjunto adnominal'],'Termo usado para chamar os ouvintes: <b>vocativo</b>.'],['Em "Recife, a capital pernambucana, é linda", o termo destacado entre vírgulas é:','aposto',['vocativo','predicativo','adjunto adverbial'],'Explica "Recife": <b>aposto</b>.'],['Em "O velho relógio da sala parou", "velho" e "da sala" são:','adjuntos adnominais',['adjuntos adverbiais','complementos nominais','predicativos'],'Caracterizam o substantivo "relógio": <b>adjuntos adnominais</b>.'],['Em "Tenho medo <b>de altura</b>", o termo destacado é:','complemento nominal',['adjunto adnominal','objeto indireto','agente da passiva'],'Completa o sentido do nome "medo" (medo de quê?): <b>complemento nominal</b>.']]}),
SKL('concord','Concordância','🤝','O verbo concorda com o sujeito; "haver" (existir) fica no singular; o adjetivo concorda com o substantivo.',
`<h3>Concordância verbal</h3><ul><li>O verbo concorda com o núcleo do sujeito: <i>A lista de nomes <b>foi</b> entregue.</i></li><li>Sujeito composto antes do verbo → plural: <i>Pai e filho <b>chegaram</b>.</i></li><li><b>Haver</b> = existir e <b>fazer</b> = tempo ficam no singular: <i><b>Havia</b> muitas pessoas. <b>Faz</b> dois anos.</i></li><li>Voz passiva sintética concorda: <i><b>Alugam-se</b> casas.</i></li><li>"Mais de um" pede singular: <i>Mais de um aluno <b>faltou</b>.</i></li><li>Porcentagem concorda com o numeral ou com o termo especificado: <i>30% dos alunos <b>faltaram</b>.</i></li></ul>
<h3>Concordância nominal</h3><ul><li>O adjetivo concorda com o substantivo: <i>blusas <b>caras</b></i>.</li><li><b>Meio</b> (advérbio = um pouco) é invariável: <i>Ela está <b>meio</b> cansada.</i> Como numeral varia: <i>meia hora</i>.</li><li><b>Bastante</b> concorda quando é adjetivo: <i><b>bastantes</b> livros</i> (= muitos).</li><li><b>Anexo, obrigado, mesmo, próprio, quite</b> concordam: <i>Seguem <b>anexas</b> as fotos. — <b>Obrigada</b>, disse ela.</i></li><li><b>É proibido, é necessário</b>: invariáveis sem artigo (<i>É proibido entrada</i>), variáveis com artigo (<i>É proibida <b>a</b> entrada</i>).</li></ul>`,
{bank:[['@@ muitas pessoas na fila.','Havia',['Haviam','Houveram','Hão'],'"Haver" = existir é impessoal: <b>Havia</b>.'],['@@ dez anos que não o vejo.','Faz',['Fazem','Fizeram','Fazemos'],'"Fazer" indicando tempo é impessoal: <b>Faz</b>.'],['@@ apartamentos na praia.','Vendem-se',['Vende-se','Vendeu-se','Vende-os'],'Voz passiva sintética: apartamentos são vendidos → <b>Vendem-se</b>.'],['Ela ficou @@ nervosa com a prova.','meio',['meia','meios','meias'],'Advérbio (= um pouco): <b>meio</b>, invariável.'],['Seguem @@ as notas fiscais.','anexas',['anexo','anexa','anexos'],'"Anexo" concorda com o substantivo: notas → <b>anexas</b>.'],['"Muito @@", disse a menina.','obrigada',['obrigado','obrigados','obrigadas'],'Concorda com quem fala: a menina → <b>obrigada</b>.'],['Mais de um aluno @@ a aula.','perdeu',['perderam','perdemos','perdi'],'"Mais de um" pede verbo no singular.'],['É @@ a entrada de animais.','proibida',['proibido','proibidas','proibidos'],'Com artigo ("a entrada"), concorda: <b>proibida</b>.'],['Os meninos e a menina @@ juntos.','saíram',['saiu','sai','saía'],'Sujeito composto anteposto: plural.']]}),
SKL('crase','Regência e crase','🔀','Crase = preposição "a" + artigo "a". Troque a palavra feminina por uma masculina: se virar "ao", há crase.',
`<h3>Regência</h3><p>É a relação entre um termo e seu complemento. Exemplos da norma culta:</p><ul><li><b>Assistir</b> (ver) é VTI: <i>assisti <b>ao</b> filme</i>. (Assistir = ajudar é VTD.)</li><li><b>Visar</b> (ter como objetivo) é VTI: <i>visa <b>ao</b> lucro</i>.</li><li><b>Obedecer / desobedecer</b> a: <i>obedeça <b>às</b> regras</i>.</li><li><b>Preferir</b> algo <b>a</b> outra coisa (sem "do que" e sem "mais"): <i>prefiro cinema <b>a</b> teatro</i>.</li><li><b>Ir, chegar</b> a um lugar (não "em"): <i>chegou <b>à</b> escola</i>.</li><li><b>Namorar</b> é VTD: <i>namora Pedro</i> (não "com").</li></ul>
<h3>Crase</h3><p>Fusão da preposição <b>a</b> com o artigo <b>a</b> (ou com "aquele", "aquela"). <b>Truque</b>: troque por uma palavra masculina — se aparecer <b>ao</b>, use <b>à</b>. <i>Vou <b>à</b> escola</i> (vou ao colégio).</p>
<ul><li><b>Não há crase</b> antes de palavra masculina, verbo, pronomes pessoais e de tratamento (<i>a ela, a Vossa Senhoria</i>), "a" no singular antes de plural (<i>a pessoas</i>) e entre palavras repetidas (<i>cara a cara</i>).</li><li><b>Há crase</b> em locuções adverbiais femininas (<i>às vezes, à noite, às pressas</i>) e na indicação de horas (<i>às 8h</i>).</li><li>Cidades: "vou a Recife, volto <b>de</b> Recife" → sem crase; "vou <b>à</b> Bahia, volto <b>da</b> Bahia" → com crase.</li></ul>`,
{bank:[['Vou @@ farmácia comprar remédio.','à',['a','há','ah'],'Vou ao mercado → vou <b>à</b> farmácia.'],['Começou @@ chover.','a',['à','há','ah'],'Antes de verbo não há crase.'],['A reunião será @@ 14h.','às',['as','a','há'],'Indicação de horas: <b>às</b> 14h.'],['Entreguei o livro @@ ela.','a',['à','há','às'],'Antes de pronome pessoal não há crase.'],['Assisti @@ filme ontem.','ao',['o','do','no'],'Assistir (ver) é VTI: assisti <b>ao</b> filme.'],['Prefiro sorvete @@ bolo.','a',['do que','que','à'],'Preferir algo <b>a</b> outra coisa.'],['Vou @@ Bahia nas férias.','à',['a','há','as'],'Volto da Bahia → vou <b>à</b> Bahia.'],['Vou @@ Curitiba amanhã.','a',['à','há','às'],'Volto de Curitiba → vou <b>a</b> Curitiba (sem crase).'],['Estudo @@ noite.','à',['a','há','na'],'Locução adverbial feminina: <b>à</b> noite.'],['Fiquei frente @@ frente com ele.','a',['à','há','às'],'Entre palavras repetidas não há crase.'],['Os alunos obedecem @@ regras.','às',['as','a','das'],'Obedecer <b>a</b> + as regras = <b>às</b> regras.'],['Ele chegou @@ escola atrasado.','à',['na','a','há'],'Chegar <b>a</b> um lugar: chegou à escola.']]}),
SKL('oracoes','Orações coordenadas e subordinadas','🧱','Coordenadas são independentes (ligadas por e, mas, ou, logo, pois); subordinadas dependem de uma oração principal.',
`<p><b>Período composto por coordenação</b>: orações sintaticamente independentes. <b>Assindéticas</b> (sem conjunção: <i>Cheguei, vi, venci.</i>) ou <b>sindéticas</b> (aditivas, adversativas, alternativas, conclusivas, explicativas).</p>
<p><b>Período composto por subordinação</b>: uma oração exerce função sintática na principal.</p><ul><li><b>Substantivas</b> (função de substantivo; geralmente introduzidas por <i>que</i> ou <i>se</i>): <i>Espero <b>que você venha</b></i> (objetiva direta).</li><li><b>Adjetivas</b> (introduzidas por pronome relativo): <b>restritivas</b> (sem vírgula) e <b>explicativas</b> (com vírgula).</li><li><b>Adverbiais</b>: causais, concessivas, condicionais, temporais, finais, consecutivas, comparativas, conformativas, proporcionais.</li></ul>
<div class="ex">"Saí cedo <b>porque tinha prova</b>" → adverbial causal. "O livro <b>que comprei</b> é ótimo" → adjetiva restritiva.</div>`,
{qs:[['"Estudei muito, mas não passei." A segunda oração é:','coordenada sindética adversativa',['subordinada adverbial concessiva','coordenada assindética','subordinada substantiva'],'"Mas" liga orações independentes com oposição.'],['"É importante que você estude." A oração destacada ("que você estude") é:','subordinada substantiva subjetiva',['subordinada adjetiva','coordenada explicativa','subordinada adverbial final'],'Funciona como sujeito de "é importante": <b>substantiva subjetiva</b>.'],['"O aluno que estudou foi aprovado." A oração "que estudou" é:','subordinada adjetiva restritiva',['subordinada adjetiva explicativa','coordenada aditiva','subordinada substantiva'],'Introduzida por pronome relativo, sem vírgulas: <b>adjetiva restritiva</b>.'],['"Se chover, o jogo será adiado." A oração "Se chover" é adverbial:','condicional',['causal','concessiva','temporal'],'"Se" expressa <b>condição</b>.'],['"Vim, vi, venci." As orações são:','coordenadas assindéticas',['coordenadas sindéticas aditivas','subordinadas adverbiais','subordinadas adjetivas'],'Sem conjunção: <b>assindéticas</b>.'],['"Falou tão alto que ficou rouco." A oração "que ficou rouco" é adverbial:','consecutiva',['causal','final','comparativa'],'"Tão… que": <b>consecutiva</b> (consequência).'],['"Estudo para que eu seja aprovado." A oração destacada é adverbial:','final',['causal','condicional','conformativa'],'"Para que" indica <b>finalidade</b>.']]})
]});

/* ------------------------ UNIDADE 4 — SENTIDO E TEXTO ------------------------ */
UNITS.push({id:'p4',title:'Sentido e texto',sub:'Figuras de linguagem, funções da linguagem, gêneros, variação e coesão',color:'#ff4b4b',dark:'#ea2b2b',skills:[
SKL('figuras','Figuras de linguagem','🎭','Metáfora compara sem "como"; comparação usa "como"; metonímia troca um termo por outro com relação de proximidade (autor pela obra, parte pelo todo).',
`<h3>Figuras de palavra</h3><ul><li><b>Metáfora</b>: comparação implícita (<i>Meu coração é um balde despejado</i>).</li><li><b>Comparação (símile)</b>: com conectivo (<i>forte <b>como</b> um touro</i>).</li><li><b>Metonímia</b>: troca por proximidade — autor pela obra (<i>li Machado</i>), parte pelo todo (<i>não há teto para ele</i>), marca pelo produto (<i>tomei um Nescau</i>).</li><li><b>Catacrese</b>: metáfora já desgastada, por falta de termo próprio (<i>pé da mesa</i>).</li><li><b>Sinestesia</b>: mistura de sentidos (<i>voz <b>doce</b></i>, <i>cor <b>gritante</b></i>).</li></ul>
<h3>Figuras de pensamento</h3><ul><li><b>Hipérbole</b>: exagero (<i>chorei rios de lágrimas</i>).</li><li><b>Eufemismo</b>: suaviza (<i>ele partiu desta para melhor</i>).</li><li><b>Ironia</b>: diz o contrário do que pensa (<i>Que belo resultado: tirou zero!</i>).</li><li><b>Antítese</b>: ideias opostas (<i>alegria e tristeza</i>). <b>Paradoxo</b>: ideias opostas que parecem absurdas juntas (<i>"é dor que desatina sem doer"</i>).</li><li><b>Prosopopeia (personificação)</b>: ações humanas a seres inanimados (<i>o vento sussurrava</i>).</li><li><b>Gradação</b>: sequência crescente ou decrescente.</li></ul>
<h3>Figuras de som e de sintaxe</h3><p><b>Aliteração</b> (repetição de consoantes: <i>"o rato roeu a roupa do rei de Roma"</i>), <b>assonância</b> (repetição de vogais), <b>onomatopeia</b> (imita sons: <i>tic-tac</i>), <b>elipse</b> (omissão de termo fácil de subentender), <b>pleonasmo</b> (repetição enfática), <b>anáfora</b> (repetição no início de versos ou frases).</p>`,
{pairs:[['"Meu coração é um balde despejado."','metáfora'],['"Ele é forte como um touro."','comparação'],['"Li Machado de Assis nas férias."','metonímia'],['"Já te disse isso um milhão de vezes."','hipérbole'],['"Ele passou desta para melhor."','eufemismo'],['"Que bonito, hein? Tirou zero de novo!"','ironia'],['"O vento sussurrava segredos à janela."','prosopopeia'],['"Amor é fogo que arde sem se ver."','paradoxo'],['"Ouvi uma voz macia e doce."','sinestesia'],['"O pé da mesa quebrou."','catacrese'],['"O rato roeu a roupa do rei de Roma."','aliteração'],['"O tique-taque do relógio me acordou."','onomatopeia']],tq:t=>`Qual figura de linguagem aparece em <b>${t}</b>?`,dq:d=>`Qual frase exemplifica <b>${d}</b>?`,noTF:true,
 tf:[['A metáfora é uma comparação sem conectivo comparativo.',true,'Verdadeiro.'],['Na metonímia, há exagero intencional.',false,'Falso: exagero é hipérbole; metonímia é substituição por proximidade.'],['"Pé da mesa" é catacrese.',true,'Verdadeiro: metáfora cristalizada por falta de termo próprio.'],['Antítese e paradoxo são a mesma figura.',false,'Falso: na antítese as ideias opostas convivem; no paradoxo elas se fundem num sentido aparentemente absurdo.']]}),
SKL('funcoes','Funções da linguagem','📡','Emotiva (emissor), apelativa (receptor), referencial (contexto), metalinguística (código), poética (mensagem), fática (canal).',
`<p>Roman Jakobson relacionou cada elemento da comunicação a uma função:</p>
<table><tr><th>Elemento</th><th>Função</th><th>Exemplo</th></tr><tr><td>Emissor</td><td><b>Emotiva (expressiva)</b></td><td>diários, cartas pessoais, 1ª pessoa</td></tr><tr><td>Receptor</td><td><b>Apelativa (conativa)</b></td><td>propagandas, imperativo, vocativo</td></tr><tr><td>Referente/contexto</td><td><b>Referencial (denotativa)</b></td><td>notícias, textos científicos</td></tr><tr><td>Código</td><td><b>Metalinguística</b></td><td>dicionários, poema sobre fazer poemas</td></tr><tr><td>Mensagem</td><td><b>Poética</b></td><td>poemas, slogans com rimas e ritmo</td></tr><tr><td>Canal</td><td><b>Fática</b></td><td>"Alô?", "Tá me ouvindo?", "Né?"</td></tr></table>
<p>Um texto costuma ter várias funções, mas uma é <b>predominante</b>.</p>`,
{pairs:[['Função emotiva','centrada no emissor, expressa sentimentos e opiniões em 1ª pessoa'],['Função apelativa','centrada no receptor, tenta convencê-lo ou levá-lo a agir'],['Função referencial','centrada no contexto, informa de modo objetivo'],['Função metalinguística','usa o código para falar do próprio código'],['Função poética','centrada na elaboração da mensagem: ritmo, sonoridade, imagens'],['Função fática','centrada no canal: testa ou mantém o contato']],
 qs:[['Um verbete de dicionário apresenta predominantemente a função:','metalinguística',['emotiva','fática','apelativa'],'Explica palavras usando palavras: <b>metalinguística</b>.'],['Uma propaganda com "Compre já! Você merece!" tem predominância da função:','apelativa',['referencial','poética','fática'],'Centrada no receptor, com imperativo: <b>apelativa</b>.'],['Uma notícia de jornal sobre a alta dos preços tem predominância da função:','referencial',['emotiva','metalinguística','fática'],'Informação objetiva: <b>referencial</b>.'],['"Alô? Está me ouvindo?" exemplifica a função:','fática',['poética','apelativa','emotiva'],'Testa o canal de comunicação: <b>fática</b>.'],['Um poema que discute como se escreve um poema tem forte presença da função:','metalinguística',['referencial','fática','apelativa'],'O poema fala do próprio código (a poesia): <b>metalinguística</b>.']]}),
SKL('generos','Tipos e gêneros textuais','📰','Tipos são poucos (narrar, descrever, dissertar, expor, injuntar); gêneros são muitos (notícia, crônica, receita, editorial…).',
`<p><b>Tipos textuais</b> são modos de organização: <b>narrativo</b> (fatos no tempo, personagens), <b>descritivo</b> (características), <b>dissertativo-argumentativo</b> (defende tese com argumentos), <b>expositivo</b> (explica), <b>injuntivo</b> (instrui, com imperativo).</p>
<p><b>Gêneros textuais</b> são textos concretos do dia a dia, definidos por função social, estrutura e suporte:</p><ul><li><b>Notícia</b>: relata fato recente, linguagem objetiva, lide (o quê, quem, quando, onde, como, por quê).</li><li><b>Reportagem</b>: aprofunda um tema com dados e entrevistas.</li><li><b>Editorial</b>: opinião do veículo, sem assinatura.</li><li><b>Artigo de opinião</b>: opinião assinada.</li><li><b>Crônica</b>: fato do cotidiano com olhar pessoal, muitas vezes humor ou lirismo.</li><li><b>Conto</b>: narrativa curta com poucos personagens e um conflito.</li><li><b>Receita, manual</b>: injuntivos. <b>Charge</b>: humor crítico sobre fato atual.</li></ul>
<h3>Redação do ENEM</h3><p>Texto <b>dissertativo-argumentativo</b> com tese, argumentos e <b>proposta de intervenção</b> detalhada (agente, ação, meio, finalidade, detalhamento), respeitando os direitos humanos.</p>`,
{pairs:[['Notícia','relata um fato recente de forma objetiva'],['Editorial','expressa a opinião do próprio jornal, sem assinatura'],['Crônica','comenta o cotidiano com olhar pessoal, muitas vezes com humor'],['Receita culinária','gênero injuntivo, com instruções no imperativo'],['Charge','critica com humor um fato atual, por meio de desenho'],['Artigo de opinião','defende o ponto de vista de um autor que o assina'],['Conto','narrativa curta com poucos personagens e um conflito central'],['Reportagem','aprofunda um tema com dados, pesquisa e entrevistas']],tq:t=>`O gênero <b>${t}</b>:`,dq:d=>`Qual gênero textual <b>${d}</b>?`,
 qs:[['A redação do ENEM exige um texto do tipo:','dissertativo-argumentativo',['narrativo','descritivo','injuntivo'],'Tese + argumentos + proposta de intervenção.'],['Um manual de instruções é predominantemente:','injuntivo',['narrativo','descritivo','argumentativo'],'Instrui o leitor, com verbos no imperativo: <b>injuntivo</b>.'],['Qual elemento é obrigatório na proposta de intervenção da redação do ENEM, segundo a matriz de correção?','agente, ação, meio, finalidade e detalhamento',['citação de autor famoso','título','rima'],'A proposta de intervenção completa tem <b>agente, ação, meio/modo, finalidade e detalhamento</b>, respeitando os direitos humanos.']]}),
SKL('variacao','Variação linguística','🗣️','Não existe "erro" na fala espontânea, e sim adequação: cada situação pede uma variedade. A norma-padrão é a exigida em contextos formais.',
`<p>A língua varia conforme:</p><ul><li><b>Região (diatópica)</b>: "mandioca, aipim, macaxeira"; sotaques.</li><li><b>Grupo social (diastrática)</b>: idade, escolaridade, profissão (jargões), gírias.</li><li><b>Situação (diafásica)</b>: formal × informal.</li><li><b>Tempo (diacrônica)</b>: "Vossa Mercê → vosmecê → você".</li><li><b>Modalidade (diamésica)</b>: fala × escrita.</li></ul>
<p><b>Preconceito linguístico</b> é discriminar alguém pela forma como fala. O conceito-chave é a <b>adequação</b>: a norma-padrão é adequada a situações formais, e as variedades informais, às cotidianas.</p>`,
{pairs:[['Variação regional (diatópica)','diferenças de acordo com o lugar, como "mandioca", "aipim" e "macaxeira"'],['Variação social (diastrática)','diferenças ligadas a grupo social, idade ou profissão'],['Variação situacional (diafásica)','ajuste ao grau de formalidade da situação'],['Variação histórica (diacrônica)','mudanças da língua ao longo do tempo'],['Jargão','vocabulário próprio de uma profissão ou área'],['Preconceito linguístico','discriminação de pessoas pelo modo como falam']],
 qs:[['"Vossa mercê" se transformou em "você" ao longo dos séculos. Isso é um exemplo de variação:','histórica',['regional','social','situacional'],'Mudança ao longo do tempo: <b>diacrônica</b>.'],['Segundo a Linguística, a forma mais adequada de avaliar a fala de alguém é pelo critério de:','adequação à situação comunicativa',['certo e errado absolutos','quantidade de palavras difíceis','sotaque da capital'],'Não há variedade superior; há <b>adequação</b> ao contexto.'],['O vocabulário técnico de médicos ("anamnese", "profilaxia") é chamado de:','jargão',['gíria regional','arcaísmo','neologismo'],'<b>Jargão</b>: linguagem própria de um grupo profissional.']]}),
SKL('coesao','Coesão e coerência','🧵','Coesão é a ligação entre as partes do texto (pronomes, sinônimos, conectivos); coerência é o sentido lógico do todo.',
`<p><b>Coesão</b>: mecanismos que ligam palavras, frases e parágrafos.</p><ul><li><b>Referencial</b>: retomar termos com pronomes, sinônimos, hiperônimos, elipse (<i>Maria chegou. <b>Ela</b> estava cansada.</i>). <b>Anáfora</b> retoma o que já foi dito; <b>catáfora</b> antecipa o que vai ser dito.</li><li><b>Sequencial</b>: conectivos que expressam relações lógicas (<i>além disso, no entanto, portanto, porque</i>).</li></ul>
<p><b>Coerência</b>: o texto faz sentido, sem contradições, com informações compatíveis com o mundo e com o próprio texto.</p>
<div class="ex">"Choveu muito, <b>portanto</b> a rua ficou seca." → conectivo coeso, mas o texto é <b>incoerente</b>.</div>`,
{qs:[['Em "João comprou um carro. <b>O veículo</b> é azul.", o termo destacado é um recurso de:','coesão referencial',['coesão sequencial','incoerência','ambiguidade'],'Retoma "carro" com um hiperônimo: <b>coesão referencial</b>.'],['Qual conectivo expressa ideia de <b>adição</b>?','além disso',['no entanto','portanto','embora'],'<b>Além disso</b> acrescenta informação.'],['"Estava com fome, portanto não comeu nada." O problema dessa frase é de:','coerência',['ortografia','concordância','acentuação'],'"Portanto" anuncia uma conclusão que contradiz a causa: falta <b>coerência</b>.'],['Em "Só quero isto: <b>paz</b>", o pronome "isto" antecipa o termo "paz". Esse recurso é a:','catáfora',['anáfora','elipse','hipérbole'],'Pronome que se refere ao que <b>vem depois</b>: catáfora.'],['Qual conectivo pode substituir "no entanto" sem alterar o sentido?','contudo',['portanto','porque','além disso'],'Ambos são <b>adversativos</b>.']],
 pairs:[['Anáfora (coesão)','retomada de um termo que já apareceu no texto'],['Catáfora','antecipação de um termo que ainda vai aparecer'],['Elipse','omissão de um termo que se subentende pelo contexto'],['Hiperônimo','palavra de sentido mais geral que retoma outra, como "veículo" para "carro"'],['Coerência','unidade de sentido e lógica do texto'],['Coesão sequencial','encadeamento de ideias por meio de conectivos']]})
]});

/* ------------------------ UNIDADE 5 — LITERATURA ------------------------ */
UNITS.push({id:'p5',title:'Literatura brasileira',sub:'Do Quinhentismo ao Modernismo: escolas, autores e obras',color:'#2b70c9',dark:'#1f569e',skills:[
SKL('lit1','Quinhentismo, Barroco e Arcadismo','⛵','Quinhentismo: textos de informação e catequese; Barroco: conflito e rebuscamento; Arcadismo: simplicidade, bucolismo e razão.',
`<ul><li><b>Quinhentismo (séc. XVI)</b>: literatura de informação (<i>Carta</i> de Pero Vaz de Caminha, 1500) e de catequese (padre <b>José de Anchieta</b>).</li><li><b>Barroco (séc. XVII)</b>: tensão entre fé e prazer, efemeridade da vida, antíteses e paradoxos; <b>cultismo</b> (jogo de palavras) e <b>conceptismo</b> (jogo de ideias). <b>Gregório de Matos</b>, o "Boca do Inferno" (poesia satírica, lírica e religiosa); <b>Padre Antônio Vieira</b> (<i>Sermões</i>, como o <i>Sermão da Sexagésima</i>).</li><li><b>Arcadismo (séc. XVIII)</b>: reação ao Barroco; simplicidade, vida no campo (<i>fugere urbem</i>, <i>locus amoenus</i>), pastores, <i>carpe diem</i>; ligação com a Inconfidência Mineira. <b>Tomás Antônio Gonzaga</b> (<i>Marília de Dirceu</i>, <i>Cartas Chilenas</i>), <b>Cláudio Manuel da Costa</b>, <b>Basílio da Gama</b> (<i>O Uraguai</i>), <b>Santa Rita Durão</b> (<i>Caramuru</i>).</li></ul>`,
{pairs:[['Pero Vaz de Caminha','autor da Carta que relata a chegada dos portugueses ao Brasil (Quinhentismo)'],['José de Anchieta','jesuíta da literatura de catequese (Quinhentismo)'],['Gregório de Matos','poeta barroco satírico, apelidado de "Boca do Inferno"'],['Padre Antônio Vieira','autor barroco dos Sermões, como o Sermão da Sexagésima'],['Tomás Antônio Gonzaga','poeta árcade autor de Marília de Dirceu'],['Basílio da Gama','autor árcade do poema épico O Uraguai'],['Santa Rita Durão','autor árcade do poema épico Caramuru']],
 qs:[['Uma característica do Barroco é:','o uso de antíteses e paradoxos, expressando conflito entre fé e prazer',['a exaltação do indígena como herói nacional','a busca da "arte pela arte"','o verso livre e a linguagem coloquial'],'O Barroco expressa o conflito espiritual com antíteses e paradoxos.'],['"Fugere urbem" (fugir da cidade) e "locus amoenus" (lugar ameno) são ideais do:','Arcadismo',['Barroco','Romantismo','Modernismo'],'Ideais <b>árcades</b> de vida simples no campo.'],['O Arcadismo mineiro está ligado a qual movimento histórico?','Inconfidência Mineira',['Revolução Farroupilha','Proclamação da República','Semana de Arte Moderna'],'Poetas como Gonzaga e Cláudio Manuel da Costa participaram da <b>Inconfidência Mineira</b>.']]}),
SKL('lit2','Romantismo','🌹','Três gerações de poesia: indianista/nacionalista (Gonçalves Dias), ultrarromântica (Álvares de Azevedo) e condoreira (Castro Alves).',
`<p>Início no Brasil: <i>Suspiros Poéticos e Saudades</i> (1836), de Gonçalves de Magalhães. Valoriza o <b>sentimento</b>, o <b>nacionalismo</b>, o <b>subjetivismo</b>, a idealização da mulher e da natureza.</p>
<ul><li><b>1ª geração (indianista/nacionalista)</b>: <b>Gonçalves Dias</b> — "Canção do Exílio" ("Minha terra tem palmeiras…"), "I-Juca-Pirama".</li><li><b>2ª geração (ultrarromântica, "mal do século")</b>: pessimismo, morte, amor impossível — <b>Álvares de Azevedo</b> (<i>Lira dos Vinte Anos</i>, <i>Noite na Taverna</i>), <b>Casimiro de Abreu</b> ("Meus oito anos"), <b>Fagundes Varela</b>.</li><li><b>3ª geração (condoreira/social)</b>: abolicionismo e crítica social — <b>Castro Alves</b>, o "poeta dos escravos" (<i>O Navio Negreiro</i>).</li></ul>
<h3>Prosa</h3><p><b>José de Alencar</b>: indianistas (<i>Iracema</i>, <i>O Guarani</i>, <i>Ubirajara</i>), urbanos (<i>Senhora</i>, <i>Lucíola</i>) e regionalistas (<i>O Sertanejo</i>). <b>Joaquim Manuel de Macedo</b> (<i>A Moreninha</i>, 1844), <b>Manuel Antônio de Almeida</b> (<i>Memórias de um Sargento de Milícias</i>), <b>Bernardo Guimarães</b> (<i>A Escrava Isaura</i>), <b>Visconde de Taunay</b> (<i>Inocência</i>).</p>`,
{pairs:[['Gonçalves Dias','poeta da 1ª geração romântica, autor da "Canção do Exílio"'],['Álvares de Azevedo','poeta ultrarromântico, autor de Lira dos Vinte Anos'],['Castro Alves','poeta condoreiro, autor de O Navio Negreiro'],['José de Alencar','romancista de Iracema, O Guarani e Senhora'],['Joaquim Manuel de Macedo','autor de A Moreninha (1844)'],['Bernardo Guimarães','autor de A Escrava Isaura'],['Manuel Antônio de Almeida','autor de Memórias de um Sargento de Milícias']],
 qs:[['A 2ª geração romântica, marcada pelo pessimismo, pela morte e pelo "mal do século", tem como principal nome:','Álvares de Azevedo',['Castro Alves','Gonçalves Dias','Olavo Bilac'],'<b>Álvares de Azevedo</b> é o maior nome do ultrarromantismo.'],['"Minha terra tem palmeiras / Onde canta o Sabiá" é de:','Gonçalves Dias',['Castro Alves','Casimiro de Abreu','Carlos Drummond de Andrade'],'"Canção do Exílio" (1843), de <b>Gonçalves Dias</b>.'],['A poesia condoreira de Castro Alves caracteriza-se:','pela crítica social e pelo abolicionismo',['pelo indianismo idealizado','pela obsessão com a morte','pela arte pela arte'],'Poesia social, com o "voo do condor": abolicionismo.'],['Iracema, "a virgem dos lábios de mel", é personagem de um romance:','indianista de José de Alencar',['urbano de Machado de Assis','naturalista de Aluísio Azevedo','modernista de Mário de Andrade'],'<i>Iracema</i> (1865), romance <b>indianista</b> de Alencar.']]}),
SKL('lit3','Realismo, Naturalismo, Parnasianismo e Simbolismo','🔍','Realismo: análise psicológica e crítica (Machado); Naturalismo: determinismo (Aluísio Azevedo); Parnasianismo: arte pela arte (Bilac); Simbolismo: musicalidade e mistério (Cruz e Sousa).',
`<ul><li><b>Realismo (1881)</b>: objetividade, crítica à burguesia, análise psicológica, ironia. Marco: <i>Memórias Póstumas de Brás Cubas</i> (1881), de <b>Machado de Assis</b>, que também escreveu <i>Dom Casmurro</i> (a dúvida sobre Capitu) e <i>Quincas Borba</i>.</li><li><b>Naturalismo</b>: o ser humano determinado por meio, raça e momento histórico (<b>determinismo</b>), linguagem crua, zoomorfização. <b>Aluísio Azevedo</b> (<i>O Mulato</i>, 1881; <i>O Cortiço</i>, 1890), <b>Adolfo Caminha</b> (<i>Bom-Crioulo</i>).</li><li><b>Parnasianismo</b>: "arte pela arte", rigor formal, soneto, rimas ricas, temas clássicos. Tríade: <b>Olavo Bilac</b>, <b>Alberto de Oliveira</b> e <b>Raimundo Correia</b>.</li><li><b>Simbolismo (1893)</b>: musicalidade, sinestesia, espiritualidade, mistério, cor branca. <b>Cruz e Sousa</b> (<i>Broquéis</i> e <i>Missal</i>, 1893) e <b>Alphonsus de Guimaraens</b> ("Ismália").</li></ul>`,
{pairs:[['Machado de Assis','autor realista de Memórias Póstumas de Brás Cubas e Dom Casmurro'],['Aluísio Azevedo','autor naturalista de O Cortiço'],['Olavo Bilac','principal poeta parnasiano, defensor do rigor formal'],['Cruz e Sousa','principal poeta simbolista, autor de Broquéis'],['Alphonsus de Guimaraens','poeta simbolista autor de "Ismália"'],['Raul Pompeia','autor de O Ateneu, romance sobre um colégio interno']],
 qs:[['O determinismo (o ser humano moldado pelo meio, pela raça e pelo momento) é característica do:','Naturalismo',['Romantismo','Simbolismo','Arcadismo'],'O <b>Naturalismo</b> aplica ideias científicas do séc. XIX à literatura.'],['O lema "arte pela arte" e o gosto pelo soneto perfeito caracterizam o:','Parnasianismo',['Simbolismo','Romantismo','Modernismo'],'Rigor formal e culto da forma: <b>Parnasianismo</b>.'],['A dúvida sobre a traição de Capitu é o centro de:','Dom Casmurro',['O Cortiço','Iracema','Senhora'],'<i>Dom Casmurro</i> (1899), narrado por Bentinho.'],['Musicalidade, sinestesia e espiritualidade são marcas do:','Simbolismo',['Naturalismo','Parnasianismo','Realismo'],'<b>Simbolismo</b>, com Cruz e Sousa.'],['O marco inicial do Realismo no Brasil é:','Memórias Póstumas de Brás Cubas (1881)',['O Guarani (1857)','Os Sertões (1902)','Macunaíma (1928)'],'Machado de Assis, 1881.']]}),
SKL('lit4','Pré-Modernismo e Modernismo','🎨','A Semana de Arte Moderna (1922) rompe com o passado: verso livre, linguagem coloquial, humor e nacionalismo crítico.',
`<p><b>Pré-Modernismo</b> (1902–1922): denúncia da realidade brasileira. <b>Euclides da Cunha</b> (<i>Os Sertões</i>, 1902, sobre Canudos), <b>Lima Barreto</b> (<i>Triste Fim de Policarpo Quaresma</i>), <b>Monteiro Lobato</b> (<i>Urupês</i>, o Jeca Tatu), <b>Augusto dos Anjos</b> (<i>Eu</i>).</p>
<h3>Modernismo</h3><ul><li><b>1ª fase (1922–1930, "heroica")</b>: Semana de Arte Moderna (fevereiro de 1922, Theatro Municipal de São Paulo); ruptura, verso livre, humor, poema-piada. <b>Mário de Andrade</b> (<i>Macunaíma</i>, <i>Pauliceia Desvairada</i>), <b>Oswald de Andrade</b> (<i>Manifesto Antropófago</i>, 1928), <b>Manuel Bandeira</b> ("Os Sapos", "Vou-me embora pra Pasárgada").</li><li><b>2ª fase (1930–1945)</b>: poesia reflexiva e social — <b>Carlos Drummond de Andrade</b> ("No meio do caminho", <i>Sentimento do Mundo</i>), <b>Cecília Meireles</b>, <b>Vinicius de Moraes</b>; romance regionalista de 30 — <b>Graciliano Ramos</b> (<i>Vidas Secas</i>, <i>São Bernardo</i>), <b>Rachel de Queiroz</b> (<i>O Quinze</i>), <b>Jorge Amado</b> (<i>Capitães da Areia</i>), <b>José Lins do Rego</b> (<i>Menino de Engenho</i>), <b>Erico Verissimo</b>.</li><li><b>3ª fase (a partir de 1945)</b>: experimentação com a linguagem — <b>Guimarães Rosa</b> (<i>Grande Sertão: Veredas</i>, 1956), <b>Clarice Lispector</b> (<i>A Hora da Estrela</i>, 1977), <b>João Cabral de Melo Neto</b> (<i>Morte e Vida Severina</i>).</li></ul>`,
{pairs:[['Euclides da Cunha','autor pré-modernista de Os Sertões, sobre a Guerra de Canudos'],['Lima Barreto','autor de Triste Fim de Policarpo Quaresma'],['Mário de Andrade','autor de Macunaíma, "o herói sem nenhum caráter"'],['Oswald de Andrade','autor do Manifesto Antropófago (1928)'],['Graciliano Ramos','autor de Vidas Secas, sobre a família de Fabiano'],['Rachel de Queiroz','autora de O Quinze, sobre a seca de 1915'],['Carlos Drummond de Andrade','poeta de "No meio do caminho tinha uma pedra"'],['Guimarães Rosa','autor de Grande Sertão: Veredas'],['Clarice Lispector','autora de A Hora da Estrela, com a nordestina Macabéa'],['João Cabral de Melo Neto','autor do auto de Natal Morte e Vida Severina']],
 qs:[['A Semana de Arte Moderna aconteceu em:','1922, em São Paulo',['1922, no Rio de Janeiro','1930, em São Paulo','1945, em Belo Horizonte'],'Fevereiro de <b>1922</b>, no Theatro Municipal de <b>São Paulo</b>.'],['O Manifesto Antropófago propõe:','"devorar" a cultura estrangeira e transformá-la em algo brasileiro',['copiar fielmente os modelos europeus','voltar aos valores do Arcadismo','abandonar qualquer influência indígena'],'A antropofagia cultural de Oswald de Andrade (1928).'],['O romance regionalista de 1930, que denuncia a seca e a miséria no Nordeste, tem como exemplo:','Vidas Secas',['Macunaíma','Dom Casmurro','A Moreninha'],'<i>Vidas Secas</i> (1938), de Graciliano Ramos.'],['A inovação na linguagem, com neologismos e a fala do sertão, marca a obra de:','Guimarães Rosa',['Olavo Bilac','José de Alencar','Castro Alves'],'<b>Guimarães Rosa</b>, de <i>Grande Sertão: Veredas</i>.'],['Uma característica da 1ª fase modernista é:','o verso livre e a linguagem coloquial',['o soneto com rimas ricas','a idealização do indígena','o pessimismo ultrarromântico'],'Ruptura com a tradição: <b>verso livre</b>, humor e coloquialidade.']]}),
SKL('versif','Versificação e interpretação de poemas','🎼','Conte as sílabas poéticas até a última tônica; soneto tem 14 versos: dois quartetos e dois tercetos.',
`<p><b>Verso</b> é cada linha do poema; <b>estrofe</b>, o conjunto de versos. <b>Soneto</b>: 14 versos em dois <b>quartetos</b> e dois <b>tercetos</b>.</p>
<h3>Métrica</h3><p>As <b>sílabas poéticas</b> são contadas até a última sílaba tônica, juntando vogais entre palavras (elisão). <b>Redondilha menor</b>: 5 sílabas; <b>redondilha maior</b>: 7; <b>decassílabo</b>: 10; <b>alexandrino</b>: 12. Versos sem métrica fixa são <b>versos livres</b>.</p>
<h3>Rima</h3><p><b>Emparelhada</b> (AABB), <b>alternada ou cruzada</b> (ABAB), <b>interpolada ou oposta</b> (ABBA). <b>Rima rica</b>: entre classes gramaticais diferentes; <b>pobre</b>: da mesma classe. <b>Versos brancos</b>: sem rima.</p>
<h3>Eu lírico</h3><p>É a "voz" que fala no poema — não se confunde com o autor.</p>`,
{pairs:[['Soneto','poema de 14 versos: dois quartetos e dois tercetos'],['Redondilha maior','verso de 7 sílabas poéticas'],['Redondilha menor','verso de 5 sílabas poéticas'],['Decassílabo','verso de 10 sílabas poéticas'],['Alexandrino','verso de 12 sílabas poéticas'],['Verso livre','verso sem métrica regular'],['Verso branco','verso sem rima'],['Eu lírico','a voz que se expressa no poema, diferente do autor'],['Rima interpolada','esquema ABBA'],['Rima alternada','esquema ABAB']],
 qs:[['Quantos versos tem um soneto?','14',['12','10','16'],'Dois quartetos (8) + dois tercetos (6) = <b>14</b>.'],['Em "Minha terra tem palmeiras" (Mi-nha-ter-ra-tem-pal-<b>mei</b>-ras), contamos até a última tônica. O verso tem:','7 sílabas poéticas (redondilha maior)',['8 sílabas poéticas','5 sílabas poéticas','10 sílabas poéticas'],'Conta-se até "mei": 7 sílabas — <b>redondilha maior</b>.'],['O esquema de rimas ABAB é chamado de:','alternado (cruzado)',['emparelhado','interpolado','branco'],'A rima com C, B com D: <b>alternada</b>.']]})
]});

const GLOSS=autoGloss(UNITS,[
 {k:['crase'],n:'Crase',s:'crase',t:'Crase é a fusão da preposição "a" com o artigo "a". Truque: troque a palavra feminina por uma masculina; se aparecer "ao", use "à". Ex.: vou à escola (vou ao colégio).'},
 {k:['porque','por que','porques'],n:'Porquês',s:'ortog',t:'"Por que": pergunta (Por que saiu?). "Por quê": fim de frase. "Porque": explicação. "O porquê": substantivo.'},
 {k:['redacao','enem redacao','proposta de intervencao'],n:'Redação do ENEM',s:'generos',t:'Texto dissertativo-argumentativo com tese, dois argumentos bem desenvolvidos e proposta de intervenção com agente, ação, meio, finalidade e detalhamento.'},
 {k:['virgula'],n:'Vírgula',s:'pontua',t:'Nunca separe sujeito e verbo. Use vírgula em enumerações, vocativos, apostos, adjuntos adverbiais deslocados e antes de "mas".'}]);
