/* =====================================================================
   Português v2 — Interpretação de texto e Leituras obrigatórias da FUVEST
   Os textos das questões de interpretação foram escritos para o app.
   As questões sobre os livros são de estudo (não são de prova oficial).
   ===================================================================== */
const PSG=(t,src)=>`<span class="psg">${t}${src?`<small>${src}</small>`:''}</span>`;
const YT_SEARCH=t=>'https://www.youtube.com/results?search_query='+encodeURIComponent(t);
function VIDS(list,more){ return `<h3>🎬 Vídeos sobre a obra</h3><div class="vids">${list.map(([id,t])=>`<a class="btn sm red" href="https://www.youtube.com/watch?v=${id}" target="_blank" rel="noopener">▶ ${t}</a>`).join('')}<a class="btn sm ghost" href="${YT_SEARCH(more)}" target="_blank" rel="noopener">🔎 Mais vídeos</a></div>`; }

/* ------------------------ INTERPRETAÇÃO DE TEXTO ------------------------ */
const TX_BIKE=PSG('Nas grandes cidades, a bicicleta deixou de ser apenas lazer de fim de semana. Com ciclovias interligadas, ela passou a disputar espaço com o ônibus no trajeto para o trabalho. Ainda assim, a falta de bicicletários seguros nas estações de metrô faz muitos ciclistas desistirem no meio do caminho: pedalam até certo ponto, mas não têm onde deixar a bicicleta.');
const TX_SONO=PSG('O sono não é um intervalo em que o cérebro “desliga”. Durante a noite, ele reorganiza o que foi aprendido no dia, fortalecendo algumas conexões e enfraquecendo outras. Por isso, estudantes que trocam horas de sono por horas de estudo na véspera da prova costumam lembrar menos do que colegas que estudaram menos e dormiram bem.');
const TX_BOTOES=PSG('Minha avó guardava os botões de todas as roupas que já não serviam. Ficavam num pote de vidro, misturados, sem utilidade aparente. Quando alguém perdia um botão, porém, era ali que a família inteira ia procurar. O pote, que parecia bagunça, era memória organizada de outro jeito.');
const TX_ARVORE=PSG('Não basta plantar árvores em datas comemorativas. Uma muda sem cuidado morre no primeiro verão seco. Reflorestar exige anos de rega, poda e proteção — e isso custa bem mais que uma foto na inauguração.');
const TX_FABRICA=PSG('Depois que a fábrica fechou, a padaria da esquina passou a abrir só pela manhã, e a linha de ônibus que parava ali teve os horários reduzidos pela metade.');

const UNIT_INTERP={id:'p6',free:true,title:'Interpretação de texto',sub:'Ideia central, inferência, argumentação, humor, referência e intertextualidade',color:'#2bb673',dark:'#1f8f57',skills:[
SKL('ideia','Ideia central e informação do texto','🎯','Leia primeiro a pergunta. A resposta certa está apoiada no texto: desconfie de alternativas que exageram (extrapolação), que pegam só um pedaço (redução) ou que dizem o contrário (contradição).',
`<p>Toda questão de interpretação pede que você prove a resposta com o texto. Três perguntas ajudam:</p><ul><li><b>Tema</b>: de que o texto fala? (o assunto geral)</li><li><b>Tese ou ideia central</b>: o que o texto diz sobre esse tema?</li><li><b>Informação explícita</b>: o que está escrito com todas as letras? Enunciados com “segundo o texto” ou “de acordo com o autor” pedem isso.</li></ul>
<h3>Os três erros clássicos das alternativas</h3><ul><li><b>Extrapolação</b>: vai além do que o texto permite afirmar (“sempre”, “todos”, “nunca”, “a única causa”).</li><li><b>Redução</b>: apresenta um detalhe como se fosse a ideia central.</li><li><b>Contradição</b>: afirma o oposto do texto.</li></ul>
<div class="ex">Uma alternativa pode ser verdadeira no mundo real e mesmo assim estar errada, se o texto não a sustenta.</div>
<p>Para treinar com questões reais, abra <b>Provas → ENEM</b>: quase todas as questões de Linguagens são de interpretação.</p>`,
{pairs:[['Extrapolação','ir além do que o texto permite afirmar'],['Redução','tomar um detalhe do texto como se fosse a ideia central'],['Contradição','afirmar o oposto do que o texto diz'],['Tema','assunto geral de que o texto trata'],['Tese','posição que o autor defende sobre o tema'],['Informação explícita','o que está dito com todas as letras no texto']],
 qs:[[TX_BIKE+'Qual é a ideia central do texto?','A bicicleta ganhou espaço como transporte diário, mas a falta de lugar seguro para estacioná-la limita seu uso.',['A bicicleta é mais rápida que o ônibus em qualquer trajeto.','As ciclovias das grandes cidades são perigosas.','A bicicleta continua sendo usada apenas nos fins de semana.'],'O texto afirma o crescimento do uso diário (“deixou de ser apenas lazer”) e aponta o limite (“falta de bicicletários seguros”). As outras alternativas extrapolam ou contradizem o texto.'],
  [TX_BIKE+'Segundo o texto, muitos ciclistas desistem no meio do caminho porque:','não encontram bicicletários seguros nas estações de metrô.',['as ciclovias não são interligadas.','o metrô proíbe a entrada com bicicletas.','o trajeto até o trabalho é longo demais.'],'Informação explícita: “a falta de bicicletários seguros nas estações de metrô faz muitos ciclistas desistirem”. O texto diz que as ciclovias <b>são</b> interligadas.'],
  [TX_SONO+'A tese defendida no texto é a de que:','dormir bem faz parte do processo de aprender.',['estudar na véspera da prova é sempre inútil.','o cérebro fica inativo durante o sono.','quem dorme mais estuda menos.'],'O sono “reorganiza o que foi aprendido”. “Sempre inútil” é extrapolação; “cérebro inativo” contradiz a primeira frase.'],
  [TX_SONO+'A expressão “Por isso”, no último período, introduz:','uma conclusão tirada do que foi dito antes.',['uma oposição ao que foi dito antes.','uma condição para que o fato aconteça.','um exemplo sem relação com o período anterior.'],'Se o sono consolida a memória, então quem troca sono por estudo lembra menos: <b>conclusão</b>.'],
  [TX_BOTOES+'O último período do texto sugere que:','aquilo que parece desordem pode ter sentido para quem o organizou.',['a avó era uma pessoa desorganizada.','botões antigos têm valor comercial.','a família desprezava os hábitos da avó.'],'“Memória organizada de outro jeito” reinterpreta a “bagunça”: o pote tinha uma lógica própria.'],
  [PSG('Uma pesquisa com 2 mil adolescentes mostrou que 7 em cada 10 leem notícias pelo celular, mas só 2 em cada 10 costumam checar a fonte antes de compartilhar.')+'Qual conclusão é compatível com os dados?','A maioria dos adolescentes pesquisados lê notícias pelo celular, mas poucos verificam a fonte.',['A maioria dos adolescentes compartilha notícias falsas.','Os adolescentes não se interessam por notícias.','Só 20% dos adolescentes usam celular.'],'Os dados falam de <b>checar a fonte</b>, não de compartilhar notícias falsas (isso seria extrapolação).'],
  [PSG('A cidade tem 40 praças, mas apenas 6 contam com banheiro público. Nas demais, quem passa o dia ali — vendedores, idosos, mães com crianças pequenas — depende da boa vontade dos comércios vizinhos.')+'O texto chama atenção principalmente para:','a falta de estrutura das praças para quem permanece nelas.',['o excesso de praças na cidade.','a má vontade dos comerciantes.','a proibição de vendedores nas praças.'],'O foco é a carência de banheiros (6 de 40) e quem é afetado por ela.'],
  [TX_ARVORE+'Qual alternativa faz uma <b>redução</b> da ideia do texto?','O texto informa que mudas morrem no verão seco.',['O texto defende que reflorestar exige cuidado contínuo, e não apenas atos simbólicos.','O texto critica ações ambientais feitas só para aparecer.','O texto compara o custo do cuidado com o de uma cerimônia.'],'A morte das mudas é um detalhe usado como argumento; apresentá-la como o assunto do texto é <b>redução</b>.']],
 tf:[['Tema é o assunto geral; tese é a posição que o autor defende sobre ele.',true,'Verdadeiro.'],['Se a alternativa traz uma informação verdadeira no mundo real, ela é necessariamente a resposta certa.',false,'Falso: a resposta precisa estar apoiada no texto lido.'],['Palavras como “sempre”, “nunca” e “todos” costumam indicar extrapolação nas alternativas.',true,'Verdadeiro: generalizações absolutas raramente são sustentadas pelo texto.'],['Enunciados com “segundo o texto” pedem a opinião do aluno.',false,'Falso: pedem o que o texto diz.']]}),

SKL('infere','Inferências, pressupostos e subentendidos','🔎','Pressuposto vem marcado por palavras (“voltou a”, “ainda”, “até”, “finalmente”) e continua valendo se a frase for negada; subentendido é uma insinuação que depende do contexto.',
`<p><b>Inferir</b> é concluir algo que o texto não diz com todas as letras, mas que ele autoriza. Não é inventar: toda inferência tem apoio em pistas do texto.</p>
<ul><li><b>Pressuposto</b>: informação implícita marcada na própria frase. “Pedro <b>voltou a</b> correr” pressupõe que ele corria antes. Marcadores comuns: <i>voltar a, deixar de, parar de, ainda, já, também, até, finalmente</i>. O pressuposto resiste à negação (“Pedro <b>não</b> voltou a correr” ainda pressupõe que ele corria).</li>
<li><b>Subentendido</b>: insinuação que depende da situação. “Está quente aqui, não?” pode ser um pedido para abrir a janela. Quem fala pode negar que quis dizer isso.</li></ul>`,
{pairs:[['Pressuposto','informação implícita marcada por palavras da própria frase'],['Subentendido','insinuação que depende do contexto e pode ser negada por quem fala'],['Inferência','conclusão autorizada por pistas do texto'],['“Voltar a”','marcador que pressupõe que a ação já acontecia antes'],['“Até” (inclusive)','marcador que indica algo inesperado']],
 qs:[['“Pedro voltou a correr no parque.” Essa frase pressupõe que:','Pedro já corria no parque antes.',['Pedro corre todos os dias.','Pedro nunca tinha corrido.','o parque é perto da casa de Pedro.'],'<b>Voltou a</b> indica que a ação já acontecia antes.'],
  ['“Até o professor riu da piada.” A palavra “até” indica que:','não se esperava que o professor risse.',['o professor ri de tudo.','a piada era sobre o professor.','só o professor riu.'],'“Até” marca o elemento menos esperado de uma série.'],
  ['Numa sala abafada, alguém diz: “Nossa, como está quente aqui, não?”. O subentendido mais provável é:','um pedido para abrir a janela ou ligar o ventilador.',['uma previsão do tempo.','uma reclamação sobre o inverno.','um elogio ao ambiente.'],'A frase informa o calor, mas insinua um pedido: <b>subentendido</b>.'],
  ['“Ana ainda mora com os pais.” A frase pressupõe que:','Ana já morava com os pais antes.',['Ana vai se mudar amanhã.','Ana nunca morou com os pais.','os pais de Ana moram sozinhos.'],'<b>Ainda</b> indica continuidade de uma situação anterior.'],
  ['“O prefeito finalmente inaugurou a ponte.” O advérbio “finalmente” sugere que:','a obra demorou mais do que se esperava.',['a ponte é a primeira da cidade.','o prefeito acabou de assumir.','a ponte foi barata.'],'“Finalmente” revela a expectativa frustrada pela demora.'],
  [PSG('Os ingressos esgotaram em vinte minutos. Na porta do estádio, cambistas ofereciam entradas pelo triplo do preço.')+'Pode-se inferir que:','a procura pelos ingressos era muito maior que a oferta.',['o jogo foi cancelado.','os cambistas eram funcionários do clube.','os ingressos estavam caros demais.'],'Esgotar rápido e ser revendido pelo triplo são pistas de <b>procura alta</b>.'],
  [TX_FABRICA+'Pode-se inferir do texto que a fábrica:','movimentava o comércio e a circulação de pessoas no bairro.',['era a dona da padaria da esquina.','fechou por causa da linha de ônibus.','atrapalhava a vida dos moradores.'],'As mudanças na padaria e no ônibus depois do fechamento indicam que a fábrica atraía gente ao bairro.'],
  ['“Mariana deixou de usar o carro para ir ao trabalho.” Qual informação é pressuposta?','Mariana usava o carro para ir ao trabalho.',['Mariana vendeu o carro.','Mariana agora vai de ônibus.','Mariana mudou de emprego.'],'“Deixou de” pressupõe o hábito anterior; as outras alternativas são hipóteses sem apoio.']],
 tf:[['“Pedro não voltou a correr” continua pressupondo que Pedro corria antes.',true,'Verdadeiro: o pressuposto resiste à negação.'],['No subentendido, quem fala pode negar que quis dizer aquilo.',true,'Verdadeiro: a insinuação fica por conta de quem ouve.'],['Inferir é inventar informações sem relação com o texto.',false,'Falso: a inferência é apoiada em pistas do texto.']]}),

SKL('argum','Tese, argumentos e ponto de vista','⚖️','Ache a tese (o que o autor defende) e veja como ele a sustenta: autoridade, dados, exemplos, comparação, causa e consequência. Adjetivos e advérbios revelam o ponto de vista.',
`<p>Num texto argumentativo, o autor defende uma <b>tese</b> e a sustenta com <b>argumentos</b>:</p>
<table><tr><th>Argumento</th><th>Como aparece</th></tr><tr><td><b>Autoridade</b></td><td>cita especialista ou instituição (“segundo a OMS…”)</td></tr><tr><td><b>Dados</b></td><td>números, pesquisas, estatísticas</td></tr><tr><td><b>Exemplificação</b></td><td>um caso concreto que ilustra a tese</td></tr><tr><td><b>Comparação / analogia</b></td><td>aproxima duas situações</td></tr><tr><td><b>Causa e consequência</b></td><td>mostra por que algo acontece e o que provoca</td></tr></table>
<p><b>Concessão</b>: o autor reconhece uma ideia contrária para depois rebatê-la (“É verdade que…, <b>mas</b>…”; “<b>Embora</b>…”).</p>
<p><b>Fato × opinião</b>: fato pode ser verificado (“o parque tem 12 hectares”); opinião é avaliação (“o parque é o lugar mais agradável da cidade”). Palavras avaliativas (<i>lamentável, absurdo, felizmente</i>) e <b>modalizadores</b> (<i>talvez, certamente, é preciso</i>) mostram a posição de quem escreve.</p>`,
{pairs:[['Argumento de autoridade','cita um especialista ou instituição reconhecida'],['Argumento por dados','usa números, pesquisas e estatísticas'],['Exemplificação','usa um caso concreto para ilustrar a tese'],['Analogia','aproxima duas situações diferentes para convencer'],['Concessão','reconhece uma ideia contrária antes de rebatê-la'],['Modalizador','palavra que mostra o grau de certeza ou de avaliação de quem fala']],
 qs:[['“Segundo a Organização Mundial da Saúde, adultos devem praticar ao menos 150 minutos de atividade física por semana.” Esse trecho é um argumento:','de autoridade',['de exemplificação','por analogia','de concessão'],'Apoia-se em uma instituição reconhecida.'],
  ['“Proibir o celular na escola é como tirar o volante do carro para evitar acidentes.” O autor usa:','uma analogia',['um dado estatístico','um argumento de autoridade','uma citação'],'Aproxima duas situações para convencer: <b>analogia</b>.'],
  ['“É verdade que o aplicativo facilita a vida de muitos motoristas; no entanto, a falta de direitos trabalhistas pesa sobre eles.” O trecho antes de “no entanto” é:','uma concessão, que reconhece um lado da questão antes de rebatê-lo',['a tese do autor','a conclusão do texto','um dado estatístico'],'O autor admite um ponto (“é verdade que…”) para depois contrapor: <b>concessão</b>.'],
  ['Qual frase expressa uma <b>opinião</b>, e não um fato?','O novo parque é o lugar mais agradável da cidade.',['O novo parque tem 12 hectares.','O parque foi inaugurado em março.','O parque abre das 6h às 22h.'],'“Mais agradável” é avaliação; as outras podem ser verificadas.'],
  [TX_ARVORE+'A tese do texto é a de que:','reflorestar exige cuidado contínuo, e não só atos simbólicos de plantio.',['não se deve plantar árvores em datas comemorativas.','as árvores sempre morrem no verão.','as fotos de inauguração são caras.'],'O autor não condena plantar em datas festivas; condena parar por aí (“não basta”).'],
  [TX_ARVORE+'A expressão “uma foto na inauguração” tem valor:','crítico, ao apontar ações feitas só pela aparência.',['elogioso, ao valorizar a divulgação.','técnico, ao descrever o registro da obra.','neutro, sem juízo de valor.'],'A comparação “custa bem mais que uma foto” ironiza a ação de fachada.'],
  ['Em “<b>Talvez</b> a medida funcione”, a palavra destacada:','indica dúvida de quem fala (é um modalizador).',['indica certeza absoluta.','indica o momento da ação.','liga duas orações.'],'<b>Talvez</b> modaliza o enunciado, marcando incerteza.'],
  ['“Como o transporte público é caro e demorado, muitos trabalhadores gastam até quatro horas por dia no trajeto.” O argumento se organiza por:','causa e consequência',['analogia','autoridade','concessão'],'Causa: transporte caro e demorado. Consequência: horas perdidas no trajeto.']],
 tf:[['Um dado estatístico é, por si só, uma opinião.',false,'Falso: o dado pode ser verificado; a opinião está na interpretação que se faz dele.'],['Adjetivos como “lamentável” e “absurdo” revelam o ponto de vista do autor.',true,'Verdadeiro: são termos avaliativos.'],['Na concessão, o autor reconhece uma ideia contrária para depois rebatê-la.',true,'Verdadeiro.']]}),

SKL('humor','Humor, ironia e linguagem figurada','😄','O humor costuma nascer da quebra de expectativa ou do duplo sentido; na ironia, o sentido pretendido é o contrário do literal.',
`<ul><li><b>Quebra de expectativa</b>: o final contraria o que o leitor esperava.</li><li><b>Ambiguidade / duplo sentido</b>: uma palavra ou construção permite duas leituras.</li><li><b>Ironia</b>: dizer o contrário do que se pensa, com intenção crítica ou de humor.</li><li><b>Exagero</b> (hipérbole) e <b>personificação</b> também produzem efeito cômico ou expressivo.</li></ul>
<p><b>Charge</b>: desenho de humor que critica um fato atual (precisa do contexto). <b>Tirinha</b>: sequência de quadrinhos, geralmente com desfecho inesperado.</p>
<p><b>Denotação</b> é o sentido literal (dicionário); <b>conotação</b> é o sentido figurado, que depende do contexto.</p>`,
{pairs:[['Ironia','dizer o contrário do que se pensa, com intenção crítica ou cômica'],['Ambiguidade','construção que permite mais de uma leitura'],['Quebra de expectativa','desfecho que contraria o que o leitor previa'],['Charge','desenho de humor que critica um fato atual'],['Conotação','sentido figurado, que depende do contexto'],['Denotação','sentido literal da palavra']],
 qs:[['Numa tirinha, a mãe pergunta se o filho arrumou o quarto. Ele responde: “Arrumei um jeito de você não entrar lá”. O humor nasce:','do duplo sentido de “arrumar”, que quebra a expectativa da mãe.',['de a mãe estar brava.','de o filho ter arrumado o quarto.','da falta de pontuação.'],'“Arrumar o quarto” × “arrumar um jeito”: duplo sentido e quebra de expectativa.'],
  ['O aluno entrega a prova em branco e o professor diz: “Parabéns pela originalidade!”. A fala do professor é:','irônica',['literal','um elogio sincero','uma explicação técnica'],'Diz o contrário do que pensa: <b>ironia</b>.'],
  ['Cartaz numa loja: “Vendemos bicicletas para crianças de alumínio”. A graça involuntária vem:','da ambiguidade causada pela posição de “de alumínio”.',['de um erro de ortografia.','do uso de gíria.','da falta de verbo.'],'Parece que as <b>crianças</b> são de alumínio. O certo seria “bicicletas de alumínio para crianças”.'],
  ['Em “Ele tem um coração de pedra”, a linguagem é:','conotativa (figurada)',['denotativa (literal)','técnica','regional'],'Ninguém tem coração de pedra de verdade: sentido <b>figurado</b>.'],
  ['Uma charge mostra um homem regando um vaso com uma única planta enquanto, ao fundo, a floresta pega fogo. A crítica é a:','ações ambientais pequenas diante de problemas muito maiores.',['falta de água nas cidades.','o preço das plantas.','qualidade dos regadores.'],'O contraste entre o gesto mínimo e o incêndio é o centro da crítica.'],
  ['“— Garçom, tem uma mosca na minha sopa! — Fale baixo, senão todos vão querer.” O humor está em:','o garçom tratar a mosca como algo desejado, invertendo a expectativa.',['o cliente gostar de moscas.','a sopa estar fria.','o garçom concordar com a reclamação.'],'A resposta inesperada inverte a lógica da reclamação.'],
  ['“Adoro passar três horas no trânsito”, diz o motorista, suado e irritado. O recurso é:','ironia',['eufemismo','catacrese','pleonasmo'],'O contexto (suado e irritado) mostra que ele pensa o contrário.'],
  ['Na manchete “A cidade acordou debaixo d’água”, há:','personificação: a cidade “acorda” como uma pessoa.',['catacrese','ironia','eufemismo'],'Atribui ação humana (acordar) a um ser inanimado: <b>prosopopeia</b>.']],
 tf:[['A compreensão de uma charge depende do contexto em que ela foi publicada.',true,'Verdadeiro: ela comenta um fato do momento.'],['Na ironia, o sentido pretendido coincide com o literal.',false,'Falso: é o oposto do literal.'],['A ambiguidade pode ser intencional, como em piadas e propagandas.',true,'Verdadeiro.']]}),

SKL('refer','Referência e conectivos no texto','🔗','Descubra a que termo cada pronome se refere e que relação cada conectivo estabelece: adição, oposição, causa, conclusão, condição, concessão, proporção.',
`<p>Muitas questões perguntam <b>a que termo uma palavra se refere</b> (pronomes como <i>ela, seu, isso, o qual</i>) e <b>que relação um conectivo estabelece</b>.</p>
<table><tr><th>Relação</th><th>Conectivos</th></tr><tr><td>Adição</td><td>e, além disso, também</td></tr><tr><td>Oposição</td><td>mas, porém, contudo, no entanto</td></tr><tr><td>Concessão</td><td>embora, ainda que, mesmo que, apesar de</td></tr><tr><td>Causa</td><td>porque, já que, visto que, como (no início)</td></tr><tr><td>Explicação</td><td>pois (antes do verbo), porque</td></tr><tr><td>Conclusão</td><td>portanto, logo, assim, pois (depois do verbo)</td></tr><tr><td>Condição</td><td>se, caso, desde que</td></tr><tr><td>Proporção</td><td>à medida que, à proporção que</td></tr><tr><td>Finalidade</td><td>para que, a fim de que</td></tr></table>
<p>Para testar, troque o conectivo por outro da mesma linha: o sentido tem de se manter.</p>`,
{pairs:[['Portanto','conectivo de conclusão'],['Embora','conectivo de concessão'],['No entanto','conectivo de oposição'],['Caso','conectivo de condição'],['À medida que','conectivo de proporção'],['A fim de que','conectivo de finalidade'],['Visto que','conectivo de causa']],
 qs:[[PSG('Os agricultores da região adotaram a irrigação por gotejamento. Com ela, reduziram pela metade o consumo de água.')+'O pronome “ela” retoma:','a irrigação por gotejamento',['a região','a água','a metade'],'“Com <b>ela</b>” = com a irrigação por gotejamento.'],
  ['“Choveu pouco este ano; mesmo assim, a colheita foi boa.” A expressão “mesmo assim” expressa:','concessão: a colheita foi boa apesar da pouca chuva.',['causa','conclusão','tempo'],'Um fato que “deveria” impedir o outro não impediu: <b>concessão</b>.'],
  [PSG('O museu reabriu depois da reforma. Seus visitantes, porém, ainda são poucos.')+'O termo “Seus” refere-se:','ao museu',['aos visitantes','à reforma','aos poucos'],'Os visitantes <b>do museu</b>.'],
  ['Em “Estude, pois a prova é amanhã”, o conectivo “pois” tem valor:','explicativo',['conclusivo','adversativo','condicional'],'Antes do verbo, “pois” explica a ordem dada.'],
  ['Qual conectivo pode substituir “no entanto” em “O plano era bom; no entanto, faltou dinheiro”, sem mudar o sentido?','contudo',['portanto','porque','assim que'],'<b>No entanto</b> e <b>contudo</b> expressam oposição.'],
  ['“À medida que a cidade crescia, os rios eram canalizados.” A oração destacada expressa:','proporção',['causa','finalidade','concessão'],'Um fato aumenta junto com o outro: <b>proporção</b>.'],
  ['Em “A médica conversou com a paciente sobre a sua saúde”, há ambiguidade porque:','“sua” pode se referir à médica ou à paciente.',['falta um verbo na frase.','“conversou” está no tempo errado.','“saúde” tem dois sentidos.'],'O possessivo “sua” permite duas leituras; “a saúde dela (da paciente)” desfaz a dúvida.'],
  ['“Caso chova, o show será adiado.” A palavra “Caso” introduz:','uma condição',['uma causa','uma consequência','uma comparação'],'<b>Caso</b> = se: condição.']],
 tf:[['“Portanto” e “logo” introduzem conclusão.',true,'Verdadeiro.'],['“Embora” introduz causa.',false,'Falso: “embora” introduz concessão.'],['Trocar um conectivo por outro da mesma relação mantém o sentido da frase.',true,'Verdadeiro, com os ajustes de tempo verbal quando necessários.']]}),

SKL('intertx','Intertextualidade e comparação de textos','📚','Paródia retoma um texto para mudar seu sentido (crítica ou humor); paráfrase diz o mesmo com outras palavras; alusão é uma referência indireta.',
`<p><b>Intertextualidade</b> é o diálogo entre textos:</p><ul><li><b>Citação</b>: reprodução literal, com aspas e fonte.</li><li><b>Paráfrase</b>: reescreve com outras palavras, mantendo o sentido.</li><li><b>Paródia</b>: retoma a forma de um texto conhecido para criar outro sentido, crítico ou cômico. Ex.: “Minha terra tem palmares / onde gorjeia o mar”, de Oswald de Andrade, sobre a “Canção do exílio” de Gonçalves Dias.</li><li><b>Alusão</b>: referência indireta a outro texto, fato ou obra.</li><li><b>Epígrafe</b>: citação no início de um livro ou capítulo, que anuncia o tema.</li></ul>
<h3>Comparar dois textos (Texto I e Texto II)</h3><p>Pergunte: qual é o <b>tema comum</b>? Os pontos de vista <b>concordam</b> ou <b>divergem</b>? São de <b>gêneros</b> diferentes (notícia × poema, gráfico × crônica)? O que um acrescenta ao outro?</p>`,
{pairs:[['Paródia','retoma um texto conhecido para criar outro sentido, crítico ou cômico'],['Paráfrase','reescreve um texto com outras palavras, mantendo o sentido'],['Citação','reprodução literal de outro texto, com indicação da fonte'],['Alusão','referência indireta a outro texto ou fato'],['Epígrafe','citação no início de uma obra ou capítulo, que anuncia o tema']],
 qs:[['“Minha terra tem palmares / onde gorjeia o mar” (Oswald de Andrade) retoma a “Canção do exílio”, de Gonçalves Dias. Trata-se de:','paródia, que dá novo sentido crítico ao poema original',['plágio','paráfrase fiel','citação literal'],'Mantém a forma, mas muda o sentido: “palmares” lembra o quilombo dos Palmares.'],
  ['Reescrever “A pressa é inimiga da perfeição” como “Quem faz tudo correndo costuma errar” é um exemplo de:','paráfrase',['paródia','alusão','epígrafe'],'Mesmo sentido, outras palavras: <b>paráfrase</b>.'],
  ['O slogan de uma cafeteria, “Penso, logo desperto”, faz alusão:','à frase “Penso, logo existo”, de Descartes',['a um provérbio popular sobre café','a um verso de Camões','a uma lei de trânsito'],'Retoma a célebre frase de Descartes com efeito de humor.'],
  [PSG('<b>Texto I</b>: notícia informa que o uso de bicicletas na capital cresceu 30% em um ano.<br><b>Texto II</b>: crônica narra o medo de um ciclista ao atravessar uma avenida sem ciclovia.')+'Os textos se aproximam porque:','tratam do uso da bicicleta na cidade, com enfoques diferentes: um dado objetivo e uma experiência pessoal.',['defendem a proibição das bicicletas nas avenidas.','são do mesmo gênero textual.','contradizem um ao outro sobre os números.'],'Mesmo tema, gêneros e enfoques diferentes: dado (notícia) e vivência (crônica).'],
  ['Um meme usa “Ser ou não ser, eis a questão” para falar da dúvida entre ir ou não à academia. Há intertextualidade com:','a peça Hamlet, de Shakespeare, com efeito de humor',['a Bíblia','um hino nacional','uma notícia recente'],'A fala famosa de Hamlet é deslocada para uma situação banal.'],
  ['A citação no início de um livro que anuncia o seu tema chama-se:','epígrafe',['prefácio','paródia','nota de rodapé'],'<b>Epígrafe</b>.']],
 tf:[['Toda paródia tem intenção de homenagear o texto original.',false,'Falso: em geral, a paródia critica ou satiriza; quem homenageia costuma fazer paráfrase ou alusão.'],['A paráfrase mantém o sentido do texto original.',true,'Verdadeiro.'],['Para comparar Texto I e Texto II, é útil identificar o tema comum e os pontos de vista de cada um.',true,'Verdadeiro.']]})
]};

/* ------------------------ LEITURAS OBRIGATÓRIAS FUVEST 2027 ------------------------ */
const BOOKS=[
 ['Opúsculo humanitário','Nísia Floresta','1853','ensaios','Brasil'],
 ['Nebulosas','Narcisa Amália','1872','poesia','Brasil'],
 ['Memórias de Martha','Júlia Lopes de Almeida','1889','romance','Brasil'],
 ['Caminho de pedras','Rachel de Queiroz','1937','romance','Brasil'],
 ['A paixão segundo G.H.','Clarice Lispector','1964','romance','Brasil'],
 ['Geografia','Sophia de Mello Breyner Andresen','1967','poesia','Portugal'],
 ['Balada de amor ao vento','Paulina Chiziane','1990','romance','Moçambique'],
 ['Canção para ninar menino grande','Conceição Evaristo','2018','romance (novela)','Brasil'],
 ['A visão das plantas','Djaimilia Pereira de Almeida','2019','romance (novela)','Portugal (autora nascida em Angola)']];
const BK=(b)=>`<div class="ex">📖 <b>${b[0]}</b> · ${b[1]} · ${b[2]} · ${b[3]} · ${b[4]}</div>`;

const UNIT_LIVROS={id:'p7',free:true,title:'Leituras obrigatórias FUVEST 2027',sub:'As 9 obras da lista, todas de autoras de língua portuguesa: resumo, personagens, temas, vídeos e questões',color:'#ce82ff',dark:'#a568cc',skills:[
SKL('livros','A lista da FUVEST 2027','📚','São 9 obras, todas escritas por mulheres de língua portuguesa (Brasil, Portugal e Moçambique), do século XIX ao XXI. A lista vale de 2026 a 2029, com trocas pontuais.',
`<p>A FUVEST definiu, para os vestibulares de 2026 a 2029, uma lista só com obras de <b>autoras de língua portuguesa</b>. Para a FUVEST 2027 (prova no fim de 2026), entraram <b>A paixão segundo G.H.</b> e <b>Geografia</b>, e saíram <i>O Cristo cigano</i> e <i>As meninas</i>.</p>
<table><tr><th>Obra</th><th>Autora</th><th>Ano</th><th>Gênero</th></tr>${BOOKS.map(b=>`<tr><td><b>${b[0]}</b></td><td>${b[1]} (${b[4]})</td><td>${b[2]}</td><td>${b[3]}</td></tr>`).join('')}</table>
<h3>Como a FUVEST cobra</h3><ul><li>Na <b>1ª fase</b>, questões de múltipla escolha com um trecho da obra: contexto, tema, narrador, estilo, relação com outras obras.</li><li>Na <b>2ª fase</b>, questões dissertativas que pedem interpretação de trechos e comparação entre obras da lista.</li><li>Eixos que atravessam a lista: <b>condição da mulher</b>, <b>educação</b>, <b>trabalho e classe</b>, <b>raça e colonialismo</b>, <b>natureza e espaço</b>, <b>linguagem e subjetividade</b>.</li></ul>
<p>As questões desta unidade são de estudo, escritas para o app; não são de prova oficial. Confirme a lista no <a href="https://www.fuvest.br" target="_blank" rel="noopener">site da FUVEST</a>.</p>`,
{pairs:BOOKS.map(b=>[b[0],`obra de ${b[1]}, ${b[3]}, publicada em ${b[2]}`]),tq:t=>`Sobre a obra <b>${t}</b>, é correto afirmar que é:`,dq:d=>`Qual livro da lista da FUVEST é ${d}?`,
 qs:[['O que as nove obras da lista da FUVEST 2027 têm em comum?','Todas foram escritas por mulheres de língua portuguesa.',['Todas são romances do século XX.','Todas foram escritas por autoras brasileiras.','Todas pertencem ao Modernismo.'],'A lista reúne autoras do Brasil, de Portugal e de Moçambique, em gêneros e épocas diferentes.'],
  ['Qual obra da lista é de uma autora moçambicana?','Balada de amor ao vento',['A visão das plantas','Geografia','Nebulosas'],'<b>Paulina Chiziane</b> é moçambicana.'],
  ['Quais obras da lista são livros de poemas?','Nebulosas e Geografia',['Opúsculo humanitário e Nebulosas','Geografia e A visão das plantas','Memórias de Martha e Caminho de pedras'],'<b>Nebulosas</b> (Narcisa Amália, 1872) e <b>Geografia</b> (Sophia de Mello Breyner Andresen, 1967).'],
  ['Qual é a obra mais antiga da lista?','Opúsculo humanitário (1853)',['Nebulosas (1872)','Memórias de Martha (1889)','Caminho de pedras (1937)'],'Nísia Floresta publicou o <b>Opúsculo humanitário</b> em 1853.'],
  ['Qual obra da lista não é ficção nem poesia, mas uma coletânea de artigos argumentativos?','Opúsculo humanitário',['Memórias de Martha','A visão das plantas','Canção para ninar menino grande'],'São 62 artigos (ensaios) de Nísia Floresta sobre a educação das mulheres.'],
  ['A educação como caminho para a mulher conquistar autonomia é tema central de:','Opúsculo humanitário e Memórias de Martha',['Geografia e Nebulosas','A visão das plantas e Geografia','A paixão segundo G.H. e Balada de amor ao vento'],'Nísia defende a instrução feminina; Martha estuda para se tornar professora e sair da pobreza.'],
  ['O colonialismo português aparece de modo central em:','Balada de amor ao vento e A visão das plantas',['Nebulosas e Memórias de Martha','Caminho de pedras e Geografia','Opúsculo humanitário e A paixão segundo G.H.'],'Moçambique colonial (Chiziane) e o capitão negreiro que volta a Portugal (Djaimilia).']],
 tf:[['A lista da FUVEST 2027 inclui autoras de Portugal e de Moçambique.',true,'Verdadeiro: Sophia de Mello Breyner Andresen e Djaimilia Pereira de Almeida (Portugal) e Paulina Chiziane (Moçambique).'],['Todas as obras da lista são romances.',false,'Falso: há ensaios (Opúsculo humanitário) e poesia (Nebulosas, Geografia).'],['A paixão segundo G.H. e Geografia entraram na lista para a FUVEST 2027.',true,'Verdadeiro: substituíram O Cristo cigano e As meninas.']]}),

SKL('opusculo','Opúsculo humanitário','🕯️','Coletânea de 62 artigos (1853) que defende a educação das mulheres como condição para o progresso da sociedade e critica a instrução feminina reduzida a prendas domésticas.',
BK(BOOKS[0])+`<h3>A autora</h3><p><b>Nísia Floresta Brasileira Augusta</b> é o pseudônimo de <b>Dionísia Gonçalves Pinto</b> (1810–1885), nascida no Rio Grande do Norte. Educadora e escritora, é considerada uma das precursoras do pensamento feminista no Brasil. Dirigiu um colégio para meninas no Rio de Janeiro e publicou, em 1832, <i>Direitos das mulheres e injustiça dos homens</i>. Viveu seus últimos anos na Europa.</p>
<h3>A obra</h3><p>Publicado em 1853 com a assinatura <b>B.A.</b> (“Brasileira Augusta”), reúne <b>62 artigos</b>, parte deles saída antes em jornais do Rio de Janeiro. É um texto <b>argumentativo</b> (ensaio), não ficção.</p><ul><li>Os primeiros textos traçam a <b>história da condição feminina</b> em várias civilizações, da Antiguidade ao século XIX.</li><li>Defende que a <b>instrução das meninas</b> é questão de civilização e de progresso da nação, e não enfeite.</li><li>Critica a educação feminina limitada a <b>prendas domésticas</b> e a verniz social, voltada só para o casamento.</li><li>Compara o Brasil com outros países para mostrar o atraso da educação feminina brasileira.</li><li>Valoriza a mulher como <b>educadora dos filhos</b> e, por isso, formadora de cidadãos — argumento que amplia o acesso à instrução, mas ainda a liga ao papel de mãe.</li></ul>
<h3>Fique de olho</h3><p>Relação entre <b>educação, família e nação</b>; o tom de denúncia; a data (Brasil imperial e escravocrata); o diálogo com <i>Memórias de Martha</i>, em que a educação também é caminho de autonomia.</p>`+VIDS([['SXXL0tm_CsM','Análise da obra'],['IoDp4QjbBh8','Resumo + análise']],'Opúsculo humanitário Nísia Floresta Fuvest'),
{pairs:[['Nísia Floresta','pseudônimo de Dionísia Gonçalves Pinto, educadora potiguar'],['B.A.','assinatura do livro: abreviatura de “Brasileira Augusta”'],['62 artigos','estrutura do Opúsculo humanitário, parte publicada antes em jornais'],['Educação feminina','tema central: condição para o progresso da sociedade'],['Prendas domésticas','tipo de instrução que a autora critica por limitar as mulheres']],
 qs:[['O Opúsculo humanitário pertence a qual gênero?','ensaio argumentativo (coletânea de artigos)',['romance epistolar','poesia lírica','teatro'],'São 62 artigos que defendem teses sobre a educação e a condição das mulheres.'],
  ['A tese central do Opúsculo humanitário é a de que:','a educação das mulheres é necessária ao progresso da sociedade.',['a mulher deve se dedicar só ao lar.','o Brasil já oferecia às meninas a melhor educação do mundo.','a literatura deve servir apenas ao entretenimento.'],'Nísia liga a instrução feminina ao avanço da civilização e da nação.'],
  ['O que Nísia Floresta critica na educação das meninas de seu tempo?','a instrução reduzida a prendas domésticas e a verniz social, voltada ao casamento',['o excesso de disciplinas científicas','a falta de aulas de etiqueta','o ensino de línguas estrangeiras a todos'],'A autora denuncia uma formação superficial, pensada para arranjar casamento.'],
  ['Nos primeiros textos da obra, a autora:','traça a história da condição da mulher em várias civilizações',['narra a própria infância','descreve a natureza do Nordeste','conta a história de um casamento'],'O percurso histórico (da Antiguidade ao séc. XIX) sustenta o argumento.'],
  ['Nísia Floresta Brasileira Augusta é o pseudônimo de:','Dionísia Gonçalves Pinto',['Júlia Lopes de Almeida','Narcisa Amália','Rachel de Queiroz'],'Nascida no Rio Grande do Norte em 1810.'],
  ['Qual argumento do livro amplia o acesso das mulheres à instrução, mas ainda o liga ao papel familiar?','a mulher educada forma melhor os filhos e, assim, os futuros cidadãos',['a mulher deve estudar para substituir os homens no governo','a instrução feminina é inútil fora da Europa','a mulher deve estudar apenas música e bordado'],'A valorização da mãe educadora é um traço importante e discutido da obra.'],
  ['O Opúsculo humanitário foi publicado num Brasil:','imperial e escravocrata, em 1853',['republicano, depois da abolição','da Era Vargas','da ditadura militar'],'1853: Segundo Reinado, antes da Abolição (1888).']],
 tf:[['O Opúsculo humanitário é um romance narrado em primeira pessoa.',false,'Falso: é uma coletânea de artigos argumentativos.'],['Nísia Floresta é considerada uma das precursoras do feminismo no Brasil.',true,'Verdadeiro.'],['Parte dos artigos saiu antes em jornais do Rio de Janeiro.',true,'Verdadeiro.']]}),

SKL('nebulosas','Nebulosas','🌫️','Livro de poemas românticos (1872) com natureza, subjetividade melancólica e crítica social abolicionista; o título sugere névoa, o vago — imagem da condição da poeta e da mulher.',
BK(BOOKS[1])+`<h3>A autora</h3><p><b>Narcisa Amália</b> (1852–1924), nascida em São João da Barra (RJ), publicou <i>Nebulosas</i> aos 20 anos. Foi republicana e abolicionista e é apontada como uma das primeiras mulheres a atuar como jornalista profissional no Brasil. O livro foi elogiado por <b>Machado de Assis</b> e chamou a atenção do imperador <b>D. Pedro II</b> — algo raro para uma autora naquele tempo.</p>
<h3>A obra</h3><p>Reúne <b>44 poemas</b> e se insere no <b>Romantismo</b>, dialogando com as três gerações:</p><ul><li><b>1ª geração</b>: a natureza brasileira e o sentimento de pátria.</li><li><b>2ª geração</b>: subjetivismo, melancolia, sofrimento amoroso.</li><li><b>3ª geração (condoreira)</b>: crítica social, sobretudo à <b>escravidão</b>.</li></ul>
<p>O título remete à <b>névoa</b>, ao vago, ao indefinido — metáfora da condição existencial do eu lírico e da <b>condição feminina</b> numa sociedade patriarcal, imperial e escravocrata. É uma das primeiras obras de poesia de uma mulher com grande repercussão no Brasil.</p>
<h3>Fique de olho</h3><p>A voz feminina que reivindica espaço na poesia; o engajamento abolicionista e republicano; o diálogo com Castro Alves (condoreirismo) e com Gonçalves Dias (natureza).</p>`+VIDS([['x7pmNBw3HuU','Resumo e análise'],['hyRk4grRmK8','Análise para a FUVEST']],'Nebulosas Narcisa Amália Fuvest'),
{pairs:[['Narcisa Amália','poeta fluminense que publicou Nebulosas aos 20 anos'],['Nebulosas','livro de 44 poemas românticos publicado em 1872'],['Título “Nebulosas”','imagem da névoa e do vago, metáfora da condição da poeta e da mulher'],['Abolicionismo','tema social do livro, ligado à 3ª geração romântica'],['Machado de Assis','escritor que elogiou publicamente o livro']],
 qs:[['Nebulosas se insere em qual estilo de época?','Romantismo',['Parnasianismo','Modernismo','Arcadismo'],'Publicado em 1872, dialoga com as três gerações românticas.'],
  ['A crítica à escravidão em Nebulosas aproxima a obra de qual geração romântica?','a 3ª geração (condoreira), de Castro Alves',['a 1ª geração, indianista','a 2ª geração, ultrarromântica','a geração de 1945'],'Poesia social e abolicionista é marca condoreira.'],
  ['O título Nebulosas sugere:','a névoa e o vago, imagem da condição do eu lírico e da mulher',['o céu estrelado das cidades modernas','a precisão científica da astronomia','a clareza racional do Arcadismo'],'O indefinido, o nebuloso: metáfora existencial e da condição feminina.'],
  ['Quantos poemas reúne Nebulosas?','44',['14','62','9'],'São <b>44</b> poemas.'],
  ['Com quantos anos Narcisa Amália publicou Nebulosas?','20 anos',['40 anos','15 anos','60 anos'],'Nasceu em 1852 e publicou o livro em 1872.'],
  ['Que figura ilustre elogiou Nebulosas em sua época?','Machado de Assis',['Mário de Andrade','Clarice Lispector','Carlos Drummond de Andrade'],'Machado de Assis — e o livro chamou a atenção de D. Pedro II.'],
  ['Além da escravidão, que causa política Narcisa Amália defendeu?','a República',['a volta do Absolutismo','o fim da imprensa','o Integralismo'],'Era republicana e abolicionista.']],
 tf:[['Nebulosas é um romance em prosa.',false,'Falso: é um livro de poemas.'],['Nebulosas dialoga com as três gerações do Romantismo.',true,'Verdadeiro: natureza, melancolia e crítica social.'],['Narcisa Amália é apontada como uma das primeiras jornalistas profissionais do Brasil.',true,'Verdadeiro.']]}),

SKL('martha','Memórias de Martha','🧺','Romance memorialista (folhetim de 1888, livro de 1889) narrado por Martha, que perde o pai, vai morar num cortiço com a mãe engomadeira e busca na educação um caminho de vida.',
BK(BOOKS[2])+`<h3>A autora</h3><p><b>Júlia Lopes de Almeida</b> (1862–1934), carioca, foi uma das escritoras mais lidas de seu tempo. Participou das reuniões que criaram a <b>Academia Brasileira de Letras</b>, mas não foi aceita por ser mulher (a cadeira ficou com o marido, Filinto de Almeida).</p>
<h3>A obra</h3><p>Primeiro romance da autora, saiu em <b>folhetim em 1888</b> (o ano da Abolição) e em <b>livro em 1889</b>. É um romance <b>memorialista</b>: Martha narra a própria vida em <b>1ª pessoa</b>, olhando para trás.</p><ul><li>Com a <b>morte do pai</b>, Martha e a mãe caem na pobreza, são despejadas e vão morar num <b>cortiço</b> do Rio de Janeiro.</li><li>A <b>mãe trabalha como engomadeira</b> para sustentar as duas.</li><li>Martha frequenta a escola; a mestra é <b>D. Aninha</b>. Estudar é o caminho para mudar de vida: o sonho é ser <b>professora</b>.</li><li>Ela se apaixona por <b>Luís</b>, estudante de Medicina e primo de D. Aninha, que se revela vaidoso e instável: abandona Martha e se casa com <b>Leonor</b>, moça rica.</li></ul>
<p>Há traços <b>naturalistas</b> na descrição do cortiço (antes de <i>O Cortiço</i>, de Aluísio Azevedo, 1890) e um olhar atento às <b>mulheres pobres e trabalhadoras</b> do Rio pós-abolição.</p>
<h3>Fique de olho</h3><p>Educação como emancipação; trabalho feminino; classe social e humilhação; o narrador-memorialista (a Martha adulta julga a menina que foi); o diálogo com o <i>Opúsculo humanitário</i>.</p>`+VIDS([['MO0vOcrE5-M','Análise e resumo'],['oj1SVRav8jY','Aula: resumo e contexto']],'Memórias de Martha Júlia Lopes de Almeida Fuvest'),
{pairs:[['Martha','narradora e protagonista, que conta a própria vida em 1ª pessoa'],['Mãe de Martha','engomadeira que sustenta a filha depois da morte do marido'],['Luís','estudante de Medicina que abandona Martha e se casa com Leonor'],['D. Aninha','mestra de Martha na escola'],['Leonor','moça rica com quem Luís se casa'],['Cortiço','habitação coletiva pobre do Rio onde Martha e a mãe vão morar']],
 qs:[['Memórias de Martha é narrado:','em 1ª pessoa, pela própria Martha, que relembra sua vida',['em 3ª pessoa, por um narrador onisciente','por Luís, em cartas','pela mãe de Martha'],'Romance <b>memorialista</b> em 1ª pessoa.'],
  ['O que leva Martha e a mãe a morarem num cortiço?','a morte do pai e a pobreza que se segue',['uma herança mal administrada por Luís','o casamento de Martha','uma enchente no Rio de Janeiro'],'Sem o pai, são despejadas por não pagarem o aluguel.'],
  ['Como a mãe de Martha sustenta a família?','trabalhando como engomadeira',['como professora','como costureira da corte','como dona de pensão'],'Ela passa roupas para fora: <b>engomadeira</b>.'],
  ['Na trajetória de Martha, a educação representa:','um caminho de mudança de vida e de autonomia',['uma perda de tempo','um privilégio que ela recusa','uma imposição do marido'],'Martha estuda para ser professora.'],
  ['Luís, por quem Martha se apaixona:','a abandona e se casa com Leonor, moça rica',['torna-se professor da escola','é o pai de Martha','morre no cortiço'],'Estudante de Medicina, vaidoso e instável.'],
  ['A descrição do cortiço aproxima o romance de qual estética?','o Naturalismo',['o Arcadismo','o Simbolismo','o Concretismo'],'Ambiente degradado, influência do meio: traços naturalistas.'],
  ['Em que ano Memórias de Martha saiu em folhetim?','1888, o ano da Abolição',['1822, o ano da Independência','1922, o ano da Semana de Arte Moderna','1964, o ano do golpe militar'],'Folhetim em 1888; livro em 1889.'],
  ['Que obra de Aluísio Azevedo, publicada depois, também tem um cortiço como espaço central?','O Cortiço',['O Guarani','Dom Casmurro','Vidas Secas'],'<i>O Cortiço</i> é de 1890.']],
 tf:[['Júlia Lopes de Almeida foi uma das fundadoras oficiais da Academia Brasileira de Letras.',false,'Falso: participou das reuniões, mas foi excluída por ser mulher.'],['Martha sonha em ser professora.',true,'Verdadeiro.'],['O romance se passa no Rio de Janeiro.',true,'Verdadeiro.']]}),

SKL('pedras','Caminho de pedras','🪨','Romance engajado (1937) em Fortaleza, nos anos 1930: Noemi deixa o casamento com João Jacques para viver com Roberto, militante de esquerda, e enfrenta preconceito, perdas e repressão.',
BK(BOOKS[3])+`<h3>A autora</h3><p><b>Rachel de Queiroz</b> (1910–2003), cearense, estreou com <i>O Quinze</i> (1930) e foi a <b>primeira mulher eleita para a Academia Brasileira de Letras</b> (1977). Militou no Partido Comunista no início dos anos 1930 e rompeu com ele.</p>
<h3>A obra</h3><p>Romance da <b>geração de 1930</b> (2ª fase do Modernismo), de cunho <b>social e político</b>, considerado o livro mais engajado da autora. Passa-se em <b>Fortaleza</b>, na <b>Era Vargas</b>, entre operários e militantes de esquerda.</p><ul><li><b>Noemi</b> é casada com <b>João Jacques</b>, homem bondoso e ex-militante, e mãe de um menino chamado apenas <b>Guri</b>.</li><li>Ela conhece <b>Roberto</b>, militante encarregado de organizar operários numa célula do partido, e os dois se apaixonam.</li><li>Noemi <b>rompe o casamento</b> e enfrenta o julgamento moral da sociedade e até dos companheiros de militância.</li><li><b>Guri morre</b> de uma febre repentina.</li><li>Roberto é <b>preso</b> ao tentar proteger Noemi, que distribuía boletins. Ela é solta por estar <b>grávida</b>; ele é mandado para o Sul, e os dois perdem o contato.</li></ul>
<h3>Fique de olho</h3><p>A <b>condição da mulher</b> dentro de um movimento que se diz revolucionário (o machismo persiste também ali); militância, repressão e pobreza; a linguagem direta e seca da autora; o título, que resume a trajetória de perdas de Noemi.</p>`+VIDS([['M0m1WEZvV3g','Resumo + questão comentada'],['N7sIcUX_rO8','Análise e resumo']],'Caminho de pedras Rachel de Queiroz Fuvest'),
{pairs:[['Noemi','protagonista que deixa o casamento para viver com um militante'],['João Jacques','marido de Noemi, homem bondoso e ex-militante'],['Roberto','militante de esquerda que organiza os operários e se apaixona por Noemi'],['Guri','filho pequeno de Noemi, que morre de febre'],['Fortaleza','cidade onde se passa o romance, nos anos 1930']],
 qs:[['Onde e quando se passa Caminho de pedras?','em Fortaleza, nos anos 1930 (Era Vargas)',['no Rio de Janeiro, no Segundo Reinado','no sertão, durante a seca de 1915','em São Paulo, na década de 1960'],'Capital do Ceará, meio operário e militante dos anos 1930.'],
  ['Qual é o conflito amoroso central do romance?','Noemi deixa o marido, João Jacques, para viver com Roberto, militante do partido.',['Roberto disputa Noemi com um fazendeiro.','João Jacques abandona Noemi por outra mulher.','Guri se opõe ao casamento da mãe.'],'O triângulo Noemi–João Jacques–Roberto.'],
  ['Que crítica o romance faz ao meio militante que retrata?','mesmo entre revolucionários persistem o moralismo e o machismo contra a mulher',['os militantes eram todos ricos','o partido defendia a monarquia','os operários desprezavam a política'],'Noemi é julgada até pelos companheiros de luta.'],
  ['O que acontece com Guri, filho de Noemi?','morre de uma febre repentina',['é criado por João Jacques no Sul','torna-se militante','é levado pela polícia'],'A morte do filho é uma das grandes perdas de Noemi.'],
  ['No desfecho, Roberto:','é preso e mandado para o Sul, e perde o contato com Noemi',['torna-se prefeito de Fortaleza','volta para João Jacques','foge com Noemi para a Europa'],'Ele é preso ao proteger Noemi; ela é solta por estar grávida.'],
  ['Caminho de pedras pertence a qual momento da literatura brasileira?','romance de 1930 (2ª fase do Modernismo), de caráter social',['Arcadismo','Romantismo indianista','Parnasianismo'],'Geração de 1930, a mesma de <i>O Quinze</i> e <i>Vidas Secas</i>.'],
  ['Rachel de Queiroz foi a primeira mulher a:','ser eleita para a Academia Brasileira de Letras',['ganhar o Prêmio Nobel','presidir o Brasil','fundar a FUVEST'],'Eleita em 1977.']],
 tf:[['Caminho de pedras é o romance de estreia de Rachel de Queiroz.',false,'Falso: a estreia foi O Quinze (1930).'],['Noemi é solta da prisão por estar grávida.',true,'Verdadeiro.'],['O romance trata de militância política e da condição da mulher.',true,'Verdadeiro.']]}),

SKL('gh','A paixão segundo G.H.','🪳','Romance (1964) narrado em 1ª pessoa por G.H., escultora de classe alta, que entra no quarto da empregada que foi embora, esmaga uma barata e vive uma crise que desmonta sua identidade.',
BK(BOOKS[4])+`<h3>A autora</h3><p><b>Clarice Lispector</b> (1920–1977) nasceu na Ucrânia e veio criança para o Brasil. É o grande nome da prosa <b>intimista</b> e <b>introspectiva</b> da geração de 1945, com romances como <i>Perto do coração selvagem</i> e <i>A hora da estrela</i>.</p>
<h3>A obra</h3><ul><li><b>G.H.</b> (só as iniciais, gravadas nas malas) é uma <b>escultora</b> de classe alta que mora sozinha numa <b>cobertura</b> no Rio de Janeiro.</li><li>Depois que a empregada <b>Janair</b> vai embora, G.H. decide arrumar o <b>quarto de empregada</b>, esperando encontrar sujeira. Encontra-o limpo e seco, com um <b>desenho a carvão na parede</b>: um homem, uma mulher e um cão. Percebe que nunca prestou atenção em Janair.</li><li>No guarda-roupa, vê uma <b>barata</b> e a esmaga com a porta. Diante da massa branca que sai do inseto, vive uma experiência de desagregação do “eu” e acaba <b>pondo essa massa na boca</b>.</li><li>A narração, em <b>1ª pessoa</b>, é um fluxo de pensamento dirigido a um interlocutor imaginário, a quem G.H. pede que lhe segure a mão.</li></ul>
<h3>Recursos e temas</h3><p><b>Epifania</b> (revelação súbita a partir de um fato banal); <b>fluxo de consciência</b>; perda da identidade social (“despersonalização”); a busca do que é vivo e “neutro”; os limites da linguagem para dizer a experiência; a relação <b>patroa × empregada</b> (classe e raça). O título dialoga com a <b>Paixão de Cristo</b> narrada nos Evangelhos. O livro começa e termina com travessões, e cada capítulo retoma a frase final do anterior.</p>`+VIDS([['yKxrNRAaeiU','Aula: resumo e análise'],['zF31oYsQpGE','Análise da obra']],'A paixão segundo G.H. Clarice Lispector Fuvest'),
{pairs:[['G.H.','narradora-protagonista, escultora de classe alta identificada só pelas iniciais'],['Janair','empregada que foi embora e deixou um desenho na parede do quarto'],['A barata','inseto esmagado por G.H., centro da experiência de desagregação do “eu”'],['Epifania','revelação súbita a partir de um fato banal'],['Desenho na parede','figuras de um homem, uma mulher e um cão, feitas a carvão por Janair']],
 qs:[['Quem narra A paixão segundo G.H.?','a própria G.H., em 1ª pessoa',['um narrador onisciente em 3ª pessoa','a empregada Janair','um detetive que investiga G.H.'],'Narradora-protagonista em fluxo de pensamento.'],
  ['O que desencadeia a crise de G.H.?','a entrada no quarto da empregada e o encontro com uma barata',['a morte do marido','uma viagem ao sertão','a perda do emprego'],'Um fato banal provoca a revelação: <b>epifania</b>.'],
  ['O que G.H. encontra no quarto de Janair?','o quarto limpo e um desenho a carvão na parede: um homem, uma mulher e um cão',['o quarto sujo e cheio de objetos roubados','cartas de amor de Janair','uma escultura quebrada'],'Ela esperava sujeira e encontra ordem — e percebe que nunca olhou de verdade para Janair.'],
  ['Qual a profissão de G.H.?','escultora',['professora','médica','jornalista'],'Mora sozinha numa cobertura no Rio de Janeiro.'],
  ['A epifania, recurso central de Clarice Lispector, é:','uma revelação súbita provocada por um fato banal do cotidiano',['uma rima entre versos','um diálogo entre dois narradores','a descrição objetiva de uma paisagem'],'Na obra, o encontro com a barata.'],
  ['A relação entre G.H. e Janair permite discutir:','diferenças de classe e raça entre patroa e empregada',['a vida no campo','a política partidária dos anos 1930','a colonização da África'],'G.H. se dá conta de que nunca viu Janair de fato.'],
  ['O título A paixão segundo G.H. dialoga com:','os relatos da Paixão de Cristo nos Evangelhos',['a Carta de Pero Vaz de Caminha','os Sermões do Padre Vieira','a Canção do exílio'],'“Paixão segundo…” ecoa “Evangelho segundo…”, sugerindo uma experiência de sofrimento e revelação.'],
  ['A narração de G.H. se dirige a:','um interlocutor imaginário, a quem ela pede que segure sua mão',['um juiz num tribunal','os leitores de um jornal','Janair, por carta'],'O “tu” imaginário acompanha a travessia da narradora.']],
 tf:[['G.H. é o nome completo da narradora.',false,'Falso: são só as iniciais, gravadas em suas malas.'],['A narrativa acontece quase toda num só espaço: o quarto de empregada.',true,'Verdadeiro.'],['Clarice Lispector é representante da prosa intimista e introspectiva.',true,'Verdadeiro.']]}),

SKL('geografia','Geografia (Sophia Andresen)','🌊','Livro de poemas (1967) da portuguesa Sophia de Mello Breyner Andresen: mar, luz, natureza purificadora, casa e infância, Grécia e Brasil, em 60 poemas divididos em sete partes.',
BK(BOOKS[5])+`<h3>A autora</h3><p><b>Sophia de Mello Breyner Andresen</b> (1919–2004), nascida no Porto, é uma das maiores poetas de língua portuguesa. Opôs-se à ditadura salazarista e foi a <b>primeira mulher a receber o Prêmio Camões</b> (1999). Sua poesia valoriza a <b>clareza</b>, a <b>luz</b>, o <b>mar</b> e a busca de justiça.</p>
<h3>A obra</h3><p>Publicado em 1967, reúne <b>60 poemas</b> em <b>sete partes</b>: <i>Ingrina</i>, <i>Procelária</i>, <i>A noite e a casa</i>, <i>Dual</i>, <i>Mediterrâneo</i>, <i>Brasil ou do outro lado do mar</i> e <i>No poema</i>.</p><ul><li><b>Natureza purificadora</b> em oposição à cidade; o <b>mar</b> e a <b>luz</b> como espaço de verdade e plenitude.</li><li>A <b>casa</b>, a <b>infância</b> e pessoas lembradas.</li><li>A <b>Grécia</b>: a viagem de 1963 marca a parte <i>Mediterrâneo</i> (mundo clássico, deuses, harmonia).</li><li>O <b>Brasil</b>, visto “do outro lado do mar”.</li><li>A reflexão sobre o próprio fazer poético (<i>No poema</i>).</li></ul>
<p>O título sugere uma poesia que <b>mapeia lugares</b> — reais e interiores — e liga espaço, memória e ética.</p>
<h3>Fique de olho</h3><p>Relação entre paisagem e dimensão humana; linguagem límpida e concreta; o mar como herança portuguesa; o diálogo com o Brasil e com a Grécia antiga.</p>`+VIDS([['9XLOalt4CWA','Aula: resumo e análise'],['2ofEuLBMfTc','Análise completa']],'Geografia Sophia de Mello Breyner Andresen Fuvest'),
{pairs:[['Sophia de Mello Breyner Andresen','poeta portuguesa, primeira mulher a receber o Prêmio Camões'],['Mediterrâneo','parte do livro ligada à Grécia e ao mundo clássico'],['Brasil ou do outro lado do mar','parte do livro dedicada ao Brasil'],['No poema','parte do livro que reflete sobre o próprio fazer poético'],['O mar','imagem central da poesia de Sophia, espaço de luz e plenitude']],
 qs:[['Geografia é um livro de:','poemas',['contos','crônicas jornalísticas','ensaios científicos'],'São 60 poemas.'],
  ['Qual a nacionalidade de Sophia de Mello Breyner Andresen?','portuguesa',['brasileira','moçambicana','angolana'],'Nasceu no Porto, em 1919.'],
  ['Em quantas partes se divide Geografia?','sete',['duas','doze','nove'],'Ingrina, Procelária, A noite e a casa, Dual, Mediterrâneo, Brasil ou do outro lado do mar e No poema.'],
  ['A viagem de Sophia à Grécia, em 1963, marca sobretudo a parte:','Mediterrâneo',['Ingrina','A noite e a casa','No poema'],'O mundo grego clássico aparece em <i>Mediterrâneo</i>.'],
  ['Na poesia de Geografia, a natureza costuma aparecer como:','espaço purificador, de luz e plenitude, em oposição à cidade',['cenário de terror e ameaça constante','simples pano de fundo sem importância','mercadoria a ser explorada'],'Mar, luz e natureza são espaços de verdade.'],
  ['Sophia foi a primeira mulher a receber:','o Prêmio Camões',['o Nobel de Literatura','o Prêmio Jabuti','uma cadeira na Academia Brasileira de Letras'],'Prêmio Camões de 1999.'],
  ['Qual parte do livro aborda o Brasil?','Brasil ou do outro lado do mar',['Procelária','Dual','Ingrina'],'O Brasil é visto “do outro lado do mar”.']],
 tf:[['Sophia de Mello Breyner Andresen apoiou a ditadura de Salazar.',false,'Falso: opôs-se ao regime.'],['O mar é uma imagem central da poesia de Sophia.',true,'Verdadeiro.'],['Geografia foi publicado em 1967.',true,'Verdadeiro.']]}),

SKL('balada','Balada de amor ao vento','🌬️','Primeiro romance publicado por uma mulher em Moçambique (1990): Sarnau narra seu amor por Mwando, o casamento poligâmico com Nguila e as marcas da tradição e do colonialismo na vida das mulheres.',
BK(BOOKS[6])+`<h3>A autora</h3><p><b>Paulina Chiziane</b> (1955), moçambicana, foi a <b>primeira mulher a publicar um romance em Moçambique</b> — justamente <i>Balada de amor ao vento</i> — e a primeira mulher africana a receber o <b>Prêmio Camões</b> (2021).</p>
<h3>A obra</h3><p>A narradora é <b>Sarnau</b>, mulher de uma aldeia do <b>sul de Moçambique</b>, no período colonial, que conta sua história em <b>1ª pessoa</b>.</p><ul><li>Jovem, Sarnau se apaixona por <b>Mwando</b>, rapaz que estudava para ser <b>padre</b> e que acaba correspondendo ao seu amor. Ele a abandona para se casar com outra mulher, escolhida para ele.</li><li>Sarnau se casa com <b>Nguila</b>, da família real, e se torna a primeira de suas esposas, num casamento <b>poligâmico</b>. O <b>lobolo</b> (o dote pago pela família do noivo) é alto: <b>36 vacas</b>.</li><li>Sofre violência e é preterida por outras esposas. Reencontra Mwando, tem um filho com ele e é novamente abandonada.</li><li>Mwando é <b>deportado para Angola</b>, para trabalho forçado nas roças coloniais, e volta transformado; os dois se reencontram anos depois.</li></ul>
<h3>Fique de olho</h3><p>A <b>poligamia</b> vista pela mulher; o <b>lobolo</b> e a mulher tratada como propriedade; tradição × cristianismo e colonialismo; a oralidade (o título: uma “balada”, um canto levado pelo vento); o desejo feminino num mundo que não o autoriza.</p>`+VIDS([['4Z3hPFXco1c','Aula: resumo e análise'],['G4B_0HzKvnU','Resumo do livro']],'Balada de amor ao vento Paulina Chiziane Fuvest'),
{pairs:[['Sarnau','narradora-protagonista, mulher do sul de Moçambique'],['Mwando','amor de Sarnau, que estudava para ser padre e a abandona'],['Nguila','homem da família real com quem Sarnau se casa num casamento poligâmico'],['Lobolo','dote pago pela família do noivo à família da noiva, em gado'],['Poligamia','casamento de um homem com várias esposas, tema central do livro']],
 qs:[['Quem narra Balada de amor ao vento?','Sarnau, em 1ª pessoa',['Mwando, em cartas','um narrador onisciente','Nguila, já idoso'],'A voz feminina conta a própria trajetória.'],
  ['Balada de amor ao vento tem importância histórica por ser:','o primeiro romance publicado por uma mulher em Moçambique',['o primeiro livro escrito em língua portuguesa','o último romance do período colonial','uma tradução de um épico africano'],'Publicado em 1990.'],
  ['O lobolo, presente no romance, é:','o dote pago pela família do noivo à família da noiva, geralmente em gado',['uma dança de casamento','um tipo de oração cristã','o nome da aldeia de Sarnau'],'No livro, o lobolo de Sarnau é de 36 vacas.'],
  ['O casamento de Sarnau com Nguila é:','poligâmico: ela é a primeira de várias esposas',['monogâmico e feliz','um casamento cristão celebrado por Mwando','um casamento sem lobolo'],'A poligamia é mostrada do ponto de vista da mulher.'],
  ['Mwando, amor de Sarnau, é um jovem que:','estudava para ser padre',['era rei da aldeia','era comerciante português','era soldado colonial'],'O cristianismo trazido pela colonização atravessa sua trajetória.'],
  ['Que marca do colonialismo aparece na trajetória de Mwando?','a deportação para trabalho forçado nas roças de Angola',['a construção de ferrovias no Brasil','a guerra contra a França','o exílio em Londres'],'O trabalho forçado era prática do colonialismo português.'],
  ['Paulina Chiziane foi a primeira mulher africana a receber:','o Prêmio Camões',['o Prêmio Nobel da Paz','a presidência de Moçambique','uma cadeira na Academia Brasileira de Letras'],'Prêmio Camões de 2021.']],
 tf:[['Balada de amor ao vento se passa no norte de Portugal.',false,'Falso: no sul de Moçambique, no período colonial.'],['O romance critica a condição da mulher em práticas como a poligamia e o lobolo.',true,'Verdadeiro.'],['Sarnau tem um filho com Mwando.',true,'Verdadeiro.']]}),

SKL('cancao','Canção para ninar menino grande','🎶','Romance (2018) sobre Fio Jasmim, homem negro que trabalha nos trens e se relaciona com muitas mulheres; sua história é contada pelas vozes delas, reunidas por uma narradora.',
BK(BOOKS[7])+`<h3>A autora</h3><p><b>Conceição Evaristo</b> (1946), mineira de Belo Horizonte, é um dos grandes nomes da literatura afro-brasileira contemporânea. Criou o conceito de <b>escrevivência</b>: uma escrita que nasce da experiência de vida e da memória coletiva, sobretudo das <b>mulheres negras</b>. Também é autora de <i>Ponciá Vicêncio</i> e <i>Olhos d’água</i>.</p>
<h3>A obra</h3><p>Publicada em 2018 (editora Unipalmares) e reeditada depois, é uma narrativa curta e <b>polifônica</b>, feita de fragmentos.</p><ul><li><b>Fio Jasmim</b> é um homem negro, bonito e sedutor, que trabalha nos <b>trens</b> e se relaciona com várias mulheres pelas cidades por onde passa a linha férrea.</li><li>Sua história é contada a partir das <b>vozes das mulheres</b> que o amaram, recolhidas por uma <b>narradora</b> que também faz parte desse círculo de amigas.</li><li>Na infância, Fio Jasmim sofre <b>racismo</b>: é recusado para o papel de príncipe numa peça da escola por ser negro.</li><li><b>Juventina (Tina)</b>, que viveu uma longa relação com ele, compõe a “canção para ninar menino grande” e a oferece a Fio Jasmim ao pôr fim à relação.</li></ul>
<h3>Fique de olho</h3><p><b>Masculinidade negra</b> e os efeitos do racismo e do patriarcado; o afeto e o desejo das mulheres negras; a rede de solidariedade entre as mulheres; a <b>escrevivência</b>; o título (o homem adulto tratado como “menino” a ser ninado).</p>`+VIDS([['-8e_D9pGMV4','Resumo para o vestibular']],'Canção para ninar menino grande Conceição Evaristo Fuvest'),
{pairs:[['Fio Jasmim','protagonista, homem negro que trabalha nos trens e se relaciona com muitas mulheres'],['Juventina (Tina)','mulher que compõe a canção e a oferece a Fio Jasmim ao encerrar a relação'],['Escrevivência','escrita que nasce da experiência de vida e da memória coletiva de mulheres negras'],['Narradora','amiga que recolhe e organiza as vozes das mulheres'],['Polifonia','construção da narrativa a partir de muitas vozes']],
 qs:[['Quem é Fio Jasmim?','um homem negro que trabalha nos trens e se relaciona com várias mulheres',['um fazendeiro do século XIX','um padre de uma aldeia moçambicana','um estudante de Medicina'],'O trem permite que ele passe por várias cidades e relações.'],
  ['Como a história de Fio Jasmim é contada?','pelas vozes das mulheres que se relacionaram com ele, reunidas por uma narradora',['pelo próprio Fio Jasmim, num diário','por um narrador onisciente e distante','por meio de notícias de jornal'],'A narrativa é <b>polifônica</b>.'],
  ['O conceito de escrevivência, criado por Conceição Evaristo, refere-se a:','uma escrita que nasce da vivência e da memória coletiva de mulheres negras',['um movimento de poesia concreta dos anos 1950','a escrita automática surrealista','a literatura de viagem portuguesa'],'Escrita + vivência.'],
  ['Que episódio de infância mostra o racismo sofrido por Fio Jasmim?','ser recusado para o papel de príncipe numa peça escolar por ser negro',['ser expulso do trem','perder o pai na guerra','ser proibido de estudar música'],'O episódio ajuda a entender a construção de sua masculinidade.'],
  ['Juventina (Tina) oferece a “canção para ninar menino grande” a Fio Jasmim:','quando decide encerrar a longa relação com ele',['no dia do casamento dos dois','no enterro de Fio Jasmim','para vendê-la a uma rádio'],'A canção é também despedida.'],
  ['O título “Canção para ninar menino grande” sugere:','o homem adulto visto como um menino a ser acalentado',['uma coletânea de cantigas de roda','um manual de música para crianças','um romance de aventura juvenil'],'Ironia e ternura na forma como as mulheres olham para Fio Jasmim.'],
  ['Qual destes temas é central na obra?','masculinidade negra, racismo e afeto de mulheres negras',['a colonização da Grécia','a vida na corte portuguesa','a Revolução Francesa'],'Gênero e raça se cruzam no romance.']],
 tf:[['A narrativa de Canção para ninar menino grande é construída por muitas vozes femininas.',true,'Verdadeiro.'],['Conceição Evaristo é autora de Ponciá Vicêncio.',true,'Verdadeiro.'],['Fio Jasmim narra a história em 1ª pessoa.',false,'Falso: a história é contada pelas mulheres, reunidas por uma narradora.']]}),

SKL('plantas','A visão das plantas','🌹','Novela (2019) sobre o capitão Celestino, antigo comandante de navio negreiro que volta velho à casa da infância, em Portugal, e se dedica ao jardim, sem remorso aparente pelos crimes do passado.',
BK(BOOKS[8])+`<h3>A autora</h3><p><b>Djaimilia Pereira de Almeida</b> (1982) nasceu em Luanda (Angola) e cresceu em Portugal. Sua obra discute identidade, colonialismo e memória, com uma prosa de frases muito trabalhadas.</p>
<h3>A obra</h3><ul><li><b>Celestino</b> é um velho <b>capitão</b> que passou a vida no mar, envolvido no <b>tráfico de escravizados</b> e em atos de enorme violência.</li><li>Ele volta à <b>casa da infância</b>, a casa da mãe, em Portugal, e passa os últimos anos cuidando do <b>jardim</b> com delicadeza.</li><li>O <b>padre Alfredo</b> o visita e quer levá-lo à <b>confissão</b>, mas Celestino só se interessa pelas plantas, sobretudo pelas <b>rosas</b>. Os vizinhos o temem e comentam seu passado.</li><li>O personagem foi tirado de uma passagem de <i>Os pescadores</i>, do escritor português <b>Raul Brandão</b>.</li></ul>
<h3>Fique de olho</h3><p>A convivência entre <b>beleza e horror</b>; a natureza <b>indiferente à moral</b>; culpa, silêncio e ausência de arrependimento; o <b>jardim como metáfora</b> da violência colonial que se esconde sob a aparência de cuidado; o diálogo com Raul Brandão e com a memória do colonialismo português.</p>`+VIDS([['AtueyUfThKc','Análise e resumo']],'A visão das plantas Djaimilia Pereira de Almeida Fuvest'),
{pairs:[['Celestino','velho capitão de navio negreiro que se dedica ao jardim'],['Padre Alfredo','visitante que tenta levar Celestino à confissão'],['O jardim','espaço de cuidado que contrasta com a violência do passado do capitão'],['Raul Brandão','escritor português de Os pescadores, de onde veio o personagem'],['As rosas','plantas que mais interessam ao capitão']],
 qs:[['Qual era a atividade de Celestino no passado?','comandante de navio no tráfico de escravizados',['jardineiro de um palácio','padre missionário','médico de bordo'],'Um passado de violência brutal.'],
  ['Ao voltar à casa da infância, Celestino:','passa a cuidar com delicadeza do jardim',['confessa todos os crimes ao padre','funda uma escola','entrega-se à polícia'],'O contraste entre cuidado e violência é o centro da obra.'],
  ['O padre Alfredo quer que Celestino:','se confesse',['venda a casa','volte ao mar','escreva suas memórias'],'Mas Celestino só quer falar das plantas.'],
  ['De onde a autora tirou o personagem Celestino?','de uma passagem de Os pescadores, de Raul Brandão',['de uma notícia de jornal angolano','da Bíblia','de um romance de Machado de Assis'],'Diálogo com a tradição literária portuguesa.'],
  ['O jardim, na obra, pode ser lido como:','metáfora de um cuidado que convive com a violência colonial não reconhecida',['símbolo da riqueza agrícola de Angola','espaço de festas da aldeia','cenário de uma história de amor'],'Beleza e horror convivem; a natureza parece indiferente à moral.'],
  ['Djaimilia Pereira de Almeida nasceu em:','Luanda, Angola, e cresceu em Portugal',['Maputo, Moçambique','Salvador, Brasil','Lisboa, e nunca saiu de lá'],'Nascida em 1982.'],
  ['Qual é a atitude de Celestino diante de seu passado?','silêncio e ausência de arrependimento aparente',['arrependimento público e reparação às vítimas','orgulho declarado em discursos na praça','esquecimento por doença'],'A obra explora essa ausência de culpa.']],
 tf:[['Celestino se arrepende e se confessa ao padre Alfredo.',false,'Falso: ele se recusa e só se interessa pelas plantas.'],['A visão das plantas discute a memória do colonialismo português.',true,'Verdadeiro.'],['O personagem foi inspirado em Os pescadores, de Raul Brandão.',true,'Verdadeiro.']]})
]};

/* Interpretação entra depois de “Sentido e texto”; a lista da FUVEST fecha a trilha. As duas unidades ficam liberadas desde o início */
UNITS.splice(UNITS.findIndex(u=>u.id==='p4')+1,0,UNIT_INTERP);
UNITS.push(UNIT_LIVROS);
GLOSS.push(...autoGloss([UNIT_INTERP,UNIT_LIVROS],[
 {k:['fuvest livros','leituras obrigatorias','livros da fuvest','lista da fuvest'],n:'Leituras obrigatórias da FUVEST',s:'livros',t:'FUVEST 2027: Opúsculo humanitário (Nísia Floresta), Nebulosas (Narcisa Amália), Memórias de Martha (Júlia Lopes de Almeida), Caminho de pedras (Rachel de Queiroz), A paixão segundo G.H. (Clarice Lispector), Geografia (Sophia de Mello Breyner Andresen), Balada de amor ao vento (Paulina Chiziane), Canção para ninar menino grande (Conceição Evaristo) e A visão das plantas (Djaimilia Pereira de Almeida).'},
 {k:['interpretacao','interpretacao de texto','inferencia','pressuposto'],n:'Interpretação de texto',s:'ideia',t:'Leia a pergunta primeiro e apoie a resposta no texto. Evite alternativas que extrapolam, reduzem ou contradizem o texto.'}]));
