
/* =====================================================================
   FisLingo v2 — novas habilidades e cartões de memória
   ===================================================================== */
function leverSVG(l,r){ return SV(300,130,`<polygon points="150,110 135,128 165,128" fill="#a568cc"/><rect x="20" y="102" width="260" height="8" rx="4" fill="#ff9600"/>${l?`<rect x="30" y="72" width="40" height="30" rx="4" fill="#ddf4ff" stroke="#1899d6" stroke-width="3"/><text x="50" y="92" text-anchor="middle" font-size="13" fill="#1899d6">${l}</text>`:''}${r?`<rect x="230" y="72" width="40" height="30" rx="4" fill="#ffdfe0" stroke="#ea2b2b" stroke-width="3"/><text x="250" y="92" text-anchor="middle" font-size="13" fill="#ea2b2b">${r}</text>`:''}`); }
function springSVG(){ let d='M20,60'; for(let i=0;i<10;i++) d+=` L${30+i*14},${i%2?72:48}`; d+=' L175,60 L190,60'; return SV(300,110,`<rect x="6" y="20" width="14" height="80" fill="#777"/><path d="${d}" fill="none" stroke="#1899d6" stroke-width="3"/><rect x="190" y="38" width="50" height="44" rx="5" fill="#fff4d6" stroke="#ff9600" stroke-width="3"/><text x="215" y="66" text-anchor="middle" font-size="14" fill="#e07b00">m</text><line x1="0" y1="100" x2="300" y2="100" stroke="#777" stroke-width="3"/>`); }

insertSkill('f3','grav',{id:'estatica',name:'Estática e alavancas',icon:'⚖️',tip:'Momento (torque) = F·d. Equilíbrio de alavanca: F₁·d₁ = F₂·d₂. Corpo extenso em equilíbrio: força resultante e momento resultante nulos.',
theory:`<div class="formula">M = F · d</div><p>d é a distância (braço) da linha da força até o ponto de apoio. Unidade: N·m.</p>
<h3>Alavanca em equilíbrio</h3><div class="formula">F<sub>1</sub> · d<sub>1</sub> = F<sub>2</sub> · d<sub>2</sub></div><div class="ex">Gangorra: criança de 20 kg a 3 m equilibra um adulto de 60 kg a 1 m do apoio.</div>
<h3>Condições de equilíbrio</h3><ul><li>Ponto material: força resultante nula.</li><li>Corpo extenso: força resultante nula <b>e</b> momento resultante nulo.</li></ul>
<h3>Centro de massa</h3><div class="formula">x<sub>cm</sub> = ${F('m₁x₁ + m₂x₂','m₁ + m₂')}</div>`,
gens:[
 lv=>{const F=R(2,50)*2,d=pick([0.2,0.5,1,1.5,2]);return NUM(`Uma força de <b>${F} N</b> é aplicada perpendicularmente a <b>${fmt(d)} m</b> do eixo de uma porta. Qual o momento (torque)?`,F*d,`M = F·d = ${F}·${fmt(d)} = <b>${fmt(F*d)} N·m</b>.`,'Torque = força × distância ao eixo.',{unit:'N·m'});},
 lv=>{const m1=pick([20,25,30,40]),d1=pick([1,1.5,2,3]),m2=pick([40,50,60,75,80]);return NUM(`Numa gangorra, uma criança de <b>${m1} kg</b> senta a <b>${fmt(d1)} m</b> do apoio. A que distância do apoio deve sentar um adulto de <b>${m2} kg</b> para equilibrar?`,m1*d1/m2,`${m1}·${fmt(d1)} = ${m2}·d → d = <b>${fmt(round(m1*d1/m2,3))} m</b>.`,'Iguale os momentos dos dois lados.',{unit:'m',keys:[','],tol:0.01,visual:leverSVG(m1+' kg',m2+' kg')});},
 lv=>{const F1=R(2,20)*10,d1=pick([0.1,0.2,0.25,0.5]),d2=pick([1,1.5,2]);return NUM(`Numa alavanca, uma carga de <b>${F1} N</b> está a <b>${fmt(d1)} m</b> do apoio. Qual força mínima aplicar a <b>${fmt(d2)} m</b> do apoio, do outro lado, para equilibrá-la?`,F1*d1/d2,`F·${fmt(d2)} = ${F1}·${fmt(d1)} → F = <b>${fmt(round(F1*d1/d2,3))} N</b>.`,'Braço maior → força menor.',{unit:'N',keys:[','],tol:0.01});},
 lv=>{const m1=R(1,6),m2=R(1,6),x2=pick([2,3,4,6]);return NUM(`Duas massas de <b>${m1} kg</b> (em x = 0) e <b>${m2} kg</b> (em x = ${x2} m) estão numa barra leve. Onde fica o centro de massa?`,m2*x2/(m1+m2),`x<sub>cm</sub> = ${F(`${m1}·0 + ${m2}·${x2}`,`${m1} + ${m2}`)} = <b>${fmt(round(m2*x2/(m1+m2),3))} m</b>.`,'Média das posições ponderada pelas massas.',{unit:'m',keys:[','],tol:0.01});},
 lv=>{const q=pick([['Para um corpo extenso ficar em equilíbrio é preciso:','força resultante nula e momento resultante nulo',['apenas força resultante nula','apenas momento nulo','velocidade constante']],['Maçanetas ficam longe das dobradiças porque:','um braço maior exige menos força para o mesmo torque',['a porta fica mais leve','diminui o atrito','aumenta a massa']],['Uma tesoura é um exemplo de alavanca com o apoio:','entre a força e a resistência (interfixa)',['na ponta','fora da alavanca','sobre a resistência']]]);return MC(q[0],q[1],q[2],`${q[0]} <b>${q[1]}</b>.`,'Revise a aula de estática.');},
]});
insertSkill('f4','hidro',{id:'hidrodin',name:'Hidrodinâmica (vazão)',icon:'🚰',tip:'Vazão Q = V/Δt = A·v. Continuidade: A₁·v₁ = A₂·v₂ (onde o cano afina, o fluido acelera). Bernoulli: mais velocidade → menos pressão.',
theory:`<div class="formula">Q = ${F('V','Δt')} = A · v</div><p>Vazão em m³/s ou L/s (1 m³ = 1000 L).</p>
<h3>Equação da continuidade</h3><div class="formula">A<sub>1</sub> · v<sub>1</sub> = A<sub>2</sub> · v<sub>2</sub></div><p>Apertar a ponta da mangueira (menor área) faz a água sair mais rápido.</p>
<h3>Bernoulli</h3><p>Num fluido em movimento, onde a velocidade é maior a pressão é menor — é o que ajuda a sustentar a asa do avião.</p>`,
gens:[
 lv=>{const Q=pick([0.5,1,2,5,10]),t=R(2,30)*10;return NUM(`Uma torneira enche <b>${fmt(Q*t)} L</b> em <b>${t} s</b>. Qual a vazão?`,Q,`Q = V/Δt = ${fmt(Q*t)}/${t} = <b>${fmt(Q)} L/s</b>.`,'Vazão = volume ÷ tempo.',{unit:'L/s',keys:[',']});},
 lv=>{const Q=pick([2,4,5,10,20]),V=pick([200,500,1000,2000]);return NUM(`Uma caixa-d'água de <b>${nf(V)} L</b> é enchida por uma mangueira de vazão <b>${Q} L/min</b>. Quanto tempo leva, em minutos?`,V/Q,`t = V/Q = ${nf(V)}/${Q} = <b>${nf(V/Q)} min</b>.`,'Tempo = volume ÷ vazão.',{unit:'min'});},
 lv=>{const A1=pick([4,6,8,10]),k=pick([2,4]),v1=R(1,5);return NUM(`Água flui a <b>${v1} m/s</b> num cano de <b>${A1} cm²</b> de seção, que afina para <b>${A1/k} cm²</b>. Qual a velocidade no trecho estreito?`,v1*k,`A₁v₁ = A₂v₂ → ${A1}·${v1} = ${fmt(A1/k)}·v₂ → v₂ = <b>${v1*k} m/s</b>.`,'Continuidade: área menor → velocidade maior.',{unit:'m/s'});},
 lv=>{const A=pick([0.01,0.02,0.05]),v=R(1,5);return NUM(`Um cano de seção <b>${fmt(A)} m²</b> conduz água a <b>${v} m/s</b>. Qual a vazão em <b>L/s</b>?`,A*v*1000,`Q = A·v = ${fmt(A)}·${v} = ${fmt(A*v)} m³/s = <b>${fmt(A*v*1000)} L/s</b>.`,'Q = A·v; 1 m³ = 1000 L.',{unit:'L/s'});},
 lv=>{const q=pick([['Pelo princípio de Bernoulli, onde a velocidade de um fluido é maior, a pressão é:','menor',['maior','igual','nula']],['Ao apertar a ponta de uma mangueira, a água sai mais rápido porque:','a área diminui e a vazão se mantém',['a pressão da rua aumenta','a água fica mais leve','a vazão aumenta']]]);return MC(q[0],q[1],q[2],`${q[0]} <b>${q[1]}</b>.`,'Revise a aula de hidrodinâmica.');},
]});
insertSkill('f4','termo',{id:'mhs',name:'Oscilações (MHS)',icon:'〰️',tip:'Massa-mola: T = 2π√(m/k). Pêndulo simples: T = 2π√(L/g) (não depende da massa). f = 1/T. Energia: E = k·A²/2.',
theory:`<p>No <b>movimento harmônico simples</b> o corpo oscila em torno do equilíbrio sob uma força restauradora.</p>
<div class="formula">Massa-mola: T = 2π√(m/k) · Pêndulo: T = 2π√(L/g)</div>
<ul><li>A velocidade é <b>máxima</b> no ponto de equilíbrio; a aceleração é máxima nos extremos.</li><li>O período do pêndulo não depende da massa nem da amplitude (pequenas oscilações).</li><li>Quadruplicar o comprimento do pêndulo dobra o período.</li></ul>
<div class="formula">E<sub>mec</sub> = ${F('k·A²',2)}</div>`,
gens:[
 lv=>{const p=pick([[0.25,3],[1/9,2],[1,6],[1/36,1],[4,12]]);const k=pick([36,144,900]);const m=round(k*p[0],4);return NUM(`Um bloco de <b>${fmt(m)} kg</b> oscila preso a uma mola de <b>k = ${k} N/m</b>. Qual o período? (π = 3)`,p[1],`T = 2π√(m/k) = 6·√(${fmt(m)}/${k}) = 6·${fmt(round(Math.sqrt(p[0]),4))} = <b>${p[1]} s</b>.`,'T = 2π√(m/k).',{unit:'s',visual:springSVG()});},
 lv=>{const p=pick([[10,6],[2.5,3],[0.4,1.2],[0.9,1.8],[1.6,2.4],[3.6,3.6]]);return NUM(`Qual o período de um pêndulo simples de <b>${fmt(p[0])} m</b>? (g = 10 m/s², π = 3)`,p[1],`T = 2π√(L/g) = 6·√(${fmt(p[0])}/10) = <b>${fmt(p[1])} s</b>.`,'T = 2π√(L/g).',{unit:'s',keys:[',']});},
 lv=>{const T=pick([0.5,0.25,2,4,0.1]);return NUM(`Um sistema oscila com período de <b>${fmt(T)} s</b>. Qual a frequência?`,1/T,`f = 1/T = <b>${fmt(1/T)} Hz</b>.`,'f = 1/T.',{unit:'Hz',keys:[',']});},
 lv=>{const k=pick([100,200,400,800]),A=pick([0.1,0.2,0.05]);return NUM(`Uma mola de <b>k = ${k} N/m</b> oscila com amplitude de <b>${fmt(A)} m</b>. Qual a energia mecânica?`,k*A*A/2,`E = kA²/2 = ${k}·${fmt(A)}²/2 = <b>${fmt(k*A*A/2)} J</b>.`,'E = k·A²/2.',{unit:'J',keys:[','],tol:0.001});},
 lv=>{const q=pick([['No MHS, a velocidade é máxima:','na posição de equilíbrio',['nos extremos','sempre','nunca']],['No MHS, a aceleração é máxima:','nos extremos',['na posição de equilíbrio','no meio do caminho','nunca']],['O período de um pêndulo simples NÃO depende:','da massa pendurada',['do comprimento','da gravidade','do local (planeta)']],['Se o comprimento de um pêndulo quadruplica, o período:','dobra',['quadruplica','cai pela metade','não muda']]]);return MC(q[0],q[1],q[2],`${q[0]} <b>${q[1]}</b>.`,'Revise a aula de oscilações.');},
]});
insertSkill('f4','ondas',{id:'acust',name:'Acústica: cordas e tubos',icon:'🎸',tip:'Corda e tubo aberto: fₙ = n·v/2L. Tubo fechado: fₙ = n·v/4L (só n ímpar). Fonte se aproximando: som mais agudo (Doppler). +10 dB = 10× a intensidade.',
theory:`<h3>Cordas vibrantes e tubos abertos</h3><div class="formula">f<sub>n</sub> = n · ${F('v','2L')} (n = 1, 2, 3…)</div>
<h3>Tubos fechados</h3><div class="formula">f<sub>n</sub> = n · ${F('v','4L')} (n = 1, 3, 5… só ímpares)</div>
<div class="ex">Tubo aberto de 0,85 m (v = 340 m/s): f₁ = 340/1,7 = 200 Hz</div>
<h3>Efeito Doppler</h3><p>Fonte se aproximando → frequência percebida maior (mais agudo); se afastando → mais grave.</p>
<h3>Nível sonoro</h3><p>+10 dB = intensidade 10 vezes maior; +20 dB = 100 vezes.</p>`,
gens:[
 lv=>{const v=pick([100,200,300,400]),L=pick([0.5,1,2]),n=R(1,4);return NUM(`Numa corda de <b>${fmt(L)} m</b>, as ondas se propagam a <b>${v} m/s</b>. Qual a frequência do <b>${n}º harmônico</b>?`,n*v/(2*L),`f = n·v/2L = ${n}·${v}/${fmt(2*L)} = <b>${fmt(n*v/(2*L))} Hz</b>.`,'fₙ = n·v/2L.',{unit:'Hz'});},
 lv=>{const p=pick([[0.5,340],[0.85,200],[1.7,100],[0.34,500]]);return NUM(`Qual a frequência fundamental de um tubo <b>aberto</b> de <b>${fmt(p[0])} m</b>? (v<sub>som</sub> = 340 m/s)`,p[1],`f₁ = v/2L = 340/${fmt(2*p[0])} = <b>${p[1]} Hz</b>.`,'Tubo aberto: f₁ = v/2L.',{unit:'Hz'});},
 lv=>{const p=pick([[0.85,100],[0.5,170],[0.25,340],[0.17,500]]);return NUM(`Qual a frequência fundamental de um tubo <b>fechado</b> de <b>${fmt(p[0])} m</b>? (v<sub>som</sub> = 340 m/s)`,p[1],`f₁ = v/4L = 340/${fmt(4*p[0])} = <b>${p[1]} Hz</b>.`,'Tubo fechado: f₁ = v/4L.',{unit:'Hz'});},
 lv=>{const d=pick([10,20,30]);return MC(`Se o nível sonoro aumenta <b>${d} dB</b>, a intensidade fica:`,`${nf(10**(d/10))} vezes maior`,[`${d} vezes maior`,`${2*d} vezes maior`,`${d/10} vezes maior`],`Cada +10 dB multiplica a intensidade por 10: 10<sup>${d/10}</sup> = ${nf(10**(d/10))}.`,'Escala logarítmica: +10 dB = × 10.');},
 lv=>{const q=pick([['Uma ambulância se aproxima. O som da sirene parece:','mais agudo (frequência maior)',['mais grave (frequência menor)','igual','mais fraco']],['Uma ambulância se afasta. O som da sirene parece:','mais grave (frequência menor)',['mais agudo (frequência maior)','igual','mais forte']],['Num tubo fechado numa extremidade, os harmônicos são:','apenas os ímpares',['apenas os pares','todos','apenas o fundamental']]]);return MC(q[0],q[1],q[2],`${q[0]} <b>${q[1]}</b>.`,'Revise a aula de acústica.');},
]});
insertSkill('f4','optica',{id:'espectro',name:'Ondas eletromagnéticas',icon:'🌈',tip:'No vácuo, todas viajam a c = 3 × 10⁸ m/s. Ordem de frequência: rádio < micro-ondas < infravermelho < luz visível < ultravioleta < raios X < gama. λ = c/f.',
theory:`<p>Ondas eletromagnéticas não precisam de meio e viajam no vácuo a <b>c = 3 × 10<sup>8</sup> m/s</b>.</p>
<div class="formula">c = λ · f</div>
<p><b>Espectro</b> (frequência crescente): rádio → micro-ondas → infravermelho → <b>luz visível</b> → ultravioleta → raios X → raios gama.</p>
<p>Na luz visível: vermelho tem maior λ (menor f); violeta, menor λ (maior f).</p>
<div class="ex">Rádio FM de 100 MHz: λ = 3×10⁸ / 10⁸ = 3 m</div>`,
gens:[
 lv=>{const S=['ondas de rádio','micro-ondas','infravermelho','luz visível','ultravioleta','raios X','raios gama'];const idx=shuffle([0,1,2,3,4,5,6]).slice(0,4);const hi=Math.random()<.5;const c=hi?Math.max(...idx):Math.min(...idx);return MC(`Qual destas radiações tem <b>${hi?'maior':'menor'} frequência</b>?`,S[c],idx.filter(i=>i!==c).map(i=>S[i]),`Ordem crescente de frequência: ${S.join(' < ')}.`,'Rádio é a de menor frequência; gama, a de maior.');},
 lv=>{const p=pick([[4,750],[5,600],[6,500],[7.5,400]]);return NUM(`Qual o comprimento de onda de uma luz de frequência <b>${fmt(p[0])} × 10<sup>14</sup> Hz</b>? Responda em <b>nanômetros</b> (c = 3 × 10<sup>8</sup> m/s).`,p[1],`λ = c/f = 3×10<sup>8</sup> / ${fmt(p[0])}×10<sup>14</sup> = ${fmt(p[1])}×10<sup>−9</sup> m = <b>${p[1]} nm</b>.`,'λ = c/f; 1 nm = 10⁻⁹ m.',{unit:'nm'});},
 lv=>{const f=pick([100,150,300,50]);return NUM(`Uma rádio FM transmite em <b>${f} MHz</b>. Qual o comprimento de onda? (c = 3 × 10<sup>8</sup> m/s)`,300/f,`λ = 3×10<sup>8</sup> / ${f}×10<sup>6</sup> = <b>${fmt(300/f)} m</b>.`,'MHz = 10⁶ Hz.',{unit:'m',keys:[',']});},
 lv=>{const q=pick([['Na luz visível, a cor de maior comprimento de onda é:','vermelho',['violeta','verde','azul']],['Na luz visível, a cor de maior frequência é:','violeta',['vermelho','amarelo','laranja']],['No vácuo, todas as ondas eletromagnéticas têm a mesma:','velocidade',['frequência','energia','cor']],['A radiação usada nos controles remotos é:','infravermelho',['ultravioleta','raios X','raios gama']],['A radiação responsável pelo bronzeado (e pelo câncer de pele) é:','ultravioleta',['infravermelho','ondas de rádio','micro-ondas']]]);return MC(q[0],q[1],q[2],`${q[0]} <b>${q[1]}</b>.`,'Revise o espectro eletromagnético.');},
]});
insertSkill('f5','campo',{id:'capac',name:'Capacitores',icon:'🔋',tip:'C = Q/U. Energia E = C·U²/2. Em paralelo: C_eq = C₁ + C₂. Em série: C_eq = C₁C₂/(C₁ + C₂) (o contrário dos resistores!).',
theory:`<p>Capacitor armazena carga e energia no campo elétrico entre suas placas.</p>
<div class="formula">C = ${F('Q','U')} (farad, F) · E = ${F('C · U²',2)}</div>
<h3>Associações (inverso dos resistores!)</h3><ul><li><b>Paralelo</b>: C<sub>eq</sub> = C<sub>1</sub> + C<sub>2</sub> + …</li><li><b>Série</b>: ${F(1,'C<sub>eq</sub>')} = ${F(1,'C₁')} + ${F(1,'C₂')} → dois: ${F('C₁·C₂','C₁ + C₂')}</li></ul>
<div class="ex">C = 2 µF ligado a 10 V: Q = 20 µC; E = 2·10⁻⁶·100/2 = 100 µJ</div>`,
gens:[
 lv=>{const C=R(1,20),U=R(2,50)*2;return NUM(`Um capacitor de <b>${C} µF</b> é ligado a <b>${U} V</b>. Qual a carga armazenada, em µC?`,C*U,`Q = C·U = ${C} µF · ${U} V = <b>${C*U} µC</b>.`,'Q = C·U.',{unit:'µC'});},
 lv=>{const C=R(1,20),U=R(2,20)*5;return NUM(`Um capacitor armazena <b>${C*U} µC</b> quando ligado a <b>${U} V</b>. Qual sua capacitância, em µF?`,C,`C = Q/U = ${C*U}/${U} = <b>${C} µF</b>.`,'C = Q/U.',{unit:'µF'});},
 lv=>{const C=pick([1,2,4,10]),U=pick([10,20,50,100]);return NUM(`Qual a energia armazenada num capacitor de <b>${C} µF</b> sob <b>${U} V</b>? Responda em <b>µJ</b>.`,C*U*U/2,`E = C·U²/2 = ${C}·${U}²/2 = <b>${nf(C*U*U/2)} µJ</b>.`,'E = C·U²/2.',{unit:'µJ'});},
 lv=>{const p=pick([[3,6,2],[4,4,2],[6,12,4],[10,15,6],[2,2,1]]),par=Math.random()<.5;return NUM(`Dois capacitores de <b>${p[0]} µF</b> e <b>${p[1]} µF</b> são ligados em <b>${par?'paralelo':'série'}</b>. Qual a capacitância equivalente?`,par?p[0]+p[1]:p[2],par?`Paralelo: soma → ${p[0]} + ${p[1]} = <b>${p[0]+p[1]} µF</b>.`:`Série: ${F(`${p[0]}·${p[1]}`,`${p[0]} + ${p[1]}`)} = <b>${p[2]} µF</b>.`,'Capacitores: paralelo soma; série usa produto/soma.',{unit:'µF'});},
 lv=>{const q=pick([['Capacitores em paralelo têm capacitância equivalente:','igual à soma das capacitâncias',['menor que a menor delas','igual ao produto','sempre nula']],['A unidade de capacitância no SI é o:','farad (F)',['coulomb (C)','henry (H)','ohm (Ω)']],['Dobrando a tensão num capacitor, a energia armazenada:','quadruplica',['dobra','cai pela metade','não muda']]]);return MC(q[0],q[1],q[2],`${q[0]} <b>${q[1]}</b>.`,'Revise a aula de capacitores.');},
]});
insertSkill('f5','potel',{id:'gerad',name:'Geradores e receptores',icon:'🔌',tip:'Gerador: U = ε − r·i; corrente no circuito i = ε/(R + r); curto-circuito i = ε/r; rendimento η = U/ε. Receptor: U = ε′ + r′·i.',
theory:`<p>Um <b>gerador real</b> (pilha, bateria) tem força eletromotriz ε e resistência interna r.</p>
<div class="formula">U = ε − r · i · i = ${F('ε','R + r')}</div>
<ul><li>Corrente de curto-circuito: i<sub>cc</sub> = ε/r.</li><li>Rendimento: η = U/ε.</li><li>Gerador ideal: r = 0 (U = ε sempre).</li></ul>
<h3>Receptor (motor)</h3><div class="formula">U = ε′ + r′ · i</div><div class="ex">Bateria ε = 12 V, r = 1 Ω, lâmpada R = 5 Ω: i = 12/6 = 2 A; U = 12 − 2 = 10 V; η = 83%</div>`,
gens:[
 lv=>{const e=pick([6,9,12,24]),r=pick([0.5,1,2]),i=R(1,4);return NUM(`Uma bateria de <b>ε = ${e} V</b> e resistência interna <b>${fmt(r)} Ω</b> fornece <b>${i} A</b>. Qual a tensão nos seus terminais?`,e-r*i,`U = ε − r·i = ${e} − ${fmt(r)}·${i} = <b>${fmt(e-r*i)} V</b>.`,'U = ε − r·i.',{unit:'V',keys:[',']});},
 lv=>{const r=pick([1,2]),Rr=R(2,10),i=R(1,4),e=(Rr+r)*i;return NUM(`Um gerador de <b>ε = ${e} V</b> e <b>r = ${r} Ω</b> alimenta um resistor de <b>${Rr} Ω</b>. Qual a corrente?`,i,`i = ε/(R + r) = ${e}/(${Rr} + ${r}) = <b>${i} A</b>.`,'Some a resistência externa com a interna.',{unit:'A'});},
 lv=>{const e=pick([6,9,12,24]),r=pick([0.5,1,2,3]);return NUM(`Qual a corrente de <b>curto-circuito</b> de uma bateria com ε = <b>${e} V</b> e r = <b>${fmt(r)} Ω</b>?`,e/r,`i<sub>cc</sub> = ε/r = ${e}/${fmt(r)} = <b>${fmt(e/r)} A</b>.`,'Em curto, só a resistência interna limita a corrente.',{unit:'A'});},
 lv=>{const e=pick([10,20,12,24]),f=pick([0.5,0.75,0.8,0.9]);return NUM(`Um gerador de <b>ε = ${e} V</b> mantém <b>${fmt(e*f)} V</b> nos terminais. Qual seu rendimento (%)?`,f*100,`η = U/ε = ${fmt(e*f)}/${e} = <b>${fmt(f*100)}%</b>.`,'η = U/ε.',{unit:'%'});},
 lv=>{const ep=pick([6,10,12]),rp=pick([1,2]),i=R(1,5);return NUM(`Um motor (receptor) tem <b>ε′ = ${ep} V</b> e <b>r′ = ${rp} Ω</b> e é percorrido por <b>${i} A</b>. Qual a tensão nos seus terminais?`,ep+rp*i,`U = ε′ + r′·i = ${ep} + ${rp}·${i} = <b>${ep+rp*i} V</b>.`,'Receptor: U = ε′ + r′·i.',{unit:'V'});},
]});
insertSkill('f5','moderna',{id:'nuclear',name:'Física nuclear',icon:'☢️',tip:'Nêutrons = A − Z. Alfa: A − 4 e Z − 2. Beta (β⁻): Z + 1 e A igual. Gama: não muda A nem Z. Fissão divide núcleos pesados (usinas); fusão une leves (Sol).',
theory:`<p>Núcleo <sup>A</sup><sub>Z</sub>X: Z = prótons (número atômico), A = prótons + nêutrons (número de massa). Nêutrons = A − Z.</p>
<h3>Decaimentos</h3><ul><li><b>Alfa (α)</b>: emite ⁴₂He → A diminui 4, Z diminui 2.</li><li><b>Beta (β⁻)</b>: um nêutron vira próton → Z aumenta 1, A igual.</li><li><b>Gama (γ)</b>: radiação eletromagnética → A e Z não mudam.</li></ul>
<h3>Energia nuclear</h3><ul><li><b>Fissão</b>: núcleo pesado (urânio-235) se divide — usinas como Angra.</li><li><b>Fusão</b>: núcleos leves (hidrogênio) se unem — energia do Sol.</li></ul>`,
gens:[
 lv=>{const it=pick([['carbono-14',6,14],['urânio-235',92,235],['oxigênio-16',8,16],['ferro-56',26,56],['césio-137',55,137],['cobalto-60',27,60],['iodo-131',53,131]]);return NUM(`Quantos <b>nêutrons</b> tem o núcleo de ${it[0]} (Z = ${it[1]})?`,it[2]-it[1],`Nêutrons = A − Z = ${it[2]} − ${it[1]} = <b>${it[2]-it[1]}</b>.`,'A é o número de massa (prótons + nêutrons).');},
 lv=>{const A=R(200,240),Z=R(84,94);const P=(a,z)=>`A = ${a}, Z = ${z}`;return MC(`Um núcleo com <b>${P(A,Z)}</b> emite uma partícula <b>alfa</b>. O novo núcleo tem:`,P(A-4,Z-2),[P(A-2,Z-4),P(A,Z+1),P(A-4,Z+2)],'Alfa = ⁴₂He: A − 4 e Z − 2.','A partícula alfa é um núcleo de hélio.');},
 lv=>{const A=R(10,140),Z=R(5,60);const P=(a,z)=>`A = ${a}, Z = ${z}`;return MC(`Um núcleo com <b>${P(A,Z)}</b> sofre decaimento <b>beta (β⁻)</b>. O novo núcleo tem:`,P(A,Z+1),[P(A,Z-1),P(A-1,Z),P(A-4,Z-2)],'No β⁻, um nêutron vira próton: Z + 1 e A igual.','Beta muda só o número atômico.');},
 lv=>{const q=pick([['Usinas nucleares como Angra produzem energia por:','fissão nuclear',['fusão nuclear','combustão','efeito fotoelétrico']],['O Sol produz energia por:','fusão nuclear',['fissão nuclear','combustão de gases','reações químicas']],['Na emissão gama, o número de massa e o número atômico:','não mudam',['diminuem 4 e 2','aumentam 1','diminuem 1']],['A radiação mais penetrante é a:','gama',['alfa','beta','infravermelha']]]);return MC(q[0],q[1],q[2],`${q[0]} <b>${q[1]}</b>.`,'Revise a aula de física nuclear.');},
 lv=>{const T=pick([5,8,30]),n=R(2,4);return NUM(`Uma amostra radioativa tem meia-vida de <b>${T} dias</b>. Que fração dela resta após <b>${n*T} dias</b>? (ex.: 1/8)`,1/2**n,`${n} meias-vidas: (1/2)<sup>${n}</sup> = <b>${F(1,2**n)}</b>.`,'Cada meia-vida divide por 2.',{answer:F(1,2**n),key:'1/'+2**n,keys:['/']});},
]});

/* ------------------------ UNIDADE 6 — FÍSICA NO COTIDIANO ------------------------ */
UNITS.push({id:'f6',title:'Física no cotidiano (ENEM)',sub:'Energia e sustentabilidade, trânsito e astronomia',color:'#2b70c9',dark:'#1f569e',skills:[
{id:'cotener',name:'Energia e sustentabilidade',icon:'♻️',tip:'Economia = diferença de potência × tempo. Renováveis: solar, eólica, hidrelétrica, biomassa. Não renováveis: petróleo, carvão, gás natural, nuclear.',
theory:`<h3>Fontes de energia</h3><ul><li><b>Renováveis</b>: solar, eólica, hidrelétrica, biomassa, geotérmica.</li><li><b>Não renováveis</b>: petróleo, carvão mineral, gás natural, nuclear (urânio).</li></ul>
<h3>Economizando</h3><p>Trocar uma lâmpada de 60 W por uma LED de 9 W economiza 51 W. Ligada 5 h/dia por 30 dias: 51 × 150 = 7650 Wh ≈ 7,65 kWh.</p>
<h3>Transformações em usinas</h3><p>Hidrelétrica: potencial gravitacional → cinética → elétrica. Termelétrica: química → térmica → cinética → elétrica. Eólica: cinética do vento → elétrica.</p>`,
gens:[
 lv=>{const a=pick([60,100,40]),b=pick([7,9,12]),h=pick([4,5,6,8]);const e=(a-b)*h*30/1000;return NUM(`Uma lâmpada incandescente de <b>${a} W</b> é trocada por uma LED de <b>${b} W</b>. Usando <b>${h} h por dia</b> durante <b>30 dias</b>, quanto se economiza em <b>kWh</b>?`,e,`(${a} − ${b}) W × ${h} h × 30 = ${nf((a-b)*h*30)} Wh = <b>${fmt(e)} kWh</b>.`,'Economia = diferença de potência × tempo total.',{unit:'kWh',keys:[','],tol:0.01});},
 lv=>{const it=pick([['solar','Renovável'],['eólica','Renovável'],['hidrelétrica','Renovável'],['biomassa (bagaço de cana)','Renovável'],['petróleo','Não renovável'],['carvão mineral','Não renovável'],['gás natural','Não renovável'],['nuclear (urânio)','Não renovável']]);return MC(`A energia <b>${it[0]}</b> é:`,it[1],['Renovável','Não renovável'],`${it[0]}: ${it[1].toLowerCase()}.`,'Renovável: a fonte se recompõe na escala de tempo humana.',{keep:true});},
 lv=>{const it=pick([['hidrelétrica','potencial gravitacional → cinética → elétrica'],['eólica','cinética (vento) → elétrica'],['termelétrica','química → térmica → cinética → elétrica'],['solar fotovoltaica','luminosa → elétrica']]);return MC(`Qual a sequência de transformações de energia numa usina <b>${it[0]}</b>?`,it[1],['potencial gravitacional → cinética → elétrica','cinética (vento) → elétrica','química → térmica → cinética → elétrica','luminosa → elétrica'],`Usina ${it[0]}: ${it[1]}.`,'Pense de onde vem a energia e como ela gira a turbina.',{keep:true});},
 lv=>{const P=pick([1000,2000,4000,5500]),m=pick([10,15,20,30]),p=pick([0.8,1]);const e=P/1000*m/60*30;return NUM(`Um chuveiro de <b>${nf(P)} W</b> é usado <b>${m} min por dia</b>. Com tarifa de <b>${money(p)}/kWh</b>, quanto custa por mês (30 dias)?`,e*p,`E = ${fmt(P/1000)} kW × ${fmt(m/60)} h × 30 = ${fmt(e)} kWh → custo = <b>R$ ${fmt(round(e*p,2))}</b>.`,'Converta minutos em horas e W em kW.',{keys:[','],tol:0.02});},
 lv=>{const Pu=pick([20,30,40]),Pt=100;return NUM(`Um motor recebe <b>${Pt} J</b> de energia a cada segundo e realiza <b>${Pu} J</b> de trabalho útil. O restante vira calor. Qual o rendimento (%)?`,Pu,`η = ${Pu}/${Pt} = <b>${Pu}%</b>. Os outros ${Pt-Pu}% são dissipados como calor.`,'η = útil ÷ total.',{unit:'%'});},
]},
{id:'transito',name:'Física do trânsito',icon:'🚦',tip:'Distância de parada = distância de reação (v·t_reação) + distância de frenagem (v²/2a). Dobrar a velocidade quadruplica a frenagem.',
theory:`<p>Até parar, o carro percorre:</p><div class="formula">d = v · t<sub>reação</sub> + ${F('v²','2a')}</div>
<ul><li>Tempo de reação típico: 0,7 a 1 s (maior com celular, álcool ou sono).</li><li>A frenagem depende de <b>v²</b>: a 2× a velocidade, 4× a distância de frenagem.</li></ul>
<div class="ex">72 km/h = 20 m/s, reação 1 s, a = 5 m/s²: 20 + 400/10 = 60 m</div>
<h3>Cinto e airbag</h3><p>Aumentam o tempo da desaceleração, diminuindo a força média (I = F·Δt = ΔQ).</p>`,
gens:[
 lv=>{const v=pick([36,54,72,90,108]),t=pick([0.5,1,1.5,2]);return NUM(`Um motorista a <b>${v} km/h</b> leva <b>${fmt(t)} s</b> para reagir. Quantos metros o carro percorre antes de começar a frear?`,v/3.6*t,`${v} km/h = ${v/3.6} m/s; d = ${v/3.6}·${fmt(t)} = <b>${fmt(v/3.6*t)} m</b>.`,'Durante a reação, o carro segue com velocidade constante.',{unit:'m',keys:[',']});},
 lv=>{const v=pick([36,72,108]),t=pick([0.5,1]),a=pick([5,10]);const vm=v/3.6;return NUM(`Carro a <b>${v} km/h</b>, tempo de reação <b>${fmt(t)} s</b>, desaceleração de <b>${a} m/s²</b>. Qual a distância total até parar?`,vm*t+vm*vm/(2*a),`Reação: ${vm}·${fmt(t)} = ${fmt(vm*t)} m. Frenagem: ${vm}²/(2·${a}) = ${fmt(vm*vm/(2*a))} m. Total = <b>${fmt(vm*t+vm*vm/(2*a))} m</b>.`,'Some distância de reação e distância de frenagem.',{unit:'m',keys:[',']});},
 lv=>{const k=pick([2,3]);return MC(`Se um carro trafega com velocidade <b>${k} vezes maior</b>, a distância de <b>frenagem</b> fica:`,`${k*k} vezes maior`,[`${k} vezes maior`,`${2*k} vezes maior`,'igual'],`d = v²/2a: fator ${k}² = ${k*k}.`,'A frenagem depende do quadrado da velocidade.');},
 lv=>{const m=pick([60,70,80]),v=pick([10,15,20]),t=pick([0.1,0.2]);return NUM(`Numa colisão, um passageiro de <b>${m} kg</b> a <b>${v} m/s</b> é parado pelo cinto em <b>${fmt(t)} s</b>. Qual a força média?`,m*v/t,`F = m·Δv/Δt = ${m}·${v}/${fmt(t)} = <b>${nf(m*v/t)} N</b>.`,'Impulso: F·Δt = m·Δv.',{unit:'N'});},
 lv=>{const q=pick([['Cintos de segurança e airbags reduzem lesões porque:','aumentam o tempo da desaceleração, reduzindo a força',['diminuem a massa do passageiro','eliminam a inércia','aumentam a velocidade final']],['Usar o celular ao dirigir aumenta principalmente:','o tempo de reação (e a distância percorrida antes de frear)',['a desaceleração dos freios','o atrito dos pneus','a massa do carro']],['Numa curva, o que mantém o carro na trajetória é:','o atrito entre pneus e pista (força centrípeta)',['a inércia','o peso do carro','o motor']]]);return MC(q[0],q[1],q[2],`${q[0]} <b>${q[1]}</b>.`,'Aplique inércia, impulso e atrito.');},
]},
{id:'astro',name:'Astronomia',icon:'🔭',tip:'Estações: inclinação do eixo da Terra. Luz do Sol leva ~8 min para chegar. Ano-luz é distância. Eclipse solar: Lua entre Sol e Terra.',
theory:`<ul><li><b>Dia e noite</b>: rotação da Terra (≈ 24 h).</li><li><b>Ano</b>: translação ao redor do Sol (≈ 365 dias).</li><li><b>Estações do ano</b>: causadas pela <b>inclinação do eixo</b> terrestre (≈ 23,5°), não pela distância ao Sol.</li><li><b>Fases da Lua</b>: parte iluminada vista da Terra (ciclo ≈ 29,5 dias).</li><li><b>Eclipse solar</b>: Lua entre o Sol e a Terra (lua nova). <b>Eclipse lunar</b>: Terra entre o Sol e a Lua (lua cheia).</li></ul>
<div class="formula">Ano-luz = distância que a luz percorre em 1 ano ≈ 9,5 × 10<sup>12</sup> km</div><div class="ex">Sol–Terra: 1,5 × 10¹¹ m ÷ 3 × 10⁸ m/s = 500 s ≈ 8,3 min</div>`,
gens:[
 lv=>{const q=pick([['As estações do ano são causadas principalmente:','pela inclinação do eixo da Terra',['pela distância variável até o Sol','pela rotação da Terra','pelas fases da Lua']],['O eclipse solar acontece quando:','a Lua fica entre o Sol e a Terra',['a Terra fica entre o Sol e a Lua','o Sol fica entre a Terra e a Lua','a Lua está cheia']],['Ano-luz é uma unidade de:','distância',['tempo','velocidade','brilho']],['O dia e a noite são causados:','pela rotação da Terra',['pela translação da Terra','pela inclinação do eixo','pela órbita da Lua']],['O eclipse lunar só pode ocorrer na fase de:','lua cheia',['lua nova','quarto crescente','quarto minguante']]]);return MC(q[0],q[1],q[2],`${q[0]} <b>${q[1]}</b>.`,'Revise a aula de astronomia.');},
 lv=>NUM('A luz percorre <b>1,5 × 10<sup>11</sup> m</b> do Sol até a Terra a <b>3 × 10<sup>8</sup> m/s</b>. Quantos <b>segundos</b> ela leva?',500,'t = d/v = 1,5×10<sup>11</sup> / 3×10<sup>8</sup> = <b>500 s</b> (≈ 8 min 20 s).','t = distância ÷ velocidade.',{unit:'s'}),
 lv=>{const d=pick([[3.8e8,'a Lua',1.27],[1.5e11,'o Sol',500]]);return NUM(`Um sinal de luz leva quanto tempo (em segundos) para ir da Terra até ${d[1]}, a ${SCIV(d[0])} m? (c = 3 × 10<sup>8</sup> m/s)`,d[0]/3e8,`t = ${SCIV(d[0])} / 3×10<sup>8</sup> = <b>${fmt(round(d[0]/3e8,2))} s</b>.`,'t = d/c.',{unit:'s',keys:[','],tol:0.02});},
 lv=>{const it=pick([['Quanto tempo a Terra leva para dar uma volta em torno de si mesma (em horas)?',24],['Quantos dias, aproximadamente, a Terra leva para dar uma volta ao redor do Sol?',365],['Quantos dias dura, aproximadamente, o ciclo das fases da Lua (arredonde)?',30]]);return NUM(it[0],it[1],`Resposta: <b>${it[1]}</b>.`,'Rotação: dia; translação: ano; fases da Lua: cerca de um mês.',{tol:it[1]===30?1:0});},
 lv=>{const n=R(2,8);return NUM(`Uma estrela está a <b>${n} anos-luz</b>. Há quantos anos saiu a luz que vemos hoje dela?`,n,`Ano-luz é a distância que a luz percorre em 1 ano: a luz saiu há <b>${n} anos</b>.`,'Olhar para longe no espaço é olhar para o passado.',{unit:'anos'});},
]},
]});

/* ------------------------ Cartões de memória ------------------------ */
const CARDS={
 grand:[['Unidade de força no SI','newton (N)'],['Unidade de energia no SI','joule (J)'],['Unidade de potência no SI','watt (W)'],['Grandeza vetorial','precisa de módulo, direção e sentido'],['Prefixo micro (µ)','10⁻⁶']],
 conv:[['km/h → m/s','divide por 3,6'],['m/s → km/h','multiplica por 3,6'],['72 km/h em m/s','20 m/s'],['36 km/h em m/s','10 m/s']],
 ordem:[['Velocidade da luz no vácuo','3 × 10⁸ m/s'],['Carga elementar','1,6 × 10⁻¹⁹ C'],['Ordem de grandeza com coeficiente ≥ 3,16','arredonda para a potência seguinte'],['Multiplicar potências de 10','somar os expoentes']],
 vet:[['Resultante de vetores no mesmo sentido','soma dos módulos'],['Resultante de vetores opostos','diferença dos módulos'],['Resultante de vetores perpendiculares','√(a² + b²) (Pitágoras)'],['Componente horizontal de F (ângulo com a horizontal)','F · cos θ'],['Componente vertical de F (ângulo com a horizontal)','F · sen θ']],
 vm:[['Velocidade média','Δs ÷ Δt'],['Distância percorrida com v constante','v · Δt'],['Velocidade média em trechos diferentes','distância total ÷ tempo total']],
 mu:[['Função horária do MRU','s = s₀ + v·t'],['MRU com v < 0','movimento retrógrado'],['Tempo de encontro (sentidos opostos)','d ÷ (v_A + v_B)'],['Distância para um trem atravessar uma ponte','comprimento do trem + comprimento da ponte']],
 muv:[['Aceleração média','Δv ÷ Δt'],['Velocidade no MRUV','v = v₀ + a·t'],['Posição no MRUV','s = s₀ + v₀t + at²/2'],['Equação de Torricelli','v² = v₀² + 2aΔs'],['v e a com sinais opostos','movimento retardado']],
 graf:[['Área sob o gráfico v × t','deslocamento'],['Inclinação do gráfico v × t','aceleração'],['Inclinação do gráfico s × t','velocidade'],['Formato do gráfico s × t no MRUV','parábola']],
 queda:[['Altura na queda livre (g = 10)','h = 5t²'],['Velocidade na queda livre','v = g·t'],['Altura máxima no lançamento vertical','v₀² ÷ 2g'],['Aceleração no ponto mais alto','g (não é zero!)']],
 lanc:[['Movimento horizontal num lançamento','MRU (velocidade constante)'],['Tempo de queda no lançamento horizontal','depende só da altura'],['Ângulo de alcance máximo','45°'],['Velocidade no topo do lançamento oblíquo','só a componente horizontal']],
 mcu:[['Frequência','1 ÷ período'],['Velocidade linear no MCU','2πR ÷ T'],['Aceleração centrípeta','v² ÷ R'],['rpm → Hz','divide por 60']],
 newton:[['1ª lei de Newton','inércia'],['2ª lei de Newton','F = m · a'],['3ª lei de Newton','ação e reação'],['1 newton','1 kg · m/s²'],['Ação e reação atuam','em corpos diferentes (não se anulam)']],
 peso:[['Peso','P = m · g'],['Massa de um astronauta na Lua','a mesma que na Terra'],['Normal no elevador acelerando para cima','N = m(g + a)'],['g na Lua','≈ 1,6 m/s²']],
 atrito:[['Força de atrito','μ · N'],['Atrito com o corpo parado','estático'],['Desaceleração só por atrito','a = μ · g'],['μ estático comparado ao cinético','maior']],
 plano:[['Componente do peso ao longo da rampa','m·g·sen θ'],['Normal no plano inclinado','m·g·cos θ'],['Aceleração num plano sem atrito','g · sen θ'],['sen θ de uma rampa','altura ÷ comprimento']],
 trab:[['Trabalho de uma força','τ = F · d · cos θ'],['Força perpendicular ao deslocamento','trabalho nulo'],['Potência','trabalho ÷ tempo'],['Potência com velocidade constante','P = F · v'],['Rendimento','potência útil ÷ potência total']],
 ener:[['Energia cinética','m·v² ÷ 2'],['Energia potencial gravitacional','m·g·h'],['Energia potencial elástica','k·x² ÷ 2'],['Velocidade após cair de h (sem atrito)','√(2gh)'],['Velocidade dobra → energia cinética','fica 4 vezes maior']],
 momento:[['Quantidade de movimento','Q = m · v'],['Impulso','I = F · Δt'],['Teorema do impulso','I = ΔQ'],['Quantidade de movimento num sistema isolado','se conserva'],['Colisão perfeitamente inelástica','os corpos seguem juntos']],
 grav:[['Lei da gravitação universal','F = G·M·m ÷ d²'],['Distância dobra → força gravitacional','fica 4 vezes menor'],['3ª lei de Kepler','T² ÷ R³ = constante'],['1ª lei de Kepler','órbitas elípticas com o Sol num foco'],['Gravidade na superfície de um planeta','g = G·M ÷ R²']],
 estatica:[['Momento (torque)','M = F · d'],['Alavanca em equilíbrio','F₁·d₁ = F₂·d₂'],['Equilíbrio de corpo extenso','força resultante nula e momento resultante nulo'],['Centro de massa de duas massas','(m₁x₁ + m₂x₂) ÷ (m₁ + m₂)']],
 hidro:[['Densidade','m ÷ V'],['Pressão','F ÷ A'],['Lei de Stevin','p = p₀ + d·g·h'],['Empuxo','d_líquido · V_submerso · g'],['Princípio de Pascal','F₁/A₁ = F₂/A₂']],
 hidrodin:[['Vazão','V ÷ Δt = A · v'],['Equação da continuidade','A₁·v₁ = A₂·v₂'],['Bernoulli: onde a velocidade é maior','a pressão é menor']],
 term:[['Conversão Celsius–Fahrenheit','C/5 = (F − 32)/9'],['Celsius → Kelvin','K = C + 273'],['Zero absoluto','0 K = −273 °C'],['Temperatura igual em °C e °F','−40'],['ΔF em função de ΔC','ΔF = 1,8·ΔC']],
 calor:[['Calor sensível','Q = m·c·ΔT'],['Calor latente','Q = m·L'],['Calor específico da água','1 cal/g·°C'],['Passagem sólido → gasoso','sublimação'],['Calor latente de fusão do gelo','80 cal/g']],
 dilat:[['Dilatação linear','ΔL = L₀·α·ΔT'],['Coeficiente superficial','β = 2α'],['Coeficiente volumétrico','γ = 3α'],['Densidade máxima da água','a 4 °C']],
 gases:[['Equação geral dos gases','p·V/T = constante'],['Transformação isotérmica','p·V = constante'],['Equação de Clapeyron','p·V = n·R·T'],['Temperatura nas leis dos gases','sempre em kelvin'],['Volume de 1 mol de gás nas CNTP','≈ 22,4 L']],
 termo:[['1ª lei da termodinâmica','Q = τ + ΔU'],['Trabalho a pressão constante','τ = p·ΔV'],['Rendimento de Carnot','1 − T_fria ÷ T_quente'],['2ª lei (Clausius)','calor não passa sozinho do frio para o quente'],['Isotérmica num gás ideal','ΔU = 0']],
 mhs:[['Período do sistema massa-mola','T = 2π√(m/k)'],['Período do pêndulo simples','T = 2π√(L/g)'],['Velocidade máxima no MHS','na posição de equilíbrio'],['Energia no MHS','k·A² ÷ 2'],['Período do pêndulo NÃO depende','da massa']],
 ondas:[['Equação fundamental da onda','v = λ · f'],['Velocidade do som no ar','≈ 340 m/s'],['Tipo de onda do som','mecânica e longitudinal'],['Som grave ou agudo depende da','frequência'],['Distância até o obstáculo no eco','v · t ÷ 2']],
 acust:[['Harmônicos em corda ou tubo aberto','fₙ = n·v ÷ 2L'],['Harmônicos em tubo fechado','fₙ = n·v ÷ 4L (n ímpar)'],['Fonte sonora se aproximando','som mais agudo (efeito Doppler)'],['+10 dB no nível sonoro','intensidade 10 vezes maior']],
 optica:[['Lei da reflexão','ângulo de incidência = ângulo de reflexão'],['Equação de Gauss','1/f = 1/p + 1/p′'],['Vergência','V = 1/f (f em metros)'],['Lei de Snell','n₁·sen i = n₂·sen r'],['Correção da miopia','lente divergente']],
 espectro:[['Ordem do espectro (frequência crescente)','rádio, micro-ondas, IV, visível, UV, raios X, gama'],['Cor de maior comprimento de onda','vermelho'],['Velocidade de toda onda eletromagnética no vácuo','3 × 10⁸ m/s (c)'],['Comprimento de onda da luz','λ = c ÷ f']],
 carga:[['Carga de um corpo com n elétrons em excesso','Q = n · e'],['Lei de Coulomb','F = k·|Q₁Q₂| ÷ d²'],['Constante eletrostática no vácuo','k = 9 × 10⁹ N·m²/C²'],['Eletrização por atrito','corpos ficam com cargas opostas'],['Eletrização por contato','corpos ficam com cargas de mesmo sinal']],
 campo:[['Campo elétrico de uma carga pontual','E = k·Q ÷ d²'],['Potencial elétrico de uma carga pontual','V = k·Q ÷ d'],['Trabalho da força elétrica','τ = q · U'],['Campo elétrico uniforme','U = E · d'],['Campo dentro de um condutor em equilíbrio','nulo']],
 capac:[['Capacitância','C = Q ÷ U'],['Energia no capacitor','C·U² ÷ 2'],['Capacitores em paralelo','C_eq = C₁ + C₂'],['Dois capacitores em série','C₁·C₂ ÷ (C₁ + C₂)']],
 ohm:[['1ª lei de Ohm','U = R · i'],['2ª lei de Ohm','R = ρ·L ÷ A'],['Corrente elétrica','i = Q ÷ Δt'],['Fio mais grosso','menor resistência']],
 assoc:[['Resistores em série','R_eq = R₁ + R₂ + …'],['Dois resistores em paralelo','R₁·R₂ ÷ (R₁ + R₂)'],['Grandeza igual em todos os resistores em série','a corrente'],['Grandeza igual em todos os resistores em paralelo','a tensão'],['n resistores iguais em paralelo','R ÷ n']],
 potel:[['Potência elétrica','P = U · i'],['Potência em função de U e R','P = U² ÷ R'],['Energia elétrica consumida','E = P · Δt'],['1 kWh em joules','3,6 × 10⁶ J']],
 gerad:[['Tensão nos terminais de um gerador','U = ε − r·i'],['Corrente num circuito com gerador real','i = ε ÷ (R + r)'],['Corrente de curto-circuito','ε ÷ r'],['Rendimento do gerador','U ÷ ε']],
 mag:[['Força magnética sobre uma carga','F = |q|·v·B·sen θ'],['Força magnética sobre um fio','F = B·i·L·sen θ'],['Campo de um fio reto longo','B = μ₀·i ÷ 2πd'],['Cortar um ímã ao meio','dois ímãs completos'],['Descoberta de Oersted','corrente elétrica cria campo magnético']],
 indu:[['Fluxo magnético','Φ = B·A·cos θ'],['Lei de Faraday','ε = −N·ΔΦ ÷ Δt'],['Lei de Lenz','corrente induzida se opõe à variação do fluxo'],['Relação do transformador','Uₛ/Uₚ = Nₛ/Nₚ'],['Corrente necessária para o transformador','alternada']],
 moderna:[['Energia do fóton','E = h · f'],['Efeito fotoelétrico','Ec = h·f − φ'],['Equivalência massa-energia','E = m·c²'],['Meia-vida','tempo para a amostra cair à metade'],['Dilatação do tempo','Δt = γ · Δt₀']],
 nuclear:[['Número de nêutrons','A − Z'],['Decaimento alfa','A − 4 e Z − 2'],['Decaimento beta (β⁻)','Z + 1 e A igual'],['Energia das usinas nucleares','fissão'],['Energia do Sol','fusão']],
 cotener:[['Fontes renováveis','solar, eólica, hidrelétrica, biomassa'],['Economia ao trocar lâmpadas','diferença de potência × tempo'],['Transformação na hidrelétrica','potencial gravitacional → elétrica']],
 transito:[['Distância de parada','distância de reação + distância de frenagem'],['Distância de frenagem','v² ÷ 2a'],['Velocidade dobra → frenagem','fica 4 vezes maior'],['Função do cinto e do airbag','aumentar Δt e reduzir a força média']],
 astro:[['Causa das estações do ano','inclinação do eixo da Terra'],['Eclipse solar','Lua entre o Sol e a Terra'],['Ano-luz','distância percorrida pela luz em 1 ano'],['Tempo da luz do Sol até a Terra','≈ 8 minutos']],
};
