const BRAND={app:'SaberLingo',chatPh:'ex.: o que é mol?',tutor:'Professora Marie',sym:'pH',body:'#ff9600',dark:'#e07b00',belly:'#fff4d6',lsKey:'quimlingo_v1',first:'estados',
 welcome:'Química do <b>9º ano ao Ensino Médio</b>: matéria, átomo, tabela periódica, ligações, cálculos químicos, físico-química e orgânica, com exercícios gerados sem parar.',
 range:'do 9º ano ao Ensino Médio (ENEM e vestibulares)',searchEx:'ex.: mol',firstName:'Estados físicos',
 chips:['O que é mol?','Como calcular pH?','Diferença entre ânodo e cátodo','O que é isótopo?','Funções orgânicas','Princípio de Le Chatelier'],
 askEx:'<i>"o que é mol?"</i>, <i>"ligação iônica"</i>, <i>"pH"</i>',
 formulas:'massa molar, mol, concentração, diluição, pH, meia-vida, estequiometria'};
const UNITS=[];

/* ---------- dados e geradores de Química ---------- */
const MA={H:1,C:12,N:14,O:16,Na:23,Mg:24,Al:27,S:32,Cl:35.5,K:39,Ca:40,Fe:56,Cu:63.5,Zn:65};
const CPD=[['H2O','água',{H:2,O:1}],['CO2','gás carbônico',{C:1,O:2}],['NaCl','cloreto de sódio',{Na:1,Cl:1}],['H2SO4','ácido sulfúrico',{H:2,S:1,O:4}],['C6H12O6','glicose',{C:6,H:12,O:6}],['NH3','amônia',{N:1,H:3}],['CH4','metano',{C:1,H:4}],['CaCO3','carbonato de cálcio',{Ca:1,C:1,O:3}],['NaOH','hidróxido de sódio',{Na:1,O:1,H:1}],['HCl','ácido clorídrico',{H:1,Cl:1}],['O2','gás oxigênio',{O:2}],['C2H6O','etanol',{C:2,H:6,O:1}],['MgO','óxido de magnésio',{Mg:1,O:1}],['Al2O3','óxido de alumínio',{Al:2,O:3}],['HNO3','ácido nítrico',{H:1,N:1,O:3}],['KCl','cloreto de potássio',{K:1,Cl:1}]];
const fml=f=>f.replace(/([A-Za-z)])(\d+)/g,'$1<sub>$2</sub>');
const molar=c=>round(Object.entries(c[2]).reduce((a,[e,n])=>a+MA[e]*n,0),2);
const dados=c=>'Dados (g/mol): '+Object.keys(c[2]).map(e=>`${e} = ${fmt(MA[e])}`).join('; ');
const sci=(m,e)=>`${fmt(m)} × 10<sup>${String(e).replace('-','−')}</sup>`;
/* elementos: símbolo, nome, Z, A (isótopo mais comum) */
const ELEM=[['H','hidrogênio',1,1],['He','hélio',2,4],['Li','lítio',3,7],['C','carbono',6,12],['N','nitrogênio',7,14],['O','oxigênio',8,16],['F','flúor',9,19],['Ne','neônio',10,20],['Na','sódio',11,23],['Mg','magnésio',12,24],['Al','alumínio',13,27],['Si','silício',14,28],['P','fósforo',15,31],['S','enxofre',16,32],['Cl','cloro',17,35],['Ar','argônio',18,40],['K','potássio',19,39],['Ca','cálcio',20,40],['Fe','ferro',26,56],['Zn','zinco',30,64],['Br','bromo',35,79],['Ag','prata',47,107],['I','iodo',53,127],['Au','ouro',79,197],['Hg','mercúrio',80,201],['Pb','chumbo',82,207]];
/* distribuição eletrônica pelo diagrama de Linus Pauling */
const PAUL=[['1s',2],['2s',2],['2p',6],['3s',2],['3p',6],['4s',2],['3d',10],['4p',6],['5s',2],['4d',10],['5p',6]];
function paul(z){ const out=[]; let r=z; for(const [s,c] of PAUL){ if(r<=0)break; const k=Math.min(r,c); out.push([s,k]); r-=k; } return out; }
const pstr=d=>d.map(([s,k])=>`${s}<sup>${k}</sup>`).join(' ');
function valence(z){ const d=paul(z); const n=Math.max(...d.map(([s])=>+s[0])); return d.filter(([s])=>+s[0]===n).reduce((a,[,k])=>a+k,0); }
const ZOK=[...Array(36)].map((_,i)=>i+1).filter(z=>z!==24&&z!==29);

const quiGens={
 molar:lv=>{ const c=pick(CPD),M=molar(c); return NUM(`Qual é a massa molar de <b>${fml(c[0])}</b> (${c[1]})?<br><small>${dados(c)}</small>`,M,`M = ${Object.entries(c[2]).map(([e,n])=>`${n>1?n+' × ':''}${fmt(MA[e])}`).join(' + ')} = <b>${fmt(M)} g/mol</b>.`,'Some as massas de todos os átomos da fórmula, multiplicando pelo índice de cada elemento.',{unit:'g/mol'}); },
 mol:lv=>{ const c=pick(CPD),M=molar(c),n=pick([0.5,1,2,3,4,0.25,5,10]),m=round(n*M,3);
   return Math.random()<.5?NUM(`Quantos mols há em <b>${fmt(m)} g</b> de ${fml(c[0])} (M = ${fmt(M)} g/mol)?`,n,`n = m / M = ${fmt(m)} / ${fmt(M)} = <b>${fmt(n)} mol</b>.`,'Use n = m / M.',{unit:'mol'})
     :NUM(`Qual é a massa de <b>${fmt(n)} mol</b> de ${fml(c[0])} (M = ${fmt(M)} g/mol)?`,m,`m = n × M = ${fmt(n)} × ${fmt(M)} = <b>${fmt(m)} g</b>.`,'Use m = n × M.',{unit:'g'}); },
 avog:lv=>{ const n=pick([1,2,3,0.5,5,10]),c=pick(CPD); const v=n*6; const [mm,ee]=v>=10?[v/10,24]:[v,23];
   return MC(`Quantas moléculas existem em <b>${fmt(n)} mol</b> de ${fml(c[0])}? (Constante de Avogadro ≈ 6 × 10<sup>23</sup>)`,sci(mm,ee),[sci(mm,ee+1),sci(mm,ee-1),sci(n,23),sci(round(mm*2,2),ee)],`N = n × 6 × 10<sup>23</sup> = ${fmt(n)} × 6 × 10<sup>23</sup> = <b>${sci(mm,ee)}</b>.`,'1 mol contém 6 × 10²³ partículas.'); },
 conc:lv=>{ const V=pick([0.5,1,2,0.25,4]),C=pick([10,20,40,50,5,8]),m=round(C*V,2);
   return NUM(`Dissolvem-se <b>${fmt(m)} g</b> de açúcar em água até completar <b>${fmt(V)} L</b> de solução. Qual é a concentração comum?`,C,`C = m / V = ${fmt(m)} g / ${fmt(V)} L = <b>${fmt(C)} g/L</b>.`,'Concentração comum: C = massa do soluto / volume da solução.',{unit:'g/L'}); },
 molar2:lv=>{ const c=pick(CPD.filter(x=>['NaCl','NaOH','HCl','KCl','H2SO4','C6H12O6'].includes(x[0]))),M=molar(c),n=pick([0.1,0.2,0.5,1,2]),V=pick([0.5,1,2,0.25]),mo=round(n/V,4);
   return NUM(`Qual é a concentração em mol/L de uma solução com <b>${fmt(round(n*M,2))} g</b> de ${fml(c[0])} (M = ${fmt(M)} g/mol) em <b>${fmt(V)} L</b> de solução?`,mo,`n = ${fmt(round(n*M,2))} / ${fmt(M)} = ${fmt(n)} mol; M = n / V = ${fmt(n)} / ${fmt(V)} = <b>${fmt(mo)} mol/L</b>.`,'Calcule primeiro o número de mols (n = m/M) e depois divida pelo volume em litros.',{unit:'mol/L'}); },
 dil:lv=>{ const C1=pick([2,1,0.5,4,10]),V1=pick([100,200,50,250]),f=pick([2,4,5,10]),V2=V1*f,C2=round(C1/f,4);
   return NUM(`Uma solução de <b>${fmt(V1)} mL</b> a <b>${fmt(C1)} mol/L</b> é diluída com água até <b>${fmt(V2)} mL</b>. Qual é a nova concentração?`,C2,`C₁V₁ = C₂V₂ → ${fmt(C1)} × ${fmt(V1)} = C₂ × ${fmt(V2)} → C₂ = <b>${fmt(C2)} mol/L</b>. A quantidade de soluto não muda.`,'Na diluição, C₁·V₁ = C₂·V₂.',{unit:'mol/L'}); },
 ph:lv=>{ const k=R(1,13),t=R(0,2);
   if(t===0) return NUM(`Uma solução tem [H<sup>+</sup>] = 10<sup>−${k}</sup> mol/L. Qual é o pH (a 25 °C)?`,k,`pH = −log[H<sup>+</sup>] = −log 10<sup>−${k}</sup> = <b>${k}</b>.`,'pH = −log[H⁺]: o expoente com sinal trocado.');
   if(t===1) return NUM(`Uma solução tem pH = <b>${k}</b> (a 25 °C). Qual é o pOH?`,14-k,`pH + pOH = 14 → pOH = 14 − ${k} = <b>${14-k}</b>.`,'A 25 °C, pH + pOH = 14.');
   const cl=k<7?'ácida':k>7?'básica':'neutra'; return MC(`Uma solução com pH = <b>${k}</b> (a 25 °C) é:`,cl,['ácida','básica','neutra'].filter(x=>x!==cl),`pH < 7: ácida; pH = 7: neutra; pH > 7: básica. Aqui, pH ${k} → <b>${cl}</b>.`,'Compare o pH com 7.',{keep:true}); },
 part:lv=>{ const [s,nm,Z,A]=pick(ELEM),t=R(0,3);
   if(t===0) return NUM(`O átomo de ${nm} (<sup>${A}</sup>${s}) tem número atômico Z = ${Z}. Quantos <b>nêutrons</b> ele tem?`,A-Z,`N = A − Z = ${A} − ${Z} = <b>${A-Z}</b>.`,'A = Z + N (massa = prótons + nêutrons).');
   if(t===1) return NUM(`Quantos <b>elétrons</b> tem o átomo neutro de ${nm} (Z = ${Z})?`,Z,`No átomo neutro, elétrons = prótons = Z = <b>${Z}</b>.`,'Átomo neutro: nº de elétrons = nº de prótons.');
   const ions=[['Na',11,1],['K',19,1],['Mg',12,2],['Ca',20,2],['Al',13,3],['Cl',17,-1],['O',8,-2],['S',16,-2],['F',9,-1]]; const [is,iz,q]=pick(ions); const e=iz-q;
   return NUM(`Quantos elétrons tem o íon <b>${is}<sup>${Math.abs(q)>1?Math.abs(q):''}${q>0?'+':'−'}</sup></b> (Z = ${iz})?`,e,`${q>0?'Cátion: perdeu':'Ânion: ganhou'} ${Math.abs(q)} elétron(s): ${iz} ${q>0?'−':'+'} ${Math.abs(q)} = <b>${e}</b>.`,'Cátion perde elétrons; ânion ganha elétrons.'); },
 distrib:lv=>{ const z=pick(ZOK.filter(x=>x>=3)),d=paul(z),t=R(0,2);
   if(t===0){ const c=pstr(d),wr=new Set([pstr(paul(z+1)),pstr(paul(Math.max(1,z-1)))]);
     /* erro comum: preencher camada por camada (3d antes de 4s) */
     const shell=[]; let r=z; for(const [sb,cap] of [['1s',2],['2s',2],['2p',6],['3s',2],['3p',6],['3d',10],['4s',2],['4p',6],['4d',10],['5s',2],['5p',6]]){ if(r<=0)break; const k=Math.min(r,cap); shell.push([sb,k]); r-=k; }
     wr.add(pstr(shell)); wr.add(pstr(d.map(([sb,k],i)=>i===d.length-1?[sb,k+1]:[sb,k]))); wr.delete(c);
     return MC(`Qual é a distribuição eletrônica (diagrama de Linus Pauling) do átomo com <b>Z = ${z}</b>?`,c,shuffle([...wr]),`Seguindo 1s 2s 2p 3s 3p 4s 3d 4p…: <b>${c}</b>.`,'Preencha na ordem do diagrama: 1s, 2s, 2p, 3s, 3p, 4s, 3d, 4p (s cabe 2, p cabe 6, d cabe 10).'); }
   if(t===1){ const z2=pick(ZOK.filter(x=>x<=20||x>=31)); const v=valence(z2); return NUM(`Quantos elétrons há na <b>camada de valência</b> do átomo com Z = ${z2}?`,v,`Distribuição: ${pstr(paul(z2))}. A camada mais externa tem <b>${v}</b> elétron(s).`,'Faça a distribuição e some os elétrons da camada de maior número.'); }
   const last=d[d.length-1]; return MC(`Qual é o <b>subnível mais energético</b> do átomo com Z = ${z}?`,`${last[0]}<sup>${last[1]}</sup>`,shuffle(PAUL.map(p=>p[0]).filter(s=>s!==last[0])).map(s=>`${s}<sup>${Math.min(last[1],s.endsWith('s')?2:s.endsWith('p')?6:10)}</sup>`),`${pstr(d)} → o último subnível preenchido no diagrama é <b>${last[0]}<sup>${last[1]}</sup></b>.`,'É o último subnível da distribuição pela ordem de Pauling.'); },
 meia:lv=>{ const T=pick([5,8,10,20,30,1600]),k=R(1,4),m0=pick([80,160,64,200,320,100]),m=round(m0/2**k,4),un=T>=100?'anos':'dias';
   return NUM(`Um radioisótopo tem meia-vida de <b>${T} ${un}</b>. Partindo de <b>${m0} g</b>, quanto restará após <b>${T*k} ${un}</b>?`,m,`${T*k} ${un} = ${k} meias-vidas → ${m0} / 2<sup>${k}</sup> = <b>${fmt(m)} g</b>.`,'A cada meia-vida a massa cai pela metade.',{unit:'g'}); },
 esteq:lv=>{ const rx=[['CH4 + 2 O2 → CO2 + 2 H2O','CH4',16,'CO2',44,1,1],['2 H2 + O2 → 2 H2O','H2',2,'H2O',18,2,2],['N2 + 3 H2 → 2 NH3','N2',28,'NH3',17,1,2],['C + O2 → CO2','C',12,'CO2',44,1,1],['CaCO3 → CaO + CO2','CaCO3',100,'CO2',44,1,1]];
   const [eq,A,MA_,B,MB,a,b]=pick(rx); const nA=pick([1,2,3,0.5,5])*a; const m=round(nA*MA_,2),mb=round(nA/a*b*MB,2);
   return NUM(`Na reação <b>${fml(eq)}</b>, qual massa de ${fml(B)} é produzida a partir de <b>${fmt(m)} g</b> de ${fml(A)}?<br><small>Massas molares: ${fml(A)} = ${MA_} g/mol; ${fml(B)} = ${MB} g/mol</small>`,mb,`n(${fml(A)}) = ${fmt(m)} / ${MA_} = ${fmt(nA)} mol → proporção ${a}:${b} → n(${fml(B)}) = ${fmt(nA/a*b)} mol → m = ${fmt(nA/a*b)} × ${MB} = <b>${fmt(mb)} g</b>.`,'Converta massa em mol, use a proporção dos coeficientes e volte para massa.',{unit:'g'}); },
 hidro:lv=>{ const n=R(1,8),t=R(0,2); const pre=['met','et','prop','but','pent','hex','hept','oct'][n-1];
   if(t===0){ return MC(`Qual é a fórmula molecular do <b>${pre}ano</b> (alcano)?`,`C<sub>${n>1?n:''}</sub>H<sub>${2*n+2}</sub>`.replace('<sub></sub>',''),[`C<sub>${n}</sub>H<sub>${2*n}</sub>`,`C<sub>${n}</sub>H<sub>${2*n+4}</sub>`,`C<sub>${n+1}</sub>H<sub>${2*n+2}</sub>`,`C<sub>${n}</sub>H<sub>${Math.max(2,2*n-2)}</sub>`].map(x=>x.replace('<sub>1</sub>','')),`Alcanos: C<sub>n</sub>H<sub>2n+2</sub>. Com n = ${n}: <b>C${n>1?'<sub>'+n+'</sub>':''}H<sub>${2*n+2}</sub></b>.`,'Alcanos seguem CnH2n+2; alcenos CnH2n; alcinos CnH2n−2.'); }
   const m=Math.max(2,n); const pr=['','et','prop','but','pent','hex','hept','oct'][m-1]; const kind=t===1?['eno',2*m,'alceno (uma dupla)']:['ino',2*m-2,'alcino (uma tripla)'];
   return MC(`Qual é a fórmula molecular de um ${kind[2]} com <b>${m}</b> carbonos (${pr}${kind[0]})?`,`C<sub>${m}</sub>H<sub>${kind[1]}</sub>`,[`C<sub>${m}</sub>H<sub>${2*m+2}</sub>`,`C<sub>${m}</sub>H<sub>${t===1?2*m-2:2*m}</sub>`,`C<sub>${m}</sub>H<sub>${kind[1]+4}</sub>`],`${t===1?'Alcenos: C<sub>n</sub>H<sub>2n</sub>':'Alcinos: C<sub>n</sub>H<sub>2n−2</sub>'} → <b>C<sub>${m}</sub>H<sub>${kind[1]}</sub></b>.`,'Cada ligação dupla retira 2 H em relação ao alcano; cada tripla, 4.'); }
};

/* ------------------------ UNIDADE 1 — MATÉRIA ------------------------ */
UNITS.push({id:'q1',title:'Matéria e suas transformações',sub:'Estados físicos, substâncias, misturas, separação e fenômenos',color:'#ff9600',dark:'#e07b00',skills:[
SKL('estados','Estados físicos e mudanças de estado','🧊','Sólido → líquido: fusão; líquido → gasoso: vaporização; gasoso → líquido: condensação (liquefação); líquido → sólido: solidificação; sólido ↔ gasoso: sublimação.',
`<p>A matéria aparece em três estados principais: <b>sólido</b> (forma e volume fixos, partículas muito organizadas), <b>líquido</b> (volume fixo, forma do recipiente) e <b>gasoso</b> (forma e volume variáveis, partículas muito afastadas).</p>
<h3>Mudanças de estado</h3><ul><li><b>Fusão</b>: sólido → líquido. <b>Solidificação</b>: líquido → sólido.</li><li><b>Vaporização</b>: líquido → gás — pode ser <b>evaporação</b> (lenta, na superfície), <b>ebulição</b> (em toda a massa, na temperatura de ebulição) ou <b>calefação</b> (brusca, ao cair em superfície muito quente).</li><li><b>Condensação/liquefação</b>: gás → líquido.</li><li><b>Sublimação</b>: sólido → gás (gelo-seco, naftalina); o inverso é chamado de <b>ressublimação</b> (ou deposição).</li></ul>
<p>Fusão, vaporização e sublimação <b>absorvem</b> calor (endotérmicas); as inversas <b>liberam</b> calor (exotérmicas).</p>
<div class="ex">Substância pura muda de estado em temperatura constante (patamar no gráfico); mistura, em geral, não.</div>`,
{pairs:[['Fusão','passagem do estado sólido para o líquido'],['Solidificação','passagem do estado líquido para o sólido'],['Evaporação','vaporização lenta, que ocorre na superfície do líquido'],['Ebulição','vaporização rápida, em toda a massa do líquido'],['Condensação','passagem do estado gasoso para o líquido'],['Sublimação','passagem direta do sólido para o gasoso'],['Calefação','vaporização brusca de um líquido que cai em superfície muito quente']],
 qs:[['O gelo-seco (CO<sub>2</sub> sólido) "solta fumaça" sem derreter. Isso ocorre por:','sublimação',['fusão','evaporação','condensação'],'Passa direto de sólido a gás: <b>sublimação</b>.'],['A roupa secando no varal é um exemplo de:','evaporação',['ebulição','calefação','fusão'],'Vaporização lenta, na superfície: <b>evaporação</b>.'],['As gotas que se formam do lado de fora de um copo com gelo resultam da:','condensação do vapor de água do ar',['evaporação da água do copo','fusão do vidro','sublimação do gelo'],'O vapor do ar esfria ao tocar o copo e <b>condensa</b>.'],['Qual mudança de estado LIBERA calor?','solidificação',['fusão','vaporização','sublimação'],'Solidificação, condensação e ressublimação são <b>exotérmicas</b>.'],['No gráfico de aquecimento de uma substância pura, os patamares (trechos horizontais) indicam:','mudanças de estado em temperatura constante',['aumento da temperatura','erros de medição','mistura de substâncias'],'Durante a mudança de estado de substância pura, a temperatura fica constante.']]}),
SKL('mistura','Substâncias e misturas','🥤','Substância simples: um só elemento (O₂); composta: mais de um (H₂O). Mistura homogênea tem uma fase; heterogênea, duas ou mais.',
`<ul><li><b>Substância simples</b>: formada por um só elemento químico (<i>O<sub>2</sub>, O<sub>3</sub>, Fe, H<sub>2</sub></i>).</li><li><b>Substância composta</b>: dois ou mais elementos (<i>H<sub>2</sub>O, NaCl, CO<sub>2</sub></i>).</li><li><b>Alotropia</b>: um elemento formando substâncias simples diferentes (<i>O<sub>2</sub> e O<sub>3</sub>; diamante, grafite e fulereno</i>).</li></ul>
<ul><li><b>Mistura homogênea (solução)</b>: uma única fase (<i>água com sal dissolvido, ar filtrado, álcool 70%</i>).</li><li><b>Mistura heterogênea</b>: duas ou mais fases (<i>água e óleo, granito</i>).</li></ul>
<div class="ex">Água com gelo: uma substância, duas fases → <b>sistema heterogêneo</b>, mas é <b>substância pura</b>.</div>`,
{pairs:[['O<sub>2</sub>','substância simples'],['H<sub>2</sub>O','substância composta'],['Água e óleo','mistura heterogênea'],['Água e sal dissolvido','mistura homogênea (solução)'],['Diamante e grafite','formas alotrópicas do carbono'],['Ozônio (O<sub>3</sub>)','substância simples, alótropo do oxigênio'],['Granito','mistura heterogênea (quartzo, feldspato e mica)'],['NaCl','substância composta']],tq:t=>`<b>${t}</b> é classificado(a) como:`,dq:d=>`Qual exemplo é <b>${d}</b>?`,
 qs:[['Um sistema formado por água líquida e gelo é:','substância pura em sistema heterogêneo',['mistura homogênea','mistura heterogênea de duas substâncias','substância composta em sistema homogêneo'],'Só há água (substância pura), mas em duas fases.'],['O ar atmosférico filtrado (sem poeira) é:','mistura homogênea',['substância simples','substância composta','mistura heterogênea'],'Gases sempre se misturam formando uma só fase.'],['O fenômeno em que um mesmo elemento forma substâncias simples diferentes chama-se:','alotropia',['isomeria','isotopia','sublimação'],'Ex.: O<sub>2</sub> e O<sub>3</sub>; diamante e grafite.']]}),
SKL('separa','Separação de misturas','🧪','Heterogêneas: filtração, decantação, centrifugação, catação. Homogêneas: destilação simples (sólido + líquido) e fracionada (líquidos).',
`<h3>Misturas heterogêneas</h3><ul><li><b>Filtração</b>: sólido não dissolvido + líquido (café no filtro).</li><li><b>Decantação</b>: por diferença de densidade — água e areia; líquidos imiscíveis no <b>funil de separação</b> (água e óleo).</li><li><b>Centrifugação</b>: acelera a decantação (separar componentes do sangue, nata do leite).</li><li><b>Catação, peneiração, ventilação, separação magnética</b> (ferro com ímã), <b>dissolução fracionada</b> (sal e areia com água).</li></ul>
<h3>Misturas homogêneas</h3><ul><li><b>Destilação simples</b>: sólido dissolvido em líquido (obter água pura da água do mar).</li><li><b>Destilação fracionada</b>: líquidos com pontos de ebulição diferentes (petróleo, álcool).</li><li><b>Evaporação/cristalização</b>: obter o sólido (sal nas salinas).</li><li><b>Liquefação fracionada</b>: separar gases do ar.</li><li><b>Cromatografia</b>: separar pigmentos.</li></ul>`,
{pairs:[['Filtração','separa sólido não dissolvido de um líquido, como o pó de café'],['Decantação','separa componentes por diferença de densidade, deixando-os em repouso'],['Destilação simples','separa um sólido dissolvido de um líquido, como na dessalinização'],['Destilação fracionada','separa líquidos com pontos de ebulição diferentes, como no petróleo'],['Separação magnética','separa materiais atraídos por ímã, como limalha de ferro'],['Centrifugação','acelera a sedimentação girando a mistura em alta velocidade'],['Cromatografia','separa pigmentos pela diferença de arraste em um suporte'],['Evaporação','obtém o sólido dissolvido deixando o líquido evaporar, como nas salinas']],tq:t=>`Para que serve a <b>${t}</b>?`,dq:d=>`Qual método <b>${d}</b>?`,
 qs:[['Para separar água e óleo, o método mais adequado é:','decantação em funil de separação',['filtração','destilação simples','separação magnética'],'Líquidos imiscíveis com densidades diferentes: funil de separação.'],['As refinarias separam o petróleo em frações (gás, gasolina, diesel…) por:','destilação fracionada',['filtração','catação','centrifugação'],'Frações com diferentes pontos de ebulição: <b>destilação fracionada</b>.'],['Nas salinas, o sal é obtido da água do mar por:','evaporação',['filtração','decantação','destilação fracionada'],'O Sol evapora a água e o sal cristaliza.'],['Para separar sal e areia, a sequência correta é:','dissolução em água, filtração e evaporação',['filtração e decantação','destilação e catação','separação magnética e filtração'],'O sal dissolve, a areia fica no filtro e depois se evapora a água: <b>dissolução fracionada</b>.']]}),
SKL('fenom','Fenômenos físicos e químicos','🔥','Fenômeno químico forma novas substâncias (queima, ferrugem, digestão); físico não muda a composição (derreter, quebrar, dissolver).',
`<p><b>Fenômeno físico</b>: a substância continua a mesma (<i>gelo derretendo, papel rasgado, açúcar dissolvido</i>).</p>
<p><b>Fenômeno químico (reação química)</b>: formam-se novas substâncias (<i>queima, ferrugem, cozimento, fermentação, digestão, fotossíntese</i>).</p>
<h3>Evidências de reação química</h3><p>Liberação de gás (efervescência), mudança de cor, formação de precipitado (sólido), liberação ou absorção de calor e luz, mudança de cheiro.</p>
<h3>Leis ponderais</h3><ul><li><b>Lavoisier</b> (conservação da massa): num sistema fechado, massa dos reagentes = massa dos produtos. "Na natureza nada se cria, nada se perde, tudo se transforma."</li><li><b>Proust</b> (proporções constantes): uma substância tem sempre a mesma proporção em massa entre seus elementos.</li></ul>`,
{qs:[['Qual é um fenômeno químico?','o apodrecimento de uma fruta',['o derretimento de um sorvete','a quebra de um copo','a dissolução de açúcar no café'],'Formam-se novas substâncias: <b>químico</b>.'],['Qual é um fenômeno físico?','a evaporação da água',['a queima do papel','o enferrujamento de um prego','a fermentação da massa do pão'],'A água continua sendo água: <b>físico</b>.'],['"Na natureza nada se cria, nada se perde, tudo se transforma" resume a lei de:','Lavoisier',['Proust','Dalton','Avogadro'],'Lei da conservação da massa (Lavoisier).'],['Ao queimar 12 g de carbono com 32 g de oxigênio num sistema fechado, a massa de gás carbônico formada é:','44 g',['20 g','12 g','32 g'],'Lavoisier: 12 + 32 = <b>44 g</b>.'],['Um comprimido efervescente na água libera bolhas de gás. Isso é evidência de:','reação química',['mudança de estado','dissolução física apenas','sublimação'],'Formação de gás novo (CO<sub>2</sub>) indica <b>reação química</b>.']],
 tf:[['A formação de ferrugem é um fenômeno químico.',true,'Verdadeiro: forma-se óxido de ferro.'],['Rasgar uma folha de papel é um fenômeno químico.',false,'Falso: é físico, o papel continua sendo papel.'],['Numa reação em sistema fechado, a massa total se conserva.',true,'Verdadeiro: Lei de Lavoisier.']]})
]});

/* ------------------------ UNIDADE 2 — ÁTOMO E TABELA ------------------------ */
UNITS.push({id:'q2',title:'Átomo e tabela periódica',sub:'Modelos atômicos, partículas, distribuição eletrônica e propriedades periódicas',color:'#1cb0f6',dark:'#1899d6',skills:[
SKL('modelos','Modelos atômicos','⚛️','Dalton: bola maciça; Thomson: "pudim de passas"; Rutherford: núcleo pequeno e denso com eletrosfera; Bohr: elétrons em níveis de energia.',
`<ul><li><b>Dalton (1808)</b>: átomo como esfera maciça e indivisível ("bola de bilhar").</li><li><b>Thomson (1897)</b>: descobre o <b>elétron</b>; átomo como esfera positiva com elétrons incrustados ("pudim de passas").</li><li><b>Rutherford (1911)</b>: experimento da folha de ouro — a maioria das partículas alfa atravessa: átomo com <b>núcleo pequeno, denso e positivo</b> e grande <b>eletrosfera</b> vazia ("modelo planetário").</li><li><b>Bohr (1913)</b>: elétrons em <b>órbitas (níveis) de energia</b> definidas; ao saltar para um nível mais baixo, emitem luz (explica os espectros e os fogos de artifício).</li></ul>`,
{pairs:[['Dalton','modelo da esfera maciça e indivisível ("bola de bilhar")'],['Thomson','modelo do "pudim de passas", com elétrons incrustados numa esfera positiva'],['Rutherford','modelo com núcleo pequeno, denso e positivo, cercado pela eletrosfera'],['Bohr','modelo com elétrons em níveis de energia definidos']],tq:t=>`Qual foi a proposta de <b>${t}</b> para o átomo?`,dq:d=>`Quem propôs o <b>${d}</b>?`,
 qs:[['No experimento de Rutherford, a maioria das partículas alfa atravessou a lâmina de ouro. Isso indicou que:','o átomo é formado em grande parte por espaço vazio',['o átomo é maciço','os elétrons ficam no núcleo','o núcleo é negativo'],'Grande parte do átomo é <b>vazia</b>; o núcleo é pequeno e denso.'],['As cores dos fogos de artifício são explicadas pelo modelo de:','Bohr',['Dalton','Thomson','Rutherford'],'Elétrons excitados voltam a níveis menores e emitem luz de cor característica: <b>Bohr</b>.'],['Qual partícula foi descoberta por Thomson?','elétron',['próton','nêutron','núcleo'],'Thomson descobriu o <b>elétron</b> (raios catódicos, 1897).']]}),
SKL('particulas','Prótons, nêutrons e elétrons','🔬','Z = prótons; A = prótons + nêutrons; no átomo neutro, elétrons = prótons. Cátion perde elétrons; ânion ganha.',
`<p>O <b>número atômico (Z)</b> é o número de prótons e identifica o elemento. O <b>número de massa (A)</b> é a soma de prótons e nêutrons: <b>A = Z + N</b>.</p>
<p>No átomo neutro, o número de elétrons é igual ao de prótons. <b>Íons</b>: <b>cátion</b> (positivo) perdeu elétrons; <b>ânion</b> (negativo) ganhou elétrons.</p>
<ul><li><b>Isótopos</b>: mesmo Z, A diferente (<sup>1</sup>H, <sup>2</sup>H, <sup>3</sup>H).</li><li><b>Isóbaros</b>: mesmo A, Z diferente.</li><li><b>Isótonos</b>: mesmo número de nêutrons.</li><li><b>Isoeletrônicos</b>: mesmo número de elétrons (Na<sup>+</sup>, Ne, F<sup>−</sup>).</li></ul>`,
{gens:[quiGens.part,quiGens.part],pairs:[['Isótopos','átomos com o mesmo número de prótons e massas diferentes'],['Isóbaros','átomos com o mesmo número de massa e números atômicos diferentes'],['Isótonos','átomos com o mesmo número de nêutrons'],['Isoeletrônicos','espécies com o mesmo número de elétrons'],['Cátion','íon positivo, que perdeu elétrons'],['Ânion','íon negativo, que ganhou elétrons'],['Número atômico (Z)','número de prótons do núcleo']]}),
SKL('distrib','Distribuição eletrônica','🪜','Ordem de Pauling: 1s 2s 2p 3s 3p 4s 3d 4p 5s 4d 5p… Subnível s cabe 2 elétrons, p cabe 6, d cabe 10, f cabe 14.',
`<p>Os elétrons ocupam <b>níveis</b> (camadas K, L, M, N… = 1, 2, 3, 4…) divididos em <b>subníveis</b> s, p, d, f, com capacidade de 2, 6, 10 e 14 elétrons.</p>
<p>O <b>diagrama de Linus Pauling</b> dá a ordem crescente de energia: <b>1s 2s 2p 3s 3p 4s 3d 4p 5s 4d 5p 6s 4f 5d 6p…</b> (repare que o 4s vem antes do 3d).</p>
<div class="ex">Ferro (Z = 26): 1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁶. Camada de valência: 4 (com 2 elétrons). Subnível mais energético: 3d⁶.</div>
<p>A <b>camada de valência</b> é a mais externa; para elementos representativos, o número de elétrons nela coincide com o final do número do grupo (ex.: grupo 17 → 7 elétrons).</p>`,
{gens:[quiGens.distrib,quiGens.distrib,quiGens.distrib],tf:[['O subnível 4s é preenchido antes do 3d no diagrama de Pauling.',true,'Verdadeiro: 4s tem energia menor que 3d.'],['O subnível p comporta no máximo 10 elétrons.',false,'Falso: p comporta 6; d comporta 10.'],['A camada de valência é a camada mais externa do átomo.',true,'Verdadeiro.']]}),
SKL('tabela','Tabela periódica','🗂️','Linhas = períodos (número de camadas); colunas = grupos/famílias (propriedades semelhantes). Grupo 1: alcalinos; 17: halogênios; 18: gases nobres.',
`<p>Os elementos estão em ordem crescente de <b>número atômico</b>. <b>Períodos</b> (7 linhas) indicam o número de camadas; <b>grupos</b> ou famílias (18 colunas) reúnem elementos com propriedades semelhantes.</p>
<table><tr><th>Grupo</th><th>Família</th></tr><tr><td>1</td><td>Metais alcalinos (Li, Na, K…)</td></tr><tr><td>2</td><td>Metais alcalinoterrosos (Be, Mg, Ca…)</td></tr><tr><td>13</td><td>Família do boro</td></tr><tr><td>14</td><td>Família do carbono</td></tr><tr><td>15</td><td>Família do nitrogênio</td></tr><tr><td>16</td><td>Calcogênios (O, S…)</td></tr><tr><td>17</td><td>Halogênios (F, Cl, Br, I)</td></tr><tr><td>18</td><td>Gases nobres (He, Ne, Ar…)</td></tr></table>
<p><b>Metais</b> (maioria; bons condutores, brilho), <b>ametais</b>, <b>gases nobres</b> e o <b>hidrogênio</b> (sem família). Grupos 3 a 12: <b>metais de transição</b>.</p>`,
{pairs:ELEM.filter(e=>!['Ne','Ar','Li','F','Si'].includes(e[0])).map(e=>[e[0],e[1]]),tq:t=>`Qual é o nome do elemento de símbolo <b>${t}</b>?`,dq:d=>`Qual é o símbolo do elemento <b>${d}</b>?`,tfq:(t,d)=>`O símbolo <b>${t}</b> representa o elemento ${d}.`,
 qs:[['O sódio (Na) e o potássio (K) pertencem à família dos:','metais alcalinos',['halogênios','gases nobres','calcogênios'],'Grupo 1: <b>metais alcalinos</b>.'],['O cloro, o bromo e o iodo pertencem à família dos:','halogênios',['metais alcalinos','gases nobres','alcalinoterrosos'],'Grupo 17: <b>halogênios</b>.'],['Os gases nobres praticamente não reagem porque:','têm a camada de valência completa',['são metais','têm poucos prótons','são radioativos'],'Camada de valência completa (8 elétrons, ou 2 no hélio).'],['Um elemento com 3 camadas eletrônicas está no:','3º período',['3º grupo','grupo 13','3ª família'],'O número de camadas indica o <b>período</b>.'],['O cálcio e o magnésio pertencem à família dos:','metais alcalinoterrosos',['metais alcalinos','calcogênios','halogênios'],'Grupo 2.']]}),
SKL('propper','Propriedades periódicas','📈','Raio atômico cresce para baixo e para a esquerda; eletronegatividade e energia de ionização crescem para cima e para a direita (flúor é o mais eletronegativo).',
`<ul><li><b>Raio atômico</b>: aumenta de cima para baixo (mais camadas) e da direita para a esquerda (menos prótons atraindo).</li><li><b>Energia de ionização</b>: energia para retirar um elétron — aumenta de baixo para cima e da esquerda para a direita.</li><li><b>Eletronegatividade</b>: tendência de atrair elétrons numa ligação — mesma tendência da energia de ionização. Mais eletronegativo: <b>flúor</b> (F > O > N ≈ Cl…).</li><li><b>Caráter metálico</b> (eletropositividade): oposto da eletronegatividade.</li></ul>
<div class="ex">Cátion tem raio menor que o átomo neutro; ânion tem raio maior.</div>`,
{qs:[['Qual é o elemento mais eletronegativo da tabela periódica?','flúor',['oxigênio','cloro','hélio'],'O <b>flúor</b> tem a maior eletronegatividade.'],['Num mesmo grupo, de cima para baixo, o raio atômico:','aumenta',['diminui','não muda','zera'],'Aumenta o número de camadas: o raio <b>aumenta</b>.'],['Num mesmo período, da esquerda para a direita, a energia de ionização tende a:','aumentar',['diminuir','ficar constante','se anular'],'Mais prótons, elétrons mais presos: <b>aumenta</b>.'],['Comparando Na e Na<sup>+</sup>, o raio do íon é:','menor',['maior','igual','nulo'],'Ao perder o elétron (e uma camada), o cátion fica <b>menor</b>.'],['Entre K, Na e Li (grupo 1), o de maior raio atômico é:','K',['Na','Li','os três são iguais'],'Mais abaixo no grupo: mais camadas.']]})
]});

/* ------------------------ UNIDADE 3 — LIGAÇÕES E FUNÇÕES ------------------------ */
UNITS.push({id:'q3',title:'Ligações e funções inorgânicas',sub:'Ligações, polaridade, forças intermoleculares, ácidos, bases, sais, óxidos e pH',color:'#ce82ff',dark:'#a568cc',skills:[
SKL('ligacoes','Ligações químicas','🔗','Iônica: metal + ametal (transferência de elétrons); covalente: ametal + ametal (compartilhamento); metálica: entre metais (mar de elétrons).',
`<p>Pela <b>regra do octeto</b>, os átomos tendem a ficar com 8 elétrons na camada de valência (ou 2, como o hélio).</p>
<ul><li><b>Iônica</b>: entre <b>metal e ametal</b>; o metal <b>doa</b> elétrons e o ametal <b>recebe</b>, formando íons (<i>NaCl</i>). Compostos iônicos: sólidos, altos pontos de fusão, conduzem corrente <b>fundidos ou em solução</b>.</li><li><b>Covalente (molecular)</b>: entre <b>ametais</b> (e H); os átomos <b>compartilham</b> pares de elétrons (<i>H<sub>2</sub>O, CO<sub>2</sub>, CH<sub>4</sub></i>). Pode ser simples, dupla ou tripla.</li><li><b>Metálica</b>: entre metais; cátions imersos num "mar de elétrons" livres — explica condutividade, brilho e maleabilidade.</li></ul>`,
{pairs:[['NaCl','ligação iônica (metal + ametal)'],['H<sub>2</sub>O','ligação covalente (ametal + ametal)'],['Fio de cobre','ligação metálica'],['CO<sub>2</sub>','ligação covalente com ligações duplas'],['KBr','ligação iônica'],['CH<sub>4</sub>','ligação covalente'],['Barra de ferro','ligação metálica'],['MgO','ligação iônica']],tq:t=>`Que tipo de ligação há em <b>${t}</b>?`,dq:d=>`Qual substância apresenta <b>${d}</b>?`,noTF:true,
 qs:[['O sal de cozinha dissolvido em água conduz corrente elétrica porque:','libera íons livres em solução',['tem elétrons livres como os metais','é covalente','forma moléculas neutras'],'Composto iônico dissolvido libera íons que conduzem corrente.'],['Os metais conduzem bem a eletricidade por causa:','dos elétrons livres da ligação metálica',['dos íons em solução','das ligações covalentes','dos nêutrons'],'O "mar de elétrons" permite a condução.'],['Na molécula de N<sub>2</sub>, os átomos estão unidos por:','uma ligação tripla',['uma ligação simples','uma ligação iônica','uma ligação metálica'],'Cada N compartilha 3 pares: N≡N.']]}),
SKL('interm','Polaridade e forças intermoleculares','🧲','Ligações de hidrogênio (H ligado a F, O ou N) são as mais fortes; depois dipolo-dipolo; as mais fracas são as de London (dipolo induzido).',
`<p>Uma molécula é <b>polar</b> quando a distribuição de cargas é assimétrica (<i>H<sub>2</sub>O, HCl, NH<sub>3</sub></i>) e <b>apolar</b> quando é simétrica (<i>CO<sub>2</sub>, CH<sub>4</sub>, O<sub>2</sub></i>).</p>
<p><b>"Semelhante dissolve semelhante"</b>: polar dissolve polar (sal e açúcar em água); apolar dissolve apolar (gordura em gasolina). Sabões e detergentes têm uma parte polar e outra apolar.</p>
<h3>Forças intermoleculares (da mais forte para a mais fraca)</h3><ol><li><b>Ligações de hidrogênio</b>: H ligado a F, O ou N (água, álcool, DNA).</li><li><b>Dipolo-dipolo (dipolo permanente)</b>: entre moléculas polares (HCl).</li><li><b>Dipolo induzido (London)</b>: entre moléculas apolares (CH<sub>4</sub>, I<sub>2</sub>).</li></ol>
<p>Quanto mais fortes as forças, maior o <b>ponto de ebulição</b>.</p>`,
{qs:[['A água tem ponto de ebulição alto para uma molécula tão pequena por causa das:','ligações de hidrogênio',['forças de London','ligações iônicas','ligações metálicas'],'H ligado a O forma <b>ligações de hidrogênio</b>, fortes.'],['O óleo não se mistura com a água porque:','o óleo é apolar e a água é polar',['ambos são polares','ambos são apolares','o óleo é iônico'],'Semelhante dissolve semelhante.'],['A molécula de CO<sub>2</sub> é apolar porque:','é linear e simétrica, e as polaridades se anulam',['não tem ligações','é iônica','tem hidrogênio'],'O=C=O é linear: os vetores se anulam.'],['Entre moléculas de metano (CH<sub>4</sub>) atuam principalmente forças:','de dipolo induzido (London)',['de ligação de hidrogênio','dipolo-dipolo','iônicas'],'CH<sub>4</sub> é apolar: <b>London</b>.'],['O sabão remove a gordura porque:','tem uma parte apolar que interage com a gordura e outra polar que interage com a água',['é totalmente polar','é totalmente apolar','reage com a água formando gás'],'Molécula anfipática: forma micelas.']]}),
SKL('funcinorg','Ácidos, bases, sais e óxidos','🧫','Ácido libera H⁺ em água (Arrhenius); base libera OH⁻; ácido + base → sal + água (neutralização).',
`<ul><li><b>Ácidos</b> (Arrhenius): em água liberam <b>H<sup>+</sup></b> (H<sub>3</sub>O<sup>+</sup>). Sabor azedo, pH &lt; 7. Nomes: hidrácidos em <b>-ídrico</b> (HCl, clorídrico); oxiácidos em <b>-ico/-oso</b> (H<sub>2</sub>SO<sub>4</sub>, sulfúrico).</li><li><b>Bases</b>: em água liberam <b>OH<sup>−</sup></b>. Sabor adstringente, pH &gt; 7 (<i>NaOH, soda cáustica; Mg(OH)<sub>2</sub>, leite de magnésia</i>).</li><li><b>Sais</b>: formados na <b>neutralização</b> ácido + base → sal + água (<i>HCl + NaOH → NaCl + H<sub>2</sub>O</i>).</li><li><b>Óxidos</b>: compostos binários com oxigênio como o elemento mais eletronegativo. Óxidos ácidos (CO<sub>2</sub>, SO<sub>2</sub>, NO<sub>2</sub>) causam a <b>chuva ácida</b>; óxidos básicos (CaO, cal virgem).</li></ul>
<p><b>Indicadores</b>: fenolftaleína fica rosa em meio básico e incolor em meio ácido; papel de tornassol azul fica vermelho em ácido.</p>`,
{pairs:[['HCl','ácido clorídrico'],['H<sub>2</sub>SO<sub>4</sub>','ácido sulfúrico'],['HNO<sub>3</sub>','ácido nítrico'],['H<sub>3</sub>PO<sub>4</sub>','ácido fosfórico'],['H<sub>2</sub>CO<sub>3</sub>','ácido carbônico'],['NaOH','hidróxido de sódio (soda cáustica)'],['Ca(OH)<sub>2</sub>','hidróxido de cálcio (cal hidratada)'],['NaCl','cloreto de sódio'],['CaCO<sub>3</sub>','carbonato de cálcio (calcário)'],['NaHCO<sub>3</sub>','hidrogenocarbonato de sódio (bicarbonato de sódio)'],['CaO','óxido de cálcio (cal virgem)'],['KNO<sub>3</sub>','nitrato de potássio']],tq:t=>`Qual é o nome de <b>${t}</b>?`,dq:d=>`Qual é a fórmula do <b>${d}</b>?`,noTF:true,
 qs:[['A reação HCl + NaOH → NaCl + H<sub>2</sub>O é uma:','neutralização',['combustão','decomposição','oxirredução'],'Ácido + base → sal + água.'],['A chuva ácida é causada principalmente por:','óxidos de enxofre e de nitrogênio',['óxido de cálcio','gás oxigênio','gás nitrogênio (N<sub>2</sub>)'],'SO<sub>2</sub>, SO<sub>3</sub> e NO<sub>2</sub> formam ácidos com a água da chuva.'],['A fenolftaleína fica rosa em meio:','básico',['ácido','neutro','qualquer meio'],'Fenolftaleína: incolor em ácido, <b>rosa em base</b>.'],['Segundo Arrhenius, uma base é a substância que, em água:','libera íons OH<sup>−</sup>',['libera íons H<sup>+</sup>','não se dissocia','libera elétrons'],'Base de Arrhenius: libera <b>OH<sup>−</sup></b>.'],['O leite de magnésia, usado contra a acidez do estômago, é:','uma base, Mg(OH)<sub>2</sub>',['um ácido','um sal neutro','um óxido ácido'],'Hidróxido de magnésio neutraliza o excesso de HCl.']]}),
SKL('ph','pH e pOH','🧾','pH = −log[H⁺]. A 25 °C: pH < 7 ácido, = 7 neutro, > 7 básico, e pH + pOH = 14. Cada unidade de pH muda a acidez 10 vezes.',
`<p>O <b>pH</b> mede a concentração de íons H<sup>+</sup>: <b>pH = −log[H<sup>+</sup>]</b>. Se [H<sup>+</sup>] = 10<sup>−3</sup> mol/L, o pH é 3.</p>
<p>A 25 °C: <b>pH &lt; 7 → ácido</b>; <b>pH = 7 → neutro</b>; <b>pH &gt; 7 → básico</b>. Também vale <b>pH + pOH = 14</b>.</p>
<div class="ex">Uma solução de pH 3 é <b>10 vezes</b> mais ácida que uma de pH 4 e <b>100 vezes</b> mais ácida que uma de pH 5.</div>
<p>Exemplos: suco gástrico (pH ≈ 1–2), vinagre (≈ 3), água pura (7), sangue (≈ 7,4), água sanitária (≈ 12).</p>`,
{gens:[quiGens.ph,quiGens.ph,quiGens.ph],qs:[['Uma solução de pH 2 é quantas vezes mais ácida que uma de pH 4?','100 vezes',['2 vezes','10 vezes','20 vezes'],'Cada unidade = 10×: 10 × 10 = <b>100 vezes</b>.'],['O sangue humano tem pH ≈ 7,4. Ele é:','levemente básico',['fortemente ácido','neutro exato','fortemente básico'],'Um pouco acima de 7: levemente básico.']]})
]});

/* ------------------------ UNIDADE 4 — CÁLCULOS QUÍMICOS ------------------------ */
UNITS.push({id:'q4',title:'Cálculos químicos',sub:'Massa molar, mol, concentração, diluição, balanceamento e estequiometria',color:'#ff4b4b',dark:'#ea2b2b',skills:[
SKL('massamol','Massa molar e mol','⚖️','n = m / M. 1 mol tem 6 × 10²³ partículas e sua massa em gramas é a massa molar.',
`<p><b>Massa molar (M)</b> é a massa de 1 mol da substância, em g/mol: soma das massas atômicas dos átomos da fórmula.</p><div class="formula">M(H<sub>2</sub>O) = 2 × 1 + 16 = 18 g/mol</div>
<p><b>Mol</b> é a unidade de quantidade de matéria: <b>1 mol = 6,02 × 10<sup>23</sup> partículas</b> (constante de Avogadro).</p><div class="formula">n = m / M</div>
<div class="ex">36 g de água = 36 / 18 = <b>2 mol</b> = 2 × 6 × 10<sup>23</sup> = <b>1,2 × 10<sup>24</sup> moléculas</b>.</div>
<p>Nas CNTP, 1 mol de gás ideal ocupa cerca de <b>22,4 L</b>.</p>`,
{gens:[quiGens.molar,quiGens.molar,quiGens.mol,quiGens.mol,quiGens.avog]}),
SKL('concentra','Concentração de soluções','🥛','Concentração comum C = m/V (g/L); concentração em quantidade de matéria = n/V (mol/L).',
`<p>Numa <b>solução</b>, o <b>soluto</b> é dissolvido no <b>solvente</b>.</p><ul><li><b>Concentração comum</b>: C = massa do soluto (g) / volume da solução (L) → g/L.</li><li><b>Concentração em mol/L</b> (molaridade): n / V.</li><li><b>Título / porcentagem em massa</b>: massa do soluto / massa da solução.</li><li><b>ppm</b>: partes por milhão (1 mg/kg ou ≈ 1 mg/L em água).</li></ul>
<div class="ex">20 g de NaCl em 500 mL: C = 20 / 0,5 = <b>40 g/L</b>.</div>
<p><b>Solubilidade</b>: quantidade máxima de soluto que se dissolve numa quantidade de solvente. Acima dela a solução é <b>saturada com corpo de fundo</b>.</p>`,
{gens:[quiGens.conc,quiGens.conc,quiGens.molar2,quiGens.molar2]}),
SKL('diluicao','Diluição e mistura de soluções','💧','Na diluição a quantidade de soluto não muda: C₁·V₁ = C₂·V₂.',
`<p><b>Diluir</b> é acrescentar solvente: o volume aumenta, a concentração diminui e a <b>quantidade de soluto é a mesma</b>.</p><div class="formula">C₁ · V₁ = C₂ · V₂</div>
<div class="ex">100 mL de solução 2 mol/L diluída até 400 mL: C₂ = 2 × 100 / 400 = <b>0,5 mol/L</b>.</div>
<p><b>Mistura de soluções de mesmo soluto</b>: C<sub>final</sub> = (C₁V₁ + C₂V₂) / (V₁ + V₂).</p>`,
{gens:[quiGens.dil,quiGens.dil,quiGens.dil],tf:[['Ao diluir uma solução, a massa de soluto diminui.',false,'Falso: só se acrescenta solvente; a massa de soluto se mantém.'],['Dobrando o volume por diluição, a concentração cai pela metade.',true,'Verdadeiro: C₁V₁ = C₂V₂.']]}),
SKL('balanc','Equações e balanceamento','⚗️','Balancear é igualar o número de átomos de cada elemento nos dois lados, ajustando só os coeficientes.',
`<p>Uma equação química mostra reagentes → produtos. <b>Balancear</b> é escolher coeficientes para que cada elemento tenha o mesmo número de átomos dos dois lados (Lavoisier). Nunca se mudam os índices das fórmulas.</p>
<div class="ex">CH<sub>4</sub> + <b>2</b> O<sub>2</sub> → CO<sub>2</sub> + <b>2</b> H<sub>2</sub>O (C: 1 = 1; H: 4 = 4; O: 4 = 2 + 2).</div>
<p>Método das tentativas: comece pelo elemento que aparece em menos substâncias, deixe H e O por último e, se preciso, use frações e depois multiplique.</p>
<h3>Tipos de reação</h3><p><b>Síntese</b> (A + B → AB), <b>análise/decomposição</b> (AB → A + B), <b>simples troca</b> (A + BC → AC + B) e <b>dupla troca</b> (AB + CD → AD + CB).</p>`,
{qs:[['Quais são os menores coeficientes inteiros que balanceiam: __ H<sub>2</sub> + __ O<sub>2</sub> → __ H<sub>2</sub>O?','2, 1, 2',['1, 1, 1','1, 2, 1','2, 2, 2'],'2 H<sub>2</sub> + O<sub>2</sub> → 2 H<sub>2</sub>O: 4 H e 2 O de cada lado.'],['Balanceie: __ N<sub>2</sub> + __ H<sub>2</sub> → __ NH<sub>3</sub>','1, 3, 2',['1, 1, 2','2, 3, 1','1, 3, 1'],'N<sub>2</sub> + 3 H<sub>2</sub> → 2 NH<sub>3</sub> (síntese da amônia).'],['Balanceie: __ C<sub>3</sub>H<sub>8</sub> + __ O<sub>2</sub> → __ CO<sub>2</sub> + __ H<sub>2</sub>O','1, 5, 3, 4',['1, 3, 3, 4','2, 5, 3, 4','1, 5, 4, 3'],'C: 3; H: 8 → 4 H<sub>2</sub>O; O: 6 + 4 = 10 → 5 O<sub>2</sub>.'],['Balanceie: __ Fe + __ O<sub>2</sub> → __ Fe<sub>2</sub>O<sub>3</sub>','4, 3, 2',['2, 3, 1','4, 2, 2','2, 1, 1'],'4 Fe + 3 O<sub>2</sub> → 2 Fe<sub>2</sub>O<sub>3</sub>.'],['A reação CaCO<sub>3</sub> → CaO + CO<sub>2</sub> é de:','decomposição (análise)',['síntese','simples troca','dupla troca'],'Uma substância origina duas: <b>análise</b>.'],['A reação Zn + 2 HCl → ZnCl<sub>2</sub> + H<sub>2</sub> é de:','simples troca (deslocamento)',['síntese','decomposição','dupla troca'],'O zinco desloca o hidrogênio: <b>simples troca</b>.'],['Balanceie: __ Al + __ O<sub>2</sub> → __ Al<sub>2</sub>O<sub>3</sub>','4, 3, 2',['2, 3, 1','4, 3, 1','2, 1, 1'],'4 Al + 3 O<sub>2</sub> → 2 Al<sub>2</sub>O<sub>3</sub>.']]}),
SKL('esteq','Estequiometria','🧮','Converta massa em mol, aplique a proporção dos coeficientes e converta de volta para massa.',
`<p><b>Estequiometria</b> é o cálculo das quantidades numa reação, usando a <b>proporção dos coeficientes</b> da equação balanceada.</p><ol><li>Escreva e balanceie a equação.</li><li>Converta o dado para mol (n = m/M).</li><li>Aplique a proporção dos coeficientes.</li><li>Converta para a unidade pedida (massa, moléculas, volume).</li></ol>
<div class="ex">CH<sub>4</sub> + 2 O<sub>2</sub> → CO<sub>2</sub> + 2 H<sub>2</sub>O: 16 g de CH<sub>4</sub> (1 mol) produzem 1 mol de CO<sub>2</sub> = <b>44 g</b>.</div>
<p><b>Reagente limitante</b>: o que acaba primeiro e limita a quantidade de produto. <b>Rendimento</b>: produto obtido / produto teórico × 100%.</p>`,
{gens:[quiGens.esteq,quiGens.esteq,quiGens.esteq],qs:[['Se o rendimento de uma reação é 80% e o teórico é 50 g, a massa obtida é:','40 g',['50 g','62,5 g','30 g'],'80% de 50 g = <b>40 g</b>.'],['O reagente que é totalmente consumido e determina o fim da reação é o:','reagente limitante',['reagente em excesso','catalisador','produto principal'],'Ele limita a quantidade de produto.']]})
]});

/* ------------------------ UNIDADE 5 — FÍSICO-QUÍMICA ------------------------ */
UNITS.push({id:'q5',title:'Físico-química',sub:'Termoquímica, cinética, equilíbrio, eletroquímica e radioatividade',color:'#2b70c9',dark:'#1f569e',skills:[
SKL('termo','Termoquímica','🌡️','Exotérmica libera calor (ΔH < 0); endotérmica absorve calor (ΔH > 0).',
`<ul><li><b>Exotérmica</b>: libera calor, <b>ΔH &lt; 0</b> (combustão, respiração, neutralização).</li><li><b>Endotérmica</b>: absorve calor, <b>ΔH &gt; 0</b> (fotossíntese, cozimento, decomposição do CaCO<sub>3</sub>).</li></ul><div class="formula">ΔH = H<sub>produtos</sub> − H<sub>reagentes</sub></div>
<p><b>Lei de Hess</b>: o ΔH de uma reação depende só dos estados inicial e final; pode-se somar etapas (invertendo uma equação, troca-se o sinal de ΔH; multiplicando, multiplica-se ΔH).</p>
<p><b>Energia de ligação</b>: quebrar ligações absorve energia; formar ligações libera.</p>`,
{qs:[['A combustão do etanol libera calor. Ela é:','exotérmica, com ΔH < 0',['endotérmica, com ΔH > 0','exotérmica, com ΔH > 0','endotérmica, com ΔH < 0'],'Libera calor: <b>exotérmica</b>, ΔH negativo.'],['A fotossíntese absorve energia luminosa. Ela é:','endotérmica',['exotérmica','atérmica','nuclear'],'Absorve energia: <b>endotérmica</b>.'],['Se H<sub>reagentes</sub> = 100 kJ e H<sub>produtos</sub> = 40 kJ, o ΔH vale:','−60 kJ (exotérmica)',['+60 kJ (endotérmica)','+140 kJ','−140 kJ'],'ΔH = 40 − 100 = <b>−60 kJ</b>.'],['Ao inverter uma equação termoquímica, o ΔH:','troca de sinal',['dobra','não muda','zera'],'Lei de Hess: inverte-se o sentido → sinal oposto.'],['A quebra de ligações químicas:','absorve energia',['libera energia','não envolve energia','só ocorre em ácidos'],'Romper ligações é endotérmico; formar é exotérmico.']]}),
SKL('cinetica','Cinética química','⏩','Aumentam a velocidade: temperatura, concentração, superfície de contato e catalisador (que diminui a energia de ativação).',
`<p><b>Cinética</b> estuda a velocidade das reações. Para reagir, as partículas precisam colidir com orientação favorável e energia mínima (<b>energia de ativação</b>).</p>
<h3>Fatores que aumentam a velocidade</h3><ul><li><b>Temperatura</b> maior (mais colisões efetivas) — por isso a geladeira conserva os alimentos.</li><li><b>Concentração</b> maior dos reagentes.</li><li><b>Superfície de contato</b> maior (comprimido em pó reage mais rápido que inteiro).</li><li><b>Catalisador</b>: diminui a energia de ativação sem ser consumido e sem alterar o ΔH (enzimas são catalisadores biológicos).</li><li><b>Pressão</b> (para gases).</li></ul>`,
{qs:[['Um comprimido efervescente dissolve mais rápido quando triturado porque:','aumenta a superfície de contato',['diminui a temperatura','aumenta a energia de ativação','consome o catalisador'],'Mais área exposta: mais colisões.'],['O catalisador acelera uma reação porque:','diminui a energia de ativação',['aumenta o ΔH','é consumido na reação','aumenta a temperatura'],'Cria um caminho com menor energia de ativação.'],['Guardar alimentos na geladeira retarda o apodrecimento porque:','a temperatura baixa diminui a velocidade das reações',['o frio aumenta a energia de ativação dos alimentos','o frio mata todos os microrganismos','a geladeira é um catalisador'],'Temperatura menor: menos colisões efetivas.'],['As enzimas atuam no organismo como:','catalisadores biológicos',['reagentes consumidos','inibidores de todas as reações','produtos finais'],'Enzimas diminuem a energia de ativação.']]}),
SKL('equil','Equilíbrio químico','⚖️','Le Chatelier: o equilíbrio se desloca para diminuir a perturbação. Aumento de temperatura favorece o sentido endotérmico; aumento de pressão, o lado com menos mols de gás.',
`<p>No <b>equilíbrio químico</b>, as reações direta e inversa ocorrem com a <b>mesma velocidade</b> e as concentrações ficam constantes.</p><div class="formula">aA + bB ⇌ cC + dD → Kc = [C]<sup>c</sup>[D]<sup>d</sup> / [A]<sup>a</sup>[B]<sup>b</sup></div>
<h3>Princípio de Le Chatelier</h3><ul><li>Adicionar reagente → desloca para os <b>produtos</b>; retirar produto → também.</li><li>Aumentar a <b>temperatura</b> → favorece o sentido <b>endotérmico</b>.</li><li>Aumentar a <b>pressão</b> → favorece o lado com <b>menos mols de gás</b>.</li><li><b>Catalisador</b> não desloca o equilíbrio: só faz ele ser atingido mais rápido.</li></ul>`,
{qs:[['Em N<sub>2</sub>(g) + 3 H<sub>2</sub>(g) ⇌ 2 NH<sub>3</sub>(g), aumentar a pressão desloca o equilíbrio para:','a formação de NH<sub>3</sub> (lado com menos mols de gás)',['a formação de N<sub>2</sub> e H<sub>2</sub>','nenhum lado','o lado com mais mols de gás'],'4 mols de gás → 2 mols: pressão alta favorece o lado com <b>menos mols</b>.'],['Num equilíbrio exotérmico no sentido direto, aumentar a temperatura:','desloca o equilíbrio no sentido inverso',['desloca no sentido direto','não altera o equilíbrio','dobra o Kc sempre'],'Calor favorece o sentido <b>endotérmico</b> (o inverso).'],['Adicionar um catalisador a um sistema em equilíbrio:','não desloca o equilíbrio',['desloca para os produtos','desloca para os reagentes','aumenta o rendimento'],'Catalisador acelera os dois sentidos igualmente.'],['Retirar continuamente um produto de um equilíbrio:','desloca o equilíbrio para formar mais produto',['desloca para os reagentes','não tem efeito','para a reação'],'O sistema tenta repor o que foi retirado.'],['No equilíbrio químico:','as velocidades das reações direta e inversa são iguais',['a reação parou','os reagentes acabaram','as concentrações de reagentes e produtos são sempre iguais'],'É um equilíbrio <b>dinâmico</b>.']]}),
SKL('eletro','Eletroquímica','🔋','Pilha: ânodo sofre oxidação (polo −), cátodo sofre redução (polo +); elétrons vão do ânodo para o cátodo.',
`<p><b>Oxidação</b> é perda de elétrons (o NOX aumenta); <b>redução</b> é ganho de elétrons (o NOX diminui). Quem se oxida é o <b>agente redutor</b>; quem se reduz é o <b>agente oxidante</b>.</p>
<h3>Pilha (processo espontâneo)</h3><ul><li><b>Ânodo</b>: oxidação, polo <b>negativo</b>, a placa se desgasta.</li><li><b>Cátodo</b>: redução, polo <b>positivo</b>, a placa aumenta de massa.</li><li>Os elétrons fluem do ânodo para o cátodo pelo fio; a <b>ponte salina</b> fecha o circuito.</li><li>Pilha de Daniell: Zn (ânodo) → Zn<sup>2+</sup>; Cu<sup>2+</sup> → Cu (cátodo).</li><li>Quem tem <b>maior potencial de redução</b> se reduz.</li></ul>
<h3>Eletrólise (não espontânea)</h3><p>Usa corrente elétrica para forçar uma reação (produção de alumínio, cloro, galvanoplastia). Nela, o ânodo é o polo positivo, mas continua sendo onde ocorre a oxidação.</p>`,
{pairs:[['Oxidação','perda de elétrons, com aumento do NOX'],['Redução','ganho de elétrons, com diminuição do NOX'],['Ânodo','eletrodo onde ocorre a oxidação'],['Cátodo','eletrodo onde ocorre a redução'],['Agente redutor','espécie que sofre oxidação e provoca a redução da outra'],['Ponte salina','permite a migração de íons e mantém a neutralidade das soluções'],['Eletrólise','reação não espontânea provocada por corrente elétrica']],
 qs:[['Na pilha de Daniell, o zinco:','sofre oxidação e é o ânodo',['sofre redução e é o cátodo','não reage','recebe elétrons'],'Zn → Zn<sup>2+</sup> + 2e<sup>−</sup>: oxidação no <b>ânodo</b>.'],['Numa pilha, os elétrons se movem pelo fio:','do ânodo para o cátodo',['do cátodo para o ânodo','pela ponte salina','nos dois sentidos alternadamente'],'Saem de onde ocorre oxidação (ânodo).'],['Na pilha, a placa que aumenta de massa é:','o cátodo, onde íons metálicos se reduzem e depositam',['o ânodo','a ponte salina','nenhuma'],'Cu<sup>2+</sup> + 2e<sup>−</sup> → Cu deposita metal no <b>cátodo</b>.']]}),
SKL('radio','Radioatividade','☢️','Alfa (núcleo de hélio): A − 4 e Z − 2; beta (elétron): Z + 1; gama: onda eletromagnética, maior penetração. Meia-vida: tempo para a amostra cair à metade.',
`<ul><li><b>Alfa (α)</b>: 2 prótons + 2 nêutrons (núcleo de hélio). Ao emitir: <b>A diminui 4 e Z diminui 2</b>. Baixa penetração (barrada por uma folha de papel).</li><li><b>Beta (β<sup>−</sup>)</b>: elétron emitido do núcleo (um nêutron vira próton). Ao emitir: <b>Z aumenta 1</b> e A não muda. Penetração média.</li><li><b>Gama (γ)</b>: onda eletromagnética, sem massa nem carga. Maior penetração (barrada por chumbo ou concreto espesso).</li></ul>
<p><b>Meia-vida</b>: tempo para metade dos núcleos se desintegrar. Após n meias-vidas, resta m<sub>0</sub>/2<sup>n</sup>. O carbono-14 (meia-vida ≈ 5 730 anos) é usado em datação.</p>
<p><b>Fissão</b>: núcleo pesado se divide (usinas nucleares, bomba atômica). <b>Fusão</b>: núcleos leves se unem (energia do Sol).</p>`,
{gens:[quiGens.meia,quiGens.meia],qs:[['Ao emitir uma partícula alfa, o <sup>238</sup>U (Z = 92) se transforma num núcleo com:','A = 234 e Z = 90',['A = 238 e Z = 93','A = 234 e Z = 92','A = 236 e Z = 90'],'α: A − 4 = 234; Z − 2 = 90 (tório).'],['Ao emitir uma partícula beta, o número atômico:','aumenta 1 e a massa não muda',['diminui 2','aumenta 4','não muda'],'β<sup>−</sup>: um nêutron vira próton → Z + 1.'],['A radiação com maior poder de penetração é:','gama',['alfa','beta','todas iguais'],'Onda eletromagnética de alta energia: <b>gama</b>.'],['A energia do Sol vem da:','fusão nuclear de núcleos leves',['fissão do urânio','combustão do hidrogênio com oxigênio','radiação alfa'],'Hidrogênio se funde em hélio: <b>fusão</b>.'],['Usinas nucleares como Angra produzem energia por:','fissão nuclear',['fusão nuclear','combustão','fotossíntese'],'Núcleos de urânio se dividem: <b>fissão</b>.']]})
]});

/* ------------------------ UNIDADE 6 — QUÍMICA ORGÂNICA ------------------------ */
UNITS.push({id:'q6',title:'Química orgânica e ambiente',sub:'Carbono, hidrocarbonetos, funções orgânicas, isomeria, polímeros e química verde',color:'#58cc02',dark:'#58a700',skills:[
SKL('carbono','Carbono e cadeias','⬡','O carbono é tetravalente (faz 4 ligações) e forma cadeias. Carbono primário liga-se a 1 carbono; secundário a 2; terciário a 3; quaternário a 4.',
`<p>A química orgânica estuda os compostos de <b>carbono</b>. Postulados de Kekulé: o carbono é <b>tetravalente</b> e forma <b>cadeias</b>.</p>
<h3>Classificação das cadeias</h3><ul><li><b>Aberta (acíclica)</b> × <b>fechada (cíclica)</b>; aromática se tem anel benzênico.</li><li><b>Normal</b> × <b>ramificada</b>.</li><li><b>Saturada</b> (só ligações simples entre carbonos) × <b>insaturada</b> (dupla ou tripla).</li><li><b>Homogênea</b> × <b>heterogênea</b> (heteroátomo, como O ou N, entre carbonos).</li></ul>
<h3>Classificação dos carbonos</h3><p><b>Primário</b> (ligado a 1 C), <b>secundário</b> (2 C), <b>terciário</b> (3 C), <b>quaternário</b> (4 C).</p>`,
{gens:[quiGens.hidro],pairs:[['Cadeia saturada','só tem ligações simples entre carbonos'],['Cadeia insaturada','tem pelo menos uma ligação dupla ou tripla entre carbonos'],['Cadeia heterogênea','tem heteroátomo (O, N, S) entre carbonos'],['Cadeia ramificada','tem ramificações, ou seja, mais de duas extremidades'],['Cadeia aromática','contém anel benzênico'],['Carbono quaternário','carbono ligado a quatro outros carbonos']]}),
SKL('hidrocarb','Hidrocarbonetos e nomenclatura','🛢️','Prefixo = nº de carbonos (met 1, et 2, prop 3, but 4, pent 5, hex 6); infixo = ligação (an simples, en dupla, in tripla); sufixo o.',
`<p><b>Hidrocarbonetos</b> têm só C e H. O nome oficial (IUPAC) = <b>prefixo + infixo + sufixo</b>.</p>
<table><tr><th>Prefixo</th><td>met 1</td><td>et 2</td><td>prop 3</td><td>but 4</td><td>pent 5</td><td>hex 6</td><td>hept 7</td><td>oct 8</td></tr></table>
<ul><li><b>Alcanos</b> (-ano): só simples, C<sub>n</sub>H<sub>2n+2</sub> (metano, propano, butano do gás de cozinha).</li><li><b>Alcenos</b> (-eno): uma dupla, C<sub>n</sub>H<sub>2n</sub> (eteno, que amadurece frutas).</li><li><b>Alcinos</b> (-ino): uma tripla, C<sub>n</sub>H<sub>2n−2</sub> (etino/acetileno, do maçarico).</li><li><b>Aromáticos</b>: anel benzênico (benzeno).</li></ul>
<p>O <b>petróleo</b> é uma mistura de hidrocarbonetos separada por destilação fracionada.</p>`,
{gens:[quiGens.hidro,quiGens.hidro,quiGens.hidro],pairs:[['Metano','hidrocarboneto com 1 carbono, principal componente do gás natural'],['Propano e butano','principais componentes do gás de cozinha (GLP)'],['Eteno','alceno de 2 carbonos, acelera o amadurecimento de frutas'],['Etino (acetileno)','alcino usado em maçaricos de solda'],['Benzeno','hidrocarboneto aromático com anel de 6 carbonos'],['Isoctano','isômero do octano usado como referência (índice 100) na octanagem da gasolina']]}),
SKL('funcorg','Funções orgânicas','🧬','Álcool: –OH em carbono saturado; aldeído: –CHO; cetona: C=O entre carbonos; ácido carboxílico: –COOH; éster: –COO–; amina: –NH₂.',
`<table><tr><th>Função</th><th>Grupo</th><th>Exemplo</th></tr><tr><td>Álcool</td><td>–OH em carbono saturado</td><td>etanol (álcool comum)</td></tr><tr><td>Fenol</td><td>–OH ligado ao anel aromático</td><td>fenol (desinfetantes)</td></tr><tr><td>Aldeído</td><td>–CHO (C=O na ponta)</td><td>metanal (formol)</td></tr><tr><td>Cetona</td><td>C=O entre dois carbonos</td><td>propanona (acetona)</td></tr><tr><td>Ácido carboxílico</td><td>–COOH</td><td>ácido etanoico (vinagre)</td></tr><tr><td>Éster</td><td>–COO– entre carbonos</td><td>aromas de frutas</td></tr><tr><td>Éter</td><td>C–O–C</td><td>éter etílico (anestésico antigo)</td></tr><tr><td>Amina</td><td>derivada da amônia (–NH<sub>2</sub>)</td><td>metilamina (cheiro de peixe)</td></tr><tr><td>Amida</td><td>–CO–NH<sub>2</sub></td><td>ureia</td></tr></table>
<p><b>Esterificação</b>: ácido carboxílico + álcool → éster + água. O <b>biodiesel</b> é formado por ésteres.</p>`,
{pairs:[['Álcool','hidroxila (–OH) ligada a carbono saturado'],['Fenol','hidroxila (–OH) ligada diretamente ao anel aromático'],['Aldeído','carbonila na extremidade da cadeia (–CHO)'],['Cetona','carbonila entre dois carbonos'],['Ácido carboxílico','grupo carboxila (–COOH)'],['Éster','grupo –COO– entre carbonos, comum em aromas de frutas'],['Éter','oxigênio entre dois carbonos (C–O–C)'],['Amina','derivada da amônia, com nitrogênio ligado a carbono'],['Amida','carbonila ligada a nitrogênio (–CONH<sub>2</sub>)']],tq:t=>`Qual é o grupo característico da função <b>${t}</b>?`,dq:d=>`Qual função orgânica tem <b>${d}</b>?`,
 qs:[['O vinagre contém principalmente:','ácido etanoico (acético)',['etanol','propanona','metanal'],'Ácido carboxílico: ácido acético.'],['A acetona (propanona) pertence à função:','cetona',['aldeído','álcool','éster'],'C=O entre dois carbonos.'],['A reação ácido carboxílico + álcool → éster + água chama-se:','esterificação',['saponificação','combustão','hidrogenação'],'Forma éster: <b>esterificação</b>.'],['O formol (metanal) pertence à função:','aldeído',['cetona','ácido carboxílico','éter'],'Metan<b>al</b>: aldeído.'],['A reação de gordura com base forte (NaOH), que produz sabão, é a:','saponificação',['esterificação','polimerização','fermentação'],'Hidrólise alcalina de ésteres: <b>saponificação</b>.']]}),
SKL('isomeria','Isomeria','🪞','Isômeros têm a mesma fórmula molecular e estruturas diferentes. Isomeria óptica exige carbono quiral (4 ligantes diferentes).',
`<p><b>Isômeros</b>: mesma fórmula molecular, estruturas e propriedades diferentes.</p><h3>Isomeria plana (constitucional)</h3><ul><li><b>De cadeia</b>: cadeias diferentes (butano × metilpropano).</li><li><b>De posição</b>: mesmo grupo em posições diferentes (propan-1-ol × propan-2-ol).</li><li><b>De função</b>: funções diferentes (etanol × éter dimetílico; propanal × propanona).</li><li><b>Metameria</b>: heteroátomo em posições diferentes.</li><li><b>Tautomeria</b>: equilíbrio entre funções (aldeído/cetona ⇌ enol).</li></ul>
<h3>Isomeria espacial</h3><ul><li><b>Geométrica (cis-trans)</b>: dupla ligação com ligantes diferentes em cada carbono.</li><li><b>Óptica</b>: molécula com <b>carbono quiral</b> (assimétrico, 4 ligantes diferentes) → enantiômeros, que desviam a luz polarizada em sentidos opostos.</li></ul>`,
{qs:[['Etanol (C<sub>2</sub>H<sub>6</sub>O) e éter dimetílico (C<sub>2</sub>H<sub>6</sub>O) são isômeros:','de função',['de cadeia','de posição','ópticos'],'Mesma fórmula, funções diferentes (álcool × éter).'],['Propan-1-ol e propan-2-ol são isômeros:','de posição',['de função','de cadeia','geométricos'],'O –OH muda de posição.'],['Para haver isomeria óptica, a molécula deve ter:','carbono quiral (quatro ligantes diferentes)',['ligação tripla','anel aromático obrigatoriamente','apenas carbonos primários'],'Carbono assimétrico gera imagens especulares não sobreponíveis.'],['A isomeria cis-trans ocorre em compostos com:','dupla ligação entre carbonos, cada um com ligantes diferentes',['apenas ligações simples em cadeia aberta','carbono quiral','ligação iônica'],'A dupla impede a rotação: ligantes do mesmo lado (cis) ou opostos (trans).'],['Butano e metilpropano são isômeros:','de cadeia',['de função','de posição','ópticos'],'Cadeia normal × ramificada.']]}),
SKL('ambiente','Polímeros, combustíveis e química verde','♻️','Polímeros são macromoléculas formadas por monômeros. Combustíveis fósseis liberam CO₂ que estava estocado; os biocombustíveis vêm de fontes renováveis.',
`<ul><li><b>Polímeros</b>: macromoléculas de unidades repetidas (<b>monômeros</b>). De <b>adição</b> (polietileno, PVC, isopor/poliestireno) e de <b>condensação</b> (PET, náilon), que liberam uma molécula pequena como água. Naturais: amido, celulose, proteínas, borracha.</li><li><b>Combustíveis fósseis</b> (petróleo, carvão, gás natural): liberam CO<sub>2</sub> que estava estocado há milhões de anos, intensificando o <b>efeito estufa</b>. <b>Biocombustíveis</b> (etanol da cana, biodiesel) vêm de fontes renováveis.</li><li><b>Combustão completa</b> gera CO<sub>2</sub> e H<sub>2</sub>O; a <b>incompleta</b> gera CO (tóxico) e fuligem.</li><li><b>Química verde</b>: prevenir resíduos, usar matérias-primas renováveis, catalisadores e processos mais seguros.</li></ul>`,
{pairs:[['Polietileno','polímero de adição usado em sacolas plásticas'],['PET','polímero de condensação usado em garrafas'],['Monômero','unidade pequena que se repete para formar o polímero'],['Combustão incompleta','queima com pouco oxigênio que gera monóxido de carbono e fuligem'],['Biodiesel','combustível renovável formado por ésteres de óleos vegetais ou gorduras'],['Efeito estufa','retenção de calor pela atmosfera, intensificada pelo excesso de CO<sub>2</sub> e metano'],['Química verde','práticas para reduzir resíduos e riscos na produção química']],
 qs:[['O monóxido de carbono (CO), gás tóxico, é produzido principalmente na:','combustão incompleta',['combustão completa','fotossíntese','fusão nuclear'],'Pouco oxigênio: forma CO em vez de CO<sub>2</sub>.'],['O etanol da cana-de-açúcar é considerado renovável porque:','o carbono liberado na queima foi absorvido pela planta na fotossíntese',['não libera nenhum gás','é um combustível fóssil','não precisa de oxigênio para queimar'],'O ciclo do carbono se fecha em pouco tempo.'],['Proteínas, amido e celulose são exemplos de:','polímeros naturais',['polímeros sintéticos','monômeros','hidrocarbonetos'],'Macromoléculas produzidas por seres vivos.']]})
]});

const GLOSS=autoGloss(UNITS,[
 {k:['mol','numero de avogadro','avogadro'],n:'Mol',s:'massamol',t:'Mol é a unidade de quantidade de matéria: 1 mol = 6,02 × 10²³ partículas. n = m / M.'},
 {k:['ph','pOH'],n:'pH',s:'ph',t:'pH = −log[H⁺]. A 25 °C: pH < 7 ácido, 7 neutro, > 7 básico; pH + pOH = 14.'},
 {k:['le chatelier','deslocamento de equilibrio'],n:'Princípio de Le Chatelier',s:'equil',t:'Um sistema em equilíbrio desloca-se para diminuir uma perturbação: mais reagente → forma produto; mais temperatura → sentido endotérmico; mais pressão → lado com menos mols de gás.'},
 {k:['anodo','catodo','pilha'],n:'Pilha',s:'eletro',t:'Na pilha, o ânodo sofre oxidação (polo −) e o cátodo sofre redução (polo +). Os elétrons vão do ânodo ao cátodo.'},
 {k:['isotopo','isotopos'],n:'Isótopos',s:'particulas',t:'Isótopos têm o mesmo número de prótons (Z) e diferentes números de massa (A). Ex.: carbono-12 e carbono-14.'}]);
