const BRAND={app:'SaberLingo',chatPh:'ex.: o que foi o feudalismo?',tutor:'Professor Heródoto',sym:'⌛',body:'#e2735a',dark:'#b85a44',belly:'#ffe6de',lsKey:'histlingo_v1',first:'prehist',
 welcome:'História <b>geral e do Brasil</b>, da Pré-História à Nova República: fatos, conceitos, cronologia e as relações de causa e consequência que caem no ENEM e nos vestibulares.',
 range:'do Fundamental ao Ensino Médio (ENEM e vestibulares)',searchEx:'ex.: Era Vargas',firstName:'Pré-História',
 chips:['O que foi o feudalismo?','Revolução Francesa','Era Vargas','Guerra Fria','Lei Áurea','Iluminismo'],
 askEx:'<i>"o que foi o Estado Novo?"</i>, <i>"feudalismo"</i>, <i>"Guerra Fria"</i>',
 formulas:'datas e períodos (use as questões de cronologia para fixar a linha do tempo)'};
const UNITS=[];
const sec=y=>{ const s=Math.ceil(Math.abs(y)/100); const r=['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX','XXI'][s]; return y<0?`séc. ${r} a.C.`:`séc. ${r}`; };

/* ------------------------ UNIDADE 1 — ANTIGUIDADE ------------------------ */
UNITS.push({id:'h1',title:'Pré-História e Antiguidade',sub:'Paleolítico e Neolítico, Mesopotâmia, Egito, Grécia e Roma',color:'#e2735a',dark:'#b85a44',skills:[
SKL('prehist','Pré-História','🪨','Paleolítico: caça, coleta, nomadismo, pedra lascada. Neolítico: agricultura, sedentarismo, pedra polida (Revolução Agrícola). Idade dos Metais: cobre, bronze, ferro.',
`<p>Período antes da <b>escrita</b> (c. 4000 a.C. na Mesopotâmia).</p><ul><li><b>Paleolítico</b> (Idade da Pedra Lascada): caça, pesca e coleta; <b>nomadismo</b>; domínio do <b>fogo</b>; arte rupestre.</li><li><b>Neolítico</b> (Pedra Polida): <b>Revolução Agrícola</b> (c. 10 000 a.C.), domesticação de animais, <b>sedentarismo</b>, primeiras aldeias, cerâmica e tecelagem.</li><li><b>Idade dos Metais</b>: cobre, bronze e ferro; cidades, comércio e diferenças sociais.</li></ul>
<p>No Brasil: sítios da <b>Serra da Capivara</b> (PI), com pinturas rupestres, e o fóssil de <b>Luzia</b> (MG), com cerca de 11 mil anos. A chegada humana à América é explicada principalmente pela travessia do <b>Estreito de Bering</b>.</p>`,
{pairs:[['Paleolítico','caça, coleta, nomadismo e pedra lascada'],['Neolítico','agricultura, domesticação de animais, sedentarismo e pedra polida'],['Idade dos Metais','uso do cobre, do bronze e do ferro'],['Revolução Agrícola','passagem para a produção de alimentos, que levou ao sedentarismo'],['Arte rupestre','pinturas e gravuras em paredes de cavernas e rochas'],['Serra da Capivara','sítio arqueológico no Piauí com milhares de pinturas rupestres'],['Luzia','fóssil humano com cerca de 11 mil anos encontrado em Minas Gerais']],
 qs:[['A principal transformação do Neolítico foi:','o desenvolvimento da agricultura e o sedentarismo',['o domínio do fogo','a invenção da escrita','a formação dos impérios'],'A Revolução Agrícola fixou os grupos à terra.'],['A Pré-História termina, por convenção, com:','o surgimento da escrita',['a queda de Roma','o domínio do fogo','a descoberta da América'],'A escrita surge por volta de 4000 a.C. na Mesopotâmia.']]}),
SKL('oriente','Antiguidade Oriental','🏺','Mesopotâmia (entre Tigre e Eufrates): escrita cuneiforme, Código de Hamurabi. Egito: dependência do Nilo, faraó, hieróglifos. Hebreus: monoteísmo. Fenícios: alfabeto e comércio.',
`<ul><li><b>Mesopotâmia</b> (entre os rios Tigre e Eufrates, atual Iraque): sumérios, acádios, babilônios, assírios. <b>Escrita cuneiforme</b>, zigurates e o <b>Código de Hamurabi</b> ("olho por olho, dente por dente").</li><li><b>Egito</b>: "dádiva do Nilo" (cheias fertilizavam o solo); <b>faraó</b> considerado um deus (monarquia teocrática); pirâmides, mumificação e <b>hieróglifos</b>.</li><li><b>Hebreus</b>: primeiro povo <b>monoteísta</b> de grande influência (judaísmo).</li><li><b>Fenícios</b>: grandes comerciantes e navegadores; criaram o <b>alfabeto</b> fonético que deu origem ao nosso.</li><li><b>Persas</b>: grande império, estradas e sistema de satrápias; religião de Zoroastro.</li></ul>
<p>Essas sociedades se organizavam no <b>modo de produção asiático</b>: Estado forte controlando a terra e as obras hidráulicas, com trabalho compulsório.</p>`,
{pairs:[['Mesopotâmia','civilizações entre os rios Tigre e Eufrates'],['Código de Hamurabi','conjunto de leis babilônicas baseado na lei de talião'],['Escrita cuneiforme','escrita em forma de cunha, gravada em tábuas de argila'],['Egito Antigo','civilização às margens do Nilo, governada por faraós'],['Hieróglifos','escrita sagrada dos egípcios'],['Hebreus','povo que difundiu o monoteísmo'],['Fenícios','comerciantes do Mediterrâneo que criaram o alfabeto fonético'],['Persas','império que organizou o território em satrápias']],
 qs:[['A frase "olho por olho, dente por dente" resume o princípio do:','Código de Hamurabi',['Direito Romano','Código Napoleônico','Decálogo cristão'],'Lei de talião, na Babilônia.'],['Heródoto chamou o Egito de "dádiva do Nilo" porque:','as cheias do rio fertilizavam as terras para a agricultura',['o rio separava o Egito do deserto','o Nilo era o único caminho para Roma','o rio era sagrado para os hebreus'],'O limo das cheias tornava o solo fértil.'],['Nosso alfabeto tem origem no alfabeto:','fenício',['egípcio','sumério','persa'],'Os fenícios criaram um alfabeto fonético adotado por gregos e romanos.']]}),
SKL('grecia','Grécia Antiga','🏛️','Pólis independentes; Atenas criou a democracia (só cidadãos homens livres votavam); Esparta era militarista e oligárquica.',
`<p>A Grécia era formada por <b>pólis</b> (cidades-Estado) independentes, unidas pela língua, religião e jogos olímpicos.</p>
<ul><li><b>Atenas</b>: <b>democracia</b> (reformas de Clístenes, séc. VI a.C.; auge com Péricles). Era direta, mas excluía mulheres, estrangeiros (metecos) e escravizados.</li><li><b>Esparta</b>: sociedade <b>militarista</b> e oligárquica; educação voltada à guerra.</li></ul>
<h3>Conflitos</h3><p><b>Guerras Médicas</b> (gregos × persas, séc. V a.C.), vencidas pelos gregos; <b>Guerra do Peloponeso</b> (431–404 a.C., Atenas × Esparta), que enfraqueceu as pólis. Depois vieram a conquista macedônica e <b>Alexandre, o Grande</b>, que difundiu a cultura grega no Oriente (<b>Período Helenístico</b>).</p>
<p>Legado: filosofia (Sócrates, Platão, Aristóteles), teatro, história (Heródoto), matemática e a ideia de democracia.</p>`,
{pairs:[['Pólis','cidade-Estado grega independente'],['Democracia ateniense','participação direta dos cidadãos, excluindo mulheres, estrangeiros e escravizados'],['Esparta','pólis militarista e oligárquica'],['Guerras Médicas','conflitos entre gregos e persas no século V a.C.'],['Guerra do Peloponeso','conflito entre Atenas e Esparta (431–404 a.C.)'],['Período Helenístico','fusão da cultura grega com a oriental após as conquistas de Alexandre'],['Metecos','estrangeiros que viviam em Atenas, sem direitos políticos']],
 order:[['Início da Guerra do Peloponeso',-431],['Batalha de Maratona (Guerras Médicas)',-490],['Morte de Alexandre, o Grande',-323],['Reformas democráticas de Clístenes',-508]],
 qs:[['A democracia ateniense era limitada porque:','excluía mulheres, estrangeiros e escravizados',['era representativa, com deputados eleitos','só permitia votar quem fosse rico','era controlada pelos persas'],'Só homens livres, adultos e filhos de atenienses eram cidadãos.'],['A cultura helenística resultou:','das conquistas de Alexandre, que fundiram a cultura grega com a oriental',['da vitória de Esparta sobre Atenas','da invasão romana à Pérsia','do cristianismo'],'Alexandre levou a cultura grega até a Índia.']]}),
SKL('roma','Roma Antiga','🦅','Monarquia → República (Senado; conflitos entre patrícios e plebeus) → Império (a partir de 27 a.C., com Augusto). Queda do Império Romano do Ocidente: 476.',
`<ul><li><b>Monarquia</b> (753–509 a.C., segundo a tradição).</li><li><b>República</b> (509–27 a.C.): poder do <b>Senado</b> (patrícios); lutas dos <b>plebeus</b> por direitos (tribunos da plebe, Lei das Doze Tábuas); expansão com as Guerras Púnicas contra Cartago; crise e ditadura de Júlio César.</li><li><b>Império</b> (27 a.C.–476 d.C.): Otávio <b>Augusto</b> é o primeiro imperador; <b>Pax Romana</b>; "pão e circo"; crise do século III; o <b>cristianismo</b>, antes perseguido, é liberado (Édito de Milão, 313) e vira religião oficial (380).</li><li>Divisão do Império (395) e <b>queda do Império do Ocidente em 476</b> (invasões germânicas) — marco do fim da Antiguidade. O Império do Oriente (<b>Bizantino</b>, capital Constantinopla) durou até 1453.</li></ul>
<p>Legado: <b>Direito Romano</b>, o latim (origem do português), arquitetura (arcos, aquedutos).</p>`,
{pairs:[['Senado romano','órgão político dos patrícios, central na República'],['Patrícios','aristocracia romana proprietária de terras'],['Plebeus','camadas populares que lutaram por direitos na República'],['Pax Romana','período de relativa estabilidade no início do Império'],['Política do pão e circo','distribuição de alimentos e espetáculos para conter revoltas'],['Império Bizantino','Império Romano do Oriente, com capital em Constantinopla'],['Guerras Púnicas','conflitos entre Roma e Cartago pelo Mediterrâneo']],
 order:[['Início do Império com Augusto',-27],['Édito de Milão, que libera o cristianismo',313],['Queda do Império Romano do Ocidente',476],['Queda de Constantinopla',1453],['Proclamação da República Romana',-509]],
 qs:[['A queda do Império Romano do Ocidente, em 476, é usada como marco do:','fim da Antiguidade e início da Idade Média',['início da Idade Moderna','fim da Idade Média','início da Pré-História'],'Convencionalmente, a Idade Média vai de 476 a 1453.'],['A Lei das Doze Tábuas foi uma conquista dos:','plebeus, que passaram a ter leis escritas',['patrícios, que ampliaram seus privilégios','escravizados, que ganharam a liberdade','imperadores, que se tornaram deuses'],'Leis escritas limitavam a arbitrariedade dos patrícios.'],['A língua portuguesa deriva principalmente do:','latim',['grego','árabe','germânico'],'Latim vulgar falado na Península Ibérica.']]})
]});

/* ------------------------ UNIDADE 2 — IDADE MÉDIA E MODERNA ------------------------ */
UNITS.push({id:'h2',title:'Idade Média e Idade Moderna',sub:'Feudalismo, Renascimento, Reformas, Navegações, Absolutismo e Iluminismo',color:'#1cb0f6',dark:'#1899d6',skills:[
SKL('feudal','Feudalismo e Baixa Idade Média','🏰','Feudalismo: economia agrária e autossuficiente, sociedade estamental (clero, nobreza, servos), relações de suserania e vassalagem e forte poder da Igreja.',
`<p><b>Feudalismo</b> (Europa Ocidental, séc. V–XV):</p><ul><li>Economia <b>agrária</b>, pouco comércio, feudos quase autossuficientes.</li><li>Sociedade <b>estamental</b> (pouca mobilidade): clero (os que rezam), nobreza (os que guerreiam) e servos (os que trabalham).</li><li><b>Suserania e vassalagem</b>: o suserano doava terras (feudo) em troca de fidelidade e serviço militar do vassalo.</li><li><b>Servidão</b>: servos presos à terra, pagando obrigações (<b>corveia</b>: trabalho nas terras do senhor; <b>talha</b>: parte da produção; <b>banalidades</b>: uso de moinho e forno).</li><li><b>Igreja Católica</b>: grande proprietária e dominante na cultura.</li></ul>
<h3>Baixa Idade Média (séc. XI–XV)</h3><p><b>Cruzadas</b> (1096–1270), reabertura do Mediterrâneo, <b>renascimento comercial e urbano</b>, feiras, burgos e a <b>burguesia</b>; <b>Peste Negra</b> (1347–1351) e crise do século XIV; Guerra dos Cem Anos.</p>`,
{pairs:[['Corveia','trabalho gratuito do servo nas terras do senhor'],['Talha','parte da produção do servo entregue ao senhor'],['Banalidades','taxas pelo uso do moinho, forno e outras instalações do senhor'],['Suserania e vassalagem','relação de fidelidade entre nobres, com doação de terras em troca de serviço militar'],['Sociedade estamental','sociedade dividida em grupos rígidos, com pouca mobilidade'],['Cruzadas','expedições militares cristãs para a Terra Santa'],['Burguesia','grupo social de comerciantes que surgiu nos burgos'],['Peste Negra','epidemia que matou grande parte da população europeia no século XIV']],
 order:[['Início das Cruzadas',1096],['Peste Negra na Europa',1347],['Coroação de Carlos Magno',800],['Queda de Constantinopla',1453]],
 qs:[['Uma característica do feudalismo é:','a economia agrária e voltada à subsistência',['a intensa atividade industrial','o trabalho assalariado dominante','o poder político centralizado nas mãos do rei'],'Economia rural e poder descentralizado nas mãos dos senhores.'],['As Cruzadas contribuíram para:','reativar o comércio entre Europa e Oriente',['acabar com a Igreja Católica','unificar a Europa sob um só rei','iniciar as Grandes Navegações imediatamente'],'Reabriram rotas pelo Mediterrâneo.']]}),
SKL('renasc','Renascimento e Reformas','🎨','Renascimento: antropocentrismo, humanismo, racionalismo e valorização da Antiguidade. Reforma: Lutero (1517) critica as indulgências; Contrarreforma: Concílio de Trento, jesuítas e Inquisição.',
`<h3>Renascimento (séc. XIV–XVI)</h3><p>Começa nas cidades italianas (Florença), financiado por <b>mecenas</b>. Valores: <b>antropocentrismo</b> (ser humano no centro), <b>humanismo</b>, <b>racionalismo</b>, valorização da cultura greco-romana. Artistas: Leonardo da Vinci, Michelangelo, Rafael; ciência: Copérnico (heliocentrismo), Galileu. A <b>imprensa</b> de Gutenberg (c. 1450) difundiu ideias.</p>
<h3>Reforma Protestante</h3><ul><li><b>Lutero</b> (1517, 95 teses): contra a venda de <b>indulgências</b>; salvação pela fé; Bíblia traduzida.</li><li><b>Calvino</b>: predestinação; valorização do trabalho (bem aceita pela burguesia).</li><li><b>Anglicanismo</b>: Henrique VIII rompe com Roma e se torna chefe da Igreja da Inglaterra.</li></ul>
<h3>Contrarreforma</h3><p><b>Concílio de Trento</b> (1545–1563), <b>Companhia de Jesus</b> (jesuítas, catequese na América), fortalecimento da <b>Inquisição</b> e Índice de Livros Proibidos.</p>`,
{pairs:[['Antropocentrismo','visão que coloca o ser humano no centro do universo'],['Mecenas','patrocinadores de artistas e sábios no Renascimento'],['Martinho Lutero','iniciou a Reforma Protestante em 1517'],['João Calvino','reformador que defendeu a predestinação'],['Anglicanismo','igreja criada por Henrique VIII na Inglaterra'],['Concílio de Trento','reunião que reafirmou os dogmas católicos na Contrarreforma'],['Companhia de Jesus','ordem religiosa dos jesuítas, atuante na catequese'],['Indulgências','perdão de pecados vendido pela Igreja, criticado por Lutero']],
 order:[['95 teses de Lutero',1517],['Início do Concílio de Trento',1545],['Prensa de Gutenberg',1450],['Chegada de Colombo à América',1492]],
 qs:[['O que motivou as 95 teses de Lutero?','a venda de indulgências pela Igreja',['a invasão árabe da Europa','a descoberta da América','a Revolução Francesa'],'Lutero criticou a venda do perdão.'],['A ideia de que o ser humano é o centro das preocupações artísticas e intelectuais é o:','antropocentrismo',['teocentrismo','feudalismo','mercantilismo'],'Marca do Renascimento, oposta ao teocentrismo medieval.']]}),
SKL('navega','Grandes Navegações','⛵','Portugal foi pioneiro (centralização precoce, posição geográfica, Escola de Sagres). 1492: Colombo na América; 1498: Vasco da Gama na Índia; 1500: Cabral no Brasil. Tratado de Tordesilhas: 1494.',
`<p>Motivos: busca de <b>especiarias</b> e metais, rota alternativa ao Mediterrâneo dominado por italianos e turcos (Constantinopla tomada em 1453), avanços técnicos (caravela, bússola, astrolábio) e expansão da fé cristã.</p>
<ul><li><b>Portugal</b> foi pioneiro: centralização política precoce (Revolução de Avis, 1385), burguesia mercantil e posição atlântica. Périplo africano; <b>Bartolomeu Dias</b> contorna o Cabo da Boa Esperança (1488); <b>Vasco da Gama</b> chega às Índias (1498); <b>Pedro Álvares Cabral</b> chega ao Brasil (1500).</li><li><b>Espanha</b>: <b>Cristóvão Colombo</b> chega à América (1492); Fernão de Magalhães inicia a primeira volta ao mundo (1519–1522).</li><li><b>Tratado de Tordesilhas</b> (1494): dividiu as terras entre Portugal e Espanha por um meridiano a 370 léguas de Cabo Verde.</li></ul>`,
{order:[['Chegada de Colombo à América',1492],['Chegada de Vasco da Gama às Índias',1498],['Chegada de Cabral ao Brasil',1500],['Tratado de Tordesilhas',1494],['Bartolomeu Dias contorna o Cabo da Boa Esperança',1488],['Tomada de Constantinopla pelos turcos',1453]],
 pairs:[['Tratado de Tordesilhas','dividiu as terras descobertas entre Portugal e Espanha (1494)'],['Cristóvão Colombo','navegador a serviço da Espanha que chegou à América em 1492'],['Vasco da Gama','abriu o caminho marítimo de Portugal às Índias'],['Pedro Álvares Cabral','comandou a esquadra que chegou ao Brasil em 1500'],['Caravela','embarcação leve que navegava contra o vento'],['Especiarias','produtos como pimenta, cravo e canela, muito valorizados na Europa']],
 qs:[['Portugal foi pioneiro nas navegações principalmente por causa:','da centralização política precoce e da posição geográfica atlântica',['de ser o país mais rico da Europa','de ter o maior exército europeu','da ajuda dos incas'],'Estado centralizado desde a Revolução de Avis e litoral atlântico.']]}),
SKL('absol','Absolutismo e Mercantilismo','👑','Absolutismo: poder concentrado no rei (Luís XIV: "O Estado sou eu"), justificado pelo direito divino. Mercantilismo: metalismo, balança comercial favorável, protecionismo e exploração colonial.',
`<p>Os <b>Estados Nacionais</b> se formaram com a aliança entre rei e burguesia. O <b>Absolutismo</b> concentrava o poder no monarca.</p><ul><li><b>Teóricos</b>: <b>Maquiavel</b> (<i>O Príncipe</i>: separar política e moral), <b>Hobbes</b> (<i>Leviatã</i>: Estado forte contra a "guerra de todos contra todos"), <b>Bossuet</b> (direito divino dos reis).</li><li>Exemplo máximo: <b>Luís XIV</b>, o "Rei Sol", e Versalhes.</li></ul>
<p><b>Mercantilismo</b>: política econômica dos Estados absolutistas — <b>metalismo</b> (acúmulo de ouro e prata), <b>balança comercial favorável</b>, <b>protecionismo</b> e <b>pacto colonial</b> (a colônia só comercia com a metrópole).</p>`,
{pairs:[['Absolutismo','concentração dos poderes nas mãos do rei'],['Luís XIV','rei francês conhecido como "Rei Sol"'],['Nicolau Maquiavel','autor de O Príncipe, que separou política e moral'],['Thomas Hobbes','autor do Leviatã, defensor de um Estado forte'],['Metalismo','ideia de que a riqueza do Estado depende do acúmulo de metais preciosos'],['Pacto colonial','exclusividade de comércio da colônia com a metrópole'],['Balança comercial favorável','exportar mais do que importar']],
 qs:[['A frase "O Estado sou eu" é atribuída a:','Luís XIV',['Napoleão','Henrique VIII','Robespierre'],'O "Rei Sol" da França.'],['A teoria do direito divino dos reis afirmava que:','o poder do rei vinha de Deus',['o poder vinha do povo','o rei devia obedecer ao Parlamento','os reis eram eleitos pela Igreja'],'Defendida por Bossuet.']]}),
SKL('ilum','Iluminismo','💡','Razão contra o absolutismo e os privilégios: Locke (direitos naturais), Montesquieu (três poderes), Voltaire (liberdade de expressão), Rousseau (contrato social, soberania popular), Adam Smith (liberalismo econômico).',
`<p>O <b>Iluminismo</b> (séc. XVIII) defendia a <b>razão</b>, a liberdade, a igualdade perante a lei e criticava o absolutismo, o mercantilismo e os privilégios do clero e da nobreza.</p>
<ul><li><b>John Locke</b>: direitos naturais (vida, liberdade, propriedade); direito de resistência ao governo tirânico.</li><li><b>Montesquieu</b>: <i>O Espírito das Leis</i>; <b>separação dos três poderes</b> (Executivo, Legislativo e Judiciário).</li><li><b>Voltaire</b>: liberdade de expressão e crítica à Igreja.</li><li><b>Rousseau</b>: <i>O Contrato Social</i>; soberania popular e vontade geral.</li><li><b>Diderot e D'Alembert</b>: a <i>Enciclopédia</i>.</li><li><b>Adam Smith</b>: <b>liberalismo econômico</b>, "mão invisível" do mercado (<i>A Riqueza das Nações</i>, 1776).</li></ul>
<p><b>Déspotas esclarecidos</b> (Marquês de Pombal em Portugal, Catarina II na Rússia) aplicaram algumas ideias sem abrir mão do poder absoluto.</p>`,
{pairs:[['Montesquieu','defendeu a separação dos três poderes'],['Rousseau','autor de O Contrato Social, defensor da soberania popular'],['Voltaire','defendeu a liberdade de expressão e criticou a Igreja'],['John Locke','defendeu os direitos naturais à vida, à liberdade e à propriedade'],['Adam Smith','defendeu o liberalismo econômico e a "mão invisível" do mercado'],['Enciclopédia','obra de Diderot e D\'Alembert que reuniu o saber iluminista'],['Despotismo esclarecido','reis absolutistas que adotaram algumas ideias iluministas']],
 qs:[['A divisão do Estado em Executivo, Legislativo e Judiciário, presente na Constituição brasileira, vem de:','Montesquieu',['Hobbes','Maquiavel','Luís XIV'],'<i>O Espírito das Leis</i> (1748).'],['O liberalismo econômico defendia:','a mínima intervenção do Estado na economia',['o controle total da economia pelo rei','o fim da propriedade privada','o pacto colonial'],'Livre mercado, contra o mercantilismo.']]})
]});

/* ------------------------ UNIDADE 3 — REVOLUÇÕES E SÉCULO XIX ------------------------ */
UNITS.push({id:'h3',title:'Revoluções e século XIX',sub:'Revoluções Inglesas, Industrial, Americana e Francesa, independências, Imperialismo',color:'#ff9600',dark:'#e07b00',skills:[
SKL('industrial','Revolução Industrial','🏭','Começou na Inglaterra (séc. XVIII): máquina a vapor, fábricas, trabalho assalariado, êxodo rural e péssimas condições de trabalho (ludismo, cartismo, sindicatos).',
`<p>A <b>Revolução Inglesa</b> (Puritana, 1640–1649, e <b>Gloriosa</b>, 1688) limitou o poder do rei: <b>Bill of Rights</b> (1689) e monarquia parlamentar — ambiente favorável à burguesia.</p>
<p><b>Revolução Industrial</b> (Inglaterra, a partir de c. 1760): capital acumulado, carvão e ferro, mão de obra vinda do campo (cercamentos), <b>máquina a vapor</b> (James Watt) e indústria têxtil.</p>
<ul><li>Consequências: produção em larga escala, <b>trabalho assalariado</b>, urbanização rápida, jornadas longas, trabalho infantil.</li><li>Reações: <b>ludismo</b> (quebra de máquinas), <b>cartismo</b> (direitos políticos, voto), <b>sindicatos</b> (trade unions).</li><li>2ª Revolução Industrial (fim do séc. XIX): eletricidade, petróleo, aço, química.</li></ul>`,
{pairs:[['Ludismo','movimento de trabalhadores que destruía máquinas'],['Cartismo','movimento operário que reivindicava direitos políticos, como o voto'],['Cercamentos','expulsão de camponeses das terras comuns na Inglaterra'],['Máquina a vapor','invenção aperfeiçoada por James Watt, símbolo da 1ª Revolução Industrial'],['Revolução Gloriosa','estabeleceu a monarquia parlamentar na Inglaterra (1688)'],['Bill of Rights','declaração de direitos que limitou o poder do rei inglês (1689)'],['2ª Revolução Industrial','fase marcada por eletricidade, petróleo e aço']],
 qs:[['A Revolução Industrial começou na Inglaterra, entre outros fatores, porque o país tinha:','capital acumulado, carvão, ferro e mão de obra disponível',['a maior população do mundo','um governo absolutista forte','colônias só na América do Sul'],'Recursos, capital e mão de obra dos cercamentos.'],['Os luditas protestavam contra o desemprego:','quebrando máquinas',['fazendo greves pelo voto feminino','fundando partidos comunistas','emigrando para a América'],'Viam as máquinas como causa do desemprego.']]}),
SKL('francesa','Revolução Francesa e Napoleão','🇫🇷','1789: Queda da Bastilha e Declaração dos Direitos do Homem e do Cidadão ("Liberdade, Igualdade, Fraternidade"). Fases: Monarquia Constitucional, Convenção (Terror jacobino) e Diretório. Napoleão chega ao poder em 1799.',
`<p><b>Causas</b>: crise financeira, fome, privilégios do 1º (clero) e 2º (nobreza) Estados, ideias iluministas e insatisfação do 3º Estado (burguesia, camponeses, sans-culottes).</p>
<ul><li><b>1789</b>: Estados Gerais, Assembleia Nacional, <b>Queda da Bastilha</b> (14 de julho), <b>Declaração dos Direitos do Homem e do Cidadão</b>.</li><li><b>Monarquia Constitucional</b> (1791).</li><li><b>Convenção</b> (1792–1795): República; execução de Luís XVI; <b>Terror</b> jacobino (Robespierre).</li><li><b>Diretório</b> (1795–1799): burguesia girondina no poder.</li><li><b>Napoleão</b>: golpe do 18 Brumário (1799), Consulado, Código Civil, Império (1804); <b>Bloqueio Continental</b> (1806) contra a Inglaterra — que fez a família real portuguesa fugir para o Brasil; derrota em Waterloo (1815).</li><li><b>Congresso de Viena</b> (1814–1815): restauração das monarquias.</li></ul>`,
{pairs:[['Queda da Bastilha','símbolo do início da Revolução Francesa, em 14 de julho de 1789'],['Jacobinos','grupo radical que liderou o período do Terror'],['Girondinos','grupo moderado ligado à alta burguesia'],['Sans-culottes','camadas populares urbanas de Paris'],['Bloqueio Continental','proibição imposta por Napoleão ao comércio com a Inglaterra'],['Congresso de Viena','reunião que restaurou as monarquias após Napoleão'],['18 Brumário','golpe que levou Napoleão ao poder em 1799']],
 order:[['Queda da Bastilha',1789],['Golpe do 18 Brumário',1799],['Bloqueio Continental',1806],['Batalha de Waterloo',1815],['Independência dos Estados Unidos',1776]],
 qs:[['O lema da Revolução Francesa era:','Liberdade, Igualdade, Fraternidade',['Ordem e Progresso','Paz, Terra e Pão','Deus, Pátria e Família'],'Síntese dos ideais iluministas.'],['O Bloqueio Continental afetou o Brasil porque:','levou a família real portuguesa a se transferir para o Brasil em 1808',['provocou a Independência dos EUA','acabou com a escravidão no Brasil','fez o Brasil declarar guerra à França'],'Portugal não aderiu ao bloqueio e foi invadido.']]}),
SKL('americas','Independências na América','🗽','EUA: independência em 1776 (primeira da América). Haiti (1804): primeira independência liderada por escravizados. América espanhola: Bolívar e San Martín, liderança dos criollos.',
`<ul><li><b>Estados Unidos</b>: as Treze Colônias reagiram a impostos britânicos ("sem representação, sem tributação"); <b>Declaração de Independência em 4 de julho de 1776</b>; Constituição de 1787 (república federativa e presidencialista).</li><li><b>Haiti</b> (1804): revolução de escravizados liderada por <b>Toussaint Louverture</b>; primeira república negra e primeiro país a abolir a escravidão na América.</li><li><b>América espanhola</b> (1810–1825): liderada pelos <b>criollos</b> (elite nascida na América), com <b>Simón Bolívar</b> (norte da América do Sul) e <b>José de San Martín</b> (Argentina, Chile, Peru). Resultou em vários países (fragmentação), apesar do sonho de união de Bolívar.</li></ul>
<p><b>Doutrina Monroe</b> (1823): "A América para os americanos".</p>`,
{pairs:[['Criollos','elite nascida na América espanhola, filha de espanhóis'],['Simón Bolívar','líder das independências no norte da América do Sul'],['José de San Martín','líder das independências de Argentina, Chile e Peru'],['Toussaint Louverture','líder da revolução de escravizados no Haiti'],['Doutrina Monroe','política dos EUA resumida em "A América para os americanos"'],['Declaração de Independência dos EUA','documento de 4 de julho de 1776']],
 order:[['Independência dos Estados Unidos',1776],['Independência do Haiti',1804],['Independência do Brasil',1822],['Doutrina Monroe',1823],['Constituição dos Estados Unidos',1787]],
 qs:[['A primeira independência latino-americana, liderada por escravizados, foi a do:','Haiti',['México','Brasil','Argentina'],'Haiti, 1804.'],['A liderança das independências da América espanhola coube principalmente aos:','criollos',['chapetones','indígenas','escravizados africanos'],'Elite local que queria o controle político e econômico.']]}),
SKL('imperial','Ideologias e Imperialismo','🗺️','Liberalismo, socialismo (Marx e Engels, Manifesto Comunista, 1848) e anarquismo. Imperialismo: partilha da África (Conferência de Berlim, 1884–1885) e da Ásia.',
`<h3>Ideologias do século XIX</h3><ul><li><b>Liberalismo</b>: liberdades individuais, livre mercado.</li><li><b>Socialismo utópico</b> (Owen, Saint-Simon) e <b>científico</b> (Marx e Engels): luta de classes, fim da propriedade privada dos meios de produção; <i>Manifesto Comunista</i> (1848).</li><li><b>Anarquismo</b> (Proudhon, Bakunin): fim do Estado.</li><li><b>Nacionalismo</b>: unificações da Itália e da Alemanha (1870–1871).</li></ul>
<h3>Imperialismo (neocolonialismo)</h3><p>Potências industrializadas buscavam matérias-primas, mercados e áreas de investimento. A <b>Conferência de Berlim</b> (1884–1885) dividiu a África entre europeus, sem respeitar povos e culturas locais. Justificativas racistas: "fardo do homem branco", darwinismo social. Na Ásia: Guerras do Ópio na China.</p>`,
{pairs:[['Socialismo científico','teoria de Marx e Engels baseada na luta de classes'],['Anarquismo','ideologia que defende o fim do Estado'],['Conferência de Berlim','reunião que dividiu a África entre potências europeias'],['Darwinismo social','ideia racista usada para justificar a dominação imperialista'],['Guerras do Ópio','conflitos em que a Inglaterra impôs o comércio de ópio à China'],['Manifesto Comunista','obra de Marx e Engels publicada em 1848']],
 order:[['Manifesto Comunista',1848],['Unificação da Alemanha',1871],['Conferência de Berlim',1884],['Início da Primeira Guerra Mundial',1914]],
 qs:[['Um dos principais objetivos do Imperialismo do século XIX era:','obter matérias-primas e mercados consumidores para as indústrias',['difundir a democracia na África','acabar com a escravidão mundial','ajudar os países asiáticos a se industrializarem'],'Necessidades da 2ª Revolução Industrial.']]})
]});

/* ------------------------ UNIDADE 4 — BRASIL COLÔNIA E IMPÉRIO ------------------------ */
UNITS.push({id:'h4',title:'Brasil Colônia e Império',sub:'Colonização, açúcar, ouro, escravidão, revoltas, Independência e Império',color:'#ce82ff',dark:'#a568cc',skills:[
SKL('colonia','Brasil Colônia','🌴','Capitanias hereditárias (1534) → Governo-Geral (1549, Salvador). Ciclo do açúcar no Nordeste com trabalho escravizado africano; ouro em Minas no século XVIII.',
`<ul><li><b>Período pré-colonial</b> (1500–1530): extração do <b>pau-brasil</b> com trabalho indígena (escambo).</li><li><b>Capitanias hereditárias</b> (1534): faixas de terra doadas a donatários; a maioria fracassou (Pernambuco e São Vicente prosperaram).</li><li><b>Governo-Geral</b> (1549): <b>Tomé de Sousa</b> funda <b>Salvador</b>, primeira capital; chegam os jesuítas.</li><li><b>Ciclo do açúcar</b> (séc. XVI–XVII, Nordeste): <b>plantation</b> — latifúndio, monocultura, exportação e <b>trabalho escravizado africano</b> (tráfico negreiro).</li><li><b>Invasões holandesas</b> (1630–1654, Pernambuco; Maurício de Nassau).</li><li><b>Bandeirantes</b>: expandiram o território para oeste, caçaram indígenas e encontraram ouro.</li><li><b>Ciclo do ouro</b> (séc. XVIII, Minas Gerais): quinto, derrama, urbanização; capital transferida para o <b>Rio de Janeiro em 1763</b>.</li></ul>
<p><b>Resistência</b>: <b>Quilombo dos Palmares</b> (Alagoas), liderado por <b>Zumbi</b> (morto em 20 de novembro de 1695 — Dia da Consciência Negra).</p>`,
{pairs:[['Capitanias hereditárias','faixas de terra doadas a donatários em 1534'],['Governo-Geral','administração centralizada criada em 1549, com sede em Salvador'],['Plantation','latifúndio monocultor, exportador e escravista'],['Quinto','imposto que tirava 20% do ouro para a Coroa'],['Derrama','cobrança forçada de impostos atrasados sobre o ouro'],['Quilombo dos Palmares','maior quilombo da colônia, liderado por Zumbi'],['Bandeirantes','expedições paulistas que expandiram o território e buscavam ouro e indígenas'],['Maurício de Nassau','governador do Brasil holandês em Pernambuco']],
 order:[['Chegada de Cabral',1500],['Criação das capitanias hereditárias',1534],['Fundação de Salvador',1549],['Expulsão dos holandeses',1654],['Destruição de Palmares e morte de Zumbi',1695],['Capital transferida para o Rio de Janeiro',1763]],
 qs:[['A principal atividade econômica do Brasil nos séculos XVI e XVII foi:','a produção de açúcar no Nordeste',['a mineração de ouro em Minas','o cultivo de café em São Paulo','a extração de borracha na Amazônia'],'Ciclo do açúcar.'],['A capital da colônia passou de Salvador para o Rio de Janeiro em 1763 por causa:','da importância do ouro de Minas Gerais, escoado pelo Rio',['da invasão holandesa de Salvador','da chegada da família real','da Independência'],'O Rio era o porto do ouro.']]}),
SKL('revoltas','Revoltas coloniais','⚔️','Nativistas (contra abusos, sem querer independência): Beckman, Emboabas, Mascates, Filipe dos Santos. Separatistas: Inconfidência Mineira (1789, Tiradentes) e Conjuração Baiana (1798).',
`<h3>Nativistas (sem projeto de independência)</h3><ul><li><b>Revolta de Beckman</b> (1684, MA): contra a Companhia de Comércio.</li><li><b>Guerra dos Emboabas</b> (1707–1709, MG): paulistas × forasteiros pelo ouro.</li><li><b>Guerra dos Mascates</b> (1710, PE): senhores de Olinda × comerciantes do Recife.</li><li><b>Revolta de Filipe dos Santos</b> (1720, Vila Rica): contra as Casas de Fundição.</li></ul>
<h3>Separatistas (influência iluminista)</h3><ul><li><b>Inconfidência Mineira</b> (1789): elite mineira contra a <b>derrama</b>; queria república; <b>Tiradentes</b> foi enforcado em 1792.</li><li><b>Conjuração Baiana</b> ou Revolta dos Alfaiates (1798): participação popular (alfaiates, soldados, escravizados), defendia república e <b>fim da escravidão</b>.</li><li><b>Revolução Pernambucana</b> (1817).</li></ul>`,
{pairs:[['Inconfidência Mineira','conspiração separatista de 1789 contra a derrama, com Tiradentes'],['Conjuração Baiana','revolta de 1798 com participação popular que defendia o fim da escravidão'],['Guerra dos Emboabas','conflito entre paulistas e forasteiros pelo ouro de Minas'],['Guerra dos Mascates','conflito entre senhores de Olinda e comerciantes do Recife'],['Revolta de Beckman','revolta no Maranhão contra a Companhia de Comércio'],['Revolta de Filipe dos Santos','protesto de 1720 contra as Casas de Fundição']],
 order:[['Revolta de Beckman',1684],['Guerra dos Emboabas',1707],['Revolta de Filipe dos Santos',1720],['Inconfidência Mineira',1789],['Conjuração Baiana',1798],['Revolução Pernambucana',1817]],
 qs:[['Diferentemente da Inconfidência Mineira, a Conjuração Baiana:','teve grande participação popular e propunha o fim da escravidão',['foi liderada apenas pela elite','não tinha influência iluminista','queria manter o Brasil ligado a Portugal'],'Alfaiates, soldados e escravizados participaram.']]}),
SKL('indep','Família Real, Independência e Primeiro Reinado','🇧🇷','1808: família real no Brasil e abertura dos portos. 1822: Independência (7 de setembro). 1824: primeira Constituição, com Poder Moderador. 1831: abdicação de D. Pedro I.',
`<ul><li><b>1808</b>: a família real chega ao Brasil fugindo de Napoleão; <b>abertura dos portos</b> às nações amigas (fim do pacto colonial); Banco do Brasil, Imprensa Régia, Jardim Botânico.</li><li><b>1815</b>: Brasil elevado a <b>Reino Unido</b> a Portugal e Algarves.</li><li><b>1820</b>: Revolução Liberal do Porto exige a volta do rei e a recolonização do Brasil. D. João VI volta em 1821.</li><li><b>1822</b>: Dia do Fico (9 de janeiro) e <b>Independência</b> (7 de setembro), proclamada por D. Pedro.</li><li><b>1824</b>: Constituição outorgada, com <b>Poder Moderador</b> (do imperador), voto censitário e catolicismo oficial. Reação: <b>Confederação do Equador</b> (PE).</li><li><b>1831</b>: crise política e econômica; D. Pedro I <b>abdica</b> em favor do filho de 5 anos.</li></ul>`,
{pairs:[['Abertura dos portos','medida de 1808 que acabou com o monopólio comercial português'],['Dia do Fico','decisão de D. Pedro de permanecer no Brasil (9/1/1822)'],['Poder Moderador','quarto poder, exercido pelo imperador na Constituição de 1824'],['Voto censitário','voto restrito a quem tinha determinada renda'],['Confederação do Equador','revolta de 1824 no Nordeste contra a centralização imperial'],['Revolução Liberal do Porto','movimento de 1820 que exigia a volta de D. João VI a Portugal']],
 order:[['Chegada da família real ao Brasil',1808],['Elevação a Reino Unido',1815],['Revolução Liberal do Porto',1820],['Independência do Brasil',1822],['Constituição de 1824',1824],['Abdicação de D. Pedro I',1831]],
 qs:[['A abertura dos portos em 1808 favoreceu principalmente:','a Inglaterra',['a França','a Espanha','os Estados Unidos'],'A Inglaterra era aliada de Portugal e maior potência comercial.'],['A Constituição de 1824 criou o Poder Moderador, que:','dava ao imperador o poder de intervir nos outros poderes',['limitava os poderes do imperador','criava a República','acabava com a escravidão'],'Centralização nas mãos de D. Pedro I.']]}),
SKL('regencia','Período Regencial','🌀','1831–1840: regentes governam em nome de D. Pedro II. Revoltas: Cabanagem (PA), Sabinada (BA), Balaiada (MA), Farroupilha (RS, 1835–1845) e Revolta dos Malês (BA, 1835). Termina com o Golpe da Maioridade (1840).',
`<p>Com D. Pedro II criança, o Brasil foi governado por <b>regentes</b>. O <b>Ato Adicional de 1834</b> deu autonomia às províncias, e a instabilidade gerou revoltas:</p>
<ul><li><b>Cabanagem</b> (1835–1840, Pará): participação popular (cabanos, indígenas, pobres).</li><li><b>Guerra dos Farrapos (Farroupilha)</b> (1835–1845, RS): estancieiros contra impostos sobre o charque; proclamou a República Rio-Grandense.</li><li><b>Sabinada</b> (1837–1838, Bahia): república provisória até a maioridade.</li><li><b>Balaiada</b> (1838–1841, Maranhão): sertanejos pobres e escravizados.</li><li><b>Revolta dos Malês</b> (1835, Salvador): escravizados muçulmanos.</li></ul>
<p>O <b>Golpe da Maioridade</b> (1840) antecipou a maioridade de D. Pedro II, com 14 anos.</p>`,
{pairs:[['Cabanagem','revolta popular no Pará (1835–1840)'],['Farroupilha','revolta de estancieiros gaúchos (1835–1845) que proclamou a República Rio-Grandense'],['Sabinada','revolta na Bahia que proclamou uma república provisória'],['Balaiada','revolta no Maranhão com sertanejos pobres e escravizados'],['Revolta dos Malês','levante de escravizados muçulmanos em Salvador (1835)'],['Golpe da Maioridade','antecipação da maioridade de D. Pedro II em 1840']],
 qs:[['A Revolução Farroupilha teve como uma das causas:','a concorrência do charque estrangeiro e os impostos sobre o produto gaúcho',['a abolição da escravidão','a proclamação da República no Rio','a Guerra do Paraguai'],'Estancieiros gaúchos contra a política fiscal imperial.'],['O Período Regencial terminou com:','o Golpe da Maioridade, em 1840',['a Proclamação da República','a Independência','a Lei Áurea'],'D. Pedro II assumiu com 14 anos.']]}),
SKL('segreinado','Segundo Reinado e abolição','☕','Café no Sudeste, Guerra do Paraguai (1864–1870) e abolição gradual: Eusébio de Queirós (1850), Ventre Livre (1871), Sexagenários (1885) e Lei Áurea (13/5/1888). República proclamada em 15/11/1889.',
`<ul><li><b>Economia</b>: <b>café</b> no Vale do Paraíba e depois no Oeste Paulista; ferrovias; imigração europeia (italianos) substituindo a mão de obra escravizada.</li><li><b>Política</b>: parlamentarismo "às avessas" (o imperador escolhia o chefe do gabinete); partidos Liberal e Conservador.</li><li><b>Guerra do Paraguai</b> (1864–1870): Tríplice Aliança (Brasil, Argentina, Uruguai) contra o Paraguai de Solano López; fortaleceu o Exército.</li><li><b>Abolição gradual</b>: Lei <b>Eusébio de Queirós</b> (1850, fim do tráfico), <b>Ventre Livre</b> (1871), <b>Sexagenários</b> (1885) e <b>Lei Áurea</b> (13 de maio de 1888, assinada pela princesa Isabel), sem indenização nem integração dos libertos.</li><li><b>Crise do Império</b>: questões religiosa, militar e abolicionista; <b>Proclamação da República</b> por Deodoro da Fonseca em <b>15 de novembro de 1889</b>.</li></ul>`,
{pairs:[['Lei Eusébio de Queirós','proibiu o tráfico de escravizados para o Brasil (1850)'],['Lei do Ventre Livre','declarou livres os filhos de escravizadas nascidos a partir de 1871'],['Lei dos Sexagenários','libertou escravizados com mais de 60 anos (1885)'],['Lei Áurea','aboliu a escravidão no Brasil em 13 de maio de 1888'],['Guerra do Paraguai','conflito da Tríplice Aliança contra o Paraguai (1864–1870)'],['Lei de Terras','lei de 1850 que dificultou o acesso à terra para os pobres e ex-escravizados'],['Parlamentarismo às avessas','sistema em que o imperador escolhia o chefe do gabinete']],
 order:[['Lei Eusébio de Queirós',1850],['Início da Guerra do Paraguai',1864],['Lei do Ventre Livre',1871],['Lei dos Sexagenários',1885],['Lei Áurea',1888],['Proclamação da República',1889]],
 qs:[['A abolição no Brasil (1888) foi marcada por:','ausência de políticas de integração dos libertos',['indenização aos ex-escravizados','distribuição de terras aos libertos','ser a primeira das Américas'],'O Brasil foi o último país das Américas a abolir e não houve reparação.'],['A principal atividade econômica do Segundo Reinado foi:','o café',['o açúcar','o ouro','a borracha'],'Café no Sudeste, principal exportação.']]})
]});

/* ------------------------ UNIDADE 5 — BRASIL REPÚBLICA ------------------------ */
UNITS.push({id:'h5',title:'Brasil República',sub:'República Velha, Era Vargas, República de 1946, Ditadura Militar e Nova República',color:'#ff4b4b',dark:'#ea2b2b',skills:[
SKL('repvelha','República Velha (1889–1930)','🎩','Política do café com leite (SP e MG), política dos governadores, coronelismo e voto de cabresto. Revoltas: Canudos, Contestado, Vacina, Chibata e tenentismo.',
`<ul><li><b>República da Espada</b> (Deodoro, Floriano) e <b>Constituição de 1891</b>: federalismo, presidencialismo, voto aberto e masculino (analfabetos excluídos), separação entre Igreja e Estado.</li><li><b>República Oligárquica</b>: <b>política do café com leite</b> (alternância entre SP e MG), <b>política dos governadores</b> (apoio mútuo entre presidente e oligarquias estaduais), <b>coronelismo</b> e <b>voto de cabresto</b>.</li><li><b>Revoltas</b>: <b>Canudos</b> (1896–1897, BA, Antônio Conselheiro), <b>Contestado</b> (1912–1916, PR/SC), <b>Revolta da Vacina</b> (1904, RJ, contra a vacinação obrigatória de Oswaldo Cruz), <b>Revolta da Chibata</b> (1910, marinheiros liderados por João Cândido contra castigos físicos), <b>tenentismo</b> (anos 1920, Coluna Prestes).</li><li><b>Crise de 1929</b> e a disputa de 1930 levaram à <b>Revolução de 1930</b>, que pôs Getúlio Vargas no poder.</li></ul>`,
{pairs:[['Política do café com leite','alternância de São Paulo e Minas Gerais na presidência'],['Coronelismo','poder local dos grandes proprietários rurais'],['Voto de cabresto','voto controlado pelos coronéis, já que era aberto'],['Guerra de Canudos','conflito de 1896–1897 contra a comunidade de Antônio Conselheiro, na Bahia'],['Revolta da Vacina','revolta de 1904 contra a vacinação obrigatória no Rio'],['Revolta da Chibata','revolta de marinheiros contra castigos físicos (1910)'],['Tenentismo','movimento de jovens oficiais do Exército contra as oligarquias nos anos 1920'],['Política dos governadores','troca de apoio entre o presidente e as oligarquias estaduais']],
 order:[['Constituição de 1891',1891],['Guerra de Canudos',1896],['Revolta da Vacina',1904],['Revolta da Chibata',1910],['Semana de Arte Moderna',1922],['Revolução de 1930',1930]],
 qs:[['O voto de cabresto era possível porque:','o voto era aberto, e os coronéis controlavam os eleitores',['o voto era secreto','só mulheres votavam','o voto era obrigatório para analfabetos'],'Sem voto secreto, o eleitor era vigiado.']]}),
SKL('vargas','Era Vargas (1930–1945)','🗳️','Governo Provisório (1930–34), Constitucional (1934–37) e Estado Novo (1937–45, ditadura). Voto feminino e secreto (1932), CLT (1943), trabalhismo e populismo.',
`<ul><li><b>Governo Provisório</b> (1930–1934): centralização; <b>Código Eleitoral de 1932</b> (voto secreto e <b>voto feminino</b>); <b>Revolução Constitucionalista de 1932</b> (SP).</li><li><b>Governo Constitucional</b> (1934–1937): Constituição de 1934 (direitos trabalhistas); disputa entre <b>Integralistas</b> (fascistas) e <b>ANL</b> (comunistas; Intentona de 1935).</li><li><b>Estado Novo</b> (1937–1945): <b>ditadura</b>; Constituição "Polaca"; censura (DIP); <b>CLT</b> (1943), salário mínimo (1940), CSN (siderurgia); entrada na Segunda Guerra ao lado dos Aliados (FEB).</li><li>Deposto em 1945; volta eleito em 1951, cria a <b>Petrobras</b> (1953, "O petróleo é nosso") e se suicida em 1954.</li></ul>
<p><b>Populismo</b>: liderança carismática que se apoia nas massas urbanas, com concessões trabalhistas e controle dos sindicatos.</p>`,
{pairs:[['Estado Novo','ditadura de Vargas entre 1937 e 1945'],['CLT','Consolidação das Leis do Trabalho, de 1943'],['Revolução Constitucionalista','levante paulista de 1932 que exigia uma Constituição'],['Código Eleitoral de 1932','instituiu o voto secreto e o voto feminino'],['DIP','órgão de propaganda e censura do Estado Novo'],['Integralismo','movimento brasileiro inspirado no fascismo'],['Petrobras','estatal do petróleo criada em 1953 no segundo governo Vargas']],
 order:[['Revolução de 1930',1930],['Revolução Constitucionalista',1932],['Golpe do Estado Novo',1937],['CLT',1943],['Criação da Petrobras',1953],['Suicídio de Vargas',1954]],
 qs:[['O voto feminino foi garantido no Brasil em:','1932, no governo Vargas',['1889, com a República','1988, com a Constituição Cidadã','1964, com os militares'],'Código Eleitoral de 1932.'],['O Estado Novo (1937–1945) foi:','uma ditadura, com censura e fechamento do Congresso',['um período democrático com eleições livres','o governo de Juscelino','o início da República Velha'],'Vargas governou por decretos.']]}),
SKL('rep46','República de 1946 a 1964','🏗️','JK (1956–61): Plano de Metas "50 anos em 5" e Brasília (1960). Jânio renuncia (1961); Jango propõe reformas de base e é deposto pelo golpe de 1964.',
`<ul><li><b>Dutra</b> (1946–1951): Constituição de 1946; alinhamento aos EUA na Guerra Fria.</li><li><b>Vargas</b> (1951–1954): nacionalismo, Petrobras; crise e suicídio.</li><li><b>Juscelino Kubitschek</b> (1956–1961): <b>Plano de Metas</b> ("50 anos em 5"), indústria automobilística, capital estrangeiro, <b>inauguração de Brasília (1960)</b>; inflação e dívida externa.</li><li><b>Jânio Quadros</b> (1961): renúncia após 7 meses.</li><li><b>João Goulart (Jango)</b> (1961–1964): parlamentarismo provisório; <b>reformas de base</b> (agrária, urbana, educacional); polarização; <b>golpe civil-militar de 31 de março/1º de abril de 1964</b>.</li></ul>`,
{pairs:[['Plano de Metas','programa de JK para desenvolver o país "50 anos em 5"'],['Brasília','nova capital inaugurada em 1960 por Juscelino'],['Reformas de base','propostas de Jango, como a reforma agrária'],['Jânio Quadros','presidente que renunciou em 1961'],['Constituição de 1946','carta democrática que encerrou o Estado Novo']],
 order:[['Constituição de 1946',1946],['Inauguração de Brasília',1960],['Renúncia de Jânio Quadros',1961],['Golpe civil-militar',1964]],
 qs:[['O governo JK foi marcado por:','industrialização acelerada com capital estrangeiro e a construção de Brasília',['a criação da CLT','o fim da escravidão','o Plano Real'],'Plano de Metas.']]}),
SKL('ditadura','Ditadura Militar (1964–1985)','🪖','Golpe de 1964; AI-5 (1968) endurece a repressão; "milagre econômico" (1968–73); Lei da Anistia (1979); Diretas Já (1984); eleição indireta de Tancredo (1985).',
`<ul><li><b>Golpe de 1964</b>: militares, com apoio de setores civis e dos EUA, depõem Jango.</li><li><b>Atos Institucionais</b>: bipartidarismo (ARENA × MDB), eleições indiretas; o <b>AI-5</b> (13/12/1968) fechou o Congresso, suspendeu o <i>habeas corpus</i> e ampliou a censura e a tortura.</li><li><b>"Milagre econômico"</b> (1968–1973): alto crescimento com concentração de renda e endividamento; depois, crise do petróleo e inflação.</li><li>Resistência: movimento estudantil, guerrilha, artistas (música de protesto), imprensa alternativa.</li><li><b>Abertura</b> "lenta, gradual e segura" (Geisel); <b>Lei da Anistia</b> (1979, Figueiredo); volta do pluripartidarismo; <b>Diretas Já</b> (1984, emenda Dante de Oliveira rejeitada).</li><li><b>1985</b>: <b>Tancredo Neves</b> é eleito indiretamente; morre antes da posse e <b>José Sarney</b> assume.</li></ul>`,
{pairs:[['AI-5','ato institucional de 1968 que endureceu a ditadura'],['Milagre econômico','fase de alto crescimento com concentração de renda (1968–1973)'],['Lei da Anistia','lei de 1979 que perdoou crimes políticos'],['Diretas Já','campanha de 1984 por eleições diretas para presidente'],['Bipartidarismo','sistema com apenas ARENA e MDB'],['Tancredo Neves','presidente eleito indiretamente em 1985, que morreu antes da posse']],
 order:[['Golpe civil-militar',1964],['AI-5',1968],['Lei da Anistia',1979],['Diretas Já',1984],['Eleição indireta de Tancredo Neves',1985],['Constituição de 1988',1988]],
 qs:[['O AI-5, de 1968:','fechou o Congresso e suspendeu garantias como o habeas corpus',['acabou com a ditadura','convocou eleições diretas','criou a Petrobras'],'O "golpe dentro do golpe".'],['O "milagre econômico" teve como consequência negativa:','concentração de renda e aumento da dívida externa',['o fim da indústria','a queda do PIB','a hiperinflação imediata'],'"Fazer o bolo crescer para depois dividir".']]}),
SKL('novarep','Nova República','📜','Constituição de 1988 ("Cidadã"): direitos sociais, voto para analfabetos e jovens de 16 anos, SUS, racismo como crime inafiançável. Plano Real (1994) controla a hiperinflação.',
`<ul><li><b>Sarney</b> (1985–1990): planos econômicos fracassados (Cruzado) e hiperinflação; <b>Constituição de 1988</b>.</li><li><b>Constituição de 1988</b> ("Cidadã"): eleições diretas, voto facultativo para analfabetos e jovens de 16–17 anos, direitos sociais, <b>SUS</b>, direitos indígenas e quilombolas, racismo como crime inafiançável.</li><li><b>1989</b>: primeira eleição direta para presidente desde 1960 (Collor).</li><li><b>Collor</b> (1990–1992): confisco da poupança, abertura econômica; <b>impeachment</b> em 1992 (caras-pintadas).</li><li><b>Itamar Franco</b>: <b>Plano Real</b> (1994), que controlou a hiperinflação.</li><li>Governos seguintes: Fernando Henrique Cardoso (privatizações, estabilidade), Lula (programas sociais), Dilma (impeachment em 2016), Temer, Bolsonaro e novamente Lula (a partir de 2023).</li></ul>`,
{pairs:[['Constituição de 1988','chamada de Constituição Cidadã, ampliou direitos sociais e políticos'],['Plano Real','plano de 1994 que controlou a hiperinflação'],['Impeachment de Collor','afastamento do presidente em 1992 após denúncias de corrupção'],['SUS','sistema público de saúde criado pela Constituição de 1988'],['Caras-pintadas','estudantes que protestaram pelo impeachment de Collor']],
 order:[['Constituição de 1988',1988],['Primeira eleição direta após a ditadura',1989],['Impeachment de Collor',1992],['Plano Real',1994]],
 qs:[['A Constituição de 1988 estabeleceu, entre outros pontos:','voto facultativo para jovens de 16 e 17 anos e para analfabetos',['voto censitário','o fim das eleições diretas','o bipartidarismo'],'Ampliação da cidadania política.']]})
]});

/* ------------------------ UNIDADE 6 — SÉCULO XX ------------------------ */
UNITS.push({id:'h6',title:'O mundo no século XX',sub:'Guerras Mundiais, Revolução Russa, Crise de 1929, totalitarismos, Guerra Fria e descolonização',color:'#2b70c9',dark:'#1f569e',skills:[
SKL('gm1','Primeira Guerra e Revolução Russa','💥','1ª Guerra (1914–1918): Tríplice Entente × Tríplice Aliança; estopim: assassinato em Sarajevo; Tratado de Versalhes (1919) puniu a Alemanha. Revolução Russa (1917): bolcheviques de Lenin.',
`<h3>Primeira Guerra Mundial (1914–1918)</h3><p>Causas: imperialismo, nacionalismos, corrida armamentista e política de alianças — <b>Tríplice Entente</b> (Inglaterra, França, Rússia) × <b>Tríplice Aliança</b> (Alemanha, Áustria-Hungria, Itália, que mudou de lado). Estopim: assassinato do arquiduque Francisco Ferdinando em <b>Sarajevo</b>. Guerra de trincheiras; EUA entram em 1917. O <b>Tratado de Versalhes</b> (1919) impôs à Alemanha perdas territoriais e pesadas indenizações; criou-se a Liga das Nações.</p>
<h3>Revolução Russa (1917)</h3><p>Rússia czarista, agrária e desigual, arrasada pela guerra. <b>Fevereiro</b>: queda do czar Nicolau II. <b>Outubro</b>: os <b>bolcheviques</b> de <b>Lenin</b> tomam o poder ("Paz, terra e pão"). Guerra civil, NEP e criação da <b>URSS</b> (1922). <b>Stalin</b>: planos quinquenais, coletivização forçada e expurgos.</p>`,
{pairs:[['Tríplice Entente','aliança entre Inglaterra, França e Rússia'],['Tríplice Aliança','aliança entre Alemanha, Áustria-Hungria e Itália'],['Tratado de Versalhes','acordo de 1919 que impôs duras punições à Alemanha'],['Bolcheviques','grupo revolucionário liderado por Lenin'],['Guerra de trincheiras','forma de combate típica da Primeira Guerra'],['Liga das Nações','organização criada após a Primeira Guerra para manter a paz'],['Planos quinquenais','planejamento econômico de Stalin para industrializar a URSS']],
 order:[['Início da Primeira Guerra Mundial',1914],['Revolução Russa',1917],['Tratado de Versalhes',1919],['Criação da URSS',1922],['Quebra da Bolsa de Nova York',1929]],
 qs:[['O estopim da Primeira Guerra Mundial foi:','o assassinato do arquiduque Francisco Ferdinando em Sarajevo',['a invasão da Polônia','o ataque a Pearl Harbor','a Revolução Russa'],'1914.'],['O lema bolchevique "Paz, terra e pão" expressava:','o desejo de sair da guerra, reforma agrária e fim da fome',['o apoio ao czar','a vontade de continuar a guerra','a defesa do capitalismo'],'Demandas populares na Rússia de 1917.']]}),
SKL('crise29','Crise de 1929 e totalitarismos','📉','Quebra da Bolsa de Nova York (1929) → Grande Depressão → New Deal (Roosevelt). Totalitarismos: fascismo (Mussolini) e nazismo (Hitler, 1933): partido único, culto ao líder, propaganda, perseguição.',
`<p><b>Crise de 1929</b>: superprodução e especulação levaram à <b>quebra da Bolsa de Nova York</b> e à <b>Grande Depressão</b> (desemprego em massa). Nos EUA, Roosevelt lançou o <b>New Deal</b>, com intervenção do Estado na economia (ideias de Keynes). No Brasil, afetou as exportações de café.</p>
<h3>Totalitarismos</h3><p>Características comuns: <b>partido único</b>, culto ao líder, <b>propaganda</b> e censura, nacionalismo extremo, anticomunismo, antiliberalismo, militarismo e perseguição a opositores.</p><ul><li><b>Fascismo</b> (Itália, Mussolini, 1922).</li><li><b>Nazismo</b> (Alemanha, Hitler chanceler em 1933): racismo e antissemitismo, "espaço vital", SS e Gestapo; culminou no <b>Holocausto</b>.</li><li>Na Península Ibérica: salazarismo (Portugal) e franquismo (Espanha).</li></ul>`,
{pairs:[['New Deal','programa de Roosevelt com intervenção do Estado para vencer a crise de 1929'],['Grande Depressão','crise econômica mundial após a quebra da Bolsa em 1929'],['Fascismo','regime totalitário de Mussolini na Itália'],['Nazismo','regime totalitário de Hitler, marcado pelo racismo e antissemitismo'],['Holocausto','extermínio sistemático de judeus e outros grupos pelos nazistas'],['Espaço vital','ideia nazista de expansão territorial alemã']],
 order:[['Marcha sobre Roma (Mussolini no poder)',1922],['Quebra da Bolsa de Nova York',1929],['Hitler chanceler da Alemanha',1933],['Início da Segunda Guerra Mundial',1939]],
 qs:[['A Crise de 1929 teve como causa principal:','a superprodução e a especulação financeira nos EUA',['a Revolução Russa','a Segunda Guerra Mundial','o petróleo árabe'],'Produção maior que o consumo e ações supervalorizadas.'],['Uma característica comum ao nazismo e ao fascismo é:','o partido único e o culto ao líder',['a defesa da democracia liberal','o internacionalismo operário','a tolerância às minorias'],'Regimes totalitários.']]}),
SKL('gm2','Segunda Guerra Mundial','🌐','1939–1945: Eixo (Alemanha, Itália, Japão) × Aliados (Inglaterra, URSS, EUA, França). Início: invasão da Polônia. Fim: rendição alemã (maio/1945) e bombas de Hiroshima e Nagasaki (agosto/1945). Criação da ONU (1945).',
`<ul><li><b>Início</b>: invasão da <b>Polônia</b> pela Alemanha (1º de setembro de 1939).</li><li><b>Eixo</b>: Alemanha, Itália e Japão. <b>Aliados</b>: Inglaterra, França, URSS (a partir de 1941) e EUA (após o ataque japonês a <b>Pearl Harbor</b>, dezembro de 1941).</li><li><b>Viradas</b>: Batalha de <b>Stalingrado</b> (1942–1943) e <b>Dia D</b> (desembarque na Normandia, junho de 1944).</li><li><b>Fim</b>: rendição alemã (maio de 1945) e bombas atômicas em <b>Hiroshima e Nagasaki</b> (agosto de 1945).</li><li>O <b>Brasil</b> enviou a FEB, que lutou na Itália (Monte Castelo).</li><li><b>Consequências</b>: dezenas de milhões de mortos, Holocausto, criação da <b>ONU</b> (1945), Declaração Universal dos Direitos Humanos (1948), início da Guerra Fria.</li></ul>`,
{pairs:[['Eixo','aliança entre Alemanha, Itália e Japão'],['Pearl Harbor','ataque japonês de 1941 que levou os EUA à guerra'],['Batalha de Stalingrado','vitória soviética que virou o rumo da guerra no Leste'],['Dia D','desembarque aliado na Normandia em junho de 1944'],['FEB','Força Expedicionária Brasileira, que lutou na Itália'],['ONU','organização criada em 1945 para manter a paz mundial']],
 order:[['Invasão da Polônia',1939],['Ataque a Pearl Harbor',1941],['Dia D',1944],['Bombas de Hiroshima e Nagasaki',1945],['Declaração Universal dos Direitos Humanos',1948]],
 qs:[['A Segunda Guerra começou com:','a invasão da Polônia pela Alemanha, em 1939',['o assassinato em Sarajevo','o ataque a Pearl Harbor','a Revolução Russa'],'1º de setembro de 1939.'],['Os EUA entraram na Segunda Guerra após:','o ataque japonês a Pearl Harbor',['a invasão da França','a bomba de Hiroshima','a Batalha de Stalingrado'],'Dezembro de 1941.']]}),
SKL('fria','Guerra Fria e descolonização','🧊','1947–1991: EUA (capitalismo) × URSS (socialismo), sem guerra direta. Muro de Berlim (1961–1989), Crise dos Mísseis (1962), Guerras da Coreia e do Vietnã, corrida espacial. Fim da URSS: 1991.',
`<ul><li><b>Bipolaridade</b>: bloco capitalista (EUA, OTAN, Plano Marshall) × bloco socialista (URSS, Pacto de Varsóvia).</li><li><b>Alemanha dividida</b>; <b>Muro de Berlim</b> (1961–1989).</li><li><b>Conflitos indiretos</b>: Guerra da Coreia (1950–1953), Revolução Cubana (1959), <b>Crise dos Mísseis</b> (1962), <b>Guerra do Vietnã</b> (até 1975), Afeganistão.</li><li><b>Corrida armamentista e espacial</b>: Sputnik (1957), Gagarin (1961), homem na Lua (1969).</li><li><b>Fim</b>: reformas de Gorbachev (perestroika e glasnost), <b>queda do Muro (1989)</b> e <b>fim da URSS (1991)</b>.</li></ul>
<h3>Descolonização</h3><p>Após 1945, colônias na Ásia e na África se tornaram independentes: <b>Índia</b> (1947, resistência não violenta de <b>Gandhi</b>), Argélia (1962, guerra contra a França), colônias portuguesas (Angola e Moçambique, 1975). Muitos países ficaram com fronteiras artificiais e conflitos internos. <b>Apartheid</b> na África do Sul até o início dos anos 1990 (Nelson Mandela).</p>`,
{pairs:[['Plano Marshall','ajuda econômica dos EUA para reconstruir a Europa ocidental'],['OTAN','aliança militar liderada pelos EUA'],['Pacto de Varsóvia','aliança militar liderada pela URSS'],['Muro de Berlim','símbolo da divisão da Guerra Fria, derrubado em 1989'],['Crise dos Mísseis','confronto de 1962 envolvendo mísseis soviéticos em Cuba'],['Perestroika','reestruturação econômica proposta por Gorbachev'],['Apartheid','regime de segregação racial na África do Sul'],['Mahatma Gandhi','líder da independência da Índia pela resistência não violenta']],
 order:[['Independência da Índia',1947],['Revolução Cubana',1959],['Construção do Muro de Berlim',1961],['Crise dos Mísseis',1962],['Chegada do homem à Lua',1969],['Queda do Muro de Berlim',1989],['Fim da União Soviética',1991]],
 qs:[['A Guerra Fria recebe esse nome porque:','EUA e URSS não se enfrentaram diretamente em guerra',['aconteceu em regiões geladas','durou poucos meses','não houve nenhum conflito armado no mundo'],'Houve conflitos indiretos, mas não guerra direta entre as superpotências.'],['A independência da Índia (1947) teve como principal líder:','Mahatma Gandhi',['Nelson Mandela','Mao Tsé-tung','Fidel Castro'],'Resistência pacífica (desobediência civil).']]})
]});

const GLOSS=autoGloss(UNITS,[
 {k:['feudalismo','feudo'],n:'Feudalismo',s:'feudal',t:'Sistema da Europa medieval: economia agrária, sociedade estamental (clero, nobreza, servos), suserania e vassalagem e servidão.'},
 {k:['era vargas','getulio'],n:'Era Vargas',s:'vargas',t:'1930–1945: Governo Provisório, Constitucional e Estado Novo (ditadura, 1937–45). Voto feminino (1932), CLT (1943), salário mínimo.'},
 {k:['guerra fria'],n:'Guerra Fria',s:'fria',t:'1947–1991: disputa entre EUA (capitalismo) e URSS (socialismo) sem guerra direta — Muro de Berlim, Crise dos Mísseis, corrida espacial.'},
 {k:['revolucao francesa'],n:'Revolução Francesa',s:'francesa',t:'1789: Queda da Bastilha e Declaração dos Direitos do Homem. Fases: Monarquia Constitucional, Convenção (Terror) e Diretório; depois, Napoleão.'}]);
