/* =====================================================================
   Lições — Ferramentas, Cinemática e Dinâmica
   Geradores de exercício devolvem {q,a,u,sol,traps,hint} (numérico)
   ou {q,o,a:0,why,w} (múltipla escolha; a primeira opção é a correta)
   ===================================================================== */
const NUM=(q,a,u,sol,traps,hint)=>({q,a,u,sol,traps:traps||[],hint});
const MCQ=(q,o,why,w)=>({q,o,a:0,why,w});
const POOL=arr=>()=>MCQ(...pick(arr));
const F=nf;

mod('fer','Ferramentas da física','medir, escrever números e trabalhar com vetores',[
{id:'grandezas',t:'Grandezas e unidades',min:10,
 idea:`<p>A física descreve o mundo com números. Tudo o que dá para medir é uma <b>grandeza</b>: comprimento, tempo, massa, velocidade, temperatura. Uma medida sempre tem duas partes: o <b>número</b> e a <b>unidade</b>. "O carro está a 20" não diz nada; "20 m/s" diz.</p>
 <p>O Brasil usa o <b>Sistema Internacional (SI)</b>. Nele, comprimento é medido em metros (m), massa em quilogramas (kg) e tempo em segundos (s). As outras unidades são combinações dessas: velocidade em m/s, aceleração em m/s², força em newtons (N = kg·m/s²).</p>
 <p>No dia a dia usamos km/h. Para passar para m/s, lembre que 1 km = 1000 m e 1 h = 3600 s. Então 1 km/h = 1000/3600 m/s, ou seja, <b>divida por 3,6</b>. Para voltar, multiplique por 3,6.</p>`,
 pred:{q:'Um carro está a 72 km/h. Quantos metros ele anda em 1 segundo?',o:['20 m','72 m','7,2 m','260 m'],a:0,why:'72 ÷ 3,6 = 20 m/s: a cada segundo, 20 metros. Na estrada isso é quase o comprimento de quatro carros por segundo.'},
 lab:{sim:'conv'},
 tasks:['Coloque 36 km/h. Quantos metros o carro anda por segundo?','Descubra qual velocidade faz o carro percorrer os 100 m em exatamente 5 segundos.','Um velocista olímpico corre a cerca de 10 m/s. Quanto é isso em km/h?'],
 f:[{f:'v<sub class="up">(m/s)</sub> = '+frac('v<sub class="up">(km/h)</sub>','3,6'),s:[['m','metro','comprimento'],['kg','quilograma','massa'],['s','segundo','tempo'],['K','kelvin','temperatura'],['A','ampere','corrente elétrica']],n:'Essas cinco são unidades de base do SI. 1 km = 1000 m · 1 h = 60 min = 3600 s · 1 kg = 1000 g · 1 m = 100 cm.'}],
 ex:{q:'Converta 90 km/h para m/s.',s:['90 km em metros: 90 × 1000 = 90 000 m.','1 hora em segundos: 3600 s.','90 000 m ÷ 3600 s = <b>25 m/s</b>.','Atalho: 90 ÷ 3,6 = 25. Dá o mesmo resultado porque 3600 ÷ 1000 = 3,6.']},
 probs:[
  ()=>{ const v=pick([18,36,54,72,90,108,126,144]); return NUM(`Converta <b>${v} km/h</b> para m/s.`,v/3.6,'m/s',[`${v} ÷ 3,6 = ${F(v/3.6)} m/s`],[[v*3.6,'Você multiplicou por 3,6. De km/h para m/s se <b>divide</b>.'],[v/60,'Você dividiu por 60. Uma hora tem 3600 segundos, e um km tem 1000 metros.']],'1 km/h equivale a 1000 m em 3600 s.'); },
  ()=>{ const v=R(5,40,5); return NUM(`Um guepardo corre a <b>${v} m/s</b>. Quanto é isso em km/h?`,v*3.6,'km/h',[`${v} × 3,6 = ${F(v*3.6)} km/h`],[[v/3.6,'De m/s para km/h se <b>multiplica</b> por 3,6.']],'O número em km/h é sempre maior que em m/s.'); },
  ()=>{ const h=pick([1.5,2,2.5,3,0.5]); return NUM(`Quantos segundos há em <b>${F(h)} h</b>?`,h*3600,'s',[`1 h = 3600 s`,`${F(h)} × 3600 = ${F(h*3600)} s`],[[h*60,'Isso são minutos. Cada minuto ainda tem 60 segundos.']],'Cada hora tem 60 minutos, e cada minuto tem 60 segundos.'); },
  ()=>{ const g=R(50,950,50); return NUM(`Uma fruta tem massa de <b>${g} g</b>. Quanto é em kg?`,g/1000,'kg',[`1 kg = 1000 g`,`${g} ÷ 1000 = ${F(g/1000)} kg`],[[g*1000,'De grama para quilograma o número fica <b>menor</b>: divida por 1000.'],[g/100,'O quilo tem 1000 gramas, não 100.']]); },
  POOL([['Qual destas é a unidade de massa no SI?',['quilograma (kg)','grama (g)','newton (N)','litro (L)'],'O SI usa o quilograma. O newton mede força; o litro, volume.'],['Qual destas é uma grandeza vetorial (precisa de direção e sentido)?',['velocidade','tempo','massa','temperatura'],'Velocidade tem módulo, direção e sentido. Tempo, massa e temperatura só têm valor: são escalares.'],['"A mesa mede 2" está incompleto porque falta:',['a unidade','o sinal','a notação científica','o vetor'],'Sem unidade não dá para saber se são 2 metros, 2 centímetros ou 2 pés.']])],
 traps:['Esquecer a unidade na resposta: 20 não é o mesmo que 20 m/s.','Multiplicar por 3,6 quando deveria dividir. Lembre: m/s é um número menor que km/h.','Somar grandezas diferentes, como 3 m + 2 s. Só se somam grandezas de mesma espécie e mesma unidade.'],
 keep:['Medida = número + unidade.','km/h → m/s: divida por 3,6. m/s → km/h: multiplique por 3,6.','SI: metro, quilograma, segundo.']},

{id:'potencias',t:'Notação científica e ordem de grandeza',min:12,
 idea:`<p>A física trata do muito pequeno (um átomo mede 0,0000000001 m) e do muito grande (a Terra fica a 150 000 000 000 m do Sol). Escrever tantos zeros é fácil de errar, por isso usamos a <b>notação científica</b>: um número entre 1 e 10 multiplicado por uma potência de 10.</p>
 <p>150 000 000 000 = 1,5 × 10<sup>11</sup> (a vírgula andou 11 casas para a esquerda). 0,00045 = 4,5 × 10<sup>−4</sup> (a vírgula andou 4 casas para a direita, então o expoente é negativo).</p>
 <p>Para multiplicar, multiplique os números e <b>some os expoentes</b>; para dividir, divida os números e <b>subtraia os expoentes</b>. A <b>ordem de grandeza</b> é a potência de 10 mais próxima do valor: se o número da frente for 3,16 ou mais (√10), arredonde para a potência seguinte.</p>`,
 pred:{q:'A Terra está a 150 milhões de quilômetros do Sol. Em metros, isso é:',o:['1,5 × 10¹¹ m','1,5 × 10⁸ m','1,5 × 10⁶ m','150 × 10⁶ m'],a:0,why:'150 milhões de km = 1,5 × 10⁸ km. Cada km tem 10³ m, então 1,5 × 10⁸ × 10³ = 1,5 × 10¹¹ m. (150 × 10⁶ não está em notação científica: o número da frente precisa ficar entre 1 e 10.)'},
 lab:{sim:'pow10'},
 tasks:['Ande pela régua do átomo até a galáxia. Quantas potências de 10 separam um átomo de uma pessoa?','Encontre o prefixo "quilo" e o "micro". Quanto vale cada um?','A distância São Paulo–Rio é 3,6 × 10⁵ m. Por que a ordem de grandeza dela é 10⁶, e não 10⁵?'],
 f:[{f:'a × 10<sup>n</sup>, com 1 ≤ a &lt; 10',s:[['n > 0','número grande: a vírgula andou n casas para a esquerda',''],['n < 0','número pequeno: a vírgula andou n casas para a direita','']]},{f:'(a×10<sup>m</sup>)·(b×10<sup>n</sup>) = (a·b)×10<sup>m+n</sup>',n:'Na divisão, subtraia: 10<sup>m</sup> ÷ 10<sup>n</sup> = 10<sup>m−n</sup>. Prefixos: k = 10³, M = 10⁶, G = 10⁹, m = 10⁻³, μ = 10⁻⁶, n = 10⁻⁹.'}],
 ex:{q:'Calcule (3 × 10⁸) × (2 × 10⁻³).',s:['Multiplique os números da frente: 3 × 2 = 6.','Some os expoentes: 8 + (−3) = 5.','Resultado: <b>6 × 10⁵</b>.']},
 probs:[
  ()=>{ const m=pick([1.2,2.5,3.6,4.5,7.2,9.1]), e=pick([-6,-5,-4,-3,3,4,5,6,7,8]); const txt=e>0?(m*10**e).toLocaleString('pt-BR'):(m*10**e).toFixed(-e+1).replace('.',','); return NUM(`Escreva <b>${txt}</b> em notação científica: ${F(m)} × 10<sup>?</sup>. Qual é o expoente?`,e,'',[`A vírgula de ${txt} precisa andar ${Math.abs(e)} casas até ficar ${F(m)}.`,`${e>0?'Número grande: expoente positivo':'Número pequeno: expoente negativo'} → ${e}.`],[[-e,'O sinal está trocado: números menores que 1 têm expoente negativo, e maiores que 10, positivo.'],[e>0?e+1:e-1,'Conte de novo as casas que a vírgula andou.'],[e>0?e-1:e+1,'Conte de novo as casas que a vírgula andou.']],'Conte quantas casas a vírgula anda até sobrar um só algarismo antes dela.'); },
  ()=>{ const a=pick([2,3,4]), b=pick([1.5,2,2]), m=R(2,9), n=R(-6,5); const r=a*b*10**(m+n); return NUM(`Calcule (${a} × 10<sup>${m}</sup>) × (${F(b)} × 10<sup>${n}</sup>).`,r,'',[`${a} × ${F(b)} = ${F(a*b)}`,`${m} + (${n}) = ${m+n}`,`Resultado: ${F(a*b)} × 10<sup>${m+n}</sup>`],[[a*b*10**(m*n),'Na multiplicação os expoentes se <b>somam</b>, não se multiplicam.'],[a*b*10**(m-n),'Na multiplicação os expoentes se somam; subtrair é na divisão.']],'Digite no formato 6e5 ou 6x10^5.'); },
  ()=>{ const a=pick([6,8,9]), b=pick([2,3,4]), m=R(4,12), n=R(1,5); return NUM(`Calcule (${a} × 10<sup>${m}</sup>) ÷ (${b} × 10<sup>${n}</sup>).`,a/b*10**(m-n),'',[`${a} ÷ ${b} = ${F(a/b)}`,`${m} − ${n} = ${m-n}`,`Resultado: ${F(a/b)} × 10<sup>${m-n}</sup>`],[[a/b*10**(m+n),'Na divisão os expoentes se <b>subtraem</b>.']],'Digite no formato 3e5 ou 3x10^5.'); },
  ()=>{ const m=pick([1.5,2.2,2.9,3.5,4.2,6.8,8.5]), e=R(2,9); const og=m>=3.16?e+1:e; return NUM(`Qual é a ordem de grandeza de <b>${F(m)} × 10<sup>${e}</sup></b>? Responda o expoente da potência de 10.`,og,'',[`Compare ${F(m)} com √10 ≈ 3,16.`,m>=3.16?`${F(m)} ≥ 3,16, então arredonde para 10<sup>${e+1}</sup>.`:`${F(m)} &lt; 3,16, então fica 10<sup>${e}</sup>.`],[[m>=3.16?e:e+1,m>=3.16?'Como '+F(m)+' passa de 3,16, a potência mais próxima é a seguinte.':'Como '+F(m)+' é menor que 3,16, a potência mais próxima é a própria.']],'O ponto de virada é √10 ≈ 3,16, não 5.'); },
  POOL([['1 μm (micrômetro) é igual a:',['10⁻⁶ m','10⁻³ m','10⁻⁹ m','10⁶ m'],'O prefixo micro (μ) vale 10⁻⁶.'],['3 km equivalem a:',['3 × 10³ m','3 × 10⁻³ m','3 × 10⁶ m','30 m'],'Quilo vale 10³.'],['Qual número está em notação científica correta?',['4,7 × 10⁵','47 × 10⁴','0,47 × 10⁶','4,7 × 10^5,2'],'O número da frente precisa estar entre 1 e 10, e o expoente é inteiro.']])],
 traps:['Esquecer o sinal negativo do expoente para números menores que 1.','Deixar o número da frente fora do intervalo de 1 a 10 (como 45 × 10³).','Multiplicar os expoentes em vez de somá-los.'],
 keep:['Número grande → expoente positivo; número pequeno → expoente negativo.','Multiplicação soma os expoentes; divisão subtrai.','Ordem de grandeza: compare o número da frente com 3,16.']},

{id:'vetores',t:'Vetores',min:15,
 idea:`<p>Algumas grandezas precisam só de um número: 3 kg, 20 °C. São as <b>escalares</b>. Outras precisam dizer também <b>para onde</b>: andar 5 m para o norte é diferente de 5 m para o sul. São as <b>vetoriais</b>: deslocamento, velocidade, aceleração, força.</p>
 <p>Um vetor tem <b>módulo</b> (tamanho), <b>direção</b> (a reta: horizontal, vertical…) e <b>sentido</b> (para qual lado dessa reta). Desenhamos como uma seta.</p>
 <p>Para somar vetores, coloque a cauda de um na ponta do outro: a <b>resultante</b> vai do começo do primeiro ao fim do último. Se forem perpendiculares, use Pitágoras. Outra forma é decompor cada vetor em <b>componentes</b> x e y e somar as componentes separadamente.</p>`,
 pred:{q:'Você anda 3 m para leste e depois 4 m para norte. A que distância do ponto de partida você está?',o:['5 m','7 m','1 m','12 m'],a:0,why:'Os deslocamentos são perpendiculares, então formam um triângulo retângulo: √(3² + 4²) = √25 = 5 m. Você andou 7 m no total, mas está a 5 m do início.'},
 lab:{sim:'vec'},
 tasks:['Monte A = (3, 0) e B = (0, 4). Confira o módulo de R.','Faça R ficar igual a zero. Como os dois vetores precisam estar?','Troque para A − B e compare com A + B.'],
 f:[{f:'|R| = √(R<sub class="up">x</sub>² + R<sub class="up">y</sub>²)',s:[['Rₓ','componente horizontal (soma das componentes x)',''],['R<sub>y</sub>','componente vertical (soma das componentes y)','']]},{f:'Aₓ = A·cos θ   A<sub class="up">y</sub> = A·sen θ',s:[['θ','ângulo entre o vetor e o eixo x','graus']],n:'Valores úteis: sen 30° = cos 60° = 0,5 · sen 60° = cos 30° ≈ 0,87 · sen 45° = cos 45° ≈ 0,71.'}],
 ex:{q:'Duas forças perpendiculares, de 6 N e 8 N, puxam uma caixa. Qual é a força resultante?',s:['As forças formam os catetos de um triângulo retângulo.','R = √(6² + 8²) = √(36 + 64) = √100.','<b>R = 10 N</b>, e não 14 N: forças perpendiculares não se somam direto.']},
 probs:[
  ()=>{ const [a,b,c]=pick([[3,4,5],[6,8,10],[5,12,13],[8,15,17],[9,12,15],[12,16,20]]); return NUM(`Duas forças perpendiculares de <b>${a} N</b> e <b>${b} N</b> atuam num corpo. Qual é o módulo da resultante?`,c,'N',[`R = √(${a}² + ${b}²)`,`R = √(${a*a} + ${b*b}) = √${c*c} = ${c} N`],[[a+b,'Somar os módulos só vale para forças na mesma direção e sentido. Perpendiculares: use Pitágoras.'],[b-a,'Subtrair vale para forças opostas. Perpendiculares: use Pitágoras.']],'Desenhe: os vetores formam um triângulo retângulo.'); },
  ()=>{ const a=R(8,30), b=R(2,a-2); return NUM(`Numa brincadeira de cabo de guerra, um time puxa com <b>${a*10} N</b> para a direita e o outro com <b>${b*10} N</b> para a esquerda. Qual é o módulo da força resultante?`,(a-b)*10,'N',[`Mesma direção, sentidos opostos: subtraia.`,`${a*10} − ${b*10} = ${(a-b)*10} N, para a direita`],[[(a+b)*10,'As forças são opostas: uma cancela parte da outra.']]); },
  ()=>{ const A=R(10,50,10), th=pick([30,60]); const ax=A*Math.cos(th*Math.PI/180); return NUM(`Um vetor de módulo <b>${A}</b> faz <b>${th}°</b> com o eixo x. Qual é a sua componente x? (cos 30° ≈ 0,87; cos 60° = 0,5)`,ax,'',[`Aₓ = A·cos θ = ${A} × cos ${th}°`,`Aₓ = ${F(ax)}`],[[A*Math.sin(th*Math.PI/180),'Você usou o seno. A componente x (vizinha ao ângulo) usa o cosseno.']],'A componente do lado do ângulo usa cosseno.'); },
  ()=>{ const a=R(2,9), b=R(2,9); return MCQ(`Duas forças de <b>${a} N</b> e <b>${b} N</b> atuam num corpo, em direções quaisquer. Qual valor <b>não</b> pode ser a resultante?`,[`${a+b+2} N`,`${Math.abs(a-b)} N`,`${a+b} N`,`${Math.max(a,b)} N`],`A resultante sempre fica entre ${Math.abs(a-b)} N (forças opostas) e ${a+b} N (mesmo sentido). ${a+b+2} N passa do máximo.`); },
  POOL([['Qual par forma uma grandeza escalar e uma vetorial, nessa ordem?',['massa e força','força e velocidade','tempo e massa','aceleração e peso'],'Massa só tem valor; força tem direção e sentido.'],['Dois vetores têm resultante nula. Então eles têm:',['mesmo módulo e sentidos opostos','mesmo módulo e mesmo sentido','direções perpendiculares','módulos diferentes'],'Só se anulam se forem iguais em tamanho, na mesma direção e com sentidos contrários.']])],
 traps:['Somar módulos de vetores que não estão na mesma direção.','Confundir direção (a reta) com sentido (o lado da reta).','Trocar seno e cosseno: a componente adjacente ao ângulo usa o cosseno.'],
 keep:['Vetor: módulo, direção e sentido.','Perpendiculares: R = √(a² + b²). Mesmo sentido: somam. Opostos: subtraem.','Decompor: Aₓ = A cos θ, A<sub>y</sub> = A sen θ.']}]);

mod('cin','Cinemática','descrever o movimento: posição, velocidade e aceleração',[
{id:'mu',t:'Velocidade e movimento uniforme',min:14,
 idea:`<p><b>Velocidade média</b> é quanto a posição muda por unidade de tempo: v = Δs/Δt. Se um ônibus anda 120 km em 2 h, sua velocidade média é 60 km/h, mesmo que tenha parado em semáforos.</p>
 <p>No <b>movimento uniforme (MU)</b>, a velocidade é constante: o corpo percorre distâncias iguais em tempos iguais. A posição em cada instante segue a <b>função horária</b> s = s₀ + v·t, em que s₀ é a posição no instante zero.</p>
 <p>No gráfico posição × tempo, o MU aparece como uma <b>reta</b>: quanto mais inclinada, maior a velocidade. No gráfico velocidade × tempo, é uma linha horizontal, e a <b>área</b> embaixo dela é o deslocamento. Velocidade negativa significa andar no sentido contrário ao da trajetória orientada.</p>`,
 pred:{q:'No gráfico posição × tempo, uma reta mais inclinada significa:',o:['velocidade maior','aceleração maior','posição inicial maior','movimento mais lento'],a:0,why:'A inclinação é Δs/Δt, que é a própria velocidade. Reta mais em pé: mais metros a cada segundo.'},
 lab:{sim:'mov',cfg:{acc:false}},
 tasks:['Compare v₀ = 4 m/s e v₀ = 12 m/s. O que muda no gráfico s × t?','Coloque v₀ negativo. Para onde vai o carro, e o que acontece com o gráfico?','Ao final, confira: a área sob o gráfico v × t é igual ao deslocamento?'],
 f:[{f:'v = '+frac('Δs','Δt'),s:[['v','velocidade média','m/s'],['Δs','deslocamento (posição final − inicial)','m'],['Δt','intervalo de tempo','s']]},{f:'s = s₀ + v·t',s:[['s','posição no instante t','m'],['s₀','posição inicial (em t = 0)','m'],['t','tempo','s']]}],
 ex:{q:'Um ônibus passa pelo km 20 de uma estrada às 8 h, com velocidade constante de 60 km/h. Em que quilômetro estará às 10 h?',s:['Tempo decorrido: t = 10 − 8 = 2 h.','s = s₀ + v·t = 20 + 60 × 2.','<b>s = 140 km</b> (km 140).']},
 probs:[
  ()=>{ const d=R(100,900,50), t=R(10,100,5); return NUM(`Um ciclista percorre <b>${d} m</b> em <b>${t} s</b>. Qual é a sua velocidade média?`,d/t,'m/s',[`v = Δs/Δt = ${d}/${t}`,`v = ${F(d/t)} m/s`],[[t/d,'Você dividiu o tempo pela distância. Velocidade é distância ÷ tempo.'],[d*t,'Velocidade é distância <b>dividida</b> pelo tempo.']]); },
  ()=>{ const s0=R(-20,50,5), v=pick([-8,-5,-3,2,4,6,10,12]), t=R(2,10); return NUM(`Um carrinho segue a função horária <b>s = ${s0} ${v<0?'−':'+'} ${Math.abs(v)}·t</b> (SI). Qual é a posição em t = ${t} s?`,s0+v*t,'m',[`s = ${s0} ${v<0?'−':'+'} ${Math.abs(v)} × ${t}`,`s = ${s0+v*t} m`],[[v*t,'Faltou somar a posição inicial s₀.'],[s0+v,'Faltou multiplicar a velocidade pelo tempo.'],[s0-v*t,'Confira o sinal da velocidade.']]); },
  ()=>{ const D=R(100,600,50), v1=R(40,90,10), v2=R(40,90,10); return NUM(`Duas cidades ficam a <b>${D} km</b> uma da outra. Um carro sai de cada uma, no mesmo instante, um em direção ao outro, a <b>${v1} km/h</b> e <b>${v2} km/h</b>. Depois de quantas horas eles se encontram?`,D/(v1+v2),'h',[`Indo um em direção ao outro, a distância entre eles diminui ${v1} + ${v2} = ${v1+v2} km a cada hora.`,`t = ${D} ÷ ${v1+v2} = ${F(D/(v1+v2))} h`],v1!==v2?[[D/Math.abs(v1-v2),'Subtrair as velocidades vale quando um persegue o outro. Aqui eles se aproximam: some.']]:[],'Pense em quanto a distância entre eles diminui a cada hora.'); },
  ()=>{ const d=pick([100,200,400,800]), t=pick([10,20,25,40,50,80,100]); const v=d/t; return NUM(`Um atleta corre <b>${d} m</b> em <b>${t} s</b>. Qual é a velocidade média em <b>km/h</b>?`,v*3.6,'km/h',[`Em m/s: ${d}/${t} = ${F(v)} m/s`,`Em km/h: ${F(v)} × 3,6 = ${F(v*3.6)} km/h`],[[v,'Esse valor está em m/s. Multiplique por 3,6.'],[v/3.6,'De m/s para km/h se multiplica por 3,6.']]); },
  POOL([['Num gráfico velocidade × tempo, a área sob a linha representa:',['o deslocamento','a aceleração','a velocidade média','o tempo total'],'Área = velocidade × tempo = deslocamento.'],['Um carro fica parado no semáforo por 30 s. No gráfico s × t, esse trecho é:',['uma linha horizontal','uma reta inclinada para cima','uma reta vertical','uma parábola'],'Parado, a posição não muda com o tempo: linha horizontal.'],['Na função s = 50 − 10t, o carro:',['anda no sentido contrário ao da trajetória, a 10 m/s','está parado na posição 50 m','acelera a 10 m/s²','anda a 50 m/s'],'O sinal negativo da velocidade indica movimento retrógrado.']])],
 traps:['Usar a distância total em vez do deslocamento (posição final − inicial) quando há ida e volta.','Misturar unidades: km com s, ou m/s com h.','Esquecer a posição inicial s₀ na função horária.'],
 keep:['v = Δs/Δt.','MU: s = s₀ + v·t, reta no gráfico s × t.','A área sob v × t é o deslocamento.']},

{id:'muv',t:'Aceleração e MUV',min:18,
 idea:`<p><b>Aceleração</b> é quanto a velocidade muda por unidade de tempo: a = Δv/Δt. Um carro que vai de 0 a 20 m/s em 10 s tem aceleração de 2 m/s²: ganha 2 m/s a cada segundo.</p>
 <p>No <b>movimento uniformemente variado (MUV)</b>, a aceleração é constante. A velocidade cresce (ou diminui) em linha reta, v = v₀ + a·t, e a posição forma uma <b>parábola</b>: s = s₀ + v₀·t + a·t²/2. Como o tempo aparece ao quadrado, dobrar o tempo quadruplica a distância percorrida a partir do repouso.</p>
 <p>Quando o tempo não aparece no problema, use a <b>equação de Torricelli</b>: v² = v₀² + 2·a·Δs. Frear é acelerar no sentido contrário ao movimento (a negativa quando v é positiva).</p>`,
 pred:{q:'Um carro parte do repouso com aceleração constante e anda 1 m no primeiro segundo. Quantos metros terá percorrido ao fim de 2 segundos?',o:['4 m','2 m','3 m','8 m'],a:0,why:'Partindo do repouso, s = a·t²/2. Com o dobro do tempo, a distância fica 2² = 4 vezes maior. Ele é mais rápido no segundo segundo do que no primeiro.'},
 lab:{sim:'mov',cfg:{acc:true}},
 tasks:['Com v₀ = 0 e a = 2 m/s², veja o gráfico s × t virar uma parábola.','Coloque v₀ = 10 m/s e a = −2 m/s². Quando o carro para? O que acontece depois?','A inclinação do gráfico v × t é a aceleração. Confira mudando a.'],
 f:[{f:'a = '+frac('Δv','Δt'),s:[['a','aceleração','m/s²'],['Δv','variação da velocidade','m/s']]},{f:'v = v₀ + a·t      s = s₀ + v₀·t + '+frac('a·t²','2'),s:[['v₀','velocidade inicial','m/s'],['v','velocidade no instante t','m/s']]},{f:'v² = v₀² + 2·a·Δs',n:'Equação de Torricelli: útil quando o problema não fala em tempo.'}],
 ex:{q:'Um carro a 20 m/s freia com aceleração de −5 m/s². Quanto tempo leva para parar e que distância percorre?',s:['Parar significa v = 0. Pela função da velocidade: 0 = 20 − 5·t → t = 4 s.','Distância por Torricelli: 0² = 20² + 2·(−5)·Δs.','0 = 400 − 10·Δs → <b>Δs = 40 m</b>.','Confira: velocidade média (20 + 0)/2 = 10 m/s, durante 4 s → 40 m.']},
 probs:[
  ()=>{ const v0=R(0,10), dv=R(4,30,2), t=pick([2,4,5,8,10]); return NUM(`Uma moto vai de <b>${v0} m/s</b> a <b>${v0+dv} m/s</b> em <b>${t} s</b>. Qual é a aceleração média?`,dv/t,'m/s²',[`a = Δv/Δt = (${v0+dv} − ${v0})/${t}`,`a = ${F(dv/t)} m/s²`],[[(v0+dv)/t,'Use a <b>variação</b> da velocidade: final menos inicial.']]); },
  ()=>{ const a=pick([1,1.5,2,2.5,3,4]), t=R(2,10); return NUM(`Um carro parte do repouso com aceleração de <b>${F(a)} m/s²</b>. Que distância percorre em <b>${t} s</b>?`,a*t*t/2,'m',[`Do repouso: Δs = a·t²/2`,`Δs = ${F(a)} × ${t}² / 2 = ${F(a*t*t/2)} m`],[[a*t*t,'Faltou dividir por 2.'],[a*t,'Isso é a velocidade final (a·t), não a distância.']],'Partindo do repouso, Δs = a·t²/2.'); },
  ()=>{ const v0=R(0,15), a=pick([-3,-2,2,3,4]), t=R(2,6); const v=v0+a*t; if(v<0) return NUM(`Um carrinho tem velocidade inicial de <b>${v0+20} m/s</b> e aceleração de <b>${a} m/s²</b>. Qual é a velocidade após <b>${t} s</b>?`,v0+20+a*t,'m/s',[`v = v₀ + a·t = ${v0+20} + (${a})·${t}`,`v = ${v0+20+a*t} m/s`],[[v0+20-a*t,'Confira o sinal da aceleração.']]); return NUM(`Um carrinho tem velocidade inicial de <b>${v0} m/s</b> e aceleração de <b>${a} m/s²</b>. Qual é a velocidade após <b>${t} s</b>?`,v,'m/s',[`v = v₀ + a·t = ${v0} + (${a})·${t}`,`v = ${v} m/s`],[[v0-a*t,'Confira o sinal da aceleração.'],[a*t,'Faltou somar a velocidade inicial.']]); },
  ()=>{ const v0=pick([10,20,30]), a=pick([2,4,5]); return NUM(`Um carro a <b>${v0} m/s</b> freia com desaceleração constante de <b>${a} m/s²</b> até parar. Qual é a distância de frenagem?`,v0*v0/(2*a),'m',[`Torricelli com v = 0: 0 = ${v0}² − 2·${a}·Δs`,`Δs = ${v0*v0}/(2·${a}) = ${F(v0*v0/(2*a))} m`],[[v0*v0/a,'Faltou o fator 2: Δs = v₀²/(2a).'],[v0/a,'Isso é o tempo de frenagem, não a distância.']],'Sem tempo no enunciado: Torricelli.'); },
  POOL([['No MUV, o que permanece constante?',['a aceleração','a velocidade','a posição','a distância percorrida a cada segundo'],'É a definição do MUV: aceleração constante.'],['O gráfico v × t de um MUV é:',['uma reta inclinada','uma parábola','uma reta horizontal','uma hipérbole'],'v = v₀ + a·t é uma função do 1º grau: reta. A parábola aparece no gráfico s × t.'],['Um carro freando tem, em relação à velocidade, aceleração:',['de sentido oposto','de mesmo sentido','perpendicular','nula'],'Para diminuir a velocidade, a aceleração aponta contra o movimento.']])],
 traps:['Esquecer de dividir por 2 em a·t²/2.','Achar que aceleração negativa sempre significa frear: só freia quando a aceleração é oposta à velocidade.','Usar a velocidade final como se fosse a média.'],
 keep:['a = Δv/Δt.','v = v₀ + at; s = s₀ + v₀t + at²/2.','Sem tempo: v² = v₀² + 2aΔs.']},

{id:'queda',t:'Queda livre',min:14,
 idea:`<p>Solte uma pedra e uma folha de papel: a pedra chega antes. Mas amasse o papel numa bolinha e solte de novo: chegam quase juntas. A diferença vinha da <b>resistência do ar</b>, não do peso. Galileu percebeu isso: sem ar, <b>todos os corpos caem com a mesma aceleração</b>, a gravidade g.</p>
 <p>Na Terra, g ≈ 9,8 m/s². Neste curso usamos <b>g = 10 m/s²</b> para facilitar as contas, como fazem os vestibulares. A queda livre é um MUV que parte do repouso com a = g: a velocidade cresce 10 m/s a cada segundo.</p>
 <p>Um objeto lançado para cima sobe perdendo 10 m/s a cada segundo, para no ponto mais alto e volta. No ponto mais alto a velocidade é zero, mas a aceleração continua sendo g, para baixo.</p>`,
 pred:{q:'No vácuo, uma bola de 10 kg e outra de 0,1 kg são soltas juntas da mesma altura. Qual chega primeiro ao chão?',o:['chegam juntas','a de 10 kg','a de 0,1 kg','depende da altura'],a:0,why:'Sem ar, a aceleração é g para as duas. Em 1971, o astronauta David Scott soltou um martelo e uma pena na Lua, e eles caíram juntos.'},
 lab:{sim:'fall'},
 tasks:['Solte de 45 m na Terra. Quanto tempo leva? E na Lua?','Veja as marcas a cada 0,5 s: por que o espaço entre elas aumenta?','Qual altura faz a queda durar exatamente 2 s na Terra?'],
 f:[{f:'v = g·t      h = '+frac('g·t²','2')+'      v² = 2·g·h',s:[['g','aceleração da gravidade (use 10)','m/s²'],['h','altura de queda','m'],['t','tempo de queda','s']],n:'São as fórmulas do MUV com v₀ = 0 e a = g.'},{f:'h<sub class="up">máx</sub> = '+frac('v₀²','2g')+'      t<sub class="up">subida</sub> = '+frac('v₀','g'),n:'Para um lançamento vertical para cima com velocidade v₀.'}],
 ex:{q:'Uma pedra é solta do alto de um prédio e leva 3 s para chegar ao chão. Qual é a altura do prédio e a velocidade ao tocar o solo?',s:['h = g·t²/2 = 10 × 3² / 2 = 10 × 9 / 2.','<b>h = 45 m</b>.','v = g·t = 10 × 3 = <b>30 m/s</b> (108 km/h).']},
 probs:[
  ()=>{ const t=R(1,6), h=5*t*t; return NUM(`Uma pedra é solta de uma altura de <b>${h} m</b>. Quanto tempo leva para chegar ao chão? (g = 10 m/s²)`,t,'s',[`h = g·t²/2 → ${h} = 5·t²`,`t² = ${h/5} → t = ${t} s`],[[h/10,'A altura não cresce na mesma proporção do tempo: h = g·t²/2, então t = √(2h/g).'],[h/5,'Esse é t². Falta tirar a raiz quadrada.']],'Isole t em h = 5t².'); },
  ()=>{ const t=R(1,6), h=5*t*t; return NUM(`Um objeto cai de <b>${h} m</b> de altura. Com que velocidade chega ao chão? (g = 10 m/s²)`,10*t,'m/s',[`v² = 2·g·h = 2 × 10 × ${h} = ${20*h}`,`v = √${20*h} = ${10*t} m/s`],[[20*h,'Esse é v². Tire a raiz quadrada.'],[10*h,'v = g·t, não g·h.']]); },
  ()=>{ const t=R(1,5); return NUM(`Uma chave cai do alto de um prédio e leva <b>${t} s</b> para atingir a calçada. Qual é a altura? (g = 10 m/s²)`,5*t*t,'m',[`h = g·t²/2 = 10 × ${t}² / 2`,`h = ${5*t*t} m`],[[10*t*t,'Faltou dividir por 2.'],[10*t,'Isso é a velocidade final (g·t), não a altura.']]); },
  ()=>{ const v0=R(10,40,10); return NUM(`Uma bola é lançada verticalmente para cima a <b>${v0} m/s</b>. Qual é a altura máxima? (g = 10 m/s²)`,v0*v0/20,'m',[`No topo v = 0: 0 = ${v0}² − 2·10·h`,`h = ${v0*v0}/20 = ${v0*v0/20} m`],[[v0*v0/10,'Faltou o fator 2: h = v₀²/(2g).'],[v0/10,'Isso é o tempo de subida, não a altura.']]); },
  POOL([['No ponto mais alto de um lançamento vertical, a aceleração da bola é:',['g, para baixo','zero','g, para cima','maior que g'],'A velocidade é zero naquele instante, mas a gravidade continua puxando: se a aceleração fosse zero, a bola ficaria parada no ar.'],['Por que uma folha de papel aberta cai mais devagar que uma pedra?',['por causa da resistência do ar','porque é mais leve','porque a gravidade age menos em corpos leves','porque o papel flutua'],'Sem ar, cairiam juntas. A folha aberta sofre muita resistência do ar em relação ao seu peso.'],['Um corpo em queda livre, a cada segundo:',['ganha cerca de 10 m/s de velocidade','cai sempre 10 m','ganha 10 m/s² de aceleração','perde velocidade'],'a = g = 10 m/s²: a velocidade aumenta 10 m/s por segundo.']])],
 traps:['Achar que corpos mais pesados caem mais rápido (sem ar, não caem).','Dizer que a aceleração é zero no ponto mais alto.','Esquecer de tirar a raiz quadrada ao calcular tempo ou velocidade.'],
 keep:['Sem ar, tudo cai com a mesma aceleração g ≈ 10 m/s².','v = gt; h = gt²/2; v² = 2gh.','No topo de um lançamento: v = 0, mas a = g.']},

{id:'lancamento',t:'Lançamento oblíquo',min:16,
 idea:`<p>Uma bola chutada em ângulo faz uma trajetória curva. O segredo para entender é separar o movimento em dois, que acontecem <b>ao mesmo tempo e de forma independente</b>:</p>
 <ul><li><b>Horizontal</b>: nada acelera a bola para o lado (desprezando o ar), então vₓ = v₀·cos θ fica constante. É um MU.</li><li><b>Vertical</b>: a gravidade age; a bola começa com v<sub>y</sub> = v₀·sen θ, sobe, para e desce. É um MUV com a = −g.</li></ul>
 <p>O tempo de voo vem do movimento vertical; o alcance é vₓ vezes esse tempo. O maior alcance acontece em 45°, e ângulos que somam 90° (como 30° e 60°) têm o <b>mesmo alcance</b>.</p>`,
 pred:{q:'Uma bala é disparada na horizontal e, no mesmo instante, outra idêntica é solta da mesma altura. Qual toca o chão primeiro?',o:['as duas ao mesmo tempo','a disparada','a solta','depende da velocidade do disparo'],a:0,why:'O movimento vertical das duas é igual: ambas começam com v<sub>y</sub> = 0 e caem com g. A velocidade horizontal não interfere na queda.'},
 lab:{sim:'proj'},
 tasks:['Mantendo 20 m/s, compare os alcances em 30°, 45° e 60°.','Na Lua (g = 1,6), quanto aumenta o alcance?','Observe as setas: qual componente da velocidade muda e qual fica constante?'],
 f:[{f:'vₓ = v₀·cos θ      v<sub class="up">y</sub> = v₀·sen θ − g·t',s:[['θ','ângulo de lançamento com a horizontal','°']]},{f:'t<sub class="up">voo</sub> = '+frac('2·v₀·sen θ','g')+'      A = '+frac('v₀²·sen 2θ','g')+'      H = '+frac('(v₀·sen θ)²','2g'),s:[['A','alcance horizontal','m'],['H','altura máxima','m']]},{f:'Lançamento horizontal: t = √(2h/g), A = v·t',n:'Quem cai de uma altura h leva o mesmo tempo, com ou sem velocidade horizontal.'}],
 ex:{q:'Uma bola rola para fora de uma mesa de 1,25 m de altura com velocidade horizontal de 2 m/s. A que distância da mesa ela toca o chão?',s:['Tempo de queda (vertical): 1,25 = 10·t²/2 → t² = 0,25 → t = 0,5 s.','Horizontal é MU: A = v·t = 2 × 0,5.','<b>A = 1 m</b>.']},
 probs:[
  ()=>{ const t=R(1,4), h=5*t*t, v=R(5,30,5); return NUM(`Um pacote é largado de um avião que voa na horizontal a <b>${v} m/s</b>, a <b>${h} m</b> de altura. Que distância horizontal ele percorre até o chão? (g = 10, sem ar)`,v*t,'m',[`Tempo de queda: ${h} = 5t² → t = ${t} s`,`Horizontal: A = v·t = ${v} × ${t} = ${v*t} m`],[[v*h/10,'Calcule primeiro o tempo de queda por h = gt²/2.'],[v*t*t,'O alcance é v·t, com t = '+t+' s.']],'Primeiro o tempo de queda, depois a distância horizontal.'); },
  ()=>{ const v0=pick([10,20,30]), th=pick([15,30,45,60,75]); const A=v0*v0*Math.sin(2*th*Math.PI/180)/10; return NUM(`Um projétil é lançado a <b>${v0} m/s</b> com <b>${th}°</b> em relação ao chão. Qual é o alcance? (g = 10; sen 30° = 0,5; sen 60° ≈ 0,87; sen 90° = 1)`,A,'m',[`A = v₀²·sen(2θ)/g = ${v0}² × sen ${2*th}° / 10`,`A = ${F(A)} m`],[[v0*v0*Math.sin(th*Math.PI/180)/10,'O alcance usa sen(2θ), o seno do <b>dobro</b> do ângulo.']],'Use sen(2θ). Se 2θ passar de 90°, lembre que sen 150° = sen 30°.'); },
  ()=>{ const v0=pick([10,20,30,40]), th=pick([30,90]); const vy=v0*Math.sin(th*Math.PI/180); return NUM(`Uma bola é chutada a <b>${v0} m/s</b> formando <b>${th}°</b> com o chão. Quanto tempo fica no ar? (g = 10; sen 30° = 0,5)`,2*vy/10,'s',[`v<sub>y</sub> inicial = ${v0} × sen ${th}° = ${F(vy)} m/s`,`Sobe até v<sub>y</sub> = 0 em ${F(vy/10)} s e leva o mesmo tempo para descer.`,`t = ${F(2*vy/10)} s`],[[vy/10,'Esse é só o tempo de subida. O voo inclui a descida.']]); },
  POOL([['No ponto mais alto de um lançamento oblíquo, a velocidade da bola é:',['só a componente horizontal','zero','só a componente vertical','máxima'],'A componente vertical zera no topo, mas a horizontal continua a mesma.'],['Qual ângulo dá o maior alcance (sem ar, mesmo nível)?',['45°','30°','60°','90°'],'sen(2θ) é máximo quando 2θ = 90°, ou seja, θ = 45°.'],['Uma bola lançada a 30° e outra a 60°, com a mesma velocidade, terão:',['o mesmo alcance','a mesma altura máxima','o mesmo tempo de voo','alcances que diferem por 2 vezes'],'sen 60° = sen 120°: ângulos complementares dão o mesmo alcance. A de 60° sobe mais e demora mais.']])],
 traps:['Achar que a velocidade é zero no ponto mais alto (só a vertical zera).','Usar sen θ em vez de sen 2θ no alcance.','Achar que um objeto lançado na horizontal cai mais devagar que um solto.'],
 keep:['Horizontal: MU. Vertical: MUV com −g. Os dois são independentes.','A = v₀²·sen 2θ/g; máximo em 45°.','O tempo de queda só depende da altura.']},

{id:'mcu',t:'Movimento circular',min:15,
 idea:`<p>Num carrossel, você pode girar sempre com a mesma rapidez, mas a direção do seu movimento muda o tempo todo. Como velocidade é um vetor, mudar a direção já é mudar a velocidade. Por isso, <b>todo movimento circular tem aceleração</b>, mesmo quando o módulo da velocidade é constante (MCU).</p>
 <p>Essa aceleração aponta para o <b>centro</b> do círculo: é a <b>aceleração centrípeta</b>, a<sub>c</sub> = v²/R.</p>
 <p>O <b>período</b> T é o tempo de uma volta; a <b>frequência</b> f = 1/T é o número de voltas por segundo (hertz, Hz). Em uma volta o corpo percorre a circunferência 2πR, então v = 2πR/T. A velocidade angular, ω = 2π/T, diz quantos radianos o corpo gira por segundo.</p>`,
 pred:{q:'Uma bola gira presa a uma corda com velocidade de módulo constante. Ela tem aceleração?',o:['sim, apontando para o centro','não, porque a velocidade é constante','sim, apontando para fora','sim, no sentido do movimento'],a:0,why:'O módulo não muda, mas a direção muda o tempo todo. Quem faz a direção mudar é a aceleração centrípeta, voltada para o centro.'},
 lab:{sim:'mcu',cfg:{force:false}},
 tasks:['Diminua o período: o que acontece com a velocidade e com a aceleração?','Dobre o raio mantendo o período. A velocidade dobra?','Observe: a seta da velocidade é sempre perpendicular à da aceleração.'],
 f:[{f:'f = '+frac('1','T')+'      v = '+frac('2πR','T')+'      ω = '+frac('2π','T'),s:[['T','período (tempo de uma volta)','s'],['f','frequência (voltas por segundo)','Hz'],['R','raio','m'],['ω','velocidade angular','rad/s']]},{f:'a<sub class="up">c</sub> = '+frac('v²','R')+' = ω²·R',n:'Em polias ligadas por correia, a velocidade na borda (v) é a mesma; em polias no mesmo eixo, a frequência é a mesma.'}],
 ex:{q:'Uma roda-gigante de raio 10 m dá uma volta a cada 60 s. Qual é a velocidade de uma cadeira? (π ≈ 3,14)',s:['Em uma volta, a cadeira percorre 2πR = 2 × 3,14 × 10 = 62,8 m.','Isso leva T = 60 s.','v = 62,8/60 ≈ <b>1,05 m/s</b>.']},
 probs:[
  ()=>{ const T=pick([.2,.25,.5,2,4,5,10]); return NUM(`Um ventilador dá uma volta a cada <b>${F(T)} s</b>. Qual é a frequência?`,1/T,'Hz',[`f = 1/T = 1/${F(T)}`,`f = ${F(1/T)} Hz`],[[T,'Esse é o período. A frequência é o inverso: 1/T.']]); },
  ()=>{ const R0=pick([.5,1,2,5,10]), T=pick([1,2,4,5,10]); return NUM(`Um ponto gira num círculo de raio <b>${F(R0)} m</b> com período de <b>${T} s</b>. Qual é a velocidade? (π ≈ 3,14)`,2*3.14*R0/T,'m/s',[`v = 2πR/T = 2 × 3,14 × ${F(R0)} / ${T}`,`v = ${F(2*3.14*R0/T)} m/s`],[[3.14*R0/T,'A circunferência é 2πR, não πR.'],[2*3.14*R0*T,'Divida pelo período, não multiplique.']]); },
  ()=>{ const v=R(2,20,2), r=pick([1,2,4,5,8,10]); return NUM(`Um carro faz uma curva de raio <b>${r} m</b> a <b>${v} m/s</b>. Qual é a aceleração centrípeta?`,v*v/r,'m/s²',[`a<sub>c</sub> = v²/R = ${v}²/${r}`,`a<sub>c</sub> = ${F(v*v/r)} m/s²`],[[v/r,'Faltou elevar a velocidade ao quadrado.'],[v*v*r,'Divida pelo raio.']]); },
  ()=>{ const rpm=pick([60,120,300,600,900,1200,3000]); return NUM(`O motor de uma máquina gira a <b>${rpm} rpm</b> (rotações por minuto). Qual é a frequência em hertz?`,rpm/60,'Hz',[`1 minuto = 60 s`,`f = ${rpm}/60 = ${F(rpm/60)} Hz`],[[rpm*60,'Divida por 60: são rotações por minuto, e Hz é por segundo.']]); },
  POOL([['Duas polias estão ligadas por uma correia. O que é igual nas duas?',['a velocidade de um ponto da borda','a frequência','o período','a velocidade angular'],'A correia não escorrega: a borda das duas anda junto com ela. A polia menor gira mais vezes.'],['No MCU, a aceleração centrípeta aponta:',['para o centro do círculo','para fora do círculo','no sentido do movimento','contra o movimento'],'Centrípeta quer dizer "que busca o centro".'],['Se a velocidade num círculo dobra (mesmo raio), a aceleração centrípeta:',['quadruplica','dobra','fica igual','cai pela metade'],'a<sub>c</sub> = v²/R: com v dobrado, v² fica 4 vezes maior.']])],
 traps:['Achar que velocidade constante em módulo significa aceleração zero.','Confundir período (segundos por volta) com frequência (voltas por segundo).','Usar πR em vez de 2πR para o comprimento da volta.'],
 keep:['Movimento circular sempre tem aceleração centrípeta: a<sub>c</sub> = v²/R.','v = 2πR/T; f = 1/T.','Correia: mesma v. Mesmo eixo: mesma f.']}]);

mod('din','Dinâmica','forças e as três leis de Newton',[
{id:'newton',t:'Inércia e a segunda lei de Newton',min:16,
 idea:`<p>Por que um ônibus que freia de repente joga os passageiros para a frente? Porque os corpos tendem a <b>manter o estado de movimento</b>: quem estava a 50 km/h "quer" continuar a 50 km/h. Essa tendência é a <b>inércia</b>, e é a <b>1ª lei de Newton</b>: sem força resultante, um corpo parado continua parado, e um corpo em movimento continua em linha reta com velocidade constante.</p>
 <p>A <b>2ª lei</b> diz o que acontece quando existe força resultante: ela produz aceleração, na mesma direção e sentido, e F<sub>R</sub> = m·a. Quanto maior a massa, mais difícil acelerar: a massa é a medida da inércia.</p>
 <p>A unidade de força é o <b>newton</b> (N): 1 N acelera 1 kg a 1 m/s². Atenção: na fórmula entra a força <b>resultante</b>, a soma vetorial de todas as forças.</p>`,
 pred:{q:'Um disco é empurrado e depois desliza num gelo perfeitamente liso, sem atrito nem ar. Depois do empurrão, ele:',o:['continua com a mesma velocidade, em linha reta','vai parando aos poucos','acelera','para logo depois do empurrão'],a:0,why:'Sem força resultante, não há aceleração. Na vida real as coisas param por causa do atrito e do ar; sem eles, o disco seguiria indefinidamente.'},
 lab:{sim:'block',cfg:{fric:false}},
 tasks:['Com 5 kg, dobre a força de 20 N para 40 N. O que acontece com a aceleração?','Mantenha 20 N e dobre a massa. E agora?','Zere a força com o bloco em movimento: ele para?'],
 f:[{f:'F<sub class="up">R</sub> = m·a',s:[['F<sub>R</sub>','força resultante (soma vetorial de todas as forças)','N'],['m','massa','kg'],['a','aceleração','m/s²']],n:'1 N = 1 kg·m/s².'}],
 ex:{q:'Duas pessoas empurram um carrinho de 50 kg: uma com 120 N para a direita e outra com 20 N para a esquerda. Qual é a aceleração?',s:['Resultante: 120 − 20 = 100 N para a direita.','a = F<sub>R</sub>/m = 100/50.','<b>a = 2 m/s²</b>, para a direita.']},
 probs:[
  ()=>{ const m=R(2,20), a=R(1,6); return NUM(`Uma força resultante de <b>${m*a} N</b> age numa caixa de <b>${m} kg</b>. Qual é a aceleração?`,a,'m/s²',[`a = F/m = ${m*a}/${m}`,`a = ${a} m/s²`],[[m*a*m,'Divida a força pela massa.'],[m/(m*a),'É força dividida por massa, não o contrário.']]); },
  ()=>{ const m=R(500,2000,100), a=pick([1,1.5,2,2.5,3]); return NUM(`Qual força resultante é necessária para acelerar um carro de <b>${m} kg</b> a <b>${F(a)} m/s²</b>?`,m*a,'N',[`F = m·a = ${m} × ${F(a)}`,`F = ${F(m*a)} N`],[[m/a,'Multiplique massa por aceleração.']]); },
  ()=>{ const m=R(2,10), F1=R(20,60,5), F2=R(5,F1-5,5); return NUM(`Um bloco de <b>${m} kg</b> é puxado por <b>${F1} N</b> para a direita e <b>${F2} N</b> para a esquerda (sem atrito). Qual é a aceleração?`,(F1-F2)/m,'m/s²',[`F<sub>R</sub> = ${F1} − ${F2} = ${F1-F2} N`,`a = ${F1-F2}/${m} = ${F((F1-F2)/m)} m/s²`],[[(F1+F2)/m,'As forças são opostas: subtraia para achar a resultante.'],[F1/m,'Use a força <b>resultante</b>, não só a maior.']]); },
  ()=>{ const m=R(2,10), Fo=R(10,50,10), t=R(2,6); return NUM(`Um carrinho de <b>${m} kg</b>, parado, recebe uma força resultante constante de <b>${Fo} N</b> durante <b>${t} s</b>. Qual é a velocidade final?`,Fo*t/m,'m/s',[`a = F/m = ${Fo}/${m} = ${F(Fo/m)} m/s²`,`v = a·t = ${F(Fo/m)} × ${t} = ${F(Fo*t/m)} m/s`],[[Fo/m,'Essa é a aceleração. Multiplique pelo tempo.']]); },
  POOL([['Por que usar cinto de segurança numa freada brusca?',['por inércia, o corpo tende a continuar em movimento','o carro empurra o passageiro para a frente','a freada cria uma força para a frente no passageiro','o cinto aumenta o atrito com o banco'],'O carro para, mas o corpo tende a seguir a 50 km/h. O cinto aplica a força que faz você parar junto.'],['Um avião voa em linha reta com velocidade constante. A força resultante sobre ele é:',['zero','igual ao peso','igual à força dos motores','para a frente'],'Velocidade constante e em linha reta = aceleração zero = resultante zero. Motor e resistência do ar se equilibram, assim como peso e sustentação.'],['Um corpo se move para a direita e está desacelerando. A força resultante aponta:',['para a esquerda','para a direita','para cima','não existe força'],'A aceleração (e a resultante) é oposta ao movimento quando o corpo freia.']])],
 traps:['Achar que é preciso força para manter um corpo em movimento (sem atrito, não é).','Usar só uma das forças em vez da resultante.','Achar que a força aponta sempre para onde o corpo se move: ela aponta para onde ele acelera.'],
 keep:['1ª lei: sem resultante, velocidade constante (ou repouso).','2ª lei: F<sub>R</sub> = m·a.','Força resultante é a soma vetorial de todas as forças.']},

{id:'forcas',t:'Ação e reação, peso e normal',min:16,
 idea:`<p>Quando você empurra uma parede, ela empurra você de volta. A <b>3ª lei de Newton</b> diz que as forças aparecem sempre aos pares: se A faz uma força em B, B faz em A uma força de <b>mesmo módulo, mesma direção e sentido oposto</b>. Como agem em corpos diferentes, essas forças <b>não se anulam</b>.</p>
 <p>O <b>peso</b> é a força com que a Terra puxa um corpo: P = m·g. Massa (kg) é a quantidade de matéria e é a mesma em qualquer lugar; peso (N) depende da gravidade. Um astronauta de 70 kg pesa 700 N na Terra e cerca de 112 N na Lua.</p>
 <p>A <b>normal</b> é a força que uma superfície faz num corpo apoiado, perpendicular a ela. Ela não é a reação do peso (a reação do peso é o corpo puxando a Terra). Uma balança mede a normal: num elevador acelerando para cima, a normal fica maior que o peso, e você "pesa" mais.</p>`,
 pred:{q:'Uma pessoa de 60 kg está sobre uma balança num elevador que acelera para cima. A balança marca:',o:['mais que 60 kg','exatamente 60 kg','menos que 60 kg','zero'],a:0,why:'Para acelerar a pessoa para cima, a balança precisa empurrar com mais força que o peso: N = m(g + a). A balança mostra essa normal.'},
 lab:{sim:'elev'},
 tasks:['Com a = 0, compare N e P.','Coloque a = −10 m/s². O que a balança marca? Por que isso é "flutuar"?','Qual aceleração faz a balança marcar 72 kg para uma pessoa de 60 kg?'],
 f:[{f:'P = m·g',s:[['P','peso','N'],['g','gravidade (10 na Terra, 1,6 na Lua)','m/s²']]},{f:'N − P = m·a  ⇒  N = m·(g + a)',s:[['N','normal (o que a balança mede)','N'],['a','aceleração do elevador (+ para cima)','m/s²']],n:'Ação e reação: mesmo módulo, sentidos opostos, em corpos diferentes.'}],
 ex:{q:'Uma pessoa de 50 kg está num elevador que sobe freando com aceleração de 2 m/s² para baixo. Quanto a balança marca?',s:['Aceleração para baixo: a = −2 m/s².','N = m(g + a) = 50 × (10 − 2) = 400 N.','A balança marca 400/10 = <b>40 kg</b>.']},
 probs:[
  ()=>{ const m=R(40,100,5), [g,nm]=pick([[1.6,'na Lua'],[3.7,'em Marte'],[10,'na Terra'],[25,'em Júpiter']]); return NUM(`Qual é o peso de um astronauta de <b>${m} kg</b> ${nm} (g = ${F(g)} m/s²)?`,m*g,'N',[`P = m·g = ${m} × ${F(g)}`,`P = ${F(m*g)} N`],[[m,'Isso é a massa, em kg. Peso é força: P = m·g, em newtons.']]); },
  ()=>{ const m=R(50,90,10), a=pick([-4,-2,1,2,3,4]); return NUM(`Uma pessoa de <b>${m} kg</b> está numa balança dentro de um elevador com aceleração de <b>${Math.abs(a)} m/s² para ${a>0?'cima':'baixo'}</b>. Qual é a força normal? (g = 10)`,m*(10+a),'N',[`N − P = m·a, com a = ${a} m/s²`,`N = ${m} × (10 ${a>0?'+':'−'} ${Math.abs(a)}) = ${m*(10+a)} N`],[[m*10,'Esse é o peso. Com aceleração, a normal muda.'],[m*(10-a),'Confira o sentido: aceleração para cima aumenta a normal.']]); },
  ()=>{ const m=R(50,90,10), a=pick([-5,-2,2,3,5]); return NUM(`No elevador acelerando a <b>${Math.abs(a)} m/s² para ${a>0?'cima':'baixo'}</b>, quanto a balança "marca" (em kg) para uma pessoa de <b>${m} kg</b>?`,m*(10+a)/10,'kg',[`N = m(g + a) = ${m*(10+a)} N`,`A balança divide por g: ${m*(10+a)}/10 = ${F(m*(10+a)/10)} kg`],[[m,'A balança só marca a massa real quando o elevador não acelera.']]); },
  POOL([['A reação ao peso de um livro sobre a mesa é:',['a força com que o livro puxa a Terra para cima','a normal que a mesa faz no livro','o peso da mesa','a força do livro sobre a mesa'],'Peso: a Terra puxa o livro. Reação: o livro puxa a Terra. A normal é outra interação (mesa–livro).'],['Um cavalo puxa uma carroça e a carroça puxa o cavalo com força igual e oposta. Então por que eles andam?',['essas forças estão em corpos diferentes; o cavalo anda porque o chão o empurra','as forças se anulam, mas o cavalo é mais forte','a 3ª lei não vale para seres vivos','a carroça puxa com força menor'],'Para saber se o cavalo acelera, some só as forças <b>sobre o cavalo</b>: o chão o empurra para a frente mais do que a carroça o puxa para trás.'],['Um astronauta vai da Terra para a Lua. O que acontece com a massa e o peso dele?',['a massa não muda; o peso diminui','os dois diminuem','a massa diminui; o peso não muda','os dois ficam iguais'],'Massa é a quantidade de matéria. Peso depende de g, que é menor na Lua.']])],
 traps:['Achar que peso e normal formam um par de ação e reação.','Achar que ação e reação se anulam (agem em corpos diferentes).','Confundir massa (kg) com peso (N).'],
 keep:['Ação e reação: iguais, opostas, em corpos diferentes.','P = m·g; massa não depende do lugar.','Balança mede a normal: N = m(g + a).']},

{id:'atrito',t:'Força de atrito',min:15,
 idea:`<p>Empurre um armário pesado. No começo, você faz força e ele não sai do lugar: o <b>atrito estático</b> cresce junto com a sua força e a equilibra. Ele tem um limite, μₑ·N. Passou desse limite, o armário começa a deslizar.</p>
 <p>Depois que desliza, age o <b>atrito cinético</b>, de valor fixo μ<sub>c</sub>·N, geralmente menor que o estático máximo. Por isso é mais difícil tirar algo do lugar do que mantê-lo andando.</p>
 <p>O atrito depende das superfícies (o coeficiente μ, sem unidade) e de quanto elas são apertadas uma contra a outra (a normal N). Numa superfície horizontal, N = m·g. O atrito sempre se opõe ao deslizamento entre as superfícies.</p>`,
 pred:{q:'Você empurra um armário parado com uma força pequena e ele não se mexe. A força de atrito nesse momento é:',o:['igual à sua força','maior que a sua força','zero','igual ao peso do armário'],a:0,why:'Se o armário continua parado, a resultante é zero. O atrito estático se ajusta: vale exatamente o que é preciso para equilibrar sua força, até o limite μₑ·N.'},
 lab:{sim:'block',cfg:{fric:true}},
 tasks:['Com 5 kg e μₑ = 0,5, aumente a força devagar. Em que valor o bloco começa a andar?','Depois que ele anda, o atrito muda de valor?','Coloque μ<sub>c</sub> = μₑ. O que muda?'],
 f:[{f:'Fat<sub class="up">máx</sub> = μₑ·N      Fat<sub class="up">c</sub> = μ<sub class="up">c</sub>·N',s:[['μₑ','coeficiente de atrito estático',''],['μ<sub>c</sub>','coeficiente de atrito cinético',''],['N','força normal (= m·g no plano horizontal)','N']],n:'Parado, o atrito estático vale o que for preciso até o máximo. Deslizando, vale μ<sub>c</sub>·N.'}],
 ex:{q:'Uma caixa de 20 kg está no chão (μₑ = 0,4; μ<sub>c</sub> = 0,3). Você empurra com 100 N. Ela se move? Com que aceleração?',s:['N = m·g = 200 N. Atrito estático máximo: 0,4 × 200 = 80 N.','100 N > 80 N: a caixa começa a deslizar.','Deslizando, o atrito é cinético: 0,3 × 200 = 60 N.','a = (100 − 60)/20 = <b>2 m/s²</b>.']},
 probs:[
  ()=>{ const m=R(5,50,5), u=pick([.2,.3,.4,.5,.6]); return NUM(`Uma caixa de <b>${m} kg</b> está num piso com μₑ = <b>${F(u)}</b>. Qual é a força mínima para começar a movê-la? (g = 10)`,u*m*10,'N',[`N = m·g = ${m*10} N`,`Fat<sub>máx</sub> = μₑ·N = ${F(u)} × ${m*10} = ${F(u*m*10)} N`],[[u*m,'Use a normal (m·g), não a massa.']]); },
  ()=>{ const m=R(5,20), uc=pick([.2,.3]), Fo=R(Math.ceil(.6*m*10/5)*5+5,Math.ceil(.6*m*10/5)*5+40,5); return NUM(`Um bloco de <b>${m} kg</b> é puxado com <b>${Fo} N</b> e desliza (μ<sub>c</sub> = ${F(uc)}). Qual é a aceleração? (g = 10)`,(Fo-uc*m*10)/m,'m/s²',[`Atrito cinético: ${F(uc)} × ${m*10} = ${F(uc*m*10)} N`,`a = (${Fo} − ${F(uc*m*10)})/${m} = ${F((Fo-uc*m*10)/m)} m/s²`],[[Fo/m,'Faltou descontar o atrito.']]); },
  ()=>{ const m=R(10,40,5), u=.5, Fo=R(10,Math.floor(u*m*10/5)*5-5,5); return NUM(`Você empurra um móvel de <b>${m} kg</b> (μₑ = 0,5) com <b>${Fo} N</b>, e ele não se move. Qual é a força de atrito? (g = 10)`,Fo,'N',[`Atrito máximo: 0,5 × ${m*10} = ${u*m*10} N`,`Sua força (${Fo} N) é menor que o máximo: o móvel fica parado.`,`Parado, o atrito equilibra sua força: ${Fo} N.`],[[u*m*10,'Esse é o atrito <b>máximo</b>. Enquanto não desliza, o atrito vale só o necessário.']],'Se o móvel está parado, qual deve ser a resultante?'); },
  ()=>{ const v=pick([10,20,30]), u=pick([.5,.8]); return NUM(`Um carro a <b>${v} m/s</b> trava as rodas e derrapa até parar (μ<sub>c</sub> = ${F(u)}). Qual é a distância de frenagem? (g = 10)`,v*v/(2*u*10),'m',[`A única força horizontal é o atrito: a = μ·g = ${F(u*10)} m/s²`,`Torricelli: d = v²/(2a) = ${v*v}/${F(2*u*10)} = ${F(v*v/(2*u*10))} m`],[[v*v/(u*10),'Faltou o fator 2 de Torricelli.']]); },
  POOL([['Por que é mais difícil começar a empurrar um armário do que mantê-lo andando?',['o atrito estático máximo é maior que o cinético','o armário fica mais leve andando','a normal diminui quando ele anda','o atrito some quando há movimento'],'μₑ costuma ser maior que μ<sub>c</sub>.'],['O atrito entre o pneu e o chão, quando um carro acelera, aponta:',['para a frente','para trás','para cima','não existe'],'O pneu empurra o chão para trás; o chão empurra o pneu para a frente. Sem esse atrito (no gelo), o carro patina.']])],
 traps:['Usar μₑ·N como valor do atrito quando o corpo está parado com uma força menor que o máximo.','Usar a massa no lugar da normal.','Achar que o atrito sempre atrapalha: é ele que permite andar e frear.'],
 keep:['Parado: atrito estático vale o necessário, até μₑN.','Deslizando: atrito cinético μ<sub>c</sub>N.','No plano horizontal, N = m·g.']},

{id:'plano',t:'Plano inclinado',min:15,
 idea:`<p>Numa rampa, o peso continua vertical, mas o que interessa é o que ele faz <b>ao longo</b> da rampa e <b>contra</b> ela. Decompomos o peso em duas partes: P·sen θ, paralela à rampa (puxa o corpo ladeira abaixo), e P·cos θ, perpendicular (aperta o corpo contra a rampa e é equilibrada pela normal).</p>
 <p>Sem atrito, a aceleração ao descer é a = g·sen θ, e <b>não depende da massa</b>. Com atrito, subtraia μ·N: a = g·(sen θ − μ·cos θ). O corpo só começa a escorregar quando P·sen θ supera o atrito máximo, o que acontece quando tg θ > μₑ.</p>`,
 pred:{q:'Dois blocos, de 1 kg e de 10 kg, descem uma rampa lisa (sem atrito) com a mesma inclinação. Qual tem maior aceleração?',o:['têm a mesma aceleração','o de 10 kg','o de 1 kg','depende da altura da rampa'],a:0,why:'O bloco mais pesado é puxado com mais força, mas também tem mais massa para acelerar: a = m·g·sen θ / m = g·sen θ.'},
 lab:{sim:'incl'},
 tasks:['Com μ = 0,3, aumente o ângulo até o bloco começar a escorregar. Compare com o "ângulo em que começa a escorregar".','Com atrito, mude a massa: a aceleração muda?','Em 0° e em 90°, quanto valem P·sen θ e P·cos θ?'],
 f:[{f:'Pₓ = P·sen θ      P<sub class="up">y</sub> = N = P·cos θ',s:[['θ','inclinação da rampa','°'],['Pₓ','componente do peso ao longo da rampa','N'],['P<sub>y</sub>','componente perpendicular, equilibrada pela normal','N']]},{f:'a = g·(sen θ − μ·cos θ)',n:'Sem atrito (μ = 0): a = g·sen θ. Valores úteis: sen 30° = 0,5; sen 37° ≈ 0,6 e cos 37° ≈ 0,8; sen 45° ≈ 0,71.'}],
 ex:{q:'Um bloco de 2 kg desce uma rampa de 37° com μ<sub>c</sub> = 0,25. Qual é a aceleração? (sen 37° = 0,6; cos 37° = 0,8)',s:['Componente do peso ao longo da rampa: 20 × 0,6 = 12 N.','Normal: 20 × 0,8 = 16 N. Atrito: 0,25 × 16 = 4 N.','a = (12 − 4)/2 = <b>4 m/s²</b>. Pela fórmula: 10 × (0,6 − 0,25 × 0,8) = 4 m/s².']},
 probs:[
  ()=>{ const [th,s]=pick([[30,.5],[37,.6],[53,.8],[90,1]]); return NUM(`Um carrinho desce uma rampa lisa de <b>${th}°</b> (sen ${th}° = ${F(s)}). Qual é a aceleração? (g = 10)`,10*s,'m/s²',[`Sem atrito: a = g·sen θ = 10 × ${F(s)}`,`a = ${F(10*s)} m/s²`],[[10,'Na rampa, só a componente g·sen θ acelera o carrinho.']]); },
  ()=>{ const m=R(2,10), [th,c]=pick([[37,.8],[53,.6],[60,.5]]); return NUM(`Um bloco de <b>${m} kg</b> está numa rampa de <b>${th}°</b> (cos ${th}° = ${F(c)}). Qual é a força normal? (g = 10)`,m*10*c,'N',[`N = P·cos θ = ${m*10} × ${F(c)}`,`N = ${F(m*10*c)} N`],[[m*10,'No plano inclinado, a normal é menor que o peso: N = P·cos θ.']]); },
  ()=>{ const u=pick([.25,.5]); return NUM(`Um bloco desce uma rampa de 37° com coeficiente de atrito cinético <b>${F(u)}</b>. Qual é a aceleração? (g = 10; sen 37° = 0,6; cos 37° = 0,8)`,10*(.6-u*.8),'m/s²',[`a = g·(sen θ − μ·cos θ) = 10 × (0,6 − ${F(u)} × 0,8)`,`a = ${F(10*(.6-u*.8))} m/s²`],[[6,'Faltou descontar o atrito.'],[10*(.6-u),'O atrito usa a normal, que é P·cos θ.']]); },
  POOL([['Um bloco está parado numa rampa com atrito. A força de atrito sobre ele:',['aponta rampa acima e vale P·sen θ','aponta rampa abaixo','vale μ·N obrigatoriamente','é zero'],'Parado, o atrito estático equilibra a componente P·sen θ, e aponta contra a tendência de escorregar.'],['Aumentando a inclinação de uma rampa, a normal:',['diminui','aumenta','não muda','fica igual ao peso'],'N = P·cos θ, e o cosseno diminui quando o ângulo aumenta.']])],
 traps:['Achar que a normal é igual ao peso numa rampa.','Trocar sen e cos: a componente ao longo da rampa usa o seno.','Achar que blocos mais pesados descem mais rápido numa rampa sem atrito.'],
 keep:['Ao longo da rampa: P·sen θ. Contra a rampa: P·cos θ = N.','Sem atrito: a = g·sen θ.','Com atrito: a = g(sen θ − μ cos θ).']},

{id:'centripeta',t:'Força centrípeta',min:14,
 idea:`<p>Se todo movimento circular tem aceleração para o centro, pela 2ª lei de Newton alguma força precisa apontar para o centro: a <b>força centrípeta</b>, F<sub>c</sub> = m·v²/R.</p>
 <p>Ela não é um tipo novo de força. É o <b>papel</b> que alguma força real faz: a tração da corda (pedra girando), o atrito dos pneus (carro na curva), a gravidade (Lua em volta da Terra), a normal (roupa na centrífuga da máquina de lavar).</p>
 <p>Se essa força some, o corpo segue em linha reta, tangente ao círculo, por inércia. A sensação de ser "jogado para fora" numa curva é a inércia do seu corpo querendo seguir reto enquanto o carro vira.</p>`,
 pred:{q:'Você gira uma pedra presa a um barbante e o barbante arrebenta. A pedra sai:',o:['em linha reta, tangente ao círculo','para fora, na direção do raio','em espiral','continua girando por um tempo'],a:0,why:'Sem a força centrípeta, não há nada que mude a direção: pela inércia, a pedra segue na direção que tinha no instante da ruptura.'},
 lab:{sim:'mcu',cfg:{force:true}},
 tasks:['Aumente a massa: a força necessária aumenta na mesma proporção?','Diminua o período pela metade. A força fica quantas vezes maior?','Corte a corda em pontos diferentes e observe a direção da saída.'],
 f:[{f:'F<sub class="up">c</sub> = m·'+frac('v²','R'),s:[['F<sub>c</sub>','força resultante para o centro','N'],['v','velocidade','m/s'],['R','raio da curva','m']],n:'Numa curva plana, quem faz esse papel é o atrito: a maior velocidade possível sem derrapar é v = √(μ·g·R).'}],
 ex:{q:'Um carro de 1000 kg faz uma curva de raio 50 m a 10 m/s. Qual atrito lateral os pneus precisam fazer?',s:['F<sub>c</sub> = m·v²/R = 1000 × 10²/50.','F<sub>c</sub> = 1000 × 100/50 = <b>2000 N</b>.','Essa força vem do atrito entre os pneus e o asfalto.']},
 probs:[
  ()=>{ const m=pick([.2,.5,1,2]), v=R(2,10), r=pick([.5,1,2]); return NUM(`Uma bola de <b>${F(m)} kg</b> gira presa a uma corda de <b>${F(r)} m</b> a <b>${v} m/s</b> (numa mesa sem atrito). Qual é a tração na corda?`,m*v*v/r,'N',[`T = m·v²/R = ${F(m)} × ${v}²/${F(r)}`,`T = ${F(m*v*v/r)} N`],[[m*v/r,'Faltou elevar a velocidade ao quadrado.'],[m*v*v*r,'Divida pelo raio.']]); },
  ()=>{ const m=R(800,1500,100), v=pick([10,15,20]), r=pick([50,100,200]); return NUM(`Um carro de <b>${m} kg</b> faz uma curva plana de raio <b>${r} m</b> a <b>${v} m/s</b>. Qual força de atrito lateral é necessária?`,m*v*v/r,'N',[`F<sub>c</sub> = m·v²/R = ${m} × ${v*v}/${r}`,`F<sub>c</sub> = ${F(m*v*v/r)} N`],[[m*v/r,'Faltou elevar a velocidade ao quadrado.']]); },
  ()=>{ const u=pick([.4,.5,.8]), r=pick([20,50,80,125]); return NUM(`Qual é a maior velocidade com que um carro pode fazer uma curva plana de raio <b>${r} m</b> sem derrapar, se μ = <b>${F(u)}</b>? (g = 10)`,Math.sqrt(u*10*r),'m/s',[`O atrito máximo (μ·m·g) faz o papel de força centrípeta: μ·m·g = m·v²/R`,`v = √(μ·g·R) = √(${F(u)} × 10 × ${r}) = ${F(Math.sqrt(u*10*r))} m/s`],[[u*10*r,'Esse é v². Tire a raiz quadrada.']],'Iguale μ·m·g a m·v²/R: a massa se cancela.'); },
  POOL([['O que faz o papel de força centrípeta na Lua girando em volta da Terra?',['a atração gravitacional da Terra','a força centrífuga','a inércia da Lua','nenhuma força: ela gira sozinha'],'É a gravidade que curva a trajetória da Lua.'],['Numa curva, o passageiro sente-se jogado para fora porque:',['o corpo dele tende a seguir em linha reta (inércia)','existe uma força empurrando para fora','o banco o empurra para fora','a força centrípeta aponta para fora'],'Quem acelera para o centro é o carro; o corpo do passageiro "fica para trás" até o banco ou a porta empurrá-lo junto.']])],
 traps:['Tratar a força centrípeta como uma força a mais no diagrama: ela é a resultante das forças reais.','Achar que um corpo solto de uma trajetória circular sai na direção do raio.','Esquecer de elevar v ao quadrado.'],
 keep:['F<sub>c</sub> = m·v²/R, apontando para o centro.','É um papel feito por forças reais (tração, atrito, gravidade, normal).','Sem ela, o corpo segue reto, tangente.']}]);
