/* =====================================================================
   Lições — Energia, Quantidade de movimento, Gravitação, Estática e fluidos, Termologia
   ===================================================================== */
mod('ene','Energia','trabalho, potência e conservação da energia',[
{id:'trabalho',t:'Trabalho e potência',min:14,
 idea:`<p>Em física, <b>trabalho</b> tem um sentido preciso: é a energia que uma força transfere ao deslocar um corpo. Se você empurra uma caixa com 50 N por 4 m, na direção do movimento, realiza 200 J de trabalho. A unidade é o <b>joule</b> (J = N·m).</p>
 <p>Só conta a parte da força <b>na direção do deslocamento</b>: W = F·d·cos θ. Puxando uma mala por uma alça inclinada, a parte vertical da força não realiza trabalho. Uma força perpendicular ao movimento (como o peso num deslocamento horizontal) realiza trabalho zero. Uma força contrária ao movimento (como o atrito) realiza trabalho negativo: tira energia.</p>
 <p><b>Potência</b> é a rapidez com que se realiza trabalho: P = W/Δt, em watts (W = J/s). Subir a escada correndo ou andando dá o mesmo trabalho; correndo, a potência é maior.</p>`,
 pred:{q:'Você carrega uma mochila pesada andando em linha reta num corredor plano, com velocidade constante. O trabalho da força que você faz para segurar a mochila (para cima) é:',o:['zero','positivo e grande','negativo','igual ao peso vezes a altura da mochila'],a:0,why:'A força para segurar é vertical e o deslocamento é horizontal: θ = 90° e cos 90° = 0. Você cansa por causa dos músculos, mas não transfere energia mecânica à mochila.'},
 lab:{sim:'work'},
 tasks:['Com F = 20 N e d = 5 m, compare o trabalho em 0°, 60° e 90°.','Em 60°, a força "útil" é quanto de F?','Aumente F e veja a potência média: por que ela cresce mais que o trabalho?'],
 f:[{f:'W = F·d·cos θ',s:[['W','trabalho','J'],['F','força','N'],['d','deslocamento','m'],['θ','ângulo entre a força e o deslocamento','°']],n:'θ = 0°: W = F·d. θ = 90°: W = 0. θ = 180°: W = −F·d.'},{f:'P = '+frac('W','Δt'),s:[['P','potência','W (watt)'],['Δt','tempo','s']],n:'1 kW = 1000 W. 1 cv ≈ 735 W.'}],
 ex:{q:'Um elevador ergue 500 kg a 20 m de altura em 25 s, com velocidade constante. Qual é a potência do motor? (g = 10)',s:['Força do motor = peso = 500 × 10 = 5000 N (velocidade constante).','Trabalho: W = F·d = 5000 × 20 = 100 000 J.','P = W/Δt = 100 000/25 = <b>4000 W</b> (4 kW).']},
 probs:[
  ()=>{ const Fo=R(10,100,10), d=R(2,20); return NUM(`Você empurra uma caixa com <b>${Fo} N</b>, na direção do movimento, por <b>${d} m</b>. Qual é o trabalho realizado?`,Fo*d,'J',[`W = F·d·cos 0° = ${Fo} × ${d}`,`W = ${Fo*d} J`],[[Fo/d,'Trabalho é força vezes deslocamento.']]); },
  ()=>{ const Fo=R(20,100,20), d=R(2,10), th=60; return NUM(`Uma criança puxa um carrinho com <b>${Fo} N</b> por uma corda que faz <b>60°</b> com o chão, andando <b>${d} m</b>. Qual é o trabalho da força? (cos 60° = 0,5)`,Fo*d*.5,'J',[`W = F·d·cos 60° = ${Fo} × ${d} × 0,5`,`W = ${Fo*d*.5} J`],[[Fo*d,'Só a componente horizontal da força (F·cos 60°) realiza trabalho.'],[Fo*d*.87,'Use o cosseno de 60°, que vale 0,5.']]); },
  ()=>{ const m=R(50,500,50), h=R(2,20,2), t=R(5,40,5); return NUM(`Um guindaste ergue <b>${m} kg</b> a <b>${h} m</b> de altura, com velocidade constante, em <b>${t} s</b>. Qual é a potência? (g = 10)`,m*10*h/t,'W',[`W = m·g·h = ${m} × 10 × ${h} = ${m*10*h} J`,`P = W/t = ${m*10*h}/${t} = ${F(m*10*h/t)} W`],[[m*10*h,'Esse é o trabalho. Potência é trabalho dividido pelo tempo.'],[m*h/t,'Faltou multiplicar a massa por g para obter a força (peso).']]); },
  ()=>{ const P=pick([500,750,1000,1500,2000]), t=pick([10,20,30,60]); return NUM(`Um motor de <b>${P} W</b> funciona por <b>${t} s</b>. Quanto trabalho realiza?`,P*t,'J',[`W = P·Δt = ${P} × ${t}`,`W = ${P*t} J`],[[P/t,'Potência é W/Δt, então W = P·Δt.']]); },
  POOL([['O trabalho do peso de um carro que anda numa estrada plana e horizontal é:',['zero','positivo','negativo','igual ao peso'],'O peso é vertical e o deslocamento é horizontal: cos 90° = 0.'],['O trabalho da força de atrito sobre um bloco que desliza é:',['negativo','positivo','zero','sempre igual ao da força aplicada'],'O atrito aponta contra o deslocamento (θ = 180°): tira energia do bloco.'],['Duas pessoas iguais sobem a mesma escada, uma em 10 s e outra em 20 s. Comparando:',['o trabalho é igual; a potência da mais rápida é o dobro','a mais rápida faz o dobro do trabalho','as duas têm a mesma potência','a mais lenta faz mais trabalho'],'O trabalho (m·g·h) é o mesmo. A potência é trabalho dividido pelo tempo.']])],
 traps:['Achar que toda força realiza trabalho: forças perpendiculares ao deslocamento não realizam.','Esquecer o cos θ quando a força é inclinada.','Confundir trabalho (J) com potência (W = J/s).'],
 keep:['W = F·d·cos θ (joules).','Perpendicular: trabalho zero. Contra o movimento: negativo.','P = W/Δt (watts).']},

{id:'energia',t:'Energia cinética e potencial',min:15,
 idea:`<p>Energia é a capacidade de realizar trabalho. Na mecânica, há duas formas principais:</p>
 <ul><li><b>Energia cinética</b>, a energia do movimento: E<sub>c</sub> = m·v²/2. Depende do quadrado da velocidade: um carro a 100 km/h tem quatro vezes a energia do mesmo carro a 50 km/h. Por isso a velocidade pesa tanto nos acidentes.</li><li><b>Energia potencial gravitacional</b>, a energia guardada pela altura: E<sub>p</sub> = m·g·h. Uma pedra no alto de um prédio pode realizar trabalho ao cair.</li></ul>
 <p>Há também a <b>potencial elástica</b> de uma mola deformada, E<sub>el</sub> = k·x²/2. O <b>teorema da energia cinética</b> liga tudo isso ao trabalho: o trabalho da força resultante é igual à variação da energia cinética, W = ΔE<sub>c</sub>.</p>`,
 pred:{q:'Um carro vai de 36 km/h para 72 km/h. A energia cinética dele:',o:['quadruplica','dobra','aumenta 36 vezes','fica igual'],a:0,why:'E<sub>c</sub> = m·v²/2. Com a velocidade dobrada, v² fica 4 vezes maior. É por isso que a distância de frenagem também quadruplica.'},
 lab:{sim:'ramp',cfg:{fric:false}},
 tasks:['Solte o skatista de 8 m. Onde a energia cinética é máxima? E a potencial?','Veja a barra "Total" enquanto ele anda: ela muda?','Mude a massa: a velocidade no fundo muda?'],
 f:[{f:'E<sub class="up">c</sub> = '+frac('m·v²','2')+'      E<sub class="up">p</sub> = m·g·h',s:[['E<sub>c</sub>','energia cinética','J'],['E<sub>p</sub>','energia potencial gravitacional','J'],['h','altura em relação a um nível de referência','m']]},{f:'E<sub class="up">el</sub> = '+frac('k·x²','2')+'      W<sub class="up">res</sub> = ΔE<sub class="up">c</sub>',s:[['k','constante elástica da mola','N/m'],['x','deformação da mola','m']]}],
 ex:{q:'Qual é a energia cinética de uma bola de 0,4 kg chutada a 20 m/s? De que altura ela precisaria cair para ter essa energia? (g = 10)',s:['E<sub>c</sub> = m·v²/2 = 0,4 × 400/2 = 80 J.','Para E<sub>p</sub> = 80 J: m·g·h = 80 → 0,4 × 10 × h = 80.','<b>h = 20 m</b>.']},
 probs:[
  ()=>{ const m=pick([.5,1,2,5,10,60,1000]), v=R(2,30,2); return NUM(`Qual é a energia cinética de um corpo de <b>${F(m)} kg</b> a <b>${v} m/s</b>?`,m*v*v/2,'J',[`E<sub>c</sub> = m·v²/2 = ${F(m)} × ${v}²/2`,`E<sub>c</sub> = ${F(m*v*v/2)} J`],[[m*v*v,'Faltou dividir por 2.'],[m*v/2,'Faltou elevar a velocidade ao quadrado.']]); },
  ()=>{ const m=R(1,80), h=R(2,50,2); return NUM(`Qual é a energia potencial gravitacional de um corpo de <b>${m} kg</b> a <b>${h} m</b> do chão? (g = 10)`,m*10*h,'J',[`E<sub>p</sub> = m·g·h = ${m} × 10 × ${h}`,`E<sub>p</sub> = ${m*10*h} J`],[[m*h,'Faltou multiplicar por g.']]); },
  ()=>{ const k=pick([100,200,400,800,1000]), x=pick([.05,.1,.2,.3]); return NUM(`Uma mola de constante <b>${k} N/m</b> é comprimida <b>${F(x)} m</b>. Quanta energia fica armazenada?`,k*x*x/2,'J',[`E<sub>el</sub> = k·x²/2 = ${k} × ${F(x)}²/2`,`E<sub>el</sub> = ${F(k*x*x/2)} J`],[[k*x/2,'Faltou elevar a deformação ao quadrado.'],[k*x*x,'Faltou dividir por 2.']]); },
  ()=>{ const m=R(2,10), v0=R(0,6,2), W=R(20,200,20); const v=Math.sqrt(v0*v0+2*W/m); return NUM(`Um carrinho de <b>${m} kg</b> a <b>${v0} m/s</b> recebe <b>${W} J</b> de trabalho da força resultante. Qual é a nova energia cinética?`,m*v0*v0/2+W,'J',[`E<sub>c</sub> inicial = ${m} × ${v0}²/2 = ${m*v0*v0/2} J`,`W = ΔE<sub>c</sub> → E<sub>c</sub> final = ${m*v0*v0/2} + ${W} = ${m*v0*v0/2+W} J`],[[W,'Some o trabalho à energia cinética que o carrinho já tinha.']]); },
  POOL([['Se a velocidade de um carro triplica, sua energia cinética fica:',['9 vezes maior','3 vezes maior','6 vezes maior','igual'],'E<sub>c</sub> ∝ v²: 3² = 9.'],['Uma pedra está no alto de um prédio, parada. Ela tem:',['energia potencial, mas não cinética','energia cinética, mas não potencial','as duas','nenhuma energia'],'Parada: v = 0, então E<sub>c</sub> = 0. A altura lhe dá energia potencial.']])],
 traps:['Esquecer de elevar a velocidade ao quadrado em E<sub>c</sub>.','Esquecer de dividir por 2.','Usar a massa em gramas: no SI é quilograma.'],
 keep:['E<sub>c</sub> = mv²/2 (depende de v²).','E<sub>p</sub> = mgh; E<sub>el</sub> = kx²/2.','Trabalho da resultante = variação da energia cinética.']},

{id:'conservacao',t:'Conservação da energia',min:16,
 idea:`<p>A energia não se cria nem se destrói: só muda de forma. Numa montanha-russa sem atrito, a <b>energia mecânica</b> (E<sub>c</sub> + E<sub>p</sub>) é constante. No alto, quase toda é potencial; lá embaixo, virou cinética. Por isso dá para calcular a velocidade no fundo sem saber o formato da pista: m·g·h = m·v²/2, ou seja, <b>v = √(2gh)</b>, que nem depende da massa.</p>
 <p>Com atrito, parte da energia mecânica vira <b>energia térmica</b> (calor), e o carrinho não volta à altura inicial. A energia total continua conservada; o que diminui é a parte "útil", mecânica.</p>
 <p>Esse é o princípio mais usado da física: numa usina hidrelétrica, a potencial da água vira cinética na turbina e depois elétrica; no seu corpo, a energia química dos alimentos vira movimento e calor.</p>`,
 pred:{q:'Um skatista parte do repouso a 5 m de altura numa pista em U sem atrito. Até que altura ele chega do outro lado?',o:['5 m','menos de 5 m','mais de 5 m','depende da massa dele'],a:0,why:'Sem atrito, a energia mecânica se conserva: ele só para quando toda a cinética voltar a ser potencial, na mesma altura. Com atrito, chegaria mais baixo.'},
 lab:{sim:'ramp',cfg:{fric:true}},
 tasks:['Com atrito zero, confira que o skatista volta à mesma altura.','Coloque atrito 0,06. Para onde vai a energia que "some" da barra mecânica?','Com atrito, a barra "Total" continua constante?'],
 f:[{f:'E<sub class="up">c</sub> + E<sub class="up">p</sub> = constante (sem atrito)',s:[['E<sub>mec</sub>','energia mecânica = E<sub>c</sub> + E<sub>p</sub>','J']]},{f:'v = √(2·g·h)',s:[['h','altura de queda','m']],n:'Velocidade de quem desce uma altura h partindo do repouso, sem atrito, por qualquer caminho.'},{f:'E<sub class="up">mec, final</sub> = E<sub class="up">mec, inicial</sub> − |W<sub class="up">atrito</sub>|',n:'O que o atrito tira vira energia térmica.'}],
 ex:{q:'Um carrinho de montanha-russa parte do repouso a 20 m de altura. Qual é a velocidade dele a 5 m de altura? (sem atrito, g = 10)',s:['Ele desceu 20 − 5 = 15 m.','m·g·15 = m·v²/2 → v² = 2 × 10 × 15 = 300.','<b>v ≈ 17,3 m/s</b>. A massa se cancela.']},
 probs:[
  ()=>{ const h=pick([5,20,45,80,1.8,3.2]); return NUM(`Um objeto desce um escorregador sem atrito, partindo do repouso de uma altura de <b>${F(h)} m</b>. Com que velocidade chega embaixo? (g = 10)`,Math.sqrt(20*h),'m/s',[`m·g·h = m·v²/2 → v = √(2gh)`,`v = √(2 × 10 × ${F(h)}) = ${F(Math.sqrt(20*h))} m/s`],[[20*h,'Esse é v². Tire a raiz quadrada.'],[Math.sqrt(10*h),'Confira: v² = 2·g·h.']]); },
  ()=>{ const v=R(2,20,2); return NUM(`Uma bola é lançada para cima a <b>${v} m/s</b>. Usando conservação de energia, qual é a altura máxima? (g = 10)`,v*v/20,'m',[`m·v²/2 = m·g·h`,`h = v²/(2g) = ${v*v}/20 = ${F(v*v/20)} m`],[[v*v/10,'Faltou dividir por 2.']]); },
  ()=>{ const m=R(20,80,10), h=R(5,20,5), v=pick([4,6,8,10]); const E0=m*10*h, Ef=m*v*v/2; if(Ef>=E0) return NUM(`Um carrinho de <b>${m} kg</b> desce de <b>${h} m</b> e chega embaixo a <b>2 m/s</b>. Quanta energia virou calor? (g = 10)`,E0-m*2,'J',[`Inicial: m·g·h = ${E0} J`,`Final: m·v²/2 = ${m*2} J`,`Dissipada: ${E0-m*2} J`],[]); return NUM(`Um trenó de <b>${m} kg</b> desce um morro de <b>${h} m</b>, partindo do repouso, e chega embaixo a <b>${v} m/s</b>. Quanta energia virou calor por causa do atrito? (g = 10)`,E0-Ef,'J',[`Energia mecânica inicial: m·g·h = ${E0} J`,`Energia cinética final: m·v²/2 = ${Ef} J`,`Dissipada: ${E0} − ${Ef} = ${E0-Ef} J`],[[Ef,'Essa é a energia que sobrou como cinética. Pergunta-se quanto foi dissipado.']]); },
  ()=>{ const k=pick([200,400,800]), x=pick([.1,.2]), m=pick([.1,.2,.5]); const v=Math.sqrt(k*x*x/m); return NUM(`Uma mola (k = <b>${k} N/m</b>) comprimida <b>${F(x)} m</b> lança um bloco de <b>${F(m)} kg</b> num piso sem atrito. Com que velocidade o bloco sai?`,v,'m/s',[`k·x²/2 = m·v²/2`,`v = √(k·x²/m) = √(${k} × ${F(x*x)}/${F(m)}) = ${F(v)} m/s`],[[v*v,'Esse é v². Tire a raiz.']]); },
  POOL([['Uma bola de 1 kg e outra de 5 kg descem a mesma rampa sem atrito, da mesma altura. No fim da rampa:',['têm a mesma velocidade','a de 5 kg é mais rápida','a de 1 kg é mais rápida','depende do formato da rampa'],'v = √(2gh) não depende da massa (nem do formato da rampa, sem atrito).'],['Numa hidrelétrica, a sequência de transformações é:',['potencial → cinética → elétrica','elétrica → cinética → potencial','térmica → potencial → elétrica','química → elétrica'],'A água represada tem energia potencial; ao descer, ganha cinética e gira a turbina, que gera energia elétrica.'],['Com atrito, o que acontece com a energia total de um sistema isolado?',['se conserva; parte vira energia térmica','diminui','aumenta','vira zero no fim'],'A energia total sempre se conserva. O que diminui é a energia mecânica.']])],
 traps:['Achar que objetos mais pesados chegam mais rápido ao fim de uma rampa sem atrito.','Esquecer que com atrito a energia mecânica diminui.','Dizer que a energia "acaba": ela se transforma.'],
 keep:['Sem atrito: E<sub>c</sub> + E<sub>p</sub> constante.','v = √(2gh), independente da massa e do caminho.','Com atrito, energia mecânica vira térmica; a total se conserva.']}]);

mod('mom','Quantidade de movimento','impulso e colisões',[
{id:'impulso',t:'Impulso e quantidade de movimento',min:14,
 idea:`<p>Pegar uma bola de tênis a 20 m/s é fácil; pegar uma bola de boliche na mesma velocidade, nem tanto. A grandeza que mede "quanto movimento" um corpo tem é a <b>quantidade de movimento</b> (ou momento linear): Q = m·v, um vetor, em kg·m/s.</p>
 <p>Para mudar a quantidade de movimento é preciso um <b>impulso</b>: força vezes tempo, I = F·Δt. E vale I = ΔQ. Num gráfico da força pelo tempo, o impulso é a <b>área</b> sob a curva.</p>
 <p>Isso explica o air bag e a dobra dos joelhos ao pular de um muro: a variação de Q é a mesma, mas, aumentando o tempo de contato, a força média diminui. Um chute rápido e forte, ao contrário, dá grande impulso em pouco tempo.</p>`,
 pred:{q:'Por que um air bag reduz os ferimentos numa batida?',o:['aumenta o tempo da freada do corpo, diminuindo a força','diminui a velocidade do carro antes da batida','absorve toda a quantidade de movimento','faz a batida durar menos'],a:0,why:'O corpo precisa parar de qualquer jeito (ΔQ fixo). Como F·Δt = ΔQ, esticar o Δt faz a força média cair.'},
 lab:{sim:'impulse'},
 tasks:['Dobre o tempo de contato mantendo a força máxima. O que acontece com a velocidade da bola?','Encontre duas combinações diferentes de força e tempo que deem a mesma velocidade final.','Por que a área do gráfico é metade de F<sub>máx</sub>·Δt?'],
 f:[{f:'Q = m·v      I = F·Δt = ΔQ',s:[['Q','quantidade de movimento','kg·m/s'],['I','impulso','N·s'],['F','força média','N'],['Δt','tempo de contato','s']],n:'Força variável: o impulso é a área do gráfico F × t.'}],
 ex:{q:'Uma bola de 0,5 kg chega a 10 m/s num goleiro, que a para em 0,05 s. Qual é a força média nas mãos dele?',s:['ΔQ = m·(0 − 10) = −5 kg·m/s (a bola perde 5 kg·m/s).','F·Δt = ΔQ → F = 5/0,05.','<b>F = 100 N</b>. Se o goleiro recuar as mãos e levar 0,1 s, a força cai para 50 N.']},
 probs:[
  ()=>{ const m=pick([.2,.5,1,2,70,1000]), v=R(2,30,2); return NUM(`Qual é a quantidade de movimento de um corpo de <b>${F(m)} kg</b> a <b>${v} m/s</b>?`,m*v,'kg·m/s',[`Q = m·v = ${F(m)} × ${v} = ${F(m*v)} kg·m/s`],[[m*v*v/2,'Isso é energia cinética. Quantidade de movimento é m·v.']]); },
  ()=>{ const Fo=R(10,200,10), t=pick([.1,.2,.5,1,2]); return NUM(`Uma força média de <b>${Fo} N</b> age por <b>${F(t)} s</b>. Qual é o impulso?`,Fo*t,'N·s',[`I = F·Δt = ${Fo} × ${F(t)} = ${F(Fo*t)} N·s`],[[Fo/t,'Impulso é força <b>vezes</b> tempo.']]); },
  ()=>{ const m=pick([.2,.4,.5]), v=R(10,30,5), t=pick([.01,.02,.05,.1]); return NUM(`Um jogador chuta uma bola parada de <b>${F(m)} kg</b>, que sai a <b>${v} m/s</b>. O contato dura <b>${F(t)} s</b>. Qual é a força média do chute?`,m*v/t,'N',[`ΔQ = ${F(m)} × ${v} = ${F(m*v)} kg·m/s`,`F = ΔQ/Δt = ${F(m*v)}/${F(t)} = ${F(m*v/t)} N`],[[m*v,'Esse é o impulso (ΔQ). Divida pelo tempo de contato.'],[m*v*t,'F = ΔQ/Δt: divida pelo tempo.']]); },
  ()=>{ const m=pick([.1,.2,.5]), v=R(5,20,5); return NUM(`Uma bola de <b>${F(m)} kg</b> bate numa parede a <b>${v} m/s</b> e volta com a mesma velocidade. Qual é o módulo da variação da quantidade de movimento?`,2*m*v,'kg·m/s',[`Antes: +${F(m*v)}; depois: −${F(m*v)} (sentido oposto)`,`|ΔQ| = ${F(m*v)} − (−${F(m*v)}) = ${F(2*m*v)} kg·m/s`],[[0,'Q é vetor: o sentido inverteu, então a variação não é zero.'],[m*v,'Ao voltar, o sentido inverte: a variação é o dobro.']],'Q é vetor: preste atenção ao sentido.'); },
  POOL([['Por que os joelhos devem dobrar ao pular de um muro?',['para aumentar o tempo de frenagem e diminuir a força','para diminuir a quantidade de movimento','para aumentar a velocidade de chegada','para diminuir o peso'],'A variação de Q é fixa; mais tempo, menos força.'],['No gráfico força × tempo, o impulso é:',['a área sob a curva','a inclinação da curva','o valor máximo da força','o tempo total'],'I = F·Δt: a área.']])],
 traps:['Confundir quantidade de movimento (m·v) com energia cinética (m·v²/2).','Esquecer que Q é vetor: quicar e voltar dobra a variação.','Achar que o air bag diminui a variação de Q (ele aumenta o tempo).'],
 keep:['Q = m·v (vetor).','I = F·Δt = ΔQ; área do gráfico F × t.','Mais tempo de contato, menor força para a mesma ΔQ.']},

{id:'colisoes',t:'Colisões e conservação do momento',min:16,
 idea:`<p>Quando dois corpos colidem, as forças entre eles são de ação e reação: iguais e opostas, durante o mesmo tempo. Então o impulso que um recebe é igual e oposto ao do outro, e a <b>quantidade de movimento total se conserva</b>: Q<sub>antes</sub> = Q<sub>depois</sub>. Isso vale para toda colisão e explosão de um sistema isolado.</p>
 <p>A energia cinética, porém, <b>nem sempre</b> se conserva. O <b>coeficiente de restituição</b> e mede isso: e = 1, colisão elástica (conserva energia cinética, como bolas de bilhar); 0 &lt; e &lt; 1, parcialmente elástica; e = 0, perfeitamente inelástica (os corpos saem grudados, e é aí que mais energia se perde).</p>
 <p>O recuo de uma arma e a propulsão de um foguete são o mesmo princípio: o total começa zero e continua zero, então um lado vai para a frente e o outro para trás.</p>`,
 pred:{q:'Um carrinho de 2 kg a 5 m/s bate num carrinho idêntico parado, numa colisão perfeitamente elástica. Depois da batida:',o:['o primeiro para e o segundo sai a 5 m/s','os dois saem juntos a 2,5 m/s','o primeiro volta a 5 m/s','os dois param'],a:0,why:'Com massas iguais e colisão elástica, os corpos trocam de velocidade, como no pêndulo de Newton e na sinuca.'},
 lab:{sim:'coll'},
 tasks:['Massas iguais, v₂ = 0, e = 1: confira a troca de velocidades.','Coloque e = 0. A quantidade de movimento total mudou? E a energia cinética?','Faça m₁ = 1 kg bater em m₂ = 5 kg parada, elástica. O que acontece com o carrinho leve?'],
 f:[{f:'m₁·v₁ + m₂·v₂ = m₁·v₁\' + m₂·v₂\'',s:[['v₁, v₂','velocidades antes (com sinal)','m/s'],['v₁\', v₂\'','velocidades depois','m/s']],n:'Use sinal: para a direita +, para a esquerda −.'},{f:'e = '+frac('velocidade de afastamento','velocidade de aproximação'),n:'Perfeitamente inelástica (e = 0): v\' = (m₁v₁ + m₂v₂)/(m₁ + m₂).'}],
 ex:{q:'Um vagão de 3 t a 4 m/s engata num vagão de 1 t parado, e seguem juntos. Qual é a velocidade do conjunto?',s:['Q antes = 3000 × 4 + 1000 × 0 = 12 000 kg·m/s.','Depois, juntos: (3000 + 1000)·v\' = 12 000.','<b>v\' = 3 m/s</b>. A energia cinética caiu de 24 kJ para 18 kJ: 6 kJ viraram calor e deformação.']},
 probs:[
  ()=>{ const m1=R(1,5), v1=R(2,10), m2=R(1,5); return NUM(`Um carrinho de <b>${m1} kg</b> a <b>${v1} m/s</b> colide com outro de <b>${m2} kg</b> parado, e os dois seguem grudados. Qual é a velocidade do conjunto?`,m1*v1/(m1+m2),'m/s',[`Q antes = ${m1} × ${v1} = ${m1*v1} kg·m/s`,`v' = ${m1*v1}/(${m1} + ${m2}) = ${F(m1*v1/(m1+m2))} m/s`],[[m1*v1/m2,'Depois da colisão a massa que se move é a soma das duas.'],[v1/2,'Só vale a metade quando as massas são iguais.']]); },
  ()=>{ const M=pick([2,3,4,5]), m=pick([.01,.02,.05]), v=pick([200,300,400,500]); return NUM(`Uma espingarda de <b>${M} kg</b>, inicialmente parada, dispara um projétil de <b>${F(m)} kg</b> a <b>${v} m/s</b>. Com que velocidade a arma recua?`,m*v/M,'m/s',[`Q total antes = 0 → depois: ${F(m)} × ${v} = ${M} × v<sub>recuo</sub>`,`v<sub>recuo</sub> = ${F(m*v)}/${M} = ${F(m*v/M)} m/s`],[[v,'A arma é muito mais pesada que o projétil: recua bem mais devagar.']]); },
  ()=>{ const m=R(1,4), v=R(2,8); return NUM(`Numa colisão perfeitamente elástica, uma bola de <b>${m} kg</b> a <b>${v} m/s</b> atinge outra idêntica, parada. Qual é a velocidade da bola atingida depois?`,v,'m/s',[`Massas iguais e colisão elástica: as bolas trocam de velocidade.`,`A atingida sai a ${v} m/s, e a outra para.`],[[v/2,'Metade seria se elas saíssem grudadas (inelástica).']]); },
  ()=>{ const m1=R(2,6), v1=R(3,8), m2=R(2,6); const vf=m1*v1/(m1+m2), E0=m1*v1*v1/2, Ef=(m1+m2)*vf*vf/2; return NUM(`Um bloco de <b>${m1} kg</b> a <b>${v1} m/s</b> gruda num bloco de <b>${m2} kg</b> parado. Quanta energia cinética é perdida?`,E0-Ef,'J',[`v' = ${m1*v1}/${m1+m2} = ${F(vf)} m/s`,`E antes = ${F(E0)} J; depois = ${F(Ef)} J`,`Perda = ${F(E0-Ef)} J`],[[0,'Numa colisão em que os corpos grudam, sempre se perde energia cinética.'],[Ef,'Essa é a energia que sobrou.']]); },
  POOL([['Em qualquer colisão de um sistema isolado, sempre se conserva:',['a quantidade de movimento total','a energia cinética total','a velocidade de cada corpo','a energia potencial'],'As forças internas são pares de ação e reação: o momento total não muda. A energia cinética só se conserva nas elásticas.'],['A colisão em que se perde mais energia cinética é a:',['perfeitamente inelástica (corpos grudam)','perfeitamente elástica','parcialmente elástica','depende só das massas'],'Com e = 0, a máxima energia possível vira calor e deformação.'],['Um foguete no espaço acelera porque:',['empurra os gases para trás e é empurrado para a frente','empurra o ar à sua volta','a gravidade diminui','a quantidade de movimento dele é criada pelo motor'],'Conservação do momento: gases para trás, foguete para a frente. Funciona no vácuo.']])],
 traps:['Esquecer os sinais das velocidades de sentidos opostos.','Achar que energia cinética sempre se conserva.','Na colisão em que grudam, esquecer de somar as massas.'],
 keep:['Q total se conserva em colisões e explosões.','Elástica (e = 1): conserva E<sub>c</sub>. Inelástica (e = 0): grudam, perdem mais.','Massas iguais, elástica, um parado: trocam de velocidade.']}]);

mod('grav','Gravitação','planetas, órbitas e a lei da gravitação universal',[
{id:'gravitacao',t:'Kepler e a gravitação universal',min:18,
 idea:`<p>No século XVII, Kepler analisou anos de medições dos planetas e descobriu três leis:</p>
 <ul><li><b>1ª lei (órbitas)</b>: os planetas descrevem <b>elipses</b>, com o Sol num dos focos.</li><li><b>2ª lei (áreas)</b>: a linha Sol–planeta varre <b>áreas iguais em tempos iguais</b>. Por isso o planeta é mais rápido quando está mais perto do Sol (periélio).</li><li><b>3ª lei (períodos)</b>: T²/R³ é igual para todos os planetas. Quem está mais longe demora bem mais para dar a volta.</li></ul>
 <p>Newton explicou o porquê: todo par de corpos se atrai com força <b>F = G·M·m/d²</b>. A mesma força que faz a maçã cair mantém a Lua em órbita. Dobrando a distância, a força cai para um quarto. Na superfície de um planeta, g = G·M/R².</p>`,
 pred:{q:'Numa órbita elíptica, em que ponto o planeta anda mais rápido?',o:['no ponto mais próximo do Sol','no ponto mais distante do Sol','a velocidade é a mesma em toda a órbita','nos pontos intermediários'],a:0,why:'Para varrer áreas iguais em tempos iguais, perto do Sol (raio curto) o planeta precisa percorrer um arco maior no mesmo tempo, ou seja, ir mais rápido.'},
 lab:{sim:'orbit'},
 tasks:['Com velocidade 1 × v<sub>circ</sub>, a órbita fica circular. Diminua para 0,8: onde o planeta acelera?','Observe as áreas coloridas: todas levaram o mesmo tempo. Elas parecem iguais?','A partir de que velocidade o planeta escapa da estrela?'],
 f:[{f:'F = G·'+frac('M·m','d²'),s:[['G','constante gravitacional: 6,67×10⁻¹¹','N·m²/kg²'],['M, m','massas dos dois corpos','kg'],['d','distância entre os centros','m']]},{f:frac('T²','R³')+' = constante      g = '+frac('G·M','R²'),s:[['T','período da órbita','s'],['R','raio médio da órbita','m']],n:'A força cai com o quadrado da distância: 2× mais longe → 4× menor; 3× → 9× menor.'}],
 ex:{q:'Se a distância entre dois corpos fosse reduzida à metade, o que aconteceria com a força gravitacional entre eles?',s:['F é proporcional a 1/d².','Com d pela metade: 1/(d/2)² = 4/d².','<b>A força fica 4 vezes maior</b>.']},
 probs:[
  ()=>{ const k=pick([2,3,4,5,10]), F0=R(100,900,100); return NUM(`A atração gravitacional entre dois corpos é de <b>${F0} N</b>. Se a distância entre eles ficar <b>${k} vezes maior</b>, qual será a nova força?`,F0/(k*k),'N',[`F ∝ 1/d²: com d × ${k}, F ÷ ${k}² = F ÷ ${k*k}`,`F = ${F0}/${k*k} = ${F(F0/(k*k))} N`],[[F0/k,'A força cai com o <b>quadrado</b> da distância.']]); },
  ()=>{ const k=pick([2,3,4]), F0=R(10,90,10); return NUM(`Duas esferas se atraem com <b>${F0} N</b>. Se a massa de <b>cada uma</b> for multiplicada por ${k}, mantendo a distância, qual será a força?`,F0*k*k,'N',[`F ∝ M·m: cada massa × ${k} → produto × ${k*k}`,`F = ${F0} × ${k*k} = ${F0*k*k} N`],[[F0*k,'As duas massas mudaram: o produto fica '+k*k+' vezes maior.']]); },
  ()=>{ const k=pick([4,9,16]), T0=1; const r=Math.cbrt(k*k); return NUM(`Um planeta tem órbita com raio <b>${k} vezes</b> o da Terra. Pela 3ª lei de Kepler, qual é o período dele, em anos terrestres?`,Math.sqrt(k**3),'anos',[`T²/R³ constante → T = T<sub>Terra</sub>·√(${k}³)`,`T = √${k**3} = ${F(Math.sqrt(k**3))} anos`],[[k,'O período não cresce na mesma proporção do raio: T² ∝ R³.']],'T² é proporcional a R³.'); },
  ()=>{ const km=pick([2,4,.5]), kr=pick([2,.5]); const g=10*km/(kr*kr); return NUM(`Um planeta tem massa <b>${F(km)} vezes</b> a da Terra e raio <b>${F(kr)} vezes</b> o da Terra. Quanto vale a gravidade na superfície dele? (g<sub>Terra</sub> = 10 m/s²)`,g,'m/s²',[`g = G·M/R² → g' = 10 × ${F(km)}/${F(kr)}²`,`g' = ${F(g)} m/s²`],[[10*km/kr,'O raio entra ao quadrado.']]); },
  POOL([['Segundo a 1ª lei de Kepler, o Sol fica:',['num dos focos da elipse','no centro da elipse','fora da órbita','em cada ponto da órbita'],'As órbitas são elipses com o Sol num foco.'],['Um astronauta na Estação Espacial "flutua" porque:',['ele e a estação estão caindo juntos em volta da Terra','não há gravidade lá em cima','a gravidade da Lua anula a da Terra','está fora da atmosfera'],'A 400 km de altura, g ainda é cerca de 90% do valor na superfície. Tudo lá dentro está em queda livre contínua.'],['Qual planeta tem o maior período (ano mais longo)?',['o mais distante do Sol','o mais próximo do Sol','o de maior massa','todos têm o mesmo período'],'Pela 3ª lei, T² ∝ R³: mais longe, período maior.']])],
 traps:['Achar que não há gravidade no espaço ou na órbita.','Esquecer o quadrado da distância (dobrar d divide F por 4).','Achar que a velocidade de um planeta é constante numa órbita elíptica.'],
 keep:['Elipses; áreas iguais em tempos iguais; T² ∝ R³.','F = GMm/d² (inverso do quadrado).','Órbita é queda livre contínua.']}]);

mod('flu','Estática e fluidos','equilíbrio, alavancas, pressão e empuxo',[
{id:'torque',t:'Torque e alavancas',min:14,
 idea:`<p>Uma força pode fazer um corpo <b>girar</b>. Empurrar uma porta perto da dobradiça quase não adianta; empurrar na maçaneta, longe, é fácil. O que importa é o <b>momento</b> (ou torque) da força: M = F·d, a força vezes a distância até o ponto de apoio (o braço).</p>
 <p>Uma gangorra fica em equilíbrio quando os momentos que giram para um lado igualam os que giram para o outro: m₁·d₁ = m₂·d₂. É por isso que uma criança leve, sentada longe do apoio, equilibra um adulto sentado perto.</p>
 <p>Para um corpo ficar em equilíbrio total, duas condições precisam valer ao mesmo tempo: a <b>força resultante é zero</b> (não translada) e o <b>momento resultante é zero</b> (não gira). Alavancas, tesouras, alicates e pés de cabra usam o braço longo para multiplicar a força.</p>`,
 pred:{q:'Numa gangorra, uma criança de 20 kg senta a 3 m do apoio. Onde deve sentar um adulto de 60 kg para equilibrar?',o:['a 1 m do apoio','a 3 m do apoio','a 9 m do apoio','em qualquer lugar do outro lado'],a:0,why:'20 × 3 = 60 × d → d = 1 m. Com o triplo da massa, o adulto precisa de um terço da distância.'},
 lab:{sim:'lever'},
 tasks:['Coloque 4 kg a 1,5 m. Onde 2 kg equilibram?','Use a leitura "para equilibrar, a massa direita deveria ser" para conferir sua conta.','Com a gangorra equilibrada, dobre as duas distâncias. Continua equilibrada?'],
 f:[{f:'M = F·d',s:[['M','momento (torque)','N·m'],['F','força perpendicular à barra','N'],['d','distância ao ponto de apoio (braço)','m']]},{f:'Equilíbrio: F<sub class="up">R</sub> = 0  e  M<sub class="up">horário</sub> = M<sub class="up">anti-horário</sub>',n:'Numa gangorra: m₁·d₁ = m₂·d₂.'}],
 ex:{q:'Com um pé de cabra de 1 m, apoiado a 10 cm da ponta que está sob uma pedra, você faz 100 N na outra ponta. Qual força chega à pedra?',s:['Braço do seu lado: 1 − 0,1 = 0,9 m. Braço do lado da pedra: 0,1 m.','Momentos iguais: 100 × 0,9 = F × 0,1.','<b>F = 900 N</b>: a alavanca multiplicou sua força por 9.']},
 probs:[
  ()=>{ const m1=R(10,40,5), d1=R(1,3), m2=pick([m1*2,m1*3,m1/2,m1*1.5].filter(x=>x>=5)); return NUM(`Uma criança de <b>${m1} kg</b> senta a <b>${d1} m</b> do apoio de uma gangorra. A que distância deve sentar outra, de <b>${F(m2)} kg</b>, para equilibrar?`,m1*d1/m2,'m',[`m₁·d₁ = m₂·d₂ → ${m1} × ${d1} = ${F(m2)} × d₂`,`d₂ = ${F(m1*d1/m2)} m`],[[m2*d1/m1,'Quem tem mais massa precisa sentar <b>mais perto</b> do apoio.']]); },
  ()=>{ const Fo=R(10,100,10), d=pick([.1,.2,.25,.3,.5]); return NUM(`Você aplica <b>${Fo} N</b> na ponta de uma chave de roda, a <b>${F(d)} m</b> do parafuso, perpendicularmente. Qual é o momento?`,Fo*d,'N·m',[`M = F·d = ${Fo} × ${F(d)} = ${F(Fo*d)} N·m`],[[Fo/d,'Momento é força <b>vezes</b> distância.']]); },
  ()=>{ const L=1, a=pick([.1,.2,.25]), Fo=R(50,200,50); return NUM(`Uma alavanca de <b>1 m</b> tem o apoio a <b>${F(a)} m</b> de uma carga. Você faz <b>${Fo} N</b> na outra ponta. Qual força é aplicada na carga?`,Fo*(L-a)/a,'N',[`Seu braço: ${F(L-a)} m; braço da carga: ${F(a)} m`,`${Fo} × ${F(L-a)} = F × ${F(a)} → F = ${F(Fo*(L-a)/a)} N`],[[Fo*L/a,'Seu braço vai do apoio até a sua mão: 1 − '+F(a)+' m.']]); },
  POOL([['Por que a maçaneta fica longe da dobradiça?',['para aumentar o braço e precisar de menos força','para a porta abrir mais rápido','para diminuir o peso da porta','por estética'],'Mesmo momento com braço maior exige força menor.'],['Para um corpo estar em equilíbrio completo, é preciso:',['força resultante e momento resultante nulos','só força resultante nula','só momento resultante nulo','que ele esteja apoiado no chão'],'Força resultante zero impede a translação; momento zero impede a rotação.']])],
 traps:['Usar a distância até a ponta em vez da distância até o apoio.','Achar que força resultante zero basta para o equilíbrio (o corpo ainda pode girar).','Inverter a proporção: mais massa precisa de menos distância.'],
 keep:['M = F·d (braço até o apoio).','Gangorra em equilíbrio: m₁d₁ = m₂d₂.','Equilíbrio: F<sub>R</sub> = 0 e M<sub>R</sub> = 0.']},

{id:'pressao',t:'Pressão e lei de Stevin',min:15,
 idea:`<p><b>Pressão</b> é força dividida pela área: p = F/A. Uma faca afiada corta porque concentra a força numa área mínima; um esqui não afunda na neve porque espalha o peso. A unidade é o pascal (Pa = N/m²).</p>
 <p>Dentro de um líquido, a pressão vem do peso da coluna de líquido acima: <b>p = p<sub>atm</sub> + ρ·g·h</b> (lei de Stevin). Ela cresce com a profundidade e com a densidade do líquido, e é a mesma em todos os pontos de mesma profundidade, não importa o formato do recipiente. Na água, a cada 10 m a pressão aumenta cerca de 1 atmosfera.</p>
 <p>A <b>lei de Pascal</b> diz que um acréscimo de pressão num líquido se transmite igualmente a todos os pontos. É o princípio do macaco hidráulico e do freio do carro: F₁/A₁ = F₂/A₂.</p>`,
 pred:{q:'Dois mergulhadores estão a 10 m de profundidade: um no mar aberto e outro numa piscina funda e estreita. Quem sente mais pressão?',o:['a mesma pressão','o do mar, porque há mais água','o da piscina, porque a água está mais apertada','depende da área do corpo'],a:0,why:'A pressão num líquido só depende da profundidade, da densidade e da pressão na superfície. A quantidade total de água ao lado não importa.'},
 lab:{sim:'press'},
 tasks:['Leve o sensor a 10 m na água, somando a pressão do ar. Quantas atmosferas você mede?','Troque para mercúrio: quantos metros de água equivalem a 1 m de mercúrio?','Desligue a pressão do ar: o gráfico passa a sair de onde?'],
 f:[{f:'p = '+frac('F','A'),s:[['p','pressão','Pa (N/m²)'],['F','força perpendicular','N'],['A','área','m²']]},{f:'p = p<sub class="up">atm</sub> + ρ·g·h',s:[['ρ','densidade do líquido (água: 1000)','kg/m³'],['h','profundidade','m'],['p<sub>atm</sub>','pressão atmosférica ≈ 1×10⁵','Pa']]},{f:frac('F₁','A₁')+' = '+frac('F₂','A₂'),n:'Prensa hidráulica (lei de Pascal).'}],
 ex:{q:'Um macaco hidráulico tem pistões de áreas 10 cm² e 500 cm². Que força no pistão pequeno ergue um carro de 1000 kg? (g = 10)',s:['Peso do carro: 10 000 N, no pistão grande.','F₁/10 = 10 000/500.','<b>F₁ = 200 N</b>: a área 50 vezes maior multiplica a força por 50.']},
 probs:[
  ()=>{ const m=R(40,100,10), A=pick([.02,.04,.05,.1,.2]); return NUM(`Uma pessoa de <b>${m} kg</b> fica de pé sobre uma área total de <b>${F(A)} m²</b>. Qual pressão ela exerce no chão? (g = 10)`,m*10/A,'Pa',[`F = peso = ${m*10} N`,`p = F/A = ${m*10}/${F(A)} = ${F(m*10/A)} Pa`],[[m/A,'Use a força (peso = m·g), não a massa.'],[m*10*A,'Pressão é força <b>dividida</b> pela área.']]); },
  ()=>{ const h=R(2,50,2); return NUM(`Qual é a pressão da água (só a coluna, sem o ar) a <b>${h} m</b> de profundidade? (ρ = 1000 kg/m³; g = 10)`,1000*10*h,'Pa',[`p = ρ·g·h = 1000 × 10 × ${h}`,`p = ${F(1e4*h)} Pa`],[[1000*h,'Faltou multiplicar por g.']],'Digite em notação científica se preferir: 2e5.'); },
  ()=>{ const h=pick([10,20,30,40,50]); return NUM(`Um mergulhador está a <b>${h} m</b> de profundidade no mar. Qual é a pressão total sobre ele, em atmosferas? (a cada 10 m de água, +1 atm)`,1+h/10,'atm',[`Coluna de água: ${h}/10 = ${h/10} atm`,`Somando o ar da superfície: 1 + ${h/10} = ${1+h/10} atm`],[[h/10,'Faltou somar a pressão atmosférica (1 atm) na superfície.']]); },
  ()=>{ const A1=pick([5,10,20]), A2=pick([200,400,500,1000]), m=pick([500,800,1000,1200]); return NUM(`Numa prensa hidráulica, o pistão menor tem <b>${A1} cm²</b> e o maior, <b>${A2} cm²</b>. Que força no menor equilibra <b>${m} kg</b> no maior? (g = 10)`,m*10*A1/A2,'N',[`Peso: ${m*10} N`,`F₁ = ${m*10} × ${A1}/${A2} = ${F(m*10*A1/A2)} N`],[[m*10*A2/A1,'No pistão menor a força é <b>menor</b>.']]); },
  POOL([['Por que as barragens são mais largas embaixo?',['a pressão da água aumenta com a profundidade','a água embaixo é mais densa','o fundo precisa sustentar o peso da barragem','por estética'],'Stevin: p cresce com h. A base aguenta a maior pressão.'],['Três recipientes de formatos diferentes têm água até a mesma altura. A pressão no fundo:',['é igual nos três','é maior no mais largo','é maior no que tem mais água','é maior no mais estreito'],'Só depende de ρ, g e h (paradoxo hidrostático).']])],
 traps:['Esquecer de somar a pressão atmosférica quando o problema pede a pressão total.','Usar a massa em vez da força em p = F/A.','Achar que a quantidade de líquido muda a pressão no fundo.'],
 keep:['p = F/A.','Stevin: p = p<sub>atm</sub> + ρgh; +1 atm a cada 10 m de água.','Pascal: F₁/A₁ = F₂/A₂.']},

{id:'empuxo',t:'Empuxo e flutuação',min:15,
 idea:`<p>Por que um navio de aço flutua e um prego de aço afunda? Todo corpo mergulhado num fluido recebe uma força para cima, o <b>empuxo</b>. O <b>princípio de Arquimedes</b> diz quanto ele vale: o peso do fluido deslocado. E = ρ<sub>fluido</sub>·V<sub>submerso</sub>·g.</p>
 <p>Compare o empuxo máximo (corpo todo submerso) com o peso. Na prática, basta comparar densidades: se o corpo é <b>menos denso</b> que o líquido, flutua, afundando só a fração ρ<sub>corpo</sub>/ρ<sub>líquido</sub> do volume; se é <b>mais denso</b>, afunda. O navio flutua porque, com o ar dentro do casco, sua densidade média é menor que a da água.</p>
 <p>Um corpo que afunda parece mais leve dentro da água: o <b>peso aparente</b> é P − E.</p>`,
 pred:{q:'Um bloco de madeira com densidade 600 kg/m³ é colocado na água (1000 kg/m³). Que fração do bloco fica submersa?',o:['60%','40%','100%','nenhuma'],a:0,why:'Na flutuação, E = P: ρ<sub>água</sub>·V<sub>sub</sub> = ρ<sub>madeira</sub>·V. A fração submersa é 600/1000 = 60%.'},
 lab:{sim:'buoy'},
 tasks:['Faça um bloco de 600 kg/m³ em água e depois em álcool. Em qual ele afunda mais?','Encontre a densidade que faz o bloco afundar na água.','Com o bloco flutuando, compare as setas P e E.'],
 f:[{f:'E = ρ<sub class="up">fluido</sub>·V<sub class="up">submerso</sub>·g',s:[['E','empuxo','N'],['ρ<sub>fluido</sub>','densidade do fluido','kg/m³'],['V<sub>sub</sub>','volume submerso (volume de fluido deslocado)','m³']]},{f:frac('V<sub class="up">sub</sub>','V')+' = '+frac('ρ<sub class="up">corpo</sub>','ρ<sub class="up">fluido</sub>')+'   (flutuando)',n:'1 L = 10⁻³ m³. Peso aparente de quem afunda: P − E.'}],
 ex:{q:'Um objeto de 3 L e 5 kg é totalmente mergulhado em água. Qual é o empuxo e o peso aparente? (g = 10)',s:['V = 3 L = 0,003 m³. E = 1000 × 0,003 × 10 = 30 N.','Peso real: 5 × 10 = 50 N.','Peso aparente: 50 − 30 = <b>20 N</b>: dentro da água ele parece ter 2 kg.']},
 probs:[
  ()=>{ const V=R(1,20); return NUM(`Um objeto de <b>${V} L</b> está totalmente mergulhado em água. Qual é o empuxo? (ρ<sub>água</sub> = 1000 kg/m³; g = 10)`,V*10,'N',[`V = ${V} L = ${F(V/1000)} m³`,`E = 1000 × ${F(V/1000)} × 10 = ${V*10} N`],[[V*1000*10,'Converta litros para m³: 1 L = 0,001 m³.']]); },
  ()=>{ const rb=R(200,900,100), rf=pick([1000,800]); return NUM(`Um bloco de densidade <b>${rb} kg/m³</b> flutua em ${rf===1000?'água (1000 kg/m³)':'álcool (800 kg/m³)'}. Que porcentagem do volume fica submersa?`,rb/rf*100,'%',[`V<sub>sub</sub>/V = ρ<sub>bloco</sub>/ρ<sub>líquido</sub> = ${rb}/${rf}`,`= ${F(rb/rf*100)} %`],[[100-rb/rf*100,'Essa é a parte que fica <b>fora</b> do líquido.']]); },
  ()=>{ const V=R(1,5), m=V+R(1,8); return NUM(`Um objeto de <b>${m} kg</b> e <b>${V} L</b> afunda na água. Qual é o peso aparente dele dentro da água? (g = 10)`,(m-V)*10,'N',[`P = ${m*10} N; E = 1000 × ${F(V/1000)} × 10 = ${V*10} N`,`P<sub>ap</sub> = P − E = ${(m-V)*10} N`],[[m*10,'Esse é o peso fora da água. Desconte o empuxo.']]); },
  POOL([['Um navio de aço flutua porque:',['sua densidade média (aço + ar do casco) é menor que a da água','o aço de navios é mais leve','a água do mar é muito densa','o motor o mantém na superfície'],'O casco oco desloca muita água: o empuxo máximo supera o peso.'],['Um corpo totalmente submerso desce mais fundo. O empuxo sobre ele:',['não muda','aumenta','diminui','zera no fundo'],'O empuxo depende do volume submerso e da densidade do líquido, não da profundidade.'],['O mesmo navio passa do rio (água doce) para o mar (água salgada, mais densa). Ele:',['sobe um pouco (afunda menos)','afunda mais','afunda completamente','fica igual'],'Com líquido mais denso, basta deslocar menos volume para equilibrar o peso.']])],
 traps:['Esquecer de converter litros para m³ (1 L = 0,001 m³).','Usar a densidade do corpo no empuxo: é a do fluido.','Achar que o empuxo aumenta com a profundidade.'],
 keep:['E = ρ<sub>fluido</sub>·V<sub>sub</sub>·g = peso do fluido deslocado.','Menos denso que o líquido: flutua. Mais denso: afunda.','Fração submersa = ρ<sub>corpo</sub>/ρ<sub>líquido</sub>.']}]);

mod('ter','Termologia','temperatura, calor, gases e máquinas térmicas',[
{id:'temperatura',t:'Temperatura e escalas',min:12,
 idea:`<p><b>Temperatura</b> mede o grau de agitação das partículas de um corpo: quanto mais rápido elas vibram e se movem, maior a temperatura. <b>Calor</b> é outra coisa: é energia em trânsito, que passa sozinha do corpo mais quente para o mais frio. Um corpo não "tem" calor; ele tem temperatura e energia interna.</p>
 <p>Três escalas são usadas: <b>Celsius</b> (água congela a 0 °C e ferve a 100 °C, ao nível do mar), <b>Fahrenheit</b> (32 °F e 212 °F) e <b>Kelvin</b>, a escala absoluta do SI, que começa no <b>zero absoluto</b> (0 K = −273 °C), a menor temperatura possível.</p>
 <p>Para converter: T<sub>K</sub> = T<sub>C</sub> + 273 e T<sub>C</sub>/5 = (T<sub>F</sub> − 32)/9. Uma <b>variação</b> de 1 °C é igual a 1 K e a 1,8 °F.</p>`,
 pred:{q:'Um dia de verão tem 104 °F em Phoenix (EUA). Em Celsius, isso é aproximadamente:',o:['40 °C','104 °C','58 °C','72 °C'],a:0,why:'(104 − 32)/9 = 8, e 8 × 5 = 40 °C. Muito quente, mas bem longe de ferver a água.'},
 lab:{sim:'temp'},
 tasks:['Coloque 37 °C. Quanto marca em Fahrenheit? E em Kelvin?','Encontre a temperatura em que Celsius e Fahrenheit marcam o mesmo número.','Vá até o zero absoluto. Por que o Kelvin nunca é negativo?'],
 f:[{f:'T<sub class="up">K</sub> = T<sub class="up">C</sub> + 273',s:[['T<sub>K</sub>','temperatura em kelvin','K'],['T<sub>C</sub>','temperatura em graus Celsius','°C']]},{f:frac('T<sub class="up">C</sub>','5')+' = '+frac('T<sub class="up">F</sub> − 32','9'),s:[['T<sub>F</sub>','temperatura em graus Fahrenheit','°F']],n:'Variações: ΔT<sub>C</sub> = ΔT<sub>K</sub>; ΔT<sub>F</sub> = 1,8·ΔT<sub>C</sub>.'}],
 ex:{q:'Converta 25 °C para Fahrenheit e para Kelvin.',s:['Kelvin: 25 + 273 = <b>298 K</b>.','Fahrenheit: 25/5 = (T<sub>F</sub> − 32)/9 → 5 = (T<sub>F</sub> − 32)/9.','T<sub>F</sub> − 32 = 45 → <b>T<sub>F</sub> = 77 °F</b>.']},
 probs:[
  ()=>{ const c=R(-40,200,5); return NUM(`Converta <b>${c} °C</b> para kelvin.`,c+273,'K',[`T<sub>K</sub> = ${c} + 273 = ${c+273} K`],[[c-273,'Para kelvin, some 273.']]); },
  ()=>{ const c=R(-20,100,5); return NUM(`Converta <b>${c} °C</b> para Fahrenheit.`,1.8*c+32,'°F',[`T<sub>F</sub> = 1,8 × ${c} + 32 = ${F(1.8*c+32)} °F`],[[1.8*c,'Faltou somar 32.'],[(c-32)*5/9,'Você fez a conversão ao contrário (de °F para °C).']]); },
  ()=>{ const f=pick([32,50,68,86,104,122,212,-4,14]); return NUM(`Um termômetro americano marca <b>${f} °F</b>. Quanto é em Celsius?`,(f-32)*5/9,'°C',[`T<sub>C</sub> = (${f} − 32) × 5/9`,`T<sub>C</sub> = ${F((f-32)*5/9)} °C`],[[(f-32)*9/5,'É ×5/9, não ×9/5.'],[f*5/9,'Faltou subtrair 32 antes.']]); },
  ()=>{ const d=R(10,50,5); return NUM(`A temperatura de um forno sobe <b>${d} °C</b>. Qual é essa variação em Fahrenheit?`,1.8*d,'°F',[`ΔT<sub>F</sub> = 1,8 × ΔT<sub>C</sub> = 1,8 × ${d} = ${F(1.8*d)} °F`],[[1.8*d+32,'Numa <b>variação</b> não se soma 32: o 32 é só um deslocamento do zero.']]); },
  POOL([['Qual é a diferença entre calor e temperatura?',['calor é energia em trânsito; temperatura mede a agitação das partículas','são a mesma coisa','temperatura é energia; calor é agitação','calor só existe em corpos quentes'],'Um corpo tem temperatura; o calor é o que flui entre corpos com temperaturas diferentes.'],['Ao encostar a mão numa barra de metal e numa de madeira à mesma temperatura, o metal parece mais frio porque:',['conduz calor mais rápido, tirando energia da mão','está mais frio','tem menos energia','a madeira produz calor'],'Estão à mesma temperatura; o metal é melhor condutor térmico.'],['O zero absoluto corresponde a:',['0 K, cerca de −273 °C','0 °C','−100 °C','0 °F'],'É a menor temperatura possível: 0 K = −273,15 °C.']])],
 traps:['Somar 32 ao converter uma variação de temperatura.','Confundir calor com temperatura.','Achar que 0 °C é o frio máximo.'],
 keep:['T<sub>K</sub> = T<sub>C</sub> + 273; T<sub>C</sub>/5 = (T<sub>F</sub> − 32)/9.','Calor é energia em trânsito, do quente para o frio.','Variação: 1 °C = 1 K = 1,8 °F.']},

{id:'dilatacao',t:'Dilatação térmica',min:12,
 idea:`<p>Aquecendo um corpo, suas partículas se agitam mais e ficam, em média, um pouco mais afastadas: o corpo <b>dilata</b>. É por isso que trilhos de trem e pontes têm frestas (juntas de dilatação), e que um pote de vidro com tampa de metal presa abre depois de passar água quente na tampa.</p>
 <p>A dilatação de um comprimento é <b>ΔL = L₀·α·ΔT</b>: proporcional ao comprimento inicial, à variação de temperatura e ao coeficiente α, próprio de cada material. Para áreas usa-se β = 2α, e para volumes γ = 3α.</p>
 <p>A água é uma exceção importante: entre 0 °C e 4 °C ela se <b>contrai</b> ao ser aquecida. Por isso o gelo flutua e os lagos congelam de cima para baixo, protegendo a vida no fundo.</p>`,
 pred:{q:'Uma placa de metal tem um furo circular. Ao aquecer a placa, o furo:',o:['aumenta','diminui','não muda','some'],a:0,why:'O furo dilata como se fosse feito do próprio metal: tudo se afasta proporcionalmente, como numa foto ampliada.'},
 lab:{sim:'dilat'},
 tasks:['Compare aço e alumínio com os mesmos 20 m e 50 °C. Qual dilata mais?','Quanto um trilho de aço de 20 m cresce do inverno (10 °C) ao verão (50 °C)?','Dobre o aquecimento: a dilatação dobra?'],
 f:[{f:'ΔL = L₀·α·ΔT',s:[['ΔL','variação do comprimento','m'],['L₀','comprimento inicial','m'],['α','coeficiente de dilatação linear','°C⁻¹'],['ΔT','variação de temperatura','°C']]},{f:'ΔA = A₀·β·ΔT   ΔV = V₀·γ·ΔT',n:'β = 2α e γ = 3α. Aço: α ≈ 12×10⁻⁶ °C⁻¹; alumínio: 23×10⁻⁶ °C⁻¹.'}],
 ex:{q:'Um trilho de aço (α = 12×10⁻⁶ °C⁻¹) mede 50 m a 20 °C. Quanto aumenta a 40 °C?',s:['ΔT = 40 − 20 = 20 °C.','ΔL = 50 × 12×10⁻⁶ × 20 = 12 000×10⁻⁶ m.','<b>ΔL = 0,012 m = 12 mm</b>.']},
 probs:[
  ()=>{ const L=R(10,100,10), a=pick([12,17,23]), dT=R(10,80,10); return NUM(`Uma barra de <b>${L} m</b> (α = ${a}×10⁻⁶ °C⁻¹) é aquecida em <b>${dT} °C</b>. Quanto ela aumenta, em <b>milímetros</b>?`,L*a*1e-6*dT*1000,'mm',[`ΔL = L₀·α·ΔT = ${L} × ${a}×10⁻⁶ × ${dT}`,`ΔL = ${F(L*a*1e-6*dT)} m = ${F(L*a*dT/1000)} mm`],[[L*a*1e-6*dT,'Esse valor está em metros. Multiplique por 1000.']]); },
  ()=>{ const L=R(1,10), dL=pick([.6,1.2,2.4]), dT=R(20,100,20); const a=dL/1000/(L*dT); return NUM(`Uma barra de <b>${L} m</b> aumenta <b>${F(dL)} mm</b> quando aquecida em <b>${dT} °C</b>. Qual é o coeficiente α? Responda multiplicado por 10⁶ (ex.: 12 para 12×10⁻⁶).`,a*1e6,'×10⁻⁶ °C⁻¹',[`α = ΔL/(L₀·ΔT) = ${F(dL/1000)}/(${L} × ${dT})`,`α = ${F(a)} °C⁻¹`],[[a*1e9,'Converta mm para m antes de dividir.']]); },
  ()=>{ const a=pick([10,12,20]), A0=R(1,5); return NUM(`Uma chapa de ${A0} m² tem α = ${a}×10⁻⁶ °C⁻¹. Qual é o coeficiente de dilatação <b>superficial</b> β? Responda multiplicado por 10⁶.`,2*a,'×10⁻⁶ °C⁻¹',[`β = 2α = 2 × ${a}×10⁻⁶ = ${2*a}×10⁻⁶ °C⁻¹`],[[3*a,'3α é o volumétrico. O superficial é 2α.'],[a,'Área tem duas dimensões: β = 2α.']]); },
  POOL([['Por que pontes têm juntas de dilatação?',['para que as partes possam se expandir sem rachar','para escoar a água da chuva','para diminuir o peso','para vibrar menos'],'No calor o concreto e o aço se expandem; sem folga, surgiriam tensões enormes.'],['Um lago no inverno congela primeiro:',['na superfície','no fundo','no meio','por igual'],'A água mais fria (perto de 0 °C) é menos densa que a de 4 °C e fica em cima; o gelo, ainda menos denso, flutua.']])],
 traps:['Esquecer de converter a resposta de metros para milímetros (ou o contrário).','Achar que um furo diminui ao aquecer.','Usar α em vez de 2α ou 3α para áreas e volumes.'],
 keep:['ΔL = L₀αΔT; β = 2α; γ = 3α.','Tudo dilata proporcionalmente, inclusive furos.','Água entre 0 e 4 °C é exceção.']},

{id:'calorimetria',t:'Calor e calorimetria',min:16,
 idea:`<p>Para aquecer 1 g de água em 1 °C é preciso 1 <b>caloria</b> (1 cal ≈ 4,2 J). Para aquecer 1 g de ferro em 1 °C, bastam 0,11 cal. Esse número é o <b>calor específico</b> c: diz quanta energia cada grama do material precisa para esquentar 1 °C. A água tem um c altíssimo, por isso o mar demora a esquentar e a esfriar.</p>
 <p>O <b>calor sensível</b> (que muda a temperatura) é <b>Q = m·c·ΔT</b>. O produto m·c é a <b>capacidade térmica</b> do corpo.</p>
 <p>Quando corpos a temperaturas diferentes são postos em contato num recipiente isolado, o calor passa do quente para o frio até todos chegarem à mesma temperatura, o <b>equilíbrio térmico</b>. Como nada se perde: <b>Q<sub>cedido</sub> + Q<sub>recebido</sub> = 0</b>, ou seja, o que um perde o outro ganha.</p>`,
 pred:{q:'Você mistura 200 g de água a 80 °C com 200 g de água a 20 °C. A temperatura final fica:',o:['50 °C','100 °C','60 °C','menos de 50 °C'],a:0,why:'Massas iguais e mesmo material: a temperatura final é a média simples, (80 + 20)/2 = 50 °C.'},
 lab:{sim:'calor'},
 tasks:['Misture massas iguais de água: a temperatura final é a média?','Troque o corpo frio por ferro, com 300 g. Por que a temperatura final fica tão perto de 80 °C?','Confira que o calor cedido é igual ao recebido.'],
 f:[{f:'Q = m·c·ΔT',s:[['Q','quantidade de calor','cal (ou J)'],['m','massa','g'],['c','calor específico (água: 1)','cal/(g·°C)'],['ΔT','variação de temperatura','°C']]},{f:'Q<sub class="up">cedido</sub> + Q<sub class="up">recebido</sub> = 0',n:'Mistura de água com água: T<sub>f</sub> = (m₁T₁ + m₂T₂)/(m₁ + m₂). 1 cal ≈ 4,2 J.'}],
 ex:{q:'Misturam-se 100 g de água a 90 °C com 300 g de água a 10 °C. Qual é a temperatura final?',s:['A quente perde: 100 × 1 × (90 − T). A fria ganha: 300 × 1 × (T − 10).','100(90 − T) = 300(T − 10) → 9000 − 100T = 300T − 3000.','400T = 12 000 → <b>T = 30 °C</b>.']},
 probs:[
  ()=>{ const m=R(100,1000,100), c=pick([1,.5,.2,.11]), dT=R(10,80,10); return NUM(`Quanto calor é preciso para aquecer <b>${m} g</b> de um material (c = ${F(c)} cal/g·°C) em <b>${dT} °C</b>?`,m*c*dT,'cal',[`Q = m·c·ΔT = ${m} × ${F(c)} × ${dT}`,`Q = ${F(m*c*dT)} cal`],[[m*dT,'Faltou multiplicar pelo calor específico.']]); },
  ()=>{ const m1=R(100,500,100), T1=R(60,90,10), m2=R(100,500,100), T2=R(10,30,10); return NUM(`Misturam-se <b>${m1} g</b> de água a <b>${T1} °C</b> com <b>${m2} g</b> de água a <b>${T2} °C</b>, num recipiente isolado. Qual é a temperatura final?`,(m1*T1+m2*T2)/(m1+m2),'°C',[`${m1}(${T1} − T) = ${m2}(T − ${T2})`,`T = (${m1}×${T1} + ${m2}×${T2})/(${m1} + ${m2}) = ${F((m1*T1+m2*T2)/(m1+m2))} °C`],[[(T1+T2)/2,'A média simples só vale para massas iguais.']]); },
  ()=>{ const m=R(1,4), dT=R(20,80,20); return NUM(`Uma chaleira aquece <b>${m} L</b> de água (${m*1000} g) de 20 °C até ${20+dT} °C. Quantas <b>quilocalorias</b> são necessárias? (c = 1 cal/g·°C)`,m*dT,'kcal',[`Q = ${m*1000} × 1 × ${dT} = ${m*1000*dT} cal`,`= ${m*dT} kcal`],[[m*1000*dT,'Esse valor está em cal. Divida por 1000.']]); },
  ()=>{ const P=pick([500,1000,2000]), m=R(500,2000,500), dT=pick([20,40,60]); const Q=m*dT*4.2; return NUM(`Um aquecedor de <b>${P} W</b> aquece <b>${m} g</b> de água em <b>${dT} °C</b>. Quanto tempo leva? (1 cal = 4,2 J; sem perdas)`,Q/P,'s',[`Q = ${m} × 1 × ${dT} = ${m*dT} cal = ${F(Q)} J`,`t = Q/P = ${F(Q)}/${P} = ${F(Q/P)} s`],[[m*dT/P,'Converta calorias para joules (×4,2) antes de dividir pela potência.']]); },
  POOL([['Por que as cidades à beira-mar têm temperaturas mais amenas?',['a água tem calor específico alto e varia pouco de temperatura','o mar é salgado','o vento do mar é frio','há menos sol no litoral'],'A água absorve e libera muito calor mudando pouco de temperatura.'],['Dois corpos em contato estão em equilíbrio térmico quando têm:',['a mesma temperatura','a mesma quantidade de calor','a mesma massa','o mesmo calor específico'],'O fluxo de calor para quando as temperaturas se igualam.']])],
 traps:['Usar a média simples quando as massas ou os materiais são diferentes.','Esquecer que ΔT é final menos inicial (o corpo que esfria tem Q negativo).','Misturar calorias e joules.'],
 keep:['Q = m·c·ΔT.','Isolado: Q<sub>cedido</sub> + Q<sub>recebido</sub> = 0.','Água: c = 1 cal/g·°C; 1 cal ≈ 4,2 J.']},

{id:'estados',t:'Mudanças de estado',min:14,
 idea:`<p>Aqueça gelo a −20 °C. A temperatura sobe até 0 °C e aí <b>para</b>, enquanto o gelo derrete, mesmo com o fogo aceso. Todo o calor está sendo usado para desfazer a estrutura do sólido, não para agitar mais as moléculas. Só quando todo o gelo vira água a temperatura volta a subir. O mesmo acontece a 100 °C, na fervura.</p>
 <p>Esse calor que muda o estado sem mudar a temperatura é o <b>calor latente</b>: <b>Q = m·L</b>. Para a água: fusão L<sub>f</sub> = 80 cal/g e vaporização L<sub>v</sub> = 540 cal/g. Ferver toda a água gasta muito mais que aquecê-la de 0 a 100 °C.</p>
 <p>A temperatura de fervura depende da pressão: em La Paz (3600 m de altitude), a água ferve a cerca de 88 °C; na panela de pressão, a mais de 100 °C, e a comida cozinha mais rápido.</p>`,
 pred:{q:'Um cubo de gelo a 0 °C recebe calor e começa a derreter. Enquanto houver gelo, a temperatura da mistura:',o:['fica em 0 °C','sobe devagar','cai','sobe rápido'],a:0,why:'Durante a mudança de estado, o calor vai todo para romper as ligações do sólido. A temperatura só volta a subir quando todo o gelo derreter.'},
 lab:{sim:'phase'},
 tasks:['Acompanhe o gráfico: quais trechos são horizontais? O que está acontecendo neles?','Qual patamar é mais longo, o de 0 °C ou o de 100 °C? Por quê?','Dobre a massa: o que acontece com a quantidade de calor em cada trecho?'],
 f:[{f:'Q = m·L',s:[['Q','calor latente','cal'],['m','massa que muda de estado','g'],['L','calor latente do material','cal/g']],n:'Água: fusão L<sub>f</sub> = 80 cal/g; vaporização L<sub>v</sub> = 540 cal/g. Gelo e vapor: c ≈ 0,5 cal/g·°C.'}],
 ex:{q:'Quanto calor é preciso para transformar 50 g de gelo a 0 °C em água a 20 °C?',s:['Derreter: Q₁ = m·L<sub>f</sub> = 50 × 80 = 4000 cal.','Aquecer a água de 0 a 20 °C: Q₂ = 50 × 1 × 20 = 1000 cal.','Total: <b>5000 cal</b>. Derreter custou 4 vezes mais que aquecer.']},
 probs:[
  ()=>{ const m=R(10,500,10); return NUM(`Quanto calor é preciso para derreter <b>${m} g</b> de gelo a 0 °C? (L<sub>f</sub> = 80 cal/g)`,m*80,'cal',[`Q = m·L = ${m} × 80 = ${m*80} cal`],[[m,'Multiplique a massa pelo calor latente.']]); },
  ()=>{ const m=R(10,200,10); return NUM(`Quanto calor é preciso para vaporizar <b>${m} g</b> de água a 100 °C? (L<sub>v</sub> = 540 cal/g)`,m*540,'cal',[`Q = m·L<sub>v</sub> = ${m} × 540 = ${m*540} cal`],[[m*100,'Esse seria o calor para aquecer de 0 a 100 °C. Vaporizar usa L<sub>v</sub> = 540.']]); },
  ()=>{ const m=R(10,100,10), T=R(10,50,10); return NUM(`Quanto calor transforma <b>${m} g</b> de gelo a 0 °C em água a <b>${T} °C</b>? (L<sub>f</sub> = 80 cal/g; c<sub>água</sub> = 1)`,m*80+m*T,'cal',[`Derreter: ${m} × 80 = ${m*80} cal`,`Aquecer: ${m} × 1 × ${T} = ${m*T} cal`,`Total: ${m*80+m*T} cal`],[[m*T,'Faltou o calor para derreter o gelo.'],[m*80,'Faltou aquecer a água depois de derreter.']]); },
  POOL([['Por que a comida cozinha mais rápido na panela de pressão?',['a pressão maior faz a água ferver acima de 100 °C','o vapor é mais pesado','a pressão empurra o calor para dentro da comida','a panela é mais grossa'],'A temperatura de ebulição sobe com a pressão.'],['Por que o suor refresca o corpo?',['a evaporação absorve calor latente da pele','o suor é frio','a água do suor tem calor específico baixo','o suor bloqueia o sol'],'Para evaporar, a água precisa de calor, que ela tira da pele.'],['No gráfico T × Q do aquecimento do gelo, um trecho horizontal indica:',['mudança de estado','que o aquecedor desligou','aquecimento do vapor','erro de medida'],'Nos patamares o calor muda o estado, e não a temperatura.']])],
 traps:['Achar que a temperatura sobe durante a fusão ou a ebulição.','Usar Q = m·c·ΔT numa mudança de estado (ΔT = 0).','Esquecer uma das etapas quando há mudança de estado e aquecimento.'],
 keep:['Durante a mudança de estado, a temperatura não muda.','Calor latente: Q = m·L.','Água: L<sub>f</sub> = 80 cal/g; L<sub>v</sub> = 540 cal/g.']},

{id:'gases',t:'Gases ideais',min:15,
 idea:`<p>Um gás é feito de partículas em movimento desordenado, batendo nas paredes do recipiente. Cada choque é um empurrão: a soma desses empurrões por área é a <b>pressão</b>. A <b>temperatura</b> (em kelvin) mede a energia de movimento das partículas.</p>
 <p>Para um gás ideal, pressão, volume e temperatura se relacionam por <b>P·V = n·R·T</b>, e, para uma mesma quantidade de gás, <b>P·V/T é constante</b>. Três casos especiais:</p>
 <ul><li><b>Isotérmica</b> (T constante): P·V constante. Apertar o êmbolo de uma seringa tampada aumenta a pressão.</li><li><b>Isobárica</b> (P constante): V/T constante. Um balão cresce no sol.</li><li><b>Isocórica</b> (V constante): P/T constante. Pneu quente fica mais cheio; lata de spray no fogo pode explodir.</li></ul>
 <p>Nas contas, a temperatura precisa estar sempre em <b>kelvin</b>.</p>`,
 pred:{q:'Um gás a 27 °C é aquecido a 327 °C, com volume constante. A pressão:',o:['dobra','fica 12 vezes maior','aumenta 300 unidades','fica igual'],a:0,why:'Em kelvin: 300 K → 600 K, o dobro. Com volume fixo, P/T é constante, então a pressão dobra. Usar Celsius daria uma resposta errada.'},
 lab:{sim:'gas'},
 tasks:['Mantenha T = 300 K e reduza o volume à metade. O que acontece com a pressão?','Mantenha V = 5 L e dobre a temperatura. E a pressão?','Mexa nos dois: a leitura P·V/T muda?'],
 f:[{f:'P·V = n·R·T      '+frac('P₁·V₁','T₁')+' = '+frac('P₂·V₂','T₂'),s:[['P','pressão','atm ou Pa'],['V','volume','L ou m³'],['T','temperatura absoluta','K'],['n','quantidade de gás','mol'],['R','constante dos gases: 0,082 atm·L/(mol·K) ou 8,31 J/(mol·K)','']]}],
 ex:{q:'Um pneu é calibrado a 30 psi numa manhã a 27 °C. Depois de rodar, os pneus chegam a 57 °C. Qual é a nova pressão (volume constante)?',s:['Temperaturas em kelvin: 300 K e 330 K.','P₂ = P₁ × T₂/T₁ = 30 × 330/300.','<b>P₂ = 33 psi</b>. Por isso se calibra o pneu frio.']},
 probs:[
  ()=>{ const P1=pick([1,2,3,4]), V1=pick([2,4,6,8,12]), k=pick([2,3,4]); return NUM(`Um gás ocupa <b>${V1} L</b> a <b>${P1} atm</b>. Comprimido lentamente, com temperatura constante, até ${F(V1/k)} L, qual será a pressão?`,P1*k,'atm',[`Isotérmica: P₁V₁ = P₂V₂`,`P₂ = ${P1} × ${V1}/${F(V1/k)} = ${P1*k} atm`],[[P1/k,'Diminuindo o volume, a pressão <b>aumenta</b>.']]); },
  ()=>{ const T1=pick([27,127,227]), k=pick([2,3]); const T2K=(T1+273)*k; return NUM(`Um recipiente fechado contém gás a <b>${T1} °C</b> e 1 atm. Até que temperatura, em °C, é preciso aquecê-lo para a pressão chegar a <b>${k} atm</b>?`,T2K-273,'°C',[`Em kelvin: T₁ = ${T1+273} K`,`P/T constante: T₂ = ${T1+273} × ${k} = ${T2K} K`,`Em Celsius: ${T2K} − 273 = ${T2K-273} °C`],[[T1*k,'Use kelvin: multiplique a temperatura absoluta e só depois volte para °C.'],[T2K,'Esse valor está em kelvin. Subtraia 273.']],'Converta para kelvin antes de fazer a proporção.'); },
  ()=>{ const V1=pick([2,3,4,5]), T1=pick([300,400]), T2=pick([450,600,900]); return NUM(`Um balão tem <b>${V1} L</b> a <b>${T1} K</b>. A pressão constante, qual será o volume a <b>${T2} K</b>?`,V1*T2/T1,'L',[`Isobárica: V/T constante`,`V₂ = ${V1} × ${T2}/${T1} = ${F(V1*T2/T1)} L`],[[V1*T1/T2,'Aquecendo, o volume <b>aumenta</b>.']]); },
  ()=>{ const n=pick([.5,1,2]), T=pick([273,300,400]), V=pick([10,20,24.6]); return NUM(`Qual é a pressão de <b>${F(n)} mol</b> de gás ideal a <b>${T} K</b> num recipiente de <b>${F(V)} L</b>? (R = 0,082 atm·L/mol·K)`,n*.082*T/V,'atm',[`P = nRT/V = ${F(n)} × 0,082 × ${T}/${F(V)}`,`P = ${F(n*.082*T/V)} atm`],[[n*.082*(T-273)/V,'A temperatura já está em kelvin.']]); },
  POOL([['Por que uma lata de spray não deve ser aquecida?',['com volume fixo, a pressão sobe com a temperatura e a lata pode explodir','o gás vira líquido','a lata dilata e vaza','o gás perde massa'],'Transformação isocórica: P/T constante.'],['A pressão de um gás vem:',['dos choques das partículas contra as paredes','do peso do gás','da temperatura em Celsius','da cor do recipiente'],'Cada choque transfere quantidade de movimento; a soma, por área, é a pressão.']])],
 traps:['Usar Celsius nas fórmulas dos gases (use kelvin).','Inverter a proporção na isotérmica (volume menor → pressão maior).','Esquecer de voltar para °C quando a pergunta pede Celsius.'],
 keep:['PV = nRT; PV/T constante.','Isotérmica: PV cte. Isobárica: V/T cte. Isocórica: P/T cte.','Temperatura sempre em kelvin.']},

{id:'termodinamica',t:'Leis da termodinâmica e máquinas',min:16,
 idea:`<p>A <b>1ª lei da termodinâmica</b> é a conservação da energia aplicada ao calor: o calor Q que um gás recebe vira aumento da energia interna ΔU ou trabalho W realizado por ele: <b>Q = ΔU + W</b>. O gás realiza trabalho quando se expande, empurrando um pistão.</p>
 <p>Uma <b>máquina térmica</b> (motor de carro, usina a vapor) recebe calor Q₁ de uma fonte quente, transforma parte em trabalho W e rejeita o resto, Q₂, para uma fonte fria. O <b>rendimento</b> é η = W/Q₁.</p>
 <p>A <b>2ª lei</b> diz que <b>nenhuma</b> máquina transforma todo o calor em trabalho: sempre sobra calor rejeitado. O limite máximo é o rendimento de Carnot, η = 1 − T<sub>f</sub>/T<sub>q</sub> (temperaturas em kelvin). Motores de carro reais aproveitam cerca de 25% a 35% da energia do combustível; o resto sai como calor pelo escapamento e pelo radiador.</p>`,
 pred:{q:'Um inventor diz ter criado um motor que transforma 100% do calor do combustível em trabalho. Isso é:',o:['impossível pela 2ª lei da termodinâmica','possível com tecnologia moderna','possível se não houver atrito','possível se o motor for elétrico'],a:0,why:'Toda máquina térmica precisa rejeitar parte do calor para uma fonte fria. Mesmo a máquina ideal de Carnot tem rendimento menor que 100%.'},
 lab:{sim:'engine'},
 tasks:['Com T<sub>q</sub> = 800 K e T<sub>f</sub> = 300 K, qual é o rendimento máximo?','O que aumenta mais o rendimento: esquentar a fonte quente ou esfriar a fria?','Para ter 100% de rendimento, qual deveria ser T<sub>f</sub>?'],
 f:[{f:'Q = ΔU + W',s:[['Q','calor recebido pelo gás','J'],['ΔU','variação da energia interna','J'],['W','trabalho realizado pelo gás','J']],n:'Isobárica: W = P·ΔV.'},{f:'η = '+frac('W','Q₁')+' = 1 − '+frac('Q₂','Q₁')+'      η<sub class="up">Carnot</sub> = 1 − '+frac('T<sub class="up">f</sub>','T<sub class="up">q</sub>'),s:[['η','rendimento',''],['Q₁','calor recebido da fonte quente','J'],['Q₂','calor rejeitado à fonte fria','J'],['T<sub>q</sub>, T<sub>f</sub>','temperaturas das fontes','K']]}],
 ex:{q:'Um motor recebe 1000 J de calor por ciclo e rejeita 700 J. Qual é o trabalho e o rendimento?',s:['W = Q₁ − Q₂ = 1000 − 700 = 300 J.','η = W/Q₁ = 300/1000.','<b>η = 0,3 = 30%</b>.']},
 probs:[
  ()=>{ const Q=R(200,1000,100), W=R(50,Q-50,50); return NUM(`Um gás recebe <b>${Q} J</b> de calor e realiza <b>${W} J</b> de trabalho. Qual é a variação da energia interna?`,Q-W,'J',[`Q = ΔU + W → ΔU = ${Q} − ${W}`,`ΔU = ${Q-W} J`],[[Q+W,'O trabalho realizado <b>sai</b> do gás: subtraia.']]); },
  ()=>{ const Q1=R(500,2000,100), W=R(100,Q1/2,50); return NUM(`Uma máquina recebe <b>${Q1} J</b> por ciclo e realiza <b>${W} J</b> de trabalho. Qual é o rendimento, em porcentagem?`,W/Q1*100,'%',[`η = W/Q₁ = ${W}/${Q1} = ${F(W/Q1)}`,`= ${F(W/Q1*100)} %`],[[W/Q1,'Converta para porcentagem (× 100).'],[(Q1-W)/Q1*100,'Essa é a fração rejeitada.']]); },
  ()=>{ const Tq=pick([400,500,600,800,1000]), Tf=pick([200,250,300]); return NUM(`Qual é o rendimento máximo (Carnot) de uma máquina que opera entre <b>${Tq} K</b> e <b>${Tf} K</b>? Responda em porcentagem.`,(1-Tf/Tq)*100,'%',[`η = 1 − T<sub>f</sub>/T<sub>q</sub> = 1 − ${Tf}/${Tq}`,`η = ${F(1-Tf/Tq)} = ${F((1-Tf/Tq)*100)} %`],[[Tf/Tq*100,'Isso é T<sub>f</sub>/T<sub>q</sub>. O rendimento é 1 menos isso.']]); },
  ()=>{ const P=pick([2e5,1e5,3e5]), dV=pick([.001,.002,.005]); return NUM(`Um gás se expande à pressão constante de <b>${F(P)} Pa</b>, aumentando o volume em <b>${F(dV)} m³</b>. Que trabalho ele realiza?`,P*dV,'J',[`W = P·ΔV = ${F(P)} × ${F(dV)}`,`W = ${F(P*dV)} J`],[[P/dV,'Trabalho é pressão <b>vezes</b> a variação de volume.']]); },
  POOL([['A geladeira tira calor de dentro e joga fora. Isso viola a 2ª lei?',['não, porque ela gasta energia elétrica (trabalho) para isso','sim, calor não pode ir do frio para o quente','não, porque o gás da geladeira é especial','sim, mas é permitido pela 1ª lei'],'Calor só flui sozinho do quente para o frio. Para inverter, é preciso realizar trabalho: é o que o compressor faz.'],['Num ciclo completo de uma máquina térmica, a variação da energia interna do gás é:',['zero','igual ao calor recebido','igual ao trabalho','negativa'],'O gás volta ao estado inicial; então ΔU = 0 e o trabalho do ciclo é Q₁ − Q₂.']])],
 traps:['Usar Celsius no rendimento de Carnot.','Achar que uma máquina sem atrito teria rendimento de 100%.','Trocar o sinal do trabalho: expansão é trabalho realizado pelo gás (W > 0).'],
 keep:['1ª lei: Q = ΔU + W.','η = W/Q₁; nenhuma máquina chega a 100%.','Carnot: η = 1 − T<sub>f</sub>/T<sub>q</sub>, em kelvin.']}]);
