/* =====================================================================
   Lições — Ondas, Óptica, Eletricidade, Magnetismo e Física moderna
   ===================================================================== */
mod('ond','Ondas','o que é uma onda, e o som',[
{id:'ondas',t:'Ondas e a equação v = λ·f',min:15,
 idea:`<p>Uma <b>onda</b> transporta energia de um lugar a outro <b>sem transportar matéria</b>. Numa "ola" no estádio, cada torcedor só levanta e senta; o que percorre a arquibancada é o movimento. Numa corda, cada ponto sobe e desce enquanto a forma da onda avança.</p>
 <p>Grandezas de uma onda: <b>amplitude</b> (altura da crista, ligada à energia), <b>comprimento de onda</b> λ (distância entre duas cristas), <b>frequência</b> f (oscilações por segundo, em Hz) e <b>período</b> T = 1/f. Em um período a onda avança um comprimento de onda, então <b>v = λ·f</b>.</p>
 <p>A velocidade depende do <b>meio</b> (tipo de corda, ar, água), não da fonte. Se a fonte vibrar mais rápido no mesmo meio, o comprimento de onda diminui. Ondas <b>mecânicas</b> (som, ondas na corda) precisam de um meio; ondas <b>eletromagnéticas</b> (luz, rádio, micro-ondas) viajam até no vácuo, a 300 000 km/s.</p>`,
 pred:{q:'Numa mesma corda esticada, você passa a balançar a ponta duas vezes mais rápido. O que acontece com o comprimento de onda?',o:['cai pela metade','dobra','fica igual','quadruplica'],a:0,why:'A velocidade depende da corda, que não mudou. Como v = λ·f, dobrar f faz λ cair pela metade.'},
 lab:{sim:'wave'},
 tasks:['Mantenha v = 4 m/s e dobre a frequência. O que acontece com λ?','Acompanhe o ponto vermelho: ele anda para a direita junto com a onda?','Mude a amplitude: a velocidade ou o comprimento de onda mudam?'],
 f:[{f:'v = λ·f      f = '+frac('1','T'),s:[['v','velocidade de propagação','m/s'],['λ','comprimento de onda','m'],['f','frequência','Hz'],['T','período','s']],n:'Luz no vácuo: c = 3×10⁸ m/s. Som no ar: cerca de 340 m/s.'}],
 ex:{q:'Uma rádio FM transmite em 100 MHz. Qual é o comprimento das ondas? (c = 3×10⁸ m/s)',s:['f = 100 MHz = 1×10⁸ Hz.','λ = c/f = 3×10⁸/1×10⁸.','<b>λ = 3 m</b>.']},
 probs:[
  ()=>{ const l=pick([.5,1,2,3,4]), f=pick([2,5,10,20,50]); return NUM(`Uma onda tem comprimento de <b>${F(l)} m</b> e frequência de <b>${f} Hz</b>. Qual é a sua velocidade?`,l*f,'m/s',[`v = λ·f = ${F(l)} × ${f} = ${F(l*f)} m/s`],[[l/f,'v = λ·f: multiplique.']]); },
  ()=>{ const f=pick([170,340,440,680,1700]); return NUM(`Um som de <b>${f} Hz</b> se propaga no ar a 340 m/s. Qual é o comprimento de onda?`,340/f,'m',[`λ = v/f = 340/${f} = ${F(340/f)} m`],[[340*f,'λ = v/f: divida.']]); },
  ()=>{ const MHz=pick([88,90,100,105,150,300]); return NUM(`Uma estação de rádio transmite em <b>${MHz} MHz</b>. Qual é o comprimento de onda? (c = 3×10⁸ m/s)`,3e8/(MHz*1e6),'m',[`f = ${MHz}×10⁶ Hz`,`λ = c/f = 3×10⁸/${MHz}×10⁶ = ${F(3e8/(MHz*1e6))} m`],[[3e8/MHz,'Converta MHz para Hz (× 10⁶).']]); },
  ()=>{ const T=pick([.1,.2,.5,2,4]); return NUM(`Uma boia sobe e desce, completando uma oscilação a cada <b>${F(T)} s</b>. Qual é a frequência das ondas?`,1/T,'Hz',[`f = 1/T = 1/${F(T)} = ${F(1/T)} Hz`],[[T,'Esse é o período. A frequência é o inverso.']]); },
  POOL([['O que uma onda transporta?',['energia, sem transportar matéria','matéria e energia','só matéria','nada; é só uma forma'],'Cada ponto do meio só oscila em torno da sua posição.'],['O som não se propaga:',['no vácuo','na água','no ferro','no ar'],'Som é onda mecânica: precisa de um meio material. No espaço, uma explosão seria silenciosa.'],['A velocidade de uma onda numa corda depende:',['da corda (tensão e densidade)','da frequência da mão','da amplitude','do comprimento de onda escolhido'],'O meio fixa a velocidade; a fonte fixa a frequência.']])],
 traps:['Achar que aumentar a frequência aumenta a velocidade da onda no mesmo meio.','Achar que a matéria viaja com a onda.','Esquecer de converter MHz ou kHz para Hz.'],
 keep:['Onda transporta energia, não matéria.','v = λ·f; f = 1/T.','A velocidade depende do meio.']},

{id:'som',t:'Som e efeito Doppler',min:14,
 idea:`<p>O som é uma onda mecânica <b>longitudinal</b>: o ar é comprimido e rarefeito na mesma direção em que a onda avança. No ar, viaja a cerca de <b>340 m/s</b>; na água, a uns 1500 m/s; no aço, a mais de 5000 m/s.</p>
 <p>Três qualidades do som: <b>altura</b> (grave ou agudo, depende da frequência; ouvimos de 20 Hz a 20 000 Hz), <b>intensidade</b> (forte ou fraco, depende da amplitude, medida em decibéis) e <b>timbre</b> (o que distingue um violão de um piano tocando a mesma nota, pela forma da onda).</p>
 <p>O <b>efeito Doppler</b> é a mudança da frequência percebida quando fonte e ouvinte se aproximam ou se afastam. A sirene da ambulância soa mais aguda chegando e mais grave indo embora: à frente da fonte as frentes de onda ficam comprimidas; atrás, espaçadas. Se a fonte ultrapassa a velocidade do som, as frentes se acumulam num cone e ouve-se o <b>estrondo sônico</b>.</p>`,
 pred:{q:'Uma ambulância passa por você com a sirene ligada. O som que você ouve:',o:['fica mais agudo chegando e mais grave indo embora','fica mais alto chegando e mais baixo indo embora, com a mesma nota','fica mais grave chegando e mais agudo indo embora','não muda'],a:0,why:'É o efeito Doppler: à frente, as frentes de onda chegam mais juntas (frequência maior, som agudo); atrás, mais espaçadas (grave).'},
 lab:{sim:'doppler'},
 tasks:['Com a fonte parada, as frentes são círculos concêntricos. O que muda quando ela anda?','Compare as frequências ouvidas à frente e atrás a 0,5 × a velocidade do som.','Passe de 1,0 × a velocidade do som. O que aparece?'],
 f:[{f:'f<sub class="up">ouvida</sub> = f·'+frac('v ± v<sub class="up">o</sub>','v ∓ v<sub class="up">f</sub>'),s:[['v','velocidade do som (340 m/s no ar)','m/s'],['v<sub>o</sub>','velocidade do ouvinte','m/s'],['v<sub>f</sub>','velocidade da fonte','m/s']],n:'Use os sinais de cima quando fonte e ouvinte se aproximam e os de baixo quando se afastam. Aproximação: som mais agudo.'},{f:'Eco: d = '+frac('v·t','2'),n:'O som vai e volta: a distância é metade do caminho total.'}],
 ex:{q:'Uma fonte de 680 Hz se aproxima de você, parado, a 40 m/s. Que frequência você ouve?',s:['Fonte se aproximando: f\' = f·v/(v − v<sub>f</sub>).','f\' = 680 × 340/(340 − 40) = 680 × 340/300.','<b>f\' ≈ 771 Hz</b>, mais agudo.']},
 probs:[
  ()=>{ const t=pick([.2,.4,.6,1,2]); return NUM(`Você grita diante de um paredão e ouve o eco <b>${F(t)} s</b> depois. A que distância está o paredão? (som: 340 m/s)`,340*t/2,'m',[`O som vai e volta: 340 × ${F(t)} = ${F(340*t)} m ida e volta`,`Distância: ${F(340*t)}/2 = ${F(340*t/2)} m`],[[340*t,'O som percorreu ida <b>e</b> volta: divida por 2.']]); },
  ()=>{ const t=pick([2,3,5,6]); return NUM(`Você vê o relâmpago e ouve o trovão <b>${t} s</b> depois. A que distância caiu o raio? (som: 340 m/s; a luz chega praticamente na hora)`,340*t,'m',[`d = v·t = 340 × ${t} = ${340*t} m`],[[340*t/2,'Aqui o som só faz a ida; não há volta.']]); },
  ()=>{ const f=pick([340,500,680,1000]), vf=pick([20,34,40,68]); return NUM(`Uma fonte de <b>${f} Hz</b> se <b>aproxima</b> de um ouvinte parado a <b>${vf} m/s</b>. Que frequência ele ouve? (v = 340 m/s)`,f*340/(340-vf),'Hz',[`f' = f·v/(v − v<sub>f</sub>) = ${f} × 340/${340-vf}`,`f' = ${F(f*340/(340-vf))} Hz`],[[f*340/(340+vf),'Aproximação dá som <b>mais agudo</b> (frequência maior).']]); },
  POOL([['O que diferencia uma nota dó tocada no piano da mesma nota no violão?',['o timbre','a frequência','a velocidade do som','o comprimento de onda'],'Mesma nota = mesma frequência. A forma da onda (harmônicos) muda: é o timbre.'],['"Abaixe o volume" pede para mudar a:',['intensidade (amplitude)','altura (frequência)','timbre','velocidade'],'Volume é intensidade. Na física, "som alto" pode querer dizer agudo.'],['O som é uma onda:',['mecânica e longitudinal','eletromagnética e transversal','mecânica e transversal','eletromagnética e longitudinal'],'Ele precisa de meio (mecânica) e o ar vibra na direção de propagação (longitudinal).']])],
 traps:['Confundir som "alto" (intenso) com som "alto" (agudo).','Esquecer de dividir por 2 no eco.','Achar que o Doppler muda o volume, e não a frequência.'],
 keep:['Altura: frequência. Intensidade: amplitude. Timbre: forma da onda.','Som no ar ≈ 340 m/s; não se propaga no vácuo.','Aproximação: mais agudo. Afastamento: mais grave.']}]);

mod('opt','Óptica','espelhos, refração e lentes',[
{id:'espelhos',t:'Reflexão e espelhos',min:16,
 idea:`<p>Na <b>reflexão</b>, a luz bate numa superfície e volta, com o ângulo de reflexão igual ao de incidência (medidos a partir da normal). Num <b>espelho plano</b>, a imagem é virtual (fica "atrás" do espelho), do mesmo tamanho e à mesma distância do espelho que o objeto.</p>
 <p>Espelhos esféricos são pedaços de uma esfera. O <b>côncavo</b> (a parte de dentro de uma colher) concentra os raios paralelos num ponto, o <b>foco</b> F. O <b>convexo</b> (a parte de fora) espalha os raios, que parecem sair de um foco atrás dele.</p>
 <p>A posição da imagem sai da equação de Gauss, <b>1/f = 1/p + 1/p'</b>, e o aumento é A = −p'/p. Côncavo: objeto longe forma imagem real e invertida; objeto entre o foco e o espelho, imagem virtual, direita e maior (espelho de maquiagem). Convexo: imagem sempre virtual, direita e menor, com campo de visão grande (retrovisor de moto, espelho de garagem).</p>`,
 pred:{q:'Por que os espelhos de segurança em garagens e lojas são convexos?',o:['mostram um campo de visão maior, com imagens menores','mostram imagens maiores','formam imagens reais','são mais baratos'],a:0,why:'O convexo sempre forma imagem virtual, direita e menor, o que permite enxergar uma área grande num espelho pequeno.'},
 lab:{sim:'mirror'},
 tasks:['No côncavo, leve o objeto de 40 cm até 2 cm. Em que ponto a imagem deixa de ser invertida?','Coloque o objeto exatamente no foco. O que acontece com os raios refletidos?','No convexo, a imagem muda de natureza em algum momento?'],
 f:[{f:frac('1','f')+' = '+frac('1','p')+' + '+frac('1','p\'')+'      A = −'+frac('p\'','p'),s:[['f','distância focal (+ côncavo, − convexo); f = R/2','cm'],['p','distância do objeto ao espelho','cm'],['p\'','distância da imagem (+ real, na frente; − virtual, atrás)','cm'],['A','aumento (+ direita, − invertida)','']]}],
 ex:{q:'Um objeto está a 30 cm de um espelho côncavo de foco 10 cm. Onde fica a imagem e como ela é?',s:['1/p\' = 1/f − 1/p = 1/10 − 1/30 = 2/30.','p\' = 15 cm (positivo: imagem real, na frente do espelho).','A = −15/30 = −0,5: <b>real, invertida e com metade do tamanho</b>.']},
 probs:[
  ()=>{ const f=pick([10,20]), p=pick([30,40,60]); const pi=1/(1/f-1/p); return NUM(`Um objeto está a <b>${p} cm</b> de um espelho côncavo com distância focal de <b>${f} cm</b>. A que distância do espelho se forma a imagem?`,pi,'cm',[`1/p' = 1/f − 1/p = 1/${f} − 1/${p}`,`p' = ${F(pi)} cm`],[[1/(1/f+1/p),'Isole 1/p\': 1/p\' = 1/f − 1/p.'],[p-f,'Use a equação de Gauss, 1/f = 1/p + 1/p\'.']]); },
  ()=>{ const f=pick([10,20]), p=pick([30,40,60]); const pi=1/(1/f-1/p); return NUM(`Um objeto está a <b>${p} cm</b> de um espelho côncavo de foco <b>${f} cm</b>. Qual é o aumento A da imagem?`,-pi/p,'',[`p' = ${F(pi)} cm`,`A = −p'/p = −${F(pi)}/${p} = ${F(-pi/p)}`],[[pi/p,'O aumento é −p\'/p: imagem real é invertida (A negativo).']]); },
  ()=>{ const d=pick([1,1.5,2,3]); return NUM(`Você está a <b>${F(d)} m</b> de um espelho plano. Qual é a distância entre você e a sua imagem?`,2*d,'m',[`A imagem fica ${F(d)} m atrás do espelho.`,`Distância total: ${F(d)} + ${F(d)} = ${F(2*d)} m`],[[d,'Essa é a distância até o espelho. A imagem fica do outro lado, à mesma distância.']]); },
  ()=>{ const R0=pick([20,40,60]); return NUM(`Um espelho esférico tem raio de curvatura <b>${R0} cm</b>. Qual é a distância focal?`,R0/2,'cm',[`f = R/2 = ${R0}/2 = ${R0/2} cm`],[[R0*2,'O foco fica no meio do caminho entre o espelho e o centro: f = R/2.']]); },
  POOL([['O espelho de maquiagem, que amplia o rosto, é:',['côncavo, com o rosto entre o foco e o espelho','convexo','plano','côncavo, com o rosto além do centro de curvatura'],'Objeto entre F e o espelho côncavo: imagem virtual, direita e ampliada.'],['A imagem num espelho plano é:',['virtual, direita e do mesmo tamanho','real e invertida','virtual e menor','real e maior'],'Também é revertida (a esquerda vira direita).'],['Um espelho convexo sempre forma imagens:',['virtuais, direitas e menores','reais e invertidas','virtuais e maiores','reais e maiores'],'É por isso que se usa em retrovisores e segurança.']])],
 traps:['Esquecer o sinal negativo do foco no espelho convexo.','Confundir p\' positivo (real) com negativo (virtual).','Esquecer que no espelho plano a imagem fica atrás, à mesma distância.'],
 keep:['1/f = 1/p + 1/p\'; A = −p\'/p; f = R/2.','Côncavo: f > 0. Convexo: f < 0, imagem sempre virtual e menor.','Espelho plano: imagem virtual, mesmo tamanho, mesma distância.']},

{id:'refracao',t:'Refração',min:15,
 idea:`<p>A luz muda de velocidade quando passa de um meio para outro: no vácuo, 300 000 km/s; na água, cerca de 225 000 km/s. O <b>índice de refração</b> n = c/v diz quantas vezes a luz fica mais lenta no meio (ar ≈ 1; água 1,33; vidro 1,5; diamante 2,42).</p>
 <p>Se a luz chega inclinada, mudar de velocidade faz o raio <b>mudar de direção</b>: é a <b>refração</b>. A lei de Snell diz quanto: <b>n₁·sen θ₁ = n₂·sen θ₂</b>. Entrando num meio mais refringente (n maior), o raio se aproxima da normal. É por isso que um lápis na água parece quebrado e a piscina parece mais rasa.</p>
 <p>Saindo de um meio mais refringente para um menos refringente, acima de um <b>ângulo limite</b> a luz não sai: toda ela reflete. É a <b>reflexão total</b>, usada nas fibras ópticas, que levam a internet pela luz. O brilho do diamante vem do seu ângulo limite pequeno.</p>`,
 pred:{q:'Um raio de luz passa do ar para a água, chegando inclinado. Ele:',o:['se aproxima da normal','se afasta da normal','segue reto, sem desviar','é totalmente refletido'],a:0,why:'A água tem índice maior que o ar: a luz fica mais lenta e, pela lei de Snell, o ângulo com a normal diminui.'},
 lab:{sim:'refr'},
 tasks:['Do ar para a água a 40°: o raio se aproxima ou se afasta da normal?','Troque para água → ar e aumente o ângulo até a luz não sair mais. Qual é o ângulo limite?','Incidência de 0° (perpendicular): o raio desvia?'],
 f:[{f:'n = '+frac('c','v')+'      n₁·sen θ₁ = n₂·sen θ₂',s:[['n','índice de refração (ar ≈ 1)',''],['c','velocidade da luz no vácuo: 3×10⁸','m/s'],['θ','ângulo com a normal','°']]},{f:'sen L = '+frac('n<sub class="up">menor</sub>','n<sub class="up">maior</sub>'),n:'Ângulo limite L: acima dele, reflexão total (só quando a luz vai do meio de n maior para o de n menor).'}],
 ex:{q:'Um raio passa do ar (n = 1) para um vidro (n = 1,5) com incidência de 30°. Qual é o ângulo de refração?',s:['1 × sen 30° = 1,5 × sen θ₂.','0,5 = 1,5 × sen θ₂ → sen θ₂ = 0,333.','<b>θ₂ ≈ 19,5°</b>: mais perto da normal.']},
 probs:[
  ()=>{ const n=pick([1.25,1.5,2,2.5]); return NUM(`Num material de índice de refração <b>${F(n)}</b>, qual é a velocidade da luz? (c = 3×10⁸ m/s)`,3e8/n,'m/s',[`v = c/n = 3×10⁸/${F(n)}`,`v = ${F(3e8/n)} m/s`],[[3e8*n,'A luz fica <b>mais lenta</b> no material: divida.']],'Digite em notação científica: 2e8.'); },
  ()=>{ const v=pick([1.5e8,2e8,2.25e8,2.4e8]); return NUM(`A luz viaja a <b>${F(v)} m/s</b> num líquido. Qual é o índice de refração dele? (c = 3×10⁸ m/s)`,3e8/v,'',[`n = c/v = 3×10⁸/${F(v)} = ${F(3e8/v)}`],[[v/3e8,'n = c/v, e é sempre maior que 1.']]); },
  ()=>{ const n2=pick([1.25,2]), s2=.5/n2; return NUM(`Um raio passa do ar (n = 1) para um meio de índice <b>${F(n2)}</b>, com incidência de 30° (sen 30° = 0,5). Qual é o <b>seno</b> do ângulo de refração?`,s2,'',[`1 × 0,5 = ${F(n2)} × sen θ₂`,`sen θ₂ = ${F(s2)}`],[[.5*n2,'n₁·sen θ₁ = n₂·sen θ₂: divida por n₂.']]); },
  ()=>{ const n=pick([2,1.25,1.6]); return NUM(`Qual é o <b>seno</b> do ângulo limite para a luz saindo de um material de índice <b>${F(n)}</b> para o ar?`,1/n,'',[`sen L = n<sub>ar</sub>/n = 1/${F(n)} = ${F(1/n)}`],[[n,'O seno não passa de 1: sen L = n<sub>menor</sub>/n<sub>maior</sub>.']]); },
  POOL([['A fibra óptica transmite luz por longas distâncias graças à:',['reflexão total','refração','difração','dispersão'],'A luz fica "presa" dentro da fibra refletindo totalmente nas paredes.'],['Uma piscina parece mais rasa do que é porque:',['a luz refrata ao sair da água, desviando-se','a água é transparente','a luz reflete no fundo','os olhos erram de perto'],'Os raios que saem da água se afastam da normal; o cérebro os prolonga em linha reta e "vê" o fundo mais alto.'],['A reflexão total pode acontecer quando a luz vai:',['da água para o ar','do ar para a água','do ar para o vidro','do vácuo para o ar'],'Só quando passa para um meio de índice menor.']])],
 traps:['Achar que a luz sempre desvia: com incidência perpendicular (0°), não desvia.','Esquecer que n é sempre maior ou igual a 1.','Achar que a reflexão total acontece indo para um meio mais refringente.'],
 keep:['n = c/v.','Snell: n₁ sen θ₁ = n₂ sen θ₂. Meio mais refringente: aproxima da normal.','Reflexão total: indo para n menor, acima do ângulo limite.']},

{id:'lentes',t:'Lentes e o olho humano',min:16,
 idea:`<p>Uma <b>lente</b> usa a refração para desviar a luz. A <b>convergente</b> (mais grossa no meio, como uma lupa) junta os raios paralelos no foco. A <b>divergente</b> (mais fina no meio) os espalha.</p>
 <p>A equação é a mesma dos espelhos, <b>1/f = 1/p + 1/p'</b>, com f positivo para convergente e negativo para divergente. Na lente, imagem real (p' > 0) forma-se do <b>outro lado</b>. A <b>vergência</b> V = 1/f (f em metros) é o "grau" dos óculos, em dioptrias (di).</p>
 <p>O olho é um sistema convergente que forma na retina uma imagem real e invertida (o cérebro desvira). Na <b>miopia</b>, a imagem de objetos distantes se forma antes da retina: corrige-se com lente divergente (grau negativo). Na <b>hipermetropia</b>, forma-se depois: lente convergente (grau positivo).</p>`,
 pred:{q:'Uma lupa (lente convergente) só aumenta a imagem de uma formiga se a formiga estiver:',o:['entre a lente e o foco','exatamente no foco','muito longe, além do dobro do foco','em qualquer posição'],a:0,why:'Com o objeto entre a lente e o foco, a imagem é virtual, direita e ampliada. Longe da lente, a imagem vira real e invertida (é o que a câmera faz).'},
 lab:{sim:'lens'},
 tasks:['Na convergente, leve o objeto de 40 cm até 2 cm. Onde a imagem vira virtual?','Coloque o objeto a 20 cm (o dobro do foco de 10 cm). Como fica o tamanho da imagem?','Na divergente, a imagem muda de natureza em algum momento?'],
 f:[{f:frac('1','f')+' = '+frac('1','p')+' + '+frac('1','p\'')+'      A = −'+frac('p\'','p')+'      V = '+frac('1','f'),s:[['f','distância focal (+ convergente, − divergente)','cm'],['p\'','posição da imagem (+ real, do outro lado; − virtual, do mesmo lado)','cm'],['V','vergência ("grau"), com f em metros','di']],n:'Óculos de −2 di têm f = −0,5 m: lente divergente, para miopia.'}],
 ex:{q:'Um projetor usa uma lente convergente de f = 10 cm, com o slide a 10,5 cm dela. A que distância fica a tela?',s:['1/p\' = 1/10 − 1/10,5 = (10,5 − 10)/105 = 0,5/105.','p\' = 210 cm = 2,1 m (real, do outro lado).','A = −210/10,5 = −20: imagem 20 vezes maior e invertida (por isso o slide entra de cabeça para baixo).']},
 probs:[
  ()=>{ const f=pick([10,20]), p=pick([30,40,60]); const pi=1/(1/f-1/p); return NUM(`Um objeto está a <b>${p} cm</b> de uma lente convergente de foco <b>${f} cm</b>. A que distância da lente se forma a imagem?`,pi,'cm',[`1/p' = 1/${f} − 1/${p}`,`p' = ${F(pi)} cm (imagem real, do outro lado)`],[[1/(1/f+1/p),'Isole 1/p\' = 1/f − 1/p.']]); },
  ()=>{ const f=pick([-.25,-.5,-1,.25,.5,2]); return NUM(`Uma lente tem distância focal de <b>${F(f*100)} cm</b>. Qual é a vergência (o "grau")?`,1/f,'di',[`f = ${F(f)} m`,`V = 1/f = 1/${F(f)} = ${F(1/f)} di`],[[1/(f*100),'Use f em metros.'],[-1/f,'Mantenha o sinal: divergente tem grau negativo.']]); },
  ()=>{ const V=pick([-4,-2,-1,1,2,4]); return NUM(`Uns óculos têm <b>${V>0?'+':''}${V} di</b>. Qual é a distância focal da lente, em centímetros?`,100/V,'cm',[`f = 1/V = 1/${V} m = ${F(1/V)} m`,`= ${F(100/V)} cm`],[[1/V,'Esse valor está em metros.']]); },
  ()=>{ const f=10, p=pick([4,5,8]); const pi=1/(1/f-1/p); return NUM(`Uma lupa de foco <b>10 cm</b> observa um selo a <b>${p} cm</b>. Qual é o aumento da imagem?`,-pi/p,'',[`p' = 1/(1/10 − 1/${p}) = ${F(pi)} cm (virtual)`,`A = −p'/p = ${F(-pi/p)}`],[[pi/p,'A = −p\'/p; como p\' é negativo, A fica positivo (imagem direita).']]); },
  POOL([['Uma pessoa míope enxerga mal de longe. Ela usa lentes:',['divergentes (grau negativo)','convergentes (grau positivo)','cilíndricas apenas','sem grau'],'No míope a imagem se forma antes da retina; a lente divergente empurra o foco para trás.'],['A imagem formada na retina é:',['real e invertida','virtual e direita','real e direita','virtual e invertida'],'O cristalino é convergente e forma imagem real e invertida; o cérebro interpreta.'],['Uma lente divergente sempre forma, de um objeto real, imagem:',['virtual, direita e menor','real e invertida','virtual e maior','real e maior'],'Como o espelho convexo.']])],
 traps:['Esquecer que na lente a imagem real fica do outro lado.','Usar f em centímetros na vergência (tem de ser em metros).','Trocar a correção: miopia usa divergente; hipermetropia, convergente.'],
 keep:['1/f = 1/p + 1/p\'; convergente f > 0, divergente f < 0.','V = 1/f (m) em dioptrias.','Miopia: divergente. Hipermetropia: convergente.']}]);

mod('ele','Eletricidade','cargas, campos, corrente e circuitos',[
{id:'coulomb',t:'Carga elétrica e lei de Coulomb',min:15,
 idea:`<p>A matéria é feita de átomos com prótons (carga +), elétrons (carga −) e nêutrons (sem carga). Normalmente o número de prótons e elétrons é igual e o corpo é <b>neutro</b>. Um corpo fica <b>eletrizado</b> quando ganha elétrons (fica negativo) ou perde elétrons (fica positivo). A carga de um elétron é e = 1,6×10⁻¹⁹ C.</p>
 <p>Cargas de <b>mesmo sinal se repelem</b>; de <b>sinais opostos se atraem</b>. A força segue a <b>lei de Coulomb</b>, F = k·|q₁·q₂|/d², muito parecida com a gravitação: também cai com o quadrado da distância. A constante k vale 9×10⁹ N·m²/C², um número enorme: a força elétrica é muito mais forte que a gravitacional.</p>
 <p>Eletrizamos corpos por <b>atrito</b> (pentear o cabelo seco), <b>contato</b> (esferas iguais que se tocam dividem a carga) e <b>indução</b> (aproximar um corpo carregado separa as cargas de outro).</p>`,
 pred:{q:'Duas cargas se atraem com força F. Se a distância entre elas dobrar, a força fica:',o:['F/4','F/2','2F','4F'],a:0,why:'Pela lei de Coulomb, F ∝ 1/d². Dobrar a distância divide a força por 2² = 4.'},
 lab:{sim:'coulomb'},
 tasks:['Coloque cargas de mesmo sinal e depois de sinais opostos. O que muda nas setas?','Dobre a distância. A força fica quantas vezes menor?','A força numa carga maior é maior que na menor?'],
 f:[{f:'F = k·'+frac('|q₁·q₂|','d²'),s:[['k','constante eletrostática: 9×10⁹','N·m²/C²'],['q₁, q₂','cargas','C'],['d','distância entre as cargas','m']],n:'1 μC = 10⁻⁶ C. Q = n·e, com e = 1,6×10⁻¹⁹ C.'}],
 ex:{q:'Duas cargas de 2 μC e 3 μC estão a 30 cm. Qual é a força entre elas?',s:['F = 9×10⁹ × (2×10⁻⁶)(3×10⁻⁶)/(0,3)².','F = 9×10⁹ × 6×10⁻¹² / 0,09 = 54×10⁻³/0,09.','<b>F = 0,6 N</b> (repulsão, pois as duas são positivas).']},
 probs:[
  ()=>{ const q1=R(1,5), q2=R(1,5), d=pick([.1,.2,.3,.5]); const Fo=9e9*q1*q2*1e-12/(d*d); return NUM(`Duas cargas de <b>${q1} μC</b> e <b>${q2} μC</b> estão a <b>${F(d)} m</b> uma da outra. Qual é o módulo da força entre elas? (k = 9×10⁹)`,Fo,'N',[`F = 9×10⁹ × ${q1}×10⁻⁶ × ${q2}×10⁻⁶ / ${F(d)}²`,`F = ${F(Fo)} N`],[[9e9*q1*q2*1e-12/d,'Faltou elevar a distância ao quadrado.'],[9e9*q1*q2/(d*d),'Converta μC para C (× 10⁻⁶).']],'1 μC = 10⁻⁶ C.'); },
  ()=>{ const k=pick([2,3,4]), F0=R(10,90,10); return NUM(`A força entre duas cargas é <b>${F0} N</b>. Se a distância for dividida por <b>${k}</b>, qual será a nova força?`,F0*k*k,'N',[`F ∝ 1/d²: com d ÷ ${k}, F × ${k*k}`,`F = ${F0*k*k} N`],[[F0*k,'A distância entra ao quadrado.'],[F0/(k*k),'Com as cargas mais próximas, a força <b>aumenta</b>.']]); },
  ()=>{ const n=pick([1e12,5e12,2e13,6.25e18]); return NUM(`Um corpo perde <b>${F(n)}</b> elétrons. Qual é a sua carga? (e = 1,6×10⁻¹⁹ C)`,n*1.6e-19,'C',[`Q = n·e = ${F(n)} × 1,6×10⁻¹⁹`,`Q = ${F(n*1.6e-19)} C (positiva, pois perdeu elétrons)`],[[n/1.6e-19,'Multiplique o número de elétrons pela carga de cada um.']],'Digite em notação científica: 1.6e-7.'); },
  ()=>{ const a=R(2,10,2), b=R(-6,6,2); return NUM(`Duas esferas metálicas idênticas, com cargas de <b>${a} μC</b> e <b>${b} μC</b>, se tocam e se separam. Qual é a carga de cada uma depois?`,(a+b)/2,'μC',[`No contato, as esferas idênticas dividem a carga total igualmente.`,`(${a} + (${b}))/2 = ${F((a+b)/2)} μC`],[[a+b,'Essa é a carga total. Ela se divide entre as duas.']]); },
  POOL([['Um corpo neutro fica positivo quando:',['perde elétrons','ganha prótons','ganha elétrons','perde nêutrons'],'Os prótons ficam presos no núcleo; o que se transfere são elétrons.'],['Um pente atritado no cabelo atrai pedacinhos de papel neutros por:',['indução: as cargas do papel se separam','contato','o papel já estar carregado','gravidade'],'O pente carregado induz uma separação de cargas no papel; o lado mais próximo, de sinal oposto, é atraído com mais força.'],['Duas cargas negativas próximas:',['se repelem','se atraem','não interagem','se anulam'],'Sinais iguais se repelem.']])],
 traps:['Esquecer de converter μC para C.','Esquecer de elevar a distância ao quadrado.','Achar que um corpo fica positivo por ganhar prótons.'],
 keep:['Sinais iguais: repulsão. Opostos: atração.','F = k|q₁q₂|/d², com k = 9×10⁹.','Eletrizar é transferir elétrons.']},

{id:'campo',t:'Campo e potencial elétrico',min:15,
 idea:`<p>Uma carga "altera" o espaço à sua volta: qualquer outra carga colocada ali sente uma força. Essa alteração é o <b>campo elétrico</b> E, a força por unidade de carga: E = F/q. Ele aponta para fora das cargas positivas e para dentro das negativas. Uma carga positiva colocada no campo é empurrada no sentido de E; uma negativa, no sentido contrário.</p>
 <p>Para uma carga pontual, E = k·Q/d². O <b>potencial elétrico</b> V mede a energia por unidade de carga: V = k·Q/d, em volts. A diferença de potencial (a "tensão") entre dois pontos é o que empurra as cargas: o trabalho para levar uma carga q entre eles é W = q·(V<sub>A</sub> − V<sub>B</sub>).</p>
 <p>Entre duas placas paralelas carregadas, o campo é <b>uniforme</b>: E = U/d. É o que acontece dentro de um capacitor.</p>`,
 pred:{q:'Um elétron é colocado num campo elétrico que aponta para a direita. A força sobre ele aponta:',o:['para a esquerda','para a direita','para cima','não há força'],a:0,why:'O campo indica a força numa carga positiva. O elétron é negativo, então é empurrado no sentido contrário.'},
 lab:{sim:'field'},
 tasks:['Arraste a sonda para perto da carga positiva: para onde aponta o campo?','Coloque as duas cargas com o mesmo sinal. O que acontece no ponto entre elas?','Onde o campo é mais forte? Onde as setas estão mais escuras.'],
 f:[{f:'E = '+frac('F','q')+' = k·'+frac('Q','d²')+'      V = k·'+frac('Q','d'),s:[['E','campo elétrico','N/C'],['V','potencial elétrico','V (volt)'],['Q','carga que cria o campo','C'],['d','distância até a carga','m']]},{f:'W = q·U      E = '+frac('U','d')+'  (placas paralelas)',s:[['U','diferença de potencial (tensão)','V']]}],
 ex:{q:'Qual é o campo elétrico a 30 cm de uma carga de 2 μC? E a força numa carga de 1 μC ali?',s:['E = 9×10⁹ × 2×10⁻⁶ / 0,3² = 18×10³/0,09.','<b>E = 2×10⁵ N/C</b>, apontando para fora da carga.','F = q·E = 1×10⁻⁶ × 2×10⁵ = <b>0,2 N</b>.']},
 probs:[
  ()=>{ const Q=R(1,5), d=pick([.1,.3,.5,1]); const E=9e9*Q*1e-6/(d*d); return NUM(`Qual é a intensidade do campo elétrico a <b>${F(d)} m</b> de uma carga de <b>${Q} μC</b>? (k = 9×10⁹)`,E,'N/C',[`E = k·Q/d² = 9×10⁹ × ${Q}×10⁻⁶ / ${F(d)}²`,`E = ${F(E)} N/C`],[[9e9*Q*1e-6/d,'Isso é o potencial (k·Q/d). O campo usa d².']],'Digite em notação científica: 2e5.'); },
  ()=>{ const E=pick([1e3,5e3,2e4,1e5]), q=pick([2,3,5]); return NUM(`Uma carga de <b>${q} μC</b> está num campo de <b>${F(E)} N/C</b>. Qual é a força sobre ela?`,q*1e-6*E,'N',[`F = q·E = ${q}×10⁻⁶ × ${F(E)}`,`F = ${F(q*1e-6*E)} N`],[[q*E,'Converta μC para C.']]); },
  ()=>{ const U=pick([12,100,220,1000]), q=pick([1,2,5]); return NUM(`Qual é o trabalho para levar uma carga de <b>${q} μC</b> entre dois pontos com diferença de potencial de <b>${U} V</b>?`,q*1e-6*U,'J',[`W = q·U = ${q}×10⁻⁶ × ${U}`,`W = ${F(q*1e-6*U)} J`],[[q*U,'Converta μC para C.']]); },
  ()=>{ const U=pick([100,200,500,1000]), d=pick([.01,.02,.05]); return NUM(`Duas placas paralelas separadas por <b>${F(d*100)} cm</b> estão ligadas a <b>${U} V</b>. Qual é o campo entre elas?`,U/d,'V/m',[`d = ${F(d)} m`,`E = U/d = ${U}/${F(d)} = ${F(U/d)} V/m (= N/C)`],[[U/(d*100),'Use a distância em metros.']]); },
  POOL([['As linhas de campo elétrico:',['saem das cargas positivas e chegam às negativas','saem das negativas e chegam às positivas','formam círculos em volta das cargas','só existem entre cargas iguais'],'Por convenção, o campo aponta como a força numa carga positiva de teste.'],['Dentro de um condutor metálico em equilíbrio, o campo elétrico é:',['zero','máximo','igual ao de fora','infinito'],'As cargas livres se reorganizam na superfície até anular o campo interno (blindagem, como na gaiola de Faraday).']])],
 traps:['Confundir campo (k·Q/d²) com potencial (k·Q/d).','Esquecer que carga negativa sente força contra o campo.','Esquecer de converter μC e cm.'],
 keep:['E = F/q = kQ/d² (vetor).','V = kQ/d (escalar); W = q·U.','Placas paralelas: E = U/d.']},

{id:'ohm',t:'Corrente elétrica e lei de Ohm',min:15,
 idea:`<p><b>Corrente elétrica</b> é o movimento ordenado de cargas. Num fio metálico, são elétrons empurrados pela tensão da pilha ou da tomada. A intensidade é a quantidade de carga que passa por segundo: <b>i = Q/Δt</b>, em ampères (1 A = 1 C/s).</p>
 <p>A <b>tensão</b> (ddp) U, em volts, é o "empurrão" que faz a corrente circular. A <b>resistência</b> R, em ohms (Ω), é a dificuldade que o material oferece. A <b>lei de Ohm</b> relaciona as três: <b>U = R·i</b>. Mesma tensão com resistência maior dá corrente menor.</p>
 <p>A resistência de um fio depende do material, do comprimento e da espessura: R = ρ·L/A. Fios longos e finos resistem mais; é por isso que o fio do chuveiro é grosso. Na resistência, energia elétrica vira calor (<b>efeito Joule</b>): chuveiro, ferro de passar e torradeira funcionam assim.</p>`,
 pred:{q:'Uma lâmpada ligada a uma bateria de 12 V tem resistência de 6 Ω. Trocando por uma de 12 Ω na mesma bateria, a corrente:',o:['cai pela metade','dobra','fica igual','quadruplica'],a:0,why:'i = U/R: com a mesma tensão e o dobro da resistência, a corrente cai pela metade.'},
 lab:{sim:'ohm'},
 tasks:['Com R = 20 Ω, dobre a tensão. O que acontece com a corrente?','Mantenha 12 V e aumente R. O que muda na velocidade das bolinhas?','O gráfico U × I é uma reta. O que a inclinação dela representa?'],
 f:[{f:'i = '+frac('Q','Δt')+'      U = R·i',s:[['i','corrente elétrica','A (ampère)'],['Q','carga','C'],['U','tensão (diferença de potencial)','V (volt)'],['R','resistência','Ω (ohm)']]},{f:'R = ρ·'+frac('L','A'),s:[['ρ','resistividade do material','Ω·m'],['L','comprimento do fio','m'],['A','área da seção do fio','m²']]}],
 ex:{q:'Um resistor de 20 Ω é ligado a 12 V. Qual é a corrente, e quanta carga passa por ele em 1 minuto?',s:['i = U/R = 12/20 = 0,6 A.','Q = i·Δt = 0,6 × 60.','<b>Q = 36 C</b>.']},
 probs:[
  ()=>{ const R0=pick([2,4,5,10,20,40,100]), i=pick([.5,1,1.5,2,3]); return NUM(`Um resistor de <b>${R0} Ω</b> é percorrido por <b>${F(i)} A</b>. Qual é a tensão nele?`,R0*i,'V',[`U = R·i = ${R0} × ${F(i)} = ${F(R0*i)} V`],[[R0/i,'U = R·i: multiplique.']]); },
  ()=>{ const U=pick([6,9,12,24,110,220]), R0=pick([2,3,4,6,10,20,50]); return NUM(`Um aparelho de <b>${R0} Ω</b> é ligado a <b>${U} V</b>. Qual é a corrente?`,U/R0,'A',[`i = U/R = ${U}/${R0} = ${F(U/R0)} A`],[[U*R0,'i = U/R: divida.'],[R0/U,'É tensão dividida por resistência.']]); },
  ()=>{ const i=pick([.5,2,4,10]), t=pick([10,30,60,120]); return NUM(`Uma corrente de <b>${F(i)} A</b> passa por um fio durante <b>${t} s</b>. Quanta carga atravessa o fio?`,i*t,'C',[`Q = i·Δt = ${F(i)} × ${t} = ${F(i*t)} C`],[[i/t,'Q = i·Δt: multiplique.']]); },
  ()=>{ const R0=pick([10,20,40]); return NUM(`Um fio tem resistência de <b>${R0} Ω</b>. Outro fio, do mesmo material e comprimento, mas com o <b>dobro da área</b> da seção, tem que resistência?`,R0/2,'Ω',[`R = ρL/A: com A dobrada, R cai pela metade`,`R = ${R0/2} Ω`],[[R0*2,'Fio mais grosso resiste <b>menos</b>.']]); },
  POOL([['Por que o fio do chuveiro elétrico é mais grosso que o de uma lâmpada?',['precisa conduzir corrente maior com menos resistência e aquecimento','fica mais bonito','o chuveiro usa tensão menor','para isolar a água'],'R = ρL/A: fio grosso resiste menos e esquenta menos com a corrente alta.'],['Num fio metálico, quem se move para formar a corrente são:',['os elétrons livres','os prótons','os núcleos dos átomos','os nêutrons'],'Os núcleos ficam presos na rede do metal; os elétrons livres se deslocam.'],['O efeito Joule é:',['a transformação de energia elétrica em calor num resistor','a atração entre fios','a criação de carga elétrica','o brilho de uma lâmpada LED'],'É o princípio de aquecedores, chuveiros e fusíveis.']])],
 traps:['Inverter a lei de Ohm: i = U/R, não U/R = i·R.','Achar que a corrente "se gasta" ao passar por um resistor (a mesma corrente entra e sai).','Achar que fio grosso resiste mais.'],
 keep:['i = Q/Δt (A); U = R·i.','R = ρL/A: longo e fino resiste mais.','Efeito Joule: energia elétrica vira calor.']},

{id:'resistores',t:'Associação de resistores',min:16,
 idea:`<p>Resistores podem ser ligados de dois jeitos:</p>
 <ul><li><b>Em série</b>, um depois do outro, num único caminho: a <b>mesma corrente</b> passa por todos, e as tensões se somam. R<sub>eq</sub> = R₁ + R₂ + R₃. Se um queimar, o circuito abre e tudo apaga (como pisca-piscas antigos).</li><li><b>Em paralelo</b>, lado a lado, cada um ligado direto aos mesmos dois pontos: todos têm a <b>mesma tensão</b>, e as correntes se somam. 1/R<sub>eq</sub> = 1/R₁ + 1/R₂ + 1/R₃. A resistência equivalente é <b>menor</b> que a menor delas. É assim a instalação da sua casa: cada aparelho recebe 127 V ou 220 V e funciona independente dos outros.</li></ul>
 <p>Para dois resistores em paralelo existe um atalho: R<sub>eq</sub> = R₁·R₂/(R₁ + R₂). Com n resistores iguais em paralelo, R<sub>eq</sub> = R/n.</p>`,
 pred:{q:'Na sua casa, ligar mais aparelhos na mesma instalação faz a corrente total que vem da rua:',o:['aumentar','diminuir','ficar igual','zerar'],a:0,why:'Os aparelhos estão em paralelo: cada novo aparelho abre mais um caminho para a corrente, e a resistência equivalente diminui. É por isso que ligar tudo ao mesmo tempo pode desarmar o disjuntor.'},
 lab:{sim:'resist'},
 tasks:['Em série, compare a corrente em cada resistor. E as tensões?','Troque para paralelo com os mesmos valores. A resistência equivalente fica maior ou menor que 10 Ω?','Em paralelo, qual resistor recebe mais corrente: o de maior ou o de menor resistência?'],
 f:[{f:'Série: R<sub class="up">eq</sub> = R₁ + R₂ + R₃',n:'Mesma corrente em todos; U = U₁ + U₂ + U₃.'},{f:'Paralelo: '+frac('1','R<sub class="up">eq</sub>')+' = '+frac('1','R₁')+' + '+frac('1','R₂')+' + '+frac('1','R₃'),n:'Mesma tensão em todos; i = i₁ + i₂ + i₃. Dois em paralelo: R₁R₂/(R₁ + R₂). n iguais: R/n.'}],
 ex:{q:'Resistores de 6 Ω e 3 Ω são ligados em paralelo a 12 V. Qual é a corrente total?',s:['R<sub>eq</sub> = 6 × 3/(6 + 3) = 18/9 = 2 Ω.','i = U/R<sub>eq</sub> = 12/2 = <b>6 A</b>.','Confira: 12/6 = 2 A e 12/3 = 4 A; 2 + 4 = 6 A.']},
 probs:[
  ()=>{ const a=R(2,20), b=R(2,20), c=R(2,20); return NUM(`Três resistores de <b>${a} Ω</b>, <b>${b} Ω</b> e <b>${c} Ω</b> estão em série. Qual é a resistência equivalente?`,a+b+c,'Ω',[`R<sub>eq</sub> = ${a} + ${b} + ${c} = ${a+b+c} Ω`],[[1/(1/a+1/b+1/c),'Essa seria a ligação em paralelo. Em série, some.']]); },
  ()=>{ const [a,b]=pick([[6,3],[4,4],[12,6],[10,40],[20,30],[2,6]]); return NUM(`Dois resistores de <b>${a} Ω</b> e <b>${b} Ω</b> estão em paralelo. Qual é a resistência equivalente?`,a*b/(a+b),'Ω',[`R<sub>eq</sub> = R₁R₂/(R₁ + R₂) = ${a*b}/${a+b}`,`R<sub>eq</sub> = ${F(a*b/(a+b))} Ω`],[[a+b,'Somar é para série. Em paralelo, o resultado é menor que o menor resistor.']]); },
  ()=>{ const R0=pick([10,20,30,60]), n=pick([2,3,4]); return NUM(`<b>${n} lâmpadas iguais</b> de <b>${R0} Ω</b> estão em paralelo. Qual é a resistência equivalente?`,R0/n,'Ω',[`n iguais em paralelo: R/n = ${R0}/${n} = ${F(R0/n)} Ω`],[[R0*n,'Em paralelo a resistência <b>diminui</b>.']]); },
  ()=>{ const a=R(2,10), b=R(2,10), U=pick([12,24,36]); return NUM(`Resistores de <b>${a} Ω</b> e <b>${b} Ω</b>, em série, são ligados a <b>${U} V</b>. Qual é a tensão no resistor de ${a} Ω?`,U*a/(a+b),'V',[`i = ${U}/(${a} + ${b}) = ${F(U/(a+b))} A`,`U₁ = R₁·i = ${a} × ${F(U/(a+b))} = ${F(U*a/(a+b))} V`],[[U,'Em série a tensão se <b>divide</b> entre os resistores.']]); },
  POOL([['Numa ligação em série, se uma lâmpada queima:',['todas apagam','só ela apaga','as outras brilham mais','nada muda'],'Série tem um único caminho: interrompido, não há corrente.'],['Em paralelo, o resistor que recebe maior corrente é o de:',['menor resistência','maior resistência','todos recebem a mesma','depende da ordem'],'Mesma tensão: i = U/R, maior para R menor.'],['A resistência equivalente de resistores em paralelo é:',['menor que a menor delas','maior que a maior delas','igual à média','igual à soma'],'Cada resistor a mais é um caminho a mais.']])],
 traps:['Somar resistências em paralelo.','Achar que em série cada resistor recebe a tensão total.','Esquecer de inverter no final ao usar 1/R<sub>eq</sub>.'],
 keep:['Série: mesma corrente; R<sub>eq</sub> = soma.','Paralelo: mesma tensão; R<sub>eq</sub> menor que o menor.','Dois em paralelo: R₁R₂/(R₁ + R₂).']},

{id:'potencia',t:'Potência elétrica e consumo',min:14,
 idea:`<p>A <b>potência elétrica</b> diz quanta energia um aparelho usa por segundo: <b>P = U·i</b>, em watts. Combinando com a lei de Ohm, também P = R·i² = U²/R. Um chuveiro de 5500 W em 220 V puxa i = 5500/220 = 25 A.</p>
 <p>A conta de luz não cobra potência, e sim <b>energia</b>: E = P·Δt. Como o joule é uma unidade pequena, as distribuidoras usam o <b>quilowatt-hora</b> (kWh): a energia de um aparelho de 1000 W ligado por 1 hora. 1 kWh = 3,6×10⁶ J.</p>
 <p>Para economizar, olhe para potência <b>e</b> tempo: um chuveiro de 5500 W por 15 minutos por dia gasta mais que uma geladeira de 150 W, que fica ligada o dia todo? Faça a conta no laboratório.</p>`,
 pred:{q:'Em um mês, o que gasta mais energia: um chuveiro de 5500 W usado 30 minutos por dia ou uma lâmpada LED de 9 W acesa 6 horas por dia?',o:['o chuveiro, cerca de 150 vezes mais','a lâmpada, porque fica mais tempo ligada','os dois gastam igual','depende da tensão da casa'],a:0,why:'Chuveiro: 5,5 kW × 0,5 h × 30 = 82,5 kWh. Lâmpada: 0,009 kW × 6 h × 30 = 1,62 kWh. A potência do chuveiro é enorme.'},
 lab:{sim:'consumo'},
 tasks:['Quantas horas por dia de ar-condicionado gastam o mesmo que o chuveiro por meia hora?','Com a tarifa de R$ 0,85/kWh, quanto custa por mês um banho diário de 30 min?','Por que a geladeira, ligada 24 h, gasta menos que o chuveiro?'],
 f:[{f:'P = U·i = R·i² = '+frac('U²','R'),s:[['P','potência','W'],['U','tensão','V'],['i','corrente','A']]},{f:'E = P·Δt',s:[['E','energia consumida','kWh (ou J)'],['Δt','tempo de uso','h (ou s)']],n:'Com P em kW e Δt em h, E sai em kWh. 1 kWh = 3,6×10⁶ J.'}],
 ex:{q:'Um ferro de passar de 1000 W é usado 2 h por semana. Quanto custa por mês (4 semanas), com tarifa de R$ 0,80/kWh?',s:['Tempo no mês: 2 × 4 = 8 h.','E = 1 kW × 8 h = 8 kWh.','Custo: 8 × 0,80 = <b>R$ 6,40</b>.']},
 probs:[
  ()=>{ const U=pick([127,220]), i=pick([2,5,10,20,25]); return NUM(`Um aparelho ligado a <b>${U} V</b> puxa <b>${i} A</b>. Qual é a potência?`,U*i,'W',[`P = U·i = ${U} × ${i} = ${U*i} W`],[[U/i,'P = U·i: multiplique.']]); },
  ()=>{ const P=pick([1100,2200,4400,5500,6600]), U=220; return NUM(`Um chuveiro de <b>${P} W</b> funciona em <b>${U} V</b>. Qual é a corrente?`,P/U,'A',[`i = P/U = ${P}/${U} = ${F(P/U)} A`],[[P*U,'i = P/U: divida.']]); },
  ()=>{ const P=pick([100,500,1000,1500,2000,5500]), h=pick([.5,1,2,4,8]), d=30; return NUM(`Um aparelho de <b>${P} W</b> fica ligado <b>${F(h)} h por dia</b>. Quanta energia consome em 30 dias?`,P/1000*h*d,'kWh',[`P = ${F(P/1000)} kW`,`E = ${F(P/1000)} × ${F(h)} × 30 = ${F(P/1000*h*d)} kWh`],[[P*h*d,'Esse valor está em Wh. Divida por 1000 para kWh.']]); },
  ()=>{ const E=pick([50,100,150,200,300]), t=pick([.6,.7,.8,.9]); return NUM(`Uma casa consumiu <b>${E} kWh</b> no mês, com tarifa de <b>R$ ${F(t)}</b> por kWh. Quanto é a conta (sem impostos)?`,E*t,'reais',[`Custo = ${E} × ${F(t)} = R$ ${F(E*t)}`],[[E/t,'Multiplique a energia pela tarifa.']]); },
  ()=>{ const R0=pick([10,20,50]), i=pick([2,3,5]); return NUM(`Um resistor de <b>${R0} Ω</b> é percorrido por <b>${i} A</b>. Qual é a potência dissipada?`,R0*i*i,'W',[`P = R·i² = ${R0} × ${i}² = ${R0*i*i} W`],[[R0*i,'Faltou elevar a corrente ao quadrado.']]); },
  POOL([['O que a conta de luz cobra?',['energia (kWh)','potência (W)','corrente (A)','tensão (V)'],'kWh é unidade de energia: potência vezes tempo.'],['Um chuveiro com a chave em "inverno" esquenta mais porque:',['tem resistência menor, e P = U²/R fica maior','tem resistência maior','usa tensão maior','puxa menos corrente'],'Com a mesma tensão, menos resistência → mais corrente → mais potência.']])],
 traps:['Confundir potência (W) com energia (kWh).','Esquecer de converter W para kW antes de calcular kWh.','Achar que resistência maior sempre aquece mais (com tensão fixa, é o contrário).'],
 keep:['P = U·i = R·i² = U²/R.','E = P·Δt; kW × h = kWh.','Conta de luz = kWh × tarifa.']}]);

mod('mag','Magnetismo','ímãs, forças magnéticas e indução',[
{id:'magnetismo',t:'Campo magnético e força magnética',min:15,
 idea:`<p>Ímãs têm dois polos, <b>norte</b> e <b>sul</b>: polos iguais se repelem, diferentes se atraem. Quebrar um ímã ao meio não separa os polos: cada pedaço vira um ímã completo. A Terra é um grande ímã, e a bússola aponta ao longo do campo magnético dela.</p>
 <p>Oersted descobriu em 1820 que <b>corrente elétrica cria campo magnético</b>: um fio com corrente desvia a agulha da bússola. Assim funcionam os eletroímãs, motores e alto-falantes.</p>
 <p>Uma carga em movimento dentro de um campo magnético B sofre uma <b>força magnética</b> F = |q|·v·B·sen θ, sempre <b>perpendicular</b> à velocidade e ao campo. Por isso ela não muda o módulo da velocidade, só a direção: a carga descreve um círculo de raio R = m·v/(|q|·B). É o princípio de aceleradores de partículas e explica as auroras polares, quando partículas do Sol são guiadas pelo campo da Terra.</p>`,
 pred:{q:'Um próton entra num campo magnético, perpendicular à sua velocidade. A força magnética faz o próton:',o:['descrever um círculo com velocidade de mesmo módulo','acelerar em linha reta','parar','seguir sem desviar'],a:0,why:'A força é sempre perpendicular à velocidade: faz o papel de força centrípeta. Muda a direção, nunca o módulo da velocidade.'},
 lab:{sim:'magforce'},
 tasks:['Troque o próton por um antipróton: o sentido do giro muda?','Dobre o campo B. O que acontece com o raio?','Dobre a velocidade. E o raio?'],
 f:[{f:'F = |q|·v·B·sen θ',s:[['F','força magnética','N'],['q','carga','C'],['v','velocidade','m/s'],['B','campo magnético','T (tesla)'],['θ','ângulo entre v e B','°']],n:'θ = 0° (carga paralela ao campo): força zero.'},{f:'R = '+frac('m·v','|q|·B'),n:'Raio do círculo de uma carga que entra perpendicular ao campo.'}],
 ex:{q:'Um próton (q = 1,6×10⁻¹⁹ C) entra a 1×10⁶ m/s, perpendicular a um campo de 0,5 T. Qual é a força magnética?',s:['F = q·v·B·sen 90° = 1,6×10⁻¹⁹ × 1×10⁶ × 0,5 × 1.','<b>F = 8×10⁻¹⁴ N</b>.','É uma força minúscula, mas a massa do próton é 1,67×10⁻²⁷ kg: a aceleração é enorme.']},
 probs:[
  ()=>{ const v=pick([1e5,2e5,5e5,1e6]), B=pick([.1,.2,.5,1]); return NUM(`Um elétron (|q| = 1,6×10⁻¹⁹ C) move-se a <b>${F(v)} m/s</b>, perpendicular a um campo de <b>${F(B)} T</b>. Qual é a força magnética?`,1.6e-19*v*B,'N',[`F = |q|·v·B = 1,6×10⁻¹⁹ × ${F(v)} × ${F(B)}`,`F = ${F(1.6e-19*v*B)} N`],[],'Digite em notação científica: 8e-14.'); },
  ()=>{ const F0=pick([2,4,6,8]); return NUM(`Uma carga sofre uma força magnética de <b>${F0}×10⁻¹⁴ N</b> ao cruzar um campo perpendicularmente. Qual seria a força, em unidades de 10⁻¹⁴ N, se ela se movesse com a mesma velocidade <b>paralela</b> ao campo?`,0,'×10⁻¹⁴ N',[`θ = 0°: sen 0° = 0`,`F = 0`],[[F0,'Paralela ao campo, sen θ = 0: não há força.']]); },
  ()=>{ const k=pick([2,3,4]); return NUM(`Uma partícula descreve um círculo de raio 10 cm num campo magnético. Se o campo ficar <b>${k} vezes mais forte</b>, qual será o raio, em cm?`,10/k,'cm',[`R = m·v/(|q|·B): R é inversamente proporcional a B`,`R = 10/${k} = ${F(10/k)} cm`],[[10*k,'Campo mais forte curva mais: o raio <b>diminui</b>.']]); },
  POOL([['Quebrando um ímã ao meio, obtemos:',['dois ímãs, cada um com norte e sul','um polo norte e um polo sul separados','dois pedaços sem magnetismo','um ímã e um pedaço de ferro comum'],'Não existem polos magnéticos isolados.'],['A força magnética sobre uma carga em movimento realiza trabalho:',['nulo, pois é perpendicular à velocidade','positivo','negativo','igual à energia cinética'],'Perpendicular ao deslocamento: não muda a energia, só a direção.'],['A experiência de Oersted mostrou que:',['corrente elétrica cria campo magnético','ímãs criam corrente','a Terra é um ímã','cargas paradas criam campo magnético'],'Um fio com corrente desvia a agulha de uma bússola.']])],
 traps:['Achar que uma carga parada ou paralela ao campo sofre força magnética.','Achar que a força magnética aumenta a velocidade da carga.','Achar que dá para separar os polos de um ímã.'],
 keep:['Polos iguais se repelem; não há polo isolado.','Corrente cria campo magnético.','F = |q|vB sen θ, perpendicular a v; R = mv/(|q|B).']},

{id:'inducao',t:'Indução eletromagnética',min:15,
 idea:`<p>Se corrente cria campo magnético, será que campo magnético cria corrente? Faraday mostrou que sim, mas só quando ele <b>varia</b>. Aproxime um ímã de uma bobina ligada a um medidor: aparece corrente. Deixe o ímã parado dentro dela: a corrente some. Afaste: aparece corrente no sentido contrário.</p>
 <p>A grandeza que importa é o <b>fluxo magnético</b> Φ, quanto campo atravessa a bobina. A <b>lei de Faraday</b> diz que a tensão induzida é proporcional à rapidez com que o fluxo muda e ao número de espiras: ε = −N·ΔΦ/Δt. A <b>lei de Lenz</b> (o sinal de menos) diz que a corrente induzida se opõe à variação que a criou.</p>
 <p>Quase toda a eletricidade que usamos vem daí: nas usinas, turbinas giram ímãs perto de bobinas (geradores). Também funcionam assim os transformadores, o carregador por indução do celular e o cartão de aproximação.</p>`,
 pred:{q:'Um ímã é colocado dentro de uma bobina ligada a uma lâmpada e fica parado lá. A lâmpada:',o:['não acende','acende e fica acesa','acende com brilho máximo','pisca sem parar'],a:0,why:'Só há corrente induzida quando o fluxo magnético varia. Ímã parado, fluxo constante: nenhuma corrente.'},
 lab:{sim:'induct'},
 tasks:['Troque para "ímã parado dentro": o que acontece com a fem?','Aumente a rapidez do movimento. O que acontece com o pico da fem?','Compare os dois gráficos: a fem é grande quando o fluxo é grande, ou quando ele muda rápido?'],
 f:[{f:'Φ = B·A·cos θ      ε = −N·'+frac('ΔΦ','Δt'),s:[['Φ','fluxo magnético','Wb (weber)'],['ε','força eletromotriz induzida (tensão)','V'],['N','número de espiras',''],['Δt','intervalo de tempo','s']],n:'O sinal de menos é a lei de Lenz: a corrente induzida se opõe à variação do fluxo.'},{f:frac('U₁','U₂')+' = '+frac('N₁','N₂'),n:'Transformador: a tensão é proporcional ao número de espiras. Só funciona com corrente alternada.'}],
 ex:{q:'O fluxo numa bobina de 100 espiras cai de 0,02 Wb para zero em 0,1 s. Qual é a fem média induzida?',s:['ΔΦ = 0 − 0,02 = −0,02 Wb.','ε = −N·ΔΦ/Δt = −100 × (−0,02)/0,1.','<b>ε = 20 V</b>.']},
 probs:[
  ()=>{ const N=pick([50,100,200,500]), dphi=pick([.01,.02,.05]), dt=pick([.1,.2,.5]); return NUM(`O fluxo numa bobina de <b>${N} espiras</b> varia <b>${F(dphi)} Wb</b> em <b>${F(dt)} s</b>. Qual é o módulo da fem média induzida?`,N*dphi/dt,'V',[`|ε| = N·ΔΦ/Δt = ${N} × ${F(dphi)}/${F(dt)}`,`|ε| = ${F(N*dphi/dt)} V`],[[dphi/dt,'Multiplique pelo número de espiras.']]); },
  ()=>{ const U1=pick([127,220]), N1=pick([500,1000,2000]), U2=pick([6,12,24]); return NUM(`Um transformador reduz <b>${U1} V</b> para <b>${U2} V</b>. Se o primário tem <b>${N1} espiras</b>, quantas tem o secundário?`,N1*U2/U1,'espiras',[`U₁/U₂ = N₁/N₂ → N₂ = N₁·U₂/U₁`,`N₂ = ${N1} × ${U2}/${U1} = ${F(N1*U2/U1)}`],[[N1*U1/U2,'Para reduzir a tensão, o secundário tem <b>menos</b> espiras.']],'A resposta pode não dar inteira: arredonde só no final.'); },
  ()=>{ const B=pick([.1,.2,.5]), A=pick([.01,.02,.05]); return NUM(`Um campo de <b>${F(B)} T</b> atravessa perpendicularmente uma espira de área <b>${F(A)} m²</b>. Qual é o fluxo magnético?`,B*A,'Wb',[`Φ = B·A·cos 0° = ${F(B)} × ${F(A)} = ${F(B*A)} Wb`],[[B/A,'Φ = B·A: multiplique.']]); },
  POOL([['Numa usina hidrelétrica, a eletricidade é gerada por:',['indução: ímãs girando perto de bobinas','reação química na água','atrito da água com a turbina','aquecimento da água'],'A turbina gira o gerador; o fluxo magnético nas bobinas varia e induz tensão.'],['Por que um transformador não funciona com a corrente contínua de uma pilha?',['a corrente contínua não faz o fluxo variar','a pilha tem pouca tensão','a corrente contínua é perigosa','o transformador só aceita 220 V'],'Sem variação de fluxo, não há indução no secundário.'],['A lei de Lenz diz que a corrente induzida:',['se opõe à variação de fluxo que a produziu','reforça a variação de fluxo','é sempre no sentido horário','não tem sentido definido'],'É uma consequência da conservação da energia.']])],
 traps:['Achar que um ímã parado dentro da bobina gera corrente.','Esquecer de multiplicar pelo número de espiras.','Achar que transformadores funcionam com corrente contínua.'],
 keep:['Só há indução quando o fluxo varia.','Faraday: ε = −N·ΔΦ/Δt. Lenz: opõe-se à variação.','Transformador: U₁/U₂ = N₁/N₂.']}]);

mod('mod','Física moderna','luz em pacotes, núcleos instáveis e relatividade',[
{id:'fotoeletrico',t:'Efeito fotoelétrico e o fóton',min:15,
 idea:`<p>Luz batendo num metal pode arrancar elétrons: é o <b>efeito fotoelétrico</b>. O estranho é que luz vermelha muito forte não arranca nada de alguns metais, enquanto luz ultravioleta fraca arranca na hora. A teoria ondulatória não explicava isso.</p>
 <p>Einstein explicou em 1905: a luz chega em pacotes de energia, os <b>fótons</b>, cada um com <b>E = h·f</b> (h = 6,63×10⁻³⁴ J·s, a constante de Planck). Cada elétron absorve um fóton de uma vez. Se a energia do fóton for menor que a <b>função trabalho</b> φ do metal (a energia para soltar o elétron), nada acontece, não importa quantos fótons cheguem. Se for maior, a sobra vira energia cinética: <b>E<sub>c,máx</sub> = h·f − φ</b>.</p>
 <p>Aumentar a intensidade da luz aumenta o número de fótons, e portanto de elétrons arrancados, mas não a energia de cada um. É assim que funcionam sensores de câmera e células solares. Energias atômicas costumam ser medidas em elétron-volt: 1 eV = 1,6×10⁻¹⁹ J.</p>`,
 pred:{q:'Uma luz vermelha fraca não arranca elétrons de um metal. Aumentando muito a intensidade da mesma luz vermelha:',o:['continua sem arrancar elétrons','passa a arrancar elétrons','arranca elétrons mais rápidos','o metal derrete'],a:0,why:'Cada fóton vermelho continua com a mesma energia, insuficiente. Mais intensidade só significa mais fótons fracos.'},
 lab:{sim:'photo'},
 tasks:['No sódio, encontre o maior comprimento de onda que ainda arranca elétrons.','Com luz que não arranca elétrons, aumente a intensidade ao máximo. Algo muda?','Troque para zinco. Por que a luz visível deixa de funcionar?'],
 f:[{f:'E = h·f = '+frac('h·c','λ'),s:[['E','energia de um fóton','J ou eV'],['h','constante de Planck: 6,63×10⁻³⁴ J·s (≈ 4,14×10⁻¹⁵ eV·s)',''],['f','frequência da luz','Hz'],['λ','comprimento de onda','m']],n:'Atalho útil: E (em eV) ≈ 1240/λ (em nm).'},{f:'E<sub class="up">c,máx</sub> = h·f − φ',s:[['φ','função trabalho do metal','eV'],['E<sub>c,máx</sub>','energia cinética máxima do elétron','eV']]}],
 ex:{q:'Luz de 310 nm incide sobre zinco (φ = 4,3 eV). Há emissão? Com que energia máxima?',s:['Energia do fóton: 1240/310 = 4,0 eV.','4,0 eV é menor que 4,3 eV.','<b>Não há emissão</b>, por mais intensa que seja a luz.']},
 probs:[
  ()=>{ const f=pick([1e14,4e14,5e14,1e15,2e15]); return NUM(`Qual é a energia de um fóton de frequência <b>${F(f)} Hz</b>? (h = 6,63×10⁻³⁴ J·s)`,6.63e-34*f,'J',[`E = h·f = 6,63×10⁻³⁴ × ${F(f)}`,`E = ${F(6.63e-34*f)} J`],[],'Digite em notação científica: 3.3e-19.'); },
  ()=>{ const l=pick([248,310,400,496,620]); return NUM(`Qual é a energia, em eV, de um fóton de comprimento de onda <b>${l} nm</b>? (E ≈ 1240/λ, com λ em nm)`,1240/l,'eV',[`E = 1240/${l} = ${F(1240/l)} eV`],[[l/1240,'Divida 1240 pelo comprimento de onda.']]); },
  ()=>{ const E=pick([3,4,5,6]), W=pick([2.3,2,4.3]); if(E<=W) return NUM(`Fótons de <b>${E+3} eV</b> atingem um metal de função trabalho <b>${F(W)} eV</b>. Qual é a energia cinética máxima dos elétrons?`,E+3-W,'eV',[`E<sub>c</sub> = ${E+3} − ${F(W)} = ${F(E+3-W)} eV`],[[E+3,'Desconte a função trabalho.']]); return NUM(`Fótons de <b>${E} eV</b> atingem um metal de função trabalho <b>${F(W)} eV</b>. Qual é a energia cinética máxima dos elétrons emitidos?`,E-W,'eV',[`E<sub>c,máx</sub> = h·f − φ = ${E} − ${F(W)}`,`E<sub>c,máx</sub> = ${F(E-W)} eV`],[[E+W,'A função trabalho é gasta para soltar o elétron: subtraia.']]); },
  POOL([['No efeito fotoelétrico, aumentar a intensidade da luz (com a mesma cor) aumenta:',['o número de elétrons emitidos','a energia de cada elétron','a função trabalho do metal','a frequência da luz'],'Mais fótons, mais elétrons; cada fóton continua com a mesma energia.'],['O que determina a energia de um fóton?',['a frequência (ou a cor) da luz','a intensidade','a distância da lâmpada','o metal iluminado'],'E = h·f.'],['Qual luz tem fótons mais energéticos?',['ultravioleta','vermelha','infravermelha','amarela'],'Maior frequência (menor λ), maior energia. Por isso o UV queima a pele e o infravermelho não.']])],
 traps:['Achar que luz mais intensa arranca elétrons de qualquer metal.','Confundir intensidade (quantidade de fótons) com frequência (energia de cada fóton).','Esquecer de subtrair a função trabalho.'],
 keep:['A luz vem em fótons: E = h·f.','Só há emissão se h·f > φ; E<sub>c,máx</sub> = h·f − φ.','Intensidade muda a quantidade, não a energia.']},

{id:'radioatividade',t:'Radioatividade e meia-vida',min:14,
 idea:`<p>Alguns núcleos atômicos são instáveis e se transformam sozinhos, emitindo radiação: é a <b>radioatividade</b>, descoberta por Becquerel e estudada por Marie Curie. Os principais tipos são <b>alfa</b> (α, dois prótons e dois nêutrons; um papel barra), <b>beta</b> (β, um elétron rápido; uma placa de alumínio barra) e <b>gama</b> (γ, onda eletromagnética muito energética; exige chumbo ou concreto grosso).</p>
 <p>Não dá para prever quando um núcleo vai decair, mas dá para prever o comportamento de muitos: a cada <b>meia-vida</b>, metade dos núcleos restantes decai. Depois de n meias-vidas, sobra <b>N = N₀/2ⁿ</b>.</p>
 <p>O carbono-14 (meia-vida de cerca de 5730 anos) permite datar fósseis e objetos arqueológicos. O iodo-131 (8 dias) é usado em exames da tireoide. No acidente de Goiânia, em 1987, o césio-137 (30 anos) contaminou dezenas de pessoas.</p>`,
 pred:{q:'Uma amostra tem 800 núcleos radioativos, com meia-vida de 1 hora. Depois de 3 horas, restam cerca de:',o:['100','0','400','200'],a:0,why:'800 → 400 (1 h) → 200 (2 h) → 100 (3 h). A quantidade nunca zera de uma vez: cai pela metade a cada meia-vida.'},
 lab:{sim:'decay'},
 tasks:['Acompanhe o gráfico: depois de uma meia-vida, sobraram perto de 200 núcleos?','Rode duas vezes: os mesmos núcleos decaem?','Mude a meia-vida. O formato da curva muda?'],
 f:[{f:'N = '+frac('N₀','2ⁿ')+'      n = '+frac('t','T<sub class="up">½</sub>'),s:[['N₀','quantidade inicial',''],['N','quantidade restante',''],['n','número de meias-vidas',''],['T<sub>½</sub>','meia-vida','s, anos…']]}],
 ex:{q:'Um osso tem 1/4 do carbono-14 que tinha quando o animal morreu. Há quanto tempo ele morreu? (T<sub>½</sub> = 5730 anos)',s:['1/4 = 1/2² → passaram n = 2 meias-vidas.','t = 2 × 5730.','<b>t ≈ 11 460 anos</b>.']},
 probs:[
  ()=>{ const N0=pick([800,1600,3200,6400]), n=R(1,5); return NUM(`Uma amostra tem <b>${N0}</b> núcleos radioativos. Quantos restam depois de <b>${n} meia${n>1?'s':''}-vida${n>1?'s':''}</b>?`,N0/2**n,'núcleos',[`N = N₀/2ⁿ = ${N0}/2${[...String(n)].map(c=>SUP[c]).join('')}`,`N = ${N0/2**n}`],[[N0/(2*n),'Não é dividir por 2n: a cada meia-vida, divide-se por 2 de novo.']]); },
  ()=>{ const T=pick([2,5,8,10,30]), n=R(2,5); return NUM(`Um isótopo tem meia-vida de <b>${T} dias</b>. Depois de <b>${T*n} dias</b>, que fração da amostra inicial resta? Responda em porcentagem.`,100/2**n,'%',[`n = ${T*n}/${T} = ${n} meias-vidas`,`N/N₀ = 1/2${[...String(n)].map(c=>SUP[c]).join('')} = ${F(100/2**n)} %`],[[100-100/2**n,'Essa é a fração que decaiu.']]); },
  ()=>{ const T=pick([8,30,5730]), n=pick([2,3,4]); return NUM(`Resta <b>1/${2**n}</b> da quantidade inicial de um material com meia-vida de <b>${T} anos</b>. Quanto tempo passou?`,T*n,'anos',[`1/${2**n} = 1/2${[...String(n)].map(c=>SUP[c]).join('')} → n = ${n}`,`t = ${n} × ${T} = ${T*n} anos`],[[T*2**n/2,'Descubra quantas vezes a quantidade foi dividida por 2.']]); },
  POOL([['Qual radiação é a mais penetrante?',['gama','alfa','beta','todas são iguais'],'Os raios gama são ondas eletromagnéticas de alta energia; exigem chumbo ou concreto.'],['Depois de 1 meia-vida, um núcleo específico da amostra:',['pode ou não ter decaído; é uma questão de probabilidade','decaiu com certeza','não decaiu com certeza','decaiu pela metade'],'A meia-vida vale para o conjunto; cada núcleo decai ao acaso.'],['O carbono-14 é usado para:',['datar fósseis e objetos antigos','gerar energia em usinas','fazer exames de tireoide','esterilizar alimentos'],'Seres vivos incorporam C-14; depois da morte, ele decai com meia-vida de cerca de 5730 anos.']])],
 traps:['Achar que depois de 2 meias-vidas a amostra acaba.','Dividir por 2n em vez de 2ⁿ.','Confundir a meia-vida (do conjunto) com o tempo de vida de um núcleo.'],
 keep:['A cada meia-vida, sobra metade.','N = N₀/2ⁿ; n = t/T<sub>½</sub>.','α barra no papel; β no alumínio; γ exige chumbo.']},

{id:'relatividade',t:'Relatividade restrita',min:14,
 idea:`<p>Em 1905, Einstein partiu de duas ideias: as leis da física são as mesmas para qualquer observador em movimento uniforme, e a <b>velocidade da luz no vácuo é a mesma para todos</b> (c ≈ 3×10⁸ m/s), não importa se a fonte ou o observador se movem.</p>
 <p>Para a velocidade da luz ser a mesma para todos, o tempo e o espaço precisam se ajustar. Um relógio em movimento marca o tempo mais devagar (<b>dilatação do tempo</b>): Δt = γ·Δt₀. Um objeto em movimento fica mais curto na direção do movimento (<b>contração do comprimento</b>): L = L₀/γ. O fator de Lorentz, γ = 1/√(1 − v²/c²), só fica grande perto da velocidade da luz.</p>
 <p>Não é ilusão: o GPS precisa corrigir os relógios dos satélites para funcionar, e partículas chamadas múons, criadas no alto da atmosfera, chegam ao chão porque "vivem" mais em alta velocidade. Da relatividade vem também <b>E = m·c²</b>: massa é uma forma de energia.</p>`,
 pred:{q:'Uma nave passa pela Terra a 80% da velocidade da luz. Para quem está na Terra, o relógio da nave:',o:['anda mais devagar','anda mais rápido','anda no mesmo ritmo','para completamente'],a:0,why:'Dilatação do tempo: com v = 0,8c, γ = 1/0,6 ≈ 1,67. Cada segundo da nave dura 1,67 s para quem está na Terra.'},
 lab:{sim:'rel'},
 tasks:['Coloque 0% de c. Os dois relógios marcam o mesmo número de tiques?','A 80% de c, conte: quantos tiques o relógio parado dá enquanto o outro dá 3?','A partir de que velocidade a diferença fica fácil de ver?'],
 f:[{f:'γ = '+frac('1','√(1 − v²/c²)')+'      Δt = γ·Δt₀      L = '+frac('L₀','γ'),s:[['γ','fator de Lorentz (sempre ≥ 1)',''],['Δt₀','tempo medido por quem viaja com o relógio (tempo próprio)','s'],['L₀','comprimento medido em repouso','m']]},{f:'E = m·c²',n:'Uma pequena massa equivale a uma energia enorme: é a origem da energia nuclear e da energia do Sol.'}],
 ex:{q:'Uma nave viaja a 0,6c. Quanto tempo passa na Terra enquanto passa 1 ano para os astronautas?',s:['v²/c² = 0,36 → √(1 − 0,36) = √0,64 = 0,8.','γ = 1/0,8 = 1,25.','Δt = 1,25 × 1 ano = <b>1,25 ano</b> na Terra.']},
 probs:[
  ()=>{ const [b,g]=pick([[.6,1.25],[.8,1/.6],[.28,1/.96]]); return NUM(`Qual é o fator de Lorentz γ para uma velocidade de <b>${F(b)}c</b>?`,g,'',[`v²/c² = ${F(b*b)} → √(1 − ${F(b*b)}) = ${F(Math.sqrt(1-b*b))}`,`γ = 1/${F(Math.sqrt(1-b*b))} = ${F(g)}`],[[Math.sqrt(1-b*b),'Esse é √(1 − v²/c²). γ é o inverso.']]); },
  ()=>{ const [b,g]=pick([[.6,1.25],[.8,5/3]]), t=pick([2,3,6,12]); return NUM(`Um astronauta viaja a <b>${F(b)}c</b> e mede <b>${t} anos</b> no próprio relógio. Quanto tempo passa na Terra? (a ${F(b)}c, γ = ${F(g)})`,t*g,'anos',[`Δt = γ·Δt₀ = ${F(g)} × ${t}`,`Δt = ${F(t*g)} anos`],[[t/g,'Para quem está na Terra, passa <b>mais</b> tempo.']]); },
  ()=>{ const [b,g]=pick([[.6,1.25],[.8,5/3]]), L=pick([100,150,300]); return NUM(`Uma nave mede <b>${L} m</b> parada. Qual é o comprimento dela, medido da Terra, quando passa a <b>${F(b)}c</b>? (γ = ${F(g)})`,L/g,'m',[`L = L₀/γ = ${L}/${F(g)} = ${F(L/g)} m`],[[L*g,'Em movimento, o comprimento <b>diminui</b>.']]); },
  ()=>{ const m=pick([.001,.01,1]); return NUM(`Quanta energia equivale a uma massa de <b>${F(m)} kg</b>? (c = 3×10⁸ m/s)`,m*9e16,'J',[`E = m·c² = ${F(m)} × (3×10⁸)² = ${F(m)} × 9×10¹⁶`,`E = ${F(m*9e16)} J`],[[m*3e8,'Faltou elevar c ao quadrado.']],'Digite em notação científica: 9e13.'); },
  POOL([['Um trem a 100 km/h acende o farol. A velocidade da luz medida por alguém parado na estação é:',['c, a mesma de sempre','c + 100 km/h','c − 100 km/h','depende do trem'],'É o segundo postulado de Einstein: c é igual para todos.'],['Por que não percebemos a dilatação do tempo no dia a dia?',['nossas velocidades são minúsculas perto de c, e γ ≈ 1','ela só acontece no espaço','ela não existe de verdade','os relógios são imprecisos'],'Mesmo num avião, γ − 1 é da ordem de 10⁻¹².'],['E = m·c² significa que:',['massa e energia são equivalentes','a energia é sempre igual à massa','a luz tem massa','nada pode ser mais rápido que a luz'],'Uma pequena massa corresponde a uma energia enorme, porque c² é gigantesco.']])],
 traps:['Achar que a dilatação do tempo é ilusão de óptica.','Inverter: quem observa o relógio em movimento vê ele atrasar (Δt = γΔt₀, com γ ≥ 1).','Esquecer de elevar c ao quadrado em E = mc².'],
 keep:['c é a mesma para todos os observadores.','Δt = γΔt₀; L = L₀/γ; γ = 1/√(1 − v²/c²).','E = mc².']}]);
