/* =====================================================================
   Lições novas, encaixadas nos módulos existentes:
   propagação do calor, MHS, ondas estacionárias, espectro
   eletromagnético e campo magnético de correntes
   ===================================================================== */
addLessons('ter','calorimetria',[
{id:'propagacao',t:'Propagação do calor',min:13,
 idea:`<p>O calor sempre passa do corpo mais quente para o mais frio, e pode fazer isso de três jeitos.</p>
 <p><b>Condução</b>: a agitação passa de partícula em partícula, por contato, sem que a matéria saia do lugar. Metais conduzem muito bem; ar, madeira, isopor e lã conduzem mal e são chamados de <b>isolantes</b>. Por isso, numa manhã fria, a maçaneta de metal parece mais gelada que a porta de madeira, mesmo estando as duas à mesma temperatura: o metal tira calor da sua mão mais depressa.</p>
 <p><b>Convecção</b>: em líquidos e gases, a parte aquecida fica menos densa e sobe, e a parte fria desce, formando correntes. É por isso que o ar-condicionado fica no alto da parede, que a água da panela circula quando esquenta e que surgem as brisas do litoral.</p>
 <p><b>Radiação</b>: todo corpo emite ondas eletromagnéticas (principalmente infravermelho), que viajam até no vácuo. É assim que o calor do Sol chega à Terra. Superfícies escuras absorvem e emitem mais; claras e espelhadas refletem. A garrafa térmica combate os três: vácuo entre as paredes (sem condução nem convecção) e paredes espelhadas (que refletem a radiação).</p>
 <p>Na condução, o calor que atravessa uma placa por segundo segue a <b>lei de Fourier</b>: cresce com a área e com a diferença de temperatura, e diminui com a espessura.</p>`,
 pred:{q:'De manhã, você toca uma maçaneta de metal e a porta de madeira, que estão no mesmo cômodo há horas. O metal parece mais frio porque:',o:['conduz calor melhor e tira calor da sua mão mais depressa','está a uma temperatura mais baixa que a madeira','guarda mais "frio" que a madeira','é mais denso e, por isso, mais gelado'],a:0,why:'Os dois estão à temperatura do cômodo. A sensação de frio é o calor saindo da sua mão, e o metal, bom condutor, leva esse calor muito mais rápido que a madeira.'},
 lab:{sim:'conduc'},
 tasks:['Troque o aço pelo isopor. Quantas vezes o fluxo de calor diminui?','Dobre a espessura da placa. O que acontece com o fluxo?','Descubra dois jeitos de reduzir o calor que atravessa à metade sem trocar o material.'],
 f:[{f:'Φ = '+frac('Q','Δt')+' = '+frac('k·A·ΔT','L'),s:[['Φ','fluxo de calor (energia por segundo)','W'],['k','condutividade térmica do material','W/(m·K)'],['A','área da placa','m²'],['ΔT','diferença de temperatura entre as faces','°C ou K'],['L','espessura da placa','m']],n:'Cobre: k ≈ 400 · aço: 50 · vidro: 0,8 · madeira: 0,15 · isopor: 0,03 W/(m·K).'}],
 ex:{q:'Uma janela de vidro (k = 0,8 W/m·K) tem 2 m² e 4 mm de espessura. Dentro faz 25 °C e fora, 15 °C. Quanto calor atravessa o vidro por segundo?',s:['Espessura em metros: L = 4 mm = 0,004 m.','Φ = k·A·ΔT/L = 0,8 × 2 × 10 / 0,004.','<b>Φ = 4000 W</b>. Por isso janelas de vidro duplo, com ar entre os vidros, economizam tanto ar-condicionado.']},
 probs:[
  ()=>{ const [k,m]=pick([[.8,'vidro'],[50,'aço'],[.15,'madeira'],[400,'cobre']]), A=pick([.5,1,2]), dT=R(10,50,10), L=pick([1,2,4,5,10]); const a=k*A*dT/(L/100);
    return NUM(`Uma placa de <b>${m}</b> (k = ${F(k)} W/m·K) tem <b>${F(A)} m²</b> de área e <b>${L} cm</b> de espessura. Uma face está <b>${dT} °C</b> mais quente que a outra. Qual é o fluxo de calor através dela?`,a,'W',[`L = ${L} cm = ${F(L/100)} m`,`Φ = k·A·ΔT/L = ${F(k)} × ${F(A)} × ${dT} / ${F(L/100)}`,`Φ = ${F(a)} W`],[[k*A*dT/L,'Converta a espessura para metros antes de dividir.'],[k*A*dT*L/100,'A espessura <b>divide</b>: placa mais grossa deixa passar menos calor.']],'Φ = k·A·ΔT/L, com L em metros.'); },
  ()=>{ const P0=pick([100,200,300,600]), Lk=pick([2,3,4]), Ak=pick([1,2,3].filter(x=>x!==Lk)); const a=P0*Ak/Lk;
    return NUM(`Uma parede deixa passar <b>${P0} W</b> de calor. Outra parede do mesmo material, com a mesma diferença de temperatura, tem <b>${Ak===1?'a mesma área':Ak+' vezes a área'}</b> e <b>${Lk} vezes a espessura</b>. Quanto calor passa por ela?`,a,'W',[`Φ é proporcional a A e inversamente proporcional a L`,`Φ = ${P0} × ${Ak}/${Lk} = ${F(a)} W`],[[P0*Ak*Lk,'Espessura maior <b>reduz</b> o fluxo: divida pelo fator da espessura.'],[P0*Lk/Ak,'Área maior <b>aumenta</b> o fluxo.']]); },
  ()=>{ const A=pick([1.5,2]), L=pick([2,3,5]), dT=R(5,20,5); const phi=.15*A*dT/(L/100), a=phi*3600/1000;
    return NUM(`Uma porta de madeira (k = 0,15 W/m·K) tem <b>${F(A)} m²</b> e <b>${L} cm</b> de espessura. De um lado faz ${dT} °C a mais que do outro. Quanta energia atravessa a porta em <b>1 hora</b>, em quilojoules?`,a,'kJ',[`Φ = 0,15 × ${F(A)} × ${dT} / ${F(L/100)} = ${F(phi)} W`,`Em 1 h = 3600 s: Q = ${F(phi)} × 3600 = ${F(phi*3600)} J`,`Q = ${F(a)} kJ`],[[phi,'Esse é o fluxo em watts (joules por segundo). Multiplique por 3600 s.'],[phi*3600,'Resposta em joules; divida por 1000 para ter kJ.']]); },
  ()=>{ const [k1,k2,m1,m2]=pick([[400,.8,'cobre','vidro'],[50,.15,'aço','madeira'],[.8,.04,'vidro','lã'],[400,50,'cobre','aço'],[.15,.03,'madeira','isopor']]);
    return NUM(`Duas placas de mesmas medidas, uma de <b>${m1}</b> (k = ${F(k1)} W/m·K) e outra de <b>${m2}</b> (k = ${F(k2)} W/m·K), separam os mesmos ambientes. Quantas vezes mais calor passa pela de ${m1}?`,k1/k2,'vezes',[`Mesmas A, L e ΔT: Φ é proporcional a k`,`${F(k1)} / ${F(k2)} = ${F(k1/k2)}`],[[k2/k1,'Inverteu: o material de maior k deixa passar mais calor.']]); },
  POOL([['Como o calor do Sol chega até a Terra?',['por radiação','por condução','por convecção','pelo ar que existe no espaço'],'Entre o Sol e a Terra há vácuo: só a radiação (ondas eletromagnéticas) atravessa.'],
   ['O aparelho de ar-condicionado fica no alto da parede porque:',['o ar frio é mais denso, desce e cria correntes de convecção','o ar frio sobe','assim ele junta menos poeira','perto do chão faz mais calor'],'O ar resfriado desce e o ar quente sobe até o aparelho: o ar da sala inteira circula.'],
   ['Numa garrafa térmica, o vácuo entre as paredes serve para impedir:',['a condução e a convecção','só a radiação','a entrada de luz','o vazamento pela tampa'],'Sem matéria entre as paredes não há condução nem convecção; as paredes espelhadas cuidam da radiação.'],
   ['Um cobertor deixa você aquecido porque:',['é isolante e dificulta a saída do calor do seu corpo','produz calor','impede a entrada do frio','absorve o calor do ar do quarto'],'O cobertor não gera calor: ele segura o calor que o seu corpo produz, graças ao ar preso entre as fibras.'],
   ['A brisa que sopra do mar para a terra durante o dia é um exemplo de:',['convecção','condução','radiação','dilatação'],'A terra esquenta mais rápido que o mar; o ar sobre ela sobe e o ar do mar vem ocupar o lugar.']])],
 traps:['Achar que o metal está mais frio que a madeira no mesmo ambiente: ele só conduz melhor.','Dizer que o cobertor "produz calor" ou "barra o frio": ele isola o calor do corpo.','Esquecer de passar a espessura para metros na lei de Fourier.'],
 keep:['Condução: por contato, sem transporte de matéria. Metais conduzem bem; ar e isopor, mal.','Convecção: correntes em líquidos e gases; o quente sobe e o frio desce.','Radiação: ondas eletromagnéticas, funciona até no vácuo.','Φ = k·A·ΔT/L.']}]);

addLessons('ond',null,[
{id:'mhs',t:'Oscilações: mola e pêndulo',min:15,
 idea:`<p>Muita coisa na natureza vai e volta sempre no mesmo ritmo: um balanço, a corda de um violão, o pêndulo de um relógio. Quando a força que puxa de volta é proporcional ao afastamento, o movimento se chama <b>movimento harmônico simples</b> (MHS).</p>
 <p>No sistema <b>massa-mola</b>, a mola puxa com F = −k·x (lei de Hooke): quanto mais você estica, mais forte ela puxa de volta. O tempo de uma ida e volta completa, o <b>período</b>, é <b>T = 2π·√(m/k)</b>. Massa maior oscila mais devagar; mola mais dura, mais depressa.</p>
 <p>No <b>pêndulo simples</b>, para ângulos pequenos, <b>T = 2π·√(L/g)</b>. Repare no que falta: a massa! Uma bola de ferro e uma de isopor, penduradas em fios do mesmo comprimento, balançam no mesmo ritmo. Nos dois sistemas o período também não depende da amplitude, e foi por isso que o pêndulo serviu para marcar o tempo nos relógios.</p>
 <p>Durante a oscilação a energia troca de forma: nos extremos ela é toda potencial (na mola, E = k·A²/2) e no centro é toda cinética.</p>`,
 pred:{q:'Dois pêndulos têm o mesmo comprimento. Um tem uma bola de 1 kg e o outro, uma de 4 kg. Qual oscila mais rápido?',o:['os dois no mesmo ritmo','o de 4 kg','o de 1 kg','depende de qual foi solto primeiro'],a:0,why:'O período do pêndulo é T = 2π·√(L/g): só o comprimento e a gravidade importam. A massa se cancela, como na queda livre.'},
 lab:{sim:'mhs'},
 tasks:['Aumente a massa. Qual dos dois sistemas muda de ritmo?','Leve o pêndulo de 0,5 m para 2 m (4 vezes mais comprido). O período dobra?','Mude a amplitude. Algum dos períodos muda?'],
 f:[{f:'T<sub class="up">mola</sub> = 2π·√(m/k)      T<sub class="up">pêndulo</sub> = 2π·√(L/g)',s:[['T','período: tempo de uma ida e volta','s'],['m','massa presa à mola','kg'],['k','constante elástica da mola','N/m'],['L','comprimento do pêndulo','m'],['g','aceleração da gravidade (10)','m/s²']],n:'Frequência: f = 1/T. A fórmula do pêndulo vale para ângulos pequenos (até uns 15°).'},
  {f:'F = −k·x      E = '+frac('k·A²','2'),s:[['x','afastamento da posição de equilíbrio','m'],['A','amplitude (afastamento máximo)','m'],['E','energia da oscilação','J']],n:'O sinal de menos diz que a força aponta sempre de volta para o centro.'}],
 ex:{q:'Um bloco de 0,4 kg preso a uma mola de k = 40 N/m oscila. Qual é o período? (π ≈ 3,14)',s:['T = 2π·√(m/k) = 2π·√(0,4/40).','0,4/40 = 0,01, e √0,01 = 0,1.','T = 2 × 3,14 × 0,1 ≈ <b>0,63 s</b>: cerca de 1,6 oscilação por segundo.']},
 probs:[
  ()=>{ const [m,k]=pick([[.1,10],[.4,10],[.9,10],[.2,20],[1,25],[.5,50],[2,50],[.25,100]]), r=Math.sqrt(m/k), a=2*Math.PI*r;
    return NUM(`Um bloco de <b>${F(m)} kg</b> preso a uma mola de constante <b>${k} N/m</b> oscila. Qual é o período? (π ≈ 3,14)`,a,'s',[`T = 2π·√(m/k) = 2π·√(${F(m)}/${k})`,`√${F(m/k)} = ${F(r)}`,`T = 2 × 3,14 × ${F(r)} ≈ ${F(a)} s`],[[2*Math.PI*Math.sqrt(k/m),'Você inverteu: é √(m/k), com a massa em cima.'],[2*Math.PI*m/k,'Faltou tirar a raiz quadrada.']],'T = 2π·√(m/k).'); },
  ()=>{ const L=pick([.1,.4,.9,1.6,2.5,3.6]), M=pick([.2,1,5]), r=Math.sqrt(L/10), a=2*Math.PI*r;
    return NUM(`Um pêndulo simples tem fio de <b>${F(L)} m</b> e uma bola de <b>${F(M)} kg</b>. Qual é o período das pequenas oscilações? (g = 10 m/s²; π ≈ 3,14)`,a,'s',[`A massa não entra: T = 2π·√(L/g)`,`√(${F(L)}/10) = √${F(L/10)} = ${F(r)}`,`T = 2 × 3,14 × ${F(r)} ≈ ${F(a)} s`],[[2*Math.PI*Math.sqrt(10/L),'É √(L/g), com o comprimento em cima.'],[2*Math.PI*L/10,'Faltou tirar a raiz quadrada.']],'A massa da bola não aparece na fórmula.'); },
  ()=>{ const K=pick([4,9,16]), [what,a,tr]=pick([['o comprimento de um pêndulo',Math.sqrt(K),[[K,'O período depende da <b>raiz</b> do comprimento.']]],['a massa presa a uma mola',Math.sqrt(K),[[K,'O período depende da <b>raiz</b> da massa.']]],['a constante de uma mola (mola mais dura)',1/Math.sqrt(K),[[Math.sqrt(K),'Mola mais dura oscila <b>mais rápido</b>: o período diminui.'],[1/K,'Lembre da raiz: T depende de 1/√k.']]]]);
    return NUM(`Se ${what} for multiplicado(a) por <b>${K}</b>, o período fica multiplicado por quanto? (Responda o fator; por exemplo, 0,5 para a metade.)`,a,'',[`T é proporcional a √${what.includes('constante')?'(1/k)':what.includes('massa')?'m':'L'}`,`Fator = ${what.includes('constante')?'1/√'+K:'√'+K} = ${F(a)}`],tr); },
  ()=>{ const N=pick([10,20,30,60]), t=pick([5,15,40,120]);
    return NUM(`Um pêndulo completa <b>${N} oscilações</b> em <b>${t} s</b>. Qual é a frequência?`,N/t,'Hz',[`f = oscilações ÷ tempo = ${N}/${t} = ${F(N/t)} Hz`,`(O período é T = 1/f = ${F(t/N)} s.)`],[[t/N,'Esse é o período (tempo de uma oscilação). A frequência é o inverso.']]); },
  ()=>{ const k=pick([100,200,400,800]), A=pick([5,10,20]), a=k*(A/100)**2/2;
    return NUM(`Uma mola de constante <b>${k} N/m</b> é esticada <b>${A} cm</b> e solta. Qual é a energia da oscilação?`,a,'J',[`A = ${A} cm = ${F(A/100)} m`,`E = k·A²/2 = ${k} × ${F(A/100)}² / 2 = ${F(a)} J`],[[k*(A/100)**2,'Faltou dividir por 2.'],[k*A*A/2,'Converta a amplitude para metros.']]); },
  POOL([['O período de um pêndulo simples (ângulos pequenos) NÃO depende:',['da massa nem da amplitude','do comprimento do fio','da gravidade do lugar','de nada: é sempre 1 s'],'T = 2π·√(L/g): só comprimento e gravidade.'],
   ['Levado para a Lua (g ≈ 1,6 m/s²), um relógio de pêndulo:',['atrasa, porque o pêndulo oscila mais devagar','adianta','marca a hora certa','para de oscilar'],'g menor deixa o período maior: cada "tique" demora mais.'],
   ['No ponto de maior afastamento de um MHS, a velocidade do corpo é:',['zero, e a energia é toda potencial','máxima','igual à que ele tem no centro','impossível de saber'],'Nos extremos o corpo para por um instante e volta.'],
   ['Na posição de equilíbrio (centro) de um sistema massa-mola, a força da mola é:',['zero, e a velocidade é máxima','máxima','igual ao peso do bloco sempre','máxima e a velocidade é zero'],'F = −k·x com x = 0; é ali que o bloco passa mais rápido.']])],
 traps:['Achar que a massa muda o período do pêndulo.','Esquecer a raiz quadrada: quadruplicar o comprimento só dobra o período.','Confundir período (tempo de uma oscilação) com frequência (oscilações por segundo).'],
 keep:['Mola: T = 2π·√(m/k). Pêndulo: T = 2π·√(L/g).','O período não depende da amplitude; o do pêndulo também não depende da massa.','Nos extremos, v = 0 e a energia é potencial; no centro, v é máxima.']}]);

addLessons('ond','som',[
{id:'estacionarias',t:'Ondas estacionárias: cordas e tubos',min:15,
 idea:`<p>Quando uma onda bate numa extremidade e volta, ela se soma à que está chegando. Em certas frequências as duas formam um padrão que não anda: a <b>onda estacionária</b>. Alguns pontos ficam sempre parados, os <b>nós</b>; outros vibram com a amplitude máxima, os <b>ventres</b>. De um nó ao seguinte há meio comprimento de onda.</p>
 <p>Numa <b>corda presa nas duas pontas</b> (violão, piano) as pontas são nós, então cabem na corda 1, 2, 3… meias ondas: λ = 2L/n e <b>f = n·v/(2L)</b>. O modo n = 1 é o som <b>fundamental</b>; os outros são os <b>harmônicos</b>, e a mistura deles dá o timbre de cada instrumento. Apertar a corda num traste do violão encurta L e deixa a nota mais aguda.</p>
 <p>Nos instrumentos de sopro vibra o ar dentro de um <b>tubo</b>. No <b>tubo aberto</b> as duas pontas são ventres e vale a mesma fórmula da corda. No <b>tubo fechado</b> numa ponta, ela é nó e a outra é ventre: cabem 1, 3, 5… quartos de onda, e só existem <b>harmônicos ímpares</b>, f = n·v/(4L).</p>
 <p>Todo objeto tem frequências naturais como essas. Se for empurrado exatamente numa delas, a amplitude cresce muito: é a <b>ressonância</b>. É ela que faz uma taça estourar com a voz de um cantor, e é por causa dela que engenheiros calculam as frequências de pontes e prédios.</p>`,
 pred:{q:'Você aperta a corda do violão bem no meio e toca. A frequência da nota:',o:['dobra (a nota sobe uma oitava)','cai pela metade','continua igual','quadruplica'],a:0,why:'A corda é a mesma, então a velocidade v da onda nela não muda. Com f = v/(2L), metade do comprimento dá o dobro da frequência: uma oitava acima.'},
 lab:{sim:'harm'},
 tasks:['Na corda, passe do 1º para o 3º modo. Conte os nós e compare as frequências.','Compare o tubo aberto com o fechado de mesmo comprimento: o que acontece com a frequência do 1º modo?','Diminua L. O som fica mais agudo ou mais grave?'],
 f:[{f:'Corda e tubo aberto: f<sub class="up">n</sub> = n·'+frac('v','2L')+'   (n = 1, 2, 3…)',s:[['f<sub>n</sub>','frequência do n-ésimo harmônico','Hz'],['n','número do harmônico',''],['v','velocidade da onda (no tubo, a do som)','m/s'],['L','comprimento da corda ou do tubo','m']],n:'De um nó ao seguinte há meio comprimento de onda.'},
  {f:'Tubo fechado: f<sub class="up">n</sub> = n·'+frac('v','4L')+'   (n = 1, 3, 5…)',n:'Só harmônicos ímpares. O fundamental tem a metade da frequência do de um tubo aberto de mesmo comprimento.'}],
 ex:{q:'Uma corda de violão de 0,65 m vibra no modo fundamental, e as ondas nela viajam a 286 m/s. Qual é a frequência da nota?',s:['No fundamental (n = 1) cabe meia onda na corda: λ = 2L = 1,3 m.','f = v/λ = 286/1,3.','<b>f = 220 Hz</b>: a nota lá, uma oitava abaixo do lá de 440 Hz.']},
 probs:[
  ()=>{ const L=pick([.5,.6,.8,1,1.2]), v=pick([120,240,300,360,480]), n=pick([1,2,3]), a=n*v/(2*L), tr=[[n*v/L,'Na corda presa, o fundamental é meia onda: λ = 2L.']]; if(n>1) tr.push([v/(2*L),'Esse é o fundamental. Multiplique pelo número do harmônico.']);
    return NUM(`Uma corda de <b>${F(L)} m</b>, presa nas duas pontas, vibra no <b>${n}º harmônico</b>. As ondas nela viajam a <b>${v} m/s</b>. Qual é a frequência?`,a,'Hz',[`f<sub>n</sub> = n·v/(2L) = ${n} × ${v} / (2 × ${F(L)})`,`f = ${F(a)} Hz`],tr); },
  ()=>{ const L=pick([.34,.5,.85,1.7]), a=340/(2*L);
    return NUM(`Qual é a frequência fundamental de um tubo <b>aberto nas duas pontas</b> com <b>${F(L)} m</b> de comprimento? (som: 340 m/s)`,a,'Hz',[`Tubo aberto, fundamental: λ = 2L = ${F(2*L)} m`,`f = v/λ = 340/${F(2*L)} = ${F(a)} Hz`],[[340/(4*L),'Esse seria o tubo fechado. No aberto, λ = 2L.'],[340/L,'No fundamental cabe meia onda no tubo: λ = 2L.']]); },
  ()=>{ const L=pick([.17,.25,.34,.5,.85]), n=pick([1,3,5]), a=n*340/(4*L), tr=[[n*340/(2*L),'No tubo fechado, o fundamental tem λ = 4L: use f = n·v/(4L).']]; if(n>1) tr.push([340/(4*L),'Esse é o fundamental. Multiplique pelo número do harmônico.']);
    return NUM(`Um tubo de <b>${F(L)} m</b>, fechado numa ponta, emite o <b>${n}º harmônico</b>. Qual é a frequência? (som: 340 m/s)`,a,'Hz',[`Tubo fechado: f<sub>n</sub> = n·v/(4L) = ${n} × 340 / (4 × ${F(L)})`,`f = ${F(a)} Hz`],tr); },
  ()=>{ const n=pick([2,3,4,6]), L=pick([.6,1.2,1.8,2.4]), a=2*L/n;
    return NUM(`Uma corda de <b>${F(L)} m</b>, presa nas pontas, vibra formando <b>${n} fusos</b> (${n} ventres). Qual é o comprimento de onda?`,a,'m',[`Cada fuso é meia onda: ${n} × λ/2 = ${F(L)}`,`λ = 2 × ${F(L)} / ${n} = ${F(a)} m`],[[L/n,'Cada fuso é <b>meia</b> onda, e não uma onda inteira: λ = 2L/n.']]); },
  POOL([['Um tubo fechado numa ponta pode emitir quais harmônicos?',['só os ímpares (1º, 3º, 5º…)','só os pares','todos','só o fundamental'],'A ponta fechada é nó e a aberta é ventre: cabem 1, 3, 5… quartos de onda.'],
   ['Uma cantora estoura uma taça de cristal com a voz. O fenômeno é:',['ressonância','refração','efeito Doppler','difração'],'A voz tem a frequência natural da taça: a amplitude cresce até o vidro quebrar.'],
   ['Ao apertar a corda do violão num traste que deixa a parte que vibra mais curta, o som fica:',['mais agudo','mais grave','mais forte, com a mesma nota','igual'],'f = v/(2L): L menor, f maior.'],
   ['Numa onda estacionária, a distância entre dois nós vizinhos é:',['meio comprimento de onda','um comprimento de onda','um quarto de comprimento de onda','dois comprimentos de onda'],'Cada fuso, de nó a nó, é meia onda.'],
   ['Uma flauta e um violino tocam a mesma nota. O que faz os sons serem diferentes?',['a mistura de harmônicos, o timbre','a frequência fundamental','a velocidade do som no ar','o comprimento de onda da nota'],'A fundamental é a mesma; o que muda é quanto de cada harmônico aparece.']])],
 traps:['Usar λ = L na corda: no fundamental cabe meia onda, λ = 2L.','Esquecer que o tubo fechado só tem harmônicos ímpares.','Confundir nó (ponto parado) com ventre (vibração máxima).'],
 keep:['Corda e tubo aberto: f = n·v/(2L), n = 1, 2, 3…','Tubo fechado: f = n·v/(4L), só n ímpar.','Ressonância: um corpo excitado na sua frequência natural vibra cada vez mais.']}]);

addLessons('opt',null,[
{id:'espectro',t:'Luz e espectro eletromagnético',min:13,
 idea:`<p>A luz é uma <b>onda eletromagnética</b>: um campo elétrico e um campo magnético que oscilam juntos e se sustentam, sem precisar de meio material. No vácuo, todas as ondas eletromagnéticas viajam à mesma velocidade, <b>c = 3×10⁸ m/s</b>, e por isso vale <b>c = λ·f</b>: comprimento de onda menor significa frequência maior.</p>
 <p>O que muda de uma para outra é só a frequência, e essa família inteira forma o <b>espectro eletromagnético</b>: ondas de rádio, micro-ondas, infravermelho, luz visível, ultravioleta, raios X e raios gama. Nossos olhos percebem uma faixa estreitíssima, de cerca de 400 nm (violeta) a 700 nm (vermelho).</p>
 <p>A energia chega em pacotes, os fótons, e cada fóton tem energia proporcional à frequência (você verá E = h·f em Física moderna). Por isso ultravioleta, raios X e raios gama, de frequência alta, conseguem danificar moléculas das células, enquanto ondas de rádio e micro-ondas, por mais intensas, apenas aquecem.</p>`,
 pred:{q:'Qual destas ondas viaja mais rápido no vácuo?',o:['todas viajam à mesma velocidade','os raios X','as ondas de rádio','a luz visível'],a:0,why:'No vácuo, toda onda eletromagnética viaja a c = 3×10⁸ m/s. O que muda de uma para outra é a frequência, e com ela o comprimento de onda.'},
 lab:{sim:'spectrum'},
 tasks:['Vá das ondas de rádio aos raios gama. O que acontece com o comprimento de onda e com a energia de cada fóton?','Encontre a luz visível. Que pedaço da régua ela ocupa?','Qual é o comprimento de onda de um forno de micro-ondas? Compare com o tamanho do forno.'],
 f:[{f:'c = λ·f',s:[['c','velocidade da luz no vácuo: 3×10<sup>8</sup>','m/s'],['λ','comprimento de onda','m'],['f','frequência','Hz']],n:'Em ordem de frequência crescente: rádio, micro-ondas, infravermelho, visível (do vermelho ao violeta), ultravioleta, raios X e gama. Prefixos: n = 10⁻⁹, M = 10⁶, G = 10⁹.'}],
 ex:{q:'Um forno de micro-ondas funciona em 2,45 GHz. Qual é o comprimento dessas ondas?',s:['f = 2,45 GHz = 2,45×10⁹ Hz.','λ = c/f = 3×10⁸ / 2,45×10⁹.','<b>λ ≈ 0,12 m = 12 cm</b>.']},
 probs:[
  ()=>{ const [who,num,mul,un]=pick([['uma rádio FM',100,1e6,'MHz'],['uma rádio AM',1,1e6,'MHz'],['um roteador Wi-Fi',5,1e9,'GHz'],['um celular',1.5,1e9,'GHz'],['uma rádio FM',90,1e6,'MHz'],['um radar',10,1e9,'GHz']]), f=num*mul, a=3e8/f;
    return NUM(`${who[0].toUpperCase()+who.slice(1)} transmite em <b>${F(num)} ${un}</b>. Qual é o comprimento de onda? (c = 3×10⁸ m/s)`,a,'m',[`f = ${F(num)} ${un} = ${F(f)} Hz`,`λ = c/f = 3×10⁸ / ${F(f)} = ${F(a)} m`],[[3e8/num,`Converta ${un} para hertz: ${un[0]} = 10<sup>${mul===1e6?6:9}</sup>.`],[f/3e8,'λ = c/f: a velocidade vai em cima.']]); },
  ()=>{ const nm=pick([400,480,500,600,625]), a=3e8/(nm*1e-9);
    return NUM(`Uma luz visível tem comprimento de onda de <b>${nm} nm</b>. Qual é a frequência dela? (c = 3×10⁸ m/s)`,a,'Hz',[`λ = ${nm} nm = ${nm}×10⁻⁹ m`,`f = c/λ = 3×10⁸ / ${nm}×10⁻⁹ = ${F(a)} Hz`],[[3e8/nm,'Converta nanômetros para metros (× 10⁻⁹).']],'Digite em notação científica, como 5e14.'); },
  ()=>{ const [what,d]=pick([['do Sol até a Terra',1.5e11],['da Lua até a Terra',3.84e8],['de um satélite geoestacionário até a Terra',3.6e7],['de Marte até a Terra, no ponto mais próximo',5.4e10]]), a=d/3e8;
    return NUM(`Quanto tempo a luz leva para ir <b>${what}</b>, uma distância de ${F(d)} m? (c = 3×10⁸ m/s)`,a,'s',[`t = d/c = ${F(d)} / 3×10⁸`,`t = ${F(a)} s`],[[d*3e8,'Tempo = distância ÷ velocidade.']]); },
  POOL([['Em ordem crescente de frequência:',['rádio, micro-ondas, luz visível, raios X','raios X, luz visível, micro-ondas, rádio','luz visível, rádio, raios X, micro-ondas','micro-ondas, rádio, raios X, luz visível'],'A frequência cresce do rádio para o gama; o comprimento de onda faz o contrário.'],
   ['Por que o protetor solar precisa barrar o ultravioleta, mas ninguém usa protetor contra o sinal do celular?',['cada fóton de UV tem energia suficiente para danificar células; os de micro-ondas não','o UV é mais rápido que as micro-ondas','o sinal do celular não é onda eletromagnética','o UV tem comprimento de onda maior'],'A energia de cada fóton cresce com a frequência, e o UV tem frequência muito maior.'],
   ['Qual cor visível tem o maior comprimento de onda?',['vermelho','violeta','verde','azul'],'Vermelho fica perto de 700 nm; violeta, perto de 400 nm.'],
   ['O calor que você sente no rosto perto de uma fogueira, sem tocar nela, chega principalmente como:',['radiação infravermelha','ultravioleta','ondas de rádio','raios X'],'Corpos quentes emitem sobretudo infravermelho.'],
   ['A luz, ao contrário do som:',['propaga-se no vácuo','precisa de um meio material','é uma onda longitudinal','viaja a 340 m/s'],'Ondas eletromagnéticas não precisam de meio: é assim que a luz das estrelas chega até nós.']])],
 traps:['Achar que raios X ou gama viajam mais rápido que a luz: no vácuo, todas as ondas eletromagnéticas viajam a c.','Esquecer de converter nm, MHz ou GHz para o SI.','Achar que toda radiação é perigosa: rádio e micro-ondas não danificam as células como o UV e os raios X.'],
 keep:['c = λ·f = 3×10⁸ m/s para toda onda eletromagnética no vácuo.','Rádio → micro-ondas → infravermelho → visível → UV → raios X → gama: frequência e energia crescem.','Visível: de 400 nm (violeta) a 700 nm (vermelho).']}]);

addLessons('mag','magnetismo',[
{id:'campofio',t:'Campo magnético de correntes',min:14,
 idea:`<p>Oersted viu que um fio com corrente desvia a agulha de uma bússola. O campo magnético de um <b>fio reto e longo</b> forma circunferências em volta dele, e o sentido é dado pela <b>regra da mão direita</b>: com o polegar no sentido da corrente, os outros dedos se curvam no sentido do campo.</p>
 <p>A intensidade diminui com a distância: <b>B = μ₀·i/(2π·d)</b>, em que μ₀ = 4π×10⁻⁷ T·m/A é a permeabilidade magnética do vácuo. Dobrar a corrente dobra o campo; dobrar a distância reduz o campo à metade.</p>
 <p>Enrolando o fio, os campos de cada volta se somam. No centro de uma <b>espira</b> circular de raio R, B = μ₀·i/(2R). Dentro de um <b>solenoide</b> (uma bobina comprida) com N espiras num comprimento ℓ, o campo é quase uniforme: B = μ₀·N·i/ℓ. Com um núcleo de ferro dentro, o campo fica centenas de vezes mais forte: é o <b>eletroímã</b> dos guindastes de ferro-velho, das campainhas, dos motores e dos aparelhos de ressonância magnética.</p>`,
 pred:{q:'Uma bússola está perto de um fio com corrente. Você a afasta para o dobro da distância. O campo magnético do fio nesse ponto fica:',o:['com a metade da intensidade','com um quarto da intensidade','com o dobro da intensidade','igual'],a:0,why:'B = μ₀·i/(2π·d): o campo de um fio longo cai com 1/d, e não com 1/d². Dobro da distância, metade do campo.'},
 lab:{sim:'wireB'},
 tasks:['Arraste a sonda para o dobro da distância. O que acontece com B?','Inverta o sentido da corrente. O que muda nas bússolas?','A que distância de um fio com 10 A o campo fica igual ao da Terra (≈ 50 μT)?'],
 f:[{f:'B = '+frac('μ₀·i','2π·d'),s:[['B','campo magnético','T (tesla)'],['μ₀','permeabilidade do vácuo: 4π×10<sup>−7</sup>','T·m/A'],['i','corrente elétrica','A'],['d','distância até o fio','m']],n:'Fio reto e longo. Atalho: μ₀/(2π) = 2×10⁻⁷, então B = 2×10⁻⁷·i/d.'},
  {f:'Espira: B = '+frac('μ₀·i','2R')+'      Solenoide: B = '+frac('μ₀·N·i','ℓ'),n:'R: raio da espira. N: número de espiras do solenoide; ℓ: comprimento dele.'}],
 ex:{q:'Um fio longo conduz 20 A. Qual é o campo magnético a 10 cm dele?',s:['d = 10 cm = 0,1 m.','B = 2×10⁻⁷ × 20 / 0,1.','<b>B = 4×10⁻⁵ T = 40 μT</b>, quase o valor do campo magnético da Terra: por isso uma bússola perto do fio desvia.']},
 probs:[
  ()=>{ const i=pick([2,5,10,20,50]), d=pick([1,2,4,5,10,20]), a=20*i/d;
    return NUM(`Um fio reto e longo conduz <b>${i} A</b>. Qual é o campo magnético a <b>${d} cm</b> dele, em microtesla (μT)?`,a,'μT',[`d = ${d} cm = ${F(d/100)} m`,`B = 2×10⁻⁷ × ${i} / ${F(d/100)} = ${F(a*1e-6)} T`,`B = ${F(a)} μT`],[[.2*i/d,'Converta a distância para metros antes de dividir.'],[2e-7*i*(d/100)*1e6,'A distância <b>divide</b>: mais longe, campo menor.']],'B = 2×10⁻⁷·i/d, com d em metros. 1 μT = 10⁻⁶ T.'); },
  ()=>{ const B0=pick([10,20,40,60]), K=pick([2,3,4]), M=pick([1,2,3]), a=B0*M/K;
    return NUM(`A uma certa distância de um fio, o campo magnético vale <b>${B0} μT</b>. Qual será o campo a uma distância <b>${K} vezes maior</b>${M>1?`, com a corrente <b>${M} vezes maior</b>`:', com a mesma corrente'}?`,a,'μT',[`B é proporcional a i/d`,`B = ${B0} × ${M}/${K} = ${F(a)} μT`],[[B0*M/(K*K),'O campo de um fio cai com 1/d, e não com 1/d².'],[B0*M*K,'Mais longe, o campo <b>diminui</b>.']]); },
  ()=>{ const N=pick([200,500,1000]), l=pick([.1,.2,.5]), i=pick([1,2,5]), a=4*Math.PI*1e-7*N*i/l*1000;
    return NUM(`Um solenoide de <b>${F(l*100)} cm</b> de comprimento tem <b>${N} espiras</b> e conduz <b>${i} A</b>. Qual é o campo magnético dentro dele, em militesla (mT)? (μ₀ = 4π×10⁻⁷ T·m/A; π ≈ 3,14)`,a,'mT',[`B = μ₀·N·i/ℓ = 4π×10⁻⁷ × ${N} × ${i} / ${F(l)}`,`B = ${F(a/1000)} T = ${F(a)} mT`],[[4*Math.PI*1e-4*N*i,'Divida pelo comprimento do solenoide, em metros.']]); },
  ()=>{ const R=pick([2,5,10]), i=pick([1,2,5,10]), a=4*Math.PI*1e-7*i/(2*R/100)*1e6;
    return NUM(`Uma espira circular de raio <b>${R} cm</b> conduz <b>${i} A</b>. Qual é o campo no centro dela, em μT? (μ₀ = 4π×10⁻⁷ T·m/A; π ≈ 3,14)`,a,'μT',[`R = ${F(R/100)} m`,`B = μ₀·i/(2R) = 4π×10⁻⁷ × ${i} / (2 × ${F(R/100)})`,`B = ${F(a)} μT`],[[2*a,'No centro da espira, B = μ₀·i/(2R): faltou o 2 do denominador.'],[a/Math.PI,'Essa é a fórmula do fio reto. Na espira, B = μ₀·i/(2R).']]); },
  POOL([['As linhas do campo magnético de um fio reto e longo com corrente são:',['circunferências em volta do fio','retas que saem do fio','retas paralelas ao fio','espirais que se afastam do fio'],'O campo "abraça" o fio, no sentido dado pela regra da mão direita.'],
   ['Para deixar um eletroímã mais forte, podemos:',['aumentar a corrente ou o número de espiras, ou pôr um núcleo de ferro','diminuir a corrente','desenrolar a bobina','trocar o fio de cobre por um de plástico'],'B = μ₀·N·i/ℓ, e o ferro multiplica o campo.'],
   ['Num fio vertical, a corrente sobe. Olhando de frente, num ponto à direita do fio, o campo magnético aponta:',['para dentro da tela','para fora da tela','para cima','para a direita'],'Polegar para cima: os dedos entram na tela do lado direito do fio e saem do lado esquerdo.'],
   ['Dois fios paralelos com correntes no mesmo sentido:',['se atraem','se repelem','não interagem','giram um em volta do outro'],'Cada fio está no campo do outro e sofre força magnética: correntes de mesmo sentido se atraem.']])],
 traps:['Achar que o campo do fio cai com 1/d², como na gravitação e na lei de Coulomb: cai com 1/d.','Esquecer de passar centímetros para metros.','Confundir as fórmulas do fio (2π·d), da espira (2R) e do solenoide (N/ℓ).'],
 keep:['Fio reto: B = μ₀·i/(2π·d), linhas circulares, regra da mão direita.','Espira: B = μ₀·i/(2R). Solenoide: B = μ₀·N·i/ℓ.','μ₀ = 4π×10⁻⁷ T·m/A, e μ₀/(2π) = 2×10⁻⁷.']}]);
